name: Flutter for Beginners
name_cn: Flutter 入门指南
slug: flutter-for-beginners
toc:
- - '#'
  - 1. 开始使用
- - '##'
  - 1.1 在 Windows 上安装 Flutter SDK
- - '###'
  - 问题
- - '###'
  - 解决方案
- - '###'
  - 讨论
- - '##'
  - 1.2 在 Linux 上安装 Flutter SDK
- - '###'
  - 问题
- - '###'
  - 解决方案
- - '###'
  - 讨论
- - '##'
  - 1.3 在 macOS 上安装 Flutter SDK
- - '###'
  - 问题
- - '###'
  - 解决方案
- - '###'
  - 讨论
- - '##'
  - 1.4 设置 iOS 平台
- - '###'
  - 问题
- - '###'
  - 解决方案
- - '###'
  - 讨论
- - '##'
  - 1.5 设置 iOS 模拟器
- - '###'
  - 问题
- - '###'
  - 解决方案
- - '###'
  - 讨论
- - '##'
  - 1.6 设置 iOS 真机设备
- - '###'
  - 问题
- - '###'
  - 解决方案
- - '###'
  - 讨论
- - '##'
  - 1.7 搭建 Android 平台
- - '###'
  - 问题
- - '###'
  - 解决方案
- - '###'
  - 讨论
- - '##'
  - 1.8 搭建 Android 模拟器
- - '###'
  - 问题
- - '###'
  - 解决方案
- - '###'
  - 讨论
- - '##'
  - 1.9 搭建 Android 设备
- - '###'
  - 问题
- - '###'
  - 解决方案
- - '###'
  - 讨论
- - '##'
  - 1.10 使用命令行创建 Flutter 应用
- - '###'
  - 问题
- - '###'
  - 解决方案
- - '###'
  - 讨论
- - '##'
  - 1.11 使用 Android Studio 创建 Flutter 应用
- - '###'
  - 问题
- - '###'
  - 解决方案
- - '###'
  - 讨论
- - '##'
  - 1.12 使用 VS Code 创建 Flutter 应用
- - '###'
  - 问题
- - '###'
  - 解决方案
- - '###'
  - 讨论
- - '##'
  - 1.13 运行 Flutter 应用
- - '###'
  - 问题
- - '###'
  - 解决方案
- - '###'
  - 讨论
- - '##'
  - 1.14 理解 Flutter 应用的代码结构
- - '###'
  - 问题
- - '###'
  - 解决方案
- - '###'
  - 讨论
- - '##'
  - 1.15 修复 Flutter SDK 的配置问题
- - '###'
  - 问题
- - '###'
  - 解决方案
- - '###'
  - 讨论
- - '##'
  - 1.16 总结
- - '#'
  - 2. 了解工具
- - '##'
  - 2.1 使用 Dart Observatory
- - '###'
  - 问题
- - '###'
  - 解决方案
- - '###'
  - 讨论
- - '###'
  - 注意
- - '##'
  - 2.2 使用热重载和热重启
- - '###'
  - 问题
- - '###'
  - 解决方案
- - '###'
  - 讨论
- - '##'
  - 2.3 升级 Flutter SDK
- - '###'
  - 问题
- - '###'
  - 解决方案
- - '###'
  - 讨论
- - '##'
  - 2.4 在 Android Studio 中调试 Flutter 应用
- - '###'
  - 问题
- - '###'
  - 解决方案
- - '###'
  - 讨论
- - '##'
  - 2.5 在 Android Studio 中查看 Flutter 应用的轮廓
- - '###'
  - 问题
- - '###'
  - 解决方案
- - '###'
  - 讨论
- - '##'
  - 2.6 在 VS Code 中调试 Flutter 应用
- - '###'
  - 问题
- - '###'
  - 解决方案
- - '###'
  - 讨论
- - '##'
  - 2.7 创建 Flutter 项目
- - '###'
  - 问题
- - '###'
  - 解决方案
- - '###'
  - 讨论
- - '####'
  - 项目类型
- - '####'
  - 代码示例
- - '####'
  - 项目配置
- - '####'
  - 启用或禁用功能
- - '##'
  - 2.8 运行 Flutter 应用
- - '###'
  - 问题
- - '###'
  - 解决方案
- - '###'
  - 讨论
- - '####'
  - 不同的构建风格
- - '####'
  - 其他选项
- - '##'
  - 2.9 构建 Flutter 应用二进制文件
- - '###'
  - 问题
- - '###'
  - 解决方案
- - '###'
  - 讨论
- - '####'
  - 为 Android 构建 APK 文件
- - '####'
  - 为 iOS 构建
- - '##'
  - 2.10 安装 Flutter 应用
- - '###'
  - 问题
- - '###'
  - 解决方案
- - '###'
  - 讨论
- - '##'
  - 2.11 管理包
- - '###'
  - 问题
- - '###'
  - 解决方案
- - '###'
  - 讨论
- - '###'
  - 注意
- - '##'
  - 2.12 运行 Flutter 测试
- - '###'
  - 问题
- - '###'
  - 解决方案
- - '###'
  - 讨论
- - '####'
  - 筛选要运行的测试
- - '####'
  - 测试覆盖率
- - '####'
  - 调试测试
- - '####'
  - 其他选项
- - '##'
  - 2.13 分析代码
- - '###'
  - 问题
- - '###'
  - 解决方案
- - '###'
  - 讨论
- - '##'
  - 2.14 管理模拟器
- - '###'
  - 问题
- - '###'
  - 解决方案
- - '###'
  - 讨论
- - '##'
  - 2.15 截取屏幕截图
- - '###'
  - 问题
- - '###'
  - 解决方案
- - '###'
  - 讨论
- - '##'
  - 2.16 连接到正在运行的应用
- - '###'
  - 问题
- - '###'
  - 解决方案
- - '###'
  - 讨论
- - '##'
  - 2.17 追踪正在运行的 Flutter 应用
- - '###'
  - 问题
- - '###'
  - 解决方案
- - '###'
  - 讨论
- - '##'
  - 2.18 配置 Flutter SDK
- - '###'
  - 问题
- - '###'
  - 解决方案
- - '###'
  - 讨论
- - '##'
  - 2.19 显示应用日志
- - '###'
  - 问题
- - '###'
  - 解决方案
- - '###'
  - 讨论
- - '##'
  - 2.20 格式化源代码
- - '###'
  - 问题
- - '###'
  - 解决方案
- - '###'
  - 讨论
- - '##'
  - 2.21 列出已连接的设备
- - '###'
  - 问题
- - '###'
  - 解决方案
- - '###'
  - 讨论
- - '##'
  - 2.22 运行集成测试
- - '###'
  - 问题
- - '###'
  - 解决方案
- - '###'
  - 讨论
- - '##'
  - 2.23 启用 Flutter SDK 命令的 Bash 补全功能
- - '###'
  - 问题
- - '###'
  - 解决方案
- - '###'
  - 讨论
- - '##'
  - 2.24 清理 Flutter 应用的构建文件
- - '###'
  - 问题
- - '###'
  - 解决方案
- - '###'
  - 讨论
- - '##'
  - 2.25 管理 Flutter SDK 缓存
- - '###'
  - 问题
- - '###'
  - 解决方案
- - '###'
  - 讨论
- - '##'
  - 2.26 总结
- - '#'
  - 3. Dart 核心知识
- - '##'
  - 3.1 理解内置类型
- - '###'
  - 问题
- - '###'
  - 解决方案
- - '###'
  - 讨论
- - '####'
  - 数字
- - '####'
  - 字符串
- - '####'
  - 布尔值
- - '####'
  - 列表和映射
- - '####'
  - Runes
- - '####'
  - 符号
- - '##'
  - 3.2 使用枚举类型
- - '###'
  - 问题
- - '###'
  - 解决方案
- - '###'
  - 讨论
- - '##'
  - 3.3 使用动态类型
- - '###'
  - 问题
- - '###'
  - 解决方案
- - '###'
  - 讨论
- - '##'
  - 3.4 理解函数
- - '###'
  - 问题
- - '###'
  - 解决方案
- - '###'
  - 讨论
- - '##'
  - 3.5 使用 Typedefs
- - '###'
  - 问题
- - '###'
  - 解决方案
- - '###'
  - 讨论
- - '##'
  - 3.6 使用级联运算符
- - '###'
  - 问题
- - '###'
  - 解决方案
- - '###'
  - 讨论
- - '##'
  - 3.7 重写运算符
- - '###'
  - 问题
- - '###'
  - 解决方案
- - '###'
  - 讨论
- - '##'
  - 3.8 使用构造函数
- - '###'
  - 问题
- - '###'
  - 解决方案
- - '###'
  - 讨论
- - '##'
  - 3.9 扩展类
- - '###'
  - 问题
- - '###'
  - 解决方案
- - '###'
  - 讨论
- - '##'
  - 3.10 向类添加特性
- - '###'
  - 问题
- - '###'
  - 解决方案
- - '###'
  - 讨论
- - '##'
  - 3.11 使用接口
- - '###'
  - 问题
- - '###'
  - 解决方案
- - '###'
  - 讨论
- - '##'
  - 3.12 使用泛型
- - '###'
  - 问题
- - '###'
  - 解决方案
- - '###'
  - 讨论
- - '##'
  - 3.13 使用库
- - '###'
  - 问题
- - '###'
  - 解决方案
- - '###'
  - 讨论
- - '##'
  - 3.14 使用异常
- - '###'
  - 问题
- - '###'
  - 解决方案
- - '###'
  - 讨论
- - '####'
  - 报告失败
- - '####'
  - 捕获异常
- - '##'
  - 3.15 总结
- - '#'
  - 4. 部件基础
- - '##'
  - 4.1 理解部件
- - '###'
  - 问题
- - '###'
  - 解决方案
- - '###'
  - 讨论
- - '##'
  - 4.2 理解 `BuildContext`
- - '###'
  - 问题
- - '###'
  - 解决方案
- - '###'
  - 讨论
- - '##'
  - 4.3 理解无状态小部件
- - '###'
  - 问题
- - '###'
  - 解决方案
- - '###'
  - 讨论
- - '##'
  - 4.4 理解有状态小部件
- - '###'
  - 问题
- - '###'
  - 解决方案
- - '###'
  - 讨论
- - '##'
  - 4.5 理解 InheritedWidget
- - '###'
  - 问题
- - '###'
  - 解决方案
- - '###'
  - 讨论
- - '##'
  - 4.6 显示文本
- - '###'
  - 问题
- - '###'
  - 解决方案
- - '###'
  - 讨论
- - '####'
  - Text
- - '####'
  - '`TextSpan`'
- - '####'
  - '`RichText`'
- - '##'
  - 4.7 为文本应用样式
- - '###'
  - 问题
- - '###'
  - 解决方案
- - '###'
  - 讨论
- - '##'
  - 4.8 显示图像
- - '###'
  - 问题
- - '###'
  - 解决方案
- - '###'
  - 讨论
- - '##'
  - 4.9 显示图标
- - '###'
  - 问题
- - '###'
  - 解决方案
- - '###'
  - 讨论
- - '##'
  - 4.10 使用带文字的按钮
- - '###'
  - 问题
- - '###'
  - 解决方案
- - '###'
  - 讨论
- - '##'
  - 4.11 使用带图标的按钮
- - '###'
  - 问题
- - '###'
  - 解决方案
- - '###'
  - 讨论
- - '##'
  - 4.12 添加占位符
- - '###'
  - 问题
- - '###'
  - 解决方案
- - '###'
  - 讨论
- - '##'
  - 4.13 总结
- - '#'
  - 5. 布局小部件
- - '##'
  - 5.1 理解 Flutter 中的布局
- - '###'
  - 问题
- - '###'
  - 解决方案
- - '###'
  - 讨论
- - '####'
  - RenderObject
- - '####'
  - BoxConstraints
- - '####'
  - 布局算法
- - '###'
  - 布局组件
- - '##'
  - 5.2 将组件居中放置
- - '###'
  - 问题
- - '###'
  - 解决方案
- - '###'
  - 讨论
- - '##'
  - 5.3 对齐组件
- - '###'
  - 问题
- - '###'
  - 解决方案
- - '###'
  - 讨论
- - '##'
  - 5.4 对组件施加约束
- - '###'
  - 问题
- - '###'
  - 解决方案
- - '###'
  - 讨论
- - '##'
  - 5.5 不对 Widget 施加约束
- - '###'
  - 问题
- - '###'
  - 解决方案
- - '###'
  - 讨论
- - '##'
  - 5.6 忽略父组件时对 Widget 施加约束
- - '###'
  - 问题
- - '###'
  - 解决方案
- - '###'
  - 讨论
- - '##'
  - 5.7 限制大小以允许子 Widget 溢出
- - '###'
  - 问题
- - '###'
  - 解决方案
- - '###'
  - 讨论
- - '##'
  - 5.8 在无界时限制 Widget 大小
- - '###'
  - 问题
- - '###'
  - 解决方案
- - '###'
  - 讨论
- - '##'
  - 5.9 缩放与定位 Widget
- - '###'
  - 问题
- - '###'
  - 解决方案
- - '###'
  - 讨论
- - '##'
  - 5.10 旋转 Widget
- - '###'
  - 问题
- - '###'
  - 解决方案
- - '###'
  - 讨论
- - '##'
  - 5.11 为 Widget 添加内边距
- - '###'
  - 问题
- - '###'
  - 解决方案
- - '###'
  - 讨论
- - '##'
  - 5.12 按宽高比调整 Widget 尺寸
- - '###'
  - 问题
- - '###'
  - 解决方案
- - '###'
  - 讨论
- - '##'
  - 5.13 变换组件
- - '###'
  - 问题
- - '###'
  - 解决方案
- - '###'
  - 讨论
- - '##'
  - 5.14 在组件上控制不同的布局方面
- - '###'
  - 问题
- - '###'
  - 解决方案
- - '###'
  - 讨论
- - '##'
  - 5.15 实现 Flex 框布局
- - '###'
  - 问题
- - '###'
  - 解决方案
- - '###'
  - 讨论
- - '####'
  - 弹性盒子布局算法
- - '####'
  - Flexible
- - '##'
  - 5.16 显示重叠的小部件
- - '###'
  - 问题
- - '###'
  - 解决方案
- - '###'
  - 讨论
- - '##'
  - 5.17 在多行中显示组件
- - '###'
  - 问题
- - '###'
  - 解决方案
- - '###'
  - 讨论
- - '##'
  - 5.18 创建自定义单子布局
- - '###'
  - 问题
- - '###'
  - 解决方案
- - '###'
  - 讨论
- - '##'
  - 5.19 创建自定义多子布局
- - '###'
  - 问题
- - '###'
  - 解决方案
- - '###'
  - 讨论
- - '##'
  - 5.20 总结
- - '#'
  - 6. 表单组件
- - '##'
  - 6.1 收集文本输入
- - '###'
  - 问题
- - '###'
  - 解决方案
- - '###'
  - 讨论
- - '####'
  - 使用 TextEditingController
- - '####'
  - 使用 `TextEditingController` 的监听器
- - '####'
  - 使用回调函数
- - '##'
  - 6.2 自定义文本输入键盘
- - '###'
  - 问题
- - '###'
  - 解决方案
- - '###'
  - 讨论
- - '##'
  - 6.3 在 Material Design 中为文本输入添加装饰
- - '###'
  - 问题
- - '###'
  - 解决方案
- - '###'
  - 讨论
- - '####'
  - 边框
- - '####'
  - 前缀和后缀
- - '####'
  - 文本
- - '##'
  - 6.4 设置文本长度限制
- - '###'
  - 问题
- - '###'
  - 解决方案
- - '###'
  - 讨论
- - '##'
  - 6.5 选择文本
- - '###'
  - 问题
- - '###'
  - 解决方案
- - '###'
  - 讨论
- - '##'
  - 6.6 格式化文本
- - '###'
  - 问题
- - '###'
  - 解决方案
- - '###'
  - 讨论
- - '##'
  - 6.7 选择单个值
- - '###'
  - 问题
- - '###'
  - 解决方案
- - '###'
  - 讨论
- - '##'
  - 6.8 从下拉列表中选择单个值
- - '###'
  - 问题
- - '###'
  - 解决方案
- - '###'
  - 讨论
- - '##'
  - 6.9 选择多个值
- - '###'
  - 问题
- - '###'
  - 解决方案
- - '###'
  - 讨论
- - '##'
  - 6.10 切换开/关状态
- - '###'
  - 问题
- - '###'
  - 解决方案
- - '###'
  - 讨论
- - '##'
  - 6.11 从范围中选择值
- - '###'
  - 问题
- - '###'
  - 解决方案
- - '###'
  - 讨论
- - '##'
  - 6.12 使用 Chips
- - '###'
  - 问题
- - '###'
  - 解决方案
- - '###'
  - 讨论
- - '##'
  - 6.13 选择日期和时间
- - '###'
  - 问题
- - '###'
  - 解决方案
- - '###'
  - 讨论
- - '##'
  - 6.14 包装表单字段
- - '###'
  - 问题
- - '###'
  - 解决方案
- - '###'
  - 讨论
- - '##'
  - 6.15 创建表单
- - '###'
  - 问题
- - '###'
  - 解决方案
- - '###'
  - 讨论
- - '##'
  - 6.16 小结
- - '#'
  - 7. 常用控件
- - '##'
  - 7.1 显示项目列表
- - '###'
  - 问题
- - '###'
  - 解决方案
- - '###'
  - 讨论
- - '####'
  - 带有静态子控件的 ListView
- - '####'
  - 带有项目构建器的 ListView
- - '####'
  - ListTile
- - '##'
  - 7.2 在网格中显示项目
- - '###'
  - 问题
- - '###'
  - 解决方案
- - '###'
  - 讨论
- - '##'
  - 7.3 显示表格数据
- - '###'
  - 问题
- - '###'
  - 解决方案
- - '###'
  - 讨论
- - '##'
  - 7.4 构建 Material Design 页面框架
- - '###'
  - 问题
- - '###'
  - 解决方案
- - '###'
  - 讨论
- - '####'
  - 应用栏
- - '####'
  - 浮动操作按钮
- - '####'
  - 抽屉
- - '####'
  - 底部应用栏
- - '####'
  - 底部导航栏
- - '####'
  - 底部抽屉面板
- - '####'
  - Scaffold 状态
- - '####'
  - SnackBar
- - '##'
  - 7.5 构建 iOS 页面框架
- - '###'
  - 问题
- - '###'
  - 解决方案
- - '###'
  - 讨论
- - '##'
  - 7.6 在 Material Design 中创建标签布局
- - '###'
  - 问题
- - '###'
  - 解决方案
- - '###'
  - 讨论
- - '##'
  - 7.7 在 iOS 中实现标签布局
- - '###'
  - 问题
- - '###'
  - 解决方案
- - '###'
  - 讨论
- - '##'
  - 7.8 总结
- - '#'
  - 8. 页面导航
- - '##'
  - 8.1 实现基本页面导航
- - '###'
  - 问题
- - '###'
  - 解决方案
- - '###'
  - 讨论
- - '##'
  - 8.2 使用命名路由
- - '###'
  - 问题
- - '###'
  - 解决方案
- - '###'
  - 讨论
- - '##'
  - 8.3 在路由之间传递数据
- - '###'
  - 问题
- - '###'
  - 解决方案
- - '###'
  - 讨论
- - '##'
  - 8.4 实现动态路由匹配
- - '###'
  - 问题
- - '###'
  - 解决方案
- - '###'
  - 讨论
- - '##'
  - 8.5 处理未知路由
- - '###'
  - 问题
- - '###'
  - 解决方案
- - '###'
  - 讨论
- - '##'
  - 8.6 显示 Material Design 对话框
- - '###'
  - 问题
- - '###'
  - 解决方案
- - '###'
  - 讨论
- - '##'
  - 8.7 显示 iOS 对话框
- - '###'
  - 问题
- - '###'
  - 解决方案
- - '###'
  - 讨论
- - '##'
  - 8.8 显示 iOS 操作面板
- - '###'
  - 问题
- - '###'
  - 解决方案
- - '###'
  - 讨论
- - '##'
  - 8.9 显示 Material Design 菜单
- - '###'
  - 问题
- - '###'
  - 解决方案
- - '###'
  - 讨论
- - '##'
  - 8.10 使用嵌套导航器管理复杂的页面流程
- - '###'
  - 问题
- - '###'
  - 解决方案
- - '###'
  - 讨论
- - '##'
  - 8.11 观察导航器状态变化
- - '###'
  - 问题
- - '###'
  - 解决方案
- - '###'
  - 讨论
- - '##'
  - 8.12 阻止路由被弹出
- - '###'
  - 问题
- - '###'
  - 解决方案
- - '###'
  - 讨论
- - '##'
  - 8.13 总结
- - '#'
  - 9. 服务交互
- - '##'
  - 9.1 处理 Futures
- - '###'
  - 问题
- - '###'
  - 解决方案
- - '###'
  - 讨论
- - '##'
  - 9.2 使用 async 和 await 处理 Futures
- - '###'
  - 问题
- - '###'
  - 解决方案
- - '###'
  - 讨论
- - '##'
  - 9.3 创建 Futures
- - '###'
  - 问题
- - '###'
  - 解决方案
- - '###'
  - 讨论
- - '##'
  - 9.4 使用 Streams
- - '###'
  - 问题
- - '###'
  - 解决方案
- - '###'
  - 讨论
- - '####'
  - 流订阅
- - '###'
  - 流转换
- - '##'
  - 9.5 创建流
- - '###'
  - 问题
- - '###'
  - 解决方案
- - '###'
  - 讨论
- - '##'
  - 9.6 基于流和 Future 构建小部件
- - '###'
  - 问题
- - '###'
  - 解决方案
- - '###'
  - 讨论
- - '##'
  - 9.7 处理简单 JSON 数据
- - '###'
  - 问题
- - '###'
  - 解决方案
- - '###'
  - 讨论
- - '##'
  - 9.8 处理复杂 JSON 数据
- - '###'
  - 问题
- - '###'
  - 解决方案
- - '###'
  - 讨论
- - '##'
  - 9.9 处理 XML 数据
- - '###'
  - 问题
- - '###'
  - 解决方案
- - '###'
  - 讨论
- - '####'
  - 解析 XML 文档
- - '####'
  - 构建 XML 文档
- - '##'
  - 9.10 处理 HTML 数据
- - '###'
  - 问题
- - '###'
  - 解决方案
- - '###'
  - 讨论
- - '##'
  - 9.11 发送 HTTP 请求
- - '###'
  - 问题
- - '###'
  - 解决方案
- - '###'
  - 讨论
- - '##'
  - 9.12 连接到 WebSocket
- - '###'
  - 问题
- - '###'
  - 解决方案
- - '###'
  - 讨论
- - '##'
  - 9.13 连接到 Socket
- - '###'
  - 问题
- - '###'
  - 解决方案
- - '###'
  - 讨论
- - '##'
  - 9.14 与基于 JSON 的 REST 服务交互
- - '###'
  - 问题
- - '###'
  - 解决方案
- - '###'
  - 讨论
- - '##'
  - 9.15 与 gRPC 服务交互
- - '###'
  - 问题
- - '###'
  - 解决方案
- - '###'
  - 讨论
- - '##'
  - 9.16 总结
- - '#'
  - 10. 状态管理
- - '##'
  - 10.1 使用有状态组件管理状态
- - '###'
  - 问题
- - '###'
  - 解决方案
- - '###'
  - 讨论
- - '##'
  - 10.2 使用继承 Widget 管理状态
- - '###'
  - 问题
- - '###'
  - 解决方案
- - '###'
  - 讨论
- - '##'
  - 10.3 使用继承模型管理状态
- - '###'
  - 问题
- - '###'
  - 解决方案
- - '###'
  - 讨论
- - '##'
  - 10.4 使用继承通知器管理状态
- - '###'
  - 问题
- - '###'
  - 解决方案
- - '###'
  - 讨论
- - '##'
  - 10.5 使用作用域模型管理状态
- - '###'
  - 问题
- - '###'
  - 解决方案
- - '###'
  - 讨论
- - '##'
  - 10.6 使用 Bloc 管理状态
- - '###'
  - 问题
- - '###'
  - 解决方案
- - '###'
  - 讨论
- - '##'
  - 10.7 使用 Redux 管理状态
- - '###'
  - 问题
- - '###'
  - 解决方案
- - '###'
  - 讨论
- - '##'
  - 10.8 使用 Mobx 管理状态
- - '###'
  - 问题
- - '###'
  - 解决方案
- - '###'
  - 讨论
- - '##'
  - 10.9 总结
- - '#'
  - 11. 动画
- - '##'
  - 11.1 创建简单动画
- - '###'
  - 问题
- - '###'
  - 解决方案
- - '###'
  - 讨论
- - '##'
  - 11.2 使用线性插值创建动画
- - '###'
  - 问题
- - '###'
  - 解决方案
- - '###'
  - 讨论
- - '##'
  - 11.3 创建曲线动画
- - '###'
  - 问题
- - '###'
  - 解决方案
- - '###'
  - 讨论
- - '##'
  - 11.4 链式组合补间动画
- - '###'
  - 问题
- - '###'
  - 解决方案
- - '###'
  - 讨论
- - '##'
  - 11.5 创建补间动画序列
- - '###'
  - 问题
- - '###'
  - 解决方案
- - '###'
  - 讨论
- - '##'
  - 11.6 运行同步动画
- - '###'
  - 问题
- - '###'
  - 解决方案
- - '###'
  - 讨论
- - '##'
  - 11.7 创建交错动画
- - '###'
  - 问题
- - '###'
  - 解决方案
- - '###'
  - 讨论
- - '##'
  - 11.8 创建 Hero 动画
- - '###'
  - 问题
- - '###'
  - 解决方案
- - '###'
  - 讨论
- - '##'
  - 11.9 使用通用过渡动画
- - '###'
  - 问题
- - '###'
  - 解决方案
- - '###'
  - 讨论
- - '##'
  - 11.10 创建物理仿真
- - '###'
  - 问题
- - '###'
  - 解决方案
- - '###'
  - 讨论
- - '##'
  - 11.11 总结
- - '#'
  - 12. 平台集成
- - '##'
  - 12.1 读写文件
- - '###'
  - 问题
- - '###'
  - 解决方案
- - '###'
  - 讨论
- - '##'
  - 12.2 存储键值对
- - '###'
  - 问题
- - '###'
  - 解决方案
- - '###'
  - 讨论
- - '##'
  - 12.3 编写平台特定代码
- - '###'
  - 问题
- - '###'
  - 解决方案
- - '###'
  - 讨论
- - '##'
  - 12.4 创建插件
- - '###'
  - 问题
- - '###'
  - 解决方案
- - '###'
  - 讨论
- - '##'
  - 12.5 显示网页
- - '###'
  - 问题
- - '###'
  - 解决方案
- - '###'
  - 讨论
- - '##'
  - 12.6 播放视频
- - '###'
  - 问题
- - '###'
  - 解决方案
- - '###'
  - 讨论
- - '##'
  - 12.7 使用相机
- - '###'
  - 问题
- - '###'
  - 解决方案
- - '###'
  - 讨论
- - '##'
  - 12.8 使用系统共享菜单
- - '###'
  - 问题
- - '###'
  - 解决方案
- - '###'
  - 讨论
- - '##'
  - 12.9 总结
- - '#'
  - 13. 杂项
- - '##'
  - 13.1 使用资源
- - '###'
  - 问题
- - '###'
  - 解决方案
- - '###'
  - 讨论
- - '##'
  - 13.2 使用手势
- - '###'
  - 问题
- - '###'
  - 解决方案
- - '###'
  - 讨论
- - '##'
  - 13.3 支持多种语言区域
- - '###'
  - 问题
- - '###'
  - 解决方案
- - '###'
  - 讨论
- - '##'
  - 13.4 生成翻译文件
- - '###'
  - 问题
- - '###'
  - 解决方案
- - '###'
  - 讨论
- - '##'
  - 13.5 绘制自定义元素
- - '###'
  - 问题
- - '###'
  - 解决方案
- - '###'
  - 讨论
- - '##'
  - 13.6 自定义主题
- - '###'
  - 问题
- - '###'
  - 解决方案
- - '###'
  - 讨论
- - '##'
  - 13.7 总结
- - '#'
  - 14. 测试与调试
- - '##'
  - 14.1 编写单元测试
- - '###'
  - 问题
- - '###'
  - 解决方案
- - '###'
  - 讨论
- - '##'
  - 14.2 在测试中使用模拟对象
- - '###'
  - 问题
- - '###'
  - 解决方案
- - '###'
  - 讨论
- - '##'
  - 14.3 编写 Widget 测试
- - '###'
  - 问题
- - '###'
  - 解决方案
- - '###'
  - 讨论
- - '##'
  - 14.4 编写集成测试
- - '###'
  - 问题
- - '###'
  - 解决方案
- - '###'
  - 讨论
- - '##'
  - 14.5 调试应用
- - '###'
  - 问题
- - '###'
  - 解决方案
- - '###'
  - 讨论
- - '##'
  - 14.6 小结
- - '##'
  - 索引
- - '###'
  - A
- - '###'
  - B
- - '###'
  - C
- - '###'
  - D
- - '###'
  - E
- - '###'
  - F
- - '###'
  - G
- - '###'
  - H
- - '###'
  - I
- - '###'
  - J, K
- - '###'
  - L
- - '###'
  - M
- - '###'
  - N
- - '###'
  - O
- - '###'
  - P
- - '###'
  - Q
- - '###'
  - R
- - '###'
  - S
- - '###'
  - T
- - '###'
  - U
- - '###'
  - V
- - '###'
  - W
- - '###'
  - X, Y, Z
