name: IOS 7 development recipes
name_cn: IOS 7 开发秘籍
slug: ios-7-development-recipes
toc:
- - '##'
  - 修复说明
- - '##'
  - 修复后的目录
- - '#'
  - 关于作者
- - '#'
  - 关于技术审阅者
- - '#'
  - 引言
- - '#'
  - 本书读者对象
- - '#'
  - 本书结构
- - '##'
  - 本版更新内容
- - '##'
  - 下载代码
- - '##'
  - 联系作者
- - '#'
  - 致谢
- - '#'
  - 目录
- - '#'
  - 第 1 章：应用程序实例
- - '##'
  - 内容概览
- - '##'
  - 摘要
- - '##'
  - 实例 1-1：设置单视图应用程序
- - '###'
  - 另一种方式
- - '##'
  - 配方 1-2：链接框架
- - '##'
  - 配方 1-3：添加用户界面控件视图
- - '##'
  - 配方 1-4：创建出口
- - '##'
  - 配方 1-5：创建动作
- - '##'
  - 方案 1-6：创建类
- - '##'
  - 方案 1-7：添加 Info.plist 属性
- - '##'
  - 配方 1-8：添加资源文件
- - '###'
  - 使用资源目录
- - '##'
  - 配方 1-9：处理错误
- - '###'
  - 建立错误处理框架
- - '###'
  - 通知用户
- - '###'
  - 实现恢复选项
- - '##'
  - 方法 1-10：处理异常
- - '###'
  - 处理异常的策略
- - '###'
  - 设置测试应用
- - '###'
  - 拦截未捕获的异常
- - '###'
  - 报告错误
- - '###'
  - 添加按钮
- - '###'
  - 通过电子邮件发送报告
- - '###'
  - 最终润色
- - '##'
  - 技巧 1-11：添加精简版
- - '###'
  - 添加构建目标
- - '###'
  - 为特定版本编码
- - '##'
  - 配方 1-12：添加启动图像
- - '###'
  - 设计启动图像
- - '###'
  - 启动图像文件
- - '##'
  - 本章小结
- - '#'
  - 第 2 章：故事板实例
- - '##'
  - 那么，Storyboard 里面有什么？
- - '###'
  - 场景
- - '###'
  - 跳转
- - '##'
  - 配方 2-1：实现导航控制器
- - '###'
  - 向故事板添加新场景
- - '##'
  - 配方 2-2：实现 `UITableViewController`
- - '###'
  - 添加详情视图
- - '###'
  - 设置自定义视图控制器
- - '###'
  - 使用单元格原型
- - '##'
  - 配方 2-3：实现 UITabBarController
- - '##'
  - 总结
- - '#'
  - 第 3 章：布局实例
- - '##'
  - 摘要
- - '##'
  - 方案 3-1：使用 Auto Layout
- - '###'
  - Auto Layout 约束
- - '####'
  - 使用 Control-点击并拖拽的方法添加约束
- - '###'
  - 使用自动布局问题解决菜单添加约束
- - '###'
  - 使用 Pin 菜单添加约束
- - '###'
  - 约束优先级
- - '###'
  - 添加尾部按钮
- - '####'
  - 禁用 Auto Layout
- - '####'
  - 使用预览工具
- - '##'
  - 技巧 3-2：用代码编写 Auto Layout
- - '###'
  - 设置应用程序
- - '###'
  - 可视化格式语言
- - '###'
  - 添加图像视图
- - '###'
  - 定义图像视图的约束
- - '###'
  - 清单 3-14. 完整的 `rebuildImageViewsConstraints` 方法
- - '###'
  - 清单 3-15. 删除和清除图像视图的动作方法实现
- - '##'
  - 方案 3-3：调试 Auto Layout 代码
- - '###'
  - 处理歧义布局
- - '###'
  - 处理约束不满足
- - '##'
  - 总结
- - '#'
  - 第 4 章：表格和集合视图实例
- - '##'
  - 方案 4-1：创建非分组表格
- - '###'
  - 设置应用程序
- - '###'
  - 为国家添加模型
- - '###'
  - 在表格视图中显示数据
- - '###'
  - 关于缓存单元格和复用的注意事项
- - '###'
  - 配置单元格
- - '###'
  - 实现附属视图
- - '###'
  - 增强的用户交互
- - '###'
  - 单元格视图自定义的注意事项
- - '##'
  - 方案 4-2：编辑 `UITableView`
- - '###'
  - '`UITableView` 动画'
- - '##'
  - 不过，还有更多！
- - '##'
  - 秘方 4-3：对 `UITableView` 进行重排序
- - '##'
  - 配方 4-4：创建分组 UITableView
- - '##'
  - 技巧 4-5：注册自定义单元格类
- - '###'
  - 创建自定义表格视图单元格类
- - '###'
  - 注册你的单元格类
- - '##'
  - 方法 4-6：创建国旗选取器集合视图
- - '###'
  - 设置应用程序
- - '###'
  - 创建数据模型
- - '###'
  - 构建国旗选择器
- - '###'
  - 定义集合视图接口
- - '###'
  - 显示标志选择器
- - '###'
  - 使用自动布局居中标题
- - '##'
  - 总结
- - '#'
  - 第 5 章：定位实例
- - '##'
  - 关于 Core Location
- - '##'
  - 标准定位服务与重大位置变化服务
- - '##'
  - 技巧 5-1：获取基本位置信息
- - '###'
  - 设置应用程序
- - '###'
  - 启动与停止位置更新
- - '###'
  - 接收位置更新
- - '###'
  - 测试位置更新
- - '##'
  - 示例 5-2：重大位置变化
- - '###'
  - 设置应用程序
- - '###'
  - 启用后台更新
- - '###'
  - 添加本地通知
- - '##'
  - 配方 5-3：追踪磁航向
- - '###'
  - 关于航向追踪
- - '###'
  - 设置应用程序
- - '###'
  - 开始和停止航向更新
- - '###'
  - 实现委托方法
- - '##'
  - 专题 5-4：追踪真北方
- - '###'
  - 添加真北方向
- - '##'
  - 配方 5-5：区域监控
- - '###'
  - 关于区域的一些要点
- - '###'
  - 欢迎来到丹佛！
- - '##'
  - 食谱 5-6：实现地理编码
- - '###'
  - 实现反向地理编码
- - '###'
  - 实现正向地理编码
- - '###'
  - 最佳实践
- - '##'
  - 摘要
- - '#'
  - 第 6 章：动作实例
- - '##'
  - 摘要
- - '##'
  - 秘籍 6-1：识别摇动事件
- - '###'
  - 拦截摇动事件
- - '###'
  - 创建窗口子类
- - '###'
  - 实现摇动通知
- - '###'
  - 测试摇动事件
- - '##'
  - 实践指南 6-2：访问原始 Core Motion 数据
- - '###'
  - Core Motion 传感器
- - '###'
  - 项目设置
- - '###'
  - 访问传感器数据
- - '###'
  - 推送或拉取
- - '###'
  - 选择更新间隔
- - '###'
  - 原始运动数据的特性
- - '##'
  - 方法 6-3：访问设备运动数据
- - '###'
  - 设备运动类
- - '###'
  - 设置应用程序
- - '###'
  - 访问设备运动数据
- - '###'
  - 设置参考系
- - '##'
  - 技巧 6-4：利用重力移动标签
- - '###'
  - 设置应用程序
- - '###'
  - 用重力移动标签
- - '###'
  - 添加加速效果
- - '##'
  - 本章小结
- - '#'
  - 第 7 章：地图实例
- - '##'
  - 秘籍 7-1：显示带有当前位置的地图
- - '###'
  - 设置应用程序
- - '###'
  - 用户控制的跟踪
- - '##'
  - 配方 7-2：用图钉标记位置
- - '###'
  - 添加标注对象
- - '###'
  - 更改图钉颜色
- - '##'
  - 方案 7-3：创建自定义标注
- - '###'
  - 设置应用程序
- - '###'
  - 创建自定义标注类
- - '###'
  - 创建自定义标注视图
- - '###'
  - 自定义标注气泡
- - '###'
  - 添加详细视图
- - '##'
  - 配方 7-4：拖拽图钉
- - '###'
  - 添加可拖拽的图钉
- - '##'
  - 配方 7-5：向地图添加覆盖层
- - '###'
  - 创建叠加层
- - '##'
  - 技巧 7-6：动态分组标注
- - '###'
  - 图钉森林
- - '###'
  - 实现解决方案
- - '###'
  - 添加颜色编码
- - '##'
  - 配方 7-7：从你的应用启动地图
- - '###'
  - 添加地图项目
- - '###'
  - 启动导航模式
- - '##'
  - 配方 7-8：注册路线应用
- - '###'
  - 声明路线应用
- - '###'
  - 处理启动
- - '###'
  - 测试路由应用
- - '###'
  - 指定覆盖区域
- - '##'
  - 教程 7-9：获取路线
- - '###'
  - 设置应用
- - '###'
  - 在地图上绘制路线方向
- - '###'
  - 添加预计到达时间
- - '##'
  - 方案 7-10：使用 3-D 地图
- - '###'
  - 使用属性方法
- - '###'
  - 使用便捷方法
- - '###'
  - 创建飞越效果
- - '##'
  - 总结
- - '#'
  - 第 8 章：社交网络实例
- - '##'
  - 摘要
- - '##'
  - 配方 8-1：使用活动视图分享内容
- - '###'
  - 设置活动视图控制器
- - '###'
  - 排除活动视图项
- - '###'
  - 包含活动视图项目
- - '##'
  - 食谱 8-2：使用 Compose 视图共享内容
- - '##'
  - 食谱 8-3：使用 SLRequest 共享内容
- - '###'
  - 设置主视图
- - '###'
  - 请求访问 Twitter 账户
- - '###'
  - 处理多个账户
- - '##'
  - 秘方 8-4：检索推文
- - '###'
  - 设置基于导航的应用程序
- - '###'
  - 显示可用的信息源
- - '###'
  - 显示推文
- - '###'
  - 显示单条推文
- - '##'
  - 总结
- - '#'
  - 第 9 章：相机实例
- - '##'
  - 食谱 9-1：拍照
- - '###'
  - 设置用户界面
- - '###'
  - 访问相机
- - '###'
  - 获取照片
- - '###'
  - 实现基本编辑
- - '###'
  - 将照片保存到相簿
- - '##'
  - 食谱 9-2：录制视频
- - '###'
  - 代码清单 9-10. 更新 `takePicture:` 方法以允许视频录制
- - '###'
  - 代码清单 9-11. 将框架导入 `ViewController.h` 文件
- - '###'
  - 代码清单 9-12. 在 `imagePickerController:didFinishPickingMediaWithInfo:` 方法中添加视频比较逻辑
- - '##'
  - 配方 9-3：编辑视频
- - '##'
  - 食谱 9-4：使用自定义相机覆盖层
- - '###'
  - 代码清单 9-19. `customViewForImagePicker:` 方法的实现
- - '###'
  - 代码清单 9-20. `toggleFlash:` 和 `toggleCamera:` 方法的实现
- - '##'
  - 食谱 9-5：使用 `AVCaptureSession` 显示相机预览
- - '##'
  - 食谱 9-6：使用 `AVCaptureSession` 捕获静态图像
- - '###'
  - 添加拍照按钮
- - '###'
  - 清单 9-34：启动`captureStillImage`方法并添加带有纵向方向的拍摄连接
- - '###'
  - 清单 9-35：添加用于拍摄静态图像的代码
- - '###'
  - 清单 9-36：检查拍摄图像的成功或失败
- - '###'
  - 清单 9-37：完成图像拍摄成功的代码
- - '###'
  - 清单 9-38：添加异步保存并提醒用户成功或错误的代码
- - '###'
  - 清单 9-39：完整的`captureStillImage`实现
- - '##'
  - 食谱 9-7：使用`AVCaptureSession`捕捉视频
- - '###'
  - 添加视频录制模式
- - '##'
  - 注意
- - '##'
  - 方法 9-8：捕获视频帧
- - '##'
  - 配方 9-9：捕获机器可读码
- - '##'
  - 摘要
- - '#'
  - 第 10 章：多媒体实例
- - '##'
  - 概述
- - '##'
  - 食谱 10-1：播放音频
- - '###'
  - 设置应用
- - '###'
  - 设置音频播放器
- - '###'
  - 处理错误和中断
- - '##'
  - 技巧 10-2：录制音频
- - '###'
  - 设置音频录制器
- - '###'
  - 处理中断
- - '##'
  - 技巧 10-3：访问音乐库
- - '###'
  - 搭建基础音乐播放器
- - '###'
  - 处理通知
- - '###'
  - 选取要播放的媒体
- - '###'
  - 查询媒体
- - '##'
  - 配方 10-4：播放后台音频
- - '###'
  - 设置用户界面
- - '###'
  - 声明后台模式播放
- - '###'
  - 实现播放器
- - '###'
  - 清单 10-46 至 10-53：媒体播放实现
- - '##'
  - 总结
- - '#'
  - 第 11 章：图像实例
- - '##'
  - 方案 11-1：使用图像视图
- - '###'
  - 清单 11-1：起始的 `DetailViewController.h` 实现
- - '###'
  - 清单 11-2：配置图片视图以保持比例填充并裁剪至边界
- - '###'
  - 清单 11-3：实现 `imagePickerControllerDidCancel:` 委托方法
- - '###'
  - 清单 11-4：实现 `imagePickerController:didFinishPickingMediaWithInfo:`
- - '###'
  - 清单 11-5：实现 `clearImage:` 方法
- - '##'
  - 技巧 11-2：缩放图片
- - '###'
  - 清单 11-6：添加处理用户界面配置的方法声明
- - '###'
  - 清单 11-7. 实现 `configureDetailsWithImage:label:showbuttons:` 方法
- - '###'
  - 清单 11-8. 设置用于主视图控制器和详细视图控制器之间通信的协议
- - '###'
  - 清单 11-9. 将 `UIImage` 属性添加到 `MasterViewController.h` 文件中
- - '###'
  - 清单 11-10. 修改 `imagePickerController:didFinishPickingMediaWithInfo:` 以调用新协议
- - '###'
  - 清单 11-11. 修改 `clearImage:` 方法以利用 `detailViewControllerDidClearImage:` 协议方法
- - '##'
  - 'Recipe 11-3: 使用滤镜处理图像'
- - '###'
  - 组合滤镜
- - '###'
  - 为表格视图创建缩略图
- - '##'
  - 技巧 11-4：检测特征
- - '##'
  - 总结
- - '#'
  - 第 12 章：图形实例
- - '##'
  - 摘要
- - '##'
  - 操作指南 12-1：绘制简单形状
- - '###'
  - 略作重构
- - '##'
  - 配方 12-2：绘制路径
- - '##'
  - 配方 12-3：添加字体并绘制文本
- - '###'
  - 利用可用字体
- - '###'
  - 导入自定义字体
- - '##'
  - 配方 12-4：添加阴影
- - '##'
  - 配方 12-5：创建渐变
- - '##'
  - 配方 12-6：将绘制内容裁剪到蒙版
- - '##'
  - 食谱 12-7：编程屏幕截图
- - '##'
  - 总结
- - '#'
  - 第 13 章：动画与物理实例
- - '##'
  - 摘要
- - '##'
  - 配方 13-1. 使用 UIKit 进行视图动画
- - '###'
  - 更改大小和透明度
- - '###'
  - 处理旋转与链式动画
- - '##'
  - 示例 13-2. 实现 UIKit Dynamics
- - '###'
  - 使用重力
- - '###'
  - 重力与碰撞
- - '###'
  - 使用项目属性
- - '###'
  - 添加吸附（Snap）行为
- - '###'
  - 创建推动行为
- - '###'
  - 弹簧与附着
- - '###'
  - 创建自定义行为类
- - '##'
  - 总结
- - '#'
  - 第 14 章：用户数据实例
- - '##'
  - 配方 14-1：使用 `NSCalendar` 和 `NSDate`
- - '##'
  - 配方 14-2. 获取日历事件
- - '###'
  - 代码清单 14-10. 创建 `NSPredicate`
- - '###'
  - 代码清单 14-11. 从事件存储中检索事件
- - '###'
  - 代码清单 14-12. 打印事件标题
- - '###'
  - 代码清单 14-13. 完整的 `viewDidLoad` 实现
- - '##'
  - 食谱 14-3：在表格视图中显示事件
- - '###'
  - 方法 14-4：查看、编辑和删除事件
- - '##'
  - 配方 14-5：创建日历事件
- - '###'
  - 创建重复事件
- - '##'
  - Recipe 14-6. 创建提醒事项
- - '###'
  - 设置应用程序
- - '###'
  - 请求访问提醒事项
- - '###'
  - 创建基于时间的提醒事项
- - '###'
  - 创建基于位置的提醒事项
- - '##'
  - 配方 14-7：访问通讯录
- - '###'
  - 食谱 14-8. 设置联系人信息
- - '##'
  - 总结
- - '#'
  - 第 15 章：数据存储实例
- - '##'
  - 摘要
- - '##'
  - 配方 15-1：使用 `NSUserDefaults` 持久化数据
- - '##'
  - 示例 15-2：使用文件持久化数据
- - '##'
  - Recipe 15-3. Using Core Data
- - '###'
  - Understanding Core Data
- - '###'
  - 设置 Core Data
- - '###'
  - 设计数据模型
- - '###'
  - 设置词汇表表格视图
- - '###'
  - 实现单词视图控制器
- - '###'
  - 添加单词编辑视图
- - '###'
  - 在 iCloud 上持久化数据
- - '##'
  - 配方 15-4：在 iCloud 中存储键值数据
- - '###'
  - 为应用设置 iCloud
- - '###'
  - 在 iCloud 键值存储中持久化数据
- - '###'
  - 使用 NSUserDefaults 本地缓存 iCloud 数据
- - '##'
  - 配方 15-5：在 iCloud 中存储 UIDocument
- - '##'
  - 总结
- - '#'
  - 第 16 章：数据传输实例
- - '##'
  - 范例 16-1：编写短信
- - '##'
  - 配方 16-2：编写电子邮件
- - '###'
  - 为邮件添加附件
- - '###'
  - 清单 16-16. 实现 `UIImagePickerControllerDelegate` 协议方法
- - '###'
  - 清单 16-17. 为图片视图添加 `cornerRadius` 属性
- - '###'
  - 清单 16-18. 修改 `mailMessage:` 方法以附加图片
- - '###'
  - 清单 16-19. 修改 `mailComposeController:didFinishWithResult:error:` 方法
- - '##'
  - 秘方 16-3：打印图片
- - '###'
  - 清单 16-20. 创建 `UIPrintInteractionController` 实例
- - '###'
  - 清单 16-21. 配置 `printInfo` 属性
- - '###'
  - 清单 16-22. 设置打印图片
- - '###'
  - 清单 16-23. 配置 `printInfo`
- - '###'
  - 使用 UIPrintInteractionController 进行打印
- - '###'
  - 呈现打印控制器的方法
- - '##'
  - 技巧 16-4：打印纯文本
- - '##'
  - 配方 16-5：打印一个视图
- - '##'
  - 配方 16-6：使用页面渲染器进行格式化打印
- - '##'
  - 总结
- - '#'
  - 第 17 章：Game Kit 实例
- - '##'
  - 配方 17-1. 让你的应用支持 Game Center
- - '###'
  - 实现游戏
- - '###'
  - 代码清单 17-1. 完成的 GameViewController.h 文件
- - '###'
  - 代码清单 17-2. 实现 `initWithLevel:` 初始化方法
- - '###'
  - 代码清单 17-3. 实现 `updateScoreLabel`
- - '###'
  - 代码清单 17-4. 向 `ViewDidLoad` 方法添加代码以设置关卡并更新分数
- - '###'
  - 代码清单 17-5. 将 GameViewController.h 文件导入 ViewController.h 文件
- - '###'
  - 代码清单 17-6. 实现 `playGameWithLevel:` 辅助方法
- - '###'
  - 代码清单 17-7. 实现启动每种游戏类型的方法
- - '###'
  - 幸运游戏简单难度的界面
- - '###'
  - 注册 iTunes Connect
- - '###'
  - 验证本地玩家
- - '###'
  - 在应用中显示 Game Center
- - '##'
  - 配方 17-2. 实现排行榜
- - '###'
  - 定义排行榜
- - '###'
  - 向 Game Center 报告得分
- - '##'
  - 方案 17-3. 实现成就
- - '###'
  - 在 iTunes Connect 中定义成就
- - '###'
  - 报告成就
- - '##'
  - 秘方 17-4. 创建一个简单的基于回合制的多人游戏
- - '###'
  - 构建井字棋游戏
- - '###'
  - 为游戏准备 Game Center
- - '###'
  - 实现配对功能
- - '###'
  - 比赛数据的编码与解码
- - '###'
  - 清单 17-56. 实现 `encodeMatchData` 方法
- - '###'
  - 清单 17-57. 实现 `decodeMatchData:` 方法
- - '###'
  - 清单 17-58. 实现 `loadMatchData` 方法
- - '###'
  - 清单 17-59. 实现 `localPlayerIsCurrentPlayer` 方法
- - '###'
  - 清单 17-60. 实现 `localPlayerMark` 方法
- - '###'
  - 处理回合制事件
- - '##'
  - 总结
- - '#'
  - iOS 7 开发实战
- - '##'
  - 问题-解决方案方法
- - '##'
  - 索引
- - '###'
  - A
- - '###'
  - C
- - '###'
  - D
- - '###'
  - E
- - '###'
  - F
- - '###'
  - G
- - '###'
  - H
- - '###'
  - I
- - '###'
  - J, K
- - '###'
  - L
