name: Windows 10 Development Recipes
name_cn: Windows 10 开发秘籍
slug: windows-10-development-recipes
toc:
- - '#'
  - 引言
- - '##'
  - 本书读者对象
- - '##'
  - 你将学到什么
- - '##'
  - 源代码
- - '##'
  - 致谢
- - '#'
  - 第 1 章：Windows 10 应用程序入门
- - '##'
  - 1.1 探究通用 Windows 平台
- - '###'
  - 问题
- - '###'
  - 解决方案
- - '####'
  - 一个 Windows 平台
- - '####'
  - 设备系列
- - '####'
  - 通用控件
- - '####'
  - 通用输入处理
- - '##'
  - 1.2 通用 Windows 平台的开发工具
- - '###'
  - 问题
- - '###'
  - 解决方案
- - '##'
  - 1.3 创建通用 Windows 平台应用程序
- - '###'
  - 问题
- - '###'
  - 解决方案
- - '###'
  - 工作原理
- - '##'
  - 1.4 运行通用 Windows 平台应用
- - '###'
  - 问题
- - '###'
  - 解决方案
- - '###'
  - 工作原理
- - '####'
  - 在 Windows Phone 10 模拟器上运行应用
- - '####'
  - 在 Windows 10 模拟器上运行应用
- - '####'
  - 在本地计算机上运行应用
- - '####'
  - 在设备上运行应用
- - '#'
  - 第 2 章：WinJS 基础
- - '##'
  - 2.1 JavaScript 中的命名空间
- - '###'
  - 问题
- - '###'
  - 解决方案
- - '###'
  - 工作原理
- - '##'
  - 2.2 向现有命名空间添加子命名空间
- - '###'
  - 问题
- - '###'
  - 解决方案
- - '###'
  - 工作原理
- - '##'
  - 2.3 在 WinJS 中创建类
- - '###'
  - 问题
- - '###'
  - 解决方案
- - '###'
  - 工作原理
- - '##'
  - 2.4 在 WinJS 中派生类
- - '###'
  - 问题
- - '###'
  - 解决方案
- - '###'
  - 工作原理
- - '##'
  - 2.5 在 WinJS 中创建混入
- - '###'
  - 问题
- - '###'
  - 解决方案
- - '###'
  - 工作原理
- - '##'
  - 2.6 WinJS 中的封装
- - '###'
  - 问题
- - '###'
  - 解决方案
- - '###'
  - 工作原理
- - '##'
  - 2.7 在 WinJS 中使用 Promise
- - '###'
  - 问题
- - '###'
  - 解决方案
- - '###'
  - 工作原理
- - '#'
  - 第 3 章：基本 WinJS 控件
- - '##'
  - 3.1 在页面上声明 WinJS 控件
- - '###'
  - 问题
- - '###'
  - 解决方案
- - '###'
  - 工作原理
- - '##'
  - 3.2 设置 WinJS 控件的选项
- - '###'
  - 问题
- - '###'
  - 解决方案
- - '###'
  - 工作原理
- - '##'
  - 3.3 通过 JavaScript 代码添加 WinJS 控件
- - '###'
  - 问题
- - '###'
  - 解决方案
- - '###'
  - 工作原理
- - '##'
  - 3.4 从 HTML 文档中获取 WinJS 控件
- - '###'
  - 问题
- - '###'
  - 解决方案
- - '###'
  - 工作原理
- - '##'
  - 3.5 ToggleSwitch 控件
- - '###'
  - 问题
- - '###'
  - 解决方案
- - '###'
  - 工作原理
- - '##'
  - 3.6 DatePicker 控件
- - '###'
  - 问题
- - '###'
  - 解决方案
- - '###'
  - 工作原理
- - '##'
  - 3.7 TimePicker 控件
- - '###'
  - 问题
- - '###'
  - 解决方案
- - '###'
  - 工作原理
- - '##'
  - 3.8 Tooltip 控件
- - '###'
  - 问题
- - '###'
  - 解决方案
- - '###'
  - 工作原理
- - '##'
  - 3.9 显示文本
- - '###'
  - 问题
- - '###'
  - 解决方案
- - '###'
  - 工作原理
- - '##'
  - 3.10 在应用中编辑文本
- - '###'
  - 问题
- - '###'
  - 解决方案
- - '###'
  - 工作原理
- - '#'
  - 第 4 章：列表控件、应用栏和工具栏
- - '##'
  - 4.1 使用 Repeater 控件
- - '###'
  - 问题
- - '###'
  - 解决方案
- - '###'
  - 工作原理
- - '##'
  - 4.2 使用 FlipView 控件
- - '###'
  - 问题
- - '###'
  - 解决方案
- - '###'
  - 工作原理
- - '##'
  - 4.3 使用 ListView 控件
- - '###'
  - 问题
- - '###'
  - 解决方案
- - '###'
  - 工作原理
- - '##'
  - 4.4 在`ListView`控件中筛选项
- - '###'
  - 问题
- - '###'
  - 解决方案
- - '###'
  - 工作原理
- - '##'
  - 4.5 在 ListView 控件中对项目进行分组
- - '###'
  - 问题
- - '###'
  - 解决方案
- - '###'
  - 工作原理
- - '##'
  - 4.6 ListView 中的语义缩放
- - '###'
  - 问题
- - '###'
  - 解决方案
- - '###'
  - 工作原理
- - '##'
  - 4.7 使用 AppBar 控件
- - '###'
  - 问题
- - '###'
  - 解决方案
- - '###'
  - 工作原理
- - '##'
  - 4.8 使用工具栏控件
- - '###'
  - 问题
- - '###'
  - 解决方案
- - '###'
  - 工作原理
- - '#'
  - 第 5 章：数据绑定与导航
- - '##'
  - 5.1 数据绑定到简单对象
- - '###'
  - 问题
- - '###'
  - 解决方案
- - '###'
  - 工作原理
- - '##'
  - 5.2 数据绑定 DOM 元素的样式属性
- - '###'
  - 问题
- - '###'
  - 解决方案
- - '###'
  - 工作原理
- - '##'
  - 5.3 使用模板进行数据绑定
- - '###'
  - 问题
- - '###'
  - 解决方案
- - '###'
  - 工作原理
- - '##'
  - 5.4 数据绑定 WinJS 控件
- - '###'
  - 问题
- - '###'
  - 解决方案
- - '###'
  - 工作原理
- - '##'
  - 5.5 UWP 应用中的导航结构
- - '###'
  - 问题
- - '###'
  - 解决方案
- - '##'
  - 5.6 UWP 应用中的导航元素
- - '###'
  - 问题
- - '###'
  - 解决方案
- - '##'
  - 5.7 UWP 应用中的 Pivot 导航
- - '###'
  - 问题
- - '###'
  - 解决方案
- - '###'
  - 工作原理
- - '##'
  - 5.8 UWP 应用中的 SplitView 导航
- - '###'
  - 问题
- - '###'
  - 解决方案
- - '###'
  - 工作原理
- - '##'
  - 5.9 UWP 应用中的 Hub 导航
- - '###'
  - 问题
- - '###'
  - 解决方案
- - '###'
  - 工作原理
- - '##'
  - 5.10 在 UWP 应用中使用 ListView 进行主/从导航
- - '###'
  - 问题
- - '###'
  - 解决方案
- - '###'
  - 工作原理
- - '#'
  - 第 6 章：针对不同屏幕适配 UI
- - '##'
  - 6.1 不同屏幕的设计断点
- - '###'
  - 问题
- - '###'
  - 解决方案
- - '##'
  - 6.2 自适应 UI 技术：重新定位
- - '###'
  - 问题
- - '###'
  - 解决方案
- - '###'
  - 工作原理
- - '##'
  - 6.3 自适应 UI 技术：流体布局
- - '###'
  - 问题
- - '###'
  - 解决方案
- - '###'
  - 工作原理
- - '###'
  - 新建项目对话框
- - '#'
  - 第 7 章：应用程序生命周期和导航
- - '##'
  - 7.1 应用程序状态和事件
- - '###'
  - 问题
- - '###'
  - 解决方案
- - '###'
  - 工作原理
- - '##'
  - 7.2 处理应用中的未处理异常
- - '###'
  - 问题
- - '###'
  - 解决方案
- - '###'
  - 工作原理
- - '##'
  - 7.3 处理应用的终止和恢复
- - '###'
  - 问题
- - '###'
  - 解决方案
- - '###'
  - 工作原理
- - '##'
  - 7.4 使用 SessionState 存储状态
- - '###'
  - 问题
- - '###'
  - 解决方案
- - '###'
  - 工作原理
- - '##'
  - 7.5 使用超链接在页面之间导航
- - '###'
  - 问题
- - '###'
  - 解决方案
- - '###'
  - 工作原理
- - '##'
  - 7.6 使用单页导航在页面之间导航
- - '###'
  - 问题
- - '###'
  - 解决方案
- - '###'
  - 工作原理
- - '#'
  - 第 8 章：全球化和本地化
- - '##'
  - 8.1 使用资源字符串
- - '###'
  - 问题
- - '###'
  - 解决方案
- - '###'
  - 工作原理
- - '##'
  - 8.2 格式化日期、时间、数字和货币
- - '###'
  - 问题
- - '###'
  - 解决方案
- - '###'
  - 工作原理
- - '###'
  - 格式化日期和时间
- - '###'
  - 格式化数字和货币
- - '##'
  - 8.3 本地化 WinJS 控件
- - '###'
  - 问题
- - '###'
  - 解决方案
- - '###'
  - 工作原理
- - '#'
  - 第 9 章：数据存储与应用数据
- - '##'
  - 9.1 如何创建和删除本地应用数据设置容器
- - '###'
  - 问题
- - '###'
  - 解决方案
- - '###'
  - 工作原理
- - '##'
  - 9.2 如何创建和读取本地应用数据设置
- - '###'
  - 问题
- - '###'
  - 解决方案
- - '###'
  - 工作原理
- - '##'
  - 9.3 如何创建和检索本地复合设置
- - '###'
  - 问题
- - '###'
  - 解决方案
- - '###'
  - 工作原理
- - '##'
  - 9.4 如何创建漫游应用数据存储容器
- - '###'
  - 问题
- - '###'
  - 解决方案
- - '###'
  - 工作原理
- - '##'
  - 9.5 如何创建和读取漫游应用数据设置
- - '###'
  - 问题
- - '###'
  - 解决方案
- - '###'
  - 工作原理
- - '##'
  - 9.6 如何注册数据更改事件
- - '###'
  - 问题
- - '###'
  - 解决方案
- - '###'
  - 工作原理
- - '##'
  - 9.7 如何创建、写入和读取本地文件
- - '###'
  - 问题
- - '###'
  - 解决方案
- - '###'
  - 工作原理
- - '####'
  - 本地文件夹
- - '####'
  - 漫游文件夹
- - '####'
  - 临时文件夹
- - '#'
  - 第 10 章：共享数据
- - '##'
  - 共享合同
- - '##'
  - 10.1 为源应用的共享选项设置事件处理程序
- - '###'
  - 问题
- - '###'
  - 解决方案
- - '###'
  - 工作原理
- - '##'
  - 10.2 将纯文本数据共享到其他应用
- - '###'
  - 问题
- - '###'
  - 解决方案
- - '###'
  - 工作原理
- - '##'
  - 10.3 向其他应用共享 Web 链接
- - '###'
  - 问题
- - '###'
  - 解决方案
- - '###'
  - 工作原理
- - '##'
  - 10.4 向其他应用共享图像
- - '###'
  - 问题
- - '###'
  - 解决方案
- - '###'
  - 工作原理
- - '##'
  - 10.5 将应用声明为共享目标
- - '###'
  - 问题
- - '###'
  - 解决方案
- - '###'
  - 工作原理
- - '##'
  - 10.6 处理共享激活并接收纯文本
- - '###'
  - 问题
- - '###'
  - 解决方案
- - '###'
  - 工作原理
- - '##'
  - 10.7 接收其他应用共享的图像
- - '###'
  - 问题
- - '###'
  - 解决方案
- - '###'
  - 工作原理
- - '##'
  - 10.8 共享自定义数据类型
- - '###'
  - 问题
- - '###'
  - 解决方案
- - '###'
  - 工作原理
- - '#'
  - 第 11 章：后台任务
- - '##'
  - 11.1 用于后台任务的系统事件触发器
- - '###'
  - 问题
- - '###'
  - 解决方案
- - '##'
  - 11.2 创建并注册后台任务
- - '###'
  - 问题
- - '###'
  - 解决方案
- - '###'
  - 工作原理
- - '##'
  - 11.3 设置后台任务的运行条件
- - '###'
  - 问题
- - '###'
  - 解决方案
- - '###'
  - 工作原理
- - '##'
  - 11.4 监控后台任务进度与完成
- - '###'
  - 问题
- - '###'
  - 解决方案
- - '###'
  - 工作原理
- - '#'
  - 第 12 章：Windows 应用中的位置与地图
- - '##'
  - 12.1 获取当前位置
- - '###'
  - 问题
- - '###'
  - 解决方案
- - '###'
  - 工作原理
- - '##'
  - 12.2 响应地理定位器位置更新
- - '###'
  - 问题
- - '###'
  - 解决方案
- - '###'
  - 工作原理
- - '##'
  - 12.3 使用 HTML5 检测用户位置
- - '###'
  - 问题
- - '###'
  - 解决方案
- - '###'
  - 工作原理
- - '##'
  - 12.4 使用 HTML5 检测位置更新
- - '###'
  - 问题
- - '###'
  - 解决方案
- - '###'
  - 工作原理
- - '##'
  - 12.5 在内置地图应用中显示地图
- - '###'
  - 问题
- - '###'
  - 解决方案
- - '###'
  - 工作原理
- - '##'
  - 12.6 在内置地图应用中显示路线
- - '###'
  - 问题
- - '###'
  - 解决方案
- - '###'
  - 工作原理
- - '##'
  - 12.7 Windows 应用商店应用中的必应地图控件
- - '###'
  - 问题
- - '###'
  - 解决方案
- - '###'
  - 工作原理
- - '###'
  - Visual Studio 中必应地图的引用管理器
- - '#'
  - 第 13 章：构建连接到云的应用
- - '##'
  - 13.1 在 Microsoft Azure 中创建新的移动服务
- - '###'
  - 问题
- - '###'
  - 解决方案
- - '###'
  - 工作原理
- - '##'
  - 13.2 在移动服务中创建数据库表
- - '###'
  - 问题
- - '###'
  - 解决方案
- - '###'
  - 工作原理
- - '##'
  - 13.3 为 WinJS 客户端库安装移动服务
- - '###'
  - 问题
- - '###'
  - 解决方案
- - '###'
  - 工作原理
- - '##'
  - 13.4 执行 CRUD 操作
- - '###'
  - 问题
- - '###'
  - 解决方案
- - '###'
  - 工作原理
- - '##'
  - 13.5 使用分页检索数据
- - '###'
  - 问题
- - '###'
  - 解决方案
- - '###'
  - 工作原理
- - '##'
  - 13.6 对来自移动服务的返回数据进行排序
- - '###'
  - 问题
- - '###'
  - 解决方案
- - '###'
  - 工作原理
- - '##'
  - 13.7 在服务器脚本中执行验证
- - '###'
  - 问题
- - '###'
  - 解决方案
- - '###'
  - 工作原理
- - '#'
  - 第 14 章：磁贴和通知
- - '##'
  - 14.1 创建默认磁贴
- - '###'
  - 问题
- - '###'
  - 解决方案
- - '###'
  - 工作原理
- - '##'
  - 14.2 创建自适应磁贴
- - '###'
  - 问题
- - '###'
  - 解决方案
- - '###'
  - 工作原理
- - '##'
  - 14.3 创建包含视觉内容的 Toast 通知
- - '###'
  - 问题
- - '###'
  - 解决方案
- - '###'
  - 工作原理
- - '##'
  - 14.4 创建带操作的 Toast 通知
- - '###'
  - 问题
- - '###'
  - 解决方案
- - '###'
  - 工作原理
- - '##'
  - 14.5 创建定时磁贴和 Toast 通知
- - '###'
  - 问题
- - '###'
  - 解决方案
- - '###'
  - 工作原理
- - '##'
  - 14.6 在磁贴上创建或更新徽章
- - '###'
  - 问题
- - '###'
  - 解决方案
- - '###'
  - 工作原理
- - '#'
  - 第 15 章：设备功能
- - '##'
  - 15.1 如何在应用包清单中指定设备功能
- - '###'
  - 问题
- - '###'
  - 解决方案
- - '###'
  - 工作原理
- - '##'
  - 15.2 如何为 Windows 应用的蓝牙指定设备功能
- - '###'
  - 问题
- - '###'
  - 解决方案
- - '###'
  - 工作原理
- - '##'
  - 15.3 如何查找 UWP 应用可用的设备
- - '###'
  - 问题
- - '###'
  - 解决方案
- - '###'
  - 工作原理
- - '##'
  - 15.4 如何创建音频流并基于纯文本输出语音
- - '###'
  - 问题
- - '###'
  - 解决方案
- - '###'
  - 工作原理
- - '##'
  - 15.5 如何为语音识别指定识别约束
- - '###'
  - 问题
- - '###'
  - 解决方案
- - '###'
  - 工作原理
- - '##'
  - 15.6 如何使用 Cortana 语音命令在前台启动应用
- - '###'
  - 问题
- - '###'
  - 解决方案
- - '###'
  - 工作原理
- - '#'
  - 第 16 章：其他工具
- - '##'
  - 16.1 JavaScript 控制台窗口
- - '###'
  - 问题
- - '###'
  - 解决方案
- - '###'
  - 工作原理
- - '##'
  - 16.2 DOM 资源管理器
- - '###'
  - 问题
- - '###'
  - 解决方案
- - '###'
  - 工作原理
- - '##'
  - 16.3 诊断工具
- - '###'
  - 问题
- - '###'
  - 解决方案
- - '###'
  - 工作原理
- - '##'
  - 16.4 Windows 10 移动模拟器：附加工具
- - '###'
  - 问题
- - '###'
  - 解决方案
- - '###'
  - 工作原理
- - '####'
  - 模拟鼠标输入
- - '####'
  - 近场通信 (NFC)
- - '####'
  - 多点触控输入
- - '####'
  - 加速度计
- - '####'
  - 位置
- - '####'
  - 网络
- - '#'
  - 第 17 章：旁加载和 Windows 应用认证工具包
- - '##'
  - 17.1 旁加载您的应用
- - '###'
  - 问题
- - '###'
  - 解决方案
- - '###'
  - 工作原理
- - '##'
  - 17.2 分别安装证书和包
- - '###'
  - 问题
- - '###'
  - 解决方案
- - '###'
  - 工作原理
- - '##'
  - 17.3 使用 Windows 应用认证工具包验证你的 Windows 应用
- - '###'
  - 问题
- - '###'
  - 解决方案
- - '###'
  - 工作原理
- - '##'
  - 17.4 在远程 Windows 10 设备上验证应用包
- - '###'
  - 问题
- - '###'
  - 解决方案
- - '###'
  - 工作原理
- - '#'
  - 第 18 章：商店与盈利
- - '##'
  - 18.1 创建 Windows 应用开发者帐户
- - '###'
  - 问题
- - '###'
  - 解决方案
- - '####'
  - 通过 Windows 开发人员中心访问帐户注册
- - '####'
  - 通过 Visual Studio 访问帐户注册
- - '##'
  - 18.2 为 Windows 10 打包通用 Windows 平台应用程序
- - '###'
  - 问题
- - '###'
  - 解决方案
- - '###'
  - 工作原理
- - '####'
  - 配置应用包
- - '####'
  - 创建应用包
- - '##'
  - 18.3 向 Windows 应用商店提交应用
- - '###'
  - 问题
- - '###'
  - 解决方案
- - '##'
  - 18.4 在 UWP 应用中使用 Windows Ad Mediation
- - '###'
  - 问题
- - '###'
  - 解决方案
- - '##'
  - 18.5 在应用中显示广告
- - '###'
  - 问题
- - '###'
  - 解决方案
- - '#'
  - 索引
