name: Android Apps for Absolute Beginners
name_cn: Android 应用入门指南
slug: android-apps-for-absolute-beginners
toc:
- - '##'
  - 目录
- - '##'
  - 引言
- - '##'
  - 致谢
- - '##'
  - 关于作者
- - '##'
  - 关于技术审校者
- - '#'
  - 第一部分：获取 Android，开始起步
- - '##'
  - 第一章：Android 介绍
- - '###'
  - 使用 Android：最佳之处
- - '###'
  - 使用 Android 开发：挑战与难点
- - '###'
  - 理解 Android 的传承及其对你的影响
- - '###'
  - 理解 Android 的未来
- - '##'
  - 本书后续内容预览
- - '###'
  - 剩余章节详解
- - '##'
  - 2. 介绍 Android Studio
- - '###'
  - 理解什么是集成开发环境（IDE）
- - '###'
  - Android Studio 的历史与渊源
- - '####'
  - 为你的平台下载 Android Studio 安装程序
- - '###'
  - 了解 Android Studio 版本
- - '###'
  - 理解 Android Studio 与 Android SDK 的协同工作原理
- - '####'
  - 为使用 Android Studio 做准备
- - '###'
  - 为 Android 开发选择台式机或笔记本电脑硬件
- - '###'
  - 为你的计算机选择操作系统
- - '####'
  - 继续下载安装程序
- - '####'
  - 在 Windows 上安装 Android Studio
- - '####'
  - 在 macOS 上安装 Android Studio
- - '####'
  - 在 Linux 上安装 Android Studio
- - '###'
  - 安装后继续配置 Android Studio
- - '###'
  - 使用 Android Studio 的替代方案
- - '####'
  - Eclipse
- - '####'
  - IntelliJ IDEA
- - '####'
  - 针对多操作系统和移动平台的工具
- - '####'
  - 传统平台无关的开发工具
- - '#'
  - 你的第一个 Android 应用，现在就动手！
- - '##'
  - 创建你的第一个安卓虚拟设备
- - '##'
  - 安卓软件开发工具包：再看一眼
- - '##'
  - 开始创建你的第一个安卓应用！
- - '###'
  - 使用旧版 Android 支持库
- - '###'
  - 编写你的第一段代码
- - '###'
  - 准备运行你的应用程序
- - '##'
  - 安装（附加）SDK 软件包
- - '###'
  - 运行你的应用
- - '##'
  - 探索你的第一个项目
- - '###'
  - 查看整个 Android 项目结构
- - '####'
  - 使用清单文件
- - '####'
  - 与 Java 互动
- - '####'
  - 善用资源
- - '#####'
  - 可绘制对象
- - '#####'
  - 布局
- - '####'
  - Mipmaps
- - '####'
  - 从 Values 中寻找价值
- - '####'
  - 使用 Gradle 文件构建一切
- - '#####'
  - 理解 SDK 版本参数
- - '#####'
  - 理解应用程序版本管理
- - '#####'
  - 包含向前与向后版本支持的库
- - '##'
  - 解释 Android 应用的关键逻辑构建块
- - '###'
  - Activity（活动）
- - '###'
  - Intent（意图）
- - '###'
  - Service（服务）
- - '###'
  - Content Provider（内容提供器）
- - '##'
  - 总结
- - '#'
  - 5. 深入理解 Android Studio
- - '##'
  - 从项目资源管理器开始
- - '###'
  - 轻松切换项目资源管理器视图
- - '###'
  - 使用项目资源管理器的上下文菜单
- - '##'
  - 使用 Android Studio 运行和调试
- - '###'
  - 使用运行配置运行：回顾
- - '####'
  - 运行配置：常规选项
- - '####'
  - 运行配置：杂项
- - '####'
  - 运行配置：调试器
- - '####'
  - 运行配置：性能分析
- - '###'
  - 使用 AVD 和已连接的设备进行更深入的运行
- - '##'
  - 重温 AVD 管理器
- - '##'
  - 在真实设备上运行你的代码
- - '##'
  - 调试而非运行代码
- - '###'
  - 设置和清除断点
- - '###'
  - 启动应用进行调试
- - '###'
  - 调试时单步执行代码
- - '###'
  - 附加调试器
- - '##'
  - 查看已运行的内容
- - '###'
  - 理解你的构建过程
- - '##'
  - 理解事件日志中的事件
- - '##'
  - 理解 Logcat
- - '##'
  - 重新审视 SDK Manager
- - '##'
  - 突出 Android Studio 的其他主要功能
- - '##'
  - 总结
- - '#'
  - 6. 掌握你的整个开发者生态系统
- - '##'
  - 选择专用开发者硬件
- - '###'
  - 如何选择适合你的 CPU
- - '###'
  - 内存再多也不嫌多！
- - '###'
  - 存储一切！
- - '###'
  - 查看一切！
- - '###'
  - 整合所有配置！
- - '##'
  - 测试手机和平板
- - '###'
  - 选项 1：全虚拟测试
- - '###'
  - 选项 2：虚拟起步，辅以顶级设备
- - '###'
  - 选项 3：买，买，再买点
- - '###'
  - 选项 4：他人的硬件
- - '##'
  - 使用构建工具进行构建
- - '###'
  - 更新你的 `gradle.properties` 文件
- - '###'
  - 使用 Gradle 命令行
- - '###'
  - 访问 `gradle.org` 了解更多
- - '##'
  - 使用源代码管理来管理代码
- - '##'
  - 完善你的软件工具箱
- - '##'
  - 总结
- - '#'
  - 第二部分：掌握 Android 开发技能
- - '##'
  - 7. 介绍用于 Android 开发的 Java
- - '###'
  - Android 的其他开发语言选择
- - '##'
  - Java，无处不在
- - '###'
  - Java 安全
- - '###'
  - Android 的 Java 时间扭曲
- - '###'
  - 使用 JDK 安装学习 Java
- - '###'
  - 代码中的第一个 Java 概念
- - '###'
  - 核心概念：数据类型与变量
- - '###'
  - 核心概念：Java 中的分支与循环结构 – If、While、For
- - '###'
  - Android 开发的关键 Java 构建模块
- - '####'
  - 代码结构
- - '####'
  - Android 与 Main
- - '####'
  - 理解面向对象设计、类和对象
- - '####'
  - 使用类方法和数据成员
- - '#####'
  - 培养 Java 特定编码知识
- - '#####'
  - 接口与实现
- - '#####'
  - 线程与并发
- - '#####'
  - 垃圾回收
- - '#####'
  - 异常处理
- - '#####'
  - 文件处理
- - '#####'
  - 泛型
- - '#####'
  - 集合
- - '##'
  - 总结
- - '#'
  - 8. 为 Android 开发介绍 XML
- - '##'
  - XML 入门
- - '###'
  - XML 版本与编码
- - '###'
  - XML 元素
- - '###'
  - XML 属性
- - '###'
  - XML 值
- - '###'
  - XML 命名空间
- - '###'
  - XML 世界的其他部分
- - '####'
  - 1. CDATA
- - '####'
  - 2. XML 路径和 XQuery
- - '####'
  - 3. XSLT 和转换
- - '##'
  - 在 Android 应用中使用 XML
- - '###'
  - 审视 Android 清单 XML 文件
- - '###'
  - 使用 XML 进行资源定义
- - '####'
  - 更改颜色
- - '###'
  - 增加描述性
- - '###'
  - 用 XML 定义 Activity 布局
- - '##'
  - 本章小结
- - '#'
  - 9. 探索 Android 概念：核心 UI 控件
- - '##'
  - 一切始于 `View`
- - '##'
  - 源自 `View` 的关键方法
- - '##'
  - 源自 `View` 的关键属性和特性
- - '##'
  - Android 核心 UI 控件简介
- - '###'
  - 用 `TextView` 标记内容
- - '##'
  - 打造完美 UI 的按钮
- - '##'
  - 借助 ImageView 和 ImageButton 获取图像
- - '##'
  - 使用`EditText`编辑和输入文本
- - '##'
  - 初探`CheckBox`
- - '##'
  - 用 Switch 进行切换
- - '##'
  - 使用单选按钮选择项目
- - '##'
  - 学习更多 UI 小部件
- - '##'
  - 本章小结
- - '#'
  - 10. 探索 Android 概念：布局与更多内容
- - '###'
  - 什么是 Android Jetpack
- - '###'
  - 使用流行的布局设计
- - '###'
  - 重新审视约束布局
- - '####'
  - 进入流动布局
- - '####'
  - 使用 Layer 进行分层
- - '####'
  - 使用 Motion 实现动画
- - '###'
  - 使用相对布局
- - '####'
  - 相对于父容器放置小部件
- - '#####'
  - 3. `android:layout_alignParentStart`
- - '#####'
  - 4. `android:layout_alignParentEnd`
- - '#####'
  - 5. `android:layout_centerHorizontal`
- - '#####'
  - 6. `android:layout_centerVertical`
- - '####'
  - 使用 ID 控制相对布局属性
- - '####'
  - 相对定位属性
- - '####'
  - 使用 RelativeLayout 的示例
- - '####'
  - 相对布局中的重叠控件
- - '###'
  - 使用线性布局进行排列
- - '####'
  - 掌握 `LinearLayout` 的五大主要限定符
- - '####'
  - 一个 `LinearLayout` 示例
- - '#####'
  - 运行无支持 Java 逻辑的示例
- - '#####'
  - 实现方向和重力变化的 Java 逻辑
- - '###'
  - 更多布局选项
- - '####'
  - 表格布局
- - '####'
  - 网格布局
- - '###'
  - 掌握基于 XML 的布局与 Java 逻辑：两全其美！
- - '####'
  - 在 Java 代码中连接 XML 布局定义
- - '#####'
  - 通过`ButtonAgain`重温 MyFirstApp
- - '##'
  - 总结
- - '#'
  - 11. 探索 Android 概念：深入理解 Activity
- - '##'
  - 深入探索 Android 活动生命周期
- - '###'
  - 理解 Activity 生命周期回调方法
- - '####'
  - '`onCreate()`'
- - '####'
  - '`onStart()`'
- - '####'
  - '`onRestoreInstanceState()`'
- - '####'
  - '`onResume()`'
- - '####'
  - '`onPause()`'
- - '####'
  - '`onStop()`'
- - '####'
  - '`onSaveInstanceState()`'
- - '####'
  - '`onRestart()`'
- - '####'
  - '`onRetainNonConfigurationInstance()`'
- - '####'
  - '`onDestroy()`'
- - '##'
  - 领悟 Activity 生命周期的目标
- - '##'
  - 管理 Activity 配置变更
- - '###'
  - 使用默认方法处理配置变更
- - '##'
  - 总结
- - '#'
  - 12. 初识 Fragment
- - '##'
  - 从 Fragment 类开始
- - '##'
  - Fragment 与向后兼容性
- - '##'
  - 为应用使用基于 Fragment 的设计
- - '###'
  - 以碎片化思维进行设计
- - '##'
  - 使用碎片生命周期
- - '###'
  - 审视碎片生命周期回调方法
- - '####'
  - '`onInflate()`'
- - '####'
  - '`onCreate()`'
- - '####'
  - '`onAttach()`'
- - '####'
  - '`onCreateView()`'
- - '####'
  - '`onViewCreated()`'
- - '####'
  - '`onViewStateRestored()`'
- - '####'
  - '`onStart()`'
- - '####'
  - '`onResume()`'
- - '####'
  - '`onPause()`'
- - '####'
  - '`onSaveInstanceState()`'
- - '####'
  - '`onStop()`'
- - '####'
  - '`onDestroyView()`'
- - '####'
  - '`onDestroy()`'
- - '####'
  - '`onDetach()`'
- - '###'
  - 从片段生命周期事件简单入手
- - '##'
  - 创建基于片段的应用程序
- - '###'
  - 创建片段布局：颜色列表
- - '###'
  - 创建片段布局：颜色详情
- - '###'
  - 颜色详情的单面板父 Activity
- - '###'
  - 颜色详情的双面板父 Activity
- - '###'
  - 选择要填充的布局
- - '###'
  - 为片段编写代码
- - '###'
  - ColorFragmentExample 示例
- - '###'
  - 运行中的 ColorFragmentExample
- - '##'
  - 总结
- - '#'
  - 第三部分：进阶
- - '##'
  - 13. 为 Android 处理声音、音频和音乐
- - '###'
  - 播放音频
- - '####'
  - 选择您的音频方法
- - '#####'
  - 使用原始音频资源
- - '#####'
  - 使用音频资产
- - '#####'
  - 使用文件存储存储音频
- - '#####'
  - 访问音频流服务
- - '###'
  - 使用 Media 包
- - '###'
  - 创建音频应用
- - '####'
  - 在资源文件夹与资产文件夹之间选择
- - '####'
  - 编写音频播放代码
- - '#####'
  - 简单方式播放音频
- - '#####'
  - 为 AudioPlayExample 编写 Java 逻辑
- - '###'
  - 即时播放的优缺点
- - '####'
  - 播放音频流
- - '###'
  - 探索其他播放选项
- - '###'
  - 录制音频
- - '####'
  - 使用 MediaRecorder 录制音频
- - '####'
  - '`AudioRecordExample` 代码详解'
- - '#####'
  - Android 支持的主要输出格式
- - '###'
  - 扩展您的开发者音频工具箱
- - '###'
  - 理解关键音频方面
- - '####'
  - 音频采样与频率
- - '####'
  - 音频分辨率
- - '####'
  - 编码、解码与数据丢失
- - '###'
  - 选择更多音频工具
- - '####'
  - 认识 Audacity
- - '####'
  - 使用 WavePad
- - '####'
  - 苹果 Mac 用户的选择：GarageBand
- - '##'
  - 总结
- - '#'
  - 14. 在 Android 中处理视频与电影
- - '##'
  - 播放视频
- - '###'
  - 设计基于 `VideoView` 的布局
- - '###'
  - 在代码中控制视频播放
- - '##'
  - 理解关键视频概念
- - '###'
  - 比特率
- - '###'
  - 帧率
- - '###'
  - 编解码器
- - '##'
  - 理解视频容器与子编解码器的复杂世界
- - '##'
  - 扩展你的开发者视频工具集
- - '###'
  - 审视你可用的视频编辑工具范围
- - '###'
  - 流行的开源视频编辑套件
- - '###'
  - 流行的商业视频编辑套件
- - '##'
  - 介绍用于视频编辑的 HandBrake
- - '###'
  - 下载与安装 HandBrake
- - '###'
  - 运行与使用 HandBrake
- - '##'
  - Android 视频进阶
- - '##'
  - 本章小结
- - '#'
  - 15. 通知简介
- - '##'
  - 配置通知
- - '##'
  - 使用通知对象自定义通知
- - '###'
  - 了解增强通知的旧方式和新方式
- - '##'
  - 为通知添加声音
- - '##'
  - 使用设备灯光进行通知
- - '##'
  - 振动吧！
- - '##'
  - 为通知添加图标
- - '###'
  - 理解 `PendingIntent`
- - '###'
  - 不同 Android 版本的图标尺寸
- - '###'
  - 浮动数字以增加信息
- - '###'
  - 在 API 级别中引入通知渠道
- - '###'
  - 通知的实际应用
- - '###'
  - 支持创建通知的逻辑
- - '##'
  - 总结
- - '#'
  - 16. 使用通话探索设备能力
- - '##'
  - 掌控通话
- - '###'
  - 指定电话支持
- - '###'
  - 使电话支持变为可选
- - '##'
  - 拨打电话
- - '##'
  - 注意事项
- - '##'
  - 设计 CallExample 应用界面
- - '###'
  - Android 输入法框架
- - '##'
  - CallExample 应用的工作逻辑
- - '###'
  - 发起 ACTION_DIAL 通话
- - '###'
  - 发起 ACTION_CALL 通话
- - '###'
  - 处理来电
- - '#'
  - 17. 理解意图、事件和接收器
- - '##'
  - 使用多 Activity 与 Android Intents
- - '###'
  - 介绍 Android Intents
- - '###'
  - 理解 Intent 行为
- - '####'
  - 适用于各种场景的 Intent Action
- - '####'
  - 理解 Intent 路由
- - '####'
  - 在 Manifest 中包含 Intent
- - '####'
  - 使用 Android 的验证链接
- - '###'
  - 一探意图启动的活动
- - '####'
  - 决定活动的依赖关系
- - '####'
  - 创建意图
- - '####'
  - 启动意图调用的活动
- - '###'
  - 介绍接收器
- - '####'
  - 无需 UI 时使用接收器
- - '####'
  - 处理接收器的限制
- - '###'
  - 总结
- - '#'
  - 18. 介绍 Android 服务
- - '##'
  - 得益于其 Linux 操作系统血统
- - '##'
  - 服务背景
- - '###'
  - 使用 WorkManager 作为服务的替代方案
- - '##'
  - 开始创建你自己的服务
- - '###'
  - 实现服务类
- - '###'
  - 通过回调管理服务生命周期
- - '###'
  - 为服务提供清单条目
- - '##'
  - 服务声明与通信
- - '###'
  - 服务通信
- - '####'
  - 客户端到服务的通信
- - '###'
  - 使用 `startService()` 调用命令
- - '####'
  - 2. 使用 `stopSelf()` 调用编写你的服务
- - '###'
  - 使用服务的绑定方法
- - '####'
  - 警告
- - '###'
  - 服务到客户端的通信
- - '####'
  - 使用 `bindService()` 方法进行所有通信
- - '###'
  - 意图与广播接收器
- - '####'
  - 使用 PendingIntent 对象
- - '####'
  - 使用 Messenger 和 Message 对象
- - '###'
  - 使用独立消息传递
- - '###'
  - 创建回调和监听器
- - '###'
  - 使用通知
- - '##'
  - 服务实战
- - '###'
  - 选择服务设计
- - '###'
  - 创建服务的 Java 逻辑
- - '###'
  - 创建使用服务的示例客户端
- - '###'
  - 实际测试服务
- - '##'
  - 小结
- - '#'
  - 19. 在 Android 中处理文件
- - '##'
  - 使用资源文件和原始文件
- - '###'
  - 基于原始资源方法的优势
- - '###'
  - 基于原始资源方法的劣势
- - '##'
  - 从资源文件填充列表
- - '##'
  - 处理文件系统中的文件
- - '###'
  - Android 的文件系统模型
- - '###'
  - 读写文件的权限
- - '###'
  - 实战检查外部文件
- - '###'
  - 保存和读取文件的原理
- - '###'
  - 助力优化输入法
- - '###'
  - 保存和读取文件的实际操作
- - '###'
  - 确保外部存储在需要时可用
- - '##'
  - Android 文件系统的其他注意事项
- - '###'
  - Android 文件系统发展史
- - '###'
  - 避免文件输入/输出引起的 UI 问题
- - '###'
  - 使用 StrictMode 分析应用性能
- - '####'
  - 警告
- - '###'
  - 将逻辑移至异步线程
- - '##'
  - 本章小结
- - '#'
  - 20. 在 Android 中使用数据库
- - '##'
  - 使用 SQLite：世界上最流行的数据库！
- - '###'
  - 注意
- - '##'
  - 快速学习用于 Android 开发的 SQLite
- - '##'
  - 为你的应用程序创建 SQLite 数据库
- - '##'
  - SQLiteExample 应用程序介绍
- - '##'
  - 创建数据库驱动的 Activity
- - '###'
  - 关键实现步骤与 SQLite 查询方法
- - '####'
  - 为 SQLite 和 Android 选择查询方法
- - '#####'
  - 使用查询构建过程
- - '#####'
  - 使用 SQL 的原始能力
- - '####'
  - 使用游标管理查询结果
- - '####'
  - 更新数据
- - '####'
  - 删除数据
- - '####'
  - 使用 Room 持久化库
- - '##'
  - 为 Android 打包和管理 SQLite 数据库
- - '##'
  - 管理 Android 存储以提升数据库性能
- - '###'
  - ACID 数据库原则
- - '###'
  - 将 SQLite 数据库打包到应用中
- - '##'
  - 选择 SQLite 管理工具来准备要打包的数据库
- - '###'
  - 使用内置工具
- - '###'
  - 使用第三方数据库工具
- - '##'
  - 总结
- - '##'
  - 索引
- - '###'
  - A
- - '###'
  - B
- - '###'
  - C
- - '###'
  - D
- - '###'
  - E
- - '###'
  - F
- - '###'
  - G
- - '###'
  - H
- - '###'
  - I
- - '###'
  - J
- - '###'
  - K
- - '###'
  - L
- - '###'
  - M
- - '###'
  - N
- - '###'
  - O
- - '###'
  - P
- - '###'
  - Q
- - '###'
  - R
- - '###'
  - S
- - '###'
  - T
- - '###'
  - U
- - '###'
  - V
- - '###'
  - W
- - '###'
  - X， Y， Z
