name: Learn Cocoa On The Mac
name_cn: Mac 上 Cocoa 学习指南
slug: learn-cocoa-on-the-mac
toc:
- - '#'
  - 学习 Mac 上的 Cocoa
- - '##'
  - 前言
- - '##'
  - 关于作者
- - '##'
  - 彼得·克拉克
- - '##'
  - 关于技术审阅者
- - '##'
  - 致谢
- - '#'
  - 1. Cocoa 之道
- - '##'
  - 摘要
- - '###'
  - 25 年何止 25 年？
- - '##'
  - 准备一台 Mac 并下载工具
- - '##'
  - 下载源代码
- - '##'
  - 获取帮助
- - '##'
  - 开始前你需要了解的知识
- - '###'
  - 初次接触 Objective-C？
- - '##'
  - 准备好了吗？
- - '#'
  - 2. Hello, World
- - '##'
  - 构建“Hello, World”
- - '##'
  - 项目窗口概览
- - '##'
  - 探索 Nib 文件
- - '###'
  - 库
- - '##'
  - 拖出标签
- - '###'
  - 使用蓝色参考线
- - '##'
  - 检查器
- - '###'
  - 属性检查器
- - '###'
  - 更改标签的颜色和字体
- - '###'
  - 创建应用程序图标
- - '###'
  - 向项目中添加图标
- - '###'
  - 属性列表
- - '###'
  - 运行应用程序
- - '##'
  - 与世界分享我们的作品
- - '##'
  - 再见，“你好，世界”
- - '#'
  - 3. 灯光，摄像……动作！（以及输出口）
- - '##'
  - 框架，无处不在的框架
- - '###'
  - Foundation 框架
- - '###'
  - AppKit 框架
- - '###'
  - Cocoa 之道：模型-视图-控制器
- - '##'
  - Outlets、Actions 和控制器
- - '###'
  - 输出口（Outlets）
- - '###'
  - 动作（Actions）
- - '##'
  - 输出口与动作的实际应用
- - '##'
  - 总结
- - '#'
  - 4. 行动的号角
- - '##'
  - 声明输出口和操作
- - '###'
  - 声明输出口（Outlets）
- - '###'
  - 声明动作（Actions）
- - '####'
  - 但它们究竟是什么？
- - '##'
  - 输出口与动作实战，第二幕
- - '###'
  - 占位对象
- - '###'
  - 设置窗口
- - '##'
  - 设计窗口界面
- - '##'
  - 创建控制器类
- - '###'
  - 实现操作方法
- - '####'
  - 嵌套消息
- - '##'
  - 应用程序委托
- - '###'
  - 配置应用在窗口关闭时退出
- - '##'
  - 使用文档浏览器
- - '#'
  - 总结
- - '#'
  - 5. GUI 组件
- - '###'
  - 创建“反派追踪器”应用
- - '###'
  - 构建界面
- - '####'
  - 调出文本字段
- - '####'
  - 让它们选择日期
- - '####'
  - 创建组合框
- - '###'
  - 使用级别指示器显示评分
- - '###'
  - 在矩阵中添加单选按钮
- - '####'
  - 添加图像视图
- - '####'
  - 在矩阵中添加复选框
- - '####'
  - 配置弹出按钮
- - '###'
  - 插入文本视图
- - '###'
  - 进行逻辑分组
- - '###'
  - 调整大小
- - '##'
  - 连接 `VillainTrackerAppDelegate` 类
- - '##'
  - 开始编码
- - '###'
  - 标准化键名
- - '###'
  - 创建默认反派
- - '###'
  - 关注细节
- - '####'
  - 设置简单值
- - '###'
  - 复杂控件中的值
- - '##'
  - 响应输入
- - '##'
  - 总结
- - '#'
  - 6. 使用表格视图
- - '##'
  - 摘要
- - '#'
  - 为多个反派准备 VillainTrackerAppDelegate
- - '##'
  - 为表格视图腾出空间
- - '#'
  - Table View 内容模式与配置指南
- - '##'
  - 一个棘手的缩放问题，或者说，约束来救场了！
- - '###'
  - 创建与编辑约束
- - '##'
  - 为表格视图让路：代码篇
- - '###'
  - 表格视图需要协助
- - '###'
  - 添加更多反派
- - '###'
  - 选择反派角色
- - '###'
  - 停止你的邪恶行径！
- - '###'
  - 在表格视图中编辑
- - '###'
  - 总结
- - '#'
  - 7. Cocoa 绑定
- - '##'
  - 摘要
- - '##'
  - 绑定到简单控件
- - '###'
  - 添加标签视图
- - '###'
  - 绑定到 NSUserDefaultsController
- - '###'
  - 角色生成界面的绑定
- - '###'
  - 怪物生成界面的绑定
- - '###'
  - 地牢生成界面的绑定
- - '###'
  - 创建主窗口
- - '###'
  - 设置 DungeonThingAppDelegate
- - '###'
  - 定义常量
- - '###'
  - 创建操作方法
- - '##'
  - 绑定到表格视图
- - '###'
  - 使代码支持绑定
- - '###'
  - 规范的 init 方法
- - '###'
  - 配置表视图和文本视图
- - '###'
  - 创建与配置数组控制器
- - '###'
  - 通过数组控制器绑定表格显示
- - '###'
  - 通过数组控制器的选择绑定文本字段
- - '###'
  - 填充数组
- - '###'
  - 确保运行正常
- - '###'
  - 重复操作
- - '##'
  - 好了，但这是如何实现的？
- - '###'
  - 键值编码
- - '###'
  - 键值观察
- - '###'
  - Cocoa 绑定：工作原理
- - '##'
  - 总结
- - '#'
  - 8. Core Data 基础
- - '##'
  - 我们遗漏了什么
- - '##'
  - 创建 MythBase
- - '###'
  - 定义模型
- - '####'
  - 建模：是什么？
- - '####'
  - 使用 Xcode 的模型编辑器
- - '####'
  - 创建实体
- - '####'
  - 创建属性
- - '####'
  - 为 `goodness` 和 `power` 创建数值属性
- - '####'
  - 不支持类型的属性
- - '##'
  - 设计 GUI
- - '###'
  - 自动生成 GUI
- - '###'
  - 创建 MythBase 显示界面
- - '###'
  - 显示详细信息
- - '##'
  - 设置 Cocoa 绑定
- - '###'
  - 使用数组控制器进行绑定
- - '##'
  - 为表格视图配置绑定
- - '###'
  - 完成绑定：保存与搜索
- - '##'
  - 探索模板代码
- - '###'
  - App Delegate 接口
- - '###'
  - App Delegate 实现
- - '####'
  - '`applicationSupportDirectory` 方法'
- - '###'
  - '`managedObjectModel` 访问器方法'
- - '###'
  - 使用 `NSError` 进行错误处理
- - '###'
  - '`persistentStoreCoordinator` 访问器方法'
- - '####'
  - managedObjectContext 访问器方法
- - '####'
  - NSWindow 委托方法
- - '####'
  - 'saveAction: 操作方法'
- - '###'
  - '`NSApplication` 代理方法'
- - '##'
  - 添加业务逻辑
- - '###'
  - 创建 `MythicalPerson` 类
- - '###'
  - 验证单个属性
- - '###'
  - 验证多个属性
- - '###'
  - 创建自定义属性
- - '##'
  - 小结
- - '#'
  - Core Data 关系
- - '##'
  - 建模新实体与关系
- - '###'
  - 模型版本控制与迁移
- - '###'
  - 准备多个模型版本
- - '###'
  - 添加新实体
- - '###'
  - 添加关系
- - '###'
  - 创建一个简单的迁移
- - '###'
  - 运行时间
- - '##'
  - 更新图形用户界面
- - '###'
  - 创建乐队窗口
- - '#'
  - 设置 Cocoa 绑定
- - '##'
  - 为数组控制器赋予有用的名称
- - '###'
  - 将人物关联到乐队
- - '###'
  - 显示乐队成员
- - '#'
  - 创建场馆窗口
- - '#'
  - 为乐队窗口添加演出列表
- - '##'
  - 总结
- - '#'
  - 10. 使用条件进行搜索和检索 Core Data
- - '##'
  - 摘要
- - '##'
  - 创建 QuoteMonger
- - '#'
  - 创建项目及其数据模型
- - '#'
  - 数据录入窗口
- - '##'
  - 分两部分的窗口
- - '##'
  - 显示节目
- - '####'
  - 引用引文
- - '###'
  - 输入一些初始引文
- - '###'
  - 创建引用查找器窗口
- - '##'
  - 使用 `NSPredicate` 限制结果
- - '###'
  - 创建谓词
- - '###'
  - 在 Xcode 中指定 NSAppController 的谓词
- - '###'
  - 用户自定义谓词
- - '#'
  - 在应用委托中添加谓词
- - '#'
  - 在搜索窗口中添加谓词编辑器
- - '#'
  - 配置谓词编辑器
- - '#'
  - 保存谓词
- - '##'
  - 总结
- - '#'
  - 11. 窗口、菜单和表单
- - '#'
  - NSWindow 与 NSPanel
- - '##'
  - 处理输入
- - '##'
  - 使用面板，还是不用面板
- - '###'
  - Window Attributes
- - '###'
  - 标准系统面板
- - '###'
  - 颜色面板
- - '###'
  - 响应者链
- - '###'
  - 字体面板
- - '##'
  - 拥有独立 Nib 的控制器
- - '###'
  - 使用 `NSWindowController` 加载 Nib 文件
- - '###'
  - 子类化 `NSWindowController`
- - '###'
  - 模态窗口
- - '###'
  - NSAlert 函数
- - '###'
  - 打开面板与保存面板
- - '##'
  - 系统菜单
- - '###'
  - 标准应用程序菜单项
- - '###'
  - 自定义菜单
- - '###'
  - 通过绑定启用/禁用
- - '###'
  - 通过第一响应者启用/禁用
- - '##'
  - 表单
- - '##'
  - 总结
- - '#'
  - 12. 基于文档的应用程序
- - '##'
  - 摘要
- - '##'
  - 创建 ColorMix 应用程序
- - '###'
  - 检查默认的 Nib 文件
- - '###'
  - 定义模型
- - '###'
  - 设置两种颜色
- - '###'
  - 最简单的图形界面
- - '###'
  - 创建默认 ColorSet
- - '##'
  - 排版后的文本
- - '##'
  - 确定文件格式
- - '##'
  - 添加颜色
- - '###'
  - CMColorBlendView 类
- - '##'
  - 向 GUI 添加混合颜色
- - '##'
  - 关于撤销和重做
- - '###'
  - 撤销栈
- - '##'
  - 总结
- - '#'
  - 13. 异常、信号、错误与调试
- - '##'
  - 异常处理
- - '###'
  - 捕获异常
- - '###'
  - 异常在 Cocoa 中的有限作用
- - '###'
  - 创建测试平台
- - '###'
  - 调试器
- - '###'
  - '`NSInvalidArgumentException`'
- - '###'
  - NSRangeException
- - '###'
  - 其余异常
- - '#'
  - 比异常更糟：信号致死
- - '##'
  - NSError
- - '###'
  - 域与代码
- - '###'
  - 识别错误
- - '###'
  - 呈现错误
- - '##'
  - 总结
- - '#'
  - 14. Cocoa 中的绘图
- - '##'
  - 摘要
- - '##'
  - 基础
- - '###'
  - 视图坐标系统
- - '###'
  - 视图框（Frame Rectangle）与边界框（Bounds Rectangle）
- - '###'
  - 矩形、点与尺寸
- - '###'
  - 路径基础
- - '##'
  - 创建 NSView 子类
- - '###'
  - '基本绘图方法 drawRect:'
- - '###'
  - 图形状态
- - '#'
  - 路径辅助工具
- - '##'
  - 颜色与图形上下文
- - '##'
  - 超越颜色
- - '##'
  - 手动路径构建
- - '###'
  - 突破界限
- - '##'
  - LOLmaker
- - '#'
  - LOL 入门第一步
- - '#'
  - LOLView
- - '###'
  - 绘制位图
- - '###'
  - 让它滚动起来
- - '###'
  - 绘制文本
- - '#'
  - 本章小结
- - '#'
  - 15. 高级绘图主题
- - '##'
  - 摘要
- - '##'
  - 编辑曲线
- - '###'
  - 准备工作
- - '###'
  - 贝塞尔曲线基础设施
- - '###'
  - 绘制曲线
- - '###'
  - 监听鼠标
- - '###'
  - 一点小改进
- - '#'
  - 核心动画：入门指南
- - '##'
  - Core Animation 基础
- - '###'
  - 隐式动画
- - '###'
  - 显式动画
- - '#'
  - import <Cocoa/Cocoa.h>
- - '#'
  - 动画分组
- - '#'
  - Tab View 与 App Delegate 的实现
- - '##'
  - 总结
- - '#'
  - 16. 文件操作
- - '##'
  - 摘要
- - '##'
  - 隐式文件访问
- - '##'
  - 高级文件操作
- - '###'
  - 关于那个文件：代码部分
- - '###'
  - 关于那个文件：图形界面
- - '##'
  - 总结
- - '#'
  - 17. 并发
- - '#'
  - SlowWorker
- - '#'
  - 线程基础
- - '##'
  - 工作单元
- - '##'
  - 操作队列
- - '###'
  - 成为代码块高手
- - '###'
  - 让 `SlowWorker` 焕发活力
- - '###'
  - 主线程需求
- - '##'
  - GCD：底层队列
- - '###'
  - 再次改进 SlowWorker
- - '###'
  - 别忘记主线程
- - '###'
  - GCD 中的并发代码块
- - '##'
  - 一点并发，大有裨益
- - '#'
  - 18. 未来路径
- - '##'
  - 摘要
- - '##'
  - 更多 Cocoa 特性
- - '###'
  - 通知
- - '###'
  - 块
- - '###'
  - 枚举
- - '###'
  - 使用 Block 观察通知
- - '####'
  - 弱化 Blocks 的指针
- - '####'
  - 过滤
- - '##'
  - 用其他语言开发 Cocoa
- - '###'
  - PyObjC
- - '###'
  - MacRuby
- - '###'
  - Nu
- - '###'
  - JavaScript
- - '###'
  - F-Script
- - '##'
  - 移植的 Cocoa
- - '###'
  - Cocoa Touch
- - '###'
  - GNUstep 与 Cocotron
- - '###'
  - Cappuccino/Objective-J
- - '##'
  - 在一切的终点
- - '#'
  - Mac 上的 Cocoa
- - '##'
  - 索引
- - '###'
  - A
- - '###'
  - B
- - '###'
  - C
- - '###'
  - Cocoa 绑定
- - '###'
  - Cocoa 技能
- - '###'
  - ColorMix 应用
- - '###'
  - 并发
- - '###'
  - 内容视图
- - '###'
  - Core Data
- - '###'
  - Core Data 关系
- - '###'
  - D
- - '###'
  - E
- - '###'
  - F
- - '###'
  - G
- - '###'
  - H
- - '###'
  - I
- - '###'
  - J
- - '###'
  - K
- - '###'
  - L
- - '###'
  - M
- - '###'
  - N
- - '###'
  - O
- - '###'
  - P
- - '###'
  - Q
- - '###'
  - R
- - '###'
  - S
- - '###'
  - T
- - '###'
  - U
- - '###'
  - V
- - '###'
  - W
- - '###'
  - X, Y, Z
