name: Learn Cocos2d 2
name_cn: Cocos2d 2 学习指南
slug: learn-cocos2d-2
toc:
- - '#'
  - 学习 cocos2d 2
- - '##'
  - 目录一览
- - '#'
  - 第 1 章：引言
- - '##'
  - 第三版的新内容有哪些？
- - '##'
  - 关于 ARC
- - '##'
  - 为什么要在 iOS 上使用 cocos2d？
- - '###'
  - 它是免费的
- - '###'
  - 它是开源的
- - '###'
  - 它用的是 Objective-C，懂了吗？
- - '###'
  - 它是 2D 的
- - '###'
  - 它有物理引擎
- - '###'
  - 它不那么技术化
- - '###'
  - 它仍然是编程
- - '###'
  - 它有一个很棒的社区
- - '##'
  - cocos2d 社区
- - '###'
  - 为什么用 Kobold2D 而不用 cocos2d-iphone？
- - '###'
  - 其他 cocos2d 游戏引擎
- - '##'
  - 这本书适合你
- - '##'
  - 先决条件
- - '###'
  - 编程经验
- - '###'
  - Objective-C
- - '##'
  - 你将学到什么
- - '###'
  - iOS 游戏开发初学者将学到什么
- - '###'
  - iOS 应用开发者将学到什么
- - '###'
  - Cocos2d 开发者将学到什么
- - '##'
  - 本书内容
- - '##'
  - 书籍概览
- - '##'
  - 如何获取本书源代码
- - '##'
  - 问题与反馈
- - '#'
  - 第 2 章：入门
- - '##'
  - 入门所需准备
- - '###'
  - 系统要求
- - '##'
  - 注册成为 iOS 开发者
- - '##'
  - 证书和配置文件
- - '##'
  - 下载并安装 Xcode 和 iOS SDK
- - '##'
  - 下载 cocos2d 或 Kobold2D
- - '##'
  - 安装 Kobold2D
- - '##'
  - 创建一个 Kobold2D 项目
- - '##'
  - 安装 cocos2d 及其 Xcode 项目模板
- - '##'
  - 如何创建 cocos2d 项目
- - '##'
  - 如何在 cocos2d 项目中启用 ARC
- - '###'
  - 将 cocos2d 代码构建为静态库
- - '##'
  - 重构项目的源代码以使用 ARC
- - '##'
  - cocos2d 和 Kobold2D 应用程序的剖析
- - '###'
  - 注意事项
- - '###'
  - 支持文件群组
- - '###'
  - main 函数
- - '###'
  - 前缀头文件
- - '##'
  - AppDelegate 类
- - '###'
  - 在纯 cocos2d 项目中，AppDelegate 类中最常修改的代码行是：
- - '###'
  - 显示统计信息
- - '###'
  - 动画间隔
- - '##'
  - HelloWorldLayer
- - '###'
  - 使用 ARC 的内存管理
- - '###'
  - 改变世界
- - '###'
  - 你还应该知道什么
- - '##'
  - iOS 设备
- - '##'
  - 关于内存使用
- - '##'
  - iOS 模拟器
- - '###'
  - 无法评估性能
- - '###'
  - iOS 模拟器的性能注意事项
- - '###'
  - 无法评估内存使用情况
- - '###'
  - 无法使用所有 iOS 设备功能
- - '###'
  - 运行时行为可能存在差异
- - '##'
  - 关于性能与日志记录
- - '#'
  - 第 3 章：基础
- - '##'
  - cocos2d 场景图
- - '##'
  - CCNode 类层级结构
- - '###'
  - CCNode
- - '###'
  - 使用节点
- - '##'
  - 使用操作
- - '##'
  - 调度消息
- - '##'
  - 导演、场景和层
- - '###'
  - 导演
- - '###'
  - CCScene
- - '###'
  - 场景与内存
- - '##'
  - 压入和弹出场景
- - '##'
  - CCTransitionScene
- - '##'
  - CCLayer
- - '###'
  - 接收触摸事件
- - '###'
  - 接收加速计事件
- - '###'
  - 接收键盘事件
- - '###'
  - 接收鼠标事件
- - '##'
  - CCSprite
- - '##'
  - 揭秘锚点
- - '##'
  - CCLabelTTF
- - '##'
  - 菜单
- - '##'
  - 使用块的菜单项
- - '##'
  - 动作
- - '##'
  - 区间动作
- - '###'
  - Cocos2d 中的动作管理
- - '###'
  - 动作生命周期与可重用性
- - '###'
  - 动作序列
- - '###'
  - 缓动动作
- - '###'
  - 网格动作
- - '###'
  - 即时动作
- - '###'
  - CCCallFunc 动作
- - '###'
  - CCCallBlock 动作
- - '##'
  - 方向、单例、测试和 API 参考
- - '###'
  - 设备方向教程
- - '##'
  - cocos2d 中的单例
- - '##'
  - 官方 cocos2d API 参考文档
- - '##'
  - Kobold2D API 参考文档
- - '##'
  - Xcode 及其他环境中的 API 参考文档
- - '##'
  - 总结
- - '#'
  - 第 4 章：你的第一个游戏
- - '##'
  - 创建 DoodleDrop 项目
- - '###'
  - 从一个启用 ARC 的 cocos2d 项目开始
- - '##'
  - 创建 DoodleDrop 场景
- - '##'
  - 添加玩家精灵
- - '##'
  - 简单的加速度计输入
- - '##'
  - 首次测试运行
- - '##'
  - 玩家速度
- - '###'
  - GameLayer 实现获得 playerVelocity
- - '###'
  - 使用当前速度更新玩家位置
- - '##'
  - 添加障碍物
- - '###'
  - 为方便访问，将蜘蛛精灵初始化并添加到 CCArray 中
- - '##'
  - 介绍 CCLabelBMFont
- - '##'
  - 使用 Glyph Designer 创建位图字体
- - '##'
  - 简单播放音频
- - '##'
  - iPad 相关注意事项
- - '##'
  - 支持 Retina iPad
- - '##'
  - 一个通用应用还是两个独立应用？
- - '##'
  - 限制设备支持
- - '##'
  - 总结
- - '#'
  - 第 5 章：游戏构建模块
- - '##'
  - 处理多场景
- - '###'
  - 添加更多场景
- - '###'
  - 正在加载下一段，请稍候
- - '##'
  - 使用多个图层
- - '##'
  - 如何最好地实现关卡
- - '##'
  - 游戏关卡的设计策略
- - '###'
  - 场景作为关卡
- - '###'
  - 层作为关卡
- - '##'
  - CCLayerColor 与 CCLayerGradient
- - '##'
  - 从 CCSprite 派生子类化游戏对象
- - '##'
  - 使用 CCSprite 组合游戏对象
- - '##'
  - 奇妙的 CCNode 类
- - '###'
  - CCProgressTimer
- - '##'
  - CCParallaxNode
- - '##'
  - CCMotionStreak
- - '##'
  - 总结
- - '#'
  - 第 6 章：精灵深入解析
- - '##'
  - 视网膜显示屏
- - '###'
  - 新款 iPhone 机型与 Retina 显示屏
- - '##'
  - CCSpriteBatchNode
- - '##'
  - 何时使用 CCSpriteBatchNode
- - '##'
  - Sprites01 演示项目
- - '###'
  - 一个常见且致命的错误
- - '##'
  - 不使用 SpriteBatch 的子弹
- - '##'
  - 引入 CCSpriteBatchNode
- - '##'
  - 优化
- - '##'
  - 精灵动画的硬实现
- - '###'
  - 动画辅助类别
- - '##'
  - 使用纹理图集
- - '###'
  - 什么是纹理图集？
- - '###'
  - 介绍 TexturePacker
- - '##'
  - 为 TexturePacker 准备项目
- - '##'
  - 使用 TexturePacker 创建纹理图集
- - '###'
  - PVRTC2 和 PVRTC4 图像格式
- - '##'
  - 在 cocos2d 中使用纹理图集
- - '###'
  - 代码清单 6-13. Ship 类现在使用纹理图集作为初始帧和动画
- - '##'
  - 更新 CCAnimation 辅助类别
- - '###'
  - 代码清单 6-14. CCAnimation 辅助类别的 @interface
- - '###'
  - 代码清单 6-15. animationWithFrame 辅助方法使创建动画更简单
- - '##'
  - 合而为一，一即所有
- - '##'
  - 总结
- - '#'
  - 第 7 章：欢乐滚动
- - '##'
  - 高级视差滚动
- - '###'
  - 创建条带状背景
- - '##'
  - 在代码中重新创建背景
- - '##'
  - 移动视差背景
- - '##'
  - 视差速度因子
- - '##'
  - 滚向无限远
- - '##'
  - 修复闪烁
- - '##'
  - 重复、重复、再重复
- - '##'
  - 虚拟手柄
- - '###'
  - 初识 SneakyInput
- - '###'
  - 下载 SneakyInput
- - '###'
  - 集成 SneakyInput
- - '###'
  - 触摸按钮以射击
- - '##'
  - 为按钮添加皮肤
- - '##'
  - 控制操作
- - '##'
  - 数字控制器
- - '##'
  - 总结
- - '#'
  - 第 8 章：纵情射击
- - '##'
  - 添加 BulletCache 类
- - '##'
  - 让我们制造一些敌人
- - '###'
  - 游戏敌人设计：从规划到实现
- - '##'
  - Enemy 类
- - '###'
  - EnemyCache 类
- - '##'
  - 组件类
- - '##'
  - 射击目标
- - '##'
  - 为 Boss 添加生命值条
- - '###'
  - -(void) reset
- - '###'
  - -(void) update:(ccTime)delta
- - '##'
  - 总结
- - '#'
  - 第 9 章：粒子效果
- - '##'
  - 粒子效果示例
- - '##'
  - 以艰难的方式创建粒子效果
- - '##'
  - 子类化 CCParticleSystem
- - '###'
  - 自定义粒子效果
- - '##'
  - CCParticleSystem 属性
- - '###'
  - 方差属性
- - '###'
  - 粒子数量
- - '###'
  - 发射器持续时间
- - '###'
  - 发射器模式
- - '##'
  - ParticleEffectSelfMade
- - '###'
  - 发射器模式：重力模式
- - '###'
  - 发射器模式：半径模式
- - '###'
  - 粒子位置
- - '###'
  - 粒子大小
- - '###'
  - 粒子方向
- - '###'
  - 粒子生命周期
- - '###'
  - 粒子颜色
- - '###'
  - 粒子混合模式
- - '###'
  - 粒子纹理
- - '##'
  - Particle Designer
- - '###'
  - Particle Designer 介绍
- - '###'
  - 使用粒子设计器效果
- - '###'
  - 共享粒子效果
- - '##'
  - 总结
- - '#'
  - 第 10 章：使用 Tilemap
- - '##'
  - 在瓦片地图游戏中
- - '##'
  - 什么是瓦片地图？
- - '##'
  - 使用 TexturePacker 准备图像
- - '##'
  - Tiled (Qt) 地图编辑器
- - '###'
  - 创建新瓦片地图
- - '##'
  - 如何为 Retina 和 iPad 分辨率创建图块地图
- - '###'
  - 使用 iOS 设备上的 iTileMaps 创建地图
- - '##'
  - 设计瓦片地图
- - '##'
  - 在 Cocos2d 中使用正交瓦片地图
- - '###'
  - 定位被触摸的瓦片
- - '###'
  - 处理对象层
- - '###'
  - 绘制对象图层矩形
- - '###'
  - 滚动瓦片地图
- - '##'
  - 总结
- - '#'
  - 第 11 章：等距瓦片地图
- - '##'
  - 设计等距瓦片图形
- - '##'
  - 使用 Tiled 编辑等距瓦片地图
- - '###'
  - 创建新的等距瓦片地图
- - '###'
  - 创建新的等距图块集
- - '###'
  - 制定基本原则
- - '##'
  - 等距游戏编程
- - '###'
  - 在 Cocos2d 中加载等距地图
- - '###'
  - 为等距地图设置 Cocos2d
- - '###'
  - 定位等距瓦片
- - '###'
  - 滚动等距 Tilemap
- - '###'
  - 这个世界需要更好的结局
- - '##'
  - 添加可移动的玩家角色
- - '###'
  - 使玩家能移动到瓦片后方
- - '###'
  - 逐图块移动玩家
- - '###'
  - 阻止玩家碰撞
- - '##'
  - 向游戏中添加更多内容
- - '##'
  - 总结
- - '#'
  - 第 12 章：物理引擎
- - '##'
  - 物理引擎的基本概念
- - '##'
  - 物理引擎的局限性
- - '##'
  - 对决：Box2D vs. Chipmunk
- - '##'
  - Box2D
- - '###'
  - 遵循 Box2D 的规则世界
- - '###'
  - 限制移动范围至屏幕内
- - '###'
  - 转换坐标点
- - '###'
  - 向 Box2D 世界添加方块
- - '###'
  - 更新 Box2D 世界
- - '###'
  - 碰撞检测
- - '###'
  - 关节联合
- - '##'
  - Chipmunk
- - '###'
  - 太空中的 Chipmunk
- - '###'
  - 将方块限制在盒内
- - '###'
  - 添加廉价小方块
- - '###'
  - 更新 Chipmunk 空间
- - '###'
  - Chipmunk 碰撞路线
- - '###'
  - Chipmunk 的关节
- - '##'
  - 总结
- - '#'
  - 第 13 章：弹球游戏
- - '##'
  - 形状：凸多边形与逆时针方向
- - '##'
  - 使用 PhysicsEditor
- - '###'
  - 定义弹射杆形状
- - '###'
  - 定义桌面形状
- - '###'
  - 定义挡板
- - '###'
  - 定义缓冲器与球
- - '###'
  - 保存并发布
- - '##'
  - 弹球游戏编程
- - '###'
  - 强制竖屏方向
- - '###'
  - BodySprite 类
- - '###'
  - 创建弹球桌面
- - '###'
  - Box2D 调试绘制
- - '###'
  - 添加球
- - '###'
  - 强制球移动
- - '###'
  - 添加缓冲器
- - '###'
  - 弹射杆
- - '###'
  - 挡板
- - '###'
  - 小结
- - '#'
  - 第 14 章：Game Center
- - '##'
  - 启用 Game Center
- - '##'
  - 在 iTunes Connect 中创建应用
- - '##'
  - 设置排行榜和成就
- - '##'
  - AppController 和 NavigationController
- - '##'
  - 配置 Xcode 项目
- - '###'
  - Game Kit 框架参考
- - '##'
  - GameKitHelper 委托
- - '###'
  - 检查 Game Center 可用性
- - '###'
  - 块对象
- - '###'
  - 接收本地玩家的朋友列表
- - '##'
  - 排行榜
- - '##'
  - 成就
- - '##'
  - 匹配
- - '##'
  - 发送和接收数据
- - '#'
  - 第 15 章：Cocos2d 与 UIKit 视图
- - '##'
  - 什么是 Cocoa Touch？
- - '##'
  - 同时使用 Cocoa Touch 和 cocos2d
- - '###'
  - 为什么要把 Cocoa Touch 与 cocos2d 混合使用？
- - '###'
  - 混合使用 Cocoa Touch 与 cocos2d 的限制
- - '##'
  - Cocoa Touch 与 Cocos2d 有何不同？
- - '###'
  - 模型-视图-控制器模式
- - '###'
  - Cocos2d 的视图使用 OpenGL ES
- - '##'
  - 警报：你在 Cocos2d 中的第一个 UIKit 视图
- - '###'
  - 清单 15-1. 创建 UIAlertView 并显示在 cocos2d 视图（CCGLView 类）之上
- - '###'
  - 清单 15-2. 响应 UIAlertView 的 didDismissWithButtonIndex 消息
- - '##'
  - 在 cocos2d 应用中嵌入 UIKit 视图
- - '###'
  - 在 cocos2d 视图前方添加视图
- - '##'
  - 使用 UIImage 对 UITextField 进行皮肤定制
- - '##'
  - 在 cocos2d 视图后面添加视图
- - '###'
  - 添加使用 Interface Builder 设计的视图
- - '##'
  - 在 Cocoa Touch 应用中嵌入 cocos2d 视图
- - '###'
  - 使用 cocos2d 创建基于视图的应用项目
- - '###'
  - 设计混合应用的用户界面
- - '##'
  - 启动你的 cocos2d 引擎
- - '##'
  - 切换场景
- - '##'
  - 总结
- - '#'
  - 第 16 章：Kobold2D 简介
- - '##'
  - 使用 Kobold2D 的优势
- - '###'
  - Kobold2D 即开即用
- - '###'
  - Kobold2D 免费开源
- - '###'
  - Kobold2D 易于升级
- - '###'
  - Kobold2D 集成流行库
- - '###'
  - Kobold2D 重视双平台支持
- - '##'
  - Kobold2D 工作区
- - '##'
  - Hello Kobold2D 模板项目
- - '###'
  - Hello World 项目文件
- - '##'
  - Kobold2D 如何启动应用
- - '###'
  - Main 和 AppDelegate
- - '###'
  - 启动配置文件
- - '##'
  - Hello Kobold2D 场景与图层
- - '###'
  - '@implementation HelloWorldLayer'
- - '##'
  - 使用 iSimulate 运行 Hello World
- - '##'
  - 使用 KKInput 的 Mac 版 DoodleDrop
- - '###'
  - 启用加速计
- - '###'
  - 总结
- - '#'
  - 第 17 章：与众不同
- - '##'
  - 学习与工作的额外资源
- - '###'
  - 在哪里寻求帮助
- - '###'
  - Cocos2D 主页
- - '###'
  - Cocos2D Central
- - '###'
  - Stack Exchange 网络
- - '###'
  - 教程和常见问题解答
- - '##'
  - 商业源码与教程
- - '###'
  - Quexlor 动作角色扮演游戏引擎代码与教程
- - '###'
  - 划线游戏入门套件
- - '###'
  - 太空游戏入门套件
- - '###'
  - iUridium 源代码
- - '###'
  - BATAK Duel 源代码
- - '##'
  - Cocos2D 播客
- - '##'
  - 工具、工具、还是工具
- - '##'
  - Cocos2d 参考应用
- - '##'
  - 游戏制作的生意经
- - '###'
  - 与发行商合作及寻找自由职业者
- - '###'
  - 与发行商合作
- - '###'
  - 寻找自由职业者
- - '###'
  - 寻找免费的艺术资源和音频
- - '###'
  - 寻找趁手的工具
- - '##'
  - 市场营销
- - '###'
  - 营销你的游戏和你自己
- - '###'
  - 公共关系与新闻稿
- - '##'
  - 吸引玩家，提升收入
- - '###'
  - 吸引玩家
- - '####'
  - 社交网络
- - '###'
  - 游戏社交网络平台
- - '###'
  - 多人游戏的 Socket 服务器技术
- - '###'
  - 推送通知提供商
- - '###'
  - iCloud 云端存储
- - '###'
  - 赚取更多收入
- - '####'
  - 广告与分析
- - '####'
  - 应用内购买（In-App Purchase）
- - '##'
  - 总结
- - '#'
  - 索引
- - '##'
  - 关于作者
- - '##'
  - 关于技术审校者
- - '##'
  - 致谢
- - '##'
  - 前言
