name: Pro Android Web Game Apps
name_cn: Android Web 游戏高级指南
slug: pro-android-web-game-apps
toc:
- - '##'
  - 引言
- - '##'
  - 本书内容
- - '##'
  - 本书不涉及的内容
- - '##'
  - 本书读者对象
- - '##'
  - 关于美术资源文件
- - '##'
  - 本书结构
- - '#'
  - 第一部分：2D 世界
- - '##'
  - 第 1 章：入门指南
- - '###'
  - 工具
- - '####'
  - 我们需要的工具
- - '#####'
  - Java 开发工具包
- - '#####'
  - 集成开发环境
- - '#####'
  - Web 服务器
- - '#####'
  - Android SDK 与模拟器
- - '###'
  - 技术要点
- - '####'
  - 代码
- - '#####'
  - 面向对象编程
- - '#####'
  - 关于移动浏览器的注意事项
- - '###'
  - 本章小结
- - '##'
  - 第 2 章：浏览器中的图形：Canvas 元素
- - '###'
  - 游戏的架构
- - '###'
  - 在浏览器中绘图
- - '####'
  - 基本 HTML 设置
- - '####'
  - 什么是 Canvas？
- - '#####'
  - 绘图上下文
- - '#####'
  - 坐标系
- - '###'
  - 绘制图形
- - '####'
  - 矩形
- - '####'
  - 路径
- - '#####'
  - 线条
- - '#####'
  - 弧线
- - '#####'
  - 角度与弧度
- - '#####'
  - 曲线
- - '######'
  - 二次曲线
- - '######'
  - 贝塞尔曲线
- - '#####'
  - 子路径
- - '###'
  - 描边与填充
- - '####'
  - 纯色
- - '####'
  - 渐变
- - '#####'
  - 径向渐变
- - '####'
  - 图案
- - '###'
  - 上下文状态与变换
- - '####'
  - 平移
- - '####'
  - 缩放
- - '####'
  - 旋转
- - '####'
  - 变换的叠加
- - '####'
  - 上下文状态
- - '###'
  - 本章小结
- - '##'
  - 第 3 章：创建第一个游戏
- - '###'
  - HTML5 游戏骨架
- - '####'
  - 标准骨架
- - '###'
  - 强制屏幕方向
- - '###'
  - 游戏架构
- - '###'
  - 制作游戏
- - '####'
  - 渲染棋盘
- - '####'
  - 构造函数
- - '###'
  - 处理不同的屏幕尺寸
- - '###'
  - 游戏状态与逻辑
- - '###'
  - 进行移动
- - '###'
  - 连接组件：Game 类
- - '###'
  - 将游戏添加到 HTML 骨架
- - '###'
  - 本章小结
- - '##'
  - 第 4 章：动画与精灵
- - '###'
  - 精灵
- - '###'
  - 矢量图形 vs. 光栅图形
- - '###'
  - 加载图像
- - '####'
  - 从文件加载图像
- - '####'
  - 加载多个图像
- - '####'
  - 使用数据 URL 作为图像
- - '####'
  - 图像加载技巧
- - '#####'
  - 尺寸 vs. 数量
- - '###'
  - 绘制图像
- - '####'
  - 如何绘制图像
- - '###'
  - 精灵图集
- - '###'
  - 光栅字体
- - '###'
  - 动画基础
- - '####'
  - 最简单的动画
- - '###'
  - JavaScript 线程模型
- - '###'
  - 定时器
- - '####'
  - 设置定时器
- - '####'
  - 停止定时器
- - '###'
  - 改进动画
- - '####'
  - 帧率与帧间时间
- - '####'
  - 实现 `Animator`
- - '###'
  - 本章小结
- - '##'
  - 第 5 章：事件处理与用户输入
- - '###'
  - 用户输入
- - '###'
  - 浏览器事件
- - '####'
  - 桌面浏览器与安卓浏览器的输入对比
- - '#####'
  - 移动端控制的优势
- - '#####'
  - 移动端控制的局限性
- - '###'
  - 利用事件捕捉用户输入
- - '###'
  - 事件对象
- - '###'
  - 注册事件：DOM 属性
- - '###'
  - 注册事件：事件监听器
- - '###'
  - 从事件中获取更多信息
- - '###'
  - 处理触控与鼠标界面的差异
- - '###'
  - 自定义事件
- - '####'
  - 自定义事件监听器与发射器
- - '####'
  - EventEmitter：基类
- - '###'
  - 实现 `InputHandlerBase`
- - '###'
  - 常规 DOM 事件监听器
- - '###'
  - 创建 TouchInputHandler
- - '###'
  - 高级输入
- - '####'
  - 拖放
- - '####'
  - 像素级精确选取与图像蒙版
- - '####'
  - 复合操作
- - '####'
  - 模拟摇杆
- - '###'
  - 本章小结
- - '##'
  - 第 6 章：渲染虚拟世界
- - '###'
  - 如何渲染建筑物和角色等世界对象
- - '####'
  - 瓦片地图
- - '#####'
  - 瓦片地图背后的理念
- - '#####'
  - 实现瓦片地图
- - '#####'
  - 设置
- - '###'
  - 渲染瓦片地图
- - '###'
  - 测量 FPS
- - '###'
  - 优化渲染性能
- - '####'
  - 只绘制所需内容
- - '####'
  - 离屏缓冲
- - '####'
  - 缓存视口周围区域
- - '###'
  - 世界对象
- - '####'
  - 坐标系
- - '####'
  - 实现 `WorldObjectRenderer`
- - '####'
  - 渲染顺序
- - '#####'
  - 游戏对象的渲染顺序
- - '#####'
  - 优化
- - '###'
  - 等距视角
- - '###'
  - 本章小结
- - '##'
  - 第 7 章：构建等距引擎
- - '###'
  - 设置
- - '###'
  - 交互模式
- - '###'
  - 渲染层
- - '###'
  - 构建骨架
- - '###'
  - 添加物体
- - '###'
  - 脏矩形算法
- - '###'
  - LayerManager
- - '###'
  - 准备工作
- - '###'
  - 基础代码
- - '####'
  - 工具函数
- - '#####'
  - '`bind()`、`apply()` 和 `call()` 函数'
- - '####'
  - 数学函数与 `Rect` 类
- - '####'
  - '`GameObject` 类'
- - '####'
  - '`Array` 类'
- - '###'
  - 等距地形
- - '####'
  - 坐标系
- - '###'
  - 渲染瓦片
- - '####'
  - 实现 IsometricTileLayer
- - '#####'
  - 视口和地图边界
- - '###'
  - 管理离屏画布
- - '###'
  - 为游戏添加图层
- - '###'
  - 渲染对象
- - '####'
  - 实现对象集群
- - '####'
  - 对象缓存
- - '###'
  - 处理移动
- - '###'
  - 复合对象
- - '###'
  - 对象层：后续步骤
- - '###'
  - 脏矩形
- - '####'
  - 实现
- - '####'
  - 与图层的集成
- - '####'
  - 标记脏矩形
- - '#####'
  - 代码上下文与脏矩形标记
- - '###'
  - UI 与图层管理器
- - '###'
  - 交互
- - '####'
  - 事件传播与处理
- - '###'
  - 本章小结
- - '#'
  - 第二部分：3D 世界
- - '##'
  - 第 8 章：浏览器中的 3D 技术
- - '###'
  - 认识 3D 渲染
- - '####'
  - 3D 渲染的工作原理
- - '#####'
  - 数学部分
- - '#####'
  - 一个 3D 示例
- - '###'
  - Hello World 3D 引擎
- - '####'
  - 模型与场景
- - '#####'
  - 模型
- - '#####'
  - 场景
- - '###'
  - 渲染
- - '###'
  - 矩阵
- - '####'
  - 为什么使用矩阵
- - '###'
  - 实现变换
- - '###'
  - 投影
- - '###'
  - 本章小结
- - '##'
  - 第 9 章：使用 WebGL
- - '###'
  - WebGL 基础
- - '###'
  - 初始化 WebGL
- - '###'
  - 几何体
- - '###'
  - OpenGL ES 2.0 渲染管线
- - '###'
  - 使用缓冲
- - '###'
  - 着色器与 GLSL
- - '####'
  - 关于 GLSL 的简介
- - '####'
  - 数据类型
- - '#####'
  - GLSL 存储限定符
- - '######'
  - 常量
- - '######'
  - uniform
- - '######'
  - attribute
- - '######'
  - varying
- - '####'
  - 操作与函数
- - '###'
  - 渲染 Hello World
- - '###'
  - 探索 WebGL
- - '####'
  - 颜色
- - '####'
  - 更新着色器
- - '####'
  - Varying 的工作原理
- - '####'
  - 向顶点着色器传递颜色数据
- - '###'
  - 纹理
- - '####'
  - 加载纹理
- - '####'
  - 为 WebGL 使用准备纹理
- - '####'
  - 纹理坐标
- - '####'
  - 更新着色器
- - '####'
  - 将纹理数据传递给片段着色器
- - '###'
  - 加载模型
- - '####'
  - 3D 模型概述
- - '####'
  - 处理二进制数据
- - '###'
  - 本章小结
- - '#'
  - 第三部分：连接世界
- - '##'
  - 第 10 章：走向服务器端
- - '###'
  - Node.js 基础
- - '####'
  - 认识 Node.js
- - '###'
  - 编程模型
- - '###'
  - 安装 Node.js
- - '###'
  - 调试 Node 脚本
- - '###'
  - 编写 Node.js 脚本
- - '####'
  - 异常和堆栈跟踪
- - '####'
  - 全局命名空间和 Node 模块
- - '#####'
  - 定义 API 的作用域
- - '####'
  - 编写第一个模块
- - '####'
  - 发现模块
- - '####'
  - 使用 NPM
- - '###'
  - 实战：为游戏构建一个服务器
- - '####'
  - Node 的 Web 开发框架
- - '####'
  - 渲染网页
- - '#####'
  - 创建模板
- - '####'
  - 使用会话（Sessions）
- - '####'
  - 理解中间件（Middleware）
- - '####'
  - 内务整理
- - '#####'
  - 报告错误
- - '#####'
  - 日志记录
- - '####'
  - 服务器配置
- - '###'
  - 本章小结
- - '##'
  - 第 11 章：与服务器通信
- - '###'
  - 浏览器中网络功能的演进
- - '###'
  - 服务器设置
- - '###'
  - 使用 `XMLHttpRequest` API 进行基本 HTTP 请求
- - '####'
  - 使用传统 `XHR` 发起 HTTP 请求
- - '####'
  - 使用 XHR 处理错误
- - '####'
  - XMLHttpRequest Level 2
- - '####'
  - 处理二进制数据
- - '###'
  - 反向 Ajax
- - '####'
  - 问题
- - '####'
  - 解决方案
- - '#####'
  - 最佳解决方案
- - '######'
  - WebSocket
- - '######'
  - 服务器发送事件
- - '#####'
  - 可接受的解决方案
- - '######'
  - XHR 长轮询
- - '######'
  - XHR 流式传输
- - '#####'
  - 过时的解决方案
- - '######'
  - JSONP 轮询
- - '###'
  - 共享或 CORS
- - '###'
  - Flash Socket
- - '###'
  - 永久 IFRAME
- - '###'
  - 在现场测试传输方式
- - '####'
  - 调试网络问题
- - '#####'
  - '`DDMS` （Dalvik 调试监控服务器）'
- - '#####'
  - 模拟不良网络的专用软件
- - '###'
  - 本章小结
- - '##'
  - 第 12 章：打造多人游戏
- - '###'
  - 网络游戏架构分析
- - '####'
  - 游戏架构：从单机走向联机
- - '####'
  - 客户端与服务器的职责
- - '###'
  - 游戏组件
- - '###'
  - 项目结构
- - '###'
  - 使用 Socket.IO 的游戏大厅
- - '####'
  - 客户端-服务器通信
- - '###'
  - 添加游戏逻辑
- - '####'
  - 在客户端和服务器之间共享逻辑
- - '####'
  - 服务器端
- - '####'
  - 客户端
- - '###'
  - 处理玩家操作
- - '###'
  - 更新 BoardModel 类
- - '###'
  - 更新 index.html 文件
- - '###'
  - 本章小结
- - '#'
  - 第四部分：完善世界
- - '##'
  - 第 13 章：游戏中的 AI
- - '###'
  - 我的游戏需要 AI 吗？
- - '###'
  - 寻路算法入门
- - '####'
  - 图
- - '#####'
  - 什么是图？
- - '#####'
  - 在 JavaScript 中实现图
- - '###'
  - 构建寻路 AI
- - '####'
  - A* 算法
- - '#####'
  - 非正式描述
- - '#####'
  - 节点列表
- - '#####'
  - 形式化描述
- - '#####'
  - 实现
- - '####'
  - 实现注意事项
- - '###'
  - 构建寻路图的方法
- - '####'
  - 全手动图
- - '####'
  - 射线投射（视线检测）
- - '####'
  - 导航网格
- - '###'
  - 决策制定
- - '####'
  - 决策树
- - '###'
  - 本章小结
- - '##'
  - 第 14 章：JavaScript 游戏引擎
- - '###'
  - 图形 API、库与游戏引擎
- - '####'
  - 图形 API
- - '####'
  - 图形库
- - '####'
  - 游戏引擎
- - '###'
  - 实体组件系统
- - '###'
  - Crafty 入门
- - '####'
  - Crafty 游戏
- - '#####'
  - 加载精灵
- - '#####'
  - 动画
- - '#####'
  - 与实体的交互和事件系统
- - '####'
  - 最终版本
- - '###'
  - 本章小结
- - '##'
  - 第 15 章：构建原生应用
- - '###'
  - 原生应用
- - '###'
  - 设置 Apache Cordova (PhoneGap)
- - '####'
  - 设置 Cordova
- - '####'
  - 设置 Apache Ant
- - '###'
  - 构建原生应用
- - '####'
  - 创建空白的 Android 项目
- - '####'
  - 测试空的 Android 项目
- - '####'
  - 基本的 Cordova 项目
- - '#####'
  - 为 Cordova 开发准备项目
- - '#####'
  - 更新 Java 文件和 Android 清单
- - '#####'
  - 测试项目
- - '###'
  - 网络
- - '###'
  - 最终润色：名称、图标和全屏模式
- - '###'
  - 使用原生 API
- - '###'
  - 为发布到市场做准备
- - '####'
  - 签名应用程序
- - '#####'
  - 创建数字密钥
- - '#####'
  - 签署应用程序
- - '###'
  - 发布到 Google Play
- - '###'
  - 更新你的应用程序
- - '###'
  - 本章小结
- - '##'
  - 第 16 章：添加音效
- - '###'
  - 网页中的音频
- - '####'
  - 音频标签
- - '####'
  - Web Audio API
- - '####'
  - Android 浏览器中的声音
- - '###'
  - 使用 SoundManager2
- - '####'
  - 初始设置
- - '####'
  - 循环
- - '####'
  - 为游戏添加声音
- - '###'
  - 在 Cordova 应用中播放声音
- - '###'
  - 用户体验
- - '###'
  - 本章小结
- - '###'
  - 进一步探索
- - '#'
  - 附录 A：调试客户端 JavaScript
- - '##'
  - 调试示例
- - '##'
  - 在桌面浏览器中调试
- - '##'
  - 在移动设备上调试
- - '###'
  - 几乎无需更改代码的日志记录
- - '###'
  - weinre
- - '##'
  - 本章小结
- - '#'
  - 索引
- - '##'
  - A
- - '##'
  - B
- - '##'
  - C
- - '##'
  - D
- - '##'
  - E
- - '##'
  - F
- - '##'
  - G
- - '##'
  - H
- - '##'
  - I
- - '##'
  - J, K
- - '##'
  - L
- - '##'
  - M
- - '##'
  - N
- - '##'
  - O
- - '##'
  - P
- - '##'
  - Q
- - '##'
  - R
- - '##'
  - S
- - '##'
  - T
- - '##'
  - U
- - '##'
  - V
- - '##'
  - W
- - '##'
  - X, Y, Z
