name: IOS 5 Recipes
name_cn: iOS 5 秘籍
slug: ios-5-recipes
toc:
- - '#'
  - iOS 5 秘籍：问题解决方案
- - '##'
  - 目录速览
- - '##'
  - 目录
- - '#'
  - iOS 开发食谱 - 目录
- - '#'
  - 目录
- - '##'
  - 关于作者
- - '##'
  - 关于技术审校
- - '##'
  - 引言
- - '###'
  - 本书阅读指南
- - '###'
  - 本书组织结构
- - '###'
  - 源代码与勘误
- - '###'
  - 联系方式
- - '##'
  - 第 1 章 Xcode 4 技巧与提示
- - '###'
  - Xcode 4 简介
- - '###'
  - 在同一个 Xcode 项目中同时构建精简版和完整版
- - '###'
  - 僵尸猎人
- - '###'
  - 使用 Xcode 4 进行版本控制
- - '###'
  - 创建本地仓库
- - '###'
  - 分支与合并
- - '###'
  - 远程仓库
- - '###'
  - GitHub
- - '###'
  - 源代码管理最佳实践
- - '###'
  - Steve 和 ARC
- - '####'
  - ARC 规则
- - '####'
  - 使用 ARC
- - '####'
  - 将旧项目转换到 ARC
- - '###'
  - 快速技巧
- - '####'
  - 注释
- - '####'
  - 自动完成
- - '####'
  - 快速缩进/取消缩进
- - '####'
  - 在头文件和实现文件之间快速切换
- - '####'
  - 类文档
- - '####'
  - 在助理编辑器中打开文件
- - '###'
  - 行为
- - '###'
  - 总结
- - '##'
  - 第 2 章：Interface Builder 简介
- - '###'
  - Interface Builder 入门
- - '###'
  - 我们的力量合而为一……
- - '###'
  - 触控手势
- - '###'
  - 调整色调
- - '###'
  - 使用故事板进行快速应用开发
- - '####'
  - 那么什么是故事板？
- - '#####'
  - 场景
- - '#####'
  - 转场
- - '###'
  - 讲述故事
- - '###'
  - 在场景间传递数据
- - '###'
  - UITableViewCell 原型
- - '###'
  - 向现有项目添加故事板
- - '###'
  - 总结
- - '##'
  - 第 3 章 应用程序设计元素
- - '###'
  - Cocoa Touch 控件
- - '###'
  - '`UILabel`'
- - '###'
  - '`UIButton`'
- - '###'
  - '`UISegmentedControl`'
- - '###'
  - '`UITextField`'
- - '###'
  - '`UISlider`'
- - '###'
  - '`UISwitch`'
- - '###'
  - '`UIActivityIndicatorView`'
- - '###'
  - '`UIProgressView`'
- - '###'
  - '`UIPageControl`'
- - '###'
  - '`UIStepper`'
- - '###'
  - 数据视图
- - '####'
  - '`UIImageView`'
- - '####'
  - '`UITextView`'
- - '####'
  - '`UIScrollView`'
- - '####'
  - '`UIWebView`'
- - '####'
  - '`MKMapView`'
- - '####'
  - '`UITableView`'
- - '####'
  - '`UIPickerView`'
- - '####'
  - '`UIDatePickerView`'
- - '###'
  - 手势识别器
- - '####'
  - '`UITapGestureRecognizer`'
- - '####'
  - '`UISwipeGestureRecognizer`'
- - '####'
  - '`UIPanGestureRecognizer`'
- - '####'
  - '`UILongPressGestureRecognizer`'
- - '####'
  - '`UIPinchGestureRecognizer`'
- - '####'
  - '`UIRotationGestureRecognizer`'
- - '###'
  - 视图控制器
- - '####'
  - '`UINavigationController`'
- - '####'
  - '`UITabBarController`'
- - '####'
  - '`UISplitViewController`'
- - '####'
  - '`UIPopoverController`'
- - '####'
  - '`UIPageViewController`'
- - '####'
  - 模态控制器
- - '###'
  - 临时用户界面元素
- - '####'
  - '`UIAlertView`'
- - '####'
  - '`UIActionSheet`'
- - '###'
  - 总结
- - '##'
  - 第 4 章 位置相关实践方案
- - '###'
  - 支持的设备
- - '###'
  - 要求定位服务
- - '###'
  - 如何知道我在哪里？
- - '###'
  - 方案 4-1：获取设备位置信息
- - '###'
  - 配方 4-2：重大位置变化
- - '###'
  - 配方 4-3：确定磁方位角
- - '###'
  - 配方 4-4：指定真方位
- - '###'
  - 操作指南 4-5：区域监测
- - '####'
  - 关于区域的一些要点
- - '####'
  - 欢迎来到巴尔的摩！
- - '###'
  - 食谱 4-6：反向地理编码与正向地理编码
- - '###'
  - 根据地名获取坐标
- - '###'
  - 总结
- - '##'
  - 第 5 章 地图套件使用指南
- - '###'
  - 配方 5-1：在地图上显示设备位置
- - '###'
  - 范例 5-2：使用大头针标记位置
- - '####'
  - 食谱 5-3：创建自定义标注
- - '####'
  - 食谱 5-4：向地图添加覆盖层
- - '####'
  - 方案 5-5：按位置对标注进行分组
- - '###'
  - 总结
- - '##'
  - 第 6 章 相机秘籍
- - '###'
  - 食谱 6-1：拍照
- - '###'
  - 菜谱 6-2：录制视频
- - '###'
  - 技巧 6-3：编辑视频
- - '###'
  - 配方 6-4：自定义相机覆盖层
- - '###'
  - 食谱 6-5：AV 框架与采集会话
- - '####'
  - 关于 `AVCaptureVideoPreviewLayer` 的说明
- - '###'
  - 食谱 6-6：通过编程录制视频
- - '###'
  - 食谱 6-7：捕获视频帧
- - '###'
  - 总结
- - '##'
  - 第 7 章 多媒体食谱
- - '###'
  - 食谱 7-1：播放音频
- - '###'
  - 食谱 7-2：录制音频
- - '###'
  - 菜谱 7-3：访问 iPod 资料库
- - '###'
  - 查询媒体
- - '####'
  - '`MPMediaPropertyPredicates` 的几点说明：'
- - '###'
  - 技巧 7-4：后台播放与正在播放信息
- - '###'
  - 总结
- - '##'
  - 第 8 章 用户数据秘籍
- - '###'
  - 配方 8-1：使用 `NSCalendar` 和 `NSDate`
- - '###'
  - 食谱 8-2：获取事件
- - '###'
  - 技巧 8-3：在 `UITableView` 中显示事件
- - '###'
  - 配方 8-4：查看、编辑和删除事件
- - '###'
  - 食谱 8-5：创建简单事件
- - '###'
  - 秘籍 8-6：重复事件
- - '###'
  - 食谱 8-7：基本通讯录访问
- - '###'
  - 配方 8-8：设置联系人信息
- - '###'
  - 配方 8-9：查看联系人
- - '###'
  - 总结
- - '##'
  - 第 9 章 UITableView 配方
- - '###'
  - 配方 9-1：创建无分组表格
- - '####'
  - 关于圆角的小提示
- - '####'
  - 增强的用户交互
- - '####'
  - 关于单元格视图自定义的说明
- - '###'
  - 技巧 9-2：编辑 `UITableView`
- - '####'
  - '`UITableView` 行动画'
- - '####'
  - 但等等，还有更多！
- - '###'
  - 食谱 9-3：对 UITableView 进行重新排序
- - '###'
  - 技巧 9-4：创建分组 UITableView
- - '###'
  - 总结
- - '##'
  - 第 10 章 数据存储方案
- - '###'
  - 配方 10-1：使用 `NSUserDefaults`
- - '###'
  - 方案 10-2：管理文件
- - '###'
  - Core Data
- - '###'
  - 方案 10-3：利用 iCloud 实现数据持久化
- - '###'
  - 配方 10-4：在 iCloud 中存储键值数据
- - '###'
  - 总结
- - '##'
  - 第 11 章 Core Data 配方
- - '###'
  - 什么是 Core Data？
- - '###'
  - 示例 11-1：创建数据模型
- - '###'
  - 食谱 11-2：使用 NSManagedObjects
- - '###'
  - 技巧 11-3：创建 `NSManagedObject` 的子类
- - '####'
  - '`@interface MainTableViewController : UIViewController <UITableViewDelegate,
    UITableViewDataSource>`'
- - '###'
  - 技巧 11-4：过滤你的提取请求
- - '###'
  - 食谱 11-5：版本控制
- - '###'
  - 令人恼火的错误
- - '###'
  - 总结
- - '##'
  - 第 12 章 Core Motion 实例
- - '###'
  - 配方 12-1：注册摇晃事件
- - '###'
  - 配方 12-2：访问原始 Core Motion 数据
- - '###'
  - Core Motion 详解
- - '####'
  - 姿态属性
- - '###'
  - 食谱 12-3：使用加速计移动 `UILabel`
- - '###'
  - 总结
- - '##'
  - 第 13 章 数据传输食谱
- - '###'
  - 配方 13-1：撰写短信
- - '###'
  - 秘籍 13-2：编写电子邮件
- - '####'
  - 将数据附加到邮件
- - '###'
  - 方案 13-3：打印图像
- - '###'
  - 方案 13-4：打印纯文本
- - '###'
  - 方案 13-5：打印视图
- - '###'
  - 技巧 13-6：使用页面渲染器进行格式化打印
- - '###'
  - 总结
- - '##'
  - 第 14 章 Twitter 范例
- - '###'
  - 配方 14-1：编写简单的推文
- - '###'
  - 配方 14-2：创建简单的 TWRequest
- - '####'
  - 通过 `TWRequest` 发送推文
- - '###'
  - 方案 14-3：检索推文
- - '####'
  - 代码示例：自定义初始化方法
- - '###'
  - 方案 14-4：过滤推文
- - '###'
  - 总结
- - '##'
  - 第 15 章 图像秘诀
- - '###'
  - 菜谱 15-1：绘制简单形状
- - '###'
  - 编程截图
- - '###'
  - 食谱 15-2：使用 UIImageView
- - '###'
  - 食谱 15-3：缩放图像
- - '####'
  - 回顾总结
- - '###'
  - 配方 15-4：使用滤镜处理图片
- - '###'
  - 秘方 15-5：检测特征
- - '###'
  - 总结
- - '##'
  - 第 16 章 Game Kit 技巧
- - '###'
  - 技巧 16-1：从 Game Center 开始
- - '####'
  - iTunes Connect 设置
- - '####'
  - 项目设置
- - '####'
  - 检查 Game Center 支持
- - '####'
  - 玩家认证
- - '###'
  - 技巧 16-2：排行榜
- - '####'
  - 设置 iTunes Connect
- - '####'
  - 设置你的代码
- - '####'
  - 显示高分
- - '###'
  - 配方 16-3：成就系统
- - '####'
  - 配置 iTunes Connect
- - '####'
  - 配置代码
- - '####'
  - 显示成就
- - '###'
  - 配方 16-4：多人游戏
- - '####'
  - 设置代码
- - '###'
  - 总结
- - '##'
  - 索引
- - '###'
  - A
- - '###'
  - B
- - '###'
  - C
- - '###'
  - D
- - '####'
  - 数据存储
- - '####'
  - 文件管理
- - '####'
  - 数据传输方案，453
- - '###'
  - E
- - '###'
  - F
- - '###'
  - G
- - '####'
  - iTunes Connect 设置
- - '####'
  - Game Center，555
- - '#####'
  - iTunes Connect 设置
- - '#####'
  - 项目设置
- - '####'
  - 手势识别器
- - '###'
  - H
- - '###'
  - I, J
- - '####'
  - iCloud
- - '####'
  - 图像特征检测
- - '####'
  - 图像打印，467-473
- - '####'
  - 图像食谱
- - '#####'
  - 滤镜
- - '#####'
  - 简单形状
- - '####'
  - '`imageForSegmentAtIndex:`方法，91'
- - '####'
  - '`imageFromSampleBuffer`，226'
- - '####'
  - '`-imagePickerController:didFinishPickingMediaWithInfo:`委托方法，219'
- - '####'
  - '`-initWithContentViewController:`初始化器，119'
- - '####'
  - '`initWithCoordinate`方法，175'
- - '####'
  - '`-initWithItems:`方法，91'
- - '####'
  - '`inputAccessoryView`，102'
- - '####'
  - '`inputView`属性，102'
- - '####'
  - '`-insertSegmentWithImage:atIndex:animated:`方法，91'
- - '####'
  - '`insertSegmentWithTitle:atIndex:animated:`方法，91'
- - '####'
  - Interface Builder
- - '####'
  - iPod 库
- - '###'
  - K
- - '###'
  - L
- - '####'
  - 区域监控
- - '####'
  - 反向地理编码与正向地理编码
- - '####'
  - 重大位置变更
- - '####'
  - 标准定位服务
- - '####'
  - 真方位
- - '###'
  - M
- - '####'
  - 自定义注解
- - '###'
  - 多媒体
- - '####'
  - '`AVAudioRecorder`'
- - '####'
  - '`MPMediaPropertyPredicates`'
- - '####'
  - 查询媒体
- - '###'
  - N, O
- - '###'
  - P, Q
- - '###'
  - R
- - '###'
  - S
- - '###'
  - T
- - '####'
  - '`UIActionSheetDelegate` 协议，124'
- - '####'
  - '`UINavigationController`'
- - '####'
  - '`UIPageControl`，97-98'
- - '####'
  - '`UIPageViewController`，120'
- - '####'
  - '`UIPickerViewDataSource` 协议，105'
- - '####'
  - '`UIPickerViewDelegate` 协议，105'
- - '####'
  - '`UIPopoverController`，118-120'
- - '####'
  - '`UIProgressView`，97'
- - '####'
  - '`UIRequiredDeviceCapabilities`，126'
- - '####'
  - '`UIScrollViewDelegate` 协议，104'
- - '####'
  - '`UISegmentedControl` 类，90-91'
- - '####'
  - '`UISlider`，95'
- - '####'
  - '`UISplitViewController`'
- - '####'
  - '`UIStepper`，98-99'
- - '####'
  - '`UISwipeGestureRecognizerDirectionDown`，110'
- - '####'
  - '`UISwipeGestureRecognizerDirectionLeft`，110'
- - '####'
  - '`UISwipeGestureRecognizerDirectionRight`，110'
- - '####'
  - '`UISwipeGestureRecognizerDirectionUp`，110'
- - '####'
  - '`UISwitch`，96'
- - '####'
  - '`UITabBarController`'
- - '####'
  - '`UITableView`'
- - '###'
  - V, W
- - '###'
  - X, Y
- - '###'
  - Z
