name: Beginning iOS Media App Development
name_cn: iOS 媒体应用开发入门指南
slug: beginning-ios-media-app-development
toc:
- - '#'
  - 开始 iOS 媒体应用开发
- - '#'
  - 内容概览
- - '#'
  - 目录
- - '#'
  - 开始使用
- - '#'
  - 创建系统音效
- - '#'
  - 播放系统音效
- - '#'
  - 使设备振动
- - '#'
  - 总结
- - '#'
  - 后台音频
- - '#'
  - 设置后台模式
- - '#'
  - 选择兼容的会话类型
- - '#'
  - 使用“正在播放”中心
- - '#'
  - 显示元数据
- - '#'
  - 启用播放控制（远程控制）
- - '#'
  - 构建更强大的音频会话
- - '#'
  - 处理音频中断
- - '#'
  - 处理硬件（线路）变更
- - '#'
  - 使用 AirPlay
- - '#'
  - 总结
- - '#'
  - 播放视频文件
- - '#'
  - 开始使用
- - '#'
  - 初始化视频播放器
- - '#'
  - 为你的类添加通知处理
- - '#'
  - 配置视频播放器
- - '#'
  - 开始播放
- - '#'
  - 录制视频文件
- - '#'
  - 开始使用
- - '#'
  - 为视频配置图像选择器
- - '#'
  - 保存视频录制
- - '#'
  - 总结
- - '#'
  - 开始使用
- - '#'
  - 构建用户界面
- - '#'
  - 使用 AVPlayer 类进行媒体播放
- - '#'
  - 创建类似 MediaPlayer 的通知
- - '#'
  - 构建播放控件
- - '#'
  - 切换播放状态
- - '#'
  - 快进/快退
- - '#'
  - 使用播放进度条
- - '#'
  - 关闭播放界面
- - '#'
  - 添加用户界面更新
- - '#'
  - 更新播放进度
- - '#'
  - 自动隐藏播放控件
- - '#'
  - 总结
- - '#'
  - 开始使用
- - '#'
  - 设置硬件接口
- - '#'
  - 构建用户界面
- - '#'
  - 设置视频图层
- - '#'
  - 添加拍摄设置控件
- - '#'
  - 开始/停止录制
- - '#'
  - 完成录制
- - '#'
  - 保存视频输出
- - '#'
  - 显示预览界面
- - '#'
  - 为视频修改自定义协议
- - '#'
  - 总结
- - '#'
  - 使用尺寸类别构建自适应用户界面
- - '#'
  - 使用快速查看进行运行时预览
- - '#'
  - 为你的类添加界面构建器预览
- - '#'
  - 使用界面构建器调试视图
- - '#'
  - 第 12 章：使用 AVKit 框架进行媒体播放
- - '#'
  - 第 13 章：使用 HealthKit 和 Core Motion 追踪健身数据
- - '#'
  - 第 14 章：Swift 入门
- - '#'
  - 关于作者
- - '#'
  - 关于技术审校者
- - '#'
  - 致谢
- - '#'
  - 引言
- - '#'
  - 第 1 章：欢迎进入 iOS 媒体应用开发
- - '##'
  - 本书的目的是什么？
- - '##'
  - 媒体应用开发有何不同？
- - '##'
  - 阅读本书需要哪些知识储备？
- - '##'
  - 开始学习需要准备什么？
- - '###'
  - 使用本书需要一个有效的 iOS 开发者计划账户
- - '###'
  - 构建你的第一个 iOS 媒体应用
- - '####'
  - 关于此应用
- - '####'
  - 设置应用
- - '####'
  - 将图像添加到你的应用
- - '####'
  - 处理用户界面事件
- - '##'
  - 在设备上运行应用程序
- - '##'
  - 调试常见问题
- - '#'
  - 第一部分：图像
- - '##'
  - 第二章：向应用添加图像
- - '###'
  - 使用 UIImage 类表示图像数据
- - '####'
  - 加载捆绑文件
- - '####'
  - 使用素材目录管理图像
- - '###'
  - 使用 UIImagePickerController 类选择图像
- - '###'
  - 使用协议与委托
- - '###'
  - 使用图片选取器访问已保存的图片
- - '###'
  - 配置和呈现图片选择器
- - '###'
  - 处理来自图片选择器的数据
- - '###'
  - 使用图像选择器拍照
- - '####'
  - 练习：让用户选择图像选择器类型
- - '###'
  - 理解图片选择器的用户界面限制
- - '###'
  - 在 iPad 上呈现相册
- - '###'
  - 总结
- - '#'
  - 第 3 章：用图片做有用的事
- - '##'
  - 操作图片
- - '##'
  - 调整图片大小
- - '##'
  - 裁剪图像
- - '##'
  - 保存图像
- - '###'
  - 将图像保存到文件
- - '###'
  - 将图片保存到相册
- - '##'
  - 从网络加载图片
- - '##'
  - 添加活动指示器
- - '##'
  - 为图像添加效果
- - '###'
  - 添加渐变
- - '##'
  - 让图像随设备移动
- - '##'
  - 为图像添加模糊效果
- - '##'
  - 总结
- - '#'
  - 第 4 章：高级照片界面
- - '##'
  - 构建自定义相机界面
- - '###'
  - 初始化硬件接口
- - '####'
  - 图 4-3. Xcode 的框架选择器
- - '####'
  - 代码清单 4-1. 添加摄像头输入
- - '###'
  - 访问实时摄像头画面
- - '###'
  - 捕捉静态图像
- - '###'
  - 访问硬件控制
- - '####'
  - 切换摄像头
- - '####'
  - 更改闪光灯模式
- - '####'
  - 更改自动对焦模式
- - '####'
  - 更改曝光模式
- - '###'
  - 处理不同屏幕尺寸
- - '##'
  - 构建自定义图片选择器
- - '###'
  - 实例化资产库作为数据源
- - '###'
  - Block 快速指南
- - '###'
  - 使用 UICollectionView 类来枚举资源
- - '###'
  - 排版后内容
- - '###'
  - 启用多选
- - '###'
  - 创建用于返回图像数据的接口
- - '##'
  - 入门
- - '##'
  - 配置音频会话
- - '##'
  - 使用单例
- - '##'
  - 选择音频文件
- - '##'
  - 设置音频播放器
- - '##'
  - 构建播放界面
- - '###'
  - 开始或暂停播放
- - '###'
  - 快进或快退
- - '####'
  - 列表 5-18：后退按钮的处理方法
- - '###'
  - 显示播放进度
- - '####'
  - 列表 5-19：用户开始播放文件时初始化定时器
- - '####'
  - 列表 5-20：更新进度条和标签的方法
- - '####'
  - 列表 5-21：在音频播放器委托方法中使定时器失效
- - '##'
  - 录制音频文件
- - '###'
  - 开始使用
- - '##'
  - 配置音频会话
- - '##'
  - 设置音频录音器
- - '##'
  - 构建录音界面
- - '###'
  - 开始或停止录音
- - '##'
  - 播放录制内容
- - '##'
  - 保存录制内容
- - '##'
  - 删除录制内容
- - '##'
  - 本章小结
- - '#'
  - 第 6 章：使用外部音频源
- - '##'
  - 从 iTunes 导入音乐
- - '###'
  - 开始
- - '###'
  - 初始化音乐播放器
- - '##'
  - 指定媒体队列（播放列表）
- - '##'
  - 创建项目选择界面
- - '##'
  - 构建播放界面
- - '###'
  - 在简易音频播放器应用中
- - '###'
  - 显示歌曲信息（元数据）
- - '##'
  - 流媒体音乐
- - '###'
  - 入门指南
- - '###'
  - 连接到流
- - '###'
  - 播放流媒体音频
- - '##'
  - 播放事件音效（包括振动）
- - '###'
  - 开始上手
- - '###'
  - 创建系统声音
- - '###'
  - 播放系统声音
- - '###'
  - 使设备振动
- - '##'
  - 总结
- - '#'
  - 第 7 章：高级音频主题
- - '##'
  - 后台音频
- - '###'
  - 设置后台模式
- - '##'
  - 选择兼容的会话类型
- - '##'
  - 使用“正在播放”中心
- - '##'
  - 显示元数据
- - '####'
  - 表 7-3. `nowPlayingInfo` 字典的有效键
- - '####'
  - 列表 7-2. 从 `MPMediaItem` 设置元数据信息
- - '####'
  - 列表 7-3. 为 MyPlayer 应用程序设置元数据信息
- - '####'
  - 列表 7-4. 在文件选择器委托中设置“正在播放”信息
- - '####'
  - 列表 7-5. 已添加“正在播放”更新的定时器委托
- - '##'
  - 启用播放控制（远程控制）
- - '##'
  - 构建更稳健的音频会话
- - '###'
  - 处理音频中断
- - '##'
  - 处理硬件（线路）变更
- - '##'
  - 使用 AirPlay
- - '##'
  - 总结
- - '#'
  - 第 3 部分：视频
- - '#'
  - 第 8 章：播放和录制视频
- - '##'
  - 播放视频文件
- - '###'
  - 开始
- - '##'
  - 初始化视频播放器
- - '###'
  - 指定内容 URL
- - '##'
  - 使用文件选择器作为数据源
- - '###'
  - 为媒体播放器指定父视图
- - '###'
  - 向类添加通知处理
- - '####'
  - 通知入门
- - '####'
  - iOS 开发中的协议与通知
- - '####'
  - 添加通知观察者
- - '####'
  - 发布与移除通知
- - '####'
  - 实际实现
- - '##'
  - 录制视频文件
- - '##'
  - 开始入门
- - '##'
  - 为视频配置图像选择器
- - '##'
  - 保存视频录制文件
- - '##'
  - 总结
- - '#'
  - 第 9 章：构建自定义视频播放界面
- - '##'
  - 开始
- - '##'
  - 构建用户界面
- - '##'
  - 使用`AVPlayer`类进行媒体播放
- - '##'
  - 创建类似 MediaPlayer 的通知
- - '###'
  - 构建播放控制
- - '####'
  - 切换播放
- - '####'
  - 向前/向后跳过
- - '##'
  - 使用播放进度条
- - '##'
  - 关闭播放界面
- - '##'
  - 添加用户界面更新
- - '###'
  - 更新播放进度
- - '###'
  - 自动隐藏播放控件
- - '##'
  - 构建自定义视频录制界面
- - '#'
  - 第 10 章：构建自定义视频录制界面
- - '##'
  - 开始之前
- - '##'
  - 设置硬件接口
- - '###'
  - 指定视频分辨率
- - '##'
  - 构建用户界面
- - '###'
  - 设置视频图层
- - '##'
  - 添加拍摄设置控件
- - '###'
  - 手电筒模式
- - '###'
  - 弱光增强
- - '##'
  - 开始/停止录制
- - '##'
  - 完成录制
- - '##'
  - 保存视频输出
- - '##'
  - 显示预览界面
- - '##'
  - 为视频修改你的协议
- - '##'
  - 总结
- - '#'
  - 第四部分
- - '#'
  - 第 11 章：使用 Size Classes 构建自适应用户界面
- - '##'
  - 使用 Quick Look 进行运行时预览
- - '##'
  - 向类中添加 Interface Builder 预览
- - '##'
  - 使用 Interface Builder 调试视图
- - '##'
  - 总结
- - '#'
  - 第 12 章：使用 AVKit 框架进行媒体播放
- - '##'
  - 入门指南
- - '##'
  - 使用 AVPlayer 类播放媒体文件
- - '###'
  - 呈现 AVPlayerViewController
- - '##'
  - 使用 AVQueuePlayer 类播放播放列表
- - '##'
  - 处理媒体播放事件
- - '###'
  - 使用键值观察者
- - '####'
  - 接收者（`receiver`，即调用类）是此消息需要被观察的对象；在本例中，就是数组本身。观察者（`observer`）是充当委托并基于指定值变化接收消息的类。`key
    path` 是您想要观察的对象的属性；该名称作为区分大小写的字符串传递。`options` 参数允许您指定信息应如何发送到处理方法。例如，您可以减少消息的频率（默认值
    `nil` 对于大多数初级应用来说已经足够）。`context` 参数允许您在处理方法中指定一个“原始值”进行比较。同样，默认值 `nil` 对于大多数初级应用来说已经足够。
- - '####'
  - 加载完成事件
- - '####'
  - 播放完成事件
- - '####'
  - 错误处理
- - '##'
  - 添加覆盖视图（水印）
- - '##'
  - 总结
- - '#'
  - 第 13 章：使用 HealthKit 和 Core Motion 追踪健身数据
- - '##'
  - 开始操作
- - '##'
  - 使用 Core Motion 追踪活动
- - '##'
  - 请求运动活动权限
- - '###'
  - 13-2. 检查运动活动权限
- - '###'
  - 13-3. 检查并初始化计步器
- - '##'
  - 开始锻炼
- - '###'
  - 13-4. 开始锻炼时更新用户界面
- - '###'
  - 13-5. 为计步器更新设置 `MainViewController` 类
- - '##'
  - 集成后台更新
- - '###'
  - 停止锻炼
- - '##'
  - 使用 HealthKit 同步数据
- - '###'
  - 请求使用 HealthKit 的权限
- - '##'
  - 从`HealthKit`检索数据
- - '##'
  - 获取实时更新
- - '##'
  - 记录活动
- - '##'
  - 总结
- - '#'
  - 第 14 章：Swift 入门
- - '##'
  - 入门
- - '###'
  - 创建新项目
- - '##'
  - 将 Objective-C 类导入到你的项目中
- - '##'
  - 构建故事板
- - '##'
  - 基本 Swift 语法
- - '###'
  - 调用方法（Hello World）
- - '###'
  - 定义变量
- - '####'
  - Swift 与 Objective-C 语法对比
- - '##'
  - 实例化对象
- - '##'
  - 访问属性和方法（包括 Objective-C 类）
- - '##'
  - 类型转换
- - '##'
  - 使用字符串格式化器
- - '##'
  - 使用数组
- - '##'
  - 使用条件逻辑
- - '##'
  - 使用循环
- - '##'
  - 定义方法
- - '###'
  - 排版后的内容
- - '###'
  - 参数类型声明
- - '###'
  - 调用枚举类型
- - '###'
  - 使用特殊标点（问号和感叹号运算符）
- - '##'
  - 构建类
- - '##'
  - 将项目连接到 Interface Builder
- - '##'
  - 添加委托支持
- - '##'
  - 添加键值观察支持
- - '##'
  - 添加通知支持
- - '##'
  - 总结
- - '#'
  - 索引
