name: iOS architecture patterns
name_cn: iOS 架构模式
slug: ios-architecture-patterns
toc:
- - '##'
  - 引言
- - '##'
  - 本书目标读者
- - '##'
  - 如何使用本书？
- - '##'
  - 致谢
- - '##'
  - 关于作者
- - '##'
  - 关于技术审校者
- - '#'
  - 1. 引言
- - '##'
  - 什么是软件架构？
- - '##'
  - 架构模式
- - '##'
  - 为什么我们需要为应用程序采用架构模式？
- - '##'
  - 从高层级到低层级进行设计
- - '###'
  - 设计模式
- - '####'
  - 创建型模式
- - '#####'
  - 工厂方法
- - '#####'
  - 抽象工厂
- - '#####'
  - 生成器
- - '#####'
  - 单例
- - '#####'
  - 原型
- - '##'
  - 结构型模式
- - '###'
  - 适配器模式
- - '###'
  - 桥接模式
- - '###'
  - 组合模式
- - '###'
  - 装饰器模式
- - '###'
  - 外观模式
- - '###'
  - 享元模式
- - '###'
  - 代理模式
- - '##'
  - 行为型模式
- - '###'
  - 责任链模式
- - '###'
  - 命令模式
- - '###'
  - 解释器模式
- - '###'
  - 迭代器模式
- - '###'
  - 中介者模式
- - '###'
  - 备忘录模式
- - '###'
  - 观察者模式
- - '###'
  - 状态模式
- - '###'
  - 策略模式
- - '###'
  - 模板方法模式
- - '###'
  - 访问者模式
- - '##'
  - SOLID 原则
- - '###'
  - 单一职责原则（`SRP`）
- - '###'
  - 开闭原则（`OCP`）
- - '###'
  - 里氏替换原则（`LSP`）
- - '###'
  - 接口隔离原则（`ISP`）
- - '###'
  - 依赖反转原则（`DIP`）
- - '##'
  - 如何选择正确的架构模式
- - '###'
  - 最常用的架构模式
- - '##'
  - 追寻“简洁架构”
- - '###'
  - 整洁架构分层
- - '####'
  - 领域层
- - '####'
  - 表示层
- - '####'
  - 数据层
- - '###'
  - 依赖规则
- - '###'
  - 应用整洁架构的优势
- - '##'
  - MyToDos：一个用于测试架构的简单应用
- - '###'
  - 应用界面
- - '####'
  - 启动界面
- - '####'
  - 主界面
- - '####'
  - 添加列表界面
- - '###'
  - 任务列表界面
- - '###'
  - 添加任务界面
- - '###'
  - 应用程序开发
- - '####'
  - 使用的技术
- - '####'
  - 如何移除对 Storyboard 的依赖
- - '####'
  - Core Data 配置
- - '#'
  - 如何创建数据库和实体
- - '##'
  - 创建 CoreDataManager
- - '##'
  - 总结
- - '#'
  - 2. MVC：模型-视图-控制器
- - '##'
  - 什么是 MVC？
- - '###'
  - 一点历史
- - '###'
  - Apple 的模型-视图-控制器
- - '##'
  - MVC 中的组件
- - '###'
  - 模型
- - '###'
  - 视图
- - '###'
  - 控制器
- - '##'
  - MVC 的优缺点
- - '###'
  - MVC 模式的优点
- - '###'
  - MVC 模式的缺点
- - '##'
  - MVC 应用实践
- - '###'
  - MVC 分层
- - '###'
  - 模型
- - '###'
  - 核心数据
- - '###'
  - 模型
- - '###'
  - 服务层
- - '###'
  - 扩展
- - '###'
  - 常量
- - '###'
  - 视图层
- - '###'
  - 控制器层
- - '###'
  - MyToDos 应用程序屏幕
- - '###'
  - 信息流
- - '####'
  - 委托模式
- - '####'
  - 如何实现委托模式
- - '###'
  - AppDelegate 和 SceneDelegate
- - '###'
  - 主屏幕
- - '###'
  - '`HomeViewController`'
- - '###'
  - '`HomeView`'
- - '###'
  - 添加列表屏幕
- - '####'
  - '`AddListViewController`'
- - '####'
  - '`AddListView`'
- - '###'
  - 任务列表界面
- - '####'
  - '`TaskListViewController`'
- - '###'
  - '`TaskListView`'
- - '###'
  - 添加任务屏幕
- - '####'
  - '`AddTaskViewController`'
- - '####'
  - '`AddTaskView`'
- - '###'
  - 测试
- - '####'
  - 测试应该是什么样的？
- - '#'
  - 创建第一个测试
- - '##'
  - 辅助类
- - '##'
  - MVC-MyToDos 测试
- - '#'
  - TasksListServiceTest
- - '#'
  - Mock 服务
- - '#'
  - 控制器测试
- - '###'
  - 视图测试
- - '###'
  - 总结
- - '#'
  - 3. MVP：模型-视图-展示器
- - '##'
  - 什么是 MVP？
- - '###'
  - 一点历史
- - '###'
  - 它是如何工作的
- - '###'
  - MVP 中的组件
- - '####'
  - 模型
- - '####'
  - 视图
- - '####'
  - 展示器
- - '###'
  - MVP 的优点和缺点
- - '####'
  - 优势
- - '####'
  - 劣势
- - '##'
  - MVP 应用
- - '###'
  - MVP 层
- - '####'
  - Model
- - '#####'
  - Core Data
- - '#####'
  - Models
- - '#####'
  - Services
- - '#####'
  - Extensions
- - '#####'
  - Constants
- - '####'
  - View
- - '####'
  - Presenter
- - '###'
  - MyToDos 应用程序屏幕
- - '####'
  - AppDelegate 和 SceneDelegate
- - '####'
  - 首页屏幕
- - '###'
  - HomeController
- - '###'
  - HomeView
- - '###'
  - HomePresenter
- - '###'
  - 添加列表屏幕
- - '####'
  - AddListViewController
- - '####'
  - AddListView
- - '####'
  - AddListPresenter
- - '###'
  - 任务列表屏幕
- - '####'
  - TaskListViewController
- - '####'
  - TaskListView
- - '#####'
  - '`TaskListPresenter`'
- - '###'
  - 添加任务屏幕
- - '#####'
  - '`AddTaskViewController`'
- - '#####'
  - '`AddTaskView`'
- - '#####'
  - '`AddTaskPresenter`'
- - '###'
  - MVP-MyToDos 测试
- - '####'
  - '`AddListViewController`'
- - '###'
  - '`AddListView`'
- - '###'
  - '`AddListViewPresenter`'
- - '##'
  - 小结
- - '#'
  - 4. MVVM：Model–View–ViewModel
- - '##'
  - 什么是 MVVM？
- - '###'
  - 一点历史
- - '###'
  - 工作原理
- - '###'
  - MVVM 中的组件
- - '####'
  - 模型（Model）
- - '####'
  - 视图（View）
- - '####'
  - ViewModel
- - '####'
  - 数据绑定
- - '##'
  - MVVM 的优缺点
- - '###'
  - 优点
- - '###'
  - 缺点
- - '##'
  - MVVM 应用
- - '###'
  - MVVM 分层
- - '####'
  - 模型
- - '#####'
  - 核心数据
- - '#####'
  - 模型
- - '#####'
  - 服务
- - '#####'
  - 扩展
- - '#####'
  - 常量
- - '####'
  - 视图
- - '####'
  - ViewModel
- - '###'
  - MyToDos 数据绑定
- - '#'
  - 什么是 RxSwift？
- - '##'
  - Observables 和 Observers
- - '##'
  - 安装 RxSwift
- - '##'
  - 输入/输出方法
- - '#'
  - MyToDos 应用界面
- - '##'
  - AppDelegate 和 SceneDelegate
- - '##'
  - 主屏幕
- - '###'
  - HomeViewController
- - '###'
  - HomeView
- - '###'
  - '`HomeViewModel`'
- - '###'
  - 添加列表屏幕
- - '####'
  - '`AddListViewController`'
- - '#'
  - '`AddListView`'
- - '##'
  - '`AddListViewModel`'
- - '##'
  - 任务列表界面
- - '###'
  - '`TaskListViewController`'
- - '###'
  - '`TaskListView`'
- - '###'
  - '`TasksListViewModel`'
- - '###'
  - 添加任务屏幕
- - '####'
  - '`AddTaskViewController`'
- - '####'
  - '`AddTaskView`'
- - '##'
  - MVVM-MyToDos 测试
- - '###'
  - RxTest 简介
- - '###'
  - HomeViewModel 测试
- - '###'
  - EmptyState 测试
- - '###'
  - 测试列表删除
- - '###'
  - 列表选择测试
- - '##'
  - MVVM-C：模型-视图-视图模型-协调器
- - '###'
  - 什么是协调器？
- - '###'
  - 在 MyToDos 中使用 MVVM-C
- - '####'
  - SceneDelegate
- - '###'
  - 主屏幕
- - '###'
  - 添加列表屏幕
- - '####'
  - 任务列表界面
- - '####'
  - 添加任务界面
- - '#'
  - 总结
- - '#'
  - 5. VIPER：视图-交互器-展示器-实体-路由器
- - '##'
  - 什么是 VIPER？
- - '###'
  - 一点历史
- - '###'
  - 工作原理
- - '###'
  - VIPER 中的组件
- - '####'
  - 视图
- - '####'
  - 交互器
- - '####'
  - 展示器
- - '####'
  - 实体
- - '####'
  - 路由器
- - '###'
  - VIPER 的优缺点
- - '####'
  - 优点
- - '####'
  - 缺点
- - '##'
  - VIPER 应用
- - '###'
  - 组件之间的通信
- - '###'
  - 展示层与视图之间的通信
- - '###'
  - 展示层与交互器之间的通信
- - '###'
  - 展示层与路由器之间的通信
- - '##'
  - VIPER 分层
- - '###'
  - 模块
- - '###'
  - 服务
- - '###'
  - 公共部分
- - '####'
  - Core Data
- - '####'
  - 组件
- - '####'
  - 模型
- - '####'
  - 扩展
- - '####'
  - 辅助工具
- - '###'
  - MyToDos 应用程序屏幕
- - '####'
  - AppDelegate 和 SceneDelegate
- - '#'
  - 主屏幕模块
- - '##'
  - 主屏幕协议
- - '##'
  - HomeRouter
- - '##'
  - HomeViewController
- - '###'
  - '`HomePresenter`'
- - '###'
  - '`HomeInteractor`'
- - '###'
  - Add List Module
- - '####'
  - '`AddListProtocols`'
- - '###'
  - AddListRouter
- - '###'
  - AddListViewController
- - '###'
  - AddListPresenter
- - '###'
  - AddListInteractor
- - '###'
  - 任务列表模块
- - '#'
  - TaskListProtocols
- - '##'
  - TaskListRouter
- - '##'
  - TaskListViewController
- - '######'
  - '`TaskListPresenter`'
- - '######'
  - '`TaskListInteractor`'
- - '####'
  - Add Task 模块
- - '#####'
  - '`AddTaskProtocols`'
- - '#####'
  - '`AddTaskRouter`'
- - '###'
  - '`AddTaskViewController`'
- - '###'
  - '`AddTaskPresenter`'
- - '###'
  - '`AddTaskInteractor`'
- - '##'
  - VIPER-MyToDos 测试
- - '###'
  - '`HomePresenter`'
- - '###'
  - '`HomeInteractor`'
- - '##'
  - 总结
- - '#'
  - '6. VIP: View–Interactor–Presenter'
- - '##'
  - 什么是 VIP？
- - '###'
  - 一点历史
- - '###'
  - 工作原理
- - '###'
  - VIP 中的组件
- - '#'
  - 视图（UIViewController）
- - '#'
  - 交互器
- - '#'
  - 展示器
- - '#'
  - 路由器
- - '#'
  - 工作者/服务
- - '#'
  - 模型
- - '#'
  - 配置器
- - '#'
  - VIP 的优点和缺点
- - '##'
  - 优点
- - '##'
  - 缺点
- - '###'
  - VIP 层级
- - '####'
  - 场景
- - '####'
  - 服务/工作器
- - '####'
  - 通用
- - '#####'
  - Core Data
- - '#####'
  - 组件
- - '#####'
  - 模型
- - '#####'
  - 扩展
- - '#####'
  - 辅助工具
- - '###'
  - MyToDos 应用屏幕
- - '####'
  - AppDelegate 和 SceneDelegate
- - '####'
  - Home 场景
- - '#####'
  - HomeConfigurator
- - '#####'
  - HomeView
- - '###'
  - '`HomeViewController`'
- - '###'
  - '`HomeInteractor`'
- - '###'
  - '`HomePresenter`'
- - '###'
  - '`HomeModel`'
- - '###'
  - '`HomeRouter`'
- - '##'
  - '`AddList` 场景'
- - '###'
  - '`AddListConfigurator`'
- - '###'
  - '`AddListView`'
- - '###'
  - '`AddListViewController`'
- - '###'
  - '`AddListInteractor`'
- - '###'
  - '`AddListPresenter`'
- - '###'
  - '`AddListModel`'
- - '#'
  - AddListRouter
- - '##'
  - TaskList 场景
- - '###'
  - TaskListConfigurator
- - '###'
  - TaskListView
- - '###'
  - '`TaskListViewController`'
- - '###'
  - '`TaskListInteractor`'
- - '###'
  - '`TaskListPresenter`'
- - '###'
  - '`TaskListModel`'
- - '###'
  - '`TaskListRouter`'
- - '##'
  - AddTask 场景
- - '###'
  - AddTaskConfigurator
- - '###'
  - AddTaskView
- - '####'
  - AddTaskViewController
- - '###'
  - '`AddTaskInteractor`'
- - '###'
  - '`AddTaskPresenter`'
- - '###'
  - '`AddTaskModel`'
- - '###'
  - '`AddTaskRouter`'
- - '##'
  - VIP-MyToDos 测试
- - '###'
  - '`HomeViewControllerTest`'
- - '#'
  - 排版后内容
- - '##'
  - '`HomeInteractorTest`'
- - '#'
  - HomePresenterTest
- - '##'
  - 总结
- - '#'
  - 7. 其他架构模式
- - '##'
  - 引言
- - '##'
  - RIBs：路由器、交互器和构建器
- - '###'
  - 简史
- - '###'
  - 工作原理
- - '###'
  - 组件
- - '####'
  - 路由器（Router）
- - '####'
  - 交互器（Interactor）
- - '####'
  - 构建器（Builder）
- - '####'
  - 组件（Component）
- - '####'
  - 展示器（Presenter）
- - '####'
  - 视图（View）
- - '###'
  - 优点与缺点
- - '####'
  - 优点
- - '####'
  - 缺点
- - '##'
  - Elm 架构
- - '###'
  - 简史
- - '###'
  - 工作原理
- - '###'
  - 组件
- - '####'
  - Model
- - '####'
  - View
- - '####'
  - Update
- - '####'
  - Runtime
- - '###'
  - 优点与缺点
- - '####'
  - 优点
- - '####'
  - 缺点
- - '##'
  - Redux
- - '###'
  - 历史简介
- - '###'
  - 工作原理
- - '###'
  - 组件
- - '####'
  - State
- - '####'
  - Store
- - '####'
  - Reducer
- - '####'
  - Action
- - '####'
  - View
- - '####'
  - Middleware
- - '##'
  - 优点与缺点
- - '###'
  - 优点
- - '###'
  - 缺点
- - '##'
  - TCA：可组合架构
- - '###'
  - 历史简介
- - '###'
  - 工作原理
- - '###'
  - 组件
- - '####'
  - State
- - '####'
  - View
- - '####'
  - Action
- - '####'
  - Reducer
- - '####'
  - Environment
- - '####'
  - Store
- - '##'
  - 优点与缺点
- - '###'
  - 优点
- - '###'
  - 缺点
- - '##'
  - 总结
- - '#'
  - 8. 结论
- - '##'
  - 整洁架构的重要性
- - '#'
  - 向前迈进
- - '##'
  - 索引
