name: Troubleshooting IOS
name_cn: IOS 故障排除指南
slug: troubleshooting-ios
toc:
- - '#'
  - 引言
- - '##'
  - 欢迎
- - '##'
  - 谁应该阅读本书？
- - '##'
  - 本书的结构安排
- - '##'
  - 本书特色
- - '#'
  - 第一部分：故障排除基础
- - '##'
  - 第 1 章：学习一些常规故障排除技巧
- - '###'
  - 重启与重新启动
- - '####'
  - 重启你的设备
- - '####'
  - 重新启动你的设备硬件
- - '###'
  - 更新软件
- - '###'
  - 从备份恢复你的设备
- - '###'
  - 恢复出厂设置
- - '####'
  - 通过 iTunes 恢复出厂设置
- - '####'
  - 在设备上恢复出厂设置
- - '###'
  - 排除已连接配件的故障
- - '###'
  - 高级故障排除技巧
- - '####'
  - 无法启动 iOS 时的恢复出厂设置
- - '####'
  - 抹掉你的设备
- - '##'
  - 第 2 章：修复网络和蜂窝网络问题
- - '###'
  - 解决 Wi-Fi 问题
- - '####'
  - 你无法访问 Wi-Fi 网络：第一部分
- - '####'
  - 你无法访问 Wi-Fi 网络：第二部分
- - '####'
  - iOS 自动连接到了你不再想用的网络
- - '####'
  - 你频繁收到加入附近 Wi-Fi 网络的提示
- - '####'
  - 你想要连接到一个隐藏的 Wi-Fi 网络
- - '####'
  - 你通过隔空投送发送文件时遇到问题
- - '####'
  - iOS 与 macOS 连接问题故障排除
- - '###'
  - 蜂窝网络问题故障排除
- - '####'
  - 可通过 Wi-Fi 发送电子邮件，但无法通过蜂窝网络发送
- - '####'
  - 不确定自己使用了多少数据
- - '####'
  - 想要阻止 iOS 设备使用蜂窝数据
- - '####'
  - 希望更精细地控制 iOS 设备如何使用蜂窝数据
- - '####'
  - 你想要阻止 iOS 使用数据漫游
- - '###'
  - 蓝牙问题故障排除
- - '####'
  - 你找不到蓝牙设备
- - '####'
  - 你无法与蓝牙设备配对
- - '####'
  - 通过已配对耳机听不到声音
- - '##'
  - 第 3 章：解决应用问题
- - '###'
  - 常规应用故障排除
- - '####'
  - 你发现搜索困难，因为 iOS 从太多应用中返回结果
- - '####'
  - 你找不到某个应用
- - '####'
  - 某个应用显示太多通知
- - '####'
  - 你的 Facebook 数据未出现在“通讯录”或“日历”应用中
- - '####'
  - 某个应用卡住了
- - '####'
  - 你的屏幕对触摸无响应
- - '####'
  - 某个应用占用大量空间
- - '####'
  - 你想控制第三方对你的应用的使用权限
- - '####'
  - 您在使用 Handoff 功能时遇到问题
- - '###'
  - 高级应用故障排除
- - '####'
  - 您打开了太多应用
- - '##'
  - 第 4 章：解决网页问题
- - '###'
  - 网页浏览问题故障排除
- - '####'
  - 您无法正常查看页面文本或其他信息
- - '####'
  - 滚动回长网页顶部需要很长时间
- - '####'
  - 你想查看网站的桌面版
- - '####'
  - 你觉得网页的额外功能过于干扰
- - '####'
  - 你想在后台打开新标签页
- - '####'
  - 你想在离线时阅读一个或多个页面
- - '####'
  - Safari 不会询问是否存储网站密码
- - '####'
  - 你想保存信用卡数据
- - '####'
  - 你想查看网站的弹出式窗口
- - '####'
  - 你想在点击链接前查看其地址
- - '###'
  - 搜索问题故障排除
- - '####'
  - 你想使用不同的搜索引擎
- - '####'
  - 在网页中查找特定信息并非易事
- - '####'
  - 你想使用语音命令搜索网络
- - '##'
  - 第 5 章：解决电子邮件故障
- - '###'
  - 发送电子邮件故障排除
- - '####'
  - 发送邮件时“邮件”使用了错误的账户
- - '####'
  - 你想阻止某个账户接收电子邮件
- - '####'
  - 你不再需要某个账户
- - '####'
  - 你想保存一封未完成的电子邮件
- - '####'
  - 排查使用第三方账户时的外发电子邮件问题
- - '####'
  - 使用特定账户无法发送 POP 邮件
- - '####'
  - 使用 Siri 语音命令发送电子邮件时遇到问题
- - '###'
  - 接收电子邮件疑难解答
- - '####'
  - 你在设备上能收到邮件，但在电脑上却收不到
- - '####'
  - 您收到大量垃圾邮件
- - '####'
  - 您想禁用邮件中的远程图片
- - '####'
  - 您不再希望邮件应用按主题整理邮件
- - '####'
  - 已删除的邮件正在从废纸篓文件夹中移除
- - '####'
  - 您看不到“所有收件箱”文件夹
- - '##'
  - 第 6 章：修复电话问题
- - '###'
  - 排查来电问题
- - '####'
  - 你需要将来电静音
- - '####'
  - 你无法使用音量按钮调节铃声音量
- - '####'
  - 你想要将来电直接发送到语音信箱
- - '####'
  - 你想要能够使用其他设备接听电话
- - '####'
  - 你无法访问“在其他设备上通话”设置
- - '####'
  - 你想在不接听电话的情况下回复来电
- - '####'
  - 你想设置提醒稍后回电
- - '####'
  - 你只想允许特定人群的来电
- - '####'
  - 你不想在通话时看到其他来电的信息
- - '####'
  - 您正收到不受欢迎的来电
- - '####'
  - 您更愿意在其他号码上接听 iPhone 来电
- - '###'
  - 拨出电话故障排除
- - '####'
  - 您想拨打电话，但套餐仅剩几分钟
- - '####'
  - 您想在电话号码中包含分机号或菜单选项
- - '####'
  - 您打电话时不想被识别身份
- - '####'
  - 你想将通话置于保持状态
- - '##'
  - 第 7 章：解决相机和照片相关问题
- - '###'
  - 相机问题故障排除
- - '####'
  - 你的很多照片都模糊不清
- - '####'
  - 你的弱光照片通常太暗、有颗粒感或模糊不清
- - '####'
  - 对焦或曝光设置难以固定
- - '####'
  - 你想让自己出现在后置摄像头拍摄的照片中
- - '####'
  - 难以拍出笔直的照片
- - '###'
  - 照片问题故障排除
- - '####'
  - 照片曝光不当或存在类似光线问题
- - '####'
  - 照片颜色显示异常
- - '####'
  - 你的黑白照片效果有待提升
- - '####'
  - 照片中出现一处或多处红眼
- - '####'
  - 照片中包含你想去除的元素
- - '####'
  - 照片不水平
- - '##'
  - 第 8 章：保护你的设备
- - '###'
  - 锁定你的设备
- - '####'
  - 你想用密码锁定设备
- - '####'
  - 你希望确保数据不会落入恶意之手
- - '####'
  - 你需要在 iPhone 锁定时拨打紧急电话
- - '####'
  - 你正在使用密码，但解锁设备时密码并不总是出现
- - '####'
  - 你希望可以用指纹解锁设备
- - '####'
  - 无法使用指纹解锁 iOS 设备
- - '####'
  - 不想忘记为 Touch ID 配置了哪个指纹
- - '####'
  - 想要将设备配置为自动锁定
- - '###'
  - 备份你的设备
- - '####'
  - 想要在不进行同步的情况下备份设备
- - '####'
  - 你想让 iOS 自动备份你的设备
- - '####'
  - 你遇到 iCloud 备份问题
- - '###'
  - 保护丢失的设备
- - '####'
  - 你想确保能够找到丢失的设备
- - '####'
  - 你想在地图上定位丢失的设备
- - '####'
  - 你想要通过播放声音定位丢失的设备
- - '####'
  - 你想要锁定丢失设备上的数据
- - '####'
  - 你想要擦除丢失设备上的数据
- - '##'
  - 第 9 章：解决隐私问题
- - '###'
  - 解决通用隐私问题
- - '####'
  - 输入时每个字符都会弹出，造成隐私风险
- - '####'
  - 你想阻止某个应用使用其他应用的数据
- - '####'
  - 你不想让位置被追踪
- - '####'
  - 你想阻止某个应用使用你的位置
- - '####'
  - 你想阻止一个或多个系统服务使用你的位置
- - '####'
  - 防止 iOS 存储常用位置列表
- - '####'
  - 不想与家人和朋友共享您的位置
- - '####'
  - 不想将设备使用信息发送给 Apple
- - '####'
  - 不想接收定向广告
- - '####'
  - 不想被显示您所在地区的热门应用
- - '###'
  - 解决网页浏览隐私问题
- - '####'
  - 想要删除已访问的网站列表
- - '####'
  - 不希望 Safari 在搜索时显示建议
- - '####'
  - 希望浏览网页时不存储关于所访问网站的数据
- - '####'
  - 希望确保不被在线广告商追踪
- - '####'
  - 你想要删除已保存的信用卡数据
- - '####'
  - 你想要删除已保存的网站密码
- - '##'
  - 第 10 章：修复电池与充电问题
- - '###'
  - 追踪电池使用情况
- - '####'
  - 你想要精确知道剩余电量的百分比
- - '####'
  - 你想要了解在电池供电状态下设备的使用情况
- - '####'
  - 你怀疑某个应用耗电过多
- - '###'
  - 延长电池续航时间
- - '####'
  - 阻止所有应用在后台运行
- - '####'
  - 阻止特定应用在后台运行
- - '####'
  - 希望 iOS 设备使用更少电量
- - '####'
  - 尽量节省电池电量
- - '###'
  - 排查其他电池问题
- - '####'
  - 你想最大化电池的使用寿命
- - '####'
  - 你的电池无法充电
- - '##'
  - 第 11 章：解决无障碍访问问题
- - '###'
  - 应对视觉挑战
- - '####'
  - 你想让文本更易阅读
- - '####'
  - 你想要一种快速放大屏幕的方法
- - '####'
  - 你想要听到屏幕上的内容
- - '####'
  - 你想用 iOS 设备放大现实世界中的物品
- - '###'
  - 克服身体挑战
- - '####'
  - 双击主屏幕按钮不显示多任务屏幕
- - '####'
  - 你发现使用触控 ID 解锁设备很困难
- - '####'
  - 你打字时会出现不必要的按键
- - '####'
  - iOS 有时会误解或无法识别您的轻点操作
- - '###'
  - 克服听觉挑战
- - '####'
  - 耳机声音不平衡
- - '####'
  - 您听不到提醒
- - '#'
  - 附录：其他故障排除
- - '##'
  - 排查其他 iOS 问题
- - '###'
  - 排查杂项问题
- - '####'
  - 您发现很难触及 iPhone 屏幕顶部的项目
- - '####'
  - 双击主屏幕按钮无反应
- - '####'
  - 您的 iOS 设备在不恰当的时间打扰您
- - '####'
  - 屏幕键盘的咔嗒声让你（和你附近的人）抓狂
- - '####'
  - 输入两个或更多空格时，iOS 总会在空格前添加一个句点 (.)
- - '####'
  - 您无法用另一种语言输入
- - '####'
  - 您的设备显示屏在夜间使用时亮度过于刺眼
- - '####'
  - 您想控制孩子在 iOS 设备上能看到和能操作的内容
- - '###'
  - 故障排除：连接与同步问题
- - '####'
  - iTunes 无法识别您的设备
- - '####'
  - iTunes 无法同步您的设备
- - '####'
  - 同步音乐或视频时遇到问题
- - '####'
  - 每次连接设备时都会打开某个应用
