name: Beginning IOS 6 Games Development
name_cn: IOS 6 游戏开发入门指南
slug: beginning-ios-6-games-development
toc:
- - '#'
  - iOS6 游戏开发入门
- - '#'
  - 内容概览
- - '#'
  - 致谢
- - '#'
  - 第 1 章：第一个简单的游戏
- - '##'
  - 在 Xcode 中创建项目：示例 1
- - '###'
  - 项目的文件结构
- - '###'
  - 自定义你的项目
- - '###'
  - 排列 Xcode 视图以简化操作
- - '###'
  - 添加新视图
- - '###'
  - 简单导航
- - '##'
  - 添加“石头、剪刀、布”视图
- - '##'
  - 自定义 UIView
- - '##'
  - 本章小结
- - '#'
  - 第 2 章：搭建你的游戏项目
- - '##'
  - 创建你的游戏项目
- - '###'
  - 在设备列表中选择“通用”(Universal)
- - '##'
  - 自定义通用应用程序
- - '##'
  - iOS 应用程序的初始化方式
- - '##'
  - 理解 UIViewControllers
- - '##'
  - 基于设备类型自定义行为
- - '##'
  - 以通用方式图形化设计 UI
- - '##'
  - Interface Builder 初探
- - '##'
  - 向 XIB 文件添加 UI 元素
- - '##'
  - 响应屏幕方向变化
- - '##'
  - 本章小结
- - '#'
  - 第 3 章：探索游戏应用生命周期
- - '##'
  - 理解游戏中的视图
- - '##'
  - 探索每个视图扮演的角色
- - '##'
  - 理解项目结构
- - '##'
  - 为多视图配置应用程序
- - '###'
  - 回顾 `GameController_iPhone.xib`
- - '###'
  - 回顾 `GameController.h`
- - '##'
  - 根据用户操作切换视图
- - '##'
  - 使用委托来传递应用程序状态
- - '##'
  - HighscoreController：一个简单、可复用的组件
- - '##'
  - 保存游戏状态
- - '##'
  - 归档与解档游戏状态
- - '##'
  - 实现生命周期任务
- - '##'
  - 本章小结
- - '#'
  - 第 4 章：快速构建一个输入驱动的游戏
- - '#'
  - 第 5 章：快速构建一个逐帧动画游戏
- - '#'
  - 第 6 章：创建你的角色：游戏引擎、图像 Actor 与行为
- - '#'
  - 第 7 章：构建你的游戏：矢量 Actor 与粒子系统
- - '#'
  - 第 8 章：构建你的游戏：理解手势与移动
- - '#'
  - 第 9 章：Game Center 与社交媒体
- - '#'
  - 第 10 章：通过 Apple App Store 变现
- - '#'
  - 第 11 章：为你的游戏添加音效
- - '#'
  - 第 12 章：一个完整的游戏：《腰带指挥官》
- - '#'
  - 第 13 章：物理！
- - '#'
  - 附录 A：设计与创建图形
- - '#'
  - 索引
- - '#'
  - 关于作者
- - '#'
  - 关于技术审校
- - '#'
  - 第四章：快速构建一个输入驱动的游戏
- - '##'
  - 探索如何将内容显示到屏幕上
- - '##'
  - 理解 `UIView`
- - '###'
  - 核心图形类型定义
- - '###'
  - 使用 Core Graphics 类型
- - '##'
  - 理解动画
- - '##'
  - UIView 的静态动画任务
- - '##'
  - 构建游戏 Coin Sorter
- - '##'
  - 实现游戏状态
- - '##'
  - 初始化与设置
- - '##'
  - 开始新游戏
- - '##'
  - 继续游戏
- - '##'
  - 为每个硬币初始化 UIView
- - '###'
  - '`swap:With:`'
- - '##'
  - 解释用户输入
- - '##'
  - 使用 Core Animation 对视图进行动画处理
- - '##'
  - 总结
- - '#'
  - 第 5 章：快速构建一个逐帧游戏
- - '##'
  - 设置你的第一个逐帧动画
- - '###'
  - 简单移动
- - '###'
  - 实现这些类
- - '##'
  - 移动飞船
- - '##'
  - 响应用户点击
- - '##'
  - 理解 CADisplayLink 和 NSRunLoop
- - '##'
  - 抽象 UI
- - '###'
  - 理解 Actor
- - '###'
  - Example2Controller 概述
- - '###'
  - 一个简单的演员
- - '###'
  - 演员子类：`Viper02`
- - '###'
  - Actor 子类：`Asteroid02`
- - '##'
  - 在屏幕上绘制 Actor
- - '###'
  - 为每个演员更新 UIView
- - '###'
  - 在屏幕上放置`UIImageView`
- - '##'
  - 演员状态与动画
- - '###'
  - 翻滚效果
- - '###'
  - 旋转效果
- - '##'
  - 总结
- - '#'
  - 第 6 章：创建你的角色：游戏引擎、图像 Actor 和行为
- - '##'
  - 理解游戏引擎类
- - '###'
  - '`GameController`类'
- - '##'
  - 设置 `GameController`
- - '##'
  - 调用 `displayLinkCalled` 和 `updateScene`
- - '##'
  - 更新 `updateScene`
- - '##'
  - 调用 `doAddActors` 和 `doRemoveActors`
- - '##'
  - 添加和移除演员
- - '##'
  - 排序演员
- - '##'
  - 管理`UIView`
- - '##'
  - Actor 类
- - '##'
  - 实现 Actor
- - '##'
  - 使用强化道具角色
- - '##'
  - 实现我们的强化道具角色
- - '##'
  - 为角色创建 `UIImageView`
- - '##'
  - 更新我们的视图
- - '##'
  - 通过示例理解行为
- - '###'
  - 行为：线性运动
- - '###'
  - 行为：`ExpireAfterTime`
- - '##'
  - 总结
- - '#'
  - 第 7 章：构建你的游戏：矢量角色与粒子系统
- - '##'
  - 飞碟、子弹、护盾和生命条
- - '###'
  - '`doSetup`任务'
- - '###'
  - '`updateScene`任务'
- - '##'
  - Actor 类
- - '###'
  - 实例化 Saucer 类
- - '###'
  - 实例化 HealthBar 类
- - '###'
  - FollowActor 行为类
- - '###'
  - Bullet 类
- - '###'
  - 通过 VectorRepresentation 使用 Core Graphics 绘制 Actor
- - '###'
  - VectorRepresentation 类
- - '##'
  - '基于向量的演员的 UIView: VectorActorView'
- - '##'
  - 绘制 HealthBar
- - '##'
  - 绘制 Bullet 类
- - '##'
  - 为游戏添加粒子系统
- - '##'
  - 简单粒子系统
- - '###'
  - Asteroid 类
- - '###'
  - 用同一个类表示小行星和粒子
- - '###'
  - 销毁小行星
- - '##'
  - Particle 类
- - '##'
  - 创建基于矢量的粒子
- - '##'
  - 总结
- - '#'
  - 第 8 章：构建你的游戏：理解手势与运动
- - '##'
  - 触摸输入：基础
- - '##'
  - 扩展`UIView`以接收触摸事件
- - '##'
  - 查看事件代码
- - '##'
  - 将触摸事件应用于角色
- - '##'
  - 理解手势识别器
- - '##'
  - 轻点手势
- - '##'
  - '`TemporaryBehavior`类'
- - '##'
  - 捏合手势
- - '##'
  - 响应捏合手势
- - '##'
  - 平移（或拖动）手势
- - '##'
  - 响应平移手势
- - '##'
  - 旋转手势
- - '##'
  - 长按手势
- - '##'
  - 响应用户操作
- - '##'
  - 添加子弹
- - '##'
  - 轻扫手势
- - '##'
  - 解读设备运动
- - '###'
  - 响应运动事件（摇动）
- - '###'
  - 响应加速度计数据
- - '##'
  - 总结
- - '#'
  - 第 9 章：Game Center 与社交媒体
- - '##'
  - Game Center
- - '###'
  - 在 iTunes Connect 中启用 Game Center
- - '###'
  - 在游戏中使用 Game Center
- - '###'
  - 为用户启用 Game Center
- - '##'
  - 向排行榜提交分数
- - '##'
  - 授予成就
- - '##'
  - Twitter 集成
- - '##'
  - Facebook 集成
- - '###'
  - 创建 Facebook 应用
- - '###'
  - 使用 Facebook 进行身份验证
- - '###'
  - 向 Facebook 发布内容
- - '##'
  - 总结
- - '#'
  - 第 10 章：通过 Apple App Store 盈利
- - '##'
  - 应用内购买
- - '###'
  - 购买类型概览
- - '####'
  - 非消耗型
- - '####'
  - 消耗型
- - '####'
  - 免费订阅
- - '####'
  - 自动续订订阅
- - '####'
  - 非续订订阅
- - '##'
  - 准备应用内购买
- - '##'
  - 启用和创建应用内购买
- - '###'
  - 在 iTunes Connect 中启用 App 内购买
- - '###'
  - 创建测试用户
- - '###'
  - 用于 App 内购买的类与代码
- - '##'
  - 应用内购买实现
- - '##'
  - 根据已有购买记录驱动 UI
- - '##'
  - 发起购买
- - '##'
  - 响应成功购买
- - '##'
  - 总结
- - '#'
  - 第 11 章：为你的游戏添加声音
- - '##'
  - 如何播放声音
- - '##'
  - 正确的音频行为
- - '###'
  - 用户希望将设备切换至静音时就能静音
- - '###'
  - 你的游戏可能不是唯一发出声音的应用
- - '###'
  - 你的游戏不是唯一运行的应用
- - '##'
  - 在你的游戏中实现声音
- - '##'
  - 设置音频
- - '##'
  - 响应其他音频变化
- - '##'
  - 游戏中的音频
- - '###'
  - 设置`GameController`
- - '###'
  - 游戏内事件的音效
- - '##'
  - 由角色驱动的音频
- - '##'
  - 总结
- - '#'
  - 第 12 章：一个完整的游戏：Belt Commander
- - '##'
  - Belt Commander：游戏概述
- - '##'
  - 图形与视图导航
- - '##'
  - 实现视图到视图的导航
- - '###'
  - 启动应用
- - '###'
  - XIB 文件
- - '##'
  - 视图导航
- - '##'
  - 实现游戏
- - '###'
  - 游戏类
- - '###'
  - Actor
- - '###'
  - Representation
- - '##'
  - '`BeltCommanderController` 设置与游戏逻辑'
- - '###'
  - 理解设置过程
- - '###'
  - 新游戏
- - '###'
  - 处理输入
- - '###'
  - '`BeltCommanderController`，一步一步来'
- - '####'
  - 添加 Actor
- - '####'
  - 碰撞检测
- - '####'
  - 更新 HUD
- - '##'
  - 实现 Actor
- - '###'
  - Viper Actor
- - '###'
  - Asteroid 类
- - '###'
  - Saucer 类
- - '###'
  - Powerup 类
- - '##'
  - 总结
- - '#'
  - 第十三章：物理学！
- - '##'
  - 基于物理的示例概述
- - '##'
  - Box2D 概述
- - '###'
  - 世界
- - '###'
  - 物体
- - '##'
  - 夹具
- - '##'
  - 将 Box2D 添加到 Xcode 项目
- - '##'
  - 理解示例
- - '##'
  - 扩展`GameController`
- - '##'
  - 物理角色
- - '##'
  - 扩展 PhysicsActor
- - '##'
  - 一点清理工作
- - '##'
  - 总结
- - '#'
  - 附录 A：设计与创建图形
- - '##'
  - 电子游戏中的美术
- - '##'
  - 电子游戏中的风格
- - '##'
  - 品牌与感知
- - '##'
  - 创建图像文件
- - '##'
  - 命名规范
- - '##'
  - 支持图像
- - '###'
  - 支持的图片尺寸
- - '###'
  - 多分辨率图像
- - '###'
  - 多分辨率示例
- - '##'
  - 创建最终资源
- - '###'
  - 屏幕可用空间
- - '###'
  - iPhone（Retina 屏）和 iPad 上的 Coin Sorter 游戏
- - '##'
  - 工具
- - '###'
  - GIMP
- - '###'
  - Blender 3D
- - '###'
  - Inkscape
- - '##'
  - 总结
