name: Beginning IOS Storyboarding
name_cn: IOS Storyboarding 入门指南
slug: beginning-ios-storyboarding
toc:
- - '##'
  - 修复说明
- - '#'
  - 目录
- - '##'
  - 内容概要
- - '##'
  - 前言：关于作者
- - '###'
  - Rory Lewis 博士
- - '###'
  - 为何你会与刘易斯博士产生共鸣
- - '###'
  - 跨越 17 年后
- - '###'
  - 过去——现在——未来
- - '###'
  - 为何撰写本书？
- - '###'
  - 斯蒂芬·M·莫拉科
- - '###'
  - 尤莉娅·麦卡锡
- - '##'
  - 关于合作作者
- - '##'
  - 关于技术审校
- - '#'
  - 简介
- - '##'
  - 你将学到什么
- - '##'
  - 谁应该阅读本书？
- - '#'
  - 第 1 章
- - '##'
  - 准备工作
- - '##'
  - 必需品与配件
- - '###'
  - 获取 Mac
- - '###'
  - 获取 OS X
- - '###'
  - 成为开发者
- - '####'
  - 做出选择
- - '####'
  - 安装 Xcode
- - '#####'
  - 关于 DemoMonkey
- - '##'
  - 准备你的首个 iPhone/iPad 项目
- - '###'
  - 安装 DemoMonkey
- - '#'
  - 第 2 章
- - '##'
  - 基础
- - '###'
  - helloAlien：一个快速示例应用程序
- - '####'
  - 准备工作
- - '####'
  - 第 1 步：创建一个能跳转到次级视图的按钮
- - '####'
  - 第 2 步：将信息从辅助视图（外星视图）传回主视图
- - '####'
  - 步骤 3：将信息发送到二级视图（外星人视图）
- - '####'
  - 步骤 4：自定义 Segue
- - '#'
  - 第 3 章
- - '##'
  - 使用 MapView 进行故事板设计
- - '###'
  - '`flickrPhotoMap`：一个单视图应用'
- - '####'
  - 准备工作
- - '####'
  - 第一步：建立数据连接并在地图上显示地理标记照片
- - '####'
  - 步骤 2：通过标注气泡跳转到辅助场景
- - '####'
  - 步骤 3：创建一个允许用户为照片打分的模态场景
- - '#'
  - 第四章
- - '##'
  - 构建一个工具型应用
- - '###'
  - utilityScales：一个工具型应用
- - '###'
  - 预备知识
- - '###'
  - 步骤 1：项目设置
- - '####'
  - 步骤 2：准备故事板
- - '####'
  - 第三步：编写翻转视图控制器
- - '#'
  - 第 5 章
- - '##'
  - 为基于页面的应用编排故事板
- - '###'
  - futureTravel：一个基于页面的应用
- - '###'
  - 准备工作
- - '####'
  - 步骤 1：从模板创建
- - '####'
  - 第 2 步：准备故事板
- - '####'
  - 步骤三：编码：`ModelController`
- - '####'
  - 第 4 步：代码：DataViewController
- - '#####'
  - 图 5-51. *打开实现文件并导入页面数据对象。*
- - '#####'
  - 图 5-52. *引入 setter 覆盖方法。*
- - '#####'
  - 图 5-53. *让 `viewWillAppear` 遵循我们自己的文本。*
- - '#####'
  - 图 5-54. *仅更改为横向。*
- - '#####'
  - 图 5-55. *添加我们的私有方法。*
- - '####'
  - 步骤 5：代码：`RootViewController`
- - '#'
  - 第 6 章
- - '##'
  - 精通表格视图与故事板：Core Data 设置
- - '###'
  - bookManager：一个主从应用
- - '###'
  - 准备工作
- - '####'
  - 步骤 1/3：设置文件、图片、Core Data 和数据模型
- - '#'
  - 第 7 章
- - '##'
  - 掌握故事板中的表格视图：设计流程
- - '###'
  - 第 2 步：为应用程序制作故事板
- - '####'
  - 配置主场景
- - '####'
  - 设计顶层视图：分类场景
- - '####'
  - 设计顶层视图：作者场景
- - '####'
  - 布局主图书列表视图：图书场景
- - '####'
  - 制作详情视图的故事板：图书详情场景
- - '####'
  - 创建输入和保存新数据的界面：添加图书场景
- - '#####'
  - 进行最终调整
- - '#'
  - 第 8 章
- - '##'
  - 使用故事板掌握表视图：编写后端代码
- - '###'
  - 第 3 步：在故事板元素后面编写代码并调整一些故事板必要设置
- - '####'
  - 创建自定义 `UITableViewCell` 子类
- - '####'
  - 修改详细视图控制器
- - '####'
  - 创建 SelectionViewController
- - '####'
  - 编写“添加图书”视图控制器
- - '####'
  - 连接图书场景
- - '#####'
  - 为分类场景添加代码
- - '#####'
  - 实现作者场景
- - '#####'
  - 收尾与加载测试数据
- - '#'
  - 第 9 章
- - '##'
  - '单视图 #3：wanderBoard 第一部分'
- - '###'
  - wanderBoard：单视图应用
- - '###'
  - 准备工作
- - '####'
  - 我们如何创建 3D 场景
- - '####'
  - 步骤 1：设置文件、项目设置和资源
- - '####'
  - 第 2 步：准备故事板
- - '#'
  - 第 10 章
- - '##'
  - '单视图 #3：wanderBoard 第二部分'
- - '###'
  - 第 3 步：完成 ViewController 头文件和实现文件
- - '###'
  - 步骤 4a：借助辅助创建后续八个场景
- - '####'
  - 场景 2
- - '####'
  - 场景 3：复制现有场景
- - '####'
  - 场景 4
- - '####'
  - 场景 5
- - '####'
  - 场景 6
- - '####'
  - 场景 7
- - '####'
  - 场景 8
- - '####'
  - 场景 9
- - '#'
  - 第 11 章
- - '##'
  - '单视图 #3：wanderBoard 第三部分'
- - '###'
  - 第 4b 步：创建最终的九个场景
- - '#'
  - 第十二章
- - '##'
  - 你已经走了多远
- - '###'
  - 最终思考
- - '####'
  - 在单个应用中使用多个 Storyboard 文件
- - '####'
  - 将所有 `.xib` 文件放在一个 Storyboard 的“篮子”里
- - '####'
  - 你是什么意思，并非所有场景都适合放在 Storyboard 文件中？
- - '###'
  - 嘿，我有问题！
- - '#'
  - 索引
- - '##'
  - A
- - '##'
  - B
- - '##'
  - 后端编码
- - '###'
  - '`AddBookViewController`'
- - '###'
  - '`AuthorsViewController`'
- - '###'
  - '`BooksViewController`'
- - '###'
  - '`CategoriesViewController`'
- - '###'
  - 详细视图控制器
- - '###'
  - '`SelectionViewController`'
- - '###'
  - '`UITableViewCell` 子类'
- - '###'
  - 收尾和加载测试数据
- - '##'
  - C
- - '###'
  - '`CategoriesViewController`'
- - '##'
  - D
- - '###'
  - '`DataViewController`'
- - '###'
  - '`DataViewControllerDelegate`，255'
- - '###'
  - 详情视图控制器
- - '###'
  - '`DemoMonkey`'
- - '###'
  - 达莫达尔河谷公司 (DVC)，270
- - '##'
  - F
- - '###'
  - '`FlipsdeViewController`'
- - '###'
  - '`flickrPhotoMap`'
- - '###'
  - 数据连接与地理标记照片展示
- - '###'
  - 模型场景创建
- - '##'
  - I
- - '###'
  - '`ModelController`'
- - '###'
  - '`RootViewController`'
- - '###'
  - '`storyboardPreparation`'
- - '###'
  - '`templates`'
- - '###'
  - '![images](img/square11.jpg) I'
- - '###'
  - iPhone 和 iPad
- - '####'
  - '`DemoMonkey`'
- - '####'
  - '`necessitiesAndAccessories`'
- - '####'
  - '`project`'
- - '####'
  - '`SDK`'
- - '##'
  - J, K, L
- - '###'
  - '![images](img/square11.jpg) J, K, L'
- - '##'
  - M
- - '###'
  - 主从应用程序。*另请参阅* Storyboard
- - '####'
  - 核心数据设置
- - '####'
  - '`ModelController`'
- - '##'
  - N, O, P, Q
- - '##'
  - R
- - '##'
  - S, T
- - '###'
  - 'SelectionViewController（选择视图控制器）  '
- - '###'
  - '软件开发工具包（SDK）  '
- - '###'
  - 'Xcode  '
- - '###'
  - 添加图书场景
- - '###'
  - 作者场景
- - '###'
  - 图书场景
- - '###'
  - 分类场景
- - '###'
  - 详情视图
- - '###'
  - 主场景
- - '###'
  - 准备
- - '###'
  - 微调
- - '##'
  - U
- - '##'
  - V
- - '##'
  - W
- - '###'
  - '`wanderBoard` 应用'
- - '####'
  - 3D 景观，481–482
- - '####'
  - 文件、项目设置与资源
- - '####'
  - 最终九个场景
- - '####'
  - 准备工作，480
- - '####'
  - 四步流程，510
- - '####'
  - 单视图应用
- - '####'
  - Storyboard
- - '####'
  - ViewController 头文件与实现文件
- - '##'
  - X, Y, Z
