name: Beginning iOS apps with Facebook and Twitter APIs
name_cn: Facebook 和 Twitter APIs 的 iOS 应用入门指南
slug: beginning-ios-apps-with-facebook-and-twitter-apis
toc:
- - '#'
  - 使用 Facebook 与 Twitter API 开发 iOS 应用：适用于 iPhone、iPad 和 iPod touch
- - '##'
  - 内容一览
- - '##'
  - 目录
- - '#'
  - 第 6 章：欢迎来到时间线
- - '#'
  - 第 7 章：访问人物、地点、对象与关系
- - '#'
  - 第 8 章：POST 请求、数据建模与离线处理
- - '#'
  - 第 9 章：处理位置感知与流数据
- - '#'
  - 第 10 章：使用开源工具与其他实用功能
- - '#'
  - 第 11 章：你能（以及不能）构建的应用
- - '#'
  - 第 12 章：社交 iOS 应用的 UI 设计与体验指南
- - '#'
  - 第 13 章：Twitter UI 设计
- - '#'
  - 第 14 章：Facebook UI 设计
- - '#'
  - 索引
- - '##'
  - 关于作者
- - '##'
  - 关于技术审校者
- - '#'
  - 前言
- - '#'
  - 第 1 章
- - '##'
  - 社交图谱能为你的应用带来什么
- - '###'
  - 这本书是写给谁的？
- - '####'
  - 你需要准备什么
- - '####'
  - 你应该了解什么
- - '####'
  - 你将学到什么
- - '###'
  - 了解社交图谱
- - '####'
  - 简要用例
- - '#'
  - Facebook
- - '#'
  - Twitter
- - '##'
  - 平台与服务的简要概述
- - '###'
  - Facebook
- - '####'
  - 读取
- - '####'
  - 发布
- - '####'
  - 搜索
- - '###'
  - Twitter
- - '####'
  - 核心 API
- - '####'
  - 搜索 API
- - '####'
  - 流式 API
- - '###'
  - iOS 上的社交图谱
- - '####'
  - 本地通知
- - '####'
  - 任务完成
- - '####'
  - 快速任务切换与保存状态
- - '#'
  - 背景音乐、定位与 VOIP
- - '#'
  - 短信：搜索与应用内短信
- - '#'
  - 更强大的照片与日历功能
- - '#'
  - 全新摄像头与闪光灯
- - '#'
  - 地图叠加层
- - '#'
  - iAd 广告平台
- - '#'
  - 快速查看
- - '#'
  - 数学 API
- - '#'
  - 文件传输
- - '##'
  - 小结
- - '#'
  - 第二章
- - '#'
  - 隐私，隐私，还是隐私
- - '##'
  - 旧有方式
- - '##'
  - 热点问题简史
- - '###'
  - Facebook 的前科
- - '####'
  - Twitter 的过往记录
- - '###'
  - OAuth 如何改变一切
- - '####'
  - 新标准的出现
- - '###'
  - 用户真正“想要”什么
- - '###'
  - 教育您的用户
- - '###'
  - 关于动态消息的说明
- - '###'
  - 如果遇到安全漏洞该怎么办
- - '###'
  - 总结
- - '##'
  - 第 3 章
- - '#'
  - 选择你的武器！
- - '##'
  - 它们各有什么优势？
- - '###'
  - Facebook
- - '###'
  - Twitter
- - '##'
  - 开始使用 Facebook 强大的开发者工具
- - '###'
  - 使用 Facebook 的 API
- - '####'
  - 进行 API 调用
- - '####'
  - 显示对话框
- - '####'
  - 错误处理
- - '#'
  - 登出
- - '##'
  - Twitter 的次优（但仍很棒！）工具
- - '###'
  - 使用 MGTwitterEngine
- - '####'
  - 进行 API 调用
- - '####'
  - 错误处理
- - '####'
  - 使用 ShareKit
- - '##'
  - 总结
- - '#'
  - 第 4 章：准备工作
- - '##'
  - 搞定 Git
- - '###'
  - Github.com
- - '###'
  - 安装 Git
- - '###'
  - Git 基础
- - '###'
  - 收藏这些 Twitter 资源
- - '###'
  - 也请收藏这些 Facebook 资源
- - '###'
  - 关于 Bug 追踪的说明
- - '##'
  - Hello Facebook
- - '###'
  - 创建项目
- - '####'
  - 添加 Facebook iOS SDK 源代码
- - '###'
  - 添加 UIViewController
- - '###'
  - 为 Facebook 创建应用
- - '###'
  - Hello Twitter
- - '####'
  - 创建项目
- - '###'
  - 添加 `MGTwitterEngine` 源代码
- - '###'
  - 添加 `UIViewController`
- - '###'
  - 启动 Twitter 引擎
- - '###'
  - 接下来，关于安全性
- - '##'
  - 第 5 章
- - '##'
  - 使用 OAuth 和账户进行安全开发
- - '###'
  - 关于 OAuth
- - '####'
  - OAuth 工作原理
- - '#####'
  - Facebook 和 Twitter 中的 OAuth
- - '###'
  - Facebook 中的 OAuth
- - '###'
  - 使用 Facebook 实现单点登录
- - '###'
  - OAuthFacebook 项目
- - '###'
  - 通过自定义 URL Scheme 实现应用间通信
- - '###'
  - 登录 Facebook
- - '###'
  - 注销 Facebook
- - '###'
  - 判断 iOS 是否支持应用后台运行
- - '##'
  - Twitter 中的 OAuth
- - '####'
  - 创建 Twitter 应用
- - '#####'
  - OAuthTwitter 项目
- - '#####'
  - 登录 Twitter
- - '#####'
  - 登出 Twitter
- - '#####'
  - 内部原理：webViewDidFinishLoad
- - '###'
  - 更多内容
- - '#'
  - 让您的应用程序为社交消息做好准备
- - '##'
  - 介绍 Facebook Graph API
- - '###'
  - 来自朋友的一点帮助
- - '###'
  - 分页图谱响应
- - '####'
  - 内部机制：`FBRequest` 类
- - '#####'
  - 关于错误处理的通用说明
- - '###'
  - Twitter API 介绍
- - '####'
  - 时间线简介
- - '#####'
  - 总觉得有人在关注我
- - '#'
  - 排版后内容
- - '##'
  - 内部机制：MGTwitter HTTP 连接与 XML 解析
- - '##'
  - 结论
- - '#'
  - 第 7 章
- - '#'
  - 访问人、地点、对象和关系
- - '##'
  - 更多关于 Facebook Graph API 的乐趣
- - '###'
  - Facebook 对话框
- - '##'
  - 底层机制：FBDialog 类
- - '##'
  - 发布到 Facebook 与授权
- - '#'
  - 从 Facebook 图谱获取更多好东西
- - '###'
  - 限制结果
- - '####'
  - 日期格式
- - '###'
  - 更多 Twitter API 的趣味用法
- - '#'
  - 推特，走起！
- - '###'
  - 幕后原理：Twitter URL
- - '###'
  - Twitter 开发者控制台
- - '###'
  - 结语
- - '##'
  - 第 8 章
- - '##'
  - POST 请求、数据建模与离线处理
- - '###'
  - 摆个姿势
- - '####'
  - 将图片保存到 iOS 模拟器的相册
- - '####'
  - 使用 UIImagePickerController
- - '####'
  - ImagePostController
- - '####'
  - Facebook 照片上传
- - '#'
  - Twitter 照片上传
- - '##'
  - GSTwitPicEngine
- - '##'
  - ASIHTTPRequest
- - '##'
  - SBJSON
- - '##'
  - OARequestHeader
- - '###'
  - 发布照片
- - '###'
  - 离线模式与后台处理
- - '####'
  - 使用 `TwitterDataStore` 进行数据建模
- - '###'
  - 从模型更新视图
- - '#'
  - 核心数据推文获取与删除
- - '##'
  - 结论
- - '#'
  - 第 9 章
- - '#'
  - 使用位置感知与流式数据
- - '##'
  - 此地，彼地，无处不在
- - '####'
  - 位置隐私、披露与选择退出
- - '####'
  - Facebook Places
- - '####'
  - 为推文添加位置信息
- - '####'
  - 高耗电量
- - '####'
  - '`CoreLocation`'
- - '###'
  - 使用 `CLLocationManager`
- - '###'
  - 在 iOS 模拟器中生成位置
- - '####'
  - iSimulate
- - '#'
  - futuretap 的 `FTLocationSimulator`
- - '##'
  - MapKit
- - '##'
  - Facebook 地点（搜索）、签到（获取与发布）以及附近好友
- - '####'
  - 带定位发推
- - '##'
  - 总结
- - '#'
  - 第 10 章
- - '#'
  - 使用开源工具及其他好用资源
- - '##'
  - 越短越好
- - '###'
  - 在 iOS 中使用 URL 缩短服务
- - '#'
  - ShareKit：有时“快速且粗糙”反而奏效
- - '##'
  - 开始使用 ShareKit
- - '###'
  - 最新 Twitter 潮流趋势
- - '###'
  - 热门话题
- - '###'
  - 地理位置标识符 (WOEID)
- - '###'
  - 再谈离线存储：SQLite
- - '####'
  - 在不用 Core Data 的情况下重写 OfflineTwitter
- - '#'
  - Objective-C 代码示例
- - '##'
  - 测试还是不测试，这是个问题
- - '#'
  - 为社交 iOS 应用添加单元测试
- - '###'
  - 结论
- - '##'
  - 第 11 章
- - '##'
  - 你可以构建（以及不能构建）的应用
- - '###'
  - Twitter：禁止客户端应用
- - '####'
  - Twitter 服务条款详解
- - '#####'
  - 基本规则
- - '######'
  - 使用 API
- - '#'
  - 你的应用能做什么
- - '##'
  - 管理现有推特客户端的规则
- - '##'
  - 推特对可用性的定义
- - '##'
  - 登录与身份
- - '##'
  - 正确显示内容
- - '##'
  - 通过应用盈利
- - '##'
  - 推特广告
- - '##'
  - 推特内容周边广告
- - '###'
  - 新的速率限制与白名单的终结
- - '###'
  - REST API 速率限制
- - '###'
  - Facebook：注意你的行为
- - '####'
  - 平台政策要点
- - '####'
  - 创造出色的用户体验
- - '####'
  - 值得信赖
- - '#####'
  - 速率限制
- - '#####'
  - 关于你的隐私政策
- - '#####'
  - 其他事项
- - '###'
  - 关于内容的规则
- - '###'
  - 关于 Facebook 应用工作方式的其他奇怪规则
- - '###'
  - 原则的实际应用
- - '####'
  - 照片
- - '####'
  - 点赞按钮
- - '####'
  - 广告
- - '####'
  - 使用社交动态流
- - '####'
  - 按钮文本
- - '###'
  - 应用展示
- - '####'
  - Twitter 应用
- - '###'
  - Remember The Milk
- - '####'
  - 添加任务
- - '####'
  - 向其他 Twitter 用户发送任务
- - '####'
  - 更新任务
- - '###'
  - Evernote
- - '####'
  - 短信笔记
- - '####'
  - 添加 TwitPics
- - '###'
  - Waze
- - '###'
  - Facebook Apps
- - '###'
  - Fone
- - '###'
  - Flipboard
- - '###'
  - 总结
- - '##'
  - 第 12 章
- - '##'
  - 社交类 iOS 应用的 UI 设计与体验指南
- - '###'
  - Facebook 与 Twitter 的 UI 基础
- - '####'
  - 注重细节：从图标开始
- - '###'
  - 展示各类反馈
- - '###'
  - 触摸目标与文本
- - '###'
  - 原型设计与测试
- - '###'
  - 用户希望从你的应用中获得什么
- - '####'
  - 内容
- - '####'
  - 逻辑路径
- - '####'
  - 清晰的设置
- - '####'
  - 品牌标识
- - '####'
  - 简洁
- - '#####'
  - 许可协议
- - '#####'
  - 合适的 iPad 设计
- - '####'
  - 让使用变得轻松直观
- - '###'
  - 结论
- - '##'
  - 第 13 章
- - '##'
  - 推特 UI 设计
- - '###'
  - 易用性优先级
- - '####'
  - 推文的结构
- - '#'
  - 建议组件
- - '##'
  - （不）使用 Twitter 的颜色
- - '###'
  - 创建主题元素
- - '##'
  - 使用 Twitter 商标
- - '#'
  - App Store 中的广告宣传
- - '#'
  - 我们并不了解你
- - '##'
  - Twitter 的导航范式
- - '###'
  - Twitter 徽标与图标
- - '###'
  - 启动画面
- - '###'
  - 视觉素材（即例外情况）
- - '###'
  - 项目命名指南
- - '###'
  - 离线展示指南
- - '###'
  - 通知处理
- - '####'
  - 来自网页应用的设计技巧
- - '###'
  - 结论
- - '##'
  - 第 14 章：Facebook 用户界面设计
- - '###'
  - 可用性优先事项
- - '####'
  - 创建你自己的界面
- - '##'
  - Facebook 加载项目
- - '###'
  - 主题与图标
- - '####'
  - 第三方资源
- - '###'
  - 创建主题元素
- - '####'
  - Hootsuite
- - '####'
  - Taptu
- - '###'
  - Facebook 艺术规则
- - '###'
  - 按钮文本
- - '###'
  - Facebook 导航
- - '###'
  - 显示进度
- - '####'
  - 核心 Three20 组件
- - '####'
  - Web 应用的设计技巧
- - '#####'
  - 标签式方法
- - '###'
  - 结论
- - '##'
  - 索引
- - '###'
  - 符号与数字
- - '###'
  - A
- - '###'
  - B
- - '###'
  - C
- - '###'
  - D
- - '###'
  - E
- - '###'
  - F
- - '####'
  - Facebook
- - '###'
  - G
- - '###'
  - H
- - '###'
  - I
- - '###'
  - J, K
- - '###'
  - L
- - '####'
  - 标签
- - '####'
  - 纬度参数
- - '####'
  - LED 闪光灯，iOS 4，8
- - '####'
  - letsbetrends.com
- - '####'
  - 字母文本字段
- - '####'
  - libxml XML
- - '####'
  - 许可协议
- - '####'
  - 点赞按钮
- - '####'
  - 点赞（Facebook）
- - '####'
  - 限制参数
- - '####'
  - 链接键值，Facebook 对话框，83
- - '####'
  - 加载
- - '####'
  - '`loadView` 方法，`MapViewController`，158'
- - '####'
  - 本地通知，iOS 4，6
- - '####'
  - 位置历史记录，Twitter
- - '####'
  - （设备的）位置
- - '####'
  - 位置参数
- - '####'
  - 位置权限提示，iOS，137
- - '####'
  - '`location` 属性，149、152'
- - '####'
  - 位置部分，Twitter，146、147
- - '####'
  - 定位服务设置，iOS，138
- - '####'
  - 定位服务，iOS，136、137、139
- - '####'
  - 基于位置的应用，iOS 4，7
- - '####'
  - '`LocationController` 类，148–149'
- - '####'
  - '`LocationController.h` 文件，148'
- - '####'
  - '`LocationManager.m` 文件，149'
- - '####'
  - '`locationManager:` 方法'
- - '####'
  - '`locationServicesEnabled` 属性，149'
- - '####'
  - 登录，Facebook，49–51
- - '####'
  - 登录，Twitter，58–61
- - '####'
  - 退出登录，Facebook，18、51–53
- - '####'
  - 退出登录，Twitter，62
- - '####'
  - 徽标
- - '####'
  - 经度参数
- - '####'
  - '`longUrl` 参数'
- - '###'
  - M
- - '###'
  - N
- - '###'
  - O
- - '####'
  - Objective-C
- - '####'
  - Objective-C 封装类
- - '####'
  - OCMock
- - '####'
  - 离线显示指南
- - '####'
  - 离线存储，118–133
- - '####'
  - '`OfflineTwitterTest`目标'
- - '####'
  - '`offset`参数'
- - '####'
  - 开放认证，37
- - '####'
  - '`openDatabase`方法'
- - '####'
  - '`openURL`方法，48'
- - '####'
  - 排序条件，`Tweets`，252
- - '####'
  - 覆盖层，地图，8
- - '###'
  - P
- - '###'
  - Q
- - '###'
  - R
- - '####'
  - 阅读器应用（Reader Apps）
- - '####'
  - '`Received:forRequest` 方法'
- - '####'
  - 区域监控（Region Monitoring）
- - '####'
  - '`registerRegion` 方法'
- - '####'
  - 请求方法，`MGTwitterEngine`：72
- - '####'
  - '`request:` 方法'
- - '####'
  - '`requestFailed:withError` 方法'
- - '####'
  - '`requestSucceeded` 方法'
- - '####'
  - '`requestWithGraph` 方法，Facebook：69'
- - '####'
  - '`requestWithGraphPath` 方法'
- - '####'
  - 响应，Facebook
- - '####'
  - 响应，Twitter
- - '####'
  - 反向地理编码（Reverse Geocoding）
- - '####'
  - '`RTM` (Remember The Milk)：224–226'
- - '####'
  - API 使用规则
- - '###'
  - S
- - '###'
  - T
- - '####'
  - 标签页
- - '####'
  - 标记照片
- - '####'
  - 目标
- - '####'
  - 任务，Twitter
- - '####'
  - '`tearDown` 方法'
- - '####'
  - 终端应用，Mac OS X
- - '####'
  - 测试类
- - '####'
  - 测试
- - '####'
  - 短信
- - '####'
  - 主题，Facebook 界面设计，273–275
- - '####'
  - 他人分享内容板块，Facebook，143
- - '####'
  - 时间线，Twitter，72, 254
- - '####'
  - '`TimelineViewController` 类，128, 129'
- - '####'
  - 时间戳
- - '####'
  - '`TinyURL.com` URL 缩短服务，180'
- - '####'
  - 待办事项列表
- - '####'
  - 令牌，OAuth
- - '####'
  - 触摸目标
- - '####'
  - 商标
- - '####'
  - 热门话题，Twitter，190
- - '####'
  - 趋势，Twitter (参见 Twitter 趋势)
- - '####'
  - 推文框/按钮
- - '####'
  - 推文类
- - '####'
  - 推文实体
- - '####'
  - 推文位置部分，146，147
- - '####'
  - Tweet.h 文件，124
- - '####'
  - Tweet.m 文件，124
- - '####'
  - Tweetbot
- - '####'
  - Tweetie，255–257
- - '####'
  - 推文
- - '####'
  - tweets 方法
- - '####'
  - Tweets 表
- - '####'
  - tweetsDidSynchronize 方法，130
- - '####'
  - twitgoo
- - '####'
  - TwitPic
- - '####'
  - TwitPics
- - '####'
  - Twitter API
- - '####'
  - Twitter
- - '####'
  - 推文解剖
- - '####'
  - '`TwitterDataStore` 类'
- - '####'
  - '`TwitterDataStore_SQLite` 类'
- - '####'
  - '`twitterFollowersRequestDidComplete` 方法，74'
- - '####'
  - Twitterific
- - '####'
  - '`twitterOAuthConnectionFailedWithData` 方法，59'
- - '####'
  - '`twitterTimelineRequestDidComplete` 方法，129'
- - '####'
  - Twurl
- - '###'
  - U
- - '###'
  - V
- - '###'
  - W
- - '###'
  - X
- - '###'
  - Y
- - '###'
  - Z
