name: Pro Android media
name_cn: Android 媒体高级指南
slug: pro-android-media
toc:
- - '#'
  - Pro Android 媒体开发
- - '#'
  - 内容速览
- - '#'
  - 前言
- - '#'
  - 第 1 章：Android 成像简介
- - '##'
  - 使用内置相机应用程序捕获图像
- - '##'
  - 从 Camera 应用返回数据
- - '##'
  - 拍摄更大尺寸的图像
- - '##'
  - 显示大图
- - '##'
  - 图像存储与元数据
- - '###'
  - 获取图像的 URI
- - '###'
  - 预填充关联元数据
- - '###'
  - 检索已保存的图像
- - '###'
  - 后续添加元数据
- - '###'
  - 更新我们的 `CameraActivity`，使用 `MediaStore` 进行图像存储并关联元数据
- - '##'
  - 使用 MediaStore 检索图像
- - '##'
  - 创建图像查看应用
- - '##'
  - 内部元数据
- - '##'
  - 本章小结
- - '#'
  - 第 2 章：构建自定义相机应用
- - '##'
  - 使用 Camera 类
- - '###'
  - 相机权限
- - '###'
  - 预览表面
- - '###'
  - 实现相机
- - '###'
  - 设置相机参数
- - '##'
  - 更改相机预览大小
- - '##'
  - 拍摄并保存图像
- - '##'
  - 其他相机回调方法
- - '##'
  - 整合所有内容
- - '##'
  - 扩展自定义相机应用
- - '###'
  - 构建基于定时器的相机应用
- - '###'
  - 构建延时摄影应用
- - '##'
  - 总结
- - '#'
  - 第 3 章：图像编辑与处理
- - '##'
  - 使用内置图库应用选择图像
- - '##'
  - 将位图绘制到位图上
- - '##'
  - 基本图像缩放与旋转
- - '###'
  - 矩阵登场
- - '##'
  - 矩阵方法
- - '###'
  - 旋转
- - '###'
  - 缩放
- - '###'
  - 平移
- - '###'
  - 前置与后置
- - '###'
  - 镜像
- - '###'
  - 上下翻转
- - '##'
  - 调整饱和度
- - '##'
  - 图像合成
- - '##'
  - 本章小结
- - '#'
  - 第 4 章：图形与触摸事件
- - '##'
  - Canvas 绘图
- - '###'
  - Bitmap 创建
- - '###'
  - Bitmap 配置
- - '###'
  - 创建 Canvas
- - '###'
  - 使用 Paint
- - '####'
  - 颜色
- - '####'
  - 样式
- - '####'
  - 描边宽度
- - '###'
  - 绘制形状
- - '####'
  - 点
- - '####'
  - 直线
- - '####'
  - 矩形
- - '####'
  - 椭圆
- - '####'
  - 圆形
- - '####'
  - 路径
- - '###'
  - 绘制文本
- - '###'
  - 内置字体
- - '###'
  - 字体样式
- - '#'
  - 第 5 章：Android 音频简介
- - '##'
  - 音频播放
- - '###'
  - 支持的音频格式
- - '##'
  - 通过 Intent 使用内置音频播放器
- - '##'
  - 创建自定义音频播放应用程序
- - '###'
  - 启动媒体播放器
- - '####'
  - 本地资源
- - '###'
  - 控制播放
- - '##'
  - 用于音频的 MediaStore
- - '###'
  - 从 MediaStore 访问音频
- - '###'
  - 在 MediaStore 中浏览音频
- - '####'
  - 专辑浏览应用示例
- - '#'
  - 第 6 章：后台与网络音频
- - '##'
  - 后台音频播放
- - '##'
  - 服务
- - '###'
  - 本地服务与远程服务
- - '###'
  - 简单本地服务
- - '###'
  - '`onStartCommand` 与 `onStart` 的区别'
- - '##'
  - 本地服务加 MediaPlayer
- - '##'
  - 在 Service 中控制 MediaPlayer
- - '##'
  - 网络音频
- - '###'
  - HTTP 音频播放
- - '###'
  - 通过 HTTP 流式传输音频
- - '#'
  - 第 7 章：音频采集
- - '##'
  - 使用意图进行音频捕获
- - '##'
  - 自定义音频录制
- - '###'
  - MediaRecorder 音频源
- - '###'
  - MediaRecorder 输出格式
- - '###'
  - MediaRecorder 音频编码器
- - '###'
  - MediaRecorder 输出与录制
- - '###'
  - MediaRecorder 状态机
- - '###'
  - MediaRecorder 示例
- - '###'
  - MediaRecorder 的其他方法
- - '##'
  - 将音频插入 MediaStore
- - '##'
  - 使用 AudioRecord 进行原始音频录制
- - '##'
  - 使用 AudioTrack 进行原始音频回放
- - '##'
  - 原始音频采集与回放示例
- - '##'
  - 总结
- - '#'
  - 第 8 章：音频合成与分析
- - '##'
  - 数字音频合成
- - '##'
  - 播放合成声音
- - '##'
  - 生成样本
- - '##'
  - 音频分析
- - '###'
  - 捕获声音以进行分析
- - '###'
  - 可视化频率
- - '#'
  - 第 9 章：视频简介
- - '##'
  - 使用 MediaController 添加控制功能
- - '##'
  - 使用 MediaPlayer 播放
- - '###'
  - MediaPlayer 状态
- - '###'
  - MediaPlayer 示例
- - '##'
  - 带 MediaController 的 MediaPlayer
- - '##'
  - 总结
- - '#'
  - 第 10 章：高级视频
- - '##'
  - 通过 MediaStore 检索视频
- - '##'
  - 从 MediaStore 获取视频缩略图
- - '##'
  - 完整的 MediaStore 视频示例
- - '##'
  - 网络视频
- - '###'
  - 支持的网络视频类型
- - '####'
  - HTTP
- - '####'
  - RTSP
- - '##'
  - 网络视频播放
- - '###'
  - VideoView 网络视频播放器
- - '###'
  - MediaPlayer 网络视频播放器
- - '##'
  - 总结
- - '#'
  - 第 11 章：视频采集
- - '##'
  - 使用 Intent 录制视频
- - '##'
  - 添加视频元数据
- - '##'
  - 自定义视频捕捉
- - '###'
  - 用于视频的 MediaRecorder
- - '####'
  - 音频和视频源
- - '###'
  - 输出格式
- - '###'
  - 音频与视频编码器
- - '###'
  - 音视频比特率
- - '###'
  - 音频采样率
- - '###'
  - 音频声道数
- - '###'
  - 视频帧率
- - '###'
  - 视频尺寸
- - '###'
  - 最大文件大小
- - '###'
  - 最大时长
- - '###'
  - 配置文件
- - '###'
  - 输出文件
- - '###'
  - 预览表面
- - '###'
  - 准备录制
- - '###'
  - 开始录制
- - '###'
  - 停止录制
- - '###'
  - 释放资源
- - '###'
  - 状态机
- - '###'
  - 权限
- - '##'
  - 完整的自定义视频捕捉示例
- - '##'
  - 本章小结
- - '#'
  - 第 12 章：使用网络服务的媒体消费与发布
- - '##'
  - 网络服务
- - '###'
  - HTTP 请求
- - '##'
  - JSON
- - '###'
  - JSON 解析示例
- - '###'
  - 使用 JSON 获取 Flickr 图片
- - '##'
  - 位置服务
- - '###'
  - 使用 JSON 和位置拉取 Flickr 图片
- - '##'
  - REST
- - '###'
  - 在 XML 中表示数据
- - '###'
  - SAX 解析
- - '###'
  - Android 的解析需求
- - '###'
  - HTTP 文件上传
- - '###'
  - 发起 HTTP 请求
- - '##'
  - 向 Blip.TV 上传视频
- - '###'
  - Blip.TV 上传代码解析
- - '##'
  - 总结
- - '#'
  - 索引
