name: Beginning IPhone Development with Swift 5
name_cn: Swift 5 iPhone 开发入门指南
slug: beginning-iphone-development-with-swift-5
toc:
- - '#'
  - 关于作者和技术审稿人
- - '##'
  - 关于作者
- - '##'
  - 关于技术审稿人
- - '#'
  - 1. 理解 iOS 编程
- - '##'
  - 了解 Xcode
- - '##'
  - 总结
- - '#'
  - 2. 设计用户界面
- - '##'
  - 了解视图与类文件
- - '##'
  - 适配不同屏幕尺寸
- - '##'
  - 预览用户界面
- - '##'
  - 摘要
- - '#'
  - 3. 编写 Swift 代码
- - '##'
  - 创建 IBOutlet 变量
- - '###'
  - 注意
- - '##'
  - 创建 IBAction 方法
- - '##'
  - 使用 Apple 框架
- - '##'
  - 使用 Xcode 编辑器
- - '###'
  - 获取 Swift 命令的帮助
- - '###'
  - 折叠和展开函数
- - '##'
  - 摘要
- - '#'
  - 4. 使用 Xcode
- - '##'
  - 更改 Xcode 的外观
- - '###'
  - 导航器面板
- - '###'
  - 工具栏
- - '###'
  - 标签栏（Tab Bar）
- - '###'
  - 注意
- - '##'
  - 标记 Swift 代码（Marking Swift Code）
- - '##'
  - 重命名和删除 IBOutlet 变量
- - '##'
  - 总结
- - '#'
  - 5. 使用控制器
- - '##'
  - 理解控制器
- - '##'
  - 使用多个控制器
- - '##'
  - 在控制器之间切换
- - '###'
  - 嵌入导航控制器
- - '###'
  - 使用导航控制器
- - '##'
  - 总结
- - '#'
  - 6. 添加用户界面对象
- - '##'
  - 更改对象的大小和位置
- - '###'
  - 更改对象的属性
- - '###'
  - 了解安全区域
- - '##'
  - 定义约束
- - '###'
  - 自动定义约束
- - '###'
  - 查看和删除约束
- - '###'
  - 手动添加约束
- - '##'
  - 更改约束的固定值
- - '##'
  - 使用栈视图
- - '##'
  - 总结
- - '#'
  - 7. 使用常见的用户界面对象
- - '##'
  - 使用标签
- - '###'
  - 注意
- - '##'
  - 使用文本字段
- - '###'
  - 定义不同的键盘
- - '###'
  - 定义文本字段的内容
- - '###'
  - 修改文本字段的外观
- - '##'
  - 使用按钮
- - '##'
  - 摘要
- - '#'
  - 8. 步进器、滑块、进度视图和活动指示器视图
- - '##'
  - 使用步进器
- - '##'
  - 使用滑块
- - '###'
  - 使用 Swift 代码修改滑块
- - '##'
  - 使用进度视图和活动指示器视图
- - '###'
  - 使用进度视图
- - '##'
  - 摘要
- - '#'
  - 9. 图像视图和文本视图
- - '##'
  - 使用图像视图
- - '###'
  - 让图像视图实现交互
- - '##'
  - 使用文本视图
- - '###'
  - 注意
- - '###'
  - 更改文本视图中的文字外观
- - '###'
  - 在文本视图中创建可点击文字
- - '###'
  - 使用文本视图显示虚拟键盘
- - '##'
  - 总结
- - '#'
  - 10. 按钮、开关和分段控件
- - '##'
  - 理解事件
- - '##'
  - 使用按钮
- - '##'
  - 使用开关
- - '##'
  - 使用分段控件
- - '##'
  - 将多个对象连接到同一个 `IBAction` 方法
- - '###'
  - 注意
- - '##'
  - 总结
- - '#'
  - 11. 触摸手势
- - '##'
  - 检测轻点手势
- - '##'
  - 检测捏合手势
- - '##'
  - 检测旋转手势
- - '###'
  - 检测平移手势
- - '##'
  - 检测屏幕边缘滑动手势
- - '##'
  - 检测轻扫手势
- - '##'
  - 检测长按手势
- - '##'
  - 总结
- - '#'
  - 12. 使用警告控制器和选择器
- - '##'
  - 使用警告控制器
- - '###'
  - 显示并响应多个按钮
- - '###'
  - 在警报控制器上显示文本字段
- - '####'
  - 备注
- - '##'
  - 使用日期选择器
- - '##'
  - 创建自定义选择器
- - '###'
  - 显示多组件选择器视图
- - '##'
  - 本章小结
- - '#'
  - 13. 约束和堆栈视图
- - '##'
  - 理解约束
- - '###'
  - 注意
- - '##'
  - 使用堆栈视图
- - '###'
  - 注意
- - '##'
  - 小结
- - '#'
  - 14. 使用表视图
- - '##'
  - 创建简单的表格视图
- - '##'
  - 在表格视图中选择项目
- - '##'
  - 创建分组表格
- - '###'
  - 显示索引
- - '####'
  - 注意
- - '##'
  - 使用表格视图控制器
- - '##'
  - 总结
- - '#'
  - 15. 自定义表格视图单元格
- - '##'
  - 在 Swift 中自定义表格视图单元格
- - '###'
  - 注意
- - '##'
  - 设计自定义表格视图单元格
- - '##'
  - 滑动添加与删除行
- - '##'
  - 总结
- - '#'
  - 16. 使用集合视图
- - '##'
  - 创建集合视图
- - '##'
  - 在集合视图中显示数据
- - '###'
  - 在集合视图中显示分区标题
- - '##'
  - 总结
- - '#'
  - 17. 使用导航控制器
- - '##'
  - 使用导航控制器
- - '###'
  - 弹出菜单助你定义转场
- - '##'
  - 向其他视图传递数据
- - '##'
  - 在导航控制器中显示多个视图
- - '##'
  - 自定义导航栏
- - '###'
  - 修改提示文本与标题文本
- - '###'
  - 修改返回按钮
- - '###'
  - 修改导航栏的颜色
- - '###'
  - 向导航栏添加按钮
- - '##'
  - 摘要
- - '#'
  - 18. 使用标签栏和工具栏
- - '###'
  - 注
- - '##'
  - 在标签栏控制器中切换视图控制器
- - '##'
  - 自定义标签栏图标
- - '###'
  - 注意
- - '##'
  - 从标签栏控制器中删除视图控制器
- - '###'
  - 注意
- - '##'
  - 创建工具栏
- - '###'
  - 添加和删除工具栏按钮
- - '####'
  - 注意
- - '##'
  - 总结
- - '#'
  - 19. 使用页面视图控制器
- - '##'
  - 添加和自定义页面控制器
- - '##'
  - 添加视图控制器
- - '##'
  - 让视图控制器在页面控制器中显示
- - '##'
  - 总结
- - '#'
  - 20. 使用分栏视图控制器
- - '##'
  - 理解分视图控制器的结构
- - '##'
  - 在 Storyboard 中添加分视图控制器
- - '###'
  - 创建类文件
- - '###'
  - 修改 AppDelegate.swift 文件
- - '###'
  - 修改 `DetailViewController.swift` 文件
- - '###'
  - 修改 `MasterTableViewController.swift` 文件
- - '##'
  - 摘要
- - '#'
  - 索引
- - '###'
  - A
- - '###'
  - B
- - '###'
  - C
- - '###'
  - D
- - '###'
  - E, F
- - '###'
  - G
- - '###'
  - H
- - '###'
  - I, J
- - '###'
  - K
- - '###'
  - L
- - '###'
  - M
- - '###'
  - N
- - '###'
  - O
- - '###'
  - P, Q
- - '###'
  - R
- - '###'
  - S
- - '###'
  - T
- - '###'
  - U
- - '###'
  - V, W
- - '###'
  - X, Y, Z
