name: Build Location Apps on IOS with Swift
name_cn: iOS 版位置应用构建指南
slug: build-location-apps-on-ios-with-swift
toc:
- - '#'
  - 第 1 章 创建你的第一个 MapKit 应用
- - '##'
  - 开始
- - '##'
  - 添加地图
- - '###'
  - 在地图上添加大头针
- - '##'
  - 总结
- - '#'
  - 第 2 章 获取用户位置
- - '##'
  - 隐私与位置权限
- - '###'
  - Info.plist 中的位置权限设置
- - '##'
  - 向最终用户请求位置权限
- - '###'
  - 请求位置更新
- - '###'
  - 在地图上显示用户的位置
- - '##'
  - 小结
- - '#'
  - 第 3 章 在 MapKit 地图上显示标注
- - '##'
  - 理解 MapKit 和标注
- - '##'
  - 使用自定义标注类
- - '##'
  - 显示自定义标注
- - '##'
  - 自定义标注的图钉
- - '##'
  - 处理用户位置
- - '##'
  - 复用标注视图
- - '##'
  - 出队和创建标注视图
- - '##'
  - 在标注视图上设置图像
- - '##'
  - 为标注使用标注弹窗
- - '##'
  - 总结
- - '#'
  - 第 4 章 搜索兴趣点
- - '##'
  - 本地搜索入门
- - '##'
  - 探索响应中的地图项
- - '##'
  - 在地图上显示搜索结果
- - '##'
  - 为结果创建标注
- - '##'
  - 使用兴趣点类别进行过滤
- - '#'
  - 第 5 章 使用 MapKit 获取路线指引
- - '##'
  - 理解 Directions API
- - '##'
  - 开始使用路线功能
- - '##'
  - 理解路线步骤
- - '##'
  - 构建逐步方向指示
- - '###'
  - 显示当前步骤
- - '###'
  - 在实例变量中保存路线
- - '###'
  - “上一步”和“下一步”按钮的操作
- - '##'
  - 后续步骤
- - '##'
  - 本章小结
- - '#'
  - 第 6 章 在 CoreLocation 中使用地理围栏
- - '##'
  - 区域监控概念
- - '##'
  - 设置基于位置的应用
- - '##'
  - 区域监控入门
- - '##'
  - 监听地理围栏触发事件
- - '##'
  - 在应用内部显示本地通知
- - '###'
  - 设置通知中心
- - '###'
  - 为特定区域显示本地通知
- - '##'
  - 在应用程序委托中监控区域变化
- - '##'
  - 从应用程序中移除地理围栏
- - '#'
  - 第 7 章 使用 Google Maps SDK 显示地图
- - '###'
  - 使用 Google 地图平台
- - '##'
  - 安装 iOS 版 Google Maps SDK 库
- - '##'
  - 设置 Google Maps API 密钥
- - '##'
  - 在应用程序中集成 API 密钥
- - '##'
  - 使用地图视图显示 Google 地图
- - '##'
  - 允许 Google Maps 和 Chrome 的 URL 方案
- - '##'
  - 更改地图视图的显示选项
- - '##'
  - 探索 Google 地图视图
- - '##'
  - 更改地图瓦片类型
- - '##'
  - 显示地图标记
- - '###'
  - 更改标记图标
- - '###'
  - 响应标记事件
- - '###'
  - 用户数据和标记
- - '##'
  - 在地图上添加形状
- - '###'
  - 圆形
- - '###'
  - 折线与路径
- - '###'
  - 多边形
- - '###'
  - 移除标记和形状
- - '##'
  - 总结
- - '#'
  - 第 9 章 将 Google Directions API 与导航功能结合使用
- - '##'
  - 设置 Google Directions API
- - '##'
  - 限制 API 密钥
- - '##'
  - 使用 Google Directions API
- - '###'
  - 创建 URL
- - '###'
  - 使用 URLSession 调用 Directions API
- - '###'
  - 处理导航响应
- - '###'
  - 将路线显示为折线
- - '###'
  - 更新地图边界框
- - '###'
  - 后续步骤：显示每个路段和每个步骤
- - '#'
  - 第 10 章 在 iOS 应用中使用 Google Places
- - '##'
  - 构建带地图的地点查找器
- - '##'
  - 创建项目
- - '###'
  - 获取 Google Places API 密钥
- - '###'
  - 设置 CocoaPods
- - '###'
  - 为 Google Places 和 Google Maps 提供 API 密钥
- - '###'
  - 创建用户界面
- - '##'
  - 了解自动完成搜索
- - '###'
  - 创建自动完成视图控制器
- - '###'
  - 为搜索设置地理边界
- - '###'
  - 请求数据字段子集
- - '###'
  - 按类型筛选结果
- - '###'
  - 显示视图控制器
- - '###'
  - 为自动完成实现委托
- - '##'
  - 在地图上显示地点
- - '##'
  - Places SDK 中的其他功能
- - '#'
  - 第 11 章 开始使用 Mapbox SDK
- - '##'
  - 获取 Mapbox 访问令牌
- - '##'
  - 使用 Mapbox SDK 启动新项目
- - '##'
  - 显示地图视图
- - '##'
  - 自定义地图视图的外观
- - '##'
  - 在地图上显示点标注
- - '##'
  - 使用 Mapbox 自定义地图样式
- - '###'
  - 准备地图样式
- - '###'
  - 更改地图视图上的默认样式
- - '###'
  - 使用 Mapbox Studio 创建地图样式
- - '###'
  - 在应用中显示新地图样式
- - '###'
  - 在 Mapbox Studio 中使用数据集
- - '###'
  - 地震地图
- - '###'
  - 下载地震数据
- - '###'
  - 在 Mapbox Studio 中创建数据集
- - '###'
  - 创建瓦片集
- - '###'
  - 将瓦片集添加到样式
- - '###'
  - 使用 Mapbox Studio 为要素设置样式
- - '###'
  - 在应用中显示数据集
- - '###'
  - 检测对要素的轻点
- - '###'
  - 结论
- - '#'
  - 使用 Mapbox 的逐向导航
- - '##'
  - 设置您的应用项目
- - '###'
  - 设置 CocoaPods
- - '###'
  - 向 Info.plist 添加条目
- - '###'
  - 添加必需的功能
- - '##'
  - 使用 Mapbox Directions API
- - '###'
  - 显示导航用户界面
- - '###'
  - 使用 Mapbox 模拟导航
- - '###'
  - 自定义导航体验
- - '###'
  - 结论
- - '#'
  - 第 15 章 使用 Mapbox 离线地图
- - '##'
  - 设置你的应用程序项目
- - '##'
  - 了解离线地图下载
- - '###'
  - 估算使用的瓦片数量
- - '##'
  - 下载离线地图包
- - '###'
  - 监控离线地图包下载
- - '###'
  - 使用离线地图磁贴的注意事项
- - '#'
  - 索引
