name: Pro design patterns in Swift
name_cn: Swift 设计模式高级指南
slug: pro-design-patterns-in-swift
toc:
- - '#'
  - Swift 专业设计模式
- - '##'
  - 关于作者
- - '##'
  - 关于技术审校
- - '#'
  - 第一部分
- - '#'
  - 1. 理解设计模式
- - '##'
  - 将设计模式置于具体情境中
- - '###'
  - 引入设计模式
- - '###'
  - 理解设计模式的结构
- - '##'
  - 量化设计模式的价值
- - '##'
  - 在问题发生后使用设计模式
- - '##'
  - 理解设计模式的局限性
- - '##'
  - 关于本书
- - '###'
  - 你需要具备哪些知识？
- - '###'
  - 你需要哪些软件？
- - '####'
  - 本书的结构是怎样的？
- - '####'
  - 从哪里可以获得示例代码？
- - '##'
  - 总结
- - '#'
  - 2. 熟悉 Xcode
- - '##'
  - 使用 Xcode Playground
- - '###'
  - 创建 Playground
- - '###'
  - 显示变量的值历史
- - '###'
  - 关于编码风格的一点说明
- - '###'
  - 使用值时间线
- - '###'
  - 在 Playground 中显示 UI 组件
- - '##'
  - 使用 OS X 命令行工具项目
- - '###'
  - 创建命令行项目
- - '###'
  - 理解 Xcode 布局
- - '###'
  - 添加新的 Swift 文件
- - '##'
  - 本章小结
- - '#'
  - 3. 创建 SportsStore 应用
- - '##'
  - 创建无结构的 iOS 应用项目
- - '###'
  - 创建项目
- - '###'
  - 了解 Xcode 布局
- - '###'
  - 定义数据
- - '###'
  - 使用元组
- - '##'
  - 创建基本布局
- - '###'
  - 添加基本组件
- - '###'
  - 配置自动布局
- - '###'
  - 测试基本布局
- - '##'
  - 实现总量标签
- - '###'
  - 创建引用
- - '###'
  - 更新显示
- - '##'
  - 实现表格单元格
- - '###'
  - 定义自定义表格单元格与布局
- - '###'
  - 设置表格单元格布局约束
- - '###'
  - 创建表格单元格类与出口
- - '###'
  - 实现数据源协议
- - '###'
  - 注册数据源
- - '###'
  - 测试数据源
- - '##'
  - 处理编辑操作
- - '###'
  - 处理事件
- - '##'
  - 测试 SportsStore 应用
- - '##'
  - 总结
- - '#'
  - 第二部分
- - '#'
  - 4. 对象模板模式
- - '##'
  - 准备示例项目
- - '##'
  - 理解该模式解决的问题
- - '##'
  - 理解紧耦合为何会成为问题
- - '##'
  - 理解对象模板模式
- - '###'
  - 理解类、结构体、对象和实例
- - '##'
  - 实现对象模板模式
- - '##'
  - 理解该模式的优势
- - '###'
  - 解耦的好处
- - '###'
  - 封装的好处
- - '###'
  - 公开展示方式演进的益处
- - '###'
  - 理解该模式的陷阱
- - '###'
  - Cocoa 中对象模板模式的示例
- - '###'
  - 将模式应用于 SportsStore 应用
- - '####'
  - 准备示例应用
- - '###'
  - 创建 Product 类
- - '###'
  - 理解 Swift 访问控制
- - '###'
  - 应用 Product 类
- - '##'
  - 迁移至使用 `Product` 类
- - '##'
  - 确保视图与模型分离
- - '##'
  - 扩展摘要显示
- - '##'
  - 本章小结
- - '#'
  - 5. 原型模式
- - '##'
  - 理解该模式解决的问题
- - '###'
  - 承担高昂的初始化成本
- - '###'
  - 创建模板依赖关系
- - '##'
  - 理解原型模式
- - '##'
  - 实现原型模式
- - '###'
  - 清单 5-3. `ValueTypes.playground`文件的内容
- - '###'
  - 克隆引用类型
- - '###'
  - 清单 5-4. `ReferenceTypes.playground`文件的内容
- - '###'
  - 实现`NSCopying`协议
- - '###'
  - 清单 5-5. 在`ReferenceTypes.playground`文件中实现`NSCopying`协议
- - '###'
  - 理解浅拷贝与深拷贝
- - '####'
  - 实现深拷贝
- - '####'
  - 选择浅拷贝还是深拷贝
- - '###'
  - 拷贝数组
- - '##'
  - 理解原型模式的优点
- - '###'
  - 避免昂贵的初始化操作
- - '###'
  - 分离对象的创建与使用
- - '##'
  - （并非真正）解决问题
- - '##'
  - 揭示根本问题
- - '##'
  - 应用原型模式
- - '##'
  - 理解原型模式的陷阱
- - '###'
  - 理解深拷贝与浅拷贝的陷阱
- - '###'
  - 理解“暴露原型陷阱”
- - '###'
  - 理解“非标准协议陷阱”
- - '##'
  - Cocoa 中原型模式的例子
- - '###'
  - 使用 Cocoa 数组
- - '####'
  - 对 Cocoa 数组进行浅拷贝
- - '###'
  - 创建 Cocoa 数组的深拷贝
- - '##'
  - 单层深拷贝与 `NSCoding` 协议
- - '##'
  - 使用 `NSCopying` 属性特性
- - '##'
  - 将模式应用于 SportsStore 应用
- - '###'
  - 准备示例应用
- - '###'
  - 在 Product 类中实现 NSCopying
- - '###'
  - 创建 Logger 类
- - '###'
  - 在视图控制器中记录更改
- - '###'
  - 测试更改
- - '##'
  - 总结
- - '#'
  - 6. 单例模式
- - '##'
  - 准备示例项目
- - '##'
  - 理解模式解决的问题
- - '##'
  - 理解共享资源封装问题
- - '##'
  - 理解单例模式
- - '##'
  - 实现单例模式
- - '###'
  - 快速单例实现
- - '###'
  - 创建传统的单例实现
- - '###'
  - 处理并发问题
- - '####'
  - 序列化访问
- - '##'
  - 理解 Grand Central Dispatch——第二部分
- - '##'
  - 理解单例模式的陷阱
- - '###'
  - 理解泄露陷阱
- - '###'
  - 理解共享代码文件陷阱
- - '###'
  - 理解并发陷阱
- - '####'
  - 未应用并发保护
- - '####'
  - 一致地应用并发保护
- - '####'
  - 错误的优化
- - '##'
  - Cocoa 中的单例模式示例
- - '##'
  - 将模式应用于 SportsStore 应用
- - '###'
  - 保护数据数组
- - '###'
  - 保护回调函数
- - '###'
  - 定义单例
- - '##'
  - 本章小结
- - '#'
  - 7. 对象池模式
- - '##'
  - 准备示例项目
- - '##'
  - 理解该模式解决的问题
- - '##'
  - 理解对象池模式
- - '##'
  - 实现对象池模式
- - '###'
  - 定义池类
- - '####'
  - 保护数据数组
- - '####'
  - 确保对象可被取出
- - '###'
  - 消费池类
- - '###'
  - 宽松的对象创建策略
- - '##'
  - 理解对象池模式的陷阱
- - '##'
  - Cocoa 中对象池模式的示例
- - '##'
  - 将模式应用于 SportsStore 应用
- - '###'
  - 准备示例应用
- - '###'
  - 创建（虚拟）服务器
- - '###'
  - 创建对象池
- - '###'
  - 应用对象池
- - '##'
  - 总结
- - '#'
  - 8. 对象池变体
- - '##'
  - 准备示例项目
- - '##'
  - 理解对象池模式变体
- - '###'
  - 理解对象创建策略
- - '###'
  - 理解对象复用策略
- - '####'
  - 应用协议
- - '####'
  - 测试该策略
- - '###'
  - 理解空池策略
- - '####'
  - 实现请求失败策略
- - '####'
  - 处理池资源耗尽
- - '####'
  - 创建弹性对象池
- - '##'
  - 理解分配策略
- - '###'
  - 清单 8-17 展示了一种最少使用策略。该策略会选择可用的对象中使用次数最少的那个。可能存在一些已被借出但使用次数更少的对象。将所有对象都考虑在内的策略被称为完美分配策略，但这种策略几乎没什么用，因为它意味着你需要阻塞一个请求，直到绝对最少使用的对象变得可用，而这可能在相当长一段时间内都不会发生。
- - '##'
  - 清单 8-17 在`Library.swift`文件中实现不同的分配策略
- - '##'
  - 理解模式变种的陷阱
- - '###'
  - 理解预期差距陷阱
- - '###'
  - 理解过度使用与使用不足陷阱
- - '##'
  - Cocoa 中模式变种的示例
- - '##'
  - 将模式变种应用于 SportsStore
- - '##'
  - 清单 8-18 在`NetworkPool.swift`文件中更改对象创建策略
- - '##'
  - 本章小结
- - '#'
  - 9. 工厂方法模式
- - '##'
  - 准备示例项目
- - '##'
  - 理解该模式要解决的问题
- - '##'
  - 理解工厂方法模式
- - '##'
  - 实现工厂方法模式
- - '##'
  - 定义全局工厂方法
- - '##'
  - 使用基类
- - '###'
  - 为深层类层次结构委派决策
- - '##'
  - 工厂方法模式的变体
- - '##'
  - 理解该模式的陷阱
- - '##'
  - Cocoa 中的工厂方法模式示例
- - '##'
  - 将模式应用于 SportsStore 应用程序
- - '###'
  - 准备示例应用
- - '###'
  - 实现工厂方法模式
- - '###'
  - 使用工厂方法模式
- - '##'
  - 本章小结
- - '#'
  - 10. 抽象工厂模式
- - '##'
  - 准备示例项目
- - '##'
  - 理解该模式解决的问题
- - '##'
  - 理解抽象工厂模式
- - '##'
  - 工厂方法与抽象工厂模式
- - '##'
  - 实现抽象工厂模式
- - '###'
  - 创建抽象工厂
- - '###'
  - 创建具体工厂
- - '###'
  - 完善抽象工厂
- - '###'
  - 使用抽象工厂模式
- - '##'
  - 抽象工厂模式的变体
- - '###'
  - 隐藏抽象工厂类
- - '###'
  - 对具体工厂应用单例模式
- - '###'
  - 对实现类应用原型模式
- - '###'
  - 准备示例应用程序
- - '###'
  - 应用原型模式
- - '##'
  - 理解该模式的陷阱
- - '##'
  - Cocoa 中该模式的示例
- - '##'
  - 将模式应用于 SportsStore 应用程序
- - '###'
  - 准备示例应用程序
- - '###'
  - 定义实现协议与类
- - '###'
  - 定义抽象工厂与具体工厂类
- - '###'
  - 使用工厂与实现类
- - '##'
  - 本章小结
- - '#'
  - 11. 建造者模式
- - '##'
  - 准备示例项目
- - '##'
  - 理解模式解决的问题
- - '###'
  - 理解伸缩初始化器反模式
- - '##'
  - 理解建造者模式
- - '##'
  - 实现建造者模式
- - '###'
  - 定义建造者类
- - '###'
  - 消费建造者
- - '###'
  - 理解模式的影响
- - '###'
  - 改变流程
- - '###'
  - 改变对象
- - '###'
  - 避免不一致的配置
- - '##'
  - 建造者模式的变体
- - '##'
  - 理解建造者模式的陷阱
- - '##'
  - Cocoa 中建造者模式的示例
- - '##'
  - 将模式应用于 SportsStore 应用程序
- - '###'
  - 准备示例应用程序
- - '###'
  - 定义构建器类
- - '###'
  - 使用构建器类
- - '##'
  - 本章小结
- - '#'
  - 第三部分：结构型模式
- - '##'
  - 12. 适配器模式
- - '###'
  - 准备示例项目
- - '####'
  - 创建数据源
- - '###'
  - 定义应用程序
- - '##'
  - 理解该模式解决的问题
- - '##'
  - 理解适配器模式
- - '##'
  - 实现适配器模式
- - '###'
  - 为什么不直接迁移数据？
- - '##'
  - 适配器模式的变体
- - '###'
  - 将适配器定义为包装类
- - '###'
  - 创建双向适配器
- - '##'
  - 理解适配器模式的陷阱
- - '##'
  - Cocoa 中适配器模式的示例
- - '##'
  - 将模式应用于 SportsStore 应用
- - '###'
  - 准备示例应用程序
- - '###'
  - 定义适配器类
- - '###'
  - 使用适配后的功能
- - '##'
  - 本章小结
- - '#'
  - 13. 桥接模式
- - '##'
  - 准备示例项目
- - '##'
  - 理解该模式要解决的问题
- - '##'
  - 理解桥接模式
- - '###'
  - 桥接模式难道不就是适配器模式吗？
- - '##'
  - 实现桥接模式
- - '###'
  - 处理消息
- - '###'
  - 处理通道
- - '###'
  - 创建桥接器
- - '###'
  - 添加新的消息类型和通道
- - '##'
  - 桥接模式的变体
- - '###'
  - 折叠桥接
- - '##'
  - 理解桥接模式的陷阱
- - '##'
  - Cocoa 中的桥接模式示例
- - '##'
  - 将模式应用于 SportsStore 应用
- - '###'
  - 准备示例应用
- - '###'
  - 理解问题
- - '###'
  - 定义桥接类
- - '##'
  - 总结
- - '#'
  - 14. 装饰器模式
- - '##'
  - 准备示例项目
- - '##'
  - 理解该模式所解决的问题
- - '##'
  - 理解装饰器模式
- - '##'
  - 实现装饰器模式
- - '##'
  - 装饰器模式的变体
- - '###'
  - 创建具有新功能的装饰器
- - '####'
  - 使用新功能
- - '####'
  - 理解具有新功能的装饰器的局限性
- - '###'
  - 创建合并型装饰器
- - '##'
  - 理解装饰器模式的陷阱
- - '###'
  - 副作用陷阱
- - '##'
  - Cocoa 中装饰器模式的示例
- - '##'
  - 将模式应用于 SportsStore 应用
- - '###'
  - 准备示例应用
- - '###'
  - 创建装饰器
- - '###'
  - 应用装饰器
- - '##'
  - 总结
- - '#'
  - 15. 组合模式
- - '##'
  - 准备示例项目
- - '##'
  - 理解该模式要解决的问题
- - '##'
  - 理解组合模式
- - '##'
  - 实现组合模式
- - '###'
  - 应用模式
- - '##'
  - 理解组合模式的陷阱
- - '##'
  - Cocoa 中组合模式的示例
- - '##'
  - 将模式应用于 SportsStore 应用
- - '###'
  - 准备示例应用
- - '###'
  - 定义组合类
- - '###'
  - 应用模式
- - '##'
  - 本章小结
- - '#'
  - 16. 外观模式
- - '##'
  - 准备示例项目
- - '##'
  - 理解该模式解决的问题
- - '##'
  - 理解外观模式
- - '##'
  - 实现外观模式
- - '###'
  - 应用外观
- - '##'
  - 外观模式的变体
- - '##'
  - 理解外观模式的陷阱
- - '##'
  - Cocoa 中的外观模式示例
- - '##'
  - 将模式应用于 SportsStore 应用
- - '###'
  - 准备示例应用
- - '###'
  - 创建外观类
- - '###'
  - 应用外观类
- - '##'
  - 本章小结
- - '#'
  - 17. 享元模式
- - '##'
  - 准备示例项目
- - '##'
  - 理解该模式解决的问题
- - '##'
  - 理解享元模式
- - '##'
  - 实现享元模式
- - '###'
  - 创建享元协议
- - '###'
  - 创建享元实现类
- - '###'
  - 添加并发保护
- - '###'
  - 创建享元工厂类
- - '###'
  - 应用享元
- - '##'
  - 享元模式的变体
- - '##'
  - 理解享元模式的陷阱
- - '###'
  - 理解外部数据重复陷阱
- - '###'
  - 理解可变外部数据陷阱
- - '###'
  - 理解并发访问陷阱
- - '###'
  - 理解过度优化陷阱
- - '###'
  - 理解误用陷阱
- - '##'
  - Cocoa 中享元模式的示例
- - '##'
  - 将模式应用于 SportsStore 应用程序
- - '###'
  - 准备示例应用程序
- - '###'
  - 创建享元协议和实现类
- - '###'
  - 创建享元工厂
- - '###'
  - 应用享元
- - '##'
  - 总结
- - '#'
  - 18. 代理模式
- - '##'
  - 准备示例项目
- - '##'
  - 理解该模式解决的问题
- - '###'
  - 理解远程对象问题
- - '###'
  - 理解耗时操作问题
- - '###'
  - 理解访问受限问题
- - '##'
  - 理解代理模式
- - '###'
  - 解决远程对象问题
- - '###'
  - 解决高开销操作问题
- - '###'
  - 解决访问受限问题
- - '##'
  - 实现代理模式
- - '###'
  - 实现远程对象代理
- - '####'
  - 定义代理协议
- - '####'
  - 定义代理实现类
- - '####'
  - 使用远程对象代理
- - '###'
  - 实现高开销操作代理
- - '####'
  - 延迟执行操作
- - '###'
  - 实现访问限制代理
- - '###'
  - 创建授权源
- - '###'
  - 创建代理对象
- - '###'
  - 应用代理
- - '##'
  - 代理模式的变体
- - '###'
  - 实现引用计数代理
- - '##'
  - 理解代理模式的陷阱
- - '##'
  - Cocoa 中的代理模式示例
- - '##'
  - 将模式应用于 SportsStore 应用
- - '###'
  - 准备示例应用
- - '###'
  - 定义协议、工厂方法和代理类
- - '###'
  - 更新产品数据存储
- - '###'
  - 发送库存水平更新
- - '##'
  - 总结
- - '#'
  - 第四部分
- - '#'
  - 19. 责任链模式
- - '##'
  - 准备示例项目
- - '##'
  - 理解模式要解决的问题
- - '##'
  - 理解职责链模式
- - '##'
  - 实现责任链模式
- - '###'
  - 创建并提供责任链
- - '###'
  - 应用责任链模式
- - '##'
  - 责任链模式的变体
- - '###'
  - 应用工厂方法模式
- - '###'
  - 指示是否已处理请求
- - '###'
  - 通知链中的所有节点
- - '###'
  - 理解该模式的潜在缺陷
- - '###'
  - Cocoa 中的模式示例
- - '###'
  - 将模式应用于 SportsStore 应用程序
- - '####'
  - 准备示例应用
- - '###'
  - 定义责任链及其链节
- - '##'
  - 本章小结
- - '#'
  - 20. 命令模式
- - '##'
  - 准备示例项目
- - '##'
  - 理解该模式所解决的问题
- - '##'
  - 理解命令模式
- - '##'
  - 实现命令模式
- - '###'
  - 定义命令协议
- - '###'
  - 定义命令实现类
- - '###'
  - 应用命令模式
- - '###'
  - 使用方法引用
- - '###'
  - 应用并发保护
- - '###'
  - 使用撤销功能
- - '##'
  - 命令模式的变体
- - '###'
  - 创建复合命令
- - '###'
  - 将命令用作宏
- - '###'
  - 使用闭包作为命令
- - '##'
  - 理解命令模式的陷阱
- - '##'
  - Cocoa 中命令模式的示例
- - '##'
  - 将模式应用于 SportsStore 应用程序
- - '###'
  - 准备示例应用程序
- - '###'
  - 实现撤销功能
- - '####'
  - 触发撤销命令
- - '##'
  - 小结
- - '#'
  - 21. 中介者模式
- - '##'
  - 准备示例项目
- - '##'
  - 理解该模式要解决的问题
- - '##'
  - 理解中介者模式
- - '##'
  - 实现中介者模式
- - '###'
  - 定义中介者类
- - '###'
  - 符合 Peer 协议
- - '###'
  - 实现并发保护
- - '####'
  - 在调解器中实现并发保护
- - '####'
  - 在同伴中实现并发保护
- - '##'
  - 调解器模式的变体
- - '###'
  - 将更多逻辑放入调解器
- - '###'
  - 泛化调解器-同伴关系
- - '##'
  - 用命令模式泛化中介者
- - '###'
  - 使用消息泛化中介者
- - '##'
  - 理解中介者模式的陷阱
- - '###'
  - 单一协议陷阱
- - '##'
  - Cocoa 中中介者模式的示例
- - '##'
  - 将模式应用于 SportsStore 应用
- - '##'
  - 总结
- - '#'
  - 22. 观察者模式
- - '##'
  - 准备示例项目
- - '##'
  - 理解模式要解决的问题
- - '##'
  - 理解观察者模式
- - '##'
  - 实现观察者模式
- - '###'
  - 创建基础主体类
- - '###'
  - 遵循 Subject 协议
- - '###'
  - 遵循 Observer 协议
- - '###'
  - 消费该模式
- - '##'
  - 观察者模式的变体
- - '###'
  - 通用化通知
- - '###'
  - 理解通知对象陷阱
- - '###'
  - 处理短生命周期主体
- - '###'
  - 我只需要修改基类，因为所需的所有行为都已继承。清单 22-18 展示了我将一个观察者类转变为元观察者所做的修改。
- - '##'
  - 理解观察者模式的陷阱
- - '##'
  - Cocoa 框架中的观察者模式示例
- - '###'
  - 用户界面事件
- - '###'
  - 观察属性变化
- - '##'
  - 将模式应用于 SportsStore 应用程序
- - '###'
  - 准备示例应用
- - '###'
  - 应用观察者模式
- - '##'
  - 本章小结
- - '#'
  - 23. 备忘录模式
- - '##'
  - 准备示例项目
- - '##'
  - 理解模式要解决的问题
- - '##'
  - 理解备忘录模式
- - '##'
  - 实现备忘录模式
- - '###'
  - 实现备忘录类
- - '###'
  - 使用备忘录
- - '###'
  - 备忘录模式的变体
- - '###'
  - 理解备忘录模式的陷阱
- - '##'
  - Cocoa 中备忘录模式的示例
- - '##'
  - 将模式应用于 SportsStore 应用
- - '###'
  - 准备示例应用
- - '###'
  - 实现模式
- - '##'
  - 本章小结
- - '#'
  - 24. 策略模式
- - '##'
  - 准备示例项目
- - '##'
  - 理解该模式要解决的问题
- - '##'
  - 理解策略模式
- - '##'
  - 实现策略模式
- - '###'
  - 定义策略和上下文类
- - '###'
  - 使用该模式
- - '##'
  - 策略模式的变体
- - '##'
  - 理解策略模式的陷阱
- - '##'
  - Cocoa 中的策略模式示例
- - '###'
  - Cocoa 基于协议的策略
- - '###'
  - Cocoa 基于选择器的策略
- - '##'
  - 将模式应用于 SportsStore 应用
- - '##'
  - 小结
- - '#'
  - 25. 访问者模式
- - '##'
  - 准备示例项目
- - '##'
  - 理解该模式要解决的问题
- - '##'
  - 理解访问者模式
- - '##'
  - 实现访问者模式
- - '###'
  - 理解双重分派
- - '###'
  - 遵循 Shape 协议
- - '###'
  - 创建访问者
- - '###'
  - 应用访问者模式
- - '##'
  - 访问者模式的变体
- - '##'
  - 理解访问者模式的陷阱
- - '##'
  - Cocoa 中的访问者模式示例
- - '##'
  - 将模式应用于 SportsStore 应用
- - '##'
  - 总结
- - '#'
  - 26. 模板方法模式
- - '##'
  - 准备示例项目
- - '##'
  - 理解模式解决的问题
- - '##'
  - 理解模板方法模式
- - '##'
  - 实现模板方法模式
- - '##'
  - 模板方法模式的变体
- - '##'
  - 理解该模式的陷阱
- - '##'
  - 模板方法模式在 Cocoa 中的示例
- - '##'
  - 将模式应用于 SportsStore 应用
- - '##'
  - 总结
- - '#'
  - 第五部分
- - '#'
  - 27. 模型/视图/控制器模式
- - '##'
  - 准备示例项目
- - '##'
  - 理解该模式解决的问题
- - '##'
  - 理解 MVC 模式
- - '###'
  - 理解 MVC 应用程序的组成部分
- - '####'
  - 理解模型
- - '####'
  - 理解控制器
- - '###'
  - 理解视图
- - '###'
  - 理解横切关注点
- - '##'
  - 实现 MVC 模式
- - '###'
  - 定义公共代码
- - '###'
  - 定义框架
- - '###'
  - 创建模型
- - '####'
  - 实现仓储模式
- - '###'
  - 定义视图（View）
- - '###'
  - 定义控制器（Controller）
- - '###'
  - 完成框架
- - '###'
  - 运行应用程序
- - '###'
  - 扩展应用程序
- - '####'
  - 定义新命令
- - '####'
  - 定义新视图
- - '####'
  - 定义新控制器
- - '####'
  - 更新框架
- - '####'
  - 测试更改
- - '##'
  - MVC 模式的变体
- - '##'
  - 理解 MVC 模式的陷阱
- - '##'
  - Cocoa 中的 MVC 模式示例
- - '##'
  - 总结
- - '#'
  - 索引
- - '##'
  - A
- - '##'
  - B
- - '##'
  - C
- - '##'
  - D
- - '##'
  - E
- - '##'
  - F
- - '##'
  - G, H
- - '##'
  - I, J
- - '##'
  - K
- - '##'
  - L
- - '##'
  - M
- - '##'
  - N
- - '##'
  - O
- - '##'
  - P, Q
- - '##'
  - R
- - '##'
  - S
- - '##'
  - T
- - '##'
  - U
- - '##'
  - V, W
- - '##'
  - X, Y, Z
