name: IPhone and IPad Apps for Absolute Beginners
name_cn: 绝对初学者 iPhone 与 iPad 应用开发入门指南
slug: iphone-and-ipad-apps-for-absolute-beginners
toc:
- - '#'
  - 目录
- - '##'
  - 前言：关于作者
- - '###'
  - 为何你会与刘易斯博士产生共鸣
- - '###'
  - 时光飞梭十七载
- - '###'
  - 过去—现在—未来
- - '###'
  - 为何撰写此书？
- - '##'
  - 关于合著作者
- - '##'
  - 关于技术审稿人
- - '##'
  - 序言
- - '###'
  - 本书能为你带来什么
- - '###'
  - 听起来很熟悉？
- - '###'
  - 我如何知道这些关于你的事？
- - '###'
  - 我采用的方法
- - '##'
  - 第 1 章：开始之前
- - '###'
  - 必需品与配件
- - '###'
  - 我不会教你什么
- - '###'
  - 计算机科学：一片广阔而多元的天地
- - '###'
  - 为什么 Objective-C 中存在“炼狱”
- - '###'
  - 休斯顿，我们遇到麻烦了
- - '###'
  - 我们将如何不时地探访“炼狱”
- - '###'
  - '展望未来……《Beginning iPhone 4 Development: Exploring the iPhone SDK》'
- - '####'
  - 学习内容
- - '#####'
  - 创建酷炫古怪的应用：我为什么这样教
- - '#####'
  - 向你的祖母传道授业… 你编写的东西至关重要！
- - '###'
  - 这一切是如何运作的？
- - '###'
  - 我们的路线图：使用 Xcode 和界面构建器
- - '###'
  - 准备你的第一个 iPhone/iPad 项目
- - '###'
  - 配套的截屏视频
- - '###'
  - 配套的 PDF 文件
- - '###'
  - 假装不知：去混淆的艺术
- - '###'
  - 如何逐步推进学习
- - '####'
  - 一个小练习
- - '##'
  - 第 2 章：启动！
- - '###'
  - 在 iPhone 模拟器上运行您的应用
- - '###'
  - 12. 按下回车键（![图片](img/00043.jpg)），你会看到 `-(IBAction)button:(id)sender;`，如下所示及图 2–12
    所示。是的，我们将在本章末尾的“深入代码”部分详细讨论这一点。现在，让我们继续前进。
- - '###'
  - 13. 要从这里进入实现文件，请养成首先切换视图，从助理编辑器（还记得我们在步骤 2-7 中做的吗？）切换到标准编辑器的习惯。为此，请转到视图选择器左侧的编辑器选择器，点击标准编辑器，如图
    2–13 所示。
- - '###'
  - 14. 进入标准编辑器后，选择你的 `ViewController` 的实现文件，如图 2–14 所示。
- - '###'
  - 15. 我希望你输入的代码是 `label.text = @"Hello World!"`，但这并不是那么简单，因为当你输入时，会发生一些非常酷的事情。Xcode
    会在其自动完成窗口中推断你可能想要输入的代码，如图 2–15 所示。如果你同意该选择，则按下 Tab 键（![图片](img/00059.jpg)），Xcode
    就会将完整的、拼写正确的命令放入你的代码中。如果它建议的不是正确的，但你看到正确的在下面几行，只需向下箭头键（↓）直到选中正确的选项，然后按下 ![图片](img/00059.jpg)。很酷吧？写完
    `label.text` 后，继续第 16 步。
- - '###'
  - 16. 现在我们需要输入 `@"Hello World!";`，这就是我们想说的话。你的代码应该像图 2–16 所示。如果你想说的是“我感觉我正在变成一个极客！”，那么就输入
    `label.text = @"I can feel I’m becoming a geek!";`。
- - '###'
  - 17. 保存你的工作 ![图片](img/00031.jpg)S，如图 2–17 所示。请尽量不要使用鼠标；努力养成每次想要保存时都按下 Control+S（![图片](img/00031.jpg)S）的新习惯。这会让你感觉并看起来非常聪明和极客。你可能还需要检查你的头文件和
    nib 文件是否也已保存，因为在阅读这些说明的过程中，你可能需要返回并更改文件。那么，你需要返回并保存它们。所以现在就动手保存所有内容。如果文件以灰色突出显示，则意味着你也需要保存它们。
- - '###'
  - 18. 按下 ![图片](img/00031.jpg)R 运行它，如图 2–18 所述。
- - '###'
  - 在读取 iPhone 环境的 iPad 模拟器上运行你的应用
- - '###'
  - 在 iPad 模拟器上运行你的应用
- - '####'
  - '`helloWorld_02` – iPad 模拟器'
- - '###'
  - 在物理设备上运行你的应用
- - '###'
  - 深入解析代码
- - '##'
  - 第 3 章：继续前进
- - '###'
  - helloWorld_03 – 一个交互式基于视图的应用
- - '####'
  - 创建用户界面
- - '####'
  - 连接代码
- - '###'
  - 避免一个恼人的错误
- - '###'
  - 设置编码环境
- - '###'
  - 创建编程路线图
- - '####'
  - 第一步：创建字符串来管理文本输入与输出
- - '####'
  - 第二步：处理文本
- - '####'
  - 第三步：显示你的劳动成果
- - '####'
  - 第四步：内存管理
- - '####'
  - 第五步：关闭键盘
- - '###'
  - 深究代码
- - '###'
  - Nibs、Zibs 和 Xibs
- - '####'
  - 方法
- - '#####'
  - 头文件
- - '#####'
  - 检查器栏
- - '#####'
  - NSString
- - '#####'
  - 更多关于内存管理
- - '####'
  - 好了！
- - '##'
  - 第 4 章：多图形按钮与标签
- - '###'
  - 路线图回顾
- - '###'
  - 'helloWorld_04: 一个基于视图的应用'
- - '###'
  - 理解 `IBOutlets`
- - '###'
  - 指针
- - '####'
  - 属性：管理与控制
- - '####'
  - 添加 IBActions
- - '###'
  - 深入解析代码
- - '####'
  - IBOutlets 和 IBActions
- - '####'
  - 关于指针的更多内容
- - '####'
  - 你已经说过了“你好！”……但现在，轮到 INDIO 了！
- - '#####'
  - 模型-视图-控制器
- - '###'
  - 接下来的章节
- - '##'
  - 第 5 章：触摸
- - '###'
  - 重新定义“放弃”
- - '###'
  - 路线图回顾
- - '###'
  - 触摸交互：一个基于视图的应用
- - '####'
  - '`CGAffineTransform` 结构体'
- - '###'
  - 编写头文件
- - '###'
  - 在实现文件中工作
- - '####'
  - 合成
- - '####'
  - viewDidLoad
- - '####'
  - 将按钮和背景设置为起始状态
- - '####'
  - 创建包含所有壁纸的数组
- - '####'
  - 设置“噜噜水果”图标的缩小程度
- - '####'
  - 设置“噜噜水果”图标的移动距离
- - '####'
  - 将背景图像设置为当前背景图像
- - '####'
  - 新标题
- - '####'
  - 编写缩小按钮的代码
- - '####'
  - 编写移动按钮代码
- - '####'
  - 编写更改按钮代码
- - '####'
  - 运行代码
- - '####'
  - 深入代码
- - '####'
  - 下一章内容
- - '##'
  - 第 6 章：开关
- - '###'
  - 别慌：来看看你的大脑！
- - '###'
  - '`switch:` 一个标签页应用'
- - '####'
  - 获取资源
- - '####'
  - 创建应用
- - '####'
  - 将图像添加到项目中
- - '####'
  - 运行应用
- - '####'
  - 自定义标签
- - '###'
  - 编写第二个视图的代码
- - '###'
  - 添加按钮
- - '###'
  - 编写按钮代码
- - '###'
  - 使用按钮
- - '###'
  - 深入剖析代码
- - '####'
  - 内容视图模式
- - '####'
  - 编译时与运行时
- - '###'
  - 本章前瞻
- - '##'
  - 第 7 章：故事板
- - '###'
  - 讲故事
- - '###'
  - 路线图回顾
- - '###'
  - 路线图：四个阶段
- - '###'
  - 演进：基于视图的分镜脚本应用
- - '####'
  - 第一阶段：创建核心分镜脚本配置
- - '####'
  - 第二阶段：设置视图控制器
- - '####'
  - 第三阶段：建立视图控制器内容
- - '####'
  - 阶段四：收尾与编码
- - '#####'
  - 76. 作为一名极客，你可能希望在最后一个视图控制器的导航栏中显示正确的“Ü”字符。
- - '#####'
  - 77. 打开顶行中的“语言与文本”偏好设置面板，如图 7-77 所示。
- - '#####'
  - 78. 在“输入源”选项卡中，从源列表中选择“键盘与字符显示程序”。同时，打开菜单项，如图 7-78 底部附近所示。
- - '#####'
  - 79. 现在，最小化此窗口以释放屏幕空间。稍后你将再次关闭该菜单项。见图 7-79。
- - '#####'
  - 80. 现在，从菜单栏中出现的新图标中，选择“显示字符显示程序”。会显示一个微型键盘。当你在键盘上打字时，相应的按键会高亮显示，如图 7-80 所示。
- - '#####'
  - 81. 按住 Option 键会显示大量可供键入的符号。橙色按键对应其他语言中字符上方带有标记的特殊键，例如“ö”或“ê”。嗯，这正是你需要的。见图 7-81。
- - '#####'
  - 82. 回到 Xcode，双击`ÜberView`的标题栏进行编辑。首先键入 Option-u，同时观察下方的小键盘。现在你会看到一个黄色方框中的两个点。你接下来键入的字母上方将带有这个标记。键入
    Shift-u。铛铛——Ü。然后输入“ber Geek”完成它，如图 7-83 所示。
- - '#####'
  - 83. 图 7-83 显示了“Über Geek”的正确拼写。
- - '#####'
  - 84. 图 7-84 展示了如何像关闭其他窗口一样关闭键盘。
- - '#####'
  - 85. 如前所述，你可能希望从之前最小化的偏好设置面板中隐藏该菜单项，如图 7-85 所示。
- - '#####'
  - 86. 让我们保存所有内容并测试一下，如图 7-86 所示。
- - '#####'
  - 87. 图 7-87 展示了最后一步——运行它。
- - '#####'
  - 88. 做得好！
- - '###'
  - 深入代码
- - '###'
  - 故事板视图控制器、iOS4 及其编程式创建
- - '###'
  - 在接下来的章节中
- - '##'
  - 第 8 章：调试
- - '###'
  - Xcode 的调试全景
- - '###'
  - Xcode 的工具
- - '####'
  - Xcode 的工具：文本编辑器
- - '####'
  - Xcode 的工具：调试器窗口
- - '####'
  - Xcode 的工具：GDB 控制台
- - '####'
  - Xcode 的工具：控制台输出和设备日志
- - '####'
  - Xcode 的工具：NSZombie
- - '####'
  - Xcode 的工具：Shark
- - '####'
  - Xcode 的工具：单元测试
- - '###'
  - 我们的工具：`FileMerge.app`
- - '###'
  - '`switch-mistake`：崩溃艺术的一课'
- - '####'
  - 启动项目
- - '###'
  - 创建视图
- - '###'
  - 制造 Bug
- - '####'
  - 比较源文件
- - '###'
  - 深入代码
- - '####'
  - 调试器控制台
- - '###'
  - Fix-it
- - '###'
  - Documentation
- - '###'
  - Static Analysis
- - '###'
  - 本章前瞻
- - '##'
  - 第 9 章：MapKit 与 Storyboarding
- - '###'
  - 关于框架的一点介绍
- - '###'
  - 重要须知
- - '###'
  - 预装的 MapKit 应用
- - '####'
  - 找到自己
- - '####'
  - 搜索位置
- - '####'
  - 切换视图，查看交通状况
- - '###'
  - 酷炫且受欢迎的 MapKit 应用给我们带来启发
- - '###'
  - myStory_01：一个单视图应用
- - '###'
  - 应用预备知识
- - '###'
  - 准备工作
- - '###'
  - 新建单视图模板
- - '####'
  - 前期准备：添加注释文件
- - '####'
  - 前期准备：添加框架
- - '####'
  - 引入图片！
- - '####'
  - 编写 `myPos` `NSObject`
- - '####'
  - 编写视图控制器
- - '#####'
  - 处理视图控制器的实现
- - '###'
  - 故事板
- - '###'
  - 代码解析
- - '####'
  - 协议
- - '###'
  - 故事板对象的内存管理
- - '###'
  - 深入剖析我学生的 MapKit 代码
- - '####'
  - 从互联网解析数据到 MapKit
- - '####'
  - MapKit 解析
- - '###'
  - 起点
- - '###'
  - 从网络获取数据
- - '###'
  - 向视图控制器添加方法
- - '###'
  - 测试解析器数据源
- - '###'
  - 启动解析器方法
- - '###'
  - 三个 MapKit 最终项目：CS–201 iPhone 应用，Objective–C
- - '####'
  - 示例 1 和 2 的个人简介信息
- - '#####'
  - 期末项目——示例 1
- - '#####'
  - 最终项目—示例 2
- - '####'
  - 示例 3 的个人简介
- - '#####'
  - 期末项目——示例 3
- - '###'
  - 缩小视野……纵观全局
- - '##'
  - 第 10 章：使用 Storyboarding 的 MapKit 与表格
- - '###'
  - '`myStory_02`：一个单视图应用'
- - '####'
  - 应用准备前的可能工作
- - '####'
  - 预备知识
- - '####'
  - 新建单视图模板
- - '####'
  - 导入图片！
- - '####'
  - 组织故事板
- - '####'
  - 添加表格视图控制器
- - '####'
  - 编写`myMasterTableViewController`
- - '###'
  - 第二部分
- - '####'
  - 整体概览：第二部分概述
- - '####'
  - 整体概览：编码概述
- - '#####'
  - 编写 `myDetailViewController.m` 文件
- - '###'
  - 调整故事板
- - '####'
  - 整体概览：故事板调整扩展
- - '##'
  - 第 11 章：从故事板到多媒体平台
- - '###'
  - '`myiTunes`：一个主从应用'
- - '####'
  - 准备工作
- - '####'
  - 新的主从模板
- - '####'
  - 导入图片！
- - '####'
  - 在 Storyboard 中组织弹出窗口
- - '#####'
  - 整体视图
- - '####'
  - 编写 myiTunes 应用
- - '###'
  - 总体概览
- - '####'
  - 注意
- - '####'
  - 全景概览
- - '####'
  - 编码 DetailViewController
- - '###'
  - 总体蓝图
- - '####'
  - 完成故事板
- - '###'
  - 结语
- - '##'
  - 索引
- - '###'
  - 特殊字符与数字
- - '###'
  - A
- - '###'
  - B
- - '###'
  - 按钮
- - '###'
  - C
- - '###'
  - D
- - '###'
  - E
- - '###'
  - F
- - '###'
  - G
- - '###'
  - H
- - '###'
  - J
- - '###'
  - K
- - '###'
  - L
- - '###'
  - M
- - '###'
  - N
- - '###'
  - O
- - '###'
  - P
- - '###'
  - Q
- - '###'
  - R
- - '###'
  - S
- - '###'
  - T
- - '###'
  - '`Ü` 字符，创建，315–320'
- - '###'
  - V
- - '###'
  - W
- - '###'
  - X
- - '###'
  - Y
- - '###'
  - Z
