name: IOS Code Testing
name_cn: iOS 代码测试
slug: ios-code-testing
toc:
- - '#'
  - iOS 代码测试
- - '##'
  - 使用 Swift 进行测试驱动开发与行为驱动开发
- - '#'
  - 致谢
- - '#'
  - 目录
- - '##'
  - 内容概览
- - '##'
  - 关于作者与关于技术审校
- - '#'
  - 1. 测试驱动开发简介
- - '##'
  - 什么是测试驱动开发？
- - '##'
  - TDD 术语
- - '###'
  - 被测对象
- - '###'
  - 单元测试
- - '###'
  - 状态验证测试
- - '###'
  - 交互测试
- - '###'
  - 负面测试
- - '###'
  - 测试套件
- - '###'
  - 断言
- - '###'
  - 实例化用于测试的类
- - '##'
  - 测试驱动开发的原则
- - '###'
  - 测试先行
- - '###'
  - 红 – 绿 – 重构
- - '###'
  - 编写最少量的代码
- - '###'
  - 消除重复
- - '##'
  - 总结
- - '##'
  - 注释
- - '#'
  - 2. 使用 Xcode 编写你的第一组单元测试
- - '##'
  - 下载并安装 Xcode
- - '##'
  - 创建支持单元测试的新项目
- - '##'
  - 为现有项目添加单元测试支持
- - '##'
  - Xcode 导览
- - '###'
  - 项目导航器
- - '###'
  - 测试用例类
- - '###'
  - 测试导航器
- - '###'
  - 查看测试报告
- - '####'
  - 代码覆盖率报告
- - '##'
  - 构建 Cookie Factory App
- - '###'
  - 构建 Cookie 类
- - '###'
  - 构建 CookieController 类
- - '###'
  - 更新视图控制器类
- - '###'
  - 查看代码覆盖率数据
- - '##'
  - 摘要
- - '#'
  - 3. MVVM 架构模式
- - '##'
  - MVC 架构模式
- - '###'
  - 模型-视图-控制器架构模式
- - '##'
  - 模型-视图-控制器的可测试性问题
- - '##'
  - 模型-视图-视图模型架构模式
- - '##'
  - MVVM 的优势
- - '##'
  - 视图模型实例化
- - '###'
  - 独立的视图控制器
- - '###'
  - 表视图控制器
- - '###'
  - 基于导航控制器的应用
- - '##'
  - 总结
- - '#'
  - 4. 将 TDD 应用于模型
- - '##'
  - 创建 Xcode 项目
- - '##'
  - 构建模型层
- - '###'
  - '`AccountOwner` 类'
- - '###'
  - 创建名字验证器类
- - '###'
  - 创建姓氏验证器类
- - '###'
  - 创建电子邮件地址验证器类
- - '###'
  - 将验证器类集成到 AccountOwner 类中
- - '##'
  - Transaction 类
- - '##'
  - BankAccount 类
- - '##'
  - 测试 Core Data
- - '##'
  - 总结
- - '#'
  - 5. 将 TDD 应用于视图控制器
- - '##'
  - 应用架构
- - '##'
  - 创建 Xcode 项目
- - '##'
  - 构建用户界面层
- - '###'
  - 构建登录视图控制器场景
- - '###'
  - 构建注册视图控制器场景
- - '###'
  - 在登录场景和注册场景之间创建转场
- - '##'
  - 构建模型层
- - '###'
  - LoginModel 类
- - '###'
  - '`SignupModel` 类'
- - '##'
  - 构建视图模型层
- - '###'
  - '`LoginViewModel` 类'
- - '###'
  - 视图模型 – 视图控制器绑定
- - '###'
  - 构建 `performInitialViewSetup` 方法
- - '###'
  - 构建 `userNameDidEndOnExit` 方法
- - '####'
  - 构建 `passwordDidEndOnExit` 方法
- - '####'
  - 构建 `userNameUpdated` 方法
- - '###'
  - 构建 `passwordUpdated` 方法
- - '###'
  - 构建 `login` 方法
- - '###'
  - 创建登录控制器类
- - '###'
  - 创建模拟登录控制器类
- - '###'
  - 更新 LoginViewModel 类
- - '###'
  - '`SignupViewModel` 类'
- - '##'
  - 将视图控制器连接到视图模型
- - '###'
  - 将登录视图控制器类绑定到视图模型
- - '###'
  - 从视图控制器调用视图模型的 `performInitialSetup` 方法
- - '###'
  - 从视图控制器调用视图模型的 `userNameDidEndOnExit` 方法
- - '###'
  - 从视图控制器调用视图模型的 `passwordDidEndOnExit` 方法
- - '###'
  - 从视图控制器调用视图模型的登录方法
- - '###'
  - 从视图控制器调用视图模型的 `userNameUpdated` 和 `passwordUpdated` 方法
- - '###'
  - 将注册视图控制器类绑定到视图模型
- - '###'
  - 从登录视图控制器过渡到注册视图控制器
- - '##'
  - 本章小结
- - '#'
  - 6. 对集合视图控制器应用 TDD
- - '##'
  - 应用架构
- - '##'
  - 创建 Xcode 项目
- - '##'
  - 向项目添加资源
- - '##'
  - 构建用户界面层
- - '###'
  - 创建新类
- - '###'
  - 构建集合视图控制器场景
- - '###'
  - 添加分区头部辅助视图
- - '###'
  - 构建集合视图单元格
- - '##'
  - 构建模型层
- - '###'
  - Photo 类
- - '###'
  - '`City` 类'
- - '###'
  - '`Album` 类'
- - '##'
  - 构建 ViewModel 层
- - '###'
  - '`CollectionViewModel` 类'
- - '###'
  - 视图模型 – 视图控制器绑定
- - '###'
  - 测试 `performInitialViewSetup` 方法
- - '###'
  - 测试 `numberOfSections` 方法
- - '###'
  - 测试 `numberOfItemsInSection` 方法
- - '###'
  - 测试 `cellViewModel` 方法
- - '###'
  - 测试 `headerViewModel` 方法
- - '##'
  - '`CollectionViewCellViewModel` 类'
- - '##'
  - '`CollectionViewSectionHeaderViewModel` 类'
- - '##'
  - 将视图层绑定到视图模型
- - '###'
  - 将集合视图控制器类绑定到视图模型
- - '###'
  - 将 `CollectionViewCell` 类绑定到视图模型
- - '###'
  - 将 `CollectionViewSectionHeader` 类绑定到视图模型
- - '##'
  - 总结
- - '#'
  - 7. 测试 URLSession
- - '##'
  - 测试网络层的策略
- - '##'
  - 准备 `PhotoBook` 项目
- - '###'
  - 远程内容规范
- - '###'
  - 配置应用传输安全
- - '##'
  - 构建网络层
- - '###'
  - 创建 `ServiceController` 类
- - '###'
  - 创建 `MockURLSession` 类
- - '###'
  - 创建 `MockURLSessionDataTask` 类
- - '##'
  - 更新模型层
- - '###'
  - 更新 `Album` 类
- - '####'
  - 为 `load( )` 方法编写新测试
- - '####'
  - 创建 MockServiceController 类
- - '####'
  - 修改 Album 类
- - '###'
  - 更新 Photo 类
- - '####'
  - 为 `Photo` 类编写新的测试
- - '###'
  - 创建 `MockPhoto` 类
- - '###'
  - 修改 `Photo` 类
- - '###'
  - 创建 `DownloadListenerProtocol.swift` 文件
- - '###'
  - 创建 `MockDownloadListener` 类
- - '##'
  - 更新视图模型层
- - '###'
  - 对集合视图模型的更新
- - '###'
  - 集合视图单元格视图模型的更新
- - '##'
  - 更新视图层
- - '###'
  - 集合视图控制器的更新
- - '###'
  - 集合视图单元格的更新
- - '##'
  - 总结
- - '#'
  - 8. 处理遗留代码
- - '##'
  - 拆分大型类
- - '##'
  - 向现有类添加功能
- - '###'
  - 使用类和方法进行封装
- - '###'
  - 重命名与替换
- - '###'
  - 装饰器模式
- - '##'
  - 使用协议解耦类
- - '##'
  - 使用依赖注入创建更可测试的代码
- - '##'
  - 总结
- - '##'
  - 备注
- - '#'
  - 9. 持续集成
- - '##'
  - 备注
- - '##'
  - 安装 macOS Server
- - '##'
  - 注释
- - '###'
  - 启动 macOS Server
- - '###'
  - 设置团队成员访问权限
- - '###'
  - 启动 Xcode Server
- - '###'
  - 配置 Xcode Server
- - '####'
  - Xcode 版本
- - '####'
  - Apple 开发者团队
- - '####'
  - 开发设备
- - '####'
  - 代码仓库
- - '###'
  - 在 Xcode Server 上创建新的 Git 仓库
- - '##'
  - 配置 Xcode
- - '###'
  - 向 Xcode 添加 Xcode Server 凭据
- - '###'
  - 创建新的 Xcode 项目并将其仓库托管在 Xcode Server 上
- - '###'
  - 将现有的本地仓库克隆到 Xcode Server
- - '###'
  - 从 Xcode Server 克隆 Git 仓库
- - '###'
  - 从 GitHub 克隆 Git 仓库
- - '##'
  - 创建与集成 Bot
- - '###'
  - 创建 Bot
- - '###'
  - 邮件通知
- - '###'
  - 集成机器人
- - '##'
  - 摘要
- - '#'
  - 10. 行为驱动开发简介
- - '##'
  - 什么是行为驱动开发
- - '##'
  - BDD 与 TDD 的区别
- - '###'
  - 业务需求与用户场景
- - '###'
  - 从用户场景到 BDD 测试
- - '###'
  - Quick 测试用例的结构
- - '##'
  - BDD 的优势与劣势
- - '##'
  - 总结
- - '#'
  - 11. 安装 Quick
- - '##'
  - 将 Quick 添加到 Xcode 项目
- - '###'
  - 使用 CocoaPods 将 Quick 添加到 Xcode 项目
- - '###'
  - 使用 Carthage 将 Quick 集成到 Xcode 项目中
- - '###'
  - 使用 Git 子模块将 Quick 添加到 Xcode 项目
- - '##'
  - 小结
- - '#'
  - 12. 应用 TDD 和 BDD 技术
- - '##'
  - 审阅业务需求
- - '##'
  - 高层应用架构
- - '##'
  - 创建 Xcode 项目
- - '##'
  - 向项目添加资源
- - '##'
  - 构建用户界面层
- - '##'
  - 使用 Quick 编写 BDD 测试
- - '###'
  - 检查场景 3 的 BDD 测试
- - '###'
  - 检查场景 4 的 BDD 测试
- - '###'
  - 检查场景 5 的 BDD 测试
- - '###'
  - 检查场景 6 的 BDD 测试
- - '###'
  - 检查场景 7 的 BDD 测试
- - '###'
  - 检查场景 8 的 BDD 测试
- - '###'
  - 检查场景 9 的 BDD 测试
- - '###'
  - 创建桩对象
- - '###'
  - 将餐厅数据文件添加到项目
- - '###'
  - 检查剩余的编译错误
- - '##'
  - 构建模型层
- - '##'
  - 构建视图模型层
- - '###'
  - SearchViewModel 类
- - '###'
  - '`RestaurantTableViewModel` 类'
- - '###'
  - '`RestaurantTableViewCellViewModel` 类'
- - '##'
  - 视图控制器到视图模型的绑定
- - '##'
  - 总结
- - '#'
  - 13. 测试用户界面
- - '##'
  - 向项目添加 UI 测试支持
- - '###'
  - 新项目
- - '###'
  - 现有项目
- - '##'
  - UI 测试类
- - '##'
  - 创建新的测试类
- - '##'
  - 对 XCTest 的改动以支持 UI 测试
- - '##'
  - XCUIDevice
- - '###'
  - XCUIElement, XCUIElementAttributes
- - '###'
  - XCUIElementQuery 和 XCUIElementTypeQueryProvider
- - '###'
  - 断言
- - '###'
  - UI 录制
- - '###'
  - 断言前的等待
- - '###'
  - 综合应用
- - '##'
  - 总结
- - '#'
  - 索引
- - '##'
  - A
- - '###'
  - AccountOwner 类
- - '###'
  - Album 类
- - '###'
  - AlertFactory.swift
- - '###'
  - Apple 开发者团队
- - '###'
  - 应用程序传输安全（ATS）
- - '###'
  - 断言（Assertions）
- - '###'
  - 异步测试技术
- - '##'
  - B
- - '###'
  - BankAccount 类
- - '###'
  - 行为驱动开发（BDD）
- - '###'
  - BitBucket
- - '###'
  - 机器人（Bots）
- - '###'
  - BusinessBankAccount
- - '###'
  - 业务需求
- - '##'
  - C
- - '###'
  - Carthage
- - '###'
  - CocoaPods
- - '###'
  - 代码覆盖率报告
- - '###'
  - CollectionViewCellProtocol.swift
- - '###'
  - CollectionViewCell.swift
- - '###'
  - 集合视图控制器，TDD 应用程序架构
- - '###'
  - 视图层，绑定到 Xcode 项目
- - '###'
  - ColorDetailViewController
- - '###'
  - ColorDetailViewModel
- - '###'
  - ColorListTableViewController
- - '###'
  - ColorTableViewModel
- - '###'
  - '`context()` 函数'
- - '###'
  - 持续集成（CI）机器人
- - '###'
  - macOS 服务器
- - '###'
  - Xcode 服务器
- - '###'
  - Controller 组件
- - '###'
  - CookieController 类
- - '###'
  - Cookie factory 应用程序
- - '###'
  - Core Data
- - '###'
  - CountriesAndCitiesUITests.swift 文件
- - '##'
  - D
- - '###'
  - '`dataToReturnOnSuccess`'
- - '###'
  - 装饰器模式
- - '###'
  - 依赖注入（DI）
- - '###'
  - '`describe()`'
- - '###'
  - '`displayResultsScreen()` 方法'
- - '###'
  - 领域特定语言（DSL）
- - '###'
  - DownloadListenerProtocol
- - '###'
  - '`downloadProfileHelper()`'
- - '##'
  - E
- - '###'
  - '`element(boundBy:)` 方法'
- - '###'
  - 电子邮件地址验证器类
- - '##'
  - F
- - '###'
  - 工厂方法
- - '###'
  - 伪造对象（Fake objects）
- - '###'
  - FirstNameValidator 类
- - '##'
  - G
- - '###'
  - GitHub
- - '###'
  - Git 子模块
- - '###'
  - 绿色阶段
- - '##'
  - H
- - '###'
  - 高层应用程序架构
- - '##'
  - I, J, K
- - '###'
  - 包含单元测试
- - '###'
  - 实例化类
- - '###'
  - 交互测试
- - '###'
  - LargeViewController.swift
- - '###'
  - 姓氏验证器类
- - '###'
  - '`launch()` 方法'
- - '###'
  - 遗留代码
- - '###'
  - 登录视图控制器
- - '##'
  - M
- - '###'
  - Mac App Store
- - '###'
  - macOS 服务器
- - '###'
  - 大规模视图控制器
- - '###'
  - 主从应用程序
- - '###'
  - 主视图模型
- - '###'
  - 模拟对象（Mock object）
- - '###'
  - Mock/Stub 基础测试技术
- - '###'
  - MockURLSession 类
- - '###'
  - 模拟验证器
- - '###'
  - Model 组件
- - '###'
  - 模型层
- - '###'
  - 模型层更新
- - '###'
  - 模型-视图-控制器（MVC）架构模式
- - '###'
  - Model, View, ViewModel (MVVM)
- - '###'
  - Modified BankAccount.swift
- - '##'
  - N
- - '###'
  - 基于导航控制器的应用程序
- - '###'
  - 负面单元测试
- - '###'
  - NetworkController.swift
- - '###'
  - 网络层，PhotoBook 应用
- - '###'
  - Nimble
- - '###'
  - 面向对象的系统
- - '##'
  - O
- - '###'
  - '`onViewListings()` 操作方法'
- - '##'
  - P
- - '###'
  - 性能测试方法
- - '###'
  - PersonalBankAccount
- - '###'
  - PhotoBook 应用程序
- - '###'
  - Photo 类
- - '###'
  - 项目导航器
- - '##'
  - Q
- - '###'
  - Quick 的 BDD 测试
- - '###'
  - Quick 框架
- - '###'
  - Quick 测试用例类
- - '##'
  - R
- - '###'
  - ReactiveCocoa
- - '###'
  - 红-绿-重构方法
- - '###'
  - RefactoredLargeViewController.swift
- - '###'
  - 远程内容规范
- - '###'
  - '`reset()`'
- - '###'
  - RestaurantDirectorySpecification
- - '###'
  - RxSwift
- - '##'
  - S
- - '###'
  - Segue 标识符
- - '###'
  - ServiceController 类
- - '###'
  - ServiceControllerTests
- - '###'
  - '`setUp()` 方法'
- - '###'
  - 注册视图控制器
- - '###'
  - '`spec()`'
- - '###'
  - 状态验证测试
- - '###'
  - 基于桩的测试技术
- - '###'
  - 被测对象
- - '###'
  - Swift 方法
- - '###'
  - Swift 协议
- - '##'
  - T
- - '###'
  - 表格视图控制器
- - '###'
  - TDD 和 BDD 技术
- - '###'
  - 拆卸方法
- - '###'
  - 测试用例（参见单元测试）
- - '###'
  - 测试用例类
- - '###'
  - testCountryListAppearsOnAppLaunch
- - '###'
  - 测试驱动开发（TDD）
- - '###'
  - TestGitRepositoryHostedOnXcodeServer
- - '###'
  - 测试网络层策略
- - '###'
  - 测试方法
- - '###'
  - 测试导航器
- - '###'
  - 测试套件
- - '###'
  - Transaction 类
- - '##'
  - U
- - '###'
  - 单元测试
- - '###'
  - UI 层
- - '###'
  - URLSessionProtocol.swift
- - '###'
  - 用户界面（UI）
- - '###'
  - UserProfile.swift
- - '##'
  - V, W
- - '###'
  - View 组件
- - '###'
  - 视图控制器类
- - '###'
  - 视图控制器到视图模型的绑定
- - '###'
  - 视图层更新
- - '###'
  - 视图模型
- - '###'
  - ViewModel 层
- - '###'
  - ViewModel 层构建
- - '###'
  - View Model 层更新
- - '###'
  - 视图/视图控制器层
- - '##'
  - X, Y, Z
- - '###'
  - Xcode
- - '###'
  - Xcode 8
- - '###'
  - Xcode 项目
- - '###'
  - Xcode 服务器
- - '###'
  - XCTest
- - '###'
  - XCUIApplication
- - '###'
  - XCUIDevice
- - '###'
  - XCUIElement
- - '###'
  - XCUIElementAttributes
- - '###'
  - XCUIElementQuery
