name: Pro OpenGL ES for iOS
name_cn: OpenGL ES for iOS 高级指南
slug: pro-opengl-es-for-ios
toc:
- - '#'
  - 目录
- - '##'
  - 内容一览
- - '##'
  - 引言
- - '#'
  - 第 1 章：计算机图形学：从过去到现在
- - '##'
  - 你的第一个 OpenGL ES 程序
- - '##'
  - 计算机图形学的斑驳历史
- - '###'
  - 好莱坞的 3D
- - '###'
  - 计算机图形学的曙光
- - '##'
  - 犹他大学
- - '##'
  - 工具包
- - '###'
  - OpenGL
- - '###'
  - Direct3D
- - '##'
  - 其他竞争者
- - '###'
  - QuickDraw 3D
- - '###'
  - OGRE
- - '###'
  - OpenSceneGraph
- - '###'
  - Unity3D
- - '##'
  - 还有其他
- - '##'
  - 回到两个立方体的华尔兹
- - '##'
  - 深入探究
- - '##'
  - 展示场景
- - '##'
  - 总结
- - '#'
  - 第 2 章：那些数学玩意儿
- - '##'
  - 二维变换
- - '###'
  - 平移
- - '##'
  - 旋转
- - '##'
  - 缩放
- - '##'
  - 三维变换
- - '##'
  - 透视投影与平行投影
- - '#'
  - 第 3 章：构建 3D 世界
- - '##'
  - 再补充一点理论
- - '##'
  - OpenGL 坐标
- - '##'
  - 视点坐标
- - '##'
  - 视锥体与投影矩阵
- - '##'
  - 回到有趣的部分：一个更简单的演示
- - '###'
  - 超越弹跳方块
- - '###'
  - 添加几何体
- - '##'
  - 定义视锥体
- - '##'
  - 让它旋转起来
- - '##'
  - 调整数值
- - '##'
  - 裁剪区域
- - '##'
  - 视角
- - '##'
  - 面剔除
- - '##'
  - 小结
- - '#'
  - 第 4 章：开启光照
- - '##'
  - 光与色的故事
- - '##'
  - 要有光
- - '##'
  - 回归趣事（稍作停留）
- - '##'
  - 光与材质的趣味探索
- - '##'
  - 镜面光照
- - '##'
  - 环境光
- - '##'
  - 退一步思考
- - '##'
  - 自发光材质
- - '##'
  - 衰减
- - '###'
  - 聚光灯
- - '###'
  - 光照参数实际应用
- - '###'
  - 着色背后的数学原理
- - '###'
  - 镜面反射
- - '##'
  - 回到太阳系
- - '#'
  - 第 5 章：纹理
- - '##'
  - 程序化纹理与图像纹理
- - '##'
  - 图像纹理
- - '##'
  - OpenGL ES 与纹理
- - '###'
  - Mipmaps（多级纹理映射）
- - '###'
  - 过滤
- - '##'
  - 纹理采样与过滤
- - '##'
  - OpenGL 扩展与 PVRTC 压缩
- - '##'
  - 更多太阳系内容
- - '##'
  - 总结
- - '#'
  - 第 6 章：它能融合吗？
- - '##'
  - Alpha 混合
- - '##'
  - 多色混合
- - '##'
  - 纹理混合
- - '##'
  - 多重纹理
- - '##'
  - 凹凸映射
- - '##'
  - 本章小结
- - '#'
  - 第 7 章：渲染精美的杂项
- - '##'
  - 帧缓冲对象
- - '##'
  - 海德利缓冲对象
- - '##'
  - 太阳缓冲对象
- - '##'
  - 镜头光晕
- - '##'
  - 模板反射表面
- - '##'
  - 模板操作的设置方式
- - '##'
  - 阴影的来临
- - '##'
  - 阴影映射
- - '##'
  - 阴影体积
- - '##'
  - 斑点阴影
- - '##'
  - 投影阴影
- - '##'
  - 在三维空间中移动物体
- - '##'
  - 眼见星光
- - '#'
  - 第 8 章：综合应用
- - '##'
  - 添加用户界面
- - '##'
  - 总结
- - '#'
  - 第 9 章：性能与技巧
- - '##'
  - 顶点缓冲对象
- - '##'
  - 面剔除与 VBO 使用
- - '##'
  - 交错数据
- - '##'
  - 批处理
- - '##'
  - 纹理
- - '##'
  - 精灵图表
- - '##'
  - 纹理上传
- - '##'
  - Mipmap
- - '##'
  - 更少的颜色
- - '##'
  - 其他需谨记的技巧
- - '##'
  - OpenGL 分析器
- - '###'
  - 录制/停止
- - '###'
  - 工具检查器
- - '##'
  - 追踪
- - '##'
  - 调用树
- - '##'
  - API 统计
- - '##'
  - 总结
- - '#'
  - 第 10 章：OpenGL ES 2、着色器以及……
- - '##'
  - 着色管线
- - '##'
  - 回到起点
- - '##'
  - 着色器结构
- - '###'
  - 限制
- - '###'
  - 回到旋转的立方体
- - '###'
  - 关于 `setupGL()` 的补充说明
- - '###'
  - 地球夜景
- - '##'
  - 使用 GLKit 的更多乐趣
- - '###'
  - GLKEffects
- - '###'
  - GLKReflectionMap
- - '##'
  - 总结
- - '#'
  - 索引
- - '##'
  - 数字和特殊符号
- - '##'
  - 字母 A
- - '##'
  - 字母 B
- - '##'
  - 字母 C
- - '##'
  - 字母 D
- - '##'
  - 字母 G
- - '##'
  - 字母 H
- - '##'
  - 字母 U
- - '##'
  - 字母 W
- - '##'
  - 字母 X, Y
- - '##'
  - 字母 Z
