name: Beginning Windows Mixed Reality Programming
name_cn: Windows Mixed Reality 编程入门指南
slug: beginning-windows-mixed-reality-programming
toc:
- - '#'
  - 引言：混合现实的未来
- - '#'
  - 第一部分 入门指南
- - '#'
  - 第1章 准备就绪：必要的硬件和软件工具
- - '##'
  - 确保电脑准备就绪
- - '##'
  - 理解 HoloLens 及其他 Windows 混合现实硬件
- - '###'
  - 由内向外追踪与空间映射
- - '###'
  - 空间音效
- - '###'
  - 透明式与沉浸式头戴设备
- - '##'
  - 下载并安装所需的与可选的软件工具
- - '###'
  - 安装 Visual Studio
- - '###'
  - 安装 Unity
- - '###'
  - 下载混合现实工具包
- - '##'
  - 总结
- - '#'
  - 第2章 Unity 速成课程
- - '##'
  - 什么是 Unity？
- - '##'
  - Unity 的免费与付费层级
- - '##'
  - 第一个 Unity 应用
- - '###'
  - 步骤 1：创建新的 Unity 项目
- - '###'
  - 步骤 2：保存场景
- - '###'
  - 步骤 3：创建地面平面
- - '###'
  - 步骤 4：重命名平面
- - '###'
  - 步骤 5：重置地面平面位置
- - '###'
  - 步骤 6：缩放至地面平面
- - '###'
  - 步骤 7：缩放地面
- - '###'
  - 步骤 8：创建球体
- - '###'
  - 步骤 9：重命名球体
- - '###'
  - 步骤 10：重置球体位置
- - '###'
  - 步骤 11：聚焦球体
- - '###'
  - 步骤 12：抬高球体位置
- - '###'
  - 步骤 13：将地面着色为蓝色
- - '###'
  - 步骤 14：为小球添加物理效果
- - '###'
  - 步骤 15：启用键盘控制
- - '###'
  - 步骤 16：测试应用程序
- - '##'
  - 总结
- - '#'
  - 第二部分 构建全息体验
- - '#'
  - 第3章 创建你的第一个全息图
- - '##'
  - 让 Unity 为混合现实开发做好准备
- - '###'
  - 步骤 1：将混合现实工具包导入新 Unity 项目
- - '###'
  - 步骤 2：使用混合现实工具包为混合现实开发准备场景
- - '##'
  - 您的第一个全息图
- - '###'
  - 步骤 1：创建立方体
- - '###'
  - 步骤 2：将视图聚焦到您的立方体
- - '###'
  - 步骤 3：将方块移离摄像机
- - '###'
  - 步骤 4：调整方块大小
- - '###'
  - 步骤 5：测试你的应用
- - '###'
  - 步骤 6：在 HoloLens 上安装你的应用
- - '##'
  - 总结
- - '#'
  - 第4章 混合现实工具包简介
- - '##'
  - 什么是混合现实工具包？
- - '###'
  - 三个 MRTK 仓库
- - '##'
  - 混合现实工具包设置
- - '###'
  - 导入 MRTK 资源文件
- - '###'
  - Unity 包管理器
- - '##'
  - 混合现实工具包组件
- - '###'
  - MRTK：输入系统
- - '####'
  - 如何运行测试场景
- - '###'
  - MRTK：手部追踪
- - '###'
  - MRTK：解算器系统
- - '###'
  - MRTK：多场景管理器
- - '###'
  - MRTK：空间感知
- - '###'
  - MRTK：诊断工具
- - '###'
  - MRTK：边界系统
- - '###'
  - MRTK：UX 控件
- - '###'
  - MRTK：相机系统
- - '###'
  - MRTK：配置文件
- - '###'
  - MRTK：标准着色器
- - '##'
  - MRTK 在线资源
- - '###'
  - 什么是 GitHub？
- - '###'
  - MRTK 帮助与文档
- - '##'
  - 总结
- - '#'
  - 第5章 与全息影像交互
- - '##'
  - 输入方式
- - '##'
  - 视觉注视教程
- - '###'
  - 步骤 1：设置 Unity 场景
- - '###'
  - 步骤 2：将场景添加到构建菜单
- - '###'
  - 步骤 3：尝试场景！
- - '###'
  - 步骤 4：理解场景
- - '###'
  - 步骤 5：在你的项目中使用注视
- - '##'
  - 手势教程
- - '###'
  - 步骤 1：加载测试场景
- - '###'
  - 步骤 2：试试看！
- - '###'
  - 步骤 3：边界控制
- - '###'
  - 步骤 4：按下与触摸交互
- - '###'
  - 步骤 5：对象操纵器
- - '###'
  - 步骤 6：在应用中实现手势
- - '##'
  - 语音命令教程
- - '###'
  - 步骤 1：加载示例场景
- - '###'
  - 步骤 2：试试看！
- - '###'
  - 步骤 3：理解场景
- - '###'
  - 步骤 4：添加你自己的语音指令
- - '###'
  - 步骤 5：在你自己的项目中使用语音指令
- - '###'
  - 语音命令最佳实践
- - '##'
  - 其他硬件输入
- - '##'
  - 总结
- - '#'
  - 第6章 使用空间感知
- - '##'
  - 什么是空间感知？
- - '##'
  - 空间感知教程
- - '###'
  - 步骤 1：设置 Unity 场景
- - '###'
  - 步骤 2：试试看！
- - '###'
  - 步骤 3：理解场景
- - '###'
  - 步骤 4：在应用程序中使用空间映射
- - '##'
  - 遮挡
- - '###'
  - 步骤 1：应用遮挡
- - '###'
  - 步骤 2：动手试试！
- - '##'
  - 场景理解
- - '##'
  - 总结
- - '#'
  - 第7章 空间音效
- - '##'
  - 空间音效教程
- - '###'
  - 步骤 1：设置 Unity 场景
- - '###'
  - 步骤 2：试试看！
- - '####'
  - 有趣的实验
- - '###'
  - 步骤 3：理解场景
- - '###'
  - 步骤 4：在应用程序中启用空间音效
- - '###'
  - 空间音效设计注意事项
- - '####'
  - 何时使用空间音效
- - '####'
  - 使用空间音效应避免什么
- - '##'
  - 总结
- - '#'
  - 第三部分：成长为全息开发者
- - '#'
  - 第8章 Azure Spatial Anchors
- - '##'
  - 什么是 Azure Spatial Anchors？
- - '##'
  - Azure Spatial Anchors 教程
- - '###'
  - 步骤 1：创建新的 Unity 场景
- - '###'
  - 步骤 2：安装内置 Unity 包
- - '###'
  - 步骤 3：下载并导入教程资源
- - '###'
  - 步骤 4：准备场景
- - '###'
  - 步骤 5：配置按钮以操作场景
- - '###'
  - 步骤 6：将场景连接到 Azure 资源
- - '###'
  - 步骤 7：在设备上测试应用程序
- - '##'
  - 总结
- - '#'
  - 第9章 共享体验
- - '##'
  - 什么是共享体验？
- - '##'
  - 多用户功能教程
- - '##'
  - 设置 Photon Unity 网络
- - '###'
  - 步骤 1：创建新的 Unity 场景
- - '###'
  - 步骤 2：启用附加功能
- - '###'
  - 步骤 3：安装 Unity 内置包
- - '###'
  - 步骤 4：导入教程资源
- - '###'
  - 步骤 5：导入 PUN 资源
- - '###'
  - 步骤 6：创建 PUN 应用程序
- - '###'
  - 步骤 7：将 Unity 项目连接到 PUN 应用程序
- - '##'
  - 连接多个用户
- - '###'
  - 步骤 1：准备场景
- - '###'
  - 步骤 2：创建并配置用户
- - '###'
  - 步骤 3：创建头像
- - '###'
  - 步骤 4：创建预制件
- - '###'
  - 步骤 5：配置 PUN 以实例化用户预制件
- - '##'
  - 与多用户共享物体移动
- - '###'
  - 步骤 1：准备场景
- - '###'
  - 步骤 2：配置 PUN 以实例化物体
- - '##'
  - 将 Azure 空间定位点集成到共享体验中
- - '###'
  - 步骤 1：准备场景
- - '###'
  - 步骤 2：配置按钮以操作场景
- - '###'
  - 步骤 3：将场景连接到 Azure 资源
- - '##'
  - 尝试空间对齐体验
- - '##'
  - 总结
- - '#'
  - 第10章 令人惊叹的体验
- - '##'
  - 什么造就了一款令人敬畏的应用？
- - '##'
  - 优化与性能
- - '###'
  - 如何监控性能
- - '###'
  - 性能最佳实践
- - '####'
  - 尽早开始监控和优化
- - '####'
  - 优化多边形与纹理
- - '####'
  - 细节层次渲染
- - '####'
  - 遮挡剔除
- - '####'
  - 启用单通道实例化渲染
- - '###'
  - 优化着色器
- - '###'
  - Simplygon
- - '###'
  - 稳定平面
- - '##'
  - 设计与魔法
- - '###'
  - 设计最佳实践
- - '####'
  - 空间映射
- - '####'
  - 与用户距离
- - '####'
  - 阴影
- - '####'
  - 语音
- - '####'
  - 清晰文字
- - '####'
  - 边界控制
- - '####'
  - 工具栏
- - '####'
  - 色彩
- - '####'
  - 应避免的设计体验
- - '####'
  - 更多资源
- - '###'
  - 增添魔力：Vuforia
- - '####'
  - 步骤 1：安装 Vuforia 示例
- - '####'
  - 步骤 2：试试看！
- - '##'
  - 总结
- - '#'
  - 第11章 将全息图变成金钱
- - '##'
  - 将您的应用发布到 Microsoft Store
- - '##'
  - 自由职业与合同
- - '##'
  - 如何寻找混合现实自由职业机会
- - '##'
  - 提高赢得合同的几率
- - '##'
  - 今天就是未来的机遇
- - '##'
  - 本章小结
- - '#'
  - 第12章 社区资源
- - '##'
  - HoloDevelopers Slack 团队
- - '###'
  - 什么是 Slack？
- - '###'
  - 什么是 HoloDevelopers Slack 团队？
- - '###'
  - 如何加入 HoloDevelopers Slack 团队
- - '###'
  - 参与 HoloDevelopers Slack 团队
- - '##'
  - 其他在线社区和资源
- - '###'
  - HoloLens 开发者 Facebook 群组
- - '###'
  - Unity 和 Unity HoloLens 论坛
- - '###'
  - HoloLens Subreddit
- - '###'
  - Next Reality News
- - '###'
  - YouTube
- - '##'
  - 本地活动与见面会
- - '###'
  - 欧洲见面会
- - '###'
  - 北美聚会
- - '###'
  - 亚太地区聚会
- - '##'
  - 黑客马拉松
- - '##'
  - 值得关注的行业活动
- - '##'
  - 总结
- - '#'
  - 索引
- - '##'
  - A
- - '##'
  - B
- - '##'
  - C
- - '##'
  - D
- - '##'
  - E
- - '##'
  - F
- - '##'
  - G
- - '##'
  - H
- - '##'
  - I, J, K
- - '##'
  - L
- - '##'
  - M
- - '##'
  - N
- - '##'
  - O
- - '##'
  - P, Q
- - '##'
  - R
- - '##'
  - S
- - '##'
  - T
- - '##'
  - U
- - '##'
  - V
- - '##'
  - W, X
- - '##'
  - Y, Z
