name: Pro iOS Continuous Integration
name_cn: iOS 持续集成高级指南
slug: pro-ios-continuous-integration
toc:
- - '#'
  - 第 1 章：持续集成简介
- - '##'
  - 什么是持续集成？
- - '###'
  - Apple 历史 101
- - '###'
  - 优点与缺点
- - '###'
  - 未来的道路
- - '#'
  - 第 2 章：iOS 和 Xcode 中的持续集成特性
- - '##'
  - 示例应用：Github Jobs
- - '###'
  - 创建应用
- - '###'
  - Xcode 提供了什么
- - '####'
  - 应用的 Info 文件
- - '##'
  - 测试
- - '##'
  - Git 集成
- - '##'
  - 如果这本书只能给你一条建议
- - '##'
  - iOS 和 Xcode 中的持续集成功能
- - '##'
  - CocoaPods
- - '##'
  - 编写示例应用
- - '##'
  - 安装 CocoaPods
- - '##'
  - 关于 `.gitignore` 文件
- - '##'
  - 我们为什么做这些？
- - '##'
  - 准备发布应用程序
- - '###'
  - 图 2-11. 现在已对使用 Adhoc 配置的构建启用了静态代码分析
- - '##'
  - 自定义构建设置
- - '###'
  - 图 2-12. 调试宏可用于 Debug 和 Adhoc 配置
- - '###'
  - 图 2-13. 我们的应用程序现在带有一个专用于 Github Jobs API 端点的新构建设置
- - '###'
  - 图 2-14. 应用程序清单现在包含了基于当前配置端点设置值的 URL 基础
- - '##'
  - 构建阶段
- - '###'
  - 图 2-15. 一个空项目带有一些必需的构建步骤
- - '##'
  - 比这更重要
- - '##'
  - 总结
- - '#'
  - 第 3 章：使用 Xcode 在 App Store 之外发布应用
- - '##'
  - 我们需要什么
- - '##'
  - 准备发布应用
- - '###'
  - 关于版本号
- - '##'
  - 从崩溃日志收集反馈
- - '###'
  - 创建 IPA 文件
- - '###'
  - 在测试者设备上安装应用程序
- - '###'
  - 安装应用的多个版本
- - '##'
  - 总结
- - '#'
  - 第 4 章：调用命令行的力量
- - '##'
  - 命令行界面？
- - '##'
  - 认识 Shenzhen
- - '##'
  - 处理多个 Xcode 安装
- - '##'
  - 构建应用程序
- - '###'
  - 使用 xcodebuild 构建应用程序
- - '###'
  - 使用 Xctool 构建应用
- - '###'
  - 使用 `xcpretty` 格式化 `xcodebuild` 输出
- - '##'
  - Xcode 项目文件剖析与方案共享
- - '##'
  - 从命令行创建 IPA 文件
- - '##'
  - 选择目标路径
- - '##'
  - 修改应用清单
- - '###'
  - 使用 Agvtool 提升构建版本
- - '##'
  - 总结与收官
- - '##'
  - 本章小结
- - '#'
  - 第 5 章：使用 Jenkins 进行自动化构建
- - '##'
  - 为什么我们需要自动化构建平台？
- - '##'
  - Jenkins 与 Hudson：一段历史
- - '##'
  - Jenkins 入门
- - '###'
  - 使用命令行安装 Jenkins
- - '###'
  - 在系统启动时加载 Jenkins
- - '##'
  - 初步了解
- - '##'
  - 调整 Jenkins 配置
- - '##'
  - 使用 Xcode 插件创建您的第一个 Jenkins 任务
- - '###'
  - 创建专用于 Github 的 SSH 密钥
- - '###'
  - 告知 Jenkins 使用这个全新的密钥
- - '####'
  - 构建 GitHub 任务应用
- - '####'
  - 归档生成的 IPA
- - '##'
  - Jenkins 高级用户功能
- - '###'
  - Jenkins REST API
- - '###'
  - 命令行中的 Jenkins
- - '##'
  - 获取反馈
- - '##'
  - 更新构建编号
- - '##'
  - 解锁钥匙串
- - '##'
  - 事后清理
- - '##'
  - 将 Xcode 构建集成到现有 Jenkins 安装中
- - '##'
  - 从节点基础
- - '##'
  - Jenkins 从节点的结构
- - '#'
  - 第 6 章：使用 Bamboo 实现自动化构建
- - '##'
  - 使用命令行安装 Bamboo
- - '##'
  - 为生产环境做准备
- - '##'
  - 环顾四周：与 Jenkins 不同的方法
- - '###'
  - 点击你选择的平台并填写凭据
- - '###'
  - 什么是计划？
- - '###'
  - 扩展 Bamboo
- - '###'
  - 什么是阶段？
- - '###'
  - 默认任务的配置
- - '##'
  - 总结 Bamboo 基础知识
- - '##'
  - 构建 Github Jobs 应用
- - '##'
  - 使用环境变量
- - '##'
  - 归档工件
- - '###'
  - 计划收尾与归档配置
- - '##'
  - Bamboo 高级用户功能
- - '###'
  - REST API
- - '###'
  - 仪表板
- - '###'
  - 获取反馈
- - '####'
  - 构建多个分支
- - '##'
  - 使用 Bamboo 设置钩子
- - '###'
  - ./postCommitBuildTrigger.py
- - '##'
  - 设置夜间构建
- - '###'
  - 练习：设置夜间构建
- - '##'
  - 将 Xcode 构建集成到现有的 Bamboo 安装中
- - '##'
  - 在上一章中
- - '##'
  - 安装远程代理
- - '##'
  - 配置代理
- - '##'
  - 更新作业以在远程代理上运行
- - '##'
  - 总结
- - '#'
  - 第 7 章：无线分发
- - '##'
  - 无线分发
- - '###'
  - 什么是无线分发？
- - '###'
  - 这与持续集成有何关系？
- - '###'
  - iOS 应用分发：一个可行的商业模式
- - '###'
  - 使用 TestFlight 分发应用
- - '###'
  - 使用 TestFlight 进行自动化 Beta 分发
- - '###'
  - 为 Jenkins 安装 TestFlight 插件
- - '###'
  - 配置 Github Jobs for iOS Jenkins 任务
- - '###'
  - 构建应用程序并将生成的 IPA 发送到 TestFlight
- - '####'
  - 上传到 TestFlight
- - '###'
  - 在 Bamboo 作业结束时将应用上传到 TestFlight
- - '####'
  - 更新默认作业配置
- - '###'
  - 创建部署任务
- - '##'
  - 空中分发（OTA）
- - '###'
  - 清单文件
- - '#'
  - 第 8 章：Xcode Server 与 Xcode Bots 的日常使用
- - '##'
  - OS X Server
- - '###'
  - 一点历史
- - '###'
  - 在你的计算机上安装 OS X Server
- - '##'
  - Xcode Bots 的日常使用
- - '###'
  - Xcode 6
- - '###'
  - 持续集成
- - '###'
  - 从 Xcode 与 Xcode 服务通信
- - '###'
  - 什么是 Bot？
- - '###'
  - 设置 Github Jobs
- - '###'
  - 使用 Xcode Bots 对 Github Jobs for iOS 进行每日构建
- - '####'
  - 授予对 GitHub 远程仓库的访问权限
- - '####'
  - 配置 Bot 并获取反馈
- - '###'
  - 在 Xcode Bot 执行的集成过程中安装依赖项
- - '###'
  - 从 Web 界面管理 Xcode 服务
- - '##'
  - OS X Server 与 Xcode Bots
- - '###'
  - 下载最新版应用程序
- - '###'
  - 使用大屏幕功能获取实时反馈
- - '##'
  - 总结
- - '#'
  - 第 9 章：将单元测试加入其中
- - '##'
  - 自动化测试
- - '###'
  - 测试的原因
- - '###'
  - 不测试的理由
- - '##'
  - 单元测试
- - '##'
  - Xcode 单元测试集成
- - '##'
  - 为 `PCSJobOffer` 类添加测试
- - '##'
  - 创建测试用例类
- - '##'
  - 添加单元测试
- - '##'
  - 运行测试
- - '##'
  - 从命令行运行测试
- - '##'
  - 分析结果
- - '##'
  - 从 Jenkins 运行测试
- - '##'
  - 从 Bamboo 运行测试
- - '##'
  - 使用 Xcode 机器人运行测试
- - '##'
  - 总结
- - '#'
  - 第 10 章：质量保证
- - '##'
  - 什么是质量保证？
- - '###'
  - 静态分析
- - '###'
  - 使用 clang 执行简单的静态分析
- - '####'
  - 从 Xcode Bot 执行静态分析
- - '###'
  - 使用 OCLint 获取额外反馈
- - '###'
  - 将 OCLint 集成到 Jenkins
- - '##'
  - 总结
- - '#'
  - 索引
- - '##'
  - A
- - '##'
  - C
- - '##'
  - D
- - '##'
  - G
- - '##'
  - J
- - '##'
  - L，M，N
- - '##'
  - M
- - '##'
  - Q
- - '##'
  - R
- - '##'
  - S
- - '##'
  - T
- - '##'
  - U、V、W
- - '#'
  - 附录
- - '##'
  - 关于作者
- - '##'
  - 关于技术审校者
- - '##'
  - 关于技术审校者（续）
- - '##'
  - 致谢
- - '##'
  - 致谢（续）
