name: Test-Driven Development in Swift
name_cn: Swift 测试驱动开发实战
slug: test-driven-development-in-swift
toc:
- - '#'
  - 送给你的礼物
- - '#'
  - 致谢
- - '#'
  - 关于作者 / 关于技术审稿人
- - '#'
  - 1. 为什么选择测试驱动开发？
- - '##'
  - 什么是测试？
- - '##'
  - 手动测试效率低下
- - '##'
  - 检验代码的代码
- - '##'
  - 单元测试、集成测试、UI 测试……天哪！
- - '##'
  - 从编写测试到先编写测试
- - '##'
  - 从先编写测试到测试驱动开发
- - '##'
  - 关键要点
- - '##'
  - 尾注
- - '#'
  - 2. `XCTest` 简介
- - '##'
  - Xcode 单元测试 Target
- - '##'
  - '`XCTestCase` 和相等性断言'
- - '##'
  - 其他断言
- - '##'
  - 解包可选值
- - '##'
  - 异步代码的期望
- - '##'
  - '`XCTestCase` 生命周期'
- - '##'
  - 关键要点
- - '#'
  - 3. 测试驱动开发入门
- - '##'
  - 测试列表
- - '##'
  - 伪装……直到成功
- - '##'
  - 安排、执行、断言
- - '##'
  - 先让测试通过；再让代码整洁
- - '##'
  - 编译器是 TDD 过程的一部分
- - '##'
  - 理想化编码（Wishful Coding）
- - '##'
  - 关键要点
- - '#'
  - 4. 真实世界中的测试驱动开发
- - '##'
  - 菜单点餐应用
- - '##'
  - 从哪里开始？
- - '##'
  - 问题分解与顺序解决
- - '##'
  - 构建菜单
- - '##'
  - 单元测试的严格断言与清晰断言
- - '##'
  - 尽可能使用最严格的断言
- - '##'
  - 尽可能使用最清晰的断言
- - '###'
  - 不要让测试崩溃
- - '###'
  - 测试命名约定
- - '###'
  - 红、绿，别忘重构
- - '##'
  - 连接用户界面
- - '##'
  - 纯函数
- - '##'
  - 关键要点
- - '#'
  - 5. 使用 Fixtures 变更测试
- - '##'
  - 源码变更的隐藏成本
- - '##'
  - 固定装置（Fixtures）
- - '##'
  - 固定装置（Fixtures）与便利初始化器（Convenience Initializers）
- - '##'
  - 固定装置（Fixtures）使测试的行动者（Actors）更明确
- - '##'
  - 固定装置（Fixtures）是可组合的
- - '##'
  - 尽早引入固定装置（Fixtures）
- - '##'
  - 练习时间
- - '##'
  - 要点总结
- - '##'
  - 尾注
- - '#'
  - 6. 测试静态 SwiftUI 视图
- - '##'
  - 视图层呈现逻辑的问题
- - '##'
  - 从视图实现中解耦呈现逻辑
- - '##'
  - 预备重构：缩小工作范围
- - '##'
  - ViewModel
- - '##'
  - 在视图中使用 ViewModel
- - '##'
  - 超越可测试性
- - '##'
  - ViewModel 无处不在！
- - '##'
  - 依赖注入
- - '##'
  - 关键要点
- - '##'
  - 尾注
- - '#'
  - 7. 测试动态 SwiftUI 视图
- - '##'
  - SwiftUI 与 Combine 如何实现无缝视图更新
- - '##'
  - 使用 `ObservableObject` 让 ViewModel 流式更新
- - '##'
  - 依赖倒置原则
- - '##'
  - 依赖倒置 vs. 依赖注入
- - '##'
  - 用 DIP 将 ViewModel 与数据获取解耦
- - '##'
  - 测试 `@Published` 属性的异步更新
- - '##'
  - 神秘访客
- - '##'
  - 练习时间
- - '##'
  - 关键要点
- - '#'
  - 8. 测试基于间接输入的代码
- - '##'
  - 桩测试替身
- - '###'
  - 使用 `Result` 显式处理错误
- - '##'
  - 练习时间
- - '##'
  - 关键要点
- - '#'
  - 9. 测试 JSON 解码
- - '##'
  - 选项 1：内联字符串
- - '##'
  - 选项 2：JSON 文件
- - '##'
  - 该选择哪个选项？
- - '##'
  - 测试 JSON 解码值得吗？
- - '##'
  - 实践时间
- - '##'
  - 关键要点
- - '##'
  - 尾注
- - '#'
  - 10. 测试网络代码
- - '##'
  - 为什么不应在单元测试中发起网络请求
- - '##'
  - 根据变量值进行测试的局限
- - '##'
  - 强制解包可选值
- - '##'
  - 如何将单元测试与网络解耦
- - '##'
  - 使用桩模拟网络请求
- - '###'
  - 第三方替代方案
- - '##'
  - 练习时间
- - '##'
  - 关键要点
- - '##'
  - 尾注
- - '#'
  - 11. 使用 `@EnvironmentObject` 注入依赖
- - '##'
  - 依赖注入如何保持每个测试的独立性
- - '###'
  - 依赖注入 vs. 直接访问共享实例
- - '###'
  - 使用 `@EnvironmentObject` 进行依赖注入
- - '###'
  - '`@EnvironmentObject` 的缺点'
- - '###'
  - '`@EnvironmentObject` 与直接访问共享实例'
- - '##'
  - 练习时间
- - '##'
  - 关键要点
- - '#'
  - 12. 测试副作用
- - '##'
  - 第三方依赖与其他所有依赖相同
- - '##'
  - 抽象化第三方依赖的好处
- - '##'
  - 为第三方依赖构建包装器
- - '##'
  - 间谍测试替身
- - '##'
  - 使用 Spy 的缺点
- - '##'
  - 练习时间
- - '##'
  - 关键要点
- - '#'
  - 13. 测试条件性视图展示
- - '##'
  - 告知用户结账完成
- - '##'
  - 如何在没有回调时测试异步代码
- - '##'
  - 连接视图
- - '##'
  - 测试警告框关闭行为
- - '##'
  - 关键要点
- - '##'
  - 使用 TDD 修复 Bug 和更改现有代码
- - '##'
  - 通过测试驱动修复 Bug
- - '##'
  - 通过测试驱动修改现有代码
- - '##'
  - 关键要点
- - '#'
  - 14. 使用假件保持测试隔离，使用傀儡保持测试清晰
- - '##'
  - 假对象（Fake）：如何绕过缓慢或有状态的依赖
- - '##'
  - 哑对象（Dummy）：如何提供测试所需但与行为无关的依赖
- - '##'
  - 关键要点
- - '#'
  - 15. 结论
- - '##'
  - 不仅仅是测试
- - '##'
  - TDD 与软件设计
- - '##'
  - 测试驱动开发（TDD）与生产力
- - '##'
  - TDD 与产品开发
- - '##'
  - 尾注
- - '#'
  - A
- - '##'
  - API 集成测试
- - '##'
  - AppKit
- - '##'
  - 异步代码
- - '#'
  - B
- - '##'
  - 错误
- - '#'
  - C
- - '##'
  - 更改现有行为
- - '##'
  - 使用 TDD 更改现有代码
- - '##'
  - Combine
- - '##'
  - 条件视图展示
- - '##'
  - 持续集成 (CI)
- - '##'
  - 便捷初始化器
- - '#'
  - D
- - '##'
  - 依赖注入 (DI)
- - '##'
  - 依赖倒置原则 (DIP)
- - '##'
  - 虚拟文件
- - '##'
  - 动态测试过程
- - '#'
  - E
- - '##'
  - '`@EnvironmentObject`'
- - '##'
  - 现有代码
- - '#'
  - F, G, H
- - '##'
  - 伪造测试替身
- - '##'
  - 使用 TDD 修复错误
- - '##'
  - 测试夹具
- - '#'
  - I
- - '##'
  - 间接输入
- - '#'
  - J, K, L
- - '##'
  - JSON 解码
- - '#'
  - M
- - '##'
  - 菜单排序应用
- - '#'
  - N
- - '##'
  - NetworkFetching
- - '#'
  - O
- - '##'
  - '`ObservableObject`'
- - '##'
  - 可选 `XCTUnwrap`
- - '#'
  - P
- - '##'
  - '`@Published` 属性'
- - '#'
  - Q
- - '##'
  - Quick 和 Nimble
- - '#'
  - R
- - '##'
  - 现实世界应用
- - '#'
  - S
- - '##'
  - 副作用
- - '##'
  - 快照测试
- - '##'
  - 间谍测试替身
- - '##'
  - 桩测试替身
- - '##'
  - SwiftLint
- - '##'
  - SwiftUI
- - '#'
  - T
- - '##'
  - 测试 Combine 发布者
- - '##'
  - 测试替身
- - '##'
  - 测试驱动开发 (TDD)
- - '#'
  - U
- - '##'
  - UIKit 开发
- - '##'
  - 单元测试
- - '##'
  - 用户界面 (UI) 测试
- - '#'
  - V, W
- - '##'
  - ViewModel
- - '#'
  - X, Y, Z
- - '##'
  - Xcode
- - '##'
  - XCTest
