name: Practical Android 4 Games Development
name_cn: Android 4 游戏开发实战指南
slug: practical-android-4-games-development
toc:
- - '#'
  - 开始 Android 4 游戏开发
- - '##'
  - 内容速览
- - '#'
  - 目录
- - '##'
  - 第 1 章：Android，新秀登场
- - '##'
  - 第 2 章：Android SDK 初探
- - '##'
  - 第 3 章：游戏开发基础
- - '##'
  - 第 4 章：面向游戏开发者的 Android
- - '##'
  - 关于作者
- - '##'
  - 引言
- - '###'
  - 关于目标读者的一点说明
- - '###'
  - 本书的组织结构
- - '###'
  - 获取源代码
- - '##'
  - 第 1 章 Android，新生的力量
- - '###'
  - Android 简史
- - '###'
  - Android 版本演进
- - '###'
  - 碎片化
- - '###'
  - Google 的角色
- - '###'
  - Android 开源项目
- - '###'
  - Android 市场
- - '###'
  - 挑战赛、设备赠送与 Google I/O
- - '###'
  - Android 的特性与架构
- - '####'
  - 内核
- - '####'
  - 运行时与 Dalvik
- - '####'
  - 系统库
- - '####'
  - 应用程序框架
- - '###'
  - 软件开发工具包
- - '###'
  - 开发者社区
- - '###'
  - 设备，设备，设备！
- - '####'
  - 硬件
- - '####'
  - 设备范围
- - '#####'
  - 最低实用目标
- - '###'
  - 前沿设备
- - '###'
  - 未来：下一代
- - '###'
  - 游戏手柄
- - '###'
  - 全设备兼容性
- - '###'
  - 移动游戏与众不同
- - '####'
  - 口袋里的游戏机
- - '####'
  - 始终在线
- - '###'
  - 休闲玩家与硬核玩家
- - '###'
  - 大市场，小开发者
- - '###'
  - 小结
- - '#'
  - 第 2 章 Android SDK 初步上手
- - '##'
  - 搭建开发环境
- - '###'
  - 安装 JDK
- - '###'
  - 设置 Android SDK
- - '###'
  - 安装 Eclipse
- - '###'
  - 安装 ADT Eclipse 插件
- - '###'
  - Eclipse 快速导览
- - '####'
  - 实用的 Eclipse 快捷键
- - '###'
  - 你好，世界：Android 风格
- - '####'
  - 创建项目
- - '####'
  - 探索项目
- - '###'
  - 编写应用代码
- - '##'
  - 运行和调试 Android 应用
- - '###'
  - 连接设备
- - '###'
  - 创建安卓虚拟设备
- - '###'
  - 运行应用程序
- - '###'
  - 调试应用程序
- - '####'
  - '`LogCat` 与 `DDMS`'
- - '##'
  - 使用 ADB
- - '###'
  - 摘要
- - '##'
  - 第 3 章 游戏开发入门
- - '###'
  - 游戏类型：各有所爱
- - '####'
  - 休闲游戏
- - '####'
  - 益智游戏
- - '####'
  - 动作与街机游戏
- - '####'
  - 塔防游戏
- - '###'
  - 创新
- - '###'
  - 游戏设计：笔胜于代码
- - '####'
  - 核心游戏机制
- - '####'
  - 故事与美术风格
- - '####'
  - 屏幕与转场
- - '###'
  - 代码：关键细节
- - '####'
  - 应用与窗口管理
- - '####'
  - 输入
- - '####'
  - 文件 I/O
- - '####'
  - 音频
- - '#####'
  - 声音的物理原理
- - '#####'
  - 录音与回放
- - '#####'
  - 音频质量与压缩
- - '####'
  - 图形
- - '#####'
  - 关于光栅、像素和帧缓冲
- - '#####'
  - 垂直同步与双缓冲
- - '#####'
  - 图像格式与压缩
- - '#####'
  - Alpha 合成与混合
- - '###'
  - 实践
- - '##'
  - 游戏框架
- - '####'
  - 游戏循环与界面设计
- - '####'
  - 游戏和屏幕接口
- - '####'
  - 屏幕抽象类
- - '####'
  - 一个简单示例
- - '####'
  - 帧率无关运动
- - '###'
  - 总结
- - '##'
  - 第 4 章 面向游戏开发者的 Android 开发指南
- - '###'
  - 定义 Android 应用程序：清单文件
- - '####'
  - '`<manifest>` 元素'
- - '####'
  - 应用元素
- - '####'
  - '`<activity>` 元素'
- - '####'
  - '`<uses-permission>`元素'
- - '####'
  - '`<uses-feature>` 元素'
- - '####'
  - '`<uses-sdk>` 元素'
- - '###'
  - 十步轻松完成安卓游戏项目设置
- - '###'
  - 市场过滤器
- - '###'
  - 定义游戏的图标
- - '###'
  - Android API 基础
- - '####'
  - 创建一个测试项目
- - '###'
  - '`AndroidBasicsStarter` Activity'
- - '###'
  - 以编程方式启动活动
- - '###'
  - 创建测试活动
- - '###'
  - 活动生命周期
- - '####'
  - 理论解析
- - '####'
  - 实践环节
- - '###'
  - 输入设备处理
- - '####'
  - 获取（多点）触摸事件
- - '#####'
  - 处理单点触控事件
- - '#####'
  - 处理多点触控事件
- - '#####'
  - 指针 ID 与索引
- - '#####'
  - 动作掩码与更多事件类型
- - '#####'
  - 实践应用
- - '####'
  - 处理按键事件
- - '####'
  - 读取加速度计状态
- - '###'
  - 排版后的内容
- - '####'
  - 读取指南针状态
- - '###'
  - 文件处理
- - '####'
  - 读取资源文件
- - '####'
  - 访问外部存储
- - '###'
  - 音频编程
- - '####'
  - 设置音量控制
- - '####'
  - 播放音效
- - '####'
  - 流式音乐播放
- - '###'
  - 基础图形编程
- - '####'
  - 使用唤醒锁
- - '####'
  - 进入全屏模式
- - '####'
  - UI 线程中的持续渲染
- - '####'
  - 获取屏幕分辨率（及坐标系）
- - '####'
  - 绘制简单形状
- - '#####'
  - 绘制像素
- - '#####'
  - 绘制直线
- - '#####'
  - 绘制矩形
- - '#####'
  - 绘制圆形
- - '#####'
  - 综合实践
- - '####'
  - 使用位图
- - '#####'
  - 加载与检查位图
- - '#####'
  - 释放位图
- - '#####'
  - 绘制位图
- - '#####'
  - 整合所有内容
- - '####'
  - 渲染文本
- - '#####'
  - 加载字体
- - '#####'
  - 使用字体绘制文本
- - '#####'
  - 文本对齐与边界
- - '#####'
  - 整合应用
- - '####'
  - 使用 SurfaceView 进行持续渲染
- - '#####'
  - 动机
- - '#####'
  - SurfaceHolder 与锁定
- - '#####'
  - 表面创建与有效性
- - '#####'
  - 整合所有部分
- - '###'
  - 排版后内容
- - '####'
  - 使用 Canvas 的硬件加速渲染
- - '###'
  - 最佳实践
- - '###'
  - 总结
- - '##'
  - 第 5 章 一个 Android 游戏开发框架
- - '###'
  - 行动计划
- - '###'
  - AndroidFileIO 类
- - '###'
  - AndroidAudio、AndroidSound 与 AndroidMusic：碰撞、轰鸣、巨响！
- - '###'
  - AndroidInput 和 AccelerometerHandler
- - '####'
  - AccelerometerHandler：哪面朝上？
- - '####'
  - CompassHandler
- - '###'
  - Pool 类：复用对你有益！
- - '###'
  - '`KeyboardHandler`：上上下下左右左右……'
- - '##'
  - 触摸处理器
- - '###'
  - TouchHandler 接口
- - '###'
  - '`SingleTouchHandler` 类'
- - '###'
  - MultiTouchHandler（多点触控处理器）
- - '###'
  - AndroidInput：伟大的协调者
- - '##'
  - AndroidGraphics 与 AndroidPixmap：双重彩虹
- - '###'
  - 处理不同的屏幕尺寸和分辨率
- - '####'
  - 密度
- - '###'
  - 宽高比
- - '####'
  - 应对不同的宽高比
- - '####'
  - 一个更简单的解决方案
- - '###'
  - 实现方案
- - '###'
  - AndroidPixmap：为大众服务的像素
- - '####'
  - AndroidGraphics：满足绘图需求
- - '####'
  - AndroidFastRenderView：循环、拉伸、循环、拉伸
- - '###'
  - AndroidGame：整合所有功能
- - '###'
  - 总结
- - '##'
  - 第 6 章 Mr. Nom 入侵 Android
- - '###'
  - 创建资源
- - '###'
  - 设置项目
- - '###'
  - MrNomGame：主 Activity
- - '###'
  - Assets：便捷的资源存储
- - '###'
  - 设置：追踪用户选择与最高分
- - '###'
  - '`LoadingScreen`：从磁盘获取资源'
- - '###'
  - 主菜单界面
- - '###'
  - '`HelpScreen` 类（系列）'
- - '###'
  - 高分屏幕
- - '####'
  - 渲染数字：深入探讨
- - '###'
  - 实现屏幕（Screen）
- - '###'
  - 抽象化……
- - '####'
  - 抽象化「Nom 先生」的世界：模型、视图、控制器
- - '###'
  - 污渍类
- - '###'
  - '`Snake` 和 `SnakePart` 类'
- - '###'
  - World 类
- - '####'
  - 基于时间的 Mr. Nom 运动
- - '####'
  - 放置污渍
- - '####'
  - 判断游戏何时结束
- - '###'
  - 实现世界类
- - '###'
  - '`GameScreen` 类'
- - '###'
  - 总结
- - '#'
  - 第 7 章 OpenGL ES：温和入门
- - '###'
  - 什么是 OpenGL ES，为什么我要关心它？
- - '####'
  - 编程模型：一个类比
- - '####'
  - 投影
- - '###'
  - 标准化设备空间与视口
- - '###'
  - 矩阵
- - '###'
  - 渲染管线
- - '###'
  - 开始之前
- - '###'
  - GLSurfaceView：从 2008 年起让事情变简单
- - '###'
  - GLGame：实现游戏接口
- - '###'
  - 看，我有了一个红色三角形！
- - '####'
  - 定义视口
- - '####'
  - 定义投影矩阵
- - '#####'
  - 矩阵模式与活动矩阵
- - '#####'
  - 使用 `glOrthof` 进行正交投影
- - '###'
  - 实用代码片段
- - '###'
  - 指定三角形
- - '####'
  - 关于 NIO 缓冲区的小插曲
- - '#####'
  - 向 OpenGL ES 发送顶点数据
- - '####'
  - 整合
- - '###'
  - 指定逐顶点颜色
- - '##'
  - 纹理映射：贴墙纸如此简单
- - '###'
  - 纹理坐标
- - '####'
  - 上传位图
- - '####'
  - 纹理过滤
- - '####'
  - 处理纹理
- - '####'
  - 一段实用的代码片段
- - '####'
  - 启用纹理
- - '####'
  - 综合运用
- - '###'
  - 纹理类
- - '###'
  - 索引顶点：重用对你有利
- - '####'
  - 综合分析
- - '####'
  - Vertices 类
- - '##'
  - Alpha 混合：我能看穿你
- - '###'
  - '`BlendingScreen` 类实现'
- - '##'
  - 更多图元：点、线、条带和扇形
- - '##'
  - 二维变换：模型-视图矩阵的乐趣
- - '###'
  - 世界空间与模型空间
- - '###'
  - 再次认识矩阵
- - '###'
  - 使用平移的初步示例
- - '####'
  - Bob 成为一个类
- - '####'
  - 整合起来
- - '##'
  - 更多变换
- - '###'
  - 旋转
- - '###'
  - 缩放
- - '###'
  - 组合变换
- - '##'
  - 性能优化
- - '###'
  - 测量帧率
- - '###'
  - Hero 上的 Android 1.5 奇案
- - '###'
  - 是什么让我的 OpenGL ES 渲染如此缓慢？
- - '###'
  - 移除不必要的状态变更
- - '###'
  - 减小纹理尺寸意味着需要获取的像素更少
- - '###'
  - 减少 OpenGL ES/JNI 方法的调用次数
- - '####'
  - 绑定顶点的概念
- - '####'
  - 本章小结
- - '###'
  - 总结
- - '##'
  - 第 8 章 2D 游戏编程技巧
- - '###'
  - 开始之前
- - '###'
  - 最初……向量的诞生
- - '###'
  - 向量运算
- - '###'
  - 一点三角学
- - '###'
  - 实现一个向量类
- - '####'
  - 一个简单的使用示例
- - '##'
  - 二维中的一点物理知识
- - '###'
  - 牛顿与欧拉，永远的挚友
- - '###'
  - 力与质量
- - '###'
  - 理论上的模拟练习
- - '###'
  - 实践中的模拟练习
- - '##'
  - 二维空间中的碰撞检测与物体表示
- - '###'
  - 包围形状
- - '###'
  - 构建包围形状
- - '###'
  - 游戏对象属性
- - '###'
  - 宽相位与窄相位碰撞检测
- - '##'
  - 窄相位
- - '###'
  - 圆形碰撞
- - '###'
  - 矩形碰撞
- - '###'
  - 圆与矩形碰撞
- - '###'
  - 整合所有内容
- - '####'
  - 粗测阶段
- - '####'
  - 详细示例
- - '#####'
  - GameObject、DynamicGameObject 和 Cannon
- - '###'
  - 空间哈希网格
- - '#####'
  - 整合所有内容
- - '##'
  - 2D 世界中的摄像机
- - '###'
  - Camera2D 类
- - '###'
  - 示例
- - '##'
  - 纹理图集：因为共享即是关爱
- - '###'
  - 示例
- - '##'
  - 纹理区域、精灵和批处理：隐藏 OpenGL ES
- - '###'
  - TextureRegion 类
- - '###'
  - '`SpriteBatcher` 类'
- - '##'
  - 方法详解
- - '###'
  - 使用 `SpriteBatcher` 类
- - '###'
  - 性能测量
- - '###'
  - 规避 `FloatBuffer` 中的一个 Bug
- - '##'
  - 精灵动画
- - '###'
  - 动画类
- - '###'
  - 一个示例
- - '###'
  - 总结
- - '##'
  - 第 9 章 《超级跳跃者》：一款 2D OpenGL ES 游戏
- - '###'
  - 核心游戏机制
- - '###'
  - 背景故事与美术风格
- - '###'
  - 屏幕与界面切换
- - '###'
  - 定义游戏世界
- - '###'
  - 创建资源
- - '###'
  - UI 元素
- - '###'
  - 使用位图字体处理文本
- - '####'
  - 游戏元素
- - '####'
  - 纹理图集来帮忙
- - '####'
  - 音乐与音效
- - '###'
  - 实现《超级跳跃者》
- - '###'
  - 资源类
- - '####'
  - Settings 类
- - '####'
  - 主 Activity
- - '###'
  - Font 类
- - '###'
  - GLScreen
- - '###'
  - 主菜单界面
- - '####'
  - 帮助屏幕
- - '####'
  - 高分榜界面
- - '####'
  - 模拟类
- - '##'
  - 弹簧类
- - '##'
  - 金币类
- - '##'
  - 城堡类
- - '##'
  - 松鼠类
- - '###'
  - 平台类
- - '###'
  - Bob 类
- - '###'
  - 代码清单 9–13. `Bob.java`
- - '#####'
  - 世界类
- - '#####'
  - 生成世界
- - '###'
  - 更新世界
- - '######'
  - 碰撞检测与响应
- - '######'
  - 游戏结束，伙计！
- - '###'
  - 游戏界面
- - '###'
  - 更新 `GameScreen`
- - '###'
  - 渲染游戏界面
- - '###'
  - 收尾工作
- - '##'
  - WorldRenderer 类
- - '###'
  - 优化还是不优化
- - '###'
  - 总结
- - '##'
  - 第 10 章 OpenGL ES：迈向 3D
- - '###'
  - 开始之前
- - '###'
  - 3D 中的顶点
- - '####'
  - 示例
- - '###'
  - 透视投影：近大远小
- - '###'
  - Z-缓存：为混沌带来秩序
- - '####'
  - 修复上一个示例
- - '###'
  - 混合：你身后空无一物
- - '###'
  - Z 缓存精度与 Z 冲突
- - '##'
  - 定义三维网格
- - '###'
  - 一个立方体：3D 世界中的 Hello World
- - '###'
  - 原始内容排版
- - '####'
  - 一个示例
- - '###'
  - 矩阵与变换再探
- - '####'
  - 矩阵栈
- - '####'
  - 使用矩阵栈的层级系统
- - '#####'
  - 一个简单的板条箱太阳系
- - '###'
  - HierarchicalObject 类
- - '###'
  - 综合应用
- - '###'
  - 简易相机系统
- - '##'
  - 总结
- - '#'
  - 第 11 章 3D 编程技巧
- - '###'
  - 开始之前
- - '###'
  - 三维向量
- - '##'
  - OpenGL ES 中的光照
- - '###'
  - 光照的工作原理
- - '###'
  - 光源
- - '###'
  - 材质
- - '###'
  - OpenGL ES 如何计算光照：顶点法线
- - '##'
  - 实践环节
- - '###'
  - 启用与禁用光照
- - '###'
  - 指定光源
- - '####'
  - 环境光
- - '###'
  - 点光源
- - '###'
  - 方向光
- - '#####'
  - 指定材质
- - '#####'
  - 指定法线
- - '###'
  - 整合所有内容
- - '##'
  - OpenGL ES 中光照的一些说明
- - '###'
  - 多级渐远纹理
- - '##'
  - 简单相机
- - '###'
  - 第一人称或欧拉相机
- - '###'
  - 排版后的内容
- - '####'
  - 欧拉摄像机示例
- - '###'
  - 代码示例与排版说明
- - '##'
  - 构造函数部分
- - '##'
  - '`createCube()`与`resume()`方法'
- - '##'
  - '`update()`方法'
- - '##'
  - '`present()`方法'
- - '###'
  - 观察摄像机
- - '###'
  - 加载模型
- - '###'
  - Wavefront OBJ 格式
- - '###'
  - 实现 OBJ 加载器
- - '###'
  - 使用 OBJ 加载器
- - '###'
  - 3D 中的简单物理
- - '###'
  - 3D 中的碰撞检测与对象表示
- - '####'
  - 3D 中的包围形状
- - '###'
  - 包围球重叠检测
- - '##'
  - GameObject3D 和 DynamicGameObject3D
- - '##'
  - 总结
- - '#'
  - 第 12 章：Droid Invaders：最终章
- - '###'
  - 核心游戏机制
- - '###'
  - 故事背景与美术风格
- - '###'
  - 屏幕与过渡
- - '###'
  - 定义游戏世界
- - '###'
  - 创建资源
- - '####'
  - UI 素材
- - '####'
  - 游戏素材
- - '####'
  - 音效与音乐
- - '###'
  - 行动计划
- - '###'
  - 资产类
- - '###'
  - '`Settings` 类'
- - '###'
  - 主活动
- - '###'
  - 主菜单界面
- - '###'
  - 设置界面
- - '###'
  - 模拟类
- - '###'
  - 护盾类
- - '###'
  - 子弹类
- - '###'
  - 飞船类
- - '###'
  - 侵略者类
- - '###'
  - 世界类
- - '###'
  - '`GameScreen` 类'
- - '###'
  - WorldRender 类
- - '##'
  - 优化
- - '##'
  - 总结
- - '##'
  - 第 13 章 发布你的游戏
- - '###'
  - 关于测试的一点说明
- - '###'
  - 成为注册开发者
- - '###'
  - 签署游戏的 APK
- - '###'
  - 将游戏发布到市场
- - '####'
  - 上传资源
- - '###'
  - 产品详情
- - '###'
  - 发布选项
- - '###'
  - 发布！
- - '###'
  - 市场营销
- - '###'
  - 开发者控制台
- - '###'
  - 总结
- - '##'
  - 第 14 章 接下来做什么？
- - '###'
  - 社交互动
- - '###'
  - 位置感知
- - '###'
  - 多人游戏功能
- - '###'
  - OpenGL ES 2.0 及更多
- - '###'
  - 框架与引擎
- - '###'
  - 网络资源
- - '###'
  - 结束语
- - '##'
  - 索引
- - '###'
  - 数字与特殊字符
- - '###'
  - A
- - '###'
  - B
- - '###'
  - C
- - '###'
  - D
- - '####'
  - 调试
- - '####'
  - 设备
- - '#####'
  - 尖端设备
- - '#####'
  - 下一代设备
- - '####'
  - Droid Invaders 游戏
- - '#####'
  - 模拟类
- - '###'
  - E
- - '###'
  - F
- - '###'
  - G
- - '####'
  - 图片与图形
- - '#####'
  - 颜色
- - '#####'
  - 渲染
- - '#####'
  - 接口与方法
- - '###'
  - H
- - '###'
  - I
- - '###'
  - J
- - '###'
  - K
- - '###'
  - L
- - '###'
  - M
- - '###'
  - N
- - '###'
  - O
- - '###'
  - P, Q
- - '###'
  - R
- - '###'
  - S
- - '###'
  - '`targets.size()` 方法，403，414，424'
- - '###'
  - U
- - '###'
  - V
- - '###'
  - W
- - '###'
  - X, Y
- - '###'
  - Z
