name: Beginning iPhone Development with Swift 3
name_cn: Swift 3 的 iPhone 开发入门指南
slug: beginning-iphone-development-with-swift-3
toc:
- - '#'
  - 目录
- - '##'
  - 致谢
- - '#'
  - 第 1 章：认识 iOS 开发生态 1
- - '#'
  - 第 2 章：编写第一个 App 13
- - '#'
  - 第 3 章：基本用户交互 51
- - '#'
  - 第 4 章：添加中级用户交互 87
- - '#'
  - 第 5 章：处理设备旋转 129
- - '#'
  - 第 6 章：创建多视图应用程序 179
- - '#'
  - 第 7 章：使用标签栏和选择器 209
- - '#'
  - 第 8 章：介绍表视图 255
- - '#'
  - 第 9 章：为表视图添加导航控制器 309
- - '#'
  - 第 10 章：集合视图 343
- - '#'
  - 第 11 章：iPad 应用的拆分视图和弹出窗口 357
- - '#'
  - 第 12 章：通过设置和默认值进行应用自定义 383
- - '#'
  - 第 13 章：持久化：在应用启动之间保存数据 421
- - '#'
  - 第 14 章：文档和 iCloud 467
- - '#'
  - 第 15 章：使用 Grand Central Dispatch 进行多线程编程 499
- - '#'
  - 第 16 章：图形与绘制 529
- - '#'
  - 第 17 章：使用 SpriteKit 的简单游戏 555
- - '#'
  - 第 18 章：点击、触摸和手势 597
- - '#'
  - 第 19 章：确定位置 621
- - '#'
  - 第 20 章：设备朝向与运动 641
- - '#'
  - 第 21 章：使用相机和访问照片 663
- - '#'
  - 第 22 章：使用本地化翻译应用 677
- - '#'
  - 附录 A：Swift 入门 703
- - '##'
  - 关于作者与关于技术审校者
- - '###'
  - 关于作者
- - '###'
  - 关于技术审校者
- - '#'
  - 1. 初识 iOS 开发生态
- - '##'
  - 关于本书
- - '##'
  - 你需要准备的事项
- - '###'
  - SDK 版本与示例源代码
- - '###'
  - 开发者的选择
- - '###'
  - 你需要了解的基础
- - '###'
  - iOS 开发的一些独特之处
- - '####'
  - iOS 通常一次仅支持一个应用程序
- - '####'
  - 只有一个窗口
- - '####'
  - 为安全起见，设备资源的访问受到限制
- - '####'
  - 应用需要快速响应
- - '####'
  - 有限的屏幕尺寸
- - '####'
  - 有限的设备资源
- - '####'
  - iOS 设备独有的特性
- - '####'
  - 用户输入与显示
- - '##'
  - 本书内容
- - '###'
  - 本次更新有哪些新内容？
- - '###'
  - Swift 与 Xcode 版本
- - '###'
  - 让我们开始吧
- - '#'
  - 编写我们的第一个应用
- - '##'
  - 创建 Hello World 项目
- - '###'
  - Xcode 项目窗口
- - '####'
  - 工具栏
- - '####'
  - 导航器
- - '####'
  - 跳转栏
- - '####'
  - Xcode 键盘快捷键
- - '####'
  - 工具区
- - '####'
  - 界面生成器
- - '####'
  - 集成编译器和调试器
- - '###'
  - 深入剖析 Hello World 项目
- - '###'
  - 介绍 Xcode 的 Interface Builder
- - '####'
  - 文件格式
- - '###'
  - 故事板
- - '###'
  - 工具区
- - '###'
  - 为视图添加标签
- - '###'
  - 更改属性
- - '##'
  - 收尾工作
- - '##'
  - 启动屏幕
- - '##'
  - 在设备上运行应用
- - '##'
  - 排版后的文本
- - '##'
  - 本章小结
- - '#'
  - 3. 基本用户交互
- - '##'
  - MVC 范式
- - '##'
  - 创建 ButtonFun 应用
- - '##'
  - ViewController（视图控制器）
- - '##'
  - 输出口（Outlets）与操作（Actions）
- - '###'
  - 输出口（Outlets）
- - '####'
  - 操作
- - '###'
  - 简化视图控制器
- - '###'
  - 设计用户界面
- - '###'
  - 添加按钮与操作方法
- - '##'
  - 添加标签和输出口
- - '##'
  - 自动引用计数
- - '####'
  - 编写操作方法
- - '###'
  - 测试 ButtonFun 应用
- - '####'
  - 使用自动布局修复问题
- - '###'
  - 预览布局
- - '###'
  - 更改文本样式
- - '##'
  - 检查应用委托
- - '##'
  - 总结
- - '#'
  - 4. 添加中级用户交互
- - '##'
  - 主动、静态和被动控件
- - '##'
  - 创建 Control Fun 应用
- - '##'
  - 实现图像视图和文本字段
- - '###'
  - 添加图像视图
- - '###'
  - 调整图像视图大小
- - '###'
  - 设置视图属性
- - '####'
  - Mode 属性
- - '####'
  - Semantic 属性
- - '####'
  - Tag
- - '####'
  - 交互复选框
- - '####'
  - Alpha 值
- - '####'
  - 背景
- - '####'
  - 色调
- - '####'
  - 绘制复选框
- - '####'
  - 拉伸
- - '###'
  - 添加文本字段
- - '##'
  - 文本字段检查器设置
- - '####'
  - 设置第二个文本字段的属性
- - '###'
  - 添加约束
- - '###'
  - 创建并连接插座
- - '##'
  - 关闭键盘
- - '###'
  - 点击“完成”时关闭键盘
- - '###'
  - 点击背景关闭键盘
- - '###'
  - 添加滑块和标签
- - '###'
  - 创建并连接操作和插座
- - '###'
  - 实现操作（Action）方法
- - '##'
  - 实现开关、按钮和分段控件
- - '###'
  - 添加两个带标签的开关
- - '###'
  - 连接并创建 Outlets 和 Actions
- - '###'
  - 实现开关 Actions
- - '####'
  - 添加按钮
- - '####'
  - 向按钮添加图片
- - '##'
  - 可拉伸图像
- - '###'
  - 控件状态
- - '###'
  - 连接和创建按钮的 Outlet 和 Action
- - '##'
  - 实现分段控件操作
- - '##'
  - 实现操作表和警告框
- - '###'
  - 显示操作列表
- - '###'
  - 显示警告框
- - '##'
  - 本章小结
- - '#'
  - 5. 处理设备旋转
- - '##'
  - 旋转机制
- - '###'
  - 点、像素与 Retina 显示屏
- - '###'
  - 处理旋转
- - '##'
  - 创建我们的方向项目
- - '###'
  - 应用级别的支持方向
- - '###'
  - 逐控制器旋转支持
- - '###'
  - 代码补全的实际应用
- - '##'
  - 创建布局项目
- - '##'
  - 覆盖默认约束
- - '##'
  - 全宽标签
- - '##'
  - 创建自适应布局
- - '###'
  - 创建 Restructure 应用程序
- - '##'
  - Auto Layout 配置中的宽高表示法
- - '###'
  - 设置 iPhone 横屏（wC hC）配置
- - '###'
  - 设置 iPad（iPhone Plus 横屏）(wR hR) 配置
- - '##'
  - 本章小结
- - '#'
  - 6. 创建多视图应用程序
- - '##'
  - 多视图应用的常见类型
- - '##'
  - 多视图应用的架构
- - '###'
  - 根控制器
- - '###'
  - 内容视图剖析
- - '##'
  - 创建视图切换器应用
- - '###'
  - 重命名视图控制器
- - '###'
  - 添加内容视图控制器
- - '###'
  - 修改`SwitchingViewController.swift`
- - '###'
  - 使用工具栏构建视图
- - '###'
  - 将工具栏按钮连接到视图控制器
- - '###'
  - 编写根视图控制器的实现
- - '###'
  - 实现内容视图
- - '##'
  - 动画过渡
- - '##'
  - 小结
- - '#'
  - 使用标签栏和选择器
- - '##'
  - 选择器应用
- - '###'
  - 代理和数据源
- - '##'
  - 创建选择器应用
- - '###'
  - 创建视图控制器
- - '###'
  - 创建标签栏控制器
- - '##'
  - 初始模拟器测试
- - '###'
  - 实现日期选择器
- - '##'
  - 实现单组件选择器
- - '###'
  - 构建视图
- - '###'
  - 实现数据源和代理
- - '###'
  - '// Mark: 这是什么？？'
- - '##'
  - 实现多组件选择器
- - '###'
  - 构建视图
- - '###'
  - 实现控制器
- - '###'
  - 实现关联组件
- - '##'
  - 使用自定义选择器创建一个简单游戏
- - '###'
  - 准备视图控制器
- - '###'
  - 构建视图
- - '####'
  - iOS 设备支持的字体
- - '###'
  - 实现控制器
- - '####'
  - '`spin` 方法'
- - '####'
  - '`viewDidLoad()` 方法'
- - '###'
  - 游戏附加细节
- - '##'
  - 排版后的内容
- - '##'
  - 总结
- - '#'
  - 8. 表视图入门
- - '##'
  - 表视图基础
- - '###'
  - 表视图和表视图单元格
- - '###'
  - 分组表格与普通表格
- - '##'
  - 实现一个简单的表格
- - '###'
  - 设计视图
- - '###'
  - 实现控制器
- - '###'
  - 添加图片
- - '###'
  - 使用表格视图单元格样式
- - '###'
  - 设置缩进级别
- - '###'
  - 处理行选择
- - '###'
  - 更改字号与行高
- - '##'
  - 自定义表格视图单元格
- - '###'
  - 向表格视图单元格添加子视图
- - '##'
  - 实现自定义表格视图应用
- - '###'
  - 创建 `UITableViewCell` 子类
- - '###'
  - 添加新单元格
- - '##'
  - 实现控制器代码
- - '###'
  - 从 XIB 文件加载 UITableViewCell
- - '###'
  - 在 Interface Builder 中设计表格视图单元格
- - '##'
  - 使用新的表格视图单元格
- - '##'
  - 分组和索引分区
- - '###'
  - 构建视图
- - '###'
  - 导入数据
- - '###'
  - 实现控制器
- - '###'
  - 添加索引
- - '###'
  - 添加搜索栏
- - '###'
  - 视图调试
- - '##'
  - 总结
- - '#'
  - 9. 向表格视图添加导航控制器
- - '##'
  - 导航控制器基础
- - '###'
  - 栈
- - '###'
  - 控制器栈
- - '##'
  - 字体：一个简单的字体浏览器
- - '###'
  - 字体应用的子控制器
- - '####'
  - 字体列表控制器
- - '####'
  - 字体大小视图控制器
- - '####'
  - 使用披露指示器和详细信息披露按钮
- - '####'
  - 字体信息视图控制器
- - '###'
  - 字体应用的骨架
- - '####'
  - 设置导航控制器
- - '##'
  - 追踪喜爱的字体
- - '###'
  - 创建根视图控制器
- - '###'
  - 初始故事板设置
- - '###'
  - 第一个子控制器：字体列表视图
- - '##'
  - 创建字体列表故事板
- - '###'
  - 让根视图控制器为 Segue 做好准备
- - '##'
  - 创建字体大小视图控制器
- - '###'
  - 创建字体大小视图控制器的 Storyboard
- - '###'
  - 实现字体大小视图控制器的 Prepare for Segue
- - '###'
  - 创建字体信息视图控制器
- - '###'
  - 创建字体信息视图控制器的故事板
- - '####'
  - 设置约束
- - '###'
  - 适应多个转场的字体列表视图控制器
- - '###'
  - 我最喜欢的字体
- - '###'
  - 添加功能
- - '###'
  - 实现滑动删除
- - '###'
  - 实现拖拽重新排序
- - '##'
  - 总结
- - '#'
  - 10. 集合视图
- - '##'
  - 创建 DialogViewer 项目
- - '###'
  - 定义自定义单元格
- - '###'
  - 排版后的内容
- - '###'
  - 配置视图控制器
- - '###'
  - 提供内容单元格
- - '###'
  - 创建布局流程
- - '###'
  - 实现头部视图
- - '##'
  - 总结
- - '#'
  - 11. 适用于 iPad 应用的拆分视图和弹出框
- - '##'
  - 使用 `UISplitViewController` 构建主从应用
- - '###'
  - 故事板定义结构
- - '###'
  - 代码定义功能
- - '####'
  - '`AppDelegate`'
- - '####'
  - '`MasterViewController`'
- - '####'
  - 详情视图控制器
- - '###'
  - 主从模板应用的工作原理
- - '##'
  - 添加总统数据
- - '##'
  - 排版后的文档
- - '##'
  - 创建你自己的弹出框
- - '###'
  - 方法概述
- - '##'
  - 本章小结
- - '#'
  - 12. 使用设置和默认值进行应用自定义
- - '##'
  - 设置 Bundle
- - '##'
  - 舰桥控制应用
- - '###'
  - 创建舰桥控制项目
- - '###'
  - 使用设置束
- - '###'
  - 向项目添加设置捆绑包
- - '###'
  - 添加文本字段设置
- - '###'
  - 添加应用程序图标
- - '###'
  - 添加安全文本字段设置
- - '##'
  - 添加多值字段
- - '##'
  - 添加开关切换设置
- - '##'
  - 添加滑块设置
- - '####'
  - 向设置捆绑包添加图标
- - '####'
  - 添加子设置视图
- - '###'
  - 在应用程序中读取设置
- - '###'
  - 检索用户设置
- - '###'
  - 创建主视图
- - '####'
  - 更新第一个视图控制器
- - '###'
  - 从我们的应用中更改默认值
- - '###'
  - 注册默认值
- - '###'
  - 保持实时同步
- - '###'
  - 切换到“设置”应用
- - '##'
  - 小结
- - '#'
  - 13. 数据持久化：在应用启动间保存数据
- - '##'
  - 应用程序沙盒
- - '###'
  - 获取文档与库目录
- - '###'
  - 获取 tmp 目录
- - '##'
  - 文件保存策略
- - '###'
  - 单文件持久化
- - '###'
  - 多文件持久化
- - '##'
  - 使用属性列表
- - '###'
  - 属性列表序列化
- - '###'
  - 创建持久化应用的第一个版本
- - '##'
  - 设计持久化应用程序视图
- - '##'
  - 编辑持久化类
- - '##'
  - 归档模型对象
- - '###'
  - 符合 `NSCoding` 协议
- - '###'
  - 实现 `NSCopying`
- - '###'
  - 归档和解档数据对象
- - '###'
  - 归档应用
- - '####'
  - 实现 `FourLines` 类
- - '####'
  - 实现 `ViewController` 类
- - '###'
  - 使用 iOS 内嵌的 SQLite3
- - '###'
  - 创建或打开数据库
- - '###'
  - 使用绑定变量
- - '##'
  - 创建 SQLite3 应用
- - '###'
  - 链接 SQLite3 库
- - '####'
  - 修改持久化视图控制器
- - '###'
  - 使用 Core Data 实现持久化
- - '###'
  - 使用 Core Data
- - '###'
  - 实体与管理对象
- - '###'
  - 键值编码
- - '###'
  - 将一切置于上下文中
- - '###'
  - 创建新的托管对象
- - '###'
  - 检索托管对象
- - '###'
  - Core Data 应用程序
- - '###'
  - 设计数据模型
- - '###'
  - 修改`AppDelegate.swift`文件
- - '####'
  - 创建持久化视图
- - '##'
  - 总结
- - '#'
  - 14. 文档与 iCloud
- - '##'
  - 使用 UIDocument 管理文档存储
- - '###'
  - 创建 TinyPix 应用程序
- - '###'
  - 创建 TinyPixDocument
- - '###'
  - 主控制器
- - '###'
  - 设置故事板
- - '###'
  - 创建 TinyPix 视图
- - '###'
  - 故事板中的详细视图
- - '###'
  - TinyPixView 的配置与状态同步
- - '###'
  - 添加 iCloud 支持
- - '###'
  - 创建配置文件（Provisioning Profile）
- - '###'
  - 如何进行查询
- - '###'
  - 保存位置
- - '##'
  - 总结
- - '#'
  - 15. 使用 Grand Central Dispatch 进行多线程编程
- - '##'
  - 创建 SlowWorker 应用
- - '###'
  - 线程基础
- - '###'
  - 工作单元
- - '###'
  - GCD：底层队列
- - '###'
  - 改进 SlowWorker
- - '####'
  - 别忘了那个主线程
- - '##'
  - 提供一些反馈
- - '##'
  - 并发闭包
- - '##'
  - 后台处理
- - '##'
  - 应用程序生命周期
- - '###'
  - 状态变更通知
- - '##'
  - 创建 State Lab
- - '###'
  - 探索执行状态
- - '###'
  - 利用执行状态变化
- - '####'
  - 活跃 ➤ 非活跃
- - '####'
  - 非活跃 ➤ 后台
- - '####'
  - 后台 ➤ 非活跃
- - '####'
  - 非活跃 ➤ 活跃
- - '###'
  - 处理非活跃状态
- - '###'
  - 处理后台状态
- - '###'
  - 进入后台时释放资源
- - '###'
  - 进入后台时保存状态
- - '###'
  - 请求更多后台时间
- - '##'
  - 总结
- - '#'
  - 16. 图形与绘图
- - '##'
  - Quartz 2D
- - '##'
  - Quartz 2D 的绘图方法
- - '###'
  - Quartz 2D 的图形上下文
- - '###'
  - 坐标系
- - '###'
  - 指定颜色
- - '####'
  - 关于 iOS 设备显示屏的一点色彩理论
- - '####'
  - 其他色彩模型
- - '###'
  - 在上下文中绘制图像
- - '###'
  - 绘制形状：多边形、线条和曲线
- - '###'
  - Quartz 2D 工具集锦：图案、渐变和虚线模式
- - '##'
  - QuartzFun 应用程序
- - '###'
  - 创建 QuartzFun 应用程序
- - '####'
  - 创建随机颜色
- - '####'
  - 定义形状和颜色枚举
- - '###'
  - 实现 `QuartzFunView` 骨架
- - '####'
  - 创建并连接输出口与操作
- - '####'
  - 实现操作方法
- - '###'
  - 添加 Quartz 2D 绘图代码
- - '####'
  - 绘制线条
- - '####'
  - 绘制矩形和椭圆
- - '####'
  - 绘制图像
- - '###'
  - 优化 QuartzFun 应用程序
- - '##'
  - 本章小结
- - '#'
  - 17. 使用 SpriteKit 开发简单游戏
- - '##'
  - 创建 TextShooter 应用
- - '###'
  - 初始场景自定义
- - '###'
  - 玩家移动
- - '##'
  - 将玩家角色添加到场景中
- - '##'
  - 处理触摸：玩家移动
- - '##'
  - 几何计算
- - '##'
  - 让飞船摇摆起来
- - '###'
  - 创建你的敌人
- - '###'
  - 将敌人放入场景
- - '###'
  - 开始射击
- - '####'
  - 定义物理类别
- - '####'
  - 创建 `BulletNode` 类
- - '####'
  - 应用物理效果
- - '####'
  - 在场景中添加子弹
- - '###'
  - 利用物理引擎攻击敌人
- - '###'
  - 完成关卡
- - '####'
  - 过渡到下一关
- - '##'
  - 自定义碰撞效果
- - '###'
  - 为 `SKNode` 添加类扩展
- - '###'
  - 为敌人添加自定义碰撞行为
- - '####'
  - 显示玩家生命值
- - '###'
  - 用粒子效果增添趣味
- - '####'
  - 你的第一个粒子效果
- - '###'
  - 在场景中添加粒子效果
- - '###'
  - 结束游戏
- - '###'
  - 创建 StartScene
- - '###'
  - 添加音效
- - '###'
  - 让游戏更难一点：力场
- - '##'
  - 总结
- - '#'
  - 18. 点按、触摸与手势
- - '##'
  - 多点触控术语
- - '###'
  - 响应者链
- - '####'
  - 响应事件
- - '####'
  - 转发事件：保持响应者链活跃
- - '####'
  - 多点触控架构
- - '####'
  - 四种触摸通知方法
- - '##'
  - 创建 TouchExplorer 应用
- - '##'
  - 创建滑动检测应用
- - '##'
  - 使用触摸事件检测滑动
- - '###'
  - 自动手势识别
- - '###'
  - 实现多指轻扫
- - '###'
  - 检测多次点击
- - '###'
  - 检测捏合与旋转手势
- - '##'
  - 总结
- - '#'
  - 19. 确定位置
- - '##'
  - 位置管理器
- - '###'
  - 设置所需精度
- - '###'
  - 设置距离过滤器
- - '###'
  - 获取使用定位服务的权限
- - '###'
  - 启动定位管理器
- - '###'
  - 明智地使用定位管理器
- - '##'
  - 定位管理器委托
- - '###'
  - 获取位置更新
- - '###'
  - 使用 CLLocation 获取纬度和经度
- - '###'
  - 错误通知
- - '##'
  - 创建 WhereAmI 应用程序
- - '##'
  - 使用位置管理器更新
- - '###'
  - 在地图上可视化你的移动轨迹
- - '###'
  - 更改位置服务权限
- - '##'
  - 总结
- - '#'
  - 20. 设备方向和运动
- - '##'
  - 加速度计物理学
- - '##'
  - 使用陀螺仪检测旋转
- - '##'
  - Core Motion 与运动管理器
- - '###'
  - 创建 MotionMonitor 应用程序
- - '###'
  - 主动运动访问
- - '##'
  - 排版后的内容
- - '###'
  - 陀螺仪与姿态结果
- - '###'
  - 加速度计结果
- - '##'
  - 检测摇晃
- - '###'
  - 内置摇晃检测
- - '###'
  - Shake and Break 应用
- - '##'
  - 加速计作为方向控制器
- - '##'
  - 弹球应用
- - '###'
  - 编写 Ball View
- - '####'
  - 计算球的运动
- - '##'
  - 总结
- - '#'
  - 21. 使用相机与访问照片
- - '###'
  - 使用图像选择器和 UIImagePickerController
- - '###'
  - 使用图像选取器控制器
- - '###'
  - 实现图像选择控制器代理
- - '##'
  - 创建相机界面
- - '###'
  - 隐私选项
- - '###'
  - 实现摄像头视图控制器
- - '##'
  - 总结
- - '#'
  - 22. 使用本地化翻译应用程序
- - '##'
  - 本地化架构
- - '##'
  - 字符串文件
- - '###'
  - 字符串文件
- - '###'
  - 本地化字符串函数
- - '##'
  - 创建 LocalizeMe 应用
- - '###'
  - 本地化项目
- - '###'
  - 本地化故事板
- - '####'
  - 使用助手编辑器预览本地化
- - '####'
  - 使用自定义 Scheme 更改语言和区域设置
- - '####'
  - 在设备或模拟器上切换语言和区域设置
- - '###'
  - 生成并本地化字符串文件
- - '###'
  - 本地化应用显示名称
- - '###'
  - 构建并运行应用
- - '###'
  - 警告
- - '###'
  - 添加另一种本地化
- - '###'
  - 总结
- - '###'
  - 书籍总结
- - '#'
  - 附录 A：Swift 入门
- - '##'
  - Swift 基础
- - '###'
  - 游乐场、注释、变量与常量
- - '###'
  - 预定义类型、运算符和控制语句
- - '####'
  - 数值类型
- - '###'
  - 字符串
- - '####'
  - 布尔值
- - '####'
  - 枚举
- - '###'
  - 数组、区间和字典
- - '###'
  - 数组与区间
- - '###'
  - 字典
- - '###'
  - 集合
- - '###'
  - NSArray、NSDictionary 和 NSSet
- - '##'
  - 可选类型
- - '###'
  - 控制语句
- - '###'
  - if 语句
- - '###'
  - for 语句
- - '###'
  - repeat 和 while 语句
- - '###'
  - '`switch` 语句'
- - '###'
  - 函数与闭包
- - '###'
  - 错误处理
- - '####'
  - 捕获错误
- - '###'
  - 抛出错误
- - '###'
  - guard 语句
- - '###'
  - 关于错误捕获的更多内容
- - '###'
  - 类和结构体
- - '###'
  - 结构体
- - '###'
  - 类
- - '###'
  - 属性
- - '###'
  - 方法
- - '###'
  - 可选链
- - '###'
  - 子类化与继承
- - '##'
  - 协议
- - '###'
  - 扩展
- - '##'
  - 总结
- - '#'
  - 索引
