name: Extreme Mobile
name_cn: 极端移动设备
slug: extreme-mobile
toc:
- - '#'
  - 排版后内容
- - '#'
  - 前言
- - '#'
  - 引言
- - '#'
  - 关于作者
- - '#'
  - 关于技术审校者
- - '#'
  - 1. 构建模块化框架设计的基础
- - '##'
  - 创建 iOS 框架
- - '###'
  - 配置 iOS 框架
- - '###'
  - 创建故事板
- - '##'
  - 创建用户界面
- - '###'
  - 创建 Cocoa Touch 类
- - '###'
  - 创建 Swift 协议
- - '##'
  - 创建应用目标
- - '###'
  - 创建应用目标用户界面
- - '###'
  - 设计应用目标用户界面
- - '###'
  - 添加 iOS 框架
- - '###'
  - 集成 iOS 框架
- - '###'
  - 运行应用目标
- - '#'
  - 2. 应用现代设计模式打造可扩展、可维护的框架
- - '##'
  - 设计 RecordingsFW 框架
- - '###'
  - 设置 iOS 框架与项目
- - '###'
  - 创建用户界面
- - '###'
  - 创建 Cocoa Touch 类
- - '###'
  - 创建协议与模型
- - '###'
  - 创建 ViewModel
- - '##'
  - 创建本地文件服务
- - '##'
  - 将 ViewModel 集成到视图中
- - '##'
  - 将详情视图集成到表格中
- - '###'
  - 实现 Swift 协议
- - '##'
  - 创建应用目标
- - '###'
  - 集成 iOS 框架
- - '###'
  - 运行应用目标
- - '#'
  - 3. 为可复用框架设计通用、解耦的架构
- - '##'
  - 创建属性列表
- - '##'
  - 配置属性列表
- - '##'
  - 配置外部 API
- - '###'
  - 设计一个通用服务
- - '###'
  - 设计一个支持依赖注入的 ViewModel
- - '##'
  - 将 ViewModel 集成到视图中
- - '###'
  - 将依赖注入 ViewModel
- - '###'
  - 测试
- - '###'
  - 运行应用目标
- - '#'
  - 4. 为动态功能启用奠定基础
- - '##'
  - 设置 iOS 框架和项目
- - '###'
  - 创建 SwiftData 管理器
- - '###'
  - 配置桩 API 服务
- - '####'
  - 集成 OHHTTPStubs
- - '####'
  - 设计通用服务
- - '##'
  - 使用依赖注入设计 ViewModel
- - '##'
  - 将 ViewModel 集成到视图中
- - '##'
  - 设计 SwiftUI 视图
- - '##'
  - 创建 Swift 协议
- - '##'
  - 创建应用目标
- - '###'
  - 集成 iOS 框架
- - '###'
  - 运行应用目标
- - '##'
  - 管理应用内购买
- - '#'
  - 5. 扩展动态功能启用示例
- - '##'
  - 设计 RecordingStudioFW 框架
- - '##'
  - 设置 iOS 框架和项目
- - '###'
  - 创建属性列表
- - '###'
  - 创建 Cocoa Touch 类
- - '###'
  - 创建资源目录
- - '##'
  - 创建用户界面
- - '##'
  - 创建 Swift 协议
- - '##'
  - 创建应用目标
- - '###'
  - 集成 iOS 框架
- - '###'
  - 运行应用目标
- - '#'
  - 6. 通过动态功能启用推动收入增长
- - '##'
  - 扩展 RecordingsFW 框架
- - '###'
  - 功能启用
- - '###'
  - 集成行动号召
- - '####'
  - 创建行动号召的用户界面
- - '####'
  - 运行应用目标
- - '###'
  - 启用动态框架集成
- - '####'
  - 设计 ScratchTraxApp1 应用
- - '#####'
  - 创建 iOS 应用
- - '#####'
  - 为 iOS 应用创建用户界面
- - '#####'
  - 为 iOS 应用创建属性列表
- - '#####'
  - 创建 Xcode 工作区
- - '#####'
  - 动态集成 iOS 框架
- - '######'
  - 框架注册
- - '######'
  - 关键测试
- - '#'
  - 8. 统一动态框架架构
- - '##'
  - 设计 ScratchTraxApp2 应用
- - '###'
  - 创建另一个 iOS 应用
- - '###'
  - 为 iOS App 创建用户界面
- - '###'
  - 为 iOS App 创建属性列表
- - '###'
  - 创建 Xcode 工作区
- - '###'
  - 动态集成 iOS 框架
- - '##'
  - 框架注册
- - '###'
  - RecordingStudioFW
- - '###'
  - RecordingsStoreFW
- - '##'
  - 锦上添花
- - '##'
  - 通过应用内购买驱动收入
- - '#'
  - 9. 国际化框架实现多语言支持
- - '##'
  - 本地化 `SettingsFW` 框架
- - '###'
  - 本地化视图控制器
- - '##'
  - 创建字符串目录
- - '###'
  - 向字符串目录添加本地化语言
- - '###'
  - 向英语本地化添加值
- - '###'
  - 向法语本地化添加值
- - '###'
  - 向意大利语本地化添加值
- - '##'
  - 为 App 创建本地化文件
- - '###'
  - 配置 Scheme
- - '###'
  - 在模拟器中运行 App
- - '###'
  - 在真机上运行 App
- - '#'
  - 10. 在 iOS 框架中设计动态品牌化
- - '##'
  - 动态品牌化技术
- - '##'
  - 为品牌化创建属性列表
- - '##'
  - 跨框架集中管理品牌属性
- - '##'
  - 创建 UIKit 类扩展
- - '##'
  - 在模拟器中运行应用
- - '##'
  - 创建 SwiftUI 类扩展和环境键
- - '###'
  - 在模拟器中运行应用
- - '#'
  - 11. 打包与分发
- - '##'
  - CocoaPods
- - '##'
  - Swift Package Manager
- - '#'
  - 总结
- - '#'
  - 索引
- - '##'
  - A
- - '##'
  - B
- - '##'
  - C
- - '##'
  - D
- - '##'
  - E
- - '##'
  - F
- - '##'
  - G
- - '##'
  - H
- - '##'
  - I
- - '##'
  - J, K
- - '##'
  - L
- - '##'
  - M
- - '##'
  - N
- - '##'
  - O
- - '##'
  - P, Q
- - '##'
  - R
- - '##'
  - S
- - '##'
  - T
- - '##'
  - U
- - '##'
  - V
- - '##'
  - W
- - '##'
  - X, Y, Z
