name: iPhone App Development The Missing Manual
name_cn: iPhone 应用开发缺失手册
slug: iphone-app-development-the-missing-manual
toc:
- - '#'
  - iPhone 应用开发：缺失手册
- - '##'
  - 目录
- - '###'
  - 第一部分：入门指南
- - '####'
  - 第 1 章：构建你的第一个 iPhone 应用
- - '####'
  - 第 2 章：括号的力量
- - '####'
  - 第 3 章：Cocoa Touch：让 Objective-C 大显身手
- - '####'
  - 第 4 章：设计工具：打造更好的手电筒
- - '###'
  - 第二部分：深度开发
- - '####'
  - 第 5 章：认真对待开发
- - '####'
  - 第 6 章：专业级手电筒
- - '####'
  - 第 7 章：后期润色
- - '####'
  - 第 8 章：待售
- - '###'
  - 第三部分：商业实战
- - '####'
  - 第 9 章：有客户啦！
- - '###'
  - 第四部分：附录
- - '####'
  - 附录 A：下一步去哪里
- - '##'
  - 创作人员说明
- - '##'
  - 前言
- - '##'
  - 引言
- - '##'
  - 索引
