name: Learn Apple HomeKit on IOS
name_cn: iOS 上的 Apple HomeKit 学习指南
slug: learn-apple-homekit-on-ios
toc:
- - '#'
  - 在 iOS 上学习 Apple HomeKit
- - '##'
  - 引言
- - '##'
  - 致谢
- - '#'
  - 目录
- - '#'
  - 内容概览
- - '#'
  - 关于作者与关于技术审校
- - '##'
  - 关于作者
- - '##'
  - 关于技术审校
- - '#'
  - 让家居自动化走进生活
- - '##'
  - 欢迎回家
- - '##'
  - 2015 年：苹果发布新技术
- - '###'
  - CarPlay 加速发展
- - '###'
  - 设置 Apple TV
- - '###'
  - 关注时间
- - '###'
  - 融会贯通
- - '###'
  - 超越会说话的冰箱
- - '###'
  - 工作原理——山顶俯瞰图
- - '####'
  - 认识配件
- - '###'
  - HomeKit 中枢
- - '###'
  - 基础 HomeKit 家庭
- - '###'
  - 扩展 HomeKit
- - '##'
  - 总结
- - '#'
  - 2. 探索 HomeKit 世界
- - '##'
  - 配置你的 HomeKit 环境
- - '###'
  - 从 Apple ID 开始
- - '###'
  - 在 iPad 上快速开始
- - '###'
  - 管理家庭设置
- - '###'
  - 进入你的“家”
- - '###'
  - 添加并配置家庭
- - '###'
  - 编辑或添加房间
- - '###'
  - 添加并配置配件
- - '#'
  - 3. 添加场景——HomeKit 的实践部分
- - '##'
  - 什么是场景？
- - '###'
  - 创建基本场景
- - '###'
  - 场景可以涉及多个房间
- - '###'
  - 场景可自动化，并响应 Siri 指令
- - '###'
  - 场景是即时生效的
- - '##'
  - 使用场景
- - '###'
  - 创建场景
- - '###'
  - 添加配件
- - '###'
  - 调整配件
- - '###'
  - 完成设置
- - '###'
  - 编辑场景
- - '#'
  - 4. 探索你的开发环境
- - '##'
  - 获取开发者访问权限
- - '##'
  - 审视工具
- - '###'
  - 语言：Swift 和 Objective-C
- - '###'
  - 框架
- - '###'
  - 模拟器
- - '####'
  - 模拟 HomeKit 配件
- - '##'
  - 准备工作
- - '##'
  - 下一步做什么
- - '#'
  - 5. 使用 HomeKit 配件
- - '##'
  - 搭建 HomeKit 测试实验室
- - '##'
  - 设置 HomeKit
- - '##'
  - 设置房间
- - '##'
  - 使用自动化
- - '###'
  - 自动化地理位置变化
- - '###'
  - 自动化特定时间
- - '###'
  - 让配件控制自动化
- - '###'
  - 整合运用
- - '#'
  - 6. 作为开发者、设计师或设备制造商探索 HomeKit 世界
- - '##'
  - HomeKit 概述
- - '###'
  - Swift 面向 HomeKit 的面向对象特性
- - '####'
  - 协议与委托：架构
- - '####'
  - 协议与委托：关键角色
- - '####'
  - '`CVarArg`'
- - '####'
  - '`Equatable`'
- - '####'
  - '`Hashable`'
- - '##'
  - 创建新实例
- - '##'
  - 基本 HomeKit 对象
- - '###'
  - 处理房间
- - '####'
  - 管理房间
- - '####'
  - 编辑房间
- - '##'
  - 使用配件
- - '###'
  - 查找配件
- - '###'
  - 管理配件
- - '###'
  - 编辑配件
- - '#'
  - 7. 深入探索配件
- - '##'
  - 构建配件
- - '##'
  - 使用配件
- - '##'
  - 什么是配件？
- - '###'
  - 基本配件数据
- - '####'
  - 类别
- - '####'
  - 特征
- - '####'
  - 类型
- - '####'
  - 格式
- - '####'
  - 单位
- - '###'
  - 配件做什么？（服务）
- - '###'
  - 查找配件状态
- - '#'
  - 8. 充满想象的机会：事件、触发器和操作
- - '##'
  - 使用事件
- - '###'
  - 使用位置事件进行地理围栏
- - '###'
  - 监控特征事件
- - '##'
  - 使用触发器
- - '###'
  - 使用基本触发器
- - '###'
  - 使用谓词为触发器添加条件
- - '##'
  - 使用操作
- - '##'
  - 在 HomeKit 中使用 iCloud 和用户
- - '###'
  - 设置中枢
- - '####'
  - Apple TV
- - '####'
  - iPad
- - '###'
  - 设置用户
- - '####'
  - 邀请其他用户
- - '####'
  - 响应邀请
- - '####'
  - 在 iPad 上响应
- - '####'
  - 在 iPhone 上响应
- - '###'
  - 为用户设置权限
- - '###'
  - 允许锁屏访问
