name: Swift 5 for Absolute Beginners
name_cn: Swift 5 绝对初学者指南
slug: swift-5-for-absolute-beginners
toc:
- - '#'
  - 目录
- - '##'
  - 引言
- - '###'
  - 写给新手
- - '###'
  - 写给经验更丰富的开发者
- - '###'
  - 本书的组织方式
- - '###'
  - 成功公式
- - '###'
  - 开发技术栈
- - '###'
  - 所需软件、材料和设备
- - '###'
  - 操作系统和集成开发环境
- - '###'
  - 软件开发工具包
- - '###'
  - 双显示器
- - '###'
  - 关于作者与技术评审
- - '###'
  - 作者简介
- - '###'
  - 技术评审简介
- - '#'
  - 第 1 章 成为一名出色的 iOS 开发者
- - '###'
  - 成功的关键
- - '##'
  - 像开发者一样思考
- - '###'
  - 注意
- - '##'
  - 完成开发周期
- - '###'
  - 注
- - '##'
  - 介绍面向对象编程
- - '##'
  - 使用 Playground 界面
- - '##'
  - 本章小结
- - '##'
  - 下一步
- - '###'
  - 练习题
- - '#'
  - 第 2 章 编程基础
- - '##'
  - 初识 Xcode
- - '###'
  - 探索工作区窗口
- - '###'
  - 导航您的工作区
- - '###'
  - 编辑项目文件
- - '##'
  - 创建您的第一个 Swift Playground 程序
- - '###'
  - 安装并启动 Xcode 10.2
- - '###'
  - 注意
- - '###'
  - 使用 Xcode 10.2
- - '##'
  - Xcode Playground IDE：编辑器区域和结果区域
- - '###'
  - 注意
- - '##'
  - 总结
- - '###'
  - 练习
- - '#'
  - 第 3 章 一切都与数据有关
- - '##'
  - 编程中使用的数制
- - '###'
  - 位
- - '####'
  - 摩尔定律
- - '###'
  - 注意
- - '###'
  - 字节
- - '###'
  - 十六进制
- - '###'
  - Unicode
- - '##'
  - 数据类型
- - '##'
  - 声明常量和变量
- - '###'
  - 说明
- - '##'
  - 可选类型
- - '###'
  - 注意
- - '##'
  - 在 Playground 中使用变量
- - '###'
  - 注意
- - '##'
  - 总结
- - '###'
  - 练习
- - '#'
  - 第 4 章 决策、程序流程与应用设计
- - '##'
  - 布尔逻辑
- - '###'
  - 注意
- - '###'
  - 真值表
- - '###'
  - 比较运算符
- - '###'
  - 注意
- - '##'
  - 设计应用
- - '##'
  - 伪代码
- - '##'
  - 可选类型与强制解包
- - '###'
  - 可选绑定
- - '###'
  - 隐式解包可选类型
- - '###'
  - 流程图
- - '###'
  - 设计并绘制示例应用的流程图
- - '###'
  - 应用设计
- - '###'
  - 使用循环重复程序语句
- - '####'
  - 计数控制循环
- - '####'
  - 条件控制循环
- - '####'
  - 无限循环
- - '##'
  - 用 Swift 编写示例应用
- - '###'
  - 嵌套的 `if` 语句和 `else if` 语句
- - '###'
  - 移除多余字符
- - '###'
  - 通过重构改进代码
- - '###'
  - 运行应用
- - '###'
  - 设计要求
- - '##'
  - 总结
- - '###'
  - 练习
- - '#'
  - 第 5 章 使用 Swift 进行面向对象编程
- - '##'
  - 对象
- - '##'
  - 什么是类
- - '##'
  - 规划类
- - '###'
  - 规划属性
- - '###'
  - 规划方法
- - '##'
  - 实现类
- - '##'
  - 继承
- - '###'
  - 注意
- - '##'
  - 为什么要使用 OOP？
- - '###'
  - OOP 无处不在
- - '###'
  - 消除冗余代码
- - '###'
  - 易于调试
- - '###'
  - 易于替换
- - '##'
  - 高级主题
- - '###'
  - 接口
- - '###'
  - 多态性
- - '###'
  - 值导向编程
- - '##'
  - 总结
- - '###'
  - 练习
- - '#'
  - 第 6 章 学习 Swift 和 Xcode
- - '##'
  - 新手入门
- - '##'
  - 理解语言符号
- - '##'
  - 在 Swift 中实现对象
- - '###'
  - 注意
- - '###'
  - 注意
- - '###'
  - 注意
- - '##'
  - 在 Xcode 中编写另一个程序
- - '###'
  - 创建项目
- - '###'
  - 注意
- - '###'
  - 警告
- - '###'
  - 注意
- - '###'
  - 注意
- - '##'
  - 总结
- - '###'
  - 练习
- - '#'
  - 第 7 章 Swift 类、对象和方法
- - '##'
  - 创建 Swift 类
- - '##'
  - 属性
- - '##'
  - 方法
- - '##'
  - 使用类型方法
- - '##'
  - 使用实例方法
- - '##'
  - 使用你的新类
- - '###'
  - 创建项目
- - '###'
  - 添加对象
- - '###'
  - 编写类
- - '###'
  - 创建用户界面
- - '###'
  - 连接代码
- - '###'
  - 提示
- - '###'
  - 运行程序
- - '###'
  - 将类型方法提升到新水平
- - '##'
  - 访问 Xcode 文档
- - '##'
  - 总结
- - '###'
  - 练习题
- - '#'
  - 第 8 章 Swift 编程基础
- - '##'
  - 使用`let`与`var`
- - '###'
  - 注意
- - '##'
  - 理解集合
- - '##'
  - 使用数组
- - '###'
  - 注意
- - '##'
  - 使用字典类
- - '##'
  - 创建 BookStore 应用
- - '###'
  - 创建你的类
- - '###'
  - 注意
- - '###'
  - 引入属性
- - '###'
  - 访问属性
- - '##'
  - 完成 BookStore 程序
- - '###'
  - 创建视图
- - '###'
  - 添加属性
- - '###'
  - 添加描述
- - '###'
  - 注意事项
- - '###'
  - 创建一个简单的数据模型类
- - '###'
  - 修改 `MasterViewController`
- - '###'
  - 修改 `DetailViewController`
- - '##'
  - 本章小结
- - '###'
  - 练习题
- - '#'
  - 第 9 章 比较数据
- - '##'
  - 重温布尔逻辑
- - '##'
  - 使用关系运算符
- - '###'
  - 注意
- - '##'
  - 比较数字
- - '###'
  - 注意
- - '##'
  - 创建示例 Xcode 应用
- - '###'
  - 注意
- - '###'
  - 注意
- - '##'
  - 使用布尔表达式
- - '###'
  - 注意
- - '###'
  - 注意
- - '###'
  - 比较字符串
- - '###'
  - 注意
- - '##'
  - 使用 switch 语句
- - '###'
  - 注意
- - '###'
  - 比较日期
- - '###'
  - 注意
- - '###'
  - 组合比较
- - '##'
  - 总结
- - '###'
  - 练习
- - '#'
  - 第 10 章 创建用户界面
- - '###'
  - 注意
- - '##'
  - 理解 Interface Builder
- - '##'
  - 模型-视图-控制器模式
- - '##'
  - 人机界面指南
- - '###'
  - 注意
- - '###'
  - 注意
- - '##'
  - 使用 Interface Builder 创建示例 iPhone 应用
- - '##'
  - 使用 Interface Builder
- - '##'
  - 文档大纲
- - '###'
  - 注意
- - '##'
  - 对象库
- - '##'
  - 检查器面板和选择器栏
- - '##'
  - 创建视图
- - '###'
  - 注意
- - '###'
  - 使用 Outlet
- - '###'
  - 使用 Action
- - '###'
  - 类
- - '##'
  - 总结
- - '###'
  - 练习
- - '#'
  - 第 11 章 存储信息
- - '##'
  - 存储注意事项
- - '###'
  - 警告
- - '###'
  - 说明
- - '##'
  - 数据库
- - '##'
  - 在数据库中存储信息
- - '###'
  - 说明
- - '##'
  - Core Data 入门指南
- - '##'
  - 模型
- - '###'
  - 注意
- - '###'
  - 注意
- - '###'
  - 注意事项
- - '###'
  - 托管对象上下文
- - '###'
  - 设置界面
- - '##'
  - 本章小结
- - '###'
  - 练习
- - '#'
  - 第 12 章 协议与委托
- - '##'
  - 多重继承
- - '##'
  - 理解协议
- - '##'
  - 协议语法
- - '##'
  - 委托
- - '##'
  - 协议与委托示例
- - '##'
  - 开始入门
- - '###'
  - 注意
- - '##'
  - 工作原理
- - '##'
  - 总结
- - '###'
  - 练习
- - '#'
  - 第 13 章 Xcode 调试器入门
- - '##'
  - 调试入门
- - '##'
  - 设置断点
- - '##'
  - 使用断点导航器
- - '##'
  - 调试基础
- - '###'
  - 使用调试器控件
- - '###'
  - 使用步进控件
- - '###'
  - 查看线程窗口和调用栈
- - '###'
  - 调试变量
- - '##'
  - 处理代码错误和警告
- - '###'
  - 错误
- - '###'
  - 警告
- - '##'
  - 总结
- - '#'
  - 第 14 章 一个 Swift 语言编写的 iPhone 应用
- - '##'
  - 开始动手
- - '###'
  - 备注
- - '###'
  - 开关
- - '###'
  - 警告控制器
- - '##'
  - 应用总结
- - '###'
  - 练习
- - '#'
  - 第 15 章 Apple Watch 与 WatchKit
- - '##'
  - 创建 watchOS 应用时的注意事项
- - '##'
  - 创建 Apple Watch 应用
- - '###'
  - 注意
- - '###'
  - 说明
- - '##'
  - 添加更多功能
- - '##'
  - 总结
- - '###'
  - 练习
- - '#'
  - 索引
- - '###'
  - A
- - '###'
  - B
- - '###'
  - C
- - '###'
  - D
- - '###'
  - E
- - '###'
  - F
- - '###'
  - G
- - '###'
  - H
- - '###'
  - I, J, K
- - '###'
  - L
- - '###'
  - M
- - '###'
  - N
- - '###'
  - O
- - '###'
  - P
- - '###'
  - Q
- - '###'
  - R
- - '###'
  - S
- - '###'
  - T
- - '###'
  - U
- - '###'
  - V
- - '###'
  - W
- - '###'
  - X, Y, Z
