name: Pro Objective-C
name_cn: Objective-C 高级指南
slug: pro-objective-c
toc:
- - '#'
  - Pro Objective-C
- - '#'
  - 内容速览
- - '#'
  - 目录
- - '#'
  - 关于作者
- - '#'
  - 关于技术审阅者
- - '#'
  - 致谢
- - '#'
  - 简介
- - '##'
  - 本书内容
- - '##'
  - 本书读者对象
- - '##'
  - 你需要准备什么
- - '##'
  - 本书内容概览
- - '#'
  - 第 1 章 入门
- - '##'
  - 引言
- - '##'
  - Apple Objective-C 平台
- - '##'
  - 为什么选择 Objective-C？
- - '##'
  - Objective-C 特性
- - '##'
  - 开发一个简单的 Objective-C 程序
- - '###'
  - 创建项目
- - '###'
  - Xcode 工作区
- - '###'
  - 完成您的试运行
- - '###'
  - 总结
- - '#'
  - 第 2 章：使用类
- - '##'
  - 开发您的第一个类
- - '###'
  - 向项目添加一个类
- - '##'
  - 编写 Atom 类接口
- - '##'
  - 编写 Atom 类实现
- - '##'
  - 实例变量
- - '###'
  - 实例变量访问
- - '###'
  - 声明实例变量
- - '###'
  - 访问实例变量
- - '##'
  - 属性
- - '###'
  - 属性声明
- - '###'
  - 属性特性
- - '###'
  - 属性定义
- - '###'
  - 显式定义
- - '###'
  - 通过关键字合成
- - '###'
  - 自动合成
- - '###'
  - 动态生成
- - '###'
  - 属性支持的实例变量
- - '###'
  - 属性访问
- - '##'
  - 方法
- - '###'
  - 语法
- - '###'
  - 调用方法
- - '##'
  - 协议
- - '###'
  - 语法
- - '##'
  - 类别
- - '##'
  - 扩展（Extensions）
- - '##'
  - 小结
- - '#'
  - 第 3 章：对象与消息传递
- - '###'
  - 创建对象
- - '##'
  - 对象初始化
- - '##'
  - 扩展 Elements 项目
- - '##'
  - 重构 Atom 类
- - '###'
  - 创建 Hydrogen 初始化方法
- - '###'
  - 创建 Hydrogen 工厂方法
- - '##'
  - 消息分发
- - '##'
  - 消息转发
- - '##'
  - 转发选项
- - '##'
  - 为 Hydrogen 类添加快速转发
- - '###'
  - 消息转发辅助类
- - '##'
  - 总结
- - '#'
  - 第 4 章：内存管理
- - '###'
  - 程序内存使用
- - '##'
  - Objective-C 内存管理
- - '###'
  - 局部（自动）数据
- - '###'
  - 堆内存与动态对象
- - '###'
  - Objective-C 内存模型
- - '###'
  - 实现手动保留释放
- - '####'
  - 对象引用与对象所有权
- - '####'
  - 基本内存管理规则
- - '###'
  - 释放内存
- - '###'
  - 通过自动释放实现延迟释放
- - '###'
  - 使用 MRR
- - '###'
  - 使用自动引用计数
- - '##'
  - 使用 ARC 进行内存管理
- - '###'
  - 使用 ARC 的规则和约定
- - '###'
  - ARC 生命周期限定符
- - '###'
  - 使用 ARC
- - '###'
  - 避免循环引用
- - '####'
  - 声明弱引用
- - '###'
  - 总结
- - '#'
  - 第 5 章：预处理器
- - '##'
  - 概述
- - '##'
  - 操作
- - '##'
  - 预处理器语言
- - '##'
  - 指令
- - '###'
  - 头文件包含
- - '##'
  - 条件编译
- - '##'
  - 诊断信息
- - '##'
  - Pragma
- - '##'
  - 宏
- - '##'
  - 总结
- - '#'
  - 第 6 章：专家篇：使用 ARC
- - '##'
  - ARC 与对象所有权
- - '###'
  - 声称对象的所有权权益
- - '##'
  - 释放对象的所有权
- - '###'
  - 变量重新赋值
- - '###'
  - nil 赋值
- - '###'
  - 所有者释放
- - '##'
  - 创建多个订单条目
- - '##'
  - 将 ARC 与 Apple 框架和服务结合使用
- - '###'
  - Objective-C 免费桥接
- - '###'
  - ARC 桥接转换
- - '##'
  - 使用 ARC 桥接转换
- - '##'
  - 总结
- - '#'
  - 第 7 章：运行时系统
- - '##'
  - 动态特性
- - '##'
  - 对象消息传递
- - '##'
  - 选择器
- - '##'
  - 空选择器段
- - '##'
  - SEL 类型
- - '##'
  - 方法签名
- - '##'
  - 使用对象消息传递
- - '##'
  - 动态类型
- - '###'
  - 动态绑定
- - '###'
  - 动态方法解析
- - '###'
  - 动态提供方法实现
- - '###'
  - 动态加载
- - '##'
  - 内省
- - '##'
  - 小结
- - '#'
  - 第 8 章：运行时架构
- - '##'
  - 运行时组件
- - '###'
  - 编译器
- - '###'
  - 对象消息传递代码生成
- - '###'
  - 类与对象的代码生成
- - '###'
  - 查看运行时数据结构
- - '##'
  - 运行时库
- - '##'
  - 使用运行时库 API 创建类
- - '##'
  - 实现运行时对象消息传递
- - '##'
  - 通过 vtable 进行方法查找
- - '##'
  - 通过 dyld 共享缓存进行选择器唯一化
- - '##'
  - 消息分发
- - '###'
  - 消息调用优化
- - '###'
  - 访问类实例方法
- - '###'
  - 检查类方法
- - '###'
  - 与运行时交互
- - '###'
  - 前文回顾
- - '##'
  - NSObject 运行时方法
- - '##'
  - 执行对象内省
- - '##'
  - 总结
- - '#'
  - 第 9 章：专家篇：使用运行时 API
- - '###'
  - 使用可加载 Bundle 扩展程序
- - '####'
  - 方法
- - '##'
  - 步骤 1：奠定基础
- - '##'
  - 步骤 2：创建可加载的 Bundle
- - '###'
  - 步骤 3：动态加载包
- - '###'
  - 检索包路径参数
- - '###'
  - 创建 `NSBundle` 对象
- - '##'
  - 加载 Bundle
- - '##'
  - 获取 Bundle 类
- - '##'
  - 卸载 Bundle
- - '##'
  - 检索 Bundle 路径参数
- - '##'
  - 使用运行时 API
- - '##'
  - 定义方法实现
- - '##'
  - 创建并注册类
- - '##'
  - 创建类实例
- - '##'
  - 动态添加变量到类实例
- - '##'
  - 创建动态代理
- - '###'
  - 创建 Invoker 协议
- - '##'
  - 编写代理类
- - '##'
  - 测试 AspectProxy
- - '##'
  - 小结
- - '#'
  - 第 10 章：Foundation 框架通用类
- - '##'
  - 根类
- - '###'
  - Root Classes
- - '###'
  - NSObject 协议
- - '###'
  - NSObject
- - '####'
  - 基本行为
- - '####'
  - 发送消息
- - '####'
  - 创建和初始化
- - '###'
  - NSProxy
- - '##'
  - 字符串
- - '###'
  - NSString
- - '####'
  - 创建和初始化
- - '####'
  - 扫描值
- - '####'
  - 字符串搜索和比较
- - '##'
  - Foundation 框架值对象
- - '###'
  - NSValue
- - '###'
  - NSNumber
- - '###'
  - NSDecimalNumber
- - '###'
  - NSNumber 字面量
- - '##'
  - 日期和时间支持
- - '##'
  - NSCache
- - '##'
  - 集合
- - '###'
  - NSArray
- - '####'
  - NSArray 字面量
- - '###'
  - NSPointerArray
- - '###'
  - NSDictionary
- - '####'
  - NSDictionary 字面量
- - '###'
  - NSMapTable
- - '###'
  - NSSet
- - '###'
  - NSCountedSet
- - '###'
  - NSHashTable
- - '###'
  - NSPointerFunctions
- - '##'
  - XML 处理
- - '###'
  - XML DTD 处理
- - '###'
  - 基于树的 XML 处理
- - '###'
  - 事件驱动的 XML 处理
- - '##'
  - 谓词
- - '##'
  - 总结
- - '#'
  - 第 11 章：Foundation 框架系统服务
- - '##'
  - 网络服务
- - '###'
  - '`NSHost`'
- - '###'
  - Bonjour 网络服务
- - '##'
  - 应用程序服务
- - '##'
  - 正则表达式与文本处理
- - '##'
  - 文件系统实用工具
- - '##'
  - 应用程序包
- - '##'
  - 文件管理
- - '##'
  - 流式输入输出
- - '##'
  - 元数据查询
- - '##'
  - 并发与线程
- - '###'
  - 线程管理
- - '##'
  - 并发操作
- - '##'
  - 锁
- - '##'
  - 定时器和运行循环
- - '##'
  - 创建 Bonjour 网络服务客户端
- - '##'
  - URL 处理
- - '###'
  - URL 加载
- - '###'
  - 缓存管理
- - '##'
  - 使用 URL 加载 API 下载资源
- - '##'
  - 身份验证和凭据管理
- - '##'
  - Cookie 管理
- - '##'
  - 协议支持
- - '##'
  - 进程间通信
- - '###'
  - 通过管道通信
- - '###'
  - 通过端口通信
- - '###'
  - 端口注册
- - '###'
  - 小结
- - '#'
  - 第 12 章：Foundation 框架专用服务
- - '##'
  - 通知
- - '###'
  - NSNotificationCenter 和 NSDistributedNotificationCenter
- - '###'
  - NSNotificationQueue
- - '##'
  - 归档和序列化
- - '###'
  - 归档
- - '####'
  - 顺序归档
- - '####'
  - 键控归档
- - '###'
  - 编码和解码对象
- - '###'
  - 属性列表序列化
- - '####'
  - XML 属性列表
- - '####'
  - '`NSPropertyListSerialization`'
- - '##'
  - 脚本化
- - '##'
  - 总结
- - '#'
  - 第 13 章 Foundation 函数与数据类型
- - '##'
  - Foundation 函数
- - '###'
  - 断言
- - '####'
  - 断言宏
- - '###'
  - 日志记录
- - '###'
  - Bundle 包
- - '####'
  - 本地化字符串
- - '###'
  - 本地化字符串函数
- - '###'
  - 十进制数和字节顺序
- - '###'
  - 使用 NSDecimal 函数
- - '###'
  - 字节序
- - '###'
  - 与运行时交互
- - '###'
  - 文件路径
- - '###'
  - 几何图形
- - '##'
  - 数据类型
- - '##'
  - 常量
- - '##'
  - 总结
- - '#'
  - 第 14 章：专家部分：错误处理
- - '###'
  - 运行时错误条件
- - '###'
  - 断言
- - '###'
  - 错误码
- - '##'
  - 错误对象
- - '##'
  - 异常
- - '##'
  - '`NSError`'
- - '###'
  - 使用错误对象
- - '###'
  - 处理委托方法错误
- - '###'
  - 通过间接方式创建错误对象
- - '###'
  - 错误恢复
- - '###'
  - 错误响应者
- - '###'
  - NSError 错误码
- - '##'
  - 异常处理
- - '###'
  - NSException
- - '###'
  - 异常与内存管理
- - '###'
  - 执行异常处理
- - '###'
  - Foundation 标准异常名称
- - '##'
  - 错误处理指南
- - '###'
  - 错误对象
- - '###'
  - 异常
- - '###'
  - 指南与建议
- - '##'
  - 总结
- - '#'
  - 第 15 章：块
- - '##'
  - 块语法
- - '###'
  - 方法调用中的块字面量表达式
- - '##'
  - 块就是闭包！
- - '##'
  - 词法作用域
- - '##'
  - 可变的 `__block` 变量
- - '##'
  - 块的内存管理
- - '##'
  - 使用块
- - '###'
  - 使用块对数组进行排序
- - '###'
  - 使用块加载 URL
- - '###'
  - 使用块进行并发编程
- - '##'
  - 总结
- - '#'
  - 第 16 章：Objective-C 字面量
- - '###'
  - 字面量
- - '##'
  - NSNumber 字面量
- - '##'
  - 容器字面量
- - '###'
  - NSArray 字面量
- - '###'
  - NSDictionary 字面量
- - '##'
  - 表达式字面量
- - '##'
  - 对象下标引用
- - '###'
  - NSArray 下标引用
- - '###'
  - NSDictionary 下标引用
- - '###'
  - 自定义下标引用
- - '##'
  - 使用自定义下标编辑寄存器值
- - '##'
  - 总结
- - '#'
  - 第 17 章：并发编程
- - '##'
  - 并发编程基础
- - '##'
  - 并发的优势
- - '##'
  - 实现并发
- - '##'
  - 并发面临的挑战
- - '###'
  - 共享数据
- - '####'
  - 锁的问题
- - '##'
  - 锁机制实现策略
- - '##'
  - 消息传递
- - '##'
  - 使用 Objective-C 进行并发编程
- - '###'
  - 语言特性
- - '###'
  - 消息传递
- - '##'
  - 线程（Threads）
- - '###'
  - NSObject 线程
- - '###'
  - NSThread
- - '##'
  - 线程同步
- - '###'
  - 锁
- - '###'
  - 条件
- - '##'
  - 使用线程实现并发
- - '##'
  - 操作与操作队列
- - '###'
  - 手动执行操作对象
- - '###'
  - 实现并发操作
- - '###'
  - 使用操作队列实现并发
- - '##'
  - Grand Central Dispatch
- - '###'
  - 使用调度队列
- - '##'
  - 键值编程
- - '###'
  - 为并发编程选择合适的 API
- - '##'
  - 总结
- - '#'
  - 第 18 章：键值编程
- - '##'
  - 键值编码
- - '###'
  - 键值编码基础
- - '###'
  - 键和键路径
- - '###'
  - KVC 的设计与实现
- - '###'
  - 键值编码 API
- - '###'
  - 键值搜索模式
- - '###'
  - 属性访问器命名约定
- - '###'
  - 对多属性访问器命名约定
- - '###'
  - 键值验证
- - '###'
  - 键值编码集合运算符
- - '##'
  - 键值观察
- - '###'
  - 键值观察 vs. Foundation 框架通知
- - '###'
  - 键值观察 API
- - '###'
  - KVO 设计与实现
- - '##'
  - 使用键值编程
- - '###'
  - 键值编码与键值观察
- - '#'
  - 附录 A — 语言元素
- - '###'
  - 变量
- - '###'
  - Objective-C 保留字
- - '###'
  - 变量作用域
- - '###'
  - 访问修饰符
- - '###'
  - 数据类型
- - '##'
  - '`BOOL`类型'
- - '##'
  - 类实例类型
- - '###'
  - '`id`类型'
- - '###'
  - '`instancetype`关键字'
- - '##'
  - 类定义类型
- - '###'
  - '`SEL`类型'
- - '###'
  - '`IMP`类型'
- - '###'
  - '`Class`类型'
- - '###'
  - '`objc_object`类型'
- - '##'
  - 块类型
- - '##'
  - 枚举类型
- - '##'
  - 运算符
- - '##'
  - 语句
- - '##'
  - 类元素
- - '###'
  - 实例变量
- - '###'
  - 实例变量所有权限定符
- - '###'
  - 属性
- - '##'
  - 方法
- - '##'
  - 接口
- - '###'
  - 前置声明
- - '###'
  - 实现
- - '###'
  - 协议
- - '##'
  - 类别（Category）
- - '##'
  - 类扩展（Class Extension）
- - '#'
  - 附录 B： Xcode 揭秘！
- - '##'
  - 基本概念
- - '##'
  - 目标
- - '##'
  - 构建阶段
- - '##'
  - 构建设置
- - '##'
  - 构建配置
- - '##'
  - 构建规则
- - '##'
  - 创建配置文件设置文件
- - '##'
  - 项目
- - '##'
  - 可执行环境
- - '##'
  - 工作区
- - '##'
  - 将现有项目添加到工作区
- - '##'
  - 在工作区中使用静态库
- - '###'
  - 创建工作区
- - '##'
  - 创建静态库
- - '##'
  - 创建应用程序
- - '###'
  - 向应用添加代码
- - '##'
  - 方案
- - '##'
  - 操作
- - '##'
  - 总结
- - '#'
  - '附录 C: 使用 LLDB'
- - '##'
  - LLVM 概述
- - '##'
  - LLDB
- - '##'
  - 设计
- - '###'
  - 库
- - '###'
  - 表达式解析
- - '###'
  - 插件架构
- - '###'
  - LLDB 架构
- - '###'
  - 多线程调试
- - '##'
  - LLDB 命令
- - '##'
  - Xcode LLDB 集成
- - '###'
  - 调试导航器
- - '###'
  - 断点导航器
- - '###'
  - 断点操作
- - '##'
  - 调试区
- - '##'
  - 反汇编视图
- - '##'
  - 在 Xcode 中使用 LLDB
- - '##'
  - 总结
- - '#'
  - 索引
