name: Android Studio IDE Quick Reference
name_cn: Android Studio IDE 快速参考指南
slug: android-studio-ide-quick-reference
toc:
- - '#'
  - 引言
- - '##'
  - 本书面向的读者
- - '##'
  - 源代码
- - '##'
  - 致谢
- - '##'
  - 关于作者与技术审阅者
- - '###'
  - 关于作者
- - '###'
  - 关于技术审阅者
- - '#'
  - 1. 安装与设置
- - '##'
  - 设置 Android Studio
- - '###'
  - 注意
- - '##'
  - 配置 Android Studio
- - '###'
  - 注意
- - '##'
  - 硬件加速
- - '##'
  - 本章小结
- - '#'
  - 2. 快速操作指南
- - '##'
  - 创建项目
- - '###'
  - 创建 Activity
- - '###'
  - 注意
- - '###'
  - 创建类
- - '##'
  - 创建接口
- - '##'
  - 重写方法
- - '##'
  - 运行项目
- - '##'
  - 章节总结
- - '#'
  - 3. IDE
- - '##'
  - 集成开发环境 (IDE)
- - '###'
  - 主编辑器
- - '####'
  - 编辑布局文件
- - '####'
  - 插入 TODO 项
- - '####'
  - 如何为代码获取更多屏幕空间
- - '###'
  - 项目工具窗口
- - '###'
  - SDK 管理器
- - '###'
  - 代码样式
- - '###'
  - 章节总结
- - '#'
  - 4. 调试
- - '##'
  - 错误类型
- - '###'
  - 语法错误
- - '###'
  - 运行时错误
- - '###'
  - 逻辑错误
- - '##'
  - 调试器
- - '###'
  - 注意
- - '###'
  - 单步执行
- - '###'
  - 章节总结
- - '#'
  - 5. 单元测试
- - '##'
  - JVM 测试 vs. 插桩测试
- - '##'
  - 简单示例
- - '##'
  - 实现测试
- - '##'
  - 运行单元测试
- - '###'
  - 提示
- - '##'
  - 测试先行
- - '##'
  - 本章小结
- - '#'
  - 6. 插桩测试
- - '##'
  - 关于 Espresso
- - '##'
  - 搭建一个简单的测试
- - '###'
  - 录制 Espresso 测试
- - '###'
  - 注意
- - '##'
  - 关于 Espresso 匹配器的更多信息
- - '##'
  - Espresso 操作
- - '##'
  - 章节总结
- - '#'
  - 7. Android Studio Profiler
- - '##'
  - Profiler
- - '###'
  - 注意
- - '##'
  - CPU
- - '##'
  - 内存
- - '##'
  - 网络
- - '##'
  - 能耗
- - '##'
  - 本章小结
- - '#'
  - 8. Gradle
- - '##'
  - 构建过程
- - '###'
  - 注意
- - '##'
  - 构建文件
- - '###'
  - 模块级 Gradle 文件
- - '###'
  - 依赖项
- - '####'
  - 注意
- - '##'
  - Android Support Library
- - '###'
  - 注意
- - '##'
  - 本章小结
- - '#'
  - 9. Git
- - '##'
  - 获取 Git
- - '###'
  - 提示
- - '##'
  - 将 Android Studio 与 GitHub 结合使用
- - '###'
  - 在 GitHub 上分享项目
- - '###'
  - 提示
- - '##'
  - 从 GitHub 打开项目
- - '###'
  - 注意
- - '##'
  - 更新 Git 项目
- - '##'
  - 使用其他 Git 仓库
- - '###'
  - 注意
- - '##'
  - 章节总结
- - '#'
  - 10. 导航
- - '##'
  - 导航架构组件之前
- - '##'
  - 导航组件
- - '###'
  - 使用 Jetpack 导航
- - '####'
  - 注意
- - '##'
  - 本章小结
- - '#'
  - 11. Lifecycle、ViewModel、LiveData 和 Room
- - '##'
  - 生命周期感知组件
- - '###'
  - 注意
- - '##'
  - ViewModel
- - '##'
  - '`LiveData`'
- - '##'
  - Room
- - '##'
  - 章节总结
- - '#'
  - 12. 发布构建版本
- - '##'
  - 为发布准备应用
- - '###'
  - 准备发布所需的素材和资源
- - '###'
  - 配置应用以准备发布
- - '###'
  - 构建可发布的应用
- - '##'
  - 发布应用
- - '##'
  - 本章小结
- - '#'
  - 13. 快速指南
- - '##'
  - 效率特性
- - '###'
  - 导入示例
- - '###'
  - 重构
- - '###'
  - 注释
- - '###'
  - 生成
- - '###'
  - 编码风格
- - '##'
  - 实时模板
- - '##'
  - 重要键盘快捷键
- - '##'
  - 章节总结
- - '#'
  - 索引
- - '##'
  - A, B, C
- - '##'
  - D
- - '##'
  - E
- - '##'
  - F
- - '##'
  - G, H
- - '##'
  - I
- - '##'
  - J
- - '##'
  - K
- - '##'
  - L
- - '##'
  - M
- - '##'
  - N
- - '##'
  - O
- - '##'
  - P, Q
- - '##'
  - R
- - '##'
  - S
- - '##'
  - T
- - '##'
  - U
- - '##'
  - V
- - '##'
  - W, X, Y, Z
