name: Developing Professional IPhone Photography
name_cn: iPhone 摄影专业指南
slug: developing-professional-iphone-photography
toc:
- - '#'
  - 打造专业级 iPhone 摄影技术
- - '##'
  - 引言
- - '##'
  - 如何使用本书
- - '##'
  - 练习、练习、再练习
- - '#'
  - 目录
- - '#'
  - 第一部分：释放 iPhone 相机的强大潜力
- - '##'
  - 掌握你的 iPhone 相机
- - '###'
  - 轻松访问相机
- - '####'
  - 滑动操作打开
- - '####'
  - 使用手机控制中心
- - '####'
  - 将相机应用添加到程序坞
- - '###'
  - 多种方式完成拍摄
- - '###'
  - 启用网格参考线
- - '###'
  - 使用连拍模式
- - '###'
  - 设置手动对焦与曝光
- - '###'
  - 锁定曝光与对焦
- - '###'
  - 拍摄 HDR 照片
- - '####'
  - 拍摄实况照片
- - '###'
  - 快速访问不同的照片类型
- - '##'
  - 充分利用“照片”应用
- - '###'
  - 使用“时刻”和“年度”视图
- - '###'
  - 在移动设备上查找照片
- - '###'
  - 保存人物面部信息
- - '###'
  - 将照片添加到个人收藏并创建相簿
- - '##'
  - 本章小结
- - '##'
  - 实践练习
- - '#'
  - 第二部分：照片润饰技巧
- - '##'
  - 修复照片的色彩
- - '###'
  - 使用照片应用修改色彩
- - '###'
  - 移除偏色
- - '###'
  - 使用 Adobe Lightroom 进行颜色调整
- - '###'
  - 执行高级颜色修改
- - '##'
  - 裁剪与调整照片尺寸
- - '##'
  - 移除背景
- - '##'
  - 精通选区
- - '##'
  - 从照片中移除元素
- - '##'
  - 摘要
- - '##'
  - 练习
- - '#'
  - 第三部分：处理摄影项目
- - '##'
  - 创建高级 HDR 照片
- - '###'
  - 步骤 1：准备照片
- - '###'
  - 步骤 2：应用 HDR 效果
- - '###'
  - 步骤 3：应用暗角效果
- - '###'
  - 第 4 步：添加模糊效果
- - '###'
  - 创建浅景深
- - '###'
  - 第 1 步：保护主要物体
- - '###'
  - 第 2 步：应用模糊效果
- - '###'
  - 第 3 步：应用暗角效果
- - '###'
  - 第 4 步：应用最终滤镜
- - '###'
  - 创建弱光黑白照片
- - '###'
  - 步骤 1：将照片转换为黑白
- - '###'
  - 步骤 2：聚焦于面部
- - '###'
  - 步骤 3：改善高光
- - '##'
  - 创建高调照片
- - '###'
  - 步骤 1：转换为黑白
- - '###'
  - 步骤 2：创建模糊版本
- - '###'
  - 步骤 3：完成高调照片
- - '##'
  - 创建双重曝光照片
- - '###'
  - 第 1 步：准备基础照片
- - '###'
  - 第 2 步：合并照片
- - '###'
  - 第 3 步：增强双重曝光效果
- - '##'
  - 总结
- - '##'
  - 练习实践
- - '#'
  - 第四部分：掌握照片编辑与应用效果
- - '##'
  - 制作诱人的美食照片拼贴
- - '###'
  - 第一步：修改照片颜色
- - '###'
  - 第二步：构建照片拼贴
- - '###'
  - 第三步：保存照片拼贴
- - '###'
  - 第四步：添加纹理效果
- - '##'
  - 为你的照片添加复古风格
- - '###'
  - 第一步：应用复古效果
- - '###'
  - 第二步：添加镜头光晕
- - '###'
  - 第三步：优化复古效果
- - '##'
  - 创建相框
- - '###'
  - 步骤 1：为照片添加复古效果
- - '###'
  - 步骤 2：应用更多相框
- - '###'
  - 步骤 3：添加相框背景纹理
- - '##'
  - 创建胶片条纹效果
- - '###'
  - 步骤 1：将照片转换为单色
- - '###'
  - 步骤 2：优化照片并添加相框
- - '##'
  - 使用色彩突出元素
- - '###'
  - 步骤 1：修复照片问题
- - '###'
  - 步骤 2：将照片转换为黑白
- - '###'
  - 步骤 3：为国王的面具添加颜色
- - '##'
  - 本章小结
- - '##'
  - 练习
- - '#'
  - 第五部分：与桌面版 Adobe Lightroom 集成
- - '##'
  - 为照片评分、标记并整理
- - '###'
  - 管理集合
- - '##'
  - 在 Lightroom 中拍摄原始照片
- - '##'
  - 与桌面版 Lightroom 集成文件
- - '###'
  - 通过云端整合照片
- - '###'
  - 从你的 iPhone 导入照片
- - '##'
  - 使用其他 Raw 照片应用
- - '##'
  - 总结
- - '##'
  - 实践练习
- - '#'
  - 第六部分：在桌面上将你的照片与 Adobe Photoshop 集成
- - '##'
  - 准备将 iPhone 集成
- - '##'
  - 与桌面版 Photoshop 集成文件
- - '##'
  - 在电脑上完成 iPhone 照片编辑
- - '###'
  - 步骤 1：在 iPhone 上修复照片
- - '###'
  - 步骤 2：将文档发送到 Photoshop CC
- - '###'
  - 第 3 步：在 Photoshop CC 中应用效果
- - '##'
  - 总结
- - '##'
  - 练习
- - '#'
  - 第七部分：将照片变成艺术品
- - '##'
  - 创作波普艺术作品
- - '###'
  - 步骤 1：修改照片的光线和对比度
- - '###'
  - 步骤 2：应用波普艺术效果
- - '###'
  - 步骤 3：更改波普艺术颜色
- - '##'
  - 将照片转化为马赛克艺术作品
- - '###'
  - 步骤 1：修复基础照片
- - '###'
  - 步骤 2：应用马赛克效果
- - '###'
  - 步骤 3：改善马赛克艺术作品的颜色
- - '##'
  - 将你的照片变成一幅油画
- - '###'
  - 步骤 1：改善照片的颜色和对比度
- - '###'
  - 步骤 2：应用油画效果
- - '###'
  - 步骤 3：改善绘画颜色
- - '##'
  - 为你的照片添加雾冬效果
- - '###'
  - 步骤 1：为窗户添加雾气
- - '###'
  - 第二步：应用水滴效果
- - '###'
  - 第三步：改善照片的光线与色彩
- - '##'
  - 本章小结
- - '##'
  - 实践练习
- - '#'
  - 第八部分：照片后期合成项目
- - '##'
  - 创建一个幻想场景
- - '###'
  - 第一步：准备基础场景
- - '###'
  - 第二步：去除地球背景
- - '###'
  - 第三步：将地球添加到合成中
- - '###'
  - 第 4 步：为天空增添更多效果
- - '###'
  - 第 5 步：添加垃圾摇滚效果
- - '##'
  - 构建法老风格合成图
- - '###'
  - 第 1 步：优化照片颜色和光线
- - '###'
  - 第 2 步：移除天空
- - '###'
  - 第 3 步：构建合成图
- - '###'
  - 第 4 步：添加戏剧性的天空效果
- - '##'
  - 总结
- - '##'
  - 练习
- - '#'
  - 第九部分：拍摄与剪辑视频
- - '##'
  - 拍摄与修剪视频
- - '###'
  - 设置视频质量
- - '###'
  - 在拍摄视频的同时拍摄静态照片
- - '###'
  - 在照片应用中编辑素材
- - '##'
  - 创建超延时视频
- - '###'
  - 第 1 步：创建超延时项目
- - '###'
  - 第 2 步：为视频添加音乐
- - '###'
  - 第 3 步：修改动画帧
- - '###'
  - 第 4 步：导出视频
- - '##'
  - 编辑和应用滤镜
- - '###'
  - 步骤 1：创建视频项目
- - '###'
  - 步骤 2：从视频中裁剪不需要的部分
- - '###'
  - 步骤 3：将视频转换为黑白效果
- - '###'
  - 步骤 4：为视频添加音轨
- - '###'
  - 步骤 5：将项目导出为视频
- - '##'
  - 创建 20 世纪 80 年代电视视频效果
- - '###'
  - 步骤 1：合并视频素材和音频
- - '###'
  - 步骤 2：添加视频效果并保存视频
- - '##'
  - 总结
- - '##'
  - 练习
- - '#'
  - 第十部分：存储你的照片
- - '##'
  - 管理你的 iPhone 存储空间
- - '###'
  - 不要重复保存照片
- - '###'
  - 停止存储短信历史记录
- - '###'
  - 删除已下载的播客和音乐
- - '###'
  - 移除浏览器历史记录和阅读列表
- - '##'
  - 使用 iCloud 保存和管理照片
- - '###'
  - 激活将照片保存到 iCloud
- - '###'
  - 管理 iCloud 存储与应用程序
- - '##'
  - 使用其他云服务
- - '##'
  - 使用 Lightroom 应用同步原始文件
- - '##'
  - 与您的电脑同步文件
- - '##'
  - 将 iPhone 照片导入电脑
- - '##'
  - 从电脑同步照片到 iPhone
- - '##'
  - 本章小结
- - '##'
  - 实践练习
- - '#'
  - 第十一部分：为社交网络进行照片编辑
- - '##'
  - 使用 Adobe Spark 创建有吸引力的照片展示
- - '###'
  - 第 1 步：创建页面布局
- - '###'
  - 第 2 步：预览并分享页面
- - '##'
  - 创建 Instagram 网格照片
- - '###'
  - 第 1 步：将照片分割成多个部分
- - '###'
  - 第 2 步：为分割后的照片添加滤镜
- - '###'
  - 第 3 步：分享照片
- - '##'
  - 将照片转化为社交品牌形象图
- - '###'
  - 第 1 步：创建 Facebook 横幅
- - '###'
  - 第 2 步：创建摄影名片
- - '##'
  - 总结
- - '##'
  - 练习
- - '#'
  - 第十二部分：像专业人士一样营销和销售照片
- - '##'
  - 管理合同与表格
- - '###'
  - 扫描文档
- - '###'
  - 步骤 1：设置文档并扫描
- - '###'
  - 步骤 2：添加和修改扫描文档
- - '###'
  - 步骤 3：共享文档
- - '###'
  - 步骤 4：评论文档
- - '###'
  - 步骤 5：填写并签署文档
- - '###'
  - 步骤 6：填写个人资料
- - '###'
  - 步骤 7：添加签名和姓名首字母
- - '###'
  - 步骤 8：填写表单
- - '##'
  - 构建摄影作品集
- - '###'
  - 个人摄影网站
- - '###'
  - 作品集网站
- - '###'
  - 社交网络页面
- - '##'
  - 让您的照片易于搜索
- - '##'
  - 在线销售照片
- - '###'
  - 在哪里销售您的照片？
- - '##'
  - 总结
- - '##'
  - 练习
- - '#'
  - 附录 A：摄影师简介
- - '##'
  - 阿莫·帕西科斯
- - '##'
  - 曼迪·布莱克
- - '##'
  - 迈克尔·克劳森
- - '#'
  - 索引
- - '##'
  - A
- - '##'
  - B
- - '##'
  - C
- - '##'
  - D
- - '##'
  - E
- - '##'
  - F
- - '##'
  - G
- - '##'
  - H
- - '##'
  - I, J
- - '##'
  - K
- - '##'
  - L
- - '##'
  - M, N
- - '##'
  - O
- - '##'
  - P, Q
- - '##'
  - R
- - '##'
  - S
- - '##'
  - T
- - '##'
  - V, W, X, Y, Z
