name: IOS Sensor Apps with Arduino
name_cn: Arduino iOS 传感器应用
slug: ios-sensor-apps-with-arduino
toc:
- - '#'
  - 使用 Arduino 开发 iOS 传感器应用
- - '##'
  - 阿拉斯代尔·艾伦
- - '##'
  - 布莱恩·杰普森
- - '##'
  - 肖恩·华莱士
- - '#'
  - 前言
- - '##'
  - 谁应该阅读本书？
- - '##'
  - 你应该具备哪些知识？
- - '###'
  - 注意
- - '##'
  - 你将学到什么？
- - '##'
  - 本书内容概览
- - '##'
  - 本书使用的约定
- - '###'
  - 注意
- - '###'
  - 提示
- - '##'
  - 使用代码示例
- - '###'
  - 提示
- - '##'
  - Safari® 在线图书
- - '###'
  - 注意
- - '##'
  - 如何联系我们
- - '#'
  - 第 1 章 Arduino 简介
- - '##'
  - Arduino 平台
- - '###'
  - 注意
- - '##'
  - 为电路板供电
- - '##'
  - 输入与输出
- - '###'
  - 注意
- - '##'
  - 与电路板通信
- - '##'
  - 安装软件
- - '###'
  - 注意
- - '##'
  - 连接开发板
- - '##'
  - 点亮 LED
- - '###'
  - 备注
- - '##'
  - 上传草图
- - '##'
  - 建立串行连接
- - '##'
  - 总结
- - '#'
  - 第 2 章 将 iPhone 连接到 Arduino
- - '##'
  - Apple MFi 计划
- - '###'
  - 注意
- - '##'
  - Redpark 串行电缆
- - '###'
  - 注意
- - '##'
  - 测试线缆
- - '##'
  - 连接到 Arduino
- - '###'
  - 警告
- - '##'
  - 连接到 iOS 设备
- - '##'
  - 一个简单的串行应用
- - '###'
  - 添加 Redpark 串行库
- - '###'
  - 连接 Arduino
- - '###'
  - 向 Arduino 发送数据
- - '##'
  - 日志消息
- - '##'
  - 总结
- - '#'
  - 第 3 章 从 iPad 控制 Arduino
- - '##'
  - 在你的 iPad 上运行 Arduino
- - '###'
  - 添加串行库
- - '###'
  - 构建用户界面
- - '####'
  - 备注
- - '##'
  - 集成串行库
- - '##'
  - 在 Arduino 上监听消息
- - '##'
  - 整合所有内容
- - '##'
  - 更进一步
- - '###'
  - 添加日志窗口
- - '##'
  - 总结
- - '#'
  - 第 4 章 使用 iPhone 的外部传感器
- - '##'
  - LV-MaxSonar-EZ1 超声波测距传感器
- - '###'
  - 注
- - '##'
  - 模拟输出
- - '##'
  - 脉宽输出
- - '###'
  - 注
- - '##'
  - RS-232 串行输出
- - '###'
  - 注
- - '##'
  - 适用于 iPhone 的 MaxSonar 测距仪
- - '###'
  - 添加串行库
- - '###'
  - CorePlot 库
- - '####'
  - 注
- - '####'
  - 从源代码编译 Core Plot 库
- - '####'
  - 将 Core Plot 库添加到项目中
- - '###'
  - 构建用户界面
- - '####'
  - 警告
- - '##'
  - 构建后端
- - '###'
  - 编写 Arduino 程序
- - '###'
  - 组装全部组件
- - '###'
  - 控制开关
- - '##'
  - 直接连接线缆
- - '#'
  - 第 5 章 连接至 XBee 网络
- - '##'
  - XBee 模块
- - '###'
  - Series 1 还是 Series 2？
- - '####'
  - 警告
- - '###'
  - 普通版还是 Pro 版？
- - '###'
  - 802.15.4 还是 ZigBee？
- - '###'
  - 选择哪种天线？
- - '##'
  - 如何配置 XBee Series 1 无线电模块
- - '###'
  - 注意
- - '##'
  - 将 XBee 连接到你的 Mac
- - '###'
  - 注意
- - '###'
  - 注意
- - '##'
  - XBee 寻址
- - '##'
  - 配置两个 XBee 无线电模块
- - '##'
  - 将 XBee 连接到 Arduino
- - '###'
  - 警告
- - '##'
  - 将 XBee 连接到 iOS 设备
- - '###'
  - XBee 转 RS-232 串行接口
- - '###'
  - 进一步探索
- - '#'
  - 第 6 章 其他连接方式
- - '##'
  - 使用网络
- - '###'
  - 使用以太网
- - '####'
  - 注意
- - '##'
  - 解析 JSON
- - '##'
  - 使用 WiFi
- - '##'
  - 使用软调制解调器
- - '###'
  - Switch Science 板
- - '####'
  - 警告
- - '###'
  - HiJack 板
- - '##'
  - 使用 MIDI 协议
- - '###'
  - 注意
- - '##'
  - HIDDUINO
- - '###'
  - 注意
- - '##'
  - 总结
- - '#'
  - 关于作者
