name: Learn iOS 7 App Development
name_cn: iOS 7 应用开发入门指南
slug: learn-ios-7-app-development
toc:
- - '#'
  - 学习 iOS 应用开发
- - '##'
  - 关于作者
- - '##'
  - 关于技术审校
- - '##'
  - 引言
- - '#'
  - 本书适合哪些读者？
- - '#'
  - 老派风格 vs. 潮到没朋友
- - '#'
  - 如何使用本书
- - '#'
  - 目录
- - '##'
  - 第 1 章：有工具了吗？ 1
- - '##'
  - 第 2 章：砰！App 17
- - '##'
  - 第 3 章：织一个网页 57
- - '##'
  - 第 4 章：即将发生的事件 97
- - '##'
  - 第 5 章：餐桌礼仪 137
- - '##'
  - 第 6 章：对象课程 177
- - '##'
  - 第 7 章：笑一笑！ 189
- - '##'
  - 第 8 章：模范公民 217
- - '##'
  - 第 9 章：甜美音乐 255
- - '##'
  - 第 10 章：有视图了吗？ 291
- - '##'
  - 第 11 章：给我画一幅画 321
- - '##'
  - 第 12 章：去了又回 367
- - '##'
  - 第 13 章：网络，社交类 411
- - '##'
  - 第 14 章：网络，技术类 429
- - '##'
  - 第 15 章：如果你构建它…… 485
- - '##'
  - 第 16 章：有个性的 App 507
- - '##'
  - 第 17 章：你在哪里？ 529
- - '##'
  - 第 18 章：还记得我吗？ 551
- - '##'
  - 第 19 章：医生，你是说存储 581
- - '##'
  - 第 20 章：保持客观 617
- - '##'
  - 第 21 章：房间里的大象 653
- - '##'
  - 第 22 章：你会说多种语言吗？ 671
- - '##'
  - 第 23 章：更快，更快 691
- - '##'
  - 第 24 章：加倍精彩 713
- - '##'
  - 索引 735
- - '#'
  - 内容速览
- - '#'
  - 1. 准备好了吗？
- - '##'
  - 摘要
- - '##'
  - 要求
- - '##'
  - 安装 Xcode
- - '##'
  - 什么是 Xcode？
- - '#'
  - 成为 iOS 开发者
- - '#'
  - 获取项目文件
- - '#'
  - 首次启动 Xcode
- - '#'
  - 欢迎使用 Xcode
- - '##'
  - 导航区
- - '###'
  - 编辑器区域
- - '###'
  - 实用工具区域
- - '###'
  - 调试区域
- - '###'
  - 工具栏
- - '##'
  - 运行您的第一个应用
- - '#'
  - 总结
- - '#'
  - 第二章：Boom！应用
- - '##'
  - 摘要
- - '##'
  - 设计
- - '##'
  - 创建项目
- - '##'
  - 设置项目属性
- - '##'
  - 构建界面
- - '###'
  - 添加对象
- - '###'
  - 删除和连接对象
- - '###'
  - 向视图中添加视图
- - '###'
  - 编辑对象属性
- - '###'
  - 添加资源
- - '###'
  - 自定义按钮
- - '##'
  - 使用故事板
- - '###'
  - 添加新屏幕
- - '###'
  - 创建 Segue
- - '###'
  - 设置导航标题
- - '##'
  - 测试你的界面
- - '##'
  - 完善你的应用
- - '##'
  - 调试你的应用
- - '###'
  - 添加约束
- - '###'
  - 测试你的应用
- - '##'
  - 总结
- - '#'
  - 3. 转动网络
- - '##'
  - 设计
- - '##'
  - 创建项目
- - '##'
  - 构建网页浏览器
- - '##'
  - 编写网页浏览器的代码
- - '###'
  - 为 `SUViewController` 添加输出口
- - '###'
  - 连接自定义输出口
- - '###'
  - 为 SUViewController 添加操作
- - '###'
  - 设置操作连接
- - '###'
  - 测试网页浏览器
- - '###'
  - 调试 Web 视图
- - '#'
  - 添加 URL 缩短功能
- - '##'
  - 设计 URL 缩短代码
- - '###'
  - 成为 Web 视图委托
- - '###'
  - 缩短 URL
- - '###'
  - 编写 `-shortenURL:`
- - '###'
  - URL 字符串编码
- - '###'
  - 添加私有实例变量
- - '###'
  - 成为 `NSURLConnection` 的委托
- - '###'
  - 测试服务
- - '##'
  - 收尾工作
- - '###'
  - 清理界面
- - '###'
  - 创建 iPad 版本
- - '##'
  - 总结
- - '##'
  - 4. 即将发生的事件
- - '#'
  - 运行循环
- - '##'
  - 事件队列
- - '##'
  - 事件传递
- - '###'
  - 直接传递
- - '###'
  - 命中测试
- - '###'
  - 第一响应者
- - '##'
  - 事件处理
- - '#'
  - 响应者链
- - '##'
  - 有条件地处理事件
- - '##'
  - 高级事件与低级事件
- - '##'
  - 八球
- - '###'
  - 设计
- - '###'
  - 创建项目
- - '###'
  - 创建界面
- - '###'
  - 编写代码
- - '###'
  - 处理摇动事件
- - '###'
  - 测试你的八球应用
- - '###'
  - 第一响应者与响应者链
- - '###'
  - 最后的润色
- - '#'
  - 在实体 iOS 设备上测试
- - '#'
  - 响应者链的其他用途
- - '#'
  - Touchy
- - '##'
  - 设计
- - '##'
  - 创建项目
- - '###'
  - 创建自定义视图
- - '###'
  - 处理触摸事件
- - '###'
  - 绘制你的视图
- - '###'
  - 在 Interface Builder 中添加自定义对象
- - '###'
  - 测试 Touchy
- - '#'
  - 高级事件处理
- - '##'
  - 总结
- - '##'
  - 练习题
- - '#'
  - 5. 餐桌礼仪
- - '##'
  - 表格视图
- - '###'
  - 纯表格
- - '###'
  - 分组表格
- - '###'
  - 单元格样式
- - '###'
  - 单元格辅助视图
- - '###'
  - 自定义单元格
- - '##'
  - 表格视图的工作原理
- - '###'
  - 表格单元格与橡皮图章
- - '##'
  - MyStuff
- - '###'
  - 设计
- - '###'
  - 创建项目
- - '###'
  - 创建你的数据模型
- - '###'
  - 创建数据源
- - '###'
  - 实现你的橡皮图章
- - '###'
  - 表格单元格缓存
- - '####'
  - 单元格对象标识符与重用
- - '###'
  - 数据在哪里？
- - '###'
  - 测试 `MyStuff`
- - '##'
  - 添加详情视图
- - '###'
  - 创建详情视图
- - '###'
  - 配置详情视图
- - '##'
  - 编辑
- - '###'
  - 插入和移除项目
- - '###'
  - 启用表格编辑
- - '###'
  - 编辑详情
- - '###'
  - 观察 MyWhatsit 的变更
- - '####'
  - 发布通知
- - '#'
  - 观察通知
- - '##'
  - 通知匹配
- - '##'
  - 模态编辑与非模态编辑
- - '##'
  - 细节打磨
- - '#'
  - 高级表格视图专题
- - '#'
  - 总结
- - '#'
  - 实物教学
- - '##'
  - 两家世仇，同样尊贵
- - '#'
  - 罗密欧遇见朱丽叶
- - '##'
  - 类与饼干
- - '##'
  - 类、对象和方法，哦天哪！
- - '#'
  - 继承
- - '##'
  - 抽象类与具体类
- - '##'
  - 方法重写
- - '#'
  - 设计模式与原则
- - '##'
  - 封装
- - '#'
  - 目标的唯一性
- - '#'
  - 稳定性
- - '#'
  - 开闭原则
- - '#'
  - 委托模式
- - '###'
  - 其他模式
- - '##'
  - 总结
- - '#'
  - 7. 笑一个！
- - '##'
  - 设计
- - '##'
  - 扩展你的设计
- - '###'
  - 修改数据模型
- - '###'
  - 添加图像视图
- - '###'
  - 更新视图控制器
- - '###'
  - 连接“选择图片”操作
- - '##'
  - 拍照
- - '###'
  - 鱼与熊掌不可兼得
- - '###'
  - 展示图片选择器
- - '###'
  - 导入图像
- - '###'
  - 裁剪与缩放
- - '###'
  - 收尾工作
- - '###'
  - 测试相机
- - '##'
  - 构建 iPad 界面
- - '###'
  - 添加弹出框
- - '##'
  - 粘性键盘
- - '##'
  - 高级相机技术
- - '##'
  - 总结
- - '##'
  - 练习
- - '#'
  - 8. 模范公民
- - '##'
  - 模型-视图-控制器设计模式
- - '###'
  - 数据模型对象
- - '###'
  - 视图对象
- - '###'
  - 控制器对象
- - '###'
  - MVC 通信模式
- - '##'
  - 颜色模型
- - '###'
  - 创建数据模型
- - '###'
  - 创建视图对象
- - '###'
  - 编写控制器
- - '###'
  - 连接你的界面
- - '##'
  - 拥有多个视图
- - '#'
  - 整合更新
- - '#'
  - 复杂视图对象
- - '##'
  - 用 CMColorView 替换 UIView
- - '##'
  - 将视图连接到数据模型
- - '###'
  - 绘制 `CMColorView`
- - '##'
  - 成为 K-V 观察者
- - '#'
  - 键值观察
- - '##'
  - 观察键值变化
- - '#'
  - 创建 KVO 依赖
- - '##'
  - 多向量数据模型变更
- - '###'
  - 处理触摸事件
- - '###'
  - 绑定滑块
- - '###'
  - 最终润色
- - '##'
  - 取巧做法
- - '##'
  - 总结
- - '###'
  - 练习题
- - '#'
  - 9. 美妙旋律
- - '##'
  - 摘要
- - '##'
  - 制作你自己的 iPod
- - '###'
  - 设计
- - '###'
  - 添加音乐选择器
- - '###'
  - 排版后的内容
- - '##'
  - 查询 iPod 音乐库
- - '###'
  - 使用音乐播放器
- - '###'
  - 应用与 iPod 音乐播放器
- - '###'
  - 添加播放控制
- - '###'
  - 接收音乐播放器通知
- - '###'
  - MVC 的体现
- - '###'
  - 添加媒体元数据
- - '####'
  - 创建元数据视图
- - '###'
  - 观察播放项目
- - '##'
  - 制造一些声音
- - '###'
  - 置身于更广阔的世界
- - '###'
  - 配置你的音频会话
- - '###'
  - 播放音频文件
- - '###'
  - 创建 `AVAudioPlayer` 对象
- - '###'
  - 添加声音按钮
- - '###'
  - 激活音频会话
- - '##'
  - 中断与旁路
- - '###'
  - 处理中断
- - '###'
  - 添加中断处理器
- - '###'
  - 处理音频线路变化
- - '###'
  - 其他音频主题
- - '###'
  - 总结
- - '#'
  - 10. 有视图了？
- - '##'
  - 摘要
- - '#'
  - 通过示例学习
- - '##'
  - 按钮
- - '###'
  - 响应者与视图类
- - '###'
  - 控件类
- - '###'
  - 按钮类型
- - '###'
  - 控制状态
- - '###'
  - 按钮代码
- - '##'
  - 开关和滑块
- - '#'
  - 页面控件
- - '#'
  - 步进器
- - '#'
  - 分段控件
- - '#'
  - 进度指示器
- - '#'
  - 文本视图
- - '###'
  - 标签
- - '###'
  - 文本字段
- - '#'
  - 文本编辑行为
- - '#'
  - 文本视图
- - '#'
  - 选择器
- - '##'
  - 日期选择器
- - '###'
  - 任意选择器
- - '###'
  - 图像视图
- - '###'
  - 分组表格
- - '#'
  - 你从未见过的视图
- - '##'
  - 滚动视图与键盘
- - '##'
  - 摘要
- - '#'
  - 11. 为我画一幅画
- - '##'
  - 摘要
- - '##'
  - 创建自定义视图类
- - '###'
  - 视图坐标
- - '#'
  - Frame 与 Bounds
- - '##'
  - 在坐标系之间转换
- - '##'
  - 视图何时被绘制
- - '###'
  - 绘制一个 `View`
- - '###'
  - 填充函数与描边函数
- - '###'
  - 贝塞尔曲线
- - '###'
  - 图片
- - '#'
  - Shapely
- - '##'
  - 以编程方式创建视图
- - '###'
  - '`-drawRect:` 方法'
- - '####'
  - 创建贝塞尔路径
- - '###'
  - 避免像素炎：坐标与像素
- - '###'
  - 测试方形
- - '###'
  - 更多形状，更多色彩
- - '##'
  - 变换
- - '###'
  - 应用平移变换
- - '#'
  - 手势处理与变换
- - '##'
  - 应用缩放变换
- - '#'
  - 动画：不仅仅是漫画的专利
- - '###'
  - 使用 Core Animation
- - '###'
  - 为 Shapely 添加动画
- - '###'
  - OpenGL
- - '##'
  - 层次顺序
- - '###'
  - 排查双击颜色变化问题
- - '###'
  - 修复方法
- - '###'
  - 处理手势识别器冲突
- - '###'
  - 重要提示
- - '###'
  - 总结
- - '##'
  - 图像与位图
- - '###'
  - 从位图创建图像
- - '#'
  - 从绘图创建位图
- - '##'
  - 高级图形
- - '###'
  - 文本
- - '###'
  - 阴影、渐变和图案
- - '###'
  - 混合模式
- - '###'
  - 上下文堆栈
- - '##'
  - 摘要
- - '##'
  - 练习
- - '#'
  - 12. 去而复返
- - '##'
  - 摘要
- - '##'
  - 三思而后行
- - '###'
  - 什么是导航？
- - '###'
  - 视图控制器的角色
- - '##'
  - 设计仙境
- - '###'
  - 权衡导航选项
- - '###'
  - Wonderland 导航
- - '##'
  - 创建 Wonderland
- - '###'
  - 添加仙境项目的资源
- - '###'
  - 配置标签栏项
- - '##'
  - 第一个内容视图控制器
- - '###'
  - 呈现模态视图控制器
- - '###'
  - 关闭视图控制器
- - '##'
  - 创建可导航的表格视图
- - '###'
  - 为表格视图注入数据
- - '###'
  - 创建详情视图
- - '###'
  - 添加数据模型
- - '###'
  - 实现数据源
- - '###'
  - 定义表格视图单元格对象
- - '###'
  - 推送详细视图控制器
- - '#'
  - 创建页面视图控制器
- - '##'
  - 添加页面视图控制器
- - '##'
  - 设计原型页面
- - '###'
  - 编写单页视图
- - '###'
  - 分页器
- - '####'
  - 代码清单 12-1. WLPaginator.h
- - '####'
  - 代码清单 12-2. WLPaginator.m
- - '###'
  - 编写页面视图数据源
- - '###'
  - 初始化页面视图控制器
- - '###'
  - 使用弹出控制器
- - '###'
  - 高级导航
- - '###'
  - 总结
- - '#'
  - 13. 网络社交
- - '##'
  - 摘要
- - '##'
  - 色彩（社交）世界
- - '###'
  - 准备分享内容
- - '#'
  - 显示活动视图控制器
- - '##'
  - UIACTIVITYVIEWCONTROLLER 与 IPAD
- - '##'
  - 分享更多内容
- - '###'
  - 提取代码
- - '###'
  - 提供更多可分享项目
- - '###'
  - 排除活动
- - '##'
  - 最小公分母的诅咒
- - '###'
  - 提供活动特定数据
- - '###'
  - 承诺与约定
- - '###'
  - 大数据
- - '##'
  - 与特定服务分享
- - '#'
  - 其他社交网络互动
- - '##'
  - 总结
- - '#'
  - 14. 网络，技术宅的那种
- - '##'
  - 摘要
- - '##'
  - SunTouch
- - '###'
  - 创建 SunTouch
- - '###'
  - 设计初始屏幕
- - '##'
  - 创建单人版本
- - '###'
  - '`STGameViewController` 加载'
- - '###'
  - '`SunTouch` 的工作原理'
- - '###'
  - 自定义核心动画
- - '###'
  - 开始游戏
- - '##'
  - 接入 Game Center
- - '###'
  - 配置支持 Game Center 的应用
- - '###'
  - 启用 Game Center
- - '###'
  - 在 iTunes Store 中创建应用
- - '###'
  - 配置 Game Center
- - '###'
  - 向您的应用添加 GameKit
- - '###'
  - 获取本地玩家
- - '###'
  - 添加 Game Center 按钮
- - '###'
  - 记录排行榜分数
- - '###'
  - 创建测试玩家
- - '##'
  - 对等网络
- - '###'
  - 将 SunTouch 变成双人游戏
- - '##'
  - 子类化 `STGameView`
- - '##'
  - 添加对手游戏视图
- - '#'
  - 杂项与收尾
- - '##'
  - 匹配机制
- - '#'
  - 请求匹配
- - '##'
  - 完成匹配
- - '###'
  - 与另一台设备交换数据
- - '###'
  - 开始游戏
- - '###'
  - 创建数据消息传递分类
- - '####'
  - 定义数据格式
- - '###'
  - 序列化与跨平台通信
- - '##'
  - 向玩家发送数据
- - '##'
  - 从玩家处接收数据
- - '####'
  - 发送打击数据
- - '####'
  - 接收打击数据
- - '####'
  - 发送太阳捕获数据
- - '####'
  - 接收太阳捕获数据
- - '####'
  - 处理比赛中断
- - '####'
  - 测试双人游戏
- - '##'
  - 高级网络
- - '##'
  - 最后一点细节
- - '#'
  - 总结
- - '##'
  - 练习
- - '#'
  - 15. 如果你构建了它……
- - '##'
  - 摘要
- - '##'
  - Interface Builder 文件的工作原理
- - '#'
  - 编译界面构建器文件
- - '##'
  - 加载场景
- - '##'
  - 加载 `.xib` 文件
- - '##'
  - 占位对象与文件所有者
- - '###'
  - 创建对象
- - '###'
  - 任意对象及其属性
- - '###'
  - 编辑属性
- - '###'
  - 连接
- - '###'
  - 发送操作消息
- - '##'
  - 掌控 Interface Builder 文件
- - '###'
  - 声明占位对象
- - '###'
  - 设计 `SYShapeView`
- - '###'
  - 连接手势识别器
- - '###'
  - 构建你的形状工厂
- - '###'
  - 加载 Interface Builder 文件
- - '###'
  - 替换代码
- - '##'
  - 总结
- - '#'
  - 16. 有态度的应用
- - '##'
  - 水平仪
- - '###'
  - 创建 Leveler
- - '#'
  - 深入探究 LRDialView
- - '#'
  - 创建视图
- - '#'
  - 排版后内容
- - '##'
  - 获取运动数据
- - '###'
  - 创建 CMMotionManager
- - '###'
  - 启动和停止更新
- - '#'
  - 推拉之间
- - '#'
  - 时机决定一切
- - '###'
  - 抖动问题
- - '###'
  - 使用动态动画
- - '###'
  - 创建动态动画器
- - '#'
  - 定义行为
- - '#'
  - 动画化拨号盘
- - '##'
  - 获取其他类型的运动数据
- - '###'
  - 陀螺仪数据
- - '###'
  - 磁力计数据
- - '###'
  - 设备运动与姿态
- - '#'
  - 初识设备运动接口
- - '##'
  - 测量变化
- - '##'
  - 总结
- - '#'
  - 17. 你在哪？
- - '##'
  - 摘要
- - '##'
  - 创建 Pigeon 应用
- - '##'
  - 收集位置数据
- - '##'
  - 使用地图视图
- - '#'
  - 装饰你的地图
- - '##'
  - 添加标注
- - '##'
  - 地图坐标
- - '###'
  - 添加一点弹跳效果
- - '##'
  - 指引方向
- - '#'
  - 位置监控
- - '##'
  - 近似位置与非 GPS 设备
- - '##'
  - 监控区域
- - '##'
  - 减少位置变化消息
- - '##'
  - 移动与方向
- - '##'
  - 地理编码
- - '#'
  - 获取路线指引
- - '#'
  - 总结
- - '#'
  - 练习
- - '#'
  - 18. 记住我？
- - '##'
  - 摘要
- - '##'
  - 属性列表
- - '##'
  - 序列化属性列表
- - '##'
  - 用户默认设置
- - '##'
  - 让 Pigeon 学会记忆
- - '###'
  - 最小化更新与代码量
- - '###'
  - 定义键
- - '###'
  - 将数值写入用户默认设置
- - '###'
  - 从用户默认设置中获取数值
- - '###'
  - 测试用户默认设置
- - '##'
  - 注册默认值
- - '#'
  - 将对象转换为属性列表对象
- - '#'
  - 保存与恢复`savedLocation`
- - '##'
  - 持久化视图
- - '###'
  - 淡入后台
- - '###'
  - 保留视图控制器
- - '###'
  - 指定恢复标识符
- - '###'
  - 自定义恢复
- - '###'
  - 更深层次的恢复
- - '#'
  - 云端之鸽
- - '##'
  - 在云端存储值
- - '###'
  - 云端监听
- - '###'
  - 启用 iCloud
- - '###'
  - 测试云同步
- - '##'
  - 打包你的设置
- - '###'
  - 创建一个设置包
- - '###'
  - 使用设置捆绑包的值
- - '###'
  - 测试设置捆绑包
- - '##'
  - 总结
- - '##'
  - 练习
- - '#'
  - 19. 文档，你是说存储
- - '##'
  - 摘要
- - '#'
  - 文档概览
- - '#'
  - 我的文档都去哪儿了？
- - '##'
  - 文档中的 MyStuff
- - '#'
  - 提供文档的数据
- - '##'
  - 打包你的数据
- - '##'
  - 使用包装器
- - '###'
  - 增量式文档更新
- - '###'
  - 构建你的封装器
- - '###'
  - 解读你的封装器
- - '###'
  - 其他存储方案
- - '###'
  - 归档对象
- - '###'
  - 采用 `NSCoding`
- - '###'
  - 子类化一个 `<NSCoding>` 类
- - '###'
  - 归档与解归档对象
- - '###'
  - 归档序列化对决
- - '###'
  - 序列化与归档的相遇
- - '####'
  - 注意事项
- - '##'
  - 文档化你的数据模型
- - '####'
  - 注意
- - '####'
  - 提示
- - '##'
  - 跟踪变更
- - '#'
  - 测试你的文档
- - '##'
  - 设置断点
- - '##'
  - 单步执行代码并检查变量
- - '###'
  - 问题剖析
- - '###'
  - 定义委托协议
- - '###'
  - 实现委托回调
- - '###'
  - 视图控制器采纳协议
- - '##'
  - 存储图像文件
- - '##'
  - 未尽事宜
- - '#'
  - iCloud 存储
- - '#'
  - 存档版本控制
- - '#'
  - 总结
- - '#'
  - 练习
- - '##'
  - 脚注
- - '#'
  - 20. 保持客观
- - '##'
  - Objective‑C 就是 C
- - '##'
  - Objective‑C 类
- - '###'
  - 实现你的类
- - '###'
  - 创建和销毁对象
- - '###'
  - 类簇
- - '###'
  - 引用对象
- - '###'
  - 让我看看你的 `id`？
- - '##'
  - 方法名称
- - '###'
  - 方法名称构造
- - '###'
  - +initialize 方法
- - '##'
  - 属性
- - '###'
  - 实例变量
- - '###'
  - 使用 Getter 和 Setter
- - '###'
  - 声明的属性
- - '###'
  - 自动合成属性
- - '###'
  - 属性的构成
- - '####'
  - 可变性
- - '####'
  - 存储
- - '####'
  - 生命周期限定符
- - '####'
  - 访问器方法名称
- - '####'
  - 原子性
- - '###'
  - 信守承诺
- - '##'
  - 自省
- - '###'
  - 类
- - '###'
  - 方法
- - '###'
  - 协议
- - '##'
  - 协议
- - '###'
  - 采用协议
- - '###'
  - 引用遵循协议的对象
- - '##'
  - 分类
- - '###'
  - 单一职责
- - '###'
  - 模块组织
- - '###'
  - 私有方法
- - '###'
  - 扩展（Extension）
- - '##'
  - nil 是你的朋友
- - '###'
  - nil 的轻灵
- - '###'
  - 正面表述的优点
- - '###'
  - nil 的坏处
- - '#'
  - 拷贝对象
- - '##'
  - 遵循 `NSCopying`
- - '##'
  - 继承 `NSCopying`
- - '##'
  - 拷贝特殊对象
- - '##'
  - 拷贝对象
- - '##'
  - 可变拷贝
- - '#'
  - 属性字符串
- - '#'
  - 集合
- - '###'
  - 集合类
- - '###'
  - 枚举
- - '####'
  - 快速对象枚举
- - '####'
  - 集合枚举
- - '###'
  - 快捷方式
- - '#'
  - 总结
- - '#'
  - 21. 房间里的“大象”
- - '##'
  - 摘要
- - '##'
  - 内存管理
- - '#'
  - 你祖父级的内存管理
- - '##'
  - 垃圾回收
- - '#'
  - 引用计数
- - '#'
  - 手动引用计数
- - '###'
  - 跳入池中
- - '###'
  - 快速总结
- - '###'
  - 打破循环
- - '###'
  - 恐慌避雷
- - '##'
  - 自动引用计数
- - '###'
  - 启用 ARC
- - '#'
  - ARC 做不到的事
- - '#'
  - 总结
- - '#'
  - 22. 你会说多种语言吗？
- - '##'
  - 摘要
- - '#'
  - 本地化流程
- - '##'
  - 语言包
- - '###'
  - 程序化本地化
- - '#'
  - 即刻开始本地化！
- - '##'
  - 国际化你的应用
- - '###'
  - 国际化字符串常量
- - '###'
  - 使用 `genstrings` 工具
- - '###'
  - 本地化你的字符串文件
- - '###'
  - 测试你的字符串本地化
- - '#'
  - 使用可本地化字符串实现界面本地化
- - '#'
  - 本地化 `Settings.bundle`
- - '#'
  - 其他代码注意事项
- - '##'
  - 本地化你的应用名称
- - '##'
  - 总结
- - '#'
  - 23. 更快，更快
- - '##'
  - 摘要
- - '##'
  - 性能优化
- - '#'
  - 修复缓慢的点击响应
- - '##'
  - 启动 Instruments
- - '#'
  - 寻找热点区域
- - '##'
  - 经验带来的自负
- - '###'
  - 摘取低垂的果实
- - '###'
  - 延迟通知
- - '###'
  - 再战一轮
- - '#'
  - 珍贵的内存
- - '##'
  - 压垮 MyStuff
- - '##'
  - 测量内存
- - '###'
  - 内存分析工具
- - '###'
  - 重视警告
- - '#'
  - 压力测试，第 2 轮
- - '##'
  - Allocations 工具
- - '##'
  - 总结
- - '#'
  - 24. 加倍美好
- - '##'
  - 摘要
- - '##'
  - 向 App Store 提交应用
- - '##'
  - 并发编程
- - '###'
  - 线程
- - '###'
  - 同步
- - '##'
  - 运行多个线程
- - '###'
  - 创建操作队列
- - '###'
  - 添加操作
- - '###'
  - 测量效果
- - '##'
  - 执行顺序
- - '##'
  - 线程安全
- - '###'
  - 别谈线程安全
- - '###'
  - 不共享就是关爱
- - '###'
  - 答应我永不改变
- - '###'
  - 原子时代
- - '#'
  - 创建原子方法
- - '#'
  - 创建原子属性
- - '###'
  - 使非原子方法变为原子操作
- - '##'
  - 并发工具概览
- - '###'
  - 线程安全概览
- - '###'
  - 向主线程发送消息
- - '###'
  - 锁对象
- - '###'
  - 死锁
- - '####'
  - 递归锁
- - '####'
  - 多重锁
- - '###'
  - 自旋锁
- - '###'
  - 延伸阅读
- - '##'
  - 总结
- - '#'
  - 学习 iOS 应用开发
- - '##'
  - 索引
- - '##'
  - A
- - '###'
  - 访问器方法
- - '###'
  - 辅助视图
- - '###'
  - 临时分发
- - '###'
  - 动画
- - '###'
  - 应用程序音乐播放器
- - '###'
  - 应用程序编程接口（API）
- - '###'
  - 应用
- - '###'
  - 水平仪（参见水平仪）
- - '###'
  - 运动数据
- - '###'
  - 任意对象
- - '###'
  - 归档序列化
- - '###'
  - 原子时代
- - '###'
  - 属性字符串
- - '###'
  - 自动属性
- - '###'
  - 自动引用计数（ARC）
- - '###'
  - 自动保存文档模型
- - '##'
  - B
- - '###'
  - Bonjour
- - '##'
  - C
- - '###'
  - 类簇
- - '###'
  - '`CLLocationManager`'
- - '###'
  - 云存储
- - '###'
  - 代码重构
- - '###'
  - 集合
- - '###'
  - 并发
- - '###'
  - 并发编程（参见线程）
- - '###'
  - 控制器，Interface Builder
- - '###'
  - 坐标与像素
- - '###'
  - 坐标系
- - '###'
  - 自定义视图对象（参见动画；绘制简单形状；变换）
- - '###'
  - 绘制的贝塞尔路径
- - '###'
  - 事件驱动程序练习
- - '###'
  - 图形
- - '###'
  - 图像与位图
- - '###'
  - 制作形状应用
- - '##'
  - D
- - '###'
  - 悬空指针错误
- - '###'
  - 数据网络（参见网络）
- - '###'
  - 死锁
- - '###'
  - 委托模式
- - '###'
  - 设计模式与原则
- - '###'
  - 文档
- - '###'
  - 绘制简单形状
- - '###'
  - 动态动画器
- - '##'
  - E, F
- - '###'
  - 封装
- - '###'
  - 枚举方法
- - '###'
  - 事件
- - '###'
  - 魔法八号球应用
- - '###'
  - 触控应用
- - '##'
  - G
- - '###'
  - 支持 Game Center
- - '###'
  - 垃圾回收
- - '###'
  - Getter 方法
- - '###'
  - 全球定位系统（GPS）
- - '###'
  - 地图装饰
- - '###'
  - 鸽子创建设计
- - '###'
  - Grand Central Dispatch（GCD）
- - '###'
  - 组尾
- - '###'
  - 组头
- - '##'
  - H
- - '###'
  - 热点
- - '##'
  - I, J
- - '###'
  - iCloud
- - '###'
  - 继承
- - '###'
  - '`Inherits NSCopying`'
- - '###'
  - '`+initialize` 方法'
- - '###'
  - 实例方法
- - '###'
  - 实例变量
- - '###'
  - Instruments
- - '###'
  - 集成开发环境（IDE）
- - '###'
  - Interface Builder
- - '###'
  - 内省
- - '##'
  - K
- - '###'
  - 键值观察（KVO）
- - '##'
  - L
- - '###'
  - 学习 iOS 开发项目
- - '###'
  - 水平仪
- - '###'
  - 逻辑地址空间
- - '##'
  - M
- - '###'
  - 手动引用计数
- - '###'
  - 地图装饰
- - '###'
  - 内存
- - '###'
  - 内存泄漏
- - '###'
  - 内存管理（参见自动引用计数（ARC））
- - '###'
  - 内存压力
- - '###'
  - 方法名称
- - '###'
  - 方法签名
- - '###'
  - 模型-视图-控制器设计模式
- - '###'
  - 多线程
- - '###'
  - 多任务/多线程
- - '###'
  - MyStuff 应用
- - '##'
  - N
- - '###'
  - 导航视图控制器
- - '###'
  - 网络（参见对等网络）
- - '###'
  - 下一代 Interface Builder（NIB）
- - '###'
  - nil
- - '###'
  - nil 不好
- - '###'
  - '`NSCopying`'
- - '###'
  - '`NSFileWrapper`'
- - '###'
  - '`NSNotificationQueue`'
- - '##'
  - O
- - '###'
  - Objective-C
- - '###'
  - 面向对象语言
- - '###'
  - 对象
- - '###'
  - 观察者模式
- - '###'
  - 开闭原则
- - '##'
  - P, Q
- - '###'
  - 对等网络
- - '###'
  - SunTouch 的通信
- - '###'
  - 持久化视图
- - '###'
  - 鸽子创建设计
- - '###'
  - 过程式语言
- - '###'
  - 属性列表对象
- - '###'
  - 协议
- - '##'
  - R
- - '###'
  - 引用计数
- - '###'
  - 请求评议（RFC）
- - '##'
  - S
- - '###'
  - Segue
- - '###'
  - Setter 方法
- - '###'
  - 单人游戏
- - '###'
  - 单一职责原则
- - '###'
  - 社交网络
- - '###'
  - 社交工作（参见网络）
- - '###'
  - 软件开发工具包（SDK）
- - '###'
  - 速度优化（参见 Instruments）
- - '###'
  - 故事板
- - '###'
  - 强引用与弱引用
- - '###'
  - SunTouch 创建设计
- - '###'
  - 超现实主义应用
- - '###'
  - 同步
- - '##'
  - T
- - '###'
  - 表格编辑
- - '###'
  - 表格
- - '###'
  - 表格视图单元格
- - '###'
  - 任务切换
- - '###'
  - 测试
- - '###'
  - 线程
- - '###'
  - 线程安全领域
- - '###'
  - 线程安全
- - '###'
  - 变换
- - '##'
  - U
- - '###'
  - '`UIDocument`'
- - '###'
  - URL 缩短应用
- - '##'
  - V
- - '###'
  - 视图动态
- - '###'
  - 视图对象
- - '##'
  - W
- - '###'
  - 仙境应用设计
- - '##'
  - X, Y, Z
- - '###'
  - Xcode
