name: Pro IOS Apps Performance Optimization and Tuning
name_cn: iOS 应用性能优化与调优高级指南
slug: pro-ios-apps-performance-optimization-and-tuning
toc:
- - '#'
  - iOS 应用性能优化专业指南
- - '#'
  - 目录
- - '##'
  - 关于作者
- - '##'
  - 关于技术审校
- - '#'
  - 前言
- - '#'
  - 第一章：iOS 性能优化简介
- - '##'
  - 智能手机的新时代
- - '##'
  - 为什么性能至关重要
- - '##'
  - 谁应该阅读本书？
- - '##'
  - 我的教学风格
- - '##'
  - 你需要什么？
- - '###'
  - 如何使用本书
- - '###'
  - 本书概述
- - '###'
  - 源代码
- - '###'
  - 联系作者
- - '#'
  - 第二章：使用工具对应用进行基准测试：模拟器与真机测试
- - '##'
  - 模拟器与真机
- - '##'
  - 内存与性能
- - '##'
  - 工具
- - '###'
  - 基础工具
- - '####'
  - 记录运行时间
- - '####'
  - 运行代码示例
- - '###'
  - 内存工具
- - '####'
  - 内存分配
- - '####'
  - 分配
- - '###'
  - 遗留代码
- - '####'
  - 内存泄漏
- - '#####'
  - 静态分析器
- - '#####'
  - Leaks 检测工具
- - '####'
  - 内存垃圾
- - '####'
  - 僵尸对象
- - '###'
  - 性能工具
- - '####'
  - 检测工具应用
- - '####'
  - CPU 测量
- - '####'
  - CPU 采样器
- - '####'
  - 活动监视器
- - '####'
  - 时间测量
- - '#####'
  - 时间分析器
- - '###'
  - 用户界面响应时间测量
- - '####'
  - 核心动画
- - '####'
  - OpenGL ES 驱动
- - '###'
  - 文件和网络访问测量
- - '####'
  - 系统使用情况
- - '####'
  - 文件活动
- - '###'
  - 测量线程性能
- - '###'
  - 电池功耗测量
- - '###'
  - 工具组合
- - '###'
  - 所有工具汇总
- - '##'
  - 本章小结
- - '#'
  - 第三章：提升并优化 UITableView 性能
- - '##'
  - 示例简介
- - '##'
  - 回顾 Instrument 工具
- - '##'
  - 第一个示例
- - '###'
  - 第一个示例简介
- - '###'
  - 标准基准测试
- - '###'
  - 初始基准测试
- - '###'
  - 复用 `UITableViewCell`
- - '####'
  - 标准 TableView 单元格
- - '####'
  - 通过 Interface Builder 自定义 TableView Cell
- - '####'
  - 通过代码自定义 TableView Cell
- - '###'
  - 从 Nib 文件加载 Cell
- - '###'
  - 从自定义代码加载 Cell
- - '###'
  - 再次运行基准测试
- - '###'
  - 重用图片
- - '###'
  - 减少准备时间
- - '###'
  - '`SecondExample`'
- - '###'
  - 从这些示例中能学到什么？
- - '##'
  - 其他技术
- - '###'
  - 缓存高度
- - '###'
  - 不透明度
- - '###'
  - 避免图形效果
- - '###'
  - 编辑/重排序性能
- - '###'
  - 总结
- - '#'
  - 第四章：使用图像与数据缓存技术提升应用性能
- - '##'
  - 网络、文件与内存处理的性能差异
- - '##'
  - 如何识别性能瓶颈
- - '##'
  - 缓存入门
- - '###'
  - 什么是缓存？
- - '###'
  - 缓存命中
- - '###'
  - 缓存未命中
- - '###'
  - 检索成本
- - '###'
  - 存储成本
- - '###'
  - 缓存失效
- - '###'
  - 替换策略
- - '###'
  - 缓存算法
- - '####'
  - 贝拉迪算法
- - '####'
  - 随机替换
- - '####'
  - 先进先出（FIFO）
- - '####'
  - 简单基于时间
- - '####'
  - 最近最少使用（LRU）
- - '####'
  - 最不经常使用（LFU）算法
- - '##'
  - 衡量缓存
- - '###'
  - 你应该缓存什么
- - '####'
  - 你应该将图片存储在哪里？
- - '#####'
  - 临时目录
- - '#####'
  - 缓存目录
- - '#####'
  - 文档目录
- - '###'
  - 相册
- - '###'
  - 应用程序包
- - '##'
  - 数据缓存
- - '###'
  - 存储在 plist/xml/json 中
- - '###'
  - 存储在 CoreData 中
- - '###'
  - 存储在 SQLite 中
- - '###'
  - 何时检查并删除缓存？
- - '###'
  - 内存缓存
- - '###'
  - 全局访问 vs. 严格访问
- - '###'
  - 预加载 vs. 即时加载
- - '###'
  - 总结
- - '#'
  - 第五章：使用算法和数据结构优化你的应用
- - '##'
  - 第一个示例
- - '##'
  - 衡量算法性能的理论问题
- - '###'
  - 如何衡量 Big-O
- - '###'
  - 实现细节
- - '###'
  - 著名算法的 Big-O
- - '##'
  - 实际测量
- - '##'
  - 数据结构与算法
- - '##'
  - Cocoa Touch 数据结构
- - '###'
  - NSMutableArray
- - '###'
  - 哈希
- - '###'
  - Objective-C 中的 isEqual 和 Hash 方法
- - '####'
  - isEqual
- - '####'
  - 哈希方法
- - '###'
  - NSMutableSet
- - '###'
  - NSMutableDictionary
- - '##'
  - 其他数据结构
- - '###'
  - 链表
- - '####'
  - Init
- - '####'
  - 添加对象
- - '####'
  - 获取对象
- - '####'
  - 计数
- - '####'
  - 移除对象
- - '####'
  - 性能分析
- - '###'
  - 栈与队列
- - '####'
  - 栈
- - '####'
  - 队列
- - '###'
  - 二叉树
- - '##'
  - 排序算法
- - '##'
  - 搜索
- - '###'
  - 二分查找
- - '###'
  - 二叉树
- - '####'
  - 节点和边
- - '####'
  - 树
- - '###'
  - 二叉树如何工作？
- - '###'
  - 图
- - '###'
  - 深度优先搜索
- - '###'
  - 广度优先搜索
- - '##'
  - 其他算法与问题解决方法
- - '###'
  - 递归
- - '###'
  - 用于 XML 解析的 SAX/DOM 解析器
- - '##'
  - 本章小结
- - '##'
  - 练习题
- - '#'
  - 第六章：使用多线程技术优化并行数据访问
- - '##'
  - 什么是线程与多线程？
- - '##'
  - 线程术语
- - '##'
  - 第一个示例
- - '##'
  - 多线程的优势
- - '##'
  - 如何编写多线程应用程序
- - '###'
  - 创建线程
- - '####'
  - NSThread
- - '####'
  - 使用 POSIX 线程
- - '####'
  - NSObject
- - '####'
  - NSOperationQueue
- - '#####'
  - NSInvocationOperation
- - '#####'
  - NSBlockOperation
- - '#####'
  - NSOperation
- - '###'
  - 配置线程
- - '###'
  - 你的线程入口点
- - '###'
  - 自动释放池
- - '###'
  - 异常处理器
- - '###'
  - 运行循环
- - '##'
  - 线程的风险
- - '###'
  - 线程安全
- - '####'
  - 问题
- - '####'
  - 解决方案
- - '###'
  - 活性
- - '####'
  - 问题
- - '####'
  - NSLock 解决方案
- - '####'
  - NSCondition 解决方案
- - '####'
  - 死锁
- - '###'
  - 性能
- - '###'
  - 线程同步
- - '##'
  - 线程的替代方案
- - '###'
  - NSTimer
- - '####'
  - 重复定时器与非重复定时器
- - '###'
  - 异步函数
- - '###'
  - 空闲时间通知
- - '##'
  - iPhone 的线程分析工具
- - '##'
  - 总结
- - '#'
  - 第七章：优化内存使用以获得更好的性能
- - '##'
  - 简要回顾
- - '##'
  - 旧版对象所有权策略
- - '##'
  - 自动释放
- - '##'
  - 自动释放池
- - '##'
  - 自动引用计数
- - '##'
  - 如何在 Xcode 中设置你的项目？
- - '###'
  - ARC 策略
- - '###'
  - 用于 ARC 的新限定符
- - '####'
  - 对象属性
- - '####'
  - 变量声明
- - '##'
  - 高级内存问题
- - '###'
  - 保留/循环引用
- - '###'
  - UIViewController
- - '####'
  - 加载视图过程
- - '####'
  - 卸载视图过程
- - '####'
  - 在用户界面中显示与隐藏视图
- - '##'
  - 对象拷贝
- - '###'
  - 浅拷贝 vs. 深拷贝
- - '###'
  - 实现深拷贝
- - '###'
  - 将拷贝方法集成到对象中
- - '##'
  - 高级自动释放池
- - '###'
  - 自动释放池与栈
- - '###'
  - 自动释放池与线程
- - '###'
  - 自动释放池对性能的影响
- - '##'
  - 工具（Instruments）
- - '###'
  - 静态分析器
- - '###'
  - 泄漏检测工具
- - '###'
  - 僵尸对象检测
- - '###'
  - 对象分配追踪
- - '###'
  - 内存警告级别
- - '##'
  - 总结
- - '#'
  - 第八章：集成多线程与高效内存使用以提升多任务应用性能
- - '###'
  - iPhone 中的多任务是什么？
- - '###'
  - 多任务生命周期
- - '####'
  - 多任务处理程序方法
- - '####'
  - 多任务的收益与成本
- - '###'
  - 后台服务
- - '####'
  - 音频服务
- - '####'
  - 显示启动画面
- - '####'
  - 定位服务
- - '#####'
  - 标准定位服务
- - '#####'
  - 重大位置变化
- - '#####'
  - 持续后台位置更新
- - '###'
  - 本地通知
- - '###'
  - 网络语音电话 (VOIP)
- - '###'
  - 后台执行
- - '###'
  - 在后台运行时的注意事项
- - '####'
  - 内存
- - '####'
  - 共享资源
- - '###'
  - 应用程序生命周期事件
- - '###'
  - 后台的用户界面更新与进程
- - '###'
  - 系统变更通知
- - '##'
  - 处理不同 iOS 版本
- - '##'
  - 总结
- - '#'
  - 第九章：使用原生 C/C++ 提升性能
- - '##'
  - 收益与成本
- - '##'
  - 基础 C 和 C++编程
- - '###'
  - C 编程
- - '####'
  - 基本数据类型与函数
- - '####'
  - 指针
- - '####'
  - 高级数据类型
- - '#####'
  - 数组
- - '#####'
  - 字符串
- - '#####'
  - 结构体
- - '#####'
  - 动态内存分配
- - '#####'
  - 链表示例
- - '#####'
  - 函数指针
- - '#####'
  - 位运算符
- - '###'
  - C++ 编程
- - '####'
  - 类
- - '####'
  - 指针与内存管理
- - '####'
  - 继承
- - '####'
  - 多重继承
- - '####'
  - 模板
- - '##'
  - 一个实际示例
- - '###'
  - SQLite
- - '###'
  - 将 C++ 集成到你的应用程序中
- - '###'
  - 总结
- - '#'
  - 第十章：比较 Android 与 Windows Phone 的性能问题
- - '##'
  - 通用知识
- - '##'
  - 在模拟器和设备上进行基准测试
- - '###'
  - 模拟器与设备
- - '###'
  - 基准测试
- - '####'
  - Android
- - '####'
  - Windows Phone
- - '##'
  - ListView 性能优化
- - '###'
  - Android
- - '###'
  - Windows Phone
- - '##'
  - 数据缓存
- - '###'
  - Android
- - '####'
  - 内部存储
- - '####'
  - 外部存储
- - '####'
  - SQLite 数据库
- - '###'
  - Windows Phone
- - '####'
  - IsolatedStorageFile
- - '####'
  - XML 存储
- - '####'
  - 数据库支持
- - '##'
  - 数据结构与算法
- - '##'
  - 多线程
- - '###'
  - Android
- - '###'
  - Windows Phone
- - '####'
  - 异步下载
- - '##'
  - 内存管理
- - '###'
  - Android
- - '####'
  - 上下文（Context）Activity 泄漏
- - '####'
  - 多任务处理中的内存
- - '####'
  - TabView
- - '###'
  - Windows Phone
- - '####'
  - Panorama 和 Pivot
- - '##'
  - 多任务处理
- - '###'
  - Android
- - '##'
  - C/C++ 编程支持
- - '##'
  - 总结
- - '#'
  - 索引
- - '###'
  - A
- - '###'
  - B
- - '###'
  - C
- - '###'
  - D, E
- - '###'
  - F, G
- - '###'
  - H
- - '###'
  - I, J, K
- - '###'
  - L
- - '###'
  - M, N
- - '###'
  - O
- - '###'
  - P, Q, R
- - '###'
  - S
- - '###'
  - T
- - '###'
  - U
- - '###'
  - V
- - '###'
  - W, X, Y, Z
