name: GUI Design for Android Apps
name_cn: Android 应用 GUI 设计指南
slug: gui-design-for-android-apps
toc:
- - '#'
  - Android 应用程序 GUI 设计
- - '##'
  - 关于 ApressOpen
- - '###'
  - 什么是 ApressOpen？
- - '##'
  - 内容概览
- - '##'
  - 目录
- - '#'
  - 上下文（Context）类
- - '#'
  - Intent（意图）简介
- - '#'
  - Intent（意图）的主要角色
- - '#'
  - Intent（意图）解析
- - '#'
  - 应用程序与活动（Activity）之间的关系
- - '#'
  - 基本的 Android 应用程序界面
- - '#'
  - GuiExam 应用程序代码分析
- - '#'
  - 使用布局作为界面
- - '#'
  - 直接使用视图（View）作为界面
- - '#'
  - 组件 ID
- - '#'
  - 按钮与事件
- - '#'
  - 内部类监听器
- - '#'
  - 使用 ImageView（图像视图）
- - '#'
  - 退出活动（Activity）与应用程序
- - '#'
  - 总结
- - '##'
  - 包含多个活动（Activity）的应用程序
- - '##'
  - 触发无参数的活动（Activity）显式匹配
- - '##'
  - 触发不同应用程序中带参数的活动（Activity）显式匹配
- - '##'
  - 内置活动（Activity）的隐式匹配
- - '##'
  - 使用自定义活动（Activity）进行隐式匹配
- - '##'
  - 显示输出框架
- - '##'
  - 响应触摸屏输入的绘制框架
- - '##'
  - 多点触控代码框架
- - '##'
  - 响应键盘输入
- - '##'
  - Android 中的对话框
- - '##'
  - 使用活动（Activity）的对话框主题
- - '##'
  - 使用特定的对话框类
- - '##'
  - 使用 Toast 提醒
- - '##'
  - 对话框示例
- - '##'
  - 应用程序属性设置
- - '#'
  - 索引
- - '##'
  - 关于首席项目编辑
- - '##'
  - 关于首席贡献作者
- - '##'
  - 关于技术审校
- - '##'
  - 引言
- - '##'
  - 第 1 章
- - '##'
  - 第 2 章
- - '##'
  - 第 3 章
- - '##'
  - 第 4 章
- - '#'
  - 第 1 章
- - '##'
  - Android 应用 GUI 设计，第 1 部分：总览
- - '###'
  - 嵌入式应用 GUI 概述
- - '###'
  - Android 用户界面与用户体验设计
- - '###'
  - Android 设备交互方式的特点
- - '####'
  - 多种尺寸、密度和规格的屏幕
- - '####'
  - 键盘与特殊按键
- - '####'
  - 触摸屏与触控笔替代鼠标
- - '####'
  - 屏幕键盘
- - '####'
  - 有限的多模态交互
- - '###'
  - 少数大容量便携式外部存储设备
- - '###'
  - 嵌入式系统的 UI 设计原则
- - '####'
  - 屏幕尺寸的考量
- - '####'
  - 文本和图标的大小
- - '####'
  - 按钮及其它图形元素的可点击性
- - '####'
  - 应用程序窗口的大小
- - '####'
  - 由触摸屏和触控笔引发的考量
- - '#####'
  - 在仅轻触式触摸屏上正确解释光标（鼠标）的移动和输入
- - '#####'
  - 正确设置屏幕映射
- - '####'
  - 如何解决悬停问题
- - '####'
  - 提供右键单击功能
- - '####'
  - 键盘输入问题
- - '#####'
  - 限制各种命令的输入
- - '#####'
  - 满足键盘需求
- - '###'
  - 软件分发和版权保护问题
- - '###'
  - Android 应用概述
- - '####'
  - 应用文件框架
- - '####'
  - '`AndroidManifest.xml`'
- - '####'
  - '`R.java`'
- - '####'
  - 常量定义文件
- - '####'
  - 布局文件
- - '####'
  - 源代码文件
- - '###'
  - 应用的组件结构
- - '####'
  - Activity（活动）
- - '####'
  - Intent（意图）与 Intent Filters（意图过滤器）
- - '####'
  - Service（服务）
- - '####'
  - Broadcast Intent Receiver（广播意图接收器）
- - '####'
  - Content Provider（内容提供器）
- - '####'
  - Android Emulator（Android 模拟器）
- - '###'
  - Android 与 Dalvik 虚拟机
- - '####'
  - 引入 Android 运行时（ART）
- - '###'
  - 总结
- - '#'
  - 第 2 章
- - '##'
  - Android 应用 GUI 设计，第二部分：Android 特有的 GUI
- - '##'
  - 活动的状态转换
- - '###'
  - 活动状态
- - '##'
  - 活动的重要函数
- - '###'
  - Activity 生命周期与状态转换函数
- - '####'
  - '`onCreate` 状态转换函数'
- - '####'
  - '`onStart` 状态转换函数'
- - '####'
  - '`onResume` 状态转换函数'
- - '####'
  - '`onPause` 状态转换函数'
- - '####'
  - '`onStop` 状态转换函数'
- - '####'
  - '`onRestart` 状态转换函数'
- - '####'
  - '`onDestroy` 状态转换函数'
- - '###'
  - '`finish` 函数'
- - '###'
  - '`Context` 类'
- - '###'
  - Intent 介绍
- - '###'
  - Intent 的主要作用
- - '####'
  - 触发新活动或让现有活动执行新操作
- - '####'
  - 触发新服务或向现有服务发送新请求
- - '####'
  - 触发 BroadcastReceiver
- - '###'
  - Intent 解析
- - '####'
  - 操作测试
- - '####'
  - 类别测试
- - '####'
  - 数据测试
- - '##'
  - 应用与活动之间的关系
- - '###'
  - 初学者困惑：应用程序与 Activity
- - '###'
  - 基本的 Android 应用程序界面
- - '###'
  - GuiExam 应用程序代码分析
- - '###'
  - 使用布局作为界面
- - '###'
  - 直接使用 View 作为界面
- - '###'
  - 组件 ID
- - '###'
  - 按钮和事件
- - '###'
  - 内部类监听器
- - '###'
  - 使用`ImageView`
- - '###'
  - 退出活动与应用程序
- - '###'
  - 本章小结
- - '#'
  - 第 3 章
- - '##'
  - 多活动应用与 Intent 机制
- - '##'
  - 包含多个活动的应用程序
- - '##'
  - 触发不带参数的显式匹配活动
- - '###'
  - 触发不同应用程序中带参数活动的显式匹配
- - '###'
  - 代码示例与解释
- - '####'
  - 修改调用方应用程序`HelloAndroid`的代码
- - '##'
  - 内置 Activity 的隐式匹配
- - '##'
  - 使用自定义活动的隐式匹配
- - '###'
  - 使用隐式意图设计安卓应用
- - '#'
  - 第 4 章
- - '##'
  - 安卓应用 GUI 设计（第四部分）：图形界面与触摸屏输入
- - '##'
  - 显示输出框架
- - '##'
  - 响应触摸屏输入的绘图框架
- - '##'
  - 多点触摸代码框架
- - '##'
  - 响应键盘输入
- - '###'
  - 在这段代码中，你需要让 `Activity` 类接收并响应按键事件，因此在第 19–42 行重写了 `onKeyDown` 函数，并加入了按键响应代码。虽然按键响应函数位于
    `Activity` 类中，但显示更新需要在视图 `MyView` 类中实现，所以必须让 `Activity` 类知晓其对应的视图对象。为此，你在第 7 行添加了一个记录视图对象的变量
    `theView`。在第 11 和 12 行，你让 `theView` 在构造视图对象时记录下该对象。
- - '##'
  - Android 中的对话框
- - '###'
  - 使用 Activity 的对话框主题
- - '####'
  - '`onCreateDialog(int)` 函数'
- - '####'
  - '`showDialog(int)` 函数'
- - '####'
  - '`onPrepareDialog(int, Dialog)` 函数'
- - '####'
  - '`dismissDialog(int)` 函数'
- - '###'
  - 使用特定的 Dialog 类
- - '###'
  - 使用 Toast 提醒
- - '###'
  - 对话框示例
- - '###'
  - 应用属性设置
