name: Swift OS X programming for absolute beginners
name_cn: 绝对初学者的 Swift OS X 编程入门指南
slug: swift-os-x-programming-for-absolute-beginners
toc:
- - '#'
  - Swift OS X 编程入门（零基础适用）
- - '##'
  - 华莱士·王（Wallace Wang）
- - '##'
  - 引言
- - '##'
  - 为什么要学习 Swift 并为 Macintosh 编程？
- - '###'
  - 追随有利可图的编程趋势
- - '###'
  - 本书的阅读预期
- - '###'
  - 致谢
- - '#'
  - 目录
- - '#'
  - 1. 理解编程
- - '##'
  - 编程原理
- - '##'
  - 结构化编程
- - '##'
  - 事件驱动编程
- - '##'
  - 面向对象编程
- - '###'
  - 封装
- - '###'
  - 继承
- - '####'
  - 多态性
- - '##'
  - 理解编程语言
- - '##'
  - Cocoa 框架
- - '##'
  - 视图-模型-控制器设计
- - '##'
  - 程序员如何工作
- - '##'
  - 总结
- - '#'
  - 2. 认识 Xcode
- - '##'
  - 向 Xcode 下达命令
- - '##'
  - 修改 Xcode 窗口
- - '##'
  - 创建与管理文件
- - '##'
  - 创建和自定义用户界面
- - '##'
  - 标准编辑器和辅助编辑器
- - '##'
  - 运行程序
- - '##'
  - 小结
- - '#'
  - 3. 创建 Mac 程序的基础
- - '##'
  - 创建项目
- - '##'
  - 设计用户界面
- - '##'
  - 创建 IBOutlet 并使用 Assistant Editor
- - '##'
  - 创建动作连接
- - '##'
  - 使用文档大纲和连接检查器
- - '##'
  - 总结
- - '#'
  - 4. 获取帮助
- - '##'
  - 理解 Cocoa 框架
- - '##'
  - 在类文件中查找属性和方法
- - '###'
  - 通过帮助菜单查找类文件
- - '###'
  - 通过快速帮助查找类文件
- - '##'
  - 浏览文档
- - '##'
  - 搜索文档
- - '##'
  - 使用代码补全
- - '##'
  - 理解 OS X 程序的工作原理
- - '##'
  - 总结
- - '#'
  - 5. 学习 Swift
- - '##'
  - 使用 Playgrounds
- - '##'
  - 在 Swift 中创建注释
- - '##'
  - 在 Swift 中存储数据
- - '##'
  - Swift 变量与常量声明
- - '##'
  - 类型别名
- - '##'
  - 使用 Unicode 字符作为名称
- - '##'
  - 转换数据类型
- - '##'
  - 计算属性
- - '##'
  - 使用可选变量
- - '##'
  - 将 Swift 代码与用户界面关联
- - '##'
  - 总结
- - '#'
  - 6. 处理数字与字符串
- - '##'
  - 使用数学运算符
- - '###'
  - 前缀与后缀运算符
- - '###'
  - 复合赋值运算符
- - '##'
  - 使用数学函数
- - '###'
  - 舍入函数
- - '###'
  - 计算函数
- - '###'
  - 三角函数
- - '###'
  - 指数函数
- - '###'
  - 对数函数
- - '##'
  - 使用字符串函数
- - '##'
  - 创建函数
- - '###'
  - 不带参数或返回值的简单函数
- - '###'
  - 带参数的简单函数
- - '###'
  - 带参数并返回值的函数
- - '###'
  - 定义外部参数名
- - '###'
  - 使用变量参数
- - '###'
  - 使用输入输出参数
- - '###'
  - 理解 IBAction 方法
- - '##'
  - 摘要
- - '#'
  - 7. 使用分支进行决策
- - '##'
  - 理解比较运算符
- - '##'
  - 理解逻辑运算符
- - '##'
  - '`if` 语句'
- - '##'
  - '`if-else` 语句'
- - '##'
  - if-else if 语句
- - '##'
  - switch 语句
- - '##'
  - 在枚举数据结构中使用 switch 语句
- - '##'
  - 在 OS X 程序中做决策
- - '##'
  - 小结
- - '#'
  - 8. 用循环重复执行代码
- - '##'
  - '`while` 循环'
- - '##'
  - '`repeat-while` 循环'
- - '##'
  - 用于计数的 `for` 循环
- - '##'
  - '`for-in` 语句'
- - '##'
  - 提前退出循环
- - '##'
  - 在 OS X 程序中使用循环
- - '##'
  - 摘要
- - '#'
  - 9. 数组与字典
- - '##'
  - 使用数组
- - '###'
  - 向数组添加元素
- - '###'
  - 从数组删除元素
- - '###'
  - 查询数组
- - '###'
  - 操作数组
- - '##'
  - 使用字典
- - '###'
  - 向字典添加条目
- - '###'
  - 检索和更新字典中的数据
- - '###'
  - 删除字典中的数据
- - '###'
  - 查询字典
- - '###'
  - 在 OS X 程序中使用字典
- - '##'
  - 总结
- - '#'
  - 10. 元组、集合与结构体
- - '##'
  - 使用元组
- - '###'
  - 访问元组中的数据
- - '##'
  - 使用集合
- - '###'
  - 创建集合
- - '###'
  - 向集合中添加和移除元素
- - '###'
  - 查询集合
- - '###'
  - 操作集合
- - '##'
  - 使用结构体
- - '###'
  - 从结构体中存储和检索项目
- - '##'
  - 在 OS X 程序中使用结构体
- - '###'
  - Swift 中的结构体、数组与字典操作
- - '##'
  - 总结
- - '#'
  - 11. 创建类与对象
- - '##'
  - 创建类
- - '###'
  - 访问对象中的属性
- - '###'
  - 对象中的计算属性
- - '###'
  - 设置其他属性
- - '###'
  - 使用属性观察器
- - '##'
  - 创建方法
- - '##'
  - 在 OS X 程序中使用对象
- - '##'
  - 总结
- - '#'
  - 12. 继承、多态与类的扩展
- - '##'
  - 理解继承
- - '##'
  - 理解多态
- - '###'
  - 重写属性
- - '###'
  - 防止多态
- - '##'
  - 使用扩展
- - '##'
  - 使用协议
- - '###'
  - 在协议中定义可选属性和方法
- - '###'
  - 将继承与协议结合使用
- - '##'
  - 使用委托
- - '##'
  - 在 OS X 程序中使用继承
- - '##'
  - 总结
- - '#'
  - 13. 创建用户界面
- - '##'
  - 理解用户界面文件
- - '##'
  - 搜索对象库
- - '###'
  - 显示和接受文本的用户界面项
- - '###'
  - 限制选项的用户界面项
- - '###'
  - 接受命令的用户界面项
- - '###'
  - 分组项的用户界面项
- - '##'
  - 在自动布局中使用约束
- - '###'
  - 定义窗口尺寸
- - '###'
  - 对用户界面项施加约束
- - '###'
  - 编辑约束
- - '##'
  - 在 OS X 程序中定义约束
- - '##'
  - 摘要
- - '#'
  - 14. 使用视图和故事板
- - '##'
  - 创建用户界面文件
- - '###'
  - 添加 `.xib` 或 `.storyboard` 文件
- - '##'
  - 定义主用户界面
- - '##'
  - 显示多个 `.xib` 文件
- - '##'
  - 使用故事板
- - '###'
  - 缩放故事板
- - '###'
  - 向故事板添加场景
- - '###'
  - 在故事板中定义初始场景
- - '###'
  - 用 Segue 连接场景
- - '###'
  - 通过转场显示场景
- - '##'
  - 执行转场后移除场景
- - '##'
  - 在场景间传递数据
- - '##'
  - 总结
- - '#'
  - 15. 用按钮选择命令
- - '###'
  - 修改按钮上的文本
- - '##'
  - 为按钮添加图片和声音
- - '##'
  - 将多个用户界面项连接到 IBAction 方法
- - '##'
  - 使用弹出按钮
- - '###'
  - 可视化修改弹出菜单项
- - '###'
  - 使用 Swift 代码添加弹出菜单项
- - '##'
  - 总结
- - '#'
  - 16. 使用单选按钮、复选框、日期选择器和滑块做出选择
- - '##'
  - 使用复选框
- - '##'
  - 使用单选按钮
- - '##'
  - 使用日期选择器
- - '##'
  - 使用滑块
- - '##'
  - 摘要
- - '#'
  - 17. 在标签、文本字段和组合框中使用文本
- - '##'
  - 使用文本字段
- - '###'
  - 使用数字格式化器
- - '###'
  - 使用安全文本字段、搜索字段和令牌字段
- - '##'
  - 使用组合框
- - '###'
  - 创建内部列表
- - '###'
  - 使用数据源
- - '##'
  - 总结
- - '#'
  - 18. 使用警告和面板
- - '##'
  - 使用提醒
- - '###'
  - 从提醒处获取反馈
- - '###'
  - 以工作表形式显示警告
- - '##'
  - 使用面板
- - '###'
  - 创建打开面板
- - '###'
  - 创建保存面板
- - '##'
  - 总结
- - '#'
  - 19. 创建下拉菜单
- - '##'
  - 编辑下拉菜单
- - '###'
  - 向菜单栏添加新的下拉菜单标题
- - '###'
  - 向下拉菜单添加新命令
- - '###'
  - 编辑命令
- - '###'
  - 将菜单命令连接到 Swift 代码
- - '##'
  - 总结
- - '#'
  - 20. 面向协议编程
- - '##'
  - 理解协议
- - '###'
  - 在协议中使用方法
- - '##'
  - 遵循多个协议
- - '##'
  - 协议扩展
- - '###'
  - 使用协议扩展扩展通用数据类型
- - '###'
  - 小结
- - '#'
  - 21. 防御性编程
- - '##'
  - 使用极限值进行测试
- - '##'
  - 当心语言快捷方式
- - '##'
  - 使用可选变量
- - '##'
  - 使用可选链
- - '##'
  - 错误处理
- - '###'
  - 使用 `enum` 和 `ErrorType` 定义错误
- - '###'
  - 创建错误识别函数
- - '###'
  - 处理错误
- - '##'
  - 总结
- - '#'
  - 22. 简化用户界面设计
- - '##'
  - 使用堆栈视图
- - '##'
  - 解决约束冲突
- - '##'
  - 总结
- - '#'
  - 23. 调试你的程序
- - '##'
  - 简单调试技巧
- - '##'
  - 使用 Xcode 调试器
- - '###'
  - 使用断点
- - '###'
  - 单步执行代码
- - '###'
  - 管理断点
- - '###'
  - 使用符号断点
- - '###'
  - 使用条件断点
- - '###'
  - 在 Xcode 中排除断点故障
- - '###'
  - 总结
- - '#'
  - 24. 编程前后的规划
- - '##'
  - 明确程序的目的
- - '##'
  - 设计程序的结构
- - '##'
  - 设计程序的用户界面
- - '###'
  - 用纸笔设计用户界面
- - '###'
  - 使用软件设计用户界面
- - '##'
  - 营销你的软件
- - '###'
  - 为你的软件写博客
- - '###'
  - 赠送免费软件
- - '###'
  - 发布关于你软件的视频
- - '###'
  - 免费提供信息
- - '###'
  - 加入社交网络
- - '##'
  - 总结
- - '#'
  - 索引
- - '##'
  - A
- - '###'
  - 提醒
- - '###'
  - 数组
- - '###'
  - 助理编辑器
- - '##'
  - B
- - '###'
  - 按钮
- - '##'
  - C
- - '###'
  - 计算函数
- - '###'
  - 复选框
- - '###'
  - 类创建
- - '###'
  - Cocoa 应用程序
- - '###'
  - 常用逻辑运算符
- - '###'
  - 计算机程序
- - '###'
  - 条件断点
- - '###'
  - 连接检查器
- - '###'
  - 约束，自动布局
- - '##'
  - D
- - '###'
  - 数据类型
- - '###'
  - 日期选择器
- - '###'
  - 调试区
- - '###'
  - 调试
- - '###'
  - 防御性编程
- - '###'
  - 委托
- - '###'
  - '`didSet`属性观察器'
- - '###'
  - 基于文档的应用程序
- - '###'
  - 文档大纲
- - '##'
  - E, F
- - '###'
  - 编辑下拉菜单。参见下拉菜单
- - '###'
  - 指数函数
- - '###'
  - 扩展类
- - '##'
  - G, H
- - '###'
  - Getters
- - '##'
  - I, J, K
- - '###'
  - '`IBAction changeCase`方法'
- - '###'
  - '`IBAction`方法'
- - '###'
  - '`If-else if`语句'
- - '###'
  - 继承
- - '###'
  - '`Init`函数'
- - '###'
  - 检查器面板
- - '###'
  - 界面生成器
- - '###'
  - '`InternalChange`函数'
- - '##'
  - L
- - '###'
  - 对数函数
- - '###'
  - 循环
- - '##'
  - M
- - '###'
  - 操作数字
- - '###'
  - 方法创建
- - '###'
  - 多用户界面程序
- - '##'
  - N
- - '###'
  - 导航器面板
- - '###'
  - 非 (`!`)逻辑运算符
- - '##'
  - O
- - '###'
  - 对象库
- - '###'
  - 面向对象编程
- - '###'
  - 对象通信
- - '###'
  - OS X 程序
- - '###'
  - 打开面板
- - '###'
  - 运算符
- - '###'
  - 或 (`||`)逻辑运算符
- - '###'
  - OS X 人机界面指南
- - '##'
  - P, Q
- - '###'
  - 面板
- - '###'
  - 规划
- - '###'
  - 多态
- - '###'
  - 弹出按钮
- - '###'
  - 属性观察器
- - '###'
  - 面向协议编程
- - '###'
  - 协议
- - '###'
  - 下拉菜单
- - '##'
  - R
- - '###'
  - 单选按钮
- - '###'
  - 舍入函数
- - '##'
  - S
- - '###'
  - 保存面板
- - '###'
  - 场景
- - '###'
  - 搜索文本字段
- - '###'
  - 安全文本字段
- - '###'
  - Segue
- - '###'
  - 集合
- - '###'
  - Setters
- - '###'
  - '`shootButton` `IBAction`方法'
- - '###'
  - 滑块
- - '###'
  - 标准编辑器
- - '###'
  - 语句
- - '###'
  - 步入命令
- - '###'
  - 步出命令
- - '###'
  - 跳过命令
- - '###'
  - 故事板
- - '###'
  - 结构
- - '###'
  - 子程序
- - '###'
  - Swift
- - '###'
  - 符号断点
- - '###'
  - 系统插件
- - '##'
  - T
- - '###'
  - 文本字段
- - '###'
  - 三角函数
- - '###'
  - 断点故障排除
- - '###'
  - 元组
- - '###'
  - 类型别名
- - '##'
  - U
- - '###'
  - 用户界面约束，自动布局。参见约束，自动布局
- - '###'
  - 用户界面
- - '###'
  - 用户界面设计
- - '##'
  - V
- - '###'
  - 视图-控制器通信
- - '###'
  - 视图-模型-控制器设计
- - '##'
  - W
- - '###'
  - While 循环
- - '###'
  - '`willSet`属性观察器'
- - '###'
  - 窗口大小，用户界面
- - '##'
  - X, Y, Z
- - '###'
  - Xcode
- - '###'
  - Xcode 调试器
- - '###'
  - Xcode 窗口
- - '###'
  - '`.xib` 文件'
