name: Learn Cocoa Touch for iOS
name_cn: iOS Cocoa Touch 入门指南
slug: learn-cocoa-touch-for-ios
toc:
- - '#'
  - 内容一览
- - '#'
  - 引言
- - '##'
  - 本书读者对象
- - '##'
  - 本书结构
- - '##'
  - 下载代码
- - '##'
  - 联系作者
- - '#'
  - 第 1 章：入门
- - '##'
  - 安装 Xcode
- - '##'
  - 开发者工具
- - '##'
  - 你好，世界！
- - '##'
  - 添加对象到视图
- - '##'
  - 总结
- - '#'
  - 第 2 章：Objective-C 精要
- - '##'
  - 面向对象编程
- - '##'
  - 属性
- - '###'
  - 为你生成代码
- - '###'
  - 内存管理
- - '##'
  - 垃圾回收
- - '##'
  - 引用计数
- - '##'
  - 自动释放池
- - '##'
  - 自动引用计数
- - '##'
  - ARC 与属性
- - '##'
  - 类别（Categories）
- - '##'
  - 类扩展（Class Extensions）
- - '##'
  - 协议（Protocols）
- - '##'
  - 多开发者编程时的协作方式
- - '###'
  - 遵循协议
- - '##'
  - 模型-视图-控制器编程：精良代码的设计哲学
- - '##'
  - 总结
- - '#'
  - 第 3 章：使用视图控制器管理屏幕内容
- - '##'
  - 视图控制器生命周期
- - '##'
  - 通过控件实现应用逻辑
- - '##'
  - 使用表格视图提供内容列表
- - '###'
  - 为你的表格视图提供数据
- - '##'
  - 提供自定义表视图单元格
- - '##'
  - Nib 加载深入解析
- - '###'
  - 从 Nib 加载表视图单元格
- - '###'
  - iPhone 和 iPad Nib
- - '##'
  - 另一个内置视图控制器：`UIPageViewController`
- - '##'
  - 在视图控制器之间传递数据
- - '###'
  - 将数据从父视图控制器传递到子视图控制器
- - '###'
  - 向模态视图控制器传递数据并从中接收数据
- - '###'
  - 使用委托协议在视图控制器之间传递数据
- - '##'
  - 总结
- - '#'
  - 第 4 章：在应用中保存内容
- - '##'
  - 在应用内移动数据
- - '###'
  - 委托链
- - '###'
  - 键值观察
- - '####'
  - 使用 KVO
- - '##'
  - KVO 的工作原理
- - '##'
  - 手动 KVO 实现
- - '##'
  - KVO 实战
- - '##'
  - 通知
- - '###'
  - 注册通知
- - '###'
  - 发布你自己的通知
- - '###'
  - 常见的系统通知
- - '##'
  - 单例
- - '##'
  - 将数据持久化到文件
- - '###'
  - NSUserDefaults
- - '###'
  - 使用用户默认设置保存应用数据
- - '###'
  - '`NSCoding`'
- - '##'
  - 手动文件处理
- - '##'
  - SQLite 数据库
- - '##'
  - iOS 上的文件位置
- - '###'
  - 应用包
- - '###'
  - Documents 目录
- - '###'
  - Caches 目录
- - '##'
  - Core Data
- - '##'
  - 总结
- - '#'
  - 第 5 章：处理用户触摸
- - '##'
  - 响应者链
- - '##'
  - 自定义视图
- - '##'
  - UIGestureRecognizer
- - '###'
  - 更多 Target-Action 方法
- - '###'
  - 手势识别器的生命周期
- - '##'
  - 内置手势识别器
- - '##'
  - 自定义 `UIGestureRecognizer`
- - '##'
  - 滚动视图
- - '###'
  - '**实现 UI 变更**'
- - '####'
  - 为物品添加图片
- - '##'
  - 使用 UIActionSheet
- - '##'
  - 为表格视图实现“编辑”功能
- - '###'
  - 实现表视图重排序
- - '##'
  - 总结
- - '#'
  - 第 6 章：集成网络与 Web 服务
- - '##'
  - 从网络加载数据
- - '###'
  - 创建 URL 请求
- - '###'
  - 创建 URL 连接
- - '##'
  - 解释响应
- - '##'
  - 使用接收到的数据
- - '##'
  - 异步操作
- - '##'
  - URL 连接委托方法
- - '##'
  - 异步网络请求的注意事项
- - '##'
  - 解析来自 Web 服务的 JSON 与 XML
- - '###'
  - 解析 XML
- - '###'
  - 解析 JSON
- - '###'
  - 创建 JSON 表示
- - '##'
  - 将 Foundation 对象解析为模型对象
- - '##'
  - 下载文件
- - '###'
  - 何时缓存文件
- - '###'
  - 下载图片
- - '##'
  - 总结
- - '#'
  - 第 7 章：使用 Block 编写现代代码
- - '##'
  - 什么是 Blocks？
- - '##'
  - 块是封装好的函数
- - '##'
  - 使用类型定义实现可读的块声明
- - '##'
  - Block 的内存管理
- - '##'
  - Block 是对象
- - '##'
  - Block 捕获作用域
- - '##'
  - 块保留对象
- - '###'
  - 将 Block 作为方法参数
- - '###'
  - 为什么应该使用 Block？
- - '####'
  - UIView 动画
- - '##'
  - 使用块进行异步回调
- - '##'
  - 使用块进行枚举
- - '##'
  - 使用 Block 对数组排序
- - '###'
  - 使用比较选择器对数组排序
- - '###'
  - 使用排序描述符对数组排序
- - '###'
  - 使用 Block 对数组排序
- - '##'
  - 在你的代码中使用 Block
- - '##'
  - 使用 Block 更新 TwitterExample
- - '###'
  - 添加完成处理程序
- - '##'
  - 添加活动指示器
- - '##'
  - 总结
- - '#'
  - 第 8 章：管理事件的发生时机
- - '##'
  - 发送消息
- - '###'
  - 消息的底层实现
- - '###'
  - 手动执行选择器
- - '###'
  - 在后台调用选择器
- - '##'
  - 创建 `NSTimers` 的其他方式
- - '##'
  - 运行循环
- - '##'
  - 多线程代码
- - '###'
  - 在另一个线程上运行代码
- - '###'
  - 线程安全
- - '###'
  - 运行大量任务
- - '##'
  - 示例：Twitter 头像图片
- - '##'
  - Grand Central Dispatch
- - '###'
  - 使用全局调度队列
- - '###'
  - 调度对象（Dispatch Objects）
- - '###'
  - 调度队列（Dispatch Queues）
- - '###'
  - 分派信号量
- - '##'
  - 总结
- - '#'
  - 第 9 章：用户界面设计
- - '##'
  - 用`UIColor`为界面元素着色
- - '##'
  - 字体与文本大小
- - '##'
  - 使用图像
- - '##'
  - 视图布局
- - '###'
  - 视图层次结构
- - '###'
  - 视图坐标系
- - '###'
  - 视图显示属性
- - '###'
  - 视图自动调整大小
- - '###'
  - 视图内容模式
- - '###'
  - UIView 子类中的视图布局
- - '####'
  - 代码片段
- - '####'
  - 在 Retina 显示屏设备上的视图布局
- - '####'
  - iPad 上的视图布局
- - '##'
  - 视图动画
- - '##'
  - 示例：Reddit 图片浏览器
- - '##'
  - 总结
- - '#'
  - 第 10 章：硬件 API
- - '##'
  - 使用摄像头
- - '###'
  - AVFoundation 概述
- - '###'
  - 使用`UIImagePickerController`处理照片
- - '###'
  - 使用`UIImagePickerController`处理视频
- - '###'
  - 使用 UIVideoEditorController 处理视频
- - '##'
  - 使用加速计
- - '###'
  - 加速计事件
- - '###'
  - 设备方向通知
- - '##'
  - 使用 Core Motion 处理原始加速计、陀螺仪和磁力计数据
- - '##'
  - 使用位置数据
- - '###'
  - 使用 CoreLocation
- - '###'
  - 使用 MapKit
- - '##'
  - 自带设备
- - '###'
  - 在应用中指定所需设备
- - '##'
  - 总结
- - '#'
  - 第 11 章：应用中的媒体：播放音频和视频
- - '##'
  - 播放音频
- - '###'
  - 系统声音服务
- - '####'
  - 播放系统声音
- - '###'
  - 播放警报音
- - '###'
  - 触发振动
- - '###'
  - '`AVAudioPlayer`'
- - '###'
  - 其他声音 API
- - '###'
  - 示例：SoundBoard
- - '##'
  - 播放音乐
- - '###'
  - 使用`MPMediaPickerController`
- - '###'
  - 使用 MPMusicPlayerController
- - '###'
  - 媒体查询
- - '###'
  - 示例：TitularSongs
- - '##'
  - 播放视频
- - '###'
  - 使用 MPMoviePlayerController
- - '###'
  - 使用 MPMoviePlayerViewController
- - '###'
  - 使用 `presentMoviePlayerViewControllerAnimated:`
- - '###'
  - 使用 `MPMoviePlayerController` 的视图
- - '###'
  - 播放网络视频
- - '###'
  - 获取视频缩略图
- - '###'
  - 示例：CustomPlayer
- - '##'
  - 总结
- - '#'
  - 第 12 章：本地化与国际化
- - '##'
  - 国际化
- - '###'
  - 使用数字
- - '####'
  - 示例：LocaleNumbers
- - '###'
  - 使用日期
- - '###'
  - 处理用户输入
- - '##'
  - 本地化
- - '###'
  - 本地化文本
- - '####'
  - 使用 `NSLocalizedString`
- - '####'
  - 使用字符串文件的优势
- - '####'
  - 多语言的字体支持
- - '####'
  - 示例：HelloLocalization
- - '#####'
  - 构建用户界面
- - '#####'
  - 使用 `genstrings` 生成字符串文件
- - '#####'
  - 添加另一种语言（法语）
- - '###'
  - 本地化资源
- - '###'
  - 本地化 Nib 文件
- - '##'
  - 总结
- - '#'
  - 附录 A：在 iOS 设备上运行代码
- - '##'
  - iOS 开发者计划
- - '##'
  - iOS 应用安全
- - '##'
  - 获取证书
- - '##'
  - iOS 应用配置
- - '##'
  - 总结
- - '#'
  - 索引
- - '##'
  - A
- - '##'
  - C
- - '##'
  - D
- - '##'
  - H
- - '###'
  - MapKit
- - '##'
  - I
- - '###'
  - 内置手势识别器
- - '###'
  - 硬件 API
- - '###'
  - 异步操作网络
- - '###'
  - 下载
- - '##'
  - J
- - '##'
  - L
- - '##'
  - M, N
- - '##'
  - O
- - '##'
  - P
- - '##'
  - S
- - '###'
  - 保存内容
- - '###'
  - 索引
- - '##'
  - T
- - '###'
  - 选择器
- - '###'
  - 定时器
- - '###'
  - 推特
- - '###'
  - reddit 照片浏览器
- - '##'
  - U
- - '#'
  - 关于作者
- - '#'
  - 关于技术审校
- - '#'
  - 致谢
