name: Learn Computer Science with Swift
name_cn: Swift 计算机科学入门指南
slug: learn-computer-science-with-swift
toc:
- - '#'
  - 使用 Swift 学习计算机科学
- - '##'
  - 引言
- - '##'
  - 下载本书的 Playgrounds
- - '##'
  - 关于作者
- - '#'
  - 目录
- - '##'
  - 第 1 章：计算思维
- - '##'
  - 第 2 章：编写代码与使用 Swift Playgrounds
- - '##'
  - 第 3 章：探索编程范式
- - '##'
  - 第 4 章：使用算法
- - '##'
  - 第 5 章：管理控制流：重复
- - '##'
  - 第 6 章：处理数据：集合
- - '##'
  - 第 7 章：处理数据：类型
- - '##'
  - 第 8 章：管理控制流：条件语句、Switch 与枚举
- - '##'
  - 第 9 章：数据存储与数据共享
- - '##'
  - 第 10 章：构建组件
- - '##'
  - 第 11 章：使用事件驱动操作
- - '##'
  - 第 12 章：初识 Xcode
- - '##'
  - 第 13 章：引入人员因素
- - '##'
  - 第 14 章：图形化与可视化技术及问题
- - '##'
  - 索引 295
- - '##'
  - 关于作者与技术审校者
- - '###'
  - 关于作者
- - '###'
  - 关于技术审校者
- - '#'
  - 1. 计算思维
- - '##'
  - 当今的计算机科学
- - '##'
  - 使用 Swift Playgrounds
- - '##'
  - 当今计算机科学的基本概念与实践
- - '###'
  - 识别模式
- - '###'
  - 使用抽象
- - '###'
  - 结合模式与抽象进行开发
- - '##'
  - 开发者的基本任务
- - '###'
  - 构建计算问题
- - '####'
  - 识别并描述问题
- - '####'
  - 定义项目与目标
- - '####'
  - 什么不是计算问题
- - '###'
  - 建模问题或流程
- - '###'
  - 练习分解
- - '###'
  - 重新排列与重组项目模块
- - '###'
  - 验证抽象概念
- - '##'
  - 代码来了
- - '#'
  - 2. 编写代码和使用 Swift Playgrounds
- - '##'
  - 编写代码的基础知识
- - '###'
  - 操作和数据
- - '####'
  - 创建操作
- - '####'
  - 使用数据
- - '##'
  - 组合行动与数据
- - '##'
  - 代码背后的运行机制
- - '##'
  - 编译与解释代码
- - '##'
  - 使用 Swift Playgrounds
- - '##'
  - 转向编程范式
- - '#'
  - 3. 探索编程范式
- - '##'
  - 结构化编程
- - '##'
  - 面向对象编程
- - '##'
  - 命令式编程（过程式编程）
- - '##'
  - 声明式编程
- - '###'
  - 比较命令式编程与声明式编程
- - '##'
  - 并发编程
- - '#'
  - 4. 使用算法
- - '##'
  - 思考算法的目的
- - '##'
  - 创建一个数字命理学算法
- - '##'
  - 仔细审视算法
- - '###'
  - 函数
- - '###'
  - 对象
- - '###'
  - 设计模式
- - '###'
  - 在 Swift 中实现数字命理学算法
- - '###'
  - 实现数字命理学表
- - '###'
  - 实现加法运算
- - '##'
  - 总结
- - '#'
  - 5. 管理控制流：重复
- - '##'
  - 准备使用随机数进行多步控制流项目
- - '###'
  - 创建一个随机数 playground
- - '####'
  - 编写游乐场代码
- - '###'
  - 生成多个随机数
- - '###'
  - 创建重复循环
- - '####'
  - 编写要重复的代码
- - '####'
  - 创建重复控制（限制）
- - '##'
  - 本章小结
- - '#'
  - 6. 数据处理：集合
- - '##'
  - 使用数据类型
- - '##'
  - 标量数据
- - '##'
  - 转向使用收集到的数据
- - '##'
  - 使用数组
- - '###'
  - 基本术语
- - '###'
  - 数组元素的索引
- - '###'
  - Swift 数组与类型
- - '###'
  - 声明与创建数组
- - '###'
  - 修改 `var` 数组
- - '###'
  - 多维数组
- - '###'
  - 查找数组元素
- - '###'
  - 添加和删除数组元素
- - '###'
  - 遍历数组
- - '##'
  - 使用集合
- - '###'
  - 集合基本术语
- - '###'
  - 识别与查找集合元素
- - '####'
  - 声明与创建 Swift 集合及类型
- - '###'
  - 添加与删除集合元素
- - '###'
  - 处理集合
- - '##'
  - 使用字典
- - '###'
  - 字典基本术语
- - '###'
  - 声明与创建字典
- - '###'
  - 添加与删除字典元素
- - '##'
  - 总结
- - '#'
  - 7. 处理数据：类型
- - '##'
  - 类型为何重要
- - '##'
  - 查看栈和堆
- - '###'
  - 运行时数据存储
- - '###'
  - 栈与队列
- - '###'
  - 堆
- - '##'
  - 基本类型
- - '###'
  - 数值存储
- - '####'
  - 使用整数
- - '####'
  - 使用浮点数
- - '###'
  - 存储字符串与字符
- - '###'
  - 创建新类型
- - '##'
  - 元组的使用
- - '##'
  - 总结
- - '#'
  - 8. 管理控制流：条件语句、Switch 语句和枚举
- - '##'
  - 接下来是什么？
- - '###'
  - 使用 `Go To` 语句……或者不使用
- - '###'
  - 使用条件语句
- - '###'
  - 在 Swift 中使用复合语句
- - '##'
  - 三元运算符
- - '##'
  - 切换控制
- - '###'
  - Swift 的 Switch 语句与其他语言的对比
- - '###'
  - 探索 Swift Switch 语法
- - '###'
  - 使用高级 Switch Case 元素：范围
- - '###'
  - 使用高级 Switch Case 元素：Where 子句
- - '##'
  - 使用枚举类型
- - '###'
  - Swift 处理枚举类型的方法
- - '###'
  - 将 Swift 枚举与 Switch 语句结合使用
- - '##'
  - 探索重复和步进
- - '###'
  - While 和 Repeat-While 循环
- - '###'
  - For-In 循环
- - '####'
  - 遍历集合
- - '####'
  - 遍历索引（数组）和键（字典）
- - '###'
  - 使用步长（Strides）
- - '##'
  - 总结
- - '#'
  - 9. 存储数据与共享数据
- - '##'
  - 数据是什么？
- - '##'
  - 数据存储在哪里？
- - '###'
  - 在非持久化应用存储中存储数据
- - '###'
  - 在持久化应用存储中存储数据
- - '###'
  - 在设备上应用存储之外存储持久化数据
- - '###'
  - 在共享存储位置存储数据
- - '##'
  - 谁负责管理数据？
- - '###'
  - 数据所有权
- - '###'
  - 数据完整性
- - '###'
  - 使用校验和
- - '###'
  - 使用时间戳和其他数据标记
- - '###'
  - 版本控制
- - '##'
  - 数据如何管理
- - '###'
  - 管理外部数据
- - '###'
  - 格式化与构建数据
- - '###'
  - 在 Swift 4 中使用 JSON
- - '##'
  - 处理不存在的数据：Swift 可选值
- - '##'
  - 总结
- - '#'
  - 10. 构建组件
- - '##'
  - 为什么要构建组件
- - '###'
  - 组件的优势：可重用性
- - '###'
  - 组件的优势：可管理性
- - '##'
  - 开发项目的基本组件
- - '###'
  - 子程序、函数、过程和方法
- - '####'
  - 命名组件
- - '####'
  - 数据输入
- - '####'
  - 数据输出
- - '####'
  - 实现 —— 代码
- - '####'
  - 实现 —— 文档
- - '####'
  - 副作用和依赖
- - '##'
  - 类
- - '##'
  - 更大的构建块
- - '##'
  - 关于代码块和递归
- - '###'
  - 术语：代码块和闭包
- - '###'
  - 使用闭包
- - '###'
  - 递归
- - '##'
  - 在 Swift 中构建函数
- - '##'
  - 总结
- - '#'
  - 11. 使用事件引导操作
- - '##'
  - 代码块的作用
- - '##'
  - 使用操作和消息传递管理流程控制：总结
- - '##'
  - 将按钮按下/轻触/点击传递给……某个地方
- - '###'
  - 实现一个已知操作的按钮
- - '###'
  - 实现一个带通知的按钮
- - '####'
  - 通知基础
- - '###'
  - 发布通知
- - '###'
  - 监听通知
- - '##'
  - 总结
- - '#'
  - 12. 进入 Xcode
- - '##'
  - 如何编写软件
- - '###'
  - 使用 Xcode 开发应用
- - '####'
  - 设置项目
- - '####'
  - 测试项目（不进行修改）
- - '####'
  - 添加代码和界面
- - '###'
  - 测试项目（进行修改后）
- - '###'
  - 使用 Xcode 调试应用
- - '##'
  - 总结
- - '#'
  - 13. 纳入人的因素
- - '##'
  - 面向人的可计算性
- - '##'
  - 开发问题
- - '###'
  - 你在做什么？
- - '###'
  - 谁将参与其中？
- - '###'
  - 人们为什么会参与进来？
- - '###'
  - 项目将在何时进行？
- - '###'
  - 项目将在何处运行？
- - '###'
  - 你将如何得知结果？
- - '##'
  - 本章小结
- - '#'
  - 14. 图形与可视化技术及问题
- - '##'
  - 介绍 Utility Smart
- - '##'
  - 开始开发应用（Utility Smart 1）
- - '##'
  - 完善应用（Utility Smart 2）
- - '##'
  - 代码片段
- - '###'
  - 创建弹出视图：代码
- - '###'
  - 创建弹出框：故事板
- - '##'
  - 总结
- - '#'
  - 索引
- - '##'
  - A
- - '###'
  - 抽象、模式与验证
- - '###'
  - 算法
- - '###'
  - 应用与系统的基本构建块
- - '###'
  - 概念
- - '###'
  - 数组
- - '###'
  - 开发者和设计者
- - '###'
  - 元素
- - '###'
  - 汇编器
- - '##'
  - B
- - '###'
  - 块适配
- - '###'
  - 按钮
- - '##'
  - C
- - '###'
  - 代码片段
- - '###'
  - 编码动作与数据
- - '###'
  - 编译器
- - '###'
  - 组件
- - '###'
  - 计算机科学
- - '###'
  - 并发编程
- - '###'
  - 控制流管理
- - '##'
  - D, E, F
- - '###'
  - 数据
- - '###'
  - 数据集合
- - '###'
  - 数据完整性
- - '###'
  - 数据管理
- - '###'
  - 数据类型
- - '###'
  - 声明式编程
- - '###'
  - 设计模式、算法
- - '###'
  - 开发者
- - '###'
  - 字典
- - '##'
  - G, H
- - '###'
  - 图形与可视化技术
- - '##'
  - I, J, K, L
- - '###'
  - 命令式与过程式编程
- - '##'
  - M
- - '###'
  - 管理控制流
- - '###'
  - 多步控制流
- - '##'
  - N
- - '###'
  - 数字命理学表
- - '##'
  - O
- - '###'
  - 面向对象编程
- - '###'
  - 所有权、数据
- - '##'
  - P, Q
- - '###'
  - 人员
- - '###'
  - 编程范式
- - '##'
  - R
- - '###'
  - 重复
- - '###'
  - 重复（复数）
- - '##'
  - S
- - '###'
  - 标量数据
- - '###'
  - 集合
- - '###'
  - 存储与共享数据
- - '###'
  - 结构化编程
- - '###'
  - 切换控制
- - '##'
  - T, U
- - '###'
  - 三元运算符
- - '###'
  - 时间戳
- - '###'
  - 元组
- - '##'
  - V, W
- - '###'
  - 验证、抽象
- - '##'
  - X, Y, Z
- - '###'
  - Xcode
