name: Beginning Xamarin Development for the Mac
name_cn: Mac 的 Xamarin 开发入门指南
slug: beginning-xamarin-development-for-the-mac
toc:
- - '#'
  - 开始使用 Xamarin 开发 Mac 应用
- - '##'
  - 引言
- - '##'
  - 致谢
- - '##'
  - 目录
- - '#'
  - 第 1 章 基础
- - '##'
  - 1.1 设置开发环境
- - '##'
  - 1.2 Hello, World! 应用
- - '###'
  - 1.2.1 创建项目
- - '###'
  - 1.2.2 Storyboard 设计器
- - '###'
  - 1.2.3 用户界面
- - '###'
  - 1.2.4 AlertViewController
- - '###'
  - 1.2.5 操作
- - '###'
  - 1.2.6 操作表
- - '##'
  - 1.3 总结
- - '#'
  - 第 2 章 应用结构与生命周期
- - '##'
  - 2.1 入口点
- - '##'
  - 2.2 AppDelegate
- - '##'
  - 2.3 视图生命周期
- - '##'
  - 2.4 信息属性列表
- - '##'
  - 2.5 授权属性列表
- - '##'
  - 2.6 启动故事板
- - '##'
  - 2.7 故事板的工作原理
- - '###'
  - 2.7.1 模型-视图-控制器
- - '###'
  - 2.7.2 持久化数据
- - '####'
  - '`EncodeString` 和 `DecodeString` 辅助方法'
- - '##'
  - 2.8 总结
- - '#'
  - 第 3 章 视图
- - '##'
  - 3.1 基本控件
- - '##'
  - 3.2 表格
- - '###'
  - 3.2.1 显示项目
- - '###'
  - 3.2.2 选中项目
- - '###'
  - 3.2.3 删除项目
- - '##'
  - 3.3 Web View
- - '###'
  - 3.3.1 Google Geocoding API
- - '###'
  - 3.3.2 调用 JavaScript 函数
- - '##'
  - 3.4 地图视图与地理定位
- - '##'
  - 3.5 自动布局
- - '###'
  - 图 3-18. 更新约束
- - '###'
  - 图 3-17. 创建间距约束
- - '##'
  - 3.6 尺寸类别
- - '###'
  - 图 3-20. iPhone 5S 不同方向的尺寸类别
- - '###'
  - 图 3-21. 显示尺寸类别及其简短描述的网格
- - '###'
  - 表 3-1. iOS 应用的尺寸类别
- - '###'
  - 图 3-22. 安装 wChC 尺寸类别
- - '###'
  - 图 3-23. AutoLayout 与尺寸类别结合使用，可以设计自适应视图，其中的控件会根据屏幕尺寸和方向调整大小并重新排列：竖屏（上）和横屏（下）
- - '##'
  - 3.7 UI 线程
- - '##'
  - 3.8 本章小结
- - '#'
  - 第 4 章 导航
- - '##'
  - 4.1 选项卡栏
- - '###'
  - 4.1.1 Pages
- - '##'
  - 4.2 视图控制器之间的导航
- - '###'
  - 4.2.1 编辑 Segue
- - '###'
  - 4.2.2 Unwind Segue
- - '###'
  - 4.2.3 准备 Segues
- - '##'
  - 4.3 本章小结
- - '#'
  - 第 5 章 触摸
- - '##'
  - 5.1 触摸与手势识别器
- - '##'
  - 5.2 iOS 中的手势识别器
- - '###'
  - 5.2.1 滑动与长按手势识别器
- - '###'
  - 5.2.2 使用手势操作控件
- - '####'
  - 平移手势识别器
- - '####'
  - 检测手势位置
- - '####'
  - 旋转和捏合手势识别器
- - '###'
  - 5.2.3 总仿射变换
- - '###'
  - 5.2.4 旋转和缩放控件
- - '####'
  - 同时手势识别
- - '##'
  - 5.3 总结
- - '#'
  - 第 6 章 单元测试
- - '##'
  - 6.1 创建待测试模型
- - '##'
  - 6.2 实现单元测试
- - '###'
  - 6.2.1 运行单元测试
- - '###'
  - 6.2.2 用户界面测试
- - '####'
  - 创建应用
- - '####'
  - Xamarin Test Cloud 代理
- - '####'
  - 创建 UI 测试
- - '###'
  - 6.2.3 Xamarin Test Cloud
- - '####'
  - 预置描述文件
- - '###'
  - 6.2.4 在 XTC 中运行测试
- - '##'
  - 6.3 本章小结
- - '#'
  - 第 7 章 使用 RESTful Web 服务
- - '##'
  - 7.1 REST 服务客户端
- - '###'
  - 7.1.1 更新数据
- - '###'
  - 7.1.2 获取特定用户
- - '##'
  - 7.2 测试 REST 客户端
- - '##'
  - 7.3 Users 仓库
- - '##'
  - 7.4 展示用户列表
- - '##'
  - 7.5 显示用户详情
- - '##'
  - 7.6 总结
- - '#'
  - 第 8 章 watchOS
- - '##'
  - 8.1 创建项目
- - '##'
  - 8.2 Watch 应用 Bundle
- - '##'
  - 8.3 Watch 扩展
- - '##'
  - 8.4 你好，手表！
- - '###'
  - 8.4.1 Watch 模拟器
- - '###'
  - 8.4.2 视图生命周期
- - '###'
  - 8.4.3 应用程序生命周期
- - '###'
  - 8.4.4 文本输入
- - '###'
  - 8.4.5 强制触摸与导航
- - '####'
  - 修改类定义
- - '##'
  - 8.5 通知控制器
- - '##'
  - 8.6 ClockKit 和复杂功能控制器
- - '###'
  - 8.6.1 排版后的文档
- - '##'
  - 8.7 快速查看控制器
- - '##'
  - 8.8 总结
- - '#'
  - 第 9 章 tvOS
- - '##'
  - 9.1 创建项目
- - '##'
  - 9.2 用户界面
- - '##'
  - 9.3 OpenWeatherMap API
- - '###'
  - 9.3.1 检索天气预报
- - '##'
  - 9.4 显示天气信息
- - '##'
  - 9.5 温度单位
- - '##'
  - 9.6 在模拟器中测试应用
- - '##'
  - 9.7 总结
- - '#'
  - 索引
- - '##'
  - A、B、C
- - '##'
  - D
- - '##'
  - E、F
- - '##'
  - G
- - '##'
  - H
- - '##'
  - I
- - '##'
  - J、K、L
- - '##'
  - M
- - '##'
  - N、O、P、Q
- - '##'
  - R
- - '##'
  - S
- - '##'
  - T
- - '##'
  - U
- - '##'
  - V
- - '##'
  - W
- - '##'
  - X、Y、Z
