name: Pro IOS Testing
name_cn: IOS 测试高级指南
slug: pro-ios-testing
toc:
- - '#'
  - 目录
- - '#'
  - 1. 测试简介
- - '##'
  - 简介
- - '##'
  - 如何阅读本书
- - '##'
  - 什么是软件测试？
- - '##'
  - iOS 中的软件测试
- - '##'
  - 为什么测试如此重要？
- - '##'
  - 我们可以测试什么？
- - '##'
  - 总结
- - '#'
  - 2. 设置我们的基础设施
- - '##'
  - 简介
- - '##'
  - 基本术语
- - '##'
  - “我的天气”应用
- - '###'
  - 向现有项目添加测试目标
- - '###'
  - 将一切关联起来
- - '##'
  - 信息标签页
- - '###'
  - 并行测试
- - '###'
  - 随机化执行顺序
- - '###'
  - 位置和应用程序数据
- - '####'
  - 位置
- - '####'
  - 应用程序数据
- - '##'
  - Arguments 选项卡
- - '###'
  - 启动参数
- - '###'
  - 环境变量
- - '##'
  - 选项选项卡
- - '##'
  - 诊断选项卡
- - '##'
  - 排除测试类
- - '###'
  - 通过方案编辑器禁用测试
- - '###'
  - 通过测试导航器禁用测试
- - '###'
  - 通过重命名来禁用测试
- - '##'
  - 创建多少个测试包？
- - '##'
  - 测试计划
- - '###'
  - 让您的工作更轻松的测试计划
- - '###'
  - 创建您的第一个测试计划
- - '###'
  - 测试计划配置
- - '###'
  - 运行你的测试计划
- - '####'
  - 仅运行一个配置
- - '##'
  - 总结
- - '#'
  - 3. 编写测试——基础
- - '##'
  - 引言
- - '##'
  - 单元测试到底是什么？
- - '##'
  - XCTest 和 XCTestCase
- - '###'
  - XCTestCase
- - '####'
  - 添加新的 XCTestCase 子类
- - '##'
  - 我们的第一个测试类
- - '##'
  - 启用可测试性
- - '###'
  - '@testable'
- - '###'
  - CocoaPods 与测试目标
- - '##'
  - XCTestCase 生命周期
- - '###'
  - 类方法 `setUp()`
- - '###'
  - '`setUpWithError()` 抛异常'
- - '###'
  - 测试方法
- - '###'
  - 拆解块
- - '###'
  - '`tearDownWithError()` 抛异常'
- - '###'
  - 类方法 `tearDown()`
- - '###'
  - 如何协同工作
- - '###'
  - XCTest 为每个测试方法创建一个 XCTestCase 实例
- - '##'
  - 编写单元测试
- - '###'
  - 单元测试结构
- - '###'
  - 断言
- - '###'
  - 创建自定义断言
- - '####'
  - 准备就绪：如何编写自定义断言？
- - '##'
  - 编写异步操作
- - '###'
  - Expect、Wait、Fulfill 和 Assert
- - '###'
  - XCTestExpectation 模式
- - '###'
  - 一个期望多次满足
- - '###'
  - 当期望未满足时进行断言
- - '###'
  - 期望数组，按顺序
- - '###'
  - XCTestExpectation 子类
- - '##'
  - 总结
- - '#'
  - 4. 编写测试——高级技巧
- - '##'
  - 引言
- - '##'
  - 测试替身（Fake, Fake, Fake）
- - '###'
  - Mocks。到处都是 Mocks？（？）
- - '####'
  - Dummy（哑对象）
- - '####'
  - Fake（伪造对象）
- - '####'
  - Stub（桩件）
- - '####'
  - 间谍（Spy）
- - '####'
  - 模拟（Mock）
- - '####'
  - 完全模拟 vs. 部分模拟
- - '###'
  - 尽量避免使用测试替身
- - '####'
  - 耦合
- - '#####'
  - 耦合类型
- - '#####'
  - 子类耦合
- - '#####'
  - 共享对象
- - '#####'
  - 依赖
- - '#####'
  - 副作用
- - '####'
  - 如何解耦现有代码？
- - '#####'
  - 耦合严重级别
- - '#####'
  - 紧耦合
- - '#####'
  - 耦合
- - '#####'
  - 松耦合
- - '#####'
  - 解耦
- - '####'
  - 修改你的代码
- - '#####'
  - 减少耦合的更多方法
- - '#####'
  - 比较
- - '#####'
  - 比较的问题
- - '#####'
  - Equatable 协议
- - '#####'
  - Comparable 协议
- - '#####'
  - 比较 UIImages
- - '#####'
  - 比较数组
- - '#####'
  - 比较在测试中的重要性
- - '##'
  - 参数化单元测试
- - '###'
  - 为测试创建抽象方法
- - '###'
  - 从文件加载测试用例
- - '###'
  - 动态调用测试
- - '####'
  - XCTestRun 环境
- - '####'
  - 第一步 —— 重写 `defaultTestSuite()` 变量
- - '####'
  - 创建 `XCTestSuite` 对象
- - '####'
  - 创建并动态添加新测试用例
- - '##'
  - 总结
- - '#'
  - 5. 集成测试
- - '##'
  - 引言
- - '##'
  - 集成测试背后的理念
- - '###'
  - 什么是集成测试
- - '###'
  - 集成测试 vs 单元测试
- - '###'
  - 定义测试范围
- - '####'
  - 填补空白
- - '####'
  - 就像单元测试与集成测试的比例关系
- - '##'
  - 编写集成测试
- - '###'
  - 我们的第一个集成测试
- - '###'
  - 并行运行
- - '###'
  - 集成测试中的故障点
- - '###'
  - 一个更庞大的测试系统
- - '##'
  - 增量式集成测试
- - '###'
  - 自底向上
- - '###'
  - 自顶向下
- - '##'
  - 处理边界问题
- - '##'
  - 客户端-服务器测试
- - '###'
  - 黑盒客户端-服务器测试
- - '###'
  - 白盒客户端-服务器测试
- - '##'
  - 将你的应用置于理想状态
- - '##'
  - 记录当前状态
- - '##'
  - 与黄金响应文件比较响应
- - '##'
  - 总结
- - '#'
  - 6. 编写可测试代码
- - '##'
  - 引言
- - '##'
  - 什么是可测试的代码？
- - '##'
  - 整洁代码
- - '###'
  - KISS（保持简单）
- - '###'
  - DRY
- - '###'
  - YAGNI（你不会需要它）
- - '###'
  - 易于阅读的代码也易于测试
- - '##'
  - 纯函数
- - '###'
  - 重构我们的函数使其成为纯函数
- - '###'
  - 面向协议编程
- - '##'
  - 依赖注入
- - '###'
  - 实现依赖注入的方式
- - '####'
  - 经典方式——基于初始化的依赖注入
- - '####'
  - 简单方式——基于属性的依赖注入
- - '####'
  - 折衷方式——基于参数的依赖注入
- - '##'
  - SOLID 原则
- - '###'
  - S —— 单一职责原则
- - '###'
  - O —— 开闭原则
- - '###'
  - L – 里氏替换原则
- - '###'
  - I – 接口隔离原则
- - '###'
  - D – 依赖倒置原则
- - '##'
  - 设计模式与架构
- - '###'
  - 单例模式
- - '###'
  - 外观模式
- - '###'
  - 装饰器
- - '###'
  - 工厂
- - '###'
  - MVC
- - '####'
  - 模型 – M
- - '####'
  - 视图 – V
- - '####'
  - 控制器 – C
- - '####'
  - MVC 的问题
- - '###'
  - MVP/MVVM
- - '###'
  - VIPER
- - '##'
  - 不同设计模式的比较
- - '##'
  - 总结
- - '#'
  - 7. 用户界面测试
- - '##'
  - 引言
- - '##'
  - 添加 UI 测试
- - '##'
  - UI 测试如何工作？
- - '###'
  - UIKit 中的无障碍功能 – accessibilityLabel
- - '###'
  - 元素树
- - '##'
  - 编写我们的第一个 UI 测试
- - '###'
  - XCUIApplication
- - '###'
  - 元素
- - '####'
  - 查询元素
- - '#####'
  - 查询如何工作？
- - '#####'
  - 精准使用查询
- - '#####'
  - 解析元素数据
- - '#####'
  - 按标识符或索引获取元素
- - '#####'
  - 元素查询示例
- - '####'
  - 对元素执行操作
- - '####'
  - 等待元素出现
- - '####'
  - 断言
- - '#####'
  - 整合所有内容
- - '###'
  - 记录您的操作
- - '##'
  - 处理问题
- - '###'
  - 保持测试的一致性
- - '####'
  - 处理系统警报
- - '##'
  - 页面对象模型
- - '###'
  - 问题所在
- - '###'
  - 什么是页面对象模型？
- - '##'
  - 测试报告
- - '###'
  - 活动
- - '###'
  - 附件
- - '####'
  - 屏幕截图
- - '#####'
  - 测试报告中的屏幕截图
- - '#####'
  - 检查附件
- - '#####'
  - 屏幕截图的位置
- - '###'
  - 关于 XCResult
- - '###'
  - 更多附件类型
- - '##'
  - 更多优秀的 UI 测试功能
- - '###'
  - 测试 Siri 集成
- - '###'
  - 多应用测试
- - '###'
  - 使用 XCUICoordinate 进行拖动
- - '##'
  - 总结
- - '#'
  - 8. 覆盖应用的另一个方面——性能测试
- - '##'
  - 简介
- - '##'
  - 性能测试的基本理念
- - '##'
  - 基础测量函数
- - '###'
  - 定义基准
- - '###'
  - “基准”对我们的测试意味着什么？
- - '####'
  - 为什么偏差很重要？
- - '##'
  - '`measure(metrics:)` 函数'
- - '###'
  - 分析指标
- - '####'
  - 单调时钟时间
- - '####'
  - CPU 周期、CPU 时间和 CPU 指令
- - '####'
  - 使用 XCTStorageMetric 检查写入活动
- - '###'
  - 使用 XCTMeasureOptions 进行更多配置
- - '####'
  - iterationCount
- - '####'
  - invocationOptions
- - '###'
  - 测量应用启动
- - '###'
  - 异步性能测试
- - '##'
  - 幕后的基线
- - '###'
  - Xcode 在哪里保存基线？
- - '###'
  - Xcode 如何从这些文件中获取基线
- - '##'
  - 总结
- - '#'
  - 9. 快照测试
- - '##'
  - 引言
- - '##'
  - 什么是快照测试？
- - '##'
  - 从零开始快照测试
- - '###'
  - 使用 Swift 关键字
- - '###'
  - 创建我们的断言函数
- - '##'
  - 快照测试的缺点
- - '###'
  - 缺少文档
- - '###'
  - 过于简单的修复
- - '###'
  - 为什么我的测试失败了
- - '##'
  - 使用 iOSSnapshotTestCase 进行 UI 快照测试
- - '###'
  - 为什么我们需要它？
- - '###'
  - iOSSnapshotTestCase
- - '###'
  - 它如何工作？
- - '###'
  - 设置并运行 iOSSnapshotTestCase
- - '####'
  - 使用 CocoaPods 安装
- - '####'
  - Pods for testing
- - '####'
  - 定义环境变量
- - '####'
  - 继承 FBSnapshotTestCase
- - '####'
  - 验证失败
- - '####'
  - 快照测试配置
- - '#####'
  - 包含设备信息
- - '#####'
  - 控制变化的容忍度及其他
- - '##'
  - 总结
- - '#'
  - 10. 在日常工作中实施测试
- - '##'
  - 引言
- - '##'
  - 我们如何开始？
- - '###'
  - 测试是开发任务的一部分
- - '###'
  - 需要决定测试什么
- - '###'
  - 修复了 Bug？那就编写一个测试
- - '##'
  - 测试组合
- - '##'
  - 测试金字塔
- - '###'
  - 经典金字塔
- - '###'
  - 冰淇淋甜筒模型
- - '###'
  - 测试菱形模型
- - '###'
  - 哪种才是正确的方法？
- - '##'
  - 如何构建测试场景？
- - '##'
  - 测试驱动开发 (TDD)
- - '##'
  - 行为驱动开发（BDD）
- - '###'
  - 如何编写好的 BDD 场景
- - '###'
  - 尝试撰写描述性场景
- - '###'
  - 每个场景专注于一个测试
- - '###'
  - 正确理解和使用 Gherkin 语言
- - '###'
  - 使用通俗语言编写场景
- - '###'
  - 考虑自动化测试的可行性
- - '###'
  - 基于场景创建测试
- - '##'
  - 代码覆盖率
- - '###'
  - 不要为代码覆盖率设定目标
- - '###'
  - 那么，我们为什么需要代码覆盖率？
- - '###'
  - 接下来是测试覆盖率。等等。什么？
- - '##'
  - 总结
- - '#'
  - 11. 使用命令行工具
- - '##'
  - 简介
- - '##'
  - 究竟什么是 CI/CD？
- - '###'
  - 测试如何融入其中？
- - '##'
  - 命令行工具
- - '###'
  - 认识 `xcodebuild`
- - '###'
  - 安装与设置 `xcodebuild`
- - '###'
  - 使用 xcodebuild 运行测试
- - '####'
  - 目标参数
- - '####'
  - 从命令行运行测试计划
- - '###'
  - 更多重要的 xcodebuild 参数
- - '##'
  - 总结
- - '#'
  - 索引
- - '##'
  - A
- - '##'
  - B
- - '##'
  - C
- - '##'
  - D, E
- - '##'
  - F
- - '##'
  - G, H
- - '##'
  - I, J
- - '##'
  - K
- - '##'
  - L
- - '##'
  - M
- - '##'
  - N
- - '##'
  - O
- - '##'
  - P, Q, R
- - '##'
  - S
- - '##'
  - T
- - '##'
  - U
- - '##'
  - V
- - '##'
  - W
- - '##'
  - X
- - '##'
  - Y, Z
