name: Beginning IOS Game Center and Game Kit
name_cn: IOS Game Center 与 Game Kit 入门指南
slug: beginning-ios-game-center-and-game-kit
toc:
- - '#'
  - 开始使用 iOS 游戏中心与游戏套件：适用于 iPhone、iPad 和 iPod touch
- - '##'
  - 目录概览
- - '##'
  - 关于作者
- - '##'
  - 关于技术评审者
- - '##'
  - 序言：游戏英雄凯尔的传奇
- - '###'
  - 引言
- - '####'
  - 预备知识
- - '####'
  - 本书的组织结构
- - '####'
  - 所需软件、素材与设备
- - '##'
  - 第 1 章：开始使用 Game Kit 与 Game Center
- - '###'
  - Game Kit：概述
- - '####'
  - 网络功能
- - '####'
  - Game Center
- - '####'
  - 语音聊天
- - '###'
  - 示例游戏：UFOs
- - '####'
  - UFO：了解游戏
- - '###'
  - UFO：检查源代码
- - '####'
  - 设置加速度计委托
- - '####'
  - 将玩家绘制到视图
- - '####'
  - 设置奶牛、光束和分数
- - '####'
  - 处理旋转事件
- - '###'
  - 添加玩家移动
- - '###'
  - 监听触摸事件
- - '###'
  - 生成与移动奶牛
- - '###'
  - 对 UIImage 执行碰撞检测
- - '####'
  - 绑架奶牛
- - '####'
  - 为 Game Center 配置 iTunes Connect
- - '###'
  - 开始使用 iTunes Connect
- - '####'
  - 在 iTunes Connect 中配置 Game Center
- - '###'
  - 概述
- - '##'
  - 第 2 章：Game Center：配置与入门
- - '###'
  - 测试 Game Center
- - '###'
  - 使用 Game Center 进行身份验证
- - '####'
  - 修改 `GameCenterManager` 类
- - '####'
  - 从 `UFOViewController` 进行身份验证
- - '###'
  - 沙盒
- - '###'
  - 监听状态变化
- - '###'
  - 使用 `GKLocalPlayer`
- - '###'
  - 获取好友列表
- - '####'
  - 好友列表头像
- - '###'
  - 与玩家协作
- - '###'
  - 本章小结
- - '##'
  - 第 3 章：排行榜
- - '###'
  - 为什么要用排行榜？
- - '###'
  - Game Center 排行榜概览
- - '####'
  - 使用 Apple 排行榜 GUI 与自定义 GUI 的优势对比
- - '###'
  - 在 iTunes Connect 中配置排行榜
- - '###'
  - 提交分数
- - '###'
  - 设置默认排行榜
- - '###'
  - 为 UFO 游戏添加分数提交功能
- - '###'
  - 处理提交分数时的失败情况
- - '##'
  - 展示排行榜
- - '###'
  - 自定义排行榜
- - '###'
  - 修改 GameCenterManager
- - '####'
  - 过滤自定义排行榜的结果
- - '####'
  - 显示自定义排行榜
- - '###'
  - 映射玩家 ID
- - '###'
  - 本地玩家分数
- - '###'
  - 更好的方法
- - '###'
  - 总结
- - '##'
  - 第 4 章：成就
- - '###'
  - 为什么使用成就？
- - '###'
  - Game Center 成就概览
- - '###'
  - 使用苹果成就 GUI 对比自定义 GUI 的优势
- - '###'
  - 在 iTunes Connect 中配置成就
- - '####'
  - 呈现成就
- - '####'
  - 修改成就进度
- - '###'
  - 重置成就
- - '###'
  - 添加成就钩子
- - '###'
  - 排版后的内容
- - '###'
  - 另一个便捷方法
- - '###'
  - 成就完成反馈
- - '###'
  - iOS 5 完成横幅
- - '####'
  - 自定义成就界面
- - '####'
  - 从提交失败中恢复
- - '###'
  - 总结
- - '##'
  - 第 5 章：匹配与邀请
- - '###'
  - 为何要在应用中添加匹配与邀请功能？
- - '###'
  - 常见的匹配场景
- - '###'
  - 创建新的匹配请求
- - '###'
  - 展示匹配界面
- - '###'
  - 处理收到的邀请
- - '###'
  - 自动匹配
- - '###'
  - 以编程方式匹配
- - '###'
  - 向匹配中添加玩家
- - '###'
  - iOS 5 重新邀请
- - '###'
  - 玩家分组
- - '###'
  - 玩家属性
- - '####'
  - 了解玩家属性的限制
- - '###'
  - 使用玩家属性
- - '###'
  - 玩家活跃度
- - '###'
  - 使用自有服务器（托管比赛）
- - '###'
  - 本章小结
- - '##'
  - 第 6 章：玩家选择器
- - '###'
  - 对等选择器的优势
- - '###'
  - 真实世界案例
- - '###'
  - 使用会话
- - '###'
  - 展示对等端选择器
- - '###'
  - 高级 `GKSession` 交互
- - '###'
  - 对等选择器委托
- - '###'
  - 总结
- - '##'
  - 第 7 章：网络设计概述
- - '###'
  - 三种网络类型
- - '####'
  - 对等网络
- - '####'
  - 客户端-主机网络
- - '####'
  - 环形网络
- - '###'
  - 较少见的网络
- - '###'
  - 可靠数据 vs. 不可靠数据
- - '###'
  - 只发送必要的数据
- - '###'
  - 预测与外推
- - '###'
  - 格式化消息
- - '###'
  - 防止作弊和防止超时断线
- - '###'
  - 当其他方法都失败时该怎么办
- - '###'
  - 本章小结
- - '##'
  - 第 8 章：交换数据
- - '###'
  - 修改单人游戏
- - '###'
  - 为多人游戏配置引擎
- - '####'
  - 选定主机
- - '###'
  - 发送数据
- - '###'
  - 接收数据
- - '####'
  - 整合所有内容
- - '####'
  - 选择主机
- - '####'
  - 显示敌方飞碟
- - '####'
  - 生成奶牛
- - '###'
  - 共享分数
- - '###'
  - 添加网络绑架代码
- - '###'
  - 断开连接
- - '###'
  - 总结
- - '##'
  - 第 9 章：使用 Game Center 进行回合制游戏
- - '###'
  - 新示例项目
- - '###'
  - GKTurnedBasedMatchmakerViewController
- - '###'
  - 开始新游戏
- - '###'
  - 执行第一步落子
- - '###'
  - 继续正在进行的游戏
- - '###'
  - 结束比赛
- - '###'
  - 退出与弃权
- - '###'
  - 程序化匹配
- - '###'
  - GKTurnBasedEventHandler
- - '###'
  - 总结
- - '##'
  - 第 10 章：语音聊天
- - '###'
  - Game Center 的语音聊天
- - '####'
  - 创建音频会话
- - '####'
  - 创建新的语音频道
- - '####'
  - 启动与停止语音聊天
- - '####'
  - 聊天音量与静音
- - '####'
  - 监控玩家状态
- - '###'
  - Game Kit 的语音聊天
- - '####'
  - 创建音频会话
- - '####'
  - 必需的准备工作
- - '###'
  - 启动运行
- - '###'
  - 整合在一起
- - '###'
  - 本章小结
- - '##'
  - 第 11 章：使用 StoreKit 实现应用内购买
- - '###'
  - 在 iTunes Connect 中设置你的 App
- - '###'
  - 向你的 App 添加产品
- - '####'
  - App ID 与 App 内购买
- - '####'
  - 设置
- - '###'
  - 获取产品列表
- - '###'
  - 向用户展示产品
- - '###'
  - 购买产品
- - '####'
  - 购买代码
- - '#####'
  - 购买多个商品
- - '#####'
  - 处理交易
- - '#####'
  - 恢复先前完成的交易
- - '###'
  - 测试账户与测试购买
- - '###'
  - 使用测试账户登录
- - '###'
  - 提交购买界面截图
- - '###'
  - 开发者审批
- - '###'
  - 收据
- - '###'
  - 在 UFOs 中将一切整合
- - '###'
  - 总结
- - '##'
  - 索引
- - '###'
  - 符号与数字
- - '###'
  - A
- - '###'
  - B
- - '###'
  - C
- - '###'
  - D
- - '###'
  - E
- - '###'
  - F
- - '###'
  - G
- - '###'
  - H
- - '###'
  - I, J
- - '###'
  - L
- - '###'
  - M
- - '###'
  - N
- - '###'
  - O
- - '###'
  - P
- - '###'
  - Q
- - '###'
  - R
- - '###'
  - S
- - '###'
  - T
- - '###'
  - U
- - '###'
  - V
- - '###'
  - W, X
- - '###'
  - Y, Z
