name: Learn Objective-C for Java developers
name_cn: Java 开发者的 Objective-C 入门指南
slug: learn-objective-c-for-java-developers
toc:
- - '#'
  - 为 Java 开发者学习 Objective-C
- - '#'
  - 第一部分：语言
- - '##'
  - 第 1 章：引言
- - '###'
  - 本书读者对象
- - '###'
  - 本书结构
- - '###'
  - 前提条件
- - '###'
  - 下载源代码
- - '###'
  - 联系作者
- - '###'
  - 什么是 Objective-C？
- - '####'
  - 历史
- - '####'
  - 一种现代面向对象语言
- - '####'
  - 先进的编译器
- - '####'
  - 性能
- - '####'
  - 动态性
- - '###'
  - 开发者生产力
- - '###'
  - 学习一门新语言
- - '###'
  - 术语与文化冲击
- - '###'
  - 定义“更好”
- - '##'
  - 第 2 章：Java 与 C 的关键差异
- - '###'
  - 基本类型
- - '###'
  - 常量
- - '###'
  - Typedefs
- - '###'
  - 指针
- - '###'
  - 结构体
- - '###'
  - 对象引用
- - '###'
  - 数组
- - '###'
  - '`static`'
- - '###'
  - 函数
- - '###'
  - '`extern`'
- - '###'
  - 预处理器
- - '###'
  - 预处理器指令（`#if`等）
- - '###'
  - '`#include` 和 `#import`'
- - '###'
  - 初始化自动变量
- - '###'
  - 标签：break、continue 和 goto
- - '###'
  - 本章小结
- - '##'
  - 第 3 章：欢迎使用 Objective-C
- - '###'
  - 定义一个 Objective-C 类
- - '###'
  - 对象指针
- - '###'
  - 如果你把所有对象指针都声明为 `id` 类型
- - '###'
  - 发送消息
- - '###'
  - 命名方法
- - '###'
  - 方法命名的可读性
- - '###'
  - 参数和返回类型
- - '###'
  - 方法选择器
- - '###'
  - 实例变量
- - '###'
  - '`isa`'
- - '###'
  - 属性
- - '####'
  - 属性声明
- - '####'
  - 属性特性
- - '####'
  - 重写属性
- - '###'
  - 格式规范说明
- - '###'
  - 提示
- - '###'
  - 访问属性
- - '###'
  - 作用域
- - '####'
  - 类名作用域
- - '####'
  - 实例变量作用域
- - '####'
  - 方法作用域
- - '####'
  - 类似的技术也适用于 `@property` 指令。
- - '####'
  - 前向 `@class` 指令
- - '####'
  - '`self` 和 `super`'
- - '###'
  - 类方法
- - '###'
  - 构造对象
- - '###'
  - 编写 init 方法
- - '####'
  - 链式初始化方法
- - '####'
  - 指定初始化方法
- - '####'
  - 便捷构造函数
- - '####'
  - 析构函数
- - '####'
  - 缺失了什么？
- - '##'
  - 第 4 章：创建 Xcode 项目
- - '###'
  - 下载项目
- - '###'
  - 创建项目
- - '###'
  - 开始之前
- - '###'
  - 设计应用程序
- - '###'
  - 设计用户界面
- - '###'
  - 添加控制器
- - '###'
  - 建立绑定
- - '###'
  - KVC
- - '###'
  - KVO
- - '###'
  - 控制器
- - '###'
  - 绑定
- - '###'
  - 添加数组控制器
- - '###'
  - 开始业务逻辑
- - '###'
  - 调试应用程序
- - '####'
  - 创建沙盒应用
- - '###'
  - 总结
- - '##'
  - 第 5 章：探索协议与类别
- - '###'
  - 协议
- - '####'
  - 非正式协议
- - '####'
  - 结合正式协议与非正式协议
- - '###'
  - 类别
- - '####'
  - 使用类别进行组织
- - '####'
  - 隐藏方法
- - '####'
  - 扩充外部类
- - '###'
  - 扩展
- - '###'
  - 摘要
- - '##'
  - 第 6 章：发送消息
- - '###'
  - 编译消息
- - '####'
  - 未声明的方法
- - '####'
  - 歧义方法
- - '####'
  - 强制类型转换
- - '###'
  - 以编程方式发送消息
- - '####'
  - 即时消息
- - '####'
  - 延迟消息
- - '###'
  - 面向对象的方法调用
- - '###'
  - 直接调用方法
- - '###'
  - 可变参数
- - '###'
  - 未实现的方法
- - '###'
  - 摘要
- - '##'
  - 第 7 章：与 `nil` 交朋友
- - '###'
  - 向 `nil` 发送消息是安全的
- - '###'
  - '`nil` 返回零值'
- - '###'
  - 用 `nil` 进行设计
- - '####'
  - 属性访问器
- - '####'
  - 缺失行为
- - '####'
  - 与空值的一致性
- - '###'
  - 没有免费的午餐
- - '###'
  - 摘要
- - '#'
  - 第二部分：翻译技术
- - '##'
  - 第 8 章：字符串和原始值
- - '###'
  - 包装标量基本类型
- - '####'
  - 标量类型转换
- - '####'
  - 将字符串转换为标量
- - '###'
  - 包装数组
- - '###'
  - 包装任意值
- - '###'
  - 包装 nil
- - '###'
  - 字符串
- - '####'
  - 将对象转换为字符串
- - '####'
  - C 语言字符串
- - '###'
  - 格式化字符串
- - '####'
  - NSFormatter
- - '#####'
  - NSNumberFormatter
- - '#####'
  - NSDateFormatter
- - '###'
  - 摘要
- - '##'
  - 第 9 章：垃圾回收
- - '###'
  - 选择使用垃圾回收
- - '###'
  - 编写支持垃圾回收的代码
- - '###'
  - 编写 finalize 方法
- - '###'
  - 创建弱引用
- - '###'
  - 创建强引用
- - '###'
  - 触发垃圾回收
- - '###'
  - GC 与非 GC 指针
- - '####'
  - 写入屏障
- - '####'
  - 分配可回收内存
- - '####'
  - 垃圾回收陷阱
- - '#####'
  - 内部指针
- - '#####'
  - 不透明指针
- - '#####'
  - 枚举弱集合
- - '#####'
  - 未初始化的栈引用
- - '#####'
  - 其他陷阱
- - '###'
  - 应避免的设计模式
- - '###'
  - 调试
- - '###'
  - 摘要
- - '##'
  - 第 10 章：自省
- - '###'
  - 测试方法
- - '###'
  - 测试类成员关系
- - '###'
  - 键值编码
- - '####'
  - 使用键值编码
- - '####'
  - 设计符合 KVC 规范的类
- - '####'
  - 自定义键值
- - '###'
  - 检查类
- - '###'
  - 探索协议
- - '###'
  - 探索方法
- - '###'
  - 探索属性
- - '###'
  - 探索实例变量
- - '###'
  - 总结
- - '##'
  - 第 11 章：文件
- - '###'
  - 文件系统 API
- - '####'
  - 标识文件系统中的项目
- - '#####'
  - 文件与路径名称
- - '#####'
  - 工作目录
- - '#####'
  - 文件 URL
- - '#####'
  - 创建与删除目录
- - '#####'
  - 定位特殊目录
- - '###'
  - 向用户请求文件
- - '###'
  - 符号链接、硬链接与别名
- - '###'
  - 处理目录内容
- - '###'
  - 文件属性
- - '###'
  - 高级文件操作
- - '###'
  - NSWorkspace
- - '###'
  - 随机文件访问
- - '###'
  - NSFileManager 委托
- - '###'
  - 备选 API
- - '###'
  - 总结
- - '##'
  - 第 12 章：序列化
- - '###'
  - 归档
- - '####'
  - 归档类型
- - '####'
  - 归档编码器
- - '####'
  - 归档与文档
- - '###'
  - 为你的类添加基于键的归档支持
- - '###'
  - 为你的类添加顺序归档支持
- - '###'
  - 同时支持基于键和顺序的归档
- - '###'
  - 归档的复杂性
- - '####'
  - 瞬态属性
- - '####'
  - 重复对象
- - '####'
  - 限制对象图
- - '####'
  - 类版本兼容性
- - '###'
  - Objective-C 序列化
- - '###'
  - 属性列表
- - '###'
  - XML
- - '###'
  - 复制对象
- - '###'
  - 总结
- - '##'
  - 第 13 章：远近通信
- - '###'
  - 单进程内通信
- - '###'
  - 与其他进程通信
- - '####'
  - 底层通信
- - '#####'
  - '`NSPort`'
- - '#####'
  - '`NSPipe` 和 `NSFileHandle`'
- - '#####'
  - '`NSStream`'
- - '####'
  - 高层通信
- - '#####'
  - 分布式通知
- - '#####'
  - 分布式对象
- - '###'
  - 网络
- - '####'
  - 网络服务
- - '####'
  - URL 加载
- - '#####'
  - 简单 URL 请求
- - '#####'
  - 异步 URL 请求
- - '#####'
  - 写入 URL
- - '#####'
  - 下载 URL
- - '#####'
  - 缓存与 Cookie
- - '###'
  - 总结
- - '##'
  - 第 14 章：异常处理
- - '###'
  - 使用异常
- - '###'
  - 异常处理的差异
- - '####'
  - 无需捕获或指定
- - '####'
  - 可抛出任何对象
- - '####'
  - 重新抛出异常
- - '####'
  - 捕获顺序
- - '####'
  - 链式调用
- - '####'
  - 调用堆栈
- - '####'
  - 性能
- - '####'
  - 未捕获异常
- - '###'
  - 遗留异常
- - '###'
  - 断言
- - '###'
  - 异常处理的替代方案
- - '####'
  - 简单错误
- - '####'
  - POSIX 错误码
- - '####'
  - Core Foundation 错误码
- - '####'
  - Cocoa 错误
- - '#####'
  - 错误域
- - '#####'
  - 自定义与显示
- - '#####'
  - 本地化
- - '#####'
  - 恢复
- - '###'
  - 结合错误与异常
- - '###'
  - 总结
- - '##'
  - 第 15 章：线程
- - '###'
  - 线程 API
- - '###'
  - 启动线程
- - '###'
  - 管理线程
- - '####'
  - 使线程休眠
- - '####'
  - 线程属性
- - '#####'
  - 信息
- - '#####'
  - 线程特定值
- - '#####'
  - 优先级
- - '#####'
  - 栈大小
- - '#####'
  - 名称
- - '###'
  - 终止线程
- - '###'
  - 运行循环
- - '####'
  - 启动运行循环
- - '####'
  - 运行循环模式
- - '####'
  - 停止运行循环
- - '####'
  - 自定义运行循环
- - '###'
  - 线程通知
- - '###'
  - 线程同步
- - '####'
  - '`@synchronized` 指令'
- - '####'
  - 互斥信号量对象
- - '####'
  - NSLock
- - '####'
  - NSRecursiveLock
- - '####'
  - NSConditionLock
- - '####'
  - NSDistributedLock
- - '####'
  - 自旋锁
- - '###'
  - 操作
- - '###'
  - 定时器
- - '###'
  - 总结
- - '#'
  - 第三部分：编程模式
- - '##'
  - 第 16 章：集合模式
- - '###'
  - 不可变集合
- - '###'
  - 有序集合
- - '####'
  - 常用方法
- - '####'
  - '`NSArray`、`NSMutableArray`'
- - '####'
  - '`NSPointerArray`'
- - '###'
  - 字典集合
- - '####'
  - 常用方法
- - '####'
  - '`NSDictionary`、`NSMutableDictionary`'
- - '####'
  - '`NSMapTable`'
- - '###'
  - 集合
- - '####'
  - 通用方法
- - '####'
  - '`NSSet`、`NSMutableSet`'
- - '####'
  - '`NSCountedSet`'
- - '####'
  - '`NSIndexSet`'
- - '####'
  - '`NSHashTable`'
- - '###'
  - 组合模式
- - '###'
  - 集合相等性约定
- - '###'
  - 使用枚举器进行快速枚举
- - '####'
  - 使用枚举器
- - '####'
  - 添加枚举支持
- - '###'
  - 排序集合
- - '####'
  - Objective-C 消息排序
- - '####'
  - C 函数排序
- - '####'
  - 排序描述符
- - '###'
  - 过滤集合
- - '###'
  - 集合并发性
- - '####'
  - 枚举集合的副本
- - '####'
  - 延迟对集合的修改
- - '####'
  - 线程安全
- - '####'
  - 垃圾回收与弱引用集合
- - '###'
  - 总结
- - '##'
  - 第 17 章：委托模式
- - '###'
  - 理解委托
- - '###'
  - 使用委托
- - '###'
  - 委托方法
- - '###'
  - 委托协议
- - '###'
  - 结合委托模式
- - '###'
  - 总结
- - '##'
  - 第 18 章：提供者/订阅者模式
- - '###'
  - 通知
- - '####'
  - 通知中心
- - '####'
  - 发布同步通知
- - '####'
  - 做一个有辨别力的观察者
- - '####'
  - 移除观察者
- - '###'
  - 通知队列
- - '####'
  - 排队一个通知
- - '####'
  - 通知合并
- - '####'
  - 通知出列
- - '###'
  - 分布式通知
- - '####'
  - 分布式通知中心
- - '####'
  - 属性列表值
- - '####'
  - 异步通知传递
- - '###'
  - 总结
- - '##'
  - 第 19 章：观察者模式
- - '###'
  - 键值观察的工作原理
- - '###'
  - 与提供者/订阅者及观察者模式的比较
- - '###'
  - KVO 的核心特性
- - '###'
  - 注册键值观察者
- - '###'
  - 处理键值变更通知
- - '###'
  - 注销观察者
- - '###'
  - 使你的类符合 KVO 标准
- - '###'
  - 发送手动 KVO 通知
- - '###'
  - 创建属性依赖关系
- - '###'
  - 重写键值观察
- - '###'
  - 优化键值观察
- - '###'
  - 摘要
- - '##'
  - 第 20 章：模型-视图-控制器模式
- - '###'
  - 理解模型-视图-控制器
- - '###'
  - MVC 的变体
- - '####'
  - 控制器与数据模型合并
- - '####'
  - 中介控制器
- - '####'
  - 视图与数据模型的直接绑定
- - '####'
  - 其他变体
- - '###'
  - MVC 的优势
- - '####'
  - 模块化
- - '####'
  - 灵活性
- - '####'
  - 复用
- - '####'
  - 扩展
- - '###'
  - Interface Builder
- - '####'
  - NIB 文档
- - '####'
  - 连接
- - '#####'
  - 输出口
- - '#####'
  - 操作
- - '####'
  - 绑定
- - '###'
  - 视图
- - '####'
  - 视图几何
- - '####'
  - 自定义视图
- - '###'
  - 文档模型
- - '###'
  - 事件与响应者
- - '####'
  - 动态应用
- - '####'
  - 事件
- - '#####'
  - 事件对象
- - '#####'
  - 按键事件
- - '#####'
  - 鼠标事件
- - '####'
  - 响应者链
- - '###'
  - 操作消息
- - '####'
  - 发送操作消息
- - '####'
  - 菜单操作
- - '####'
  - 使用响应者链进行设计
- - '###'
  - 数据模型
- - '####'
  - 传统表和树模型
- - '####'
  - 集合控制器
- - '####'
  - Core Data
- - '####'
  - 自定义数据模型对象
- - '###'
  - 控制器
- - '####'
  - 自定义控制器
- - '###'
  - 关于 TicTacToe
- - '###'
  - Info.plist
- - '###'
  - 撤销
- - '###'
  - 资源
- - '####'
  - 本地化资源
- - '###'
  - 总结
- - '##'
  - 第 21 章：懒加载模式
- - '###'
  - 实现该模式
- - '###'
  - 全局变量的懒加载
- - '###'
  - 类的 `+initialize` 方法
- - '##'
  - 第 22 章：工厂模式
- - '###'
  - URL 工厂
- - '###'
  - 矩阵类
- - '###'
  - Java 矩阵工厂
- - '###'
  - Objective-C 矩阵类簇
- - '####'
  - '`Matrix` 的实现'
- - '####'
  - '`MatrixCopyArray` 函数'
- - '###'
  - 类簇
- - '###'
  - 小结
- - '##'
  - 第 23 章：单例模式
- - '###'
  - 实现单例
- - '###'
  - 惰性单例
- - '###'
  - 单例工厂
- - '###'
  - 总结
- - '#'
  - 第四部分：高级 Objective-C
- - '##'
  - 第 24 章：内存管理
- - '###'
  - C 语言内存分配
- - '###'
  - Objective-C 的引用计数
- - '###'
  - 自动释放池
- - '####'
  - 自动释放池的生命周期
- - '####'
  - 返回的引用
- - '###'
  - 托管内存模式
- - '####'
  - 新对象模式
- - '####'
  - 自动释放对象模式
- - '####'
  - 返回自动释放的对象
- - '####'
  - 设置器模式
- - '####'
  - '`init` 模式'
- - '####'
  - '`dealloc` 模式'
- - '###'
  - 隐式保留的对象
- - '###'
  - 管理内存的问题
- - '####'
  - 过度保留或释放不足的对象
- - '###'
  - 混合受管内存与垃圾回收
- - '###'
  - 总结
- - '##'
  - 第 25 章：混合 C 和 Objective-C
- - '###'
  - 在 Objective-C 中使用 C
- - '####'
  - 从 Objective-C 调用 C 函数
- - '####'
  - 在 C 中使用 Objective-C 对象
- - '###'
  - Core Foundation
- - '###'
  - 无缝桥接
- - '###'
  - C 内存管理
- - '####'
  - 使用 Core Foundation 内存管理模式
- - '####'
  - 使用垃圾回收的 Core Foundation
- - '####'
  - 在托管内存中使用 Core Foundation
- - '###'
  - 总结
- - '##'
  - 第 26 章：运行时
- - '###'
  - 进程
- - '####'
  - 环境
- - '####'
  - 命令行参数
- - '####'
  - 进程属性
- - '###'
  - 版本控制
- - '####'
  - 控制开发与部署版本
- - '####'
  - 测试类、方法和函数
- - '###'
  - 软件包和捆绑包
- - '###'
  - 框架
- - '###'
  - 用户默认设置
- - '###'
  - isa 交换
- - '###'
  - 64 位编程
- - '###'
  - 总结
- - '#'
  - 参考文献
- - '#'
  - 索引
