name: Objective-C for Absolute Beginners
name_cn: 绝对初学者的 Objective-C
slug: objective-c-for-absolute-beginners
toc:
- - '##'
  - 目录一览
- - '#'
  - 第 9 章：数据比较
- - '#'
  - 第 10 章：创建用户界面
- - '#'
  - 第 11 章：信息存储
- - '#'
  - 第 12 章：协议与委托
- - '#'
  - 第 13 章：内存、地址与指针
- - '#'
  - 第 14 章：介绍 Xcode 调试器
- - '#'
  - 索引
- - '##'
  - 关于作者
- - '##'
  - 关于技术审校
- - '##'
  - 引言
- - '###'
  - 写给新手
- - '###'
  - 写给更有经验的开发者
- - '###'
  - 为什么选择 Alice：一个创新的 3D 编程环境
- - '###'
  - 不使用 Alice 学习 Objective-C
- - '###'
  - 本书的组织方式
- - '###'
  - 成功公式
- - '###'
  - 开发技术栈
- - '###'
  - 所需软件、材料和设备
- - '####'
  - 操作系统与集成开发环境
- - '####'
  - 软件开发工具包
- - '####'
  - 双显示器
- - '###'
  - 免费在线研讨会、问答与 YouTube 视频
- - '####'
  - 免费书籍论坛
- - '#'
  - 第 1 章：成为优秀的 iOS 或 Mac 程序员
- - '###'
  - 像开发者一样思考
- - '###'
  - 完成开发周期
- - '###'
  - 面向对象编程简介
- - '###'
  - 使用 Alice 界面
- - '###'
  - 本章小结
- - '###'
  - 练习
- - '#'
  - 第 2 章：编程基础
- - '###'
  - 与爱丽丝一起探索
- - '####'
  - 导航菜单
- - '####'
  - 世界窗口
- - '####'
  - 爱丽丝中的类、对象和实例
- - '####'
  - 对象树
- - '####'
  - 编辑器区域
- - '####'
  - 详细信息区域
- - '####'
  - 事件区域
- - '###'
  - 创建 Alice 应用——登月，爱丽丝
- - '###'
  - 你的第一个 Objective-C 程序
- - '###'
  - 启动和使用 Xcode 4.2
- - '###'
  - 总结
- - '###'
  - 练习
- - '#'
  - 第 3 章：数据即为一切
- - '###'
  - 编程中使用的数制
- - '###'
  - 位（Bits）
- - '####'
  - 摩尔定律
- - '###'
  - 字节（Bytes）
- - '###'
  - 十六进制（Hexadecimal）
- - '###'
  - Unicode
- - '###'
  - 数据类型（Data Types）
- - '####'
  - 使用 Alice 操作变量与数据类型
- - '####'
  - 数据类型与 Objective-C
- - '###'
  - 问题识别
- - '###'
  - 总结
- - '###'
  - 练习
- - '#'
  - 第 4 章：做出决策……并规划程序流程
- - '##'
  - 布尔逻辑
- - '###'
  - 真值表
- - '###'
  - 比较运算符
- - '##'
  - 设计应用程序
- - '###'
  - 伪代码
- - '###'
  - 设计需求
- - '###'
  - 流程图制作
- - '###'
  - 设计并绘制示例应用的流程图
- - '###'
  - 应用的设计
- - '##'
  - 使用循环重复执行程序语句
- - '###'
  - 计数控制循环
- - '###'
  - 条件控制循环
- - '###'
  - 无限循环
- - '##'
  - 在 Alice 中编写示例应用
- - '###'
  - 使用 Objective-C 编写示例应用
- - '####'
  - 嵌套 If 语句与 Else-If 语句
- - '####'
  - 移除多余字符
- - '####'
  - 通过重构改进代码
- - '####'
  - 运行应用
- - '###'
  - 告别 Alice，继续前进
- - '###'
  - 本章小结
- - '###'
  - 练习
- - '#'
  - 第 5 章：使用 Objective-C 进行面向对象编程
- - '##'
  - 对象
- - '##'
  - 什么是类？
- - '##'
  - 规划类
- - '###'
  - 规划属性
- - '##'
  - 规划方法
- - '###'
  - 实现类
- - '##'
  - 继承
- - '##'
  - 为什么要使用 OOP？
- - '###'
  - 随处可见
- - '###'
  - 消除冗余代码
- - '###'
  - 易于调试
- - '###'
  - 易于替换
- - '##'
  - 高级主题
- - '###'
  - 接口
- - '###'
  - 多态性
- - '##'
  - 总结
- - '###'
  - 练习
- - '#'
  - 第 6 章：学习 Objective-C 和 Xcode
- - '###'
  - Objective-C 简史
- - '###'
  - 理解语言符号
- - '###'
  - 将“Objective”注入 Objective-C
- - '###'
  - 在 Xcode 中编写另一个程序
- - '###'
  - 创建项目
- - '##'
  - 总结
- - '###'
  - 练习
- - '#'
  - 第 7 章：Objective-C 类、对象和方法
- - '##'
  - 创建 Objective-C 类
- - '###'
  - 声明接口和实例变量
- - '###'
  - 发送消息（方法）
- - '###'
  - 使用类方法
- - '###'
  - 使用实例方法
- - '###'
  - 处理实现文件
- - '###'
  - 编写方法
- - '##'
  - 使用你的新类
- - '###'
  - 创建项目
- - '###'
  - 添加对象
- - '###'
  - 编写实现文件
- - '##'
  - 创建用户界面
- - '##'
  - 连接代码
- - '###'
  - 运行程序
- - '###'
  - 进一步掌握类方法
- - '##'
  - 访问 Xcode 文档
- - '##'
  - 本章小结
- - '###'
  - 练习
- - '#'
  - 第 8 章：Objective-C 编程基础
- - '##'
  - 集合
- - '###'
  - 使用 NSSet
- - '###'
  - 使用 NSArray
- - '###'
  - 使用 NSDictionary
- - '###'
  - 确定集合中的类类型
- - '##'
  - 使用可变类
- - '###'
  - NSMutableSet
- - '###'
  - NSMutableArray
- - '###'
  - NSMutableDictionary
- - '##'
  - 创建 BookStore 应用程序
- - '##'
  - 引入实例变量
- - '###'
  - 访问实例变量
- - '###'
  - 使用 Getter 和 Setter 方法
- - '##'
  - 介绍属性
- - '##'
  - 使用属性
- - '##'
  - 理解命名规范的重要性
- - '##'
  - 完成 MyBookstore 程序
- - '###'
  - 创建视图
- - '###'
  - 添加实例变量
- - '###'
  - 添加描述
- - '####'
  - 创建一个简单的数据模型类
- - '###'
  - 修改 MasterViewController
- - '###'
  - 代码行示例
- - '##'
  - 修改 DetailViewController
- - '##'
  - 摘要
- - '##'
  - 练习
- - '#'
  - 第 9 章：比较数据
- - '##'
  - 重温布尔逻辑
- - '##'
  - 使用关系运算符
- - '###'
  - 比较数字
- - '###'
  - 创建示例 Xcode 应用
- - '##'
  - 使用布尔表达式
- - '##'
  - 比较字符串
- - '##'
  - 比较日期
- - '##'
  - 组合比较
- - '##'
  - 使用 Switch 语句
- - '##'
  - 总结
- - '###'
  - 练习
- - '#'
  - 第 10 章：创建用户界面
- - '##'
  - 理解 Interface Builder
- - '##'
  - 模型-视图-控制器
- - '##'
  - 人机界面指南（HIGs）
- - '##'
  - 使用 Interface Builder 创建示例 iPhone 应用
- - '###'
  - 使用 Interface Builder
- - '##'
  - 停靠面板
- - '##'
  - 资源库
- - '##'
  - 检查器面板和选择器栏
- - '##'
  - 创建视图
- - '##'
  - 使用 Outlet
- - '##'
  - 连接 Action 和对象
- - '##'
  - 实现文件
- - '##'
  - 总结
- - '###'
  - 练习
- - '#'
  - 第 11 章：存储信息
- - '##'
  - 存储考量
- - '##'
  - 数据库
- - '##'
  - 在数据库中存储信息
- - '##'
  - Core Data 入门
- - '##'
  - 模型
- - '##'
  - 托管对象上下文
- - '##'
  - 设置界面
- - '##'
  - 小结
- - '###'
  - 练习
- - '#'
  - 第 12 章：协议与委托
- - '##'
  - 多重继承
- - '##'
  - 理解协议
- - '###'
  - 协议语法
- - '##'
  - 理解委托
- - '##'
  - 下一步行动
- - '##'
  - 本章小结
- - '#'
  - 第 13 章：内存、地址与指针
- - '##'
  - 理解内存
- - '###'
  - 位、字节与进制
- - '###'
  - 将十进制（Base-10）转换为二进制（Base-2）
- - '###'
  - 使用十六进制（Base-16）计数法
- - '###'
  - 理解内存地址基础
- - '##'
  - 使用解引用运算符
- - '##'
  - 分配内存
- - '###'
  - 使用自动变量和指针
- - '###'
  - 释放内存
- - '###'
  - 使用特殊指针
- - '###'
  - 在 Objective-C 中使用 ARC 管理内存
- - '###'
  - 在没有 ARC 的 Objective-C 中管理内存
- - '####'
  - 使用保留/释放模型
- - '####'
  - 处理隐式保留消息和自动释放
- - '####'
  - 发送 `dealloc` 消息
- - '###'
  - 如果出现问题
- - '###'
  - 关于 ARC 的说明
- - '###'
  - 总结
- - '###'
  - 练习
- - '#'
  - 第 14 章：Xcode 调试器介绍
- - '##'
  - 开始调试
- - '###'
  - 设置断点
- - '###'
  - 使用断点导航器
- - '####'
  - 调试基础
- - '####'
  - 使用调试器控件
- - '####'
  - 使用单步执行控件
- - '####'
  - 查看线程窗口与调用堆栈
- - '####'
  - 调试变量
- - '###'
  - 处理代码错误和警告
- - '####'
  - 警告
- - '###'
  - 本章小结
- - '##'
  - 索引
- - '###'
  - 特殊字符与数字
- - '###'
  - A
- - '###'
  - B
- - '###'
  - C
- - '###'
  - D
- - '###'
  - E
- - '###'
  - F
- - '###'
  - G
- - '###'
  - H
- - '###'
  - I, J
- - '###'
  - K
- - '###'
  - L
- - '###'
  - M
- - '###'
  - N
- - '###'
  - O
- - '###'
  - P
- - '###'
  - Q
- - '###'
  - R
- - '###'
  - S
- - '###'
  - T
- - '###'
  - U
- - '###'
  - V
- - '###'
  - W
- - '###'
  - X, Y, Z
