name: Swift Game Programming for Absolute Beginners
name_cn: 绝对初学者的 Swift 游戏编程
slug: swift-game-programming-for-absolute-beginners
toc:
- - '#'
  - 引言
- - '##'
  - 本书读者对象
- - '##'
  - 本书结构
- - '###'
  - 第一部分
- - '###'
  - 第二部分
- - '###'
  - 第三部分
- - '###'
  - 第四部分
- - '###'
  - 第五部分
- - '##'
  - 工具
- - '##'
  - 示例游戏
- - '##'
  - 联系作者
- - '##'
  - 致谢
- - '#'
  - 目录
- - '##'
  - 内容概览
- - '###'
  - 第一部分：入门指南
- - '#'
  - 第一部分
- - '#'
  - 1. Swift 语言
- - '##'
  - 计算机与程序
- - '###'
  - 处理器与内存
- - '###'
  - 程序
- - '###'
  - 编程语言
- - '###'
  - 编程游戏
- - '###'
  - 开发游戏
- - '###'
  - 小规模：编写-编译-运行
- - '###'
  - 大规模：设计-规格-实现
- - '##'
  - 构建你的第一个 Swift 程序
- - '##'
  - 构建你的首个 Swift 游戏
- - '###'
  - 函数还是方法？
- - '##'
  - 几点观察
- - '###'
  - 本章所学
- - '#'
  - 2. 游戏编程基础
- - '##'
  - 游戏的构建模块
- - '###'
  - 游戏世界
- - '###'
  - 游戏循环
- - '###'
  - Swift 中的游戏循环
- - '##'
  - 程序的结构
- - '###'
  - 应用程序的类型
- - '###'
  - 函数
- - '###'
  - 语法图
- - '###'
  - 调用函数
- - '###'
  - 程序布局
- - '##'
  - 注释
- - '##'
  - 指令与行
- - '###'
  - 空格与缩进
- - '##'
  - 本章小结
- - '#'
  - 3. 创建游戏世界
- - '##'
  - 基本类型和变量
- - '###'
  - 类型
- - '###'
  - 变量的声明与赋值
- - '###'
  - 指令与表达式
- - '##'
  - 运算符与更复杂的表达式
- - '###'
  - 算术运算符
- - '###'
  - 运算符优先级
- - '##'
  - 其他数值类型
- - '###'
  - DiscoWorld 游戏
- - '##'
  - 变量的作用域
- - '##'
  - 你学到的内容
- - '#'
  - 4. 游戏资源
- - '##'
  - 定位精灵
- - '##'
  - 加载和绘制精灵
- - '##'
  - 分辨率和宽高比
- - '##'
  - 移动精灵
- - '###'
  - 加载与绘制多个精灵
- - '##'
  - 配置设备方向
- - '##'
  - 音乐与音效
- - '##'
  - 本章小结
- - '#'
  - 第二部分 画家
- - '#'
  - 5. 对玩家输入做出反应
- - '##'
  - 处理触摸输入
- - '###'
  - 利用触摸位置改变游戏世界
- - '##'
  - 基于触摸的条件执行
- - '###'
  - 判断备选情况
- - '###'
  - 比较运算符
- - '###'
  - 逻辑运算符
- - '###'
  - 布尔类型
- - '###'
  - 更改加农炮的颜色
- - '##'
  - 几句结束语
- - '##'
  - 本章所学内容
- - '#'
  - 6. 飞行的球
- - '##'
  - 方法
- - '##'
  - 参数名称与标签
- - '###'
  - 声明 vs 参数
- - '##'
  - 默认参数值
- - '##'
  - 将指令重组为方法
- - '##'
  - 在局部坐标与世界坐标之间移动
- - '##'
  - 向游戏世界添加一个球
- - '###'
  - 发射球
- - '####'
  - 更新球的位置
- - '####'
  - 固定时间步长 vs 可变时间步长
- - '###'
  - 变长时间步长 vs 固定时间步长
- - '##'
  - 更新球体颜色
- - '##'
  - 本章小结
- - '#'
  - 7. 游戏对象类型
- - '##'
  - 创建同一类型的多个对象
- - '##'
  - 类作为类型
- - '##'
  - 在独立类中进行输入处理
- - '###'
  - 初始化对象
- - '###'
  - Self 关键字
- - '###'
  - 使用静态变量访问其他对象
- - '###'
  - 类的双重角色
- - '##'
  - 编写拥有多个实例的类
- - '##'
  - 处理游戏中的随机性
- - '###'
  - 计算随机速度和颜色
- - '###'
  - 更新油漆罐
- - '##'
  - 本章所学内容
- - '#'
  - 8. 颜色与碰撞
- - '##'
  - 表示颜色的另一种方式
- - '##'
  - 对象的受控数据访问
- - '###'
  - 向类中添加计算属性
- - '##'
  - 处理球与罐子之间的碰撞
- - '##'
  - 结构体
- - '##'
  - 你学到的内容
- - '#'
  - 9. 有限的生命
- - '##'
  - 维护生命数量
- - '###'
  - 向玩家显示剩余生命数
- - '##'
  - 多次执行指令
- - '##'
  - 递增计数器的简写符号
- - '##'
  - 更紧凑的循环语法
- - '##'
  - 几个特殊情况
- - '###'
  - 完全不执行
- - '###'
  - 无限循环
- - '###'
  - 嵌套循环
- - '##'
  - 重新开始游戏
- - '##'
  - 本章小结
- - '#'
  - 10. 组织游戏对象
- - '##'
  - 游戏对象间的相似性
- - '##'
  - 继承
- - '##'
  - 游戏对象与继承
- - '###'
  - 作为 `ThreeColorGameObject` 子类的 Cannon
- - '###'
  - '`Ball` 类'
- - '###'
  - '`PaintCan` 类'
- - '##'
  - 多态性
- - '##'
  - 继承现有类
- - '###'
  - 类的层级结构
- - '##'
  - 本章所学内容
- - '#'
  - 11. 完成“画家”游戏
- - '##'
  - 添加运动效果
- - '###'
  - 创建精灵
- - '##'
  - 添加声音与音乐
- - '##'
  - 维护分数
- - '##'
  - 字符与字符串
- - '###'
  - 特殊字符
- - '##'
  - 添加应用图标
- - '##'
  - 最后几点补充
- - '##'
  - 本章所学内容
- - '#'
  - 第三部分
- - '##'
  - 图坦卡蒙之墓
- - '#'
  - 12. 高级输入处理
- - '##'
  - 创建触摸对象
- - '###'
  - 数组
- - '###'
  - 字典
- - '###'
  - 可选类型
- - '###'
  - 注意
- - '##'
  - 存储多点触摸
- - '##'
  - 让处理触摸输入更简单
- - '###'
  - 将触摸事件关联至输入辅助类
- - '##'
  - 拖动精灵
- - '##'
  - 本章所学内容
- - '#'
  - 13. 游戏物理
- - '##'
  - 游戏对象的基础类
- - '##'
  - 游戏对象子类
- - '##'
  - 为游戏对象添加物理属性
- - '###'
  - 交互
- - '##'
  - 本章所学
- - '#'
  - 14. 游戏玩法编程
- - '##'
  - 游戏对象行为
- - '###'
  - 动作
- - '###'
  - 使用动作实现宝物掉落
- - '###'
  - 特殊类型的宝藏
- - '###'
  - 将宝藏变成岩石
- - '##'
  - 处理物理接触
- - '##'
  - 本章所学内容
- - '#'
  - 15. 游戏状态
- - '##'
  - 更好的图层处理
- - '###'
  - 添加标题画面
- - '###'
  - 添加用于显示帮助框的按钮
- - '###'
  - 叠加层
- - '##'
  - 本章所学内容
- - '#'
  - 16. 完成《图坦卡蒙之墓》游戏
- - '##'
  - 添加分数
- - '##'
  - 控制访问
- - '##'
  - 使用自定义字体
- - '##'
  - 添加闪光效果
- - '##'
  - 添加更多闪光效果
- - '##'
  - 添加音乐与音效
- - '###'
  - 排行榜
- - '##'
  - 你学到了什么
- - '#'
  - 第四部分
- - '#'
  - 17. 菜单与网格
- - '##'
  - 网格布局中的游戏对象
- - '###'
  - 类扩展
- - '##'
  - 设置菜单
- - '##'
  - 添加开关按钮
- - '##'
  - 定义滑块按钮
- - '##'
  - 计算游戏对象的世界坐标位置
- - '###'
  - 完成滑块类
- - '##'
  - 本章所学内容
- - '#'
  - 18. 游戏状态管理
- - '##'
  - 游戏状态管理基础
- - '###'
  - 游戏状态管理器
- - '##'
  - 为节点分配名称
- - '##'
  - 添加状态并在状态间切换
- - '###'
  - 关卡菜单状态
- - '##'
  - 本章所学内容
- - '#'
  - 19. 存储和读取游戏数据
- - '##'
  - 关卡的结构
- - '##'
  - 从文件读取数据
- - '##'
  - Tile 类
- - '##'
  - 关卡状态
- - '###'
  - 使用 `switch` 处理多种选择
- - '###'
  - 加载不同类型的瓦片
- - '##'
  - 维护玩家游戏进度
- - '###'
  - 存档游戏的诅咒
- - '##'
  - 本章所学
- - '#'
  - 20. 游戏对象之间的交互
- - '##'
  - 定义运算符
- - '###'
  - 选择企鹅
- - '####'
  - 更新动物
- - '##'
  - 与其他游戏对象相遇
- - '##'
  - 维护配对数
- - '##'
  - 你学到了什么
- - '#'
  - 21. 完成企鹅配对游戏
- - '##'
  - 显示提示
- - '##'
  - 显示帮助框
- - '##'
  - 重置关卡
- - '###'
  - 进入下一关
- - '##'
  - 新手教程
- - '##'
  - 添加音效
- - '##'
  - 团队协作
- - '##'
  - 最后几点提示
- - '##'
  - 本章要点
- - '#'
  - 第五部分
- - '#'
  - 22. 主要游戏结构
- - '##'
  - 游戏结构概览
- - '##'
  - 关卡的结构
- - '###'
  - 水滴
- - '###'
  - 瓦片类
- - '###'
  - LevelState 类
- - '##'
  - 本章所学
- - '#'
  - 23. 动画
- - '##'
  - 什么是动画？
- - '###'
  - 游戏中的动画
- - '##'
  - 纹理图集
- - '###'
  - 动画类
- - '###'
  - 支持多个动画
- - '###'
  - 玩家类
- - '##'
  - 你学到了什么
- - '#'
  - 24. 平台游戏物理机制
- - '##'
  - 将角色锁定在游戏世界中
- - '##'
  - 将角色设置在正确位置
- - '##'
  - 跳跃……
- - '##'
  - ……和下坠
- - '##'
  - 碰撞检测
- - '###'
  - 获取边界框
- - '###'
  - 处理角色-瓦片碰撞
- - '###'
  - 处理碰撞
- - '##'
  - 本章所学内容
- - '#'
  - 25. 智能敌人
- - '##'
  - 火箭
- - '###'
  - 创建与重置火箭
- - '###'
  - 火箭行为编程
- - '##'
  - 巡逻敌人
- - '###'
  - 基本的 `PatrollingEnemy` 类
- - '###'
  - 不同类型的敌人
- - '##'
  - 其他类型的敌人
- - '###'
  - 敌人软件架构
- - '##'
  - 加载不同类型的敌人
- - '##'
  - 本章小结
- - '#'
  - 26. 添加玩家交互
- - '##'
  - 收集水滴
- - '###'
  - 冰块
- - '##'
  - 敌人与玩家碰撞
- - '##'
  - 添加水平和垂直滚动
- - '##'
  - 死亡与否？
- - '##'
  - 你学到了什么
- - '#'
  - 27. 完成嘀嗒嘀嗒游戏
- - '##'
  - 添加计时器
- - '###'
  - 让计时器变快或变慢
- - '###'
  - 适应玩家的技能水平
- - '###'
  - 当计时器归零
- - '###'
  - 制作游戏资源
- - '###'
  - 添加山脉和云朵
- - '##'
  - 显示帮助框架
- - '##'
  - 完成关卡进度
- - '##'
  - 销售你的游戏
- - '##'
  - 本章所学内容
