name: WinRT Revealed
name_cn: WinRT 揭秘
slug: winrt-revealed
toc:
- - '#'
  - 管理人类
- - '##'
  - 一位软件工程经理的辛辣幽默故事
- - '##'
  - 目录
- - '#'
  - 第一部分：管理箭袋
- - '#'
  - 第 1 章：别当刺头
- - '#'
  - 第 2 章：管理者并非邪恶
- - '#'
  - 第 3 章：邪恶确实存在
- - '#'
  - 第 4 章：组织自豪感、恐慌感与经理的角色
- - '##'
  - 你的经理的工作
- - '##'
  - 你的经理从哪里来？
- - '##'
  - 他如何弥补自己的盲区？
- - '##'
  - 你的经理会说那种语言吗？
- - '##'
  - 你的经理如何与你沟通？
- - '##'
  - 每项决策需要多少行动？
- - '#'
  - 第 5 章：授权的艺术
- - '##'
  - 你的管理者在政治食物链中处于什么位置？
- - '##'
  - 当他们失控时会怎样？
- - '#'
  - 第 6 章：终章
- - '#'
  - 第 7 章：兰兹测试
- - '##'
  - 兰兹测试：11 项评分要点
- - '###'
  - 你是否有规律的一对一会议，且谈论的是状态更新之外的话题？（+1 分）
- - '###'
  - 你是否有规律的团队会议？（+1 分）
- - '###'
  - 是否每周通过邮件发送手写状态报告？（-1 分）
- - '#'
  - 第 8 章：关于协作工具与工作沟通的思考
- - '##'
  - 你能坦然地对老板说“不”吗？（+1）
- - '##'
  - 你能向陌生人解释公司的战略吗？（+1）
- - '###'
  - 你能相当准确地告诉我公司的现状吗？（或者你现在能否找到某位相关人员，立刻搞清楚状况？）（+1 分）
- - '###'
  - 是否有一个定期会议，让负责人站在大家面前，告诉大家他/她在想什么？（+1 分）并且你相信他/她吗？（+1 分）
- - '###'
  - 你能说明自己的职业发展轨迹吗？（+1 分）加分项：你的老板能吗？（+1 分）
- - '###'
  - 你是否有明确界定并受到保护的时间来思考战略性问题？（+1 分）
- - '###'
  - 你是否在积极扼杀“小道消息”？（+1 分）
- - '#'
  - 第 9 章：幅度与方向
- - '#'
  - 第 10 章：矢量思维与 Rands 测试
- - '#'
  - 第 11 章：如何主持会议
- - '##'
  - 对齐会议 vs. 创意会议
- - '##'
  - 掌控全局
- - '##'
  - 即兴发挥
- - '##'
  - 会议文化
- - '#'
  - 第 12 章：直觉刺痛
- - '##'
  - 直觉刺痛的获得
- - '##'
  - 直觉：管理者的第六感
- - '##'
  - 直觉：建立在经验之上
- - '##'
  - 管理者的一天：充满故事
- - '###'
  - 一颗熟悉的钉子
- - '##'
  - 一次直觉灾难
- - '##'
  - 当这些看似无害的故事未经评判、未经质疑时，故事就结束了。
- - '##'
  - 又一颗钉子
- - '#'
  - 第 13 章：更新、吐槽和灾难
- - '##'
  - 基本原则
- - '##'
  - 你还好吗？
- - '###'
  - 更新
- - '##'
  - 微绩效评估
- - '##'
  - 我当前的灾难
- - '##'
  - 战略性的对话
- - '##'
  - 倾诉（The Vent）
- - '##'
  - 灾难（The Disaster）
- - '##'
  - 假设他们有东西可以教你
- - '#'
  - 第 14 章：周一恐慌症
- - '###'
  - 恐慌症
- - '####'
  - 不要加入恐慌
- - '####'
  - 相信恐慌者有其理由
- - '####'
  - 用问题敲打恐慌者
- - '####'
  - 让恐慌者解决他们自己的问题
- - '###'
  - 问题依然存在
- - '#'
  - 第 15 章：你的“怪人”炸毛了，这其实挺好的
- - '##'
  - 理解偏差
- - '##'
  - 华莱士恨我
- - '##'
  - “跌落神坛”不是教训
- - '#'
  - 第 16 章：坠落之感
- - '#'
  - 第 17 章：你的直觉百分之百错误
- - '#'
  - 第 18 章：教训的规模
- - '#'
  - 第 19 章：议程识别
- - '##'
  - '退出会议技巧 #1：识别会议类型'
- - '#'
  - 第 20 章：会议脱身术：高级议程识别
- - '##'
  - '会议脱身术技巧 #2：对参会者进行分类'
- - '##'
  - '会议脱身术技巧 #3：识别棋手'
- - '##'
  - '会议脱身术技巧 #4：识别支持方和反对方'
- - '##'
  - '会议脱身术技巧 #5：搞清楚议题'
- - '##'
  - '会议脱身术技巧 #6：给反对方他们想要的'
- - '##'
  - 所以没错，反对者确实想在这里得到些什么
- - '##'
  - '会议脱身技巧 #7：搞清楚问题所在'
- - '##'
  - 结论
- - '#'
  - 第 21 章：剖析指令
- - '##'
  - 决定
- - '##'
  - 传达
- - '##'
  - 交付阶段的目标
- - '##'
  - 再次交付
- - '##'
  - 外部指令
- - '#'
  - 第 22 章：信息饥渴
- - '##'
  - 信息管道
- - '###'
  - 自然厌恶真空
- - '#'
  - 第 23 章：管理信息流与团队沟通
- - '##'
  - 防止信息饥荒
- - '###'
  - '*“别担心，我会记得转达的。”*'
- - '###'
  - '*“我觉得没人需要知道那个。”*'
- - '###'
  - '*“我的员工能读懂我的心思。”*'
- - '##'
  - 积极的沉默
- - '##'
  - 微妙、诡计与沉默
- - '#'
  - 第 24 章：管理之道：微妙、巧计与沉默
- - '##'
  - 微妙
- - '##'
  - 巧计
- - '##'
  - 沉默
- - '#'
  - 第 25 章：商业不是战争
- - '##'
  - 管理语
- - '##'
  - 管理隐喻
- - '##'
  - 懒惰的语言
- - '##'
  - “底线”
- - '#'
  - 第 26 章：弗雷德讨厌外出会议
- - '##'
  - 我为何要与弗雷德针锋相对
- - '##'
  - 我们是谁，我们需要什么，以及我们的史诗旅程
- - '###'
  - 我们需要了解我们是谁
- - '###'
  - 我们需要新的方向和/或减少灾难
- - '###'
  - 我们即将开启一段史诗旅程
- - '###'
  - 一场具有特定特征的会议
- - '####'
  - 定义上，你无法邀请所有人
- - '####'
  - 每人都有展示，或至少发言
- - '##'
  - 它不在你平常的办公楼里
- - '##'
  - 有人负责掌控流程，也有人负责记录行动
- - '##'
  - 没有性格测试，没有信任背摔，也没有外部人员
- - '##'
  - 他们需要花时间消化一下
- - '##'
  - 我希望每个人都拥有这样一个时刻，作为团队外出会议的一部分，我称之为“亮点转折点”。
- - '##'
  - 弗雷德真正讨厌的是什么
- - '#'
  - 第 15 章：另一种 DNA
- - '##'
  - 没有盛大的庆祝游行
- - '##'
  - 五种胜利
- - '##'
  - DNA 会议
- - '##'
  - 扁平是一种心态
- - '#'
  - 第 16 章：工程师思维
- - '##'
  - 不要停止开发
- - '#'
  - 第 17 章：三种超能力
- - '##'
  - 机器人的辩论
- - '##'
  - 绝地大师的微调
- - '###'
  - '*绝地大师*拥有神奇的待人技巧'
- - '##'
  - 可能需要采取严厉措施，所以……
- - '###'
  - '*独裁者*拥有“指令”'
- - '##'
  - 我最喜欢的超能力
- - '#'
  - 第 18 章：学会说“不”
- - '#'
  - 第 19 章：管理者失控
- - '##'
  - 失控
- - '##'
  - 恢复控制
- - '##'
  - 永远别信小精灵
- - '##'
  - 然后，你将做出一个重大而艰难的决定，并会想起：“能力越大，责任越大。” 作为管理者，你负责做出伟大的决策，而实现这一目标的最佳方式，就是尽可能让整个团队参与到每一个决策中。
- - '#'
  - 第二部分 过程即产物
- - '#'
  - 第 20 章：1.0 版本
- - '##'
  - 理解 1.0
- - '##'
  - Rands 的 1.0 层级图
- - '###'
  - 构思
- - '###'
  - 人员
- - '###'
  - 流程
- - '###'
  - 产品
- - '##'
  - 使用金字塔
- - '##'
  - 构建文化
- - '#'
  - 第 21 章：如何开始
- - '###'
  - 对开始的批判性分析
- - '##'
  - 准备工作，尽管形式多样，却常常背负坏名声。
- - '##'
  - 早晨的舒展
- - '##'
  - 经验丰富的夜晚
- - '##'
  - 机缘巧合
- - '#'
  - 第 22 章：花时间思考
- - '##'
  - 反应 vs. 思考
- - '##'
  - 如何开始
- - '##'
  - 参与者
- - '##'
  - 邀请谁？
- - '##'
  - 内容
- - '##'
  - 有效吗？
- - '##'
  - 何时停止
- - '##'
  - 对抗停滞
- - '##'
  - 我不知道你具体从事什么工作，也不知道你在构建什么。但我可以肯定的是，如果你在构建的东西中未能展现创造性思维，那你就麻烦了，因为你和你的团队以及产品都将停滞不前。启动头脑风暴会议是一件棘手的事。这些会议定义模糊、难以组织，更难以衡量成效。会议产出的结果可能是天才创意，也可能是愚蠢想法……两者之间的差别微乎其微。祝你好运。
- - '#'
  - 第 23 章：浸泡的价值
- - '##'
  - 情绪与无知
- - '##'
  - 主动浸泡
- - '##'
  - 被动浸泡
- - '###'
  - 沉浸需要时间
- - '#'
  - 第 24 章：管理马尔科姆事件
- - '###'
  - 我们总是很匆忙
- - '###'
  - 理解马尔科姆事件
- - '###'
  - 文档制品
- - '###'
  - 活页夹
- - '###'
  - 成功往往是静默的
- - '#'
  - 第 25 章：捕捉上下文
- - '##'
  - 那么，然后呢？
- - '##'
  - 书呆子自白
- - '#'
  - 第 26 章：涓滴理论
- - '##'
  - 我们的反派
- - '##'
  - 不开始，什么都做不成
- - '##'
  - 迭代
- - '##'
  - 混合着来
- - '##'
  - 熵增永远会赢
- - '#'
  - 第 27 章：天塌下来的时候
- - '##'
  - 第一步：作战室里的局势
- - '###'
  - 如果你忽略这一步会发生什么
- - '##'
  - 许多聪明人会跳过的一个令人惊讶的步骤
- - '##'
  - 第二步：“押上你的车”视角
- - '###'
  - 你必须做的第一件事
- - '###'
  - 你必须做的第二件事
- - '##'
  - 如果你忽略这一步会怎样
- - '##'
  - 第三步：持续稳定的撑天压力
- - '##'
  - 如果你忽略这一步会怎样
- - '##'
  - 难以捉摸的第零步
- - '#'
  - 第 28 章：黑客精神很重要
- - '###'
  - “黑客相信一切都可以变得更好”
- - '##'
  - Facebook 的公开信与黑客精神的重要性
- - '##'
  - 迪特尔去哪了？
- - '##'
  - 无意间忘却了初心
- - '#'
  - 第三部分：不同的你
- - '#'
  - 第 29 章：人闲则走
- - '##'
  - 如何发现无聊
- - '##'
  - 发现并应对团队中的倦怠情绪
- - '##'
  - 应对倦怠的行动计划
- - '###'
  - 让他们始终面对有趣的问题
- - '###'
  - 让他们去尝试
- - '###'
  - 记住，他们为团队牺牲的时间是有限的
- - '###'
  - 保护他们的时间
- - '###'
  - 积极消除干扰
- - '##'
  - 告诉他们到底发生了什么
- - '##'
  - 不要忘记构建东西是什么感觉
- - '#'
  - 第 30 章：领头羊
- - '###'
  - 核心面试团队
- - '####'
  - 技术
- - '####'
  - 文化
- - '####'
  - 愿景（战略还是战术？）
- - '##'
  - 战略型人才 vs. 战术型人才
- - '##'
  - 团队共识
- - '###'
  - 该傻的时候就得傻
- - '###'
  - 仍然自欺欺人
- - '#'
  - 第 31 章：九十天面试
- - '###'
  - 从容不迫
- - '##'
  - 新工作的前 90 天
- - '###'
  - 1. 晚走，早到
- - '###'
  - 2. 接受你收到的所有午餐邀请
- - '###'
  - 3. 总是询问缩略语
- - '###'
  - 4. 说一些非常愚蠢的话
- - '###'
  - 5. 喝一杯
- - '###'
  - 6. 告诉某人该做什么
- - '###'
  - 7. 进行一场争论
- - '###'
  - 8. 找到你的核心圈子
- - '##'
  - 完成面试
- - '#'
  - 第 32 章：管理技术怪才
- - '###'
  - 一个最坏的情况
- - '##'
  - 数代极客
- - '##'
  - 问题
- - '##'
  - 追求两种巅峰体验
- - '###'
  - 第一种巅峰体验：当极客看到死结，他们就想解开它。
- - '###'
  - 第二种巅峰体验：完全掌控错综复杂。
- - '##'
  - 1. 极客们近乎永恒的追求，便是管理所有那些阻碍他们进入“心流状态”以追寻“高峰体验”的破事儿。会议、毫无意义的闲谈、生理上的不适、空调启动时天花板传来的神秘敲击声——极客在进入状态的头
    15 分钟里所做的一切，都是在构建专注力，这就像搭建一个叠叠乐积木塔，任何微小的干扰都能将其摧毁。
- - '##'
  - 2. 你允许极客停留在心流状态的每一秒钟，都有一秒可能发生他妈的神奇之事。
- - '##'
  - 3. 正如《洞穴中的极客》第 33 章中所解释的，你的极客为自己建造了一个洞穴。它看起来可能不像个洞穴，也可能像。建造它的目标很简单：保护心流状态，这样我们才能追逐高峰体验。现在就站起来，走到你每一位极客的办公室，去探索一下这些洞穴。问这个问题：“他们是如何保护自己的专注力的？”背对着门？戴上耳机？使用大尺寸屏幕？要理解你的极客如何保护他的洞穴，你需要问……
- - '##'
  - 极客的负担
- - '#'
  - 第 33 章：注意缺陷多动障碍（NADD）
- - '##'
  - 《枪炮》是本好书
- - '##'
  - 书呆子的诊断
- - '##'
  - 上下文切换
- - '##'
  - 利用 NADD
- - '##'
  - 负面影响
- - '##'
  - 首先，要找到自己消化外界信息的个人节奏，本就是一件大费周章的事，而且很抱歉，你总会错过一些东西。这会让你心烦，但也会不断驱使你去寻找 *下一件大事*。
- - '#'
  - 第 34 章：洞穴中的技术怪才
- - '###'
  - 洞穴
- - '###'
  - 心流状态
- - '##'
  - 是的。当你成功进入心流状态时，我有时可能会变成一个混蛋。事实上，我可能会发飙。
- - '##'
  - 发飙
- - '##'
  - 工作场
- - '##'
  - 其他场所
- - '#'
  - 第 35 章：会议生物
- - '###'
  - 话事人
- - '###'
  - 笔记本赖瑞
- - '##'
  - 会议中的角色类型
- - '###'
  - 无关先生
- - '###'
  - 话匣子帕蒂
- - '###'
  - 翻译官蒂姆
- - '###'
  - 总结者莎莉
- - '###'
  - 曲线球库尔特
- - '###'
  - 蛇
- - '##'
  - 会议开始四十五分钟后，我做了一件前所未有的事。我径直走出了一场自己作为关键人物的会议，因为我实在无法再在这毫无意义的事情上浪费时间。起身、离场、摔门而去。是的，这是一次情绪化的举动，在商业场合几乎总是下策，但在我最厌恶的职业行为清单上，排在前列的绝对是：
- - '#'
  - 第 36 章：渐进主义者与完美主义者
- - '##'
  - 中间地带
- - '###'
  - 渐进主义者需要愿景
- - '###'
  - 完美主义者需要行动
- - '##'
  - 两种不同的咖啡因依赖
- - '##'
  - 现在你明白了吗？
- - '##'
  - 这个谜题其实很简单。
- - '#'
  - 第 37 章：有机型与机械型
- - '##'
  - 痒痒视角
- - '##'
  - 如果你为有机型经理工作……
- - '##'
  - 如果你为机械型经理工作……
- - '##'
  - 小心留意……
- - '##'
  - 答案在中间
- - '#'
  - 第 38 章：内向型、外向型与整体型
- - '##'
  - 视野层级
- - '###'
  - 内向型 (Inwards)
- - '###'
  - 外向型 (Outwards)
- - '###'
  - 全局型 (Holistics)
- - '##'
  - 等等，这些全局型管理者难道不用交付产品吗？
- - '##'
  - 角色混淆
- - '##'
  - 关注成长
- - '#'
  - 第 39 章：自由电子
- - '###'
  - 引言
- - '###'
  - 自由电子
- - '###'
  - 养护与激励
- - '###'
  - 回到 Jerry
- - '#'
  - 第 40 章：重组规则
- - '#'
  - 第 41 章：意想不到的联系
- - '##'
  - 两个分类
- - '##'
  - 相关性的价值
- - '##'
  - 换言之
- - '##'
  - 连接相关事物
- - '#'
  - 第 42 章：避免成为菲兹
- - '##'
  - 了解你的位置
- - '##'
  - 成长之道：避免成为“菲斯”
- - '##'
  - 年度评估，简而言之
- - '##'
  - 他们真正在想什么
- - '##'
  - 首先，整理你的想法，但先别思考
- - '##'
  - 技能与意愿加上顿悟
- - '##'
  - 最坏情况
- - '##'
  - 关于“Fez”的管理思考
- - '##'
  - 主张，简而言之
- - '##'
  - 大结局
- - '#'
  - 第 43 章：惊鸿一瞥与引子
- - '##'
  - 第一遍
- - '##'
  - 工作经历与职业轨迹
- - '##'
  - 其他兴趣与课外活动
- - '##'
  - 职业目标
- - '##'
  - 技能
- - '##'
  - 资质总结
- - '##'
  - 第二轮筛选
- - '###'
  - 深入分析工作经历
- - '###'
  - 教育背景
- - '##'
  - 与众不同，而非惹人厌烦
- - '###'
  - 将简历设计为“降级兼容”
- - '###'
  - 永远不要附上求职信
- - '###'
  - 拥抱诚实的“关键词合规”
- - '##'
  - 与众不同，而非恼人
- - '##'
  - 像人一样说话
- - '##'
  - 包含看似不相关的经历
- - '#'
  - 第 44 章：搞定电话筛选
- - '##'
  - 目的
- - '##'
  - 你的任务是做好准备
- - '##'
  - 回到开头
- - '##'
  - 结尾
- - '#'
  - 第 45 章：你的离职清单
- - '###'
  - 规则#1：不要承诺你做不到的事
- - '##'
  - 辞职的七个规则
- - '###'
  - '规则 #2：尊重你的人脉'
- - '###'
  - '规则 #3：更新“核心团队”'
- - '###'
  - '规则 #4：不要进行廉价攻击'
- - '###'
  - '规则 #5：善待为你工作和与你共事的人'
- - '###'
  - '规则 #6：不要自愿在离职后继续工作（或者，如果你要做，确保得到一大笔钱）'
- - '###'
  - '规则 #7：不要给太多通知时间'
- - '##'
  - 他们知道
- - '#'
  - 术语表
- - '#'
  - 索引
- - '###'
  - A
- - '###'
  - B
- - '###'
  - C
- - '###'
  - D
- - '###'
  - E
- - '###'
  - F
- - '###'
  - G
- - '###'
  - H
- - '###'
  - I
- - '##'
  - 会议
- - '###'
  - 会议小贴士
- - '###'
  - N
- - '###'
  - O
- - '###'
  - P
- - '###'
  - Q
- - '###'
  - R
- - '##'
  - 关于作者
- - '##'
  - 致谢
- - '##'
  - 第二版序言
