name: Pro iOS 5 Tools
name_cn: iOS 5 工具高级指南
slug: pro-ios-5-tools
toc:
- - '#'
  - 目录
- - '##'
  - 内容速览
- - '##'
  - 关于作者
- - '##'
  - 关于技术审校
- - '##'
  - 简介
- - '###'
  - 为什么要写一本关于工具的书？
- - '###'
  - 本书的组织结构
- - '###'
  - 支持与贡献
- - '##'
  - 第 1 章 蜡上蜡，蜡下蜡
- - '###'
  - 本书面向哪些读者？
- - '###'
  - 本书是什么
- - '###'
  - 开始前的准备工作
- - '###'
  - 本书内容概览
- - '###'
  - 让我们开始吧
- - '##'
  - 第 2 章 一流工具
- - '###'
  - 环顾四周
- - '####'
  - 这么多窗格！
- - '###'
  - 编辑器及配套的实用工具
- - '###'
  - 跳转栏
- - '###'
  - 管理器
- - '####'
  - 标签页，标签页，更多的标签页
- - '###'
  - 回到代码
- - '####'
  - 更新核心数据模型
- - '###'
  - 添加一个新的视图控制器
- - '###'
  - 回顾我们目前的进展
- - '###'
  - Instruments 时间
- - '####'
  - 进入“ Instruments ”工具
- - '####'
  - 众多的 Instruments 工具
- - '###'
  - 性能调优
- - '###'
  - 本章小结
- - '##'
  - 第 3 章 三个屏幕……嗯，它能跑起来
- - '###'
  - 使用 GitHub
- - '###'
  - 连接到 Super Checkout
- - '###'
  - 四处看看
- - '###'
  - 运行超级结账应用
- - '###'
  - 项目导航（与 Xcode）
- - '###'
  - 本章小结
- - '##'
  - 第 4 章 内存管理与诊断
- - '###'
  - 分支是我们的好帮手
- - '###'
  - 自动引用计数
- - '###'
  - 转换为 ARC
- - '###'
  - 识别保留循环
- - '###'
  - 回到手动引用计数
- - '###'
  - 建立健康的编码实践
- - '####'
  - 保留还是释放，这是个问题
- - '####'
  - 连接属性与多态点语法
- - '###'
  - 执行静态分析
- - '###'
  - 排版后内容
- - '###'
  - 僵尸——不，不是那种僵尸
- - '####'
  - 其他线程中的僵尸对象（大致如此）
- - '####'
  - 泄露（Leaks）
- - '###'
  - 扩展详细窗格
- - '###'
  - 重新审视保留循环
- - '###'
  - GDB 功夫
- - '####'
  - GDB，现在别让我失望
- - '#####'
  - GDB 入门指南
- - '#####'
  - 确定上下文——我在哪里？
- - '#####'
  - 检查数据——我有什么？
- - '#####'
  - 分手并不难
- - '#####'
  - 融会贯通
- - '#####'
  - 修复我们的 Bug
- - '####'
  - 当所有方法都失败时
- - '#####'
  - 海森堡虫
- - '#####'
  - 求助同事
- - '#####'
  - 推倒重来
- - '###'
  - 我们快完成了……几乎
- - '###'
  - 总结
- - '##'
  - 第 5 章 核心动画与平滑滚动
- - '###'
  - 利用主线程
- - '####'
  - 探索事件循环
- - '####'
  - 优化代码执行
- - '#####'
  - 小插曲——关于目标（Targets）的一切
- - '#####'
  - 回到性能分析
- - '###'
  - 改进产品屏幕
- - '###'
  - 探究滚动视图的幕后机制
- - '###'
  - 图片懒加载
- - '###'
  - 告别卡顿滚动
- - '####'
  - Core Graphics 简介
- - '####'
  - 回到 Instruments
- - '###'
  - 优化单元格绘制以使用单层绘制
- - '###'
  - 向苹果学习
- - '###'
  - 本章小结
- - '##'
  - 第 6 章 网络、缓存与电源管理
- - '###'
  - 理解网络与缓存控制
- - '####'
  - 探索客户端 API
- - '###'
  - 深入解析 Super Checkout 的 API 引擎设计
- - '####'
  - 设置 `ASIHTTPRequest`
- - '####'
  - 在超级结账中实现 ASI
- - '###'
  - 探索服务器 API
- - '###'
  - 为消费而设计
- - '###'
  - 使用调试工具
- - '####'
  - 使用网络链路调节器模拟慢速网络
- - '####'
  - 控制缓存
- - '#####'
  - 开始之前
- - '#####'
  - 决定缓存什么
- - '####'
  - NSCache
- - '###'
  - 排版后内容
- - '###'
  - 实现我们的磁盘缓存方案
- - '###'
  - 认识电源管理
- - '####'
  - 硬件部分
- - '####'
  - 编码技巧
- - '#####'
  - 网络通信
- - '###'
  - 追踪用电量
- - '###'
  - 运用行业技巧
- - '###'
  - 总结
- - '##'
  - 第 7 章 准备 Beta 版本！
- - '###'
  - 管理 Beta 测试
- - '####'
  - 定义 Beta 版本
- - '####'
  - 获取 Beta 测试者
- - '####'
  - 向测试者提供说明
- - '####'
  - 创建 Ad Hoc 构建
- - '#####'
  - 证书、配置文件与分发，天哪！
- - '######'
  - 创建证书签名请求
- - '#####'
  - 创建 iOS 发布证书
- - '#####'
  - 上传 UDID
- - '######'
  - 单个添加
- - '######'
  - 批量添加
- - '#####'
  - 确认
- - '#####'
  - 创建我们的应用程序 ID
- - '#####'
  - 临时分发配置描述文件
- - '#####'
  - 构建 Beta 版本
- - '#####'
  - 分发 Beta 版本
- - '####'
  - Alpha、Beta 还是 Gamma？
- - '###'
  - 本章小结
- - '##'
  - 第八章 为什么出问题了？
- - '###'
  - 测试驱动开发
- - '###'
  - 我应该何时开始测试？
- - '###'
  - Xcode 让测试变得简单
- - '####'
  - 测试目标
- - '####'
  - 设置测试
- - '#####'
  - 认识 `OCUnit`
- - '#####'
  - 有 Bug 的代码
- - '####'
  - 编写测试
- - '####'
  - 运行测试
- - '####'
  - 完善测试用例
- - '###'
  - 在你的应用中付诸实践
- - '####'
  - 测试 `SCJSONParser`
- - '####'
  - 模拟对象
- - '###'
  - 负面测试
- - '###'
  - 负面测试与有用的失败信息
- - '###'
  - UI 测试与自动化仪器
- - '###'
  - 开始使用
- - '###'
  - 编写用户界面测试脚本
- - '###'
  - 引入一个 Bug
- - '###'
  - 自动化的力量
- - '###'
  - 无论如何都要测试
- - '##'
  - 第 9 章 我们能自动化部分内容吗？
- - '###'
  - 持续集成
- - '####'
  - 认识 Jenkins
- - '####'
  - 让 Jenkins 启动并运行
- - '####'
  - Jenkins 界面
- - '###'
  - 驱逐 Jenkins 的守护进程
- - '###'
  - 获取一个任务
- - '###'
  - 'Jenkins Job: 配置与执行'
- - '####'
  - 配置源码检出
- - '####'
  - 理解任务详情页
- - '####'
  - 配置构建触发器
- - '####'
  - 脚本化 Xcode
- - '###'
  - 谁破坏了构建？
- - '###'
  - 质量可控
- - '####'
  - 使分发更简单
- - '####'
  - 你在何方，`PackageApplication`？
- - '####'
  - '`xcrun`'
- - '####'
  - 直接归档吧
- - '####'
  - 导出到 Jenkins 之外
- - '####'
  - 这些事不能交给别人处理吗？
- - '####'
  - 创建每日构建
- - '###'
  - 让构建流程面向未来
- - '###'
  - 我们还能做什么？
- - '##'
  - 第 10 章 现在，他们想要一个 iPad 版本
- - '###'
  - 在我们开始编码之前
- - '###'
  - 为 iPad 进行设计
- - '###'
  - 实现 iPad 版本
- - '####'
  - 修改目标
- - '#####'
  - 应用委托与启动界面
- - '#####'
  - 更新库存和产品详情
- - '####'
  - 重构库存列表
- - '####'
  - 更新产品详情
- - '####'
  - 为 iPad 版本创建产品详情 Nib
- - '####'
  - 修改购物车视图控制器
- - '###'
  - 收尾工作
- - '###'
  - 总结
- - '##'
  - 第 11 章 我该如何分享这些内容？
- - '###'
  - 将代码拆分为静态库
- - '####'
  - 创建静态库
- - '###'
  - 使用静态库
- - '###'
  - 将静态库作为子项目使用
- - '###'
  - 技术文档排版
- - '###'
  - 使用工作区
- - '###'
  - 在 GitHub 上共享
- - '####'
  - 登录 GitHub
- - '####'
  - 创建一个共享仓库
- - '####'
  - 提交我们的更改
- - '####'
  - 使用 GitHub 功能
- - '#####'
  - 标签
- - '#####'
  - 拉取请求
- - '#####'
  - 问题跟踪
- - '###'
  - 明智地选择许可证
- - '###'
  - 本章小结
- - '##'
  - 第 12 章 最后一件事
- - '###'
  - 自定义 Xcode
- - '####'
  - 行为
- - '####'
  - 字体与颜色
- - '####'
  - 文本编辑
- - '####'
  - 键绑定
- - '####'
  - 下载
- - '####'
  - 文档
- - '####'
  - 位置
- - '#####'
  - 源码树
- - '####'
  - 分布式构建
- - '###'
  - 键盘快捷键及其他
- - '####'
  - 从 Xcode 3 迁移到 Xcode 4
- - '####'
  - 快给我快捷键！
- - '###'
  - 查看文档
- - '###'
  - 总结
- - '##'
  - 索引
- - '###'
  - A
- - '###'
  - B
- - '###'
  - C
- - '###'
  - D
- - '###'
  - E
- - '###'
  - F
- - '###'
  - G
- - '###'
  - H
- - '###'
  - I
- - '####'
  - iPad
- - '#####'
  - 产品详情
- - '###'
  - J. K
- - '####'
  - Jenkins
- - '#####'
  - 界面
- - '###'
  - L
- - '###'
  - M
- - '####'
  - 内存管理
- - '#####'
  - 编码实践
- - '#####'
  - GDB
- - '#####'
  - 内存泄漏
- - '#####'
  - NSZombie 检测
- - '###'
  - N
- - '####'
  - 网络与缓存控制
- - '#####'
  - 客户端 API
- - '#####'
  - NSCache
- - '#####'
  - 服务端 API
- - '###'
  - O
- - '###'
  - P, Q, R
- - '###'
  - S
- - '###'
  - T
- - '###'
  - U, V
- - '###'
  - X, Y, Z
