name: Developing C# apps for iPhone and iPad using MonoTouch
name_cn: "\u4F7F\u7528 MonoTouch \u5F00\u53D1 iPhone \u548C iPad \u7684 C# \u5E94\u7528\
  \u7A0B\u5E8F"
slug: developing-c-apps-for-iphone-and-ipad-using-monotouch
