name: Android Espresso Revealed
name_cn: Android Espresso 揭秘指南
slug: android-espresso-revealed
toc:
- - '#'
  - 引言
- - '##'
  - 本书读者对象
- - '##'
  - 本书涵盖内容
- - '##'
  - 源代码与示例项目
- - '##'
  - 章节概述
- - '###'
  - 第 1 章：Espresso for Android 入门
- - '###'
  - 第 2 章：按需定制 Espresso
- - '###'
  - 第 3 章：使用 Kotlin 编写 Espresso 测试
- - '###'
  - 第 4 章：处理网络操作和异步操作
- - '###'
  - 第 5 章：使用 IntentMatchers 验证和存根 Intent
- - '###'
  - 第 6 章：测试 WebView
- - '###'
  - 第 7 章：无障碍测试
- - '###'
  - 第 8 章：Espresso 与 UI Automator：完美搭档
- - '###'
  - 第 9 章：处理运行时系统操作和权限
- - '###'
  - 第 10 章：Android 测试自动化工具
- - '###'
  - 第 11 章：Android UI 测试中的屏幕对象设计模式
- - '###'
  - 第 12 章：使用 Espresso 和 Kotlin 测试机器人模式
- - '##'
  - 第 13 章：使用 Espresso 和 UI Automator 进行有监督的 Monkey 测试
- - '##'
  - 第 14 章：AndroidX Test 库
- - '##'
  - 第 15 章：提高生产力与测试非常规组件
- - '##'
  - 本书未涵盖的内容
- - '##'
  - 工具要求
- - '##'
  - 法律声明
- - '###'
  - 关于作者与技术审校
- - '###'
  - 关于作者
- - '###'
  - 关于技术审校
- - '#'
  - 第 1 章：Espresso for Android 入门指南
- - '##'
  - 用户界面测试：目标与方法
- - '##'
  - 搭建示例项目
- - '##'
  - 理解 Android 插桩测试
- - '##'
  - Espresso 基础知识
- - '###'
  - 识别应用 UI 元素
- - '###'
  - 练习 1：检查应用布局
- - '##'
  - Espresso
- - '##'
  - Espresso 视图匹配器
- - '##'
  - Espresso 的 `ViewInteraction` 类
- - '##'
  - Espresso 的 `ViewActions` 类
- - '###'
  - 图 1-12
- - '###'
  - 图 1-13
- - '###'
  - 图 1-14
- - '##'
  - 练习 3 — 编写一个操作 `ListView` 的测试用例
- - '##'
  - 使用 Espresso 操控 RecyclerView
- - '###'
  - '`RecyclerViewActions`'
- - '###'
  - 练习 4
- - '##'
  - 从 AndroidStudio 运行 Espresso 测试
- - '###'
  - 从终端运行 Espresso 测试
- - '####'
  - 使用 Shell 命令运行 Instrumentation 测试
- - '####'
  - 使用 Gradle 命令运行 Instrumentation 测试
- - '###'
  - 练习 5
- - '##'
  - 总结
- - '#'
  - 第 2 章：为我们的需求定制 Espresso
- - '##'
  - 编写自定义 ViewAction
- - '##'
  - 适配 Espresso 滑动操作
- - '##'
  - 练习 6
- - '##'
  - 创建自定义 RecyclerView 操作
- - '##'
  - 练习 7
- - '##'
  - 编写自定义匹配器
- - '###'
  - 为简单 UI 元素创建自定义匹配器
- - '###'
  - 实现自定义 RecyclerView 匹配器
- - '##'
  - 使用自定义 FailureHandler 处理错误
- - '##'
  - 练习 8
- - '##'
  - 测试失败时截取并保存屏幕截图
- - '##'
  - 练习 9
- - '##'
  - 总结
- - '#'
  - 第 3 章：使用 Kotlin 编写 Espresso 测试
- - '##'
  - 将 Espresso Java 测试迁移到 Kotlin
- - '##'
  - 练习 10
- - '##'
  - 将 Java 代码转换为 Kotlin
- - '##'
  - 用 Kotlin 编写测试的好处
- - '###'
  - 函数作为类型
- - '###'
  - 扩展函数
- - '###'
  - 字符串模板
- - '###'
  - 导入 `R.class` 资源
- - '##'
  - Kotlin 中的 Espresso 领域特定语言
- - '#'
  - 第 4 章：处理网络操作和异步操作
- - '##'
  - Espresso 框架中的同步机制
- - '##'
  - IdlingResource 基础
- - '##'
  - 编写代码
- - '##'
  - 运行第一个测试
- - '##'
  - '`OkHttp3IdlingResource`'
- - '##'
  - '`PicassoIdlingResource`'
- - '##'
  - 作为 `IdlingResource` 替代方案的 `ConditionWatcher`
- - '##'
  - 练习 12
- - '##'
  - 将条件监视器集成到 Espresso Kotlin DSL 中
- - '##'
  - 练习 13
- - '##'
  - 总结
- - '#'
  - 第 5 章：使用 IntentMatchers 验证和存根 Intent
- - '##'
  - 设置依赖项
- - '##'
  - 桩化活动意图(Stubbing Activity Intents)
- - '##'
  - 桩化无返回结果的意图
- - '##'
  - 匹配器说明
- - '##'
  - 为单个 Intent 设置桩
- - '##'
  - 练习 14
- - '##'
  - 使用结果存根化 Intent
- - '###'
  - 在 `AddEditTaskFragment.java` 中启动和处理图像 Intent
- - '###'
  - 在 `StubSelectImageIntentTest.kt` 类中实现的测试方法
- - '###'
  - '`IntentHelper.kt` 对象，提供用于生成 Intent 存根化中使用的 Activity 结果的方法'
- - '##'
  - 练习 15
- - '##'
  - 验证 Intent
- - '##'
  - 练习 16
- - '##'
  - 总结
- - '#'
  - 第 6 章：测试 WebView
- - '##'
  - 支持的联系表单
- - '##'
  - Espresso-Web 基础
- - '###'
  - Espresso-Web API 使用公式
- - '###'
  - Android 支持库中的 Espresso-Web 依赖
- - '###'
  - AndroidX 测试库中的 Espresso-Web 依赖
- - '##'
  - Espresso-Web 构建块
- - '###'
  - Web 交互
- - '###'
  - Driver atoms
- - '###'
  - Web 断言
- - '##'
  - 练习 17：验证 Intent
- - '##'
  - 使用 Espresso-Web 编写测试
- - '###'
  - 练习 18
- - '##'
  - 总结
- - '#'
  - 第 7 章：无障碍测试
- - '##'
  - Android 无障碍工具
- - '##'
  - 测试应用无障碍
- - '###'
  - 图 7-3：创建任务视图中的无障碍问题
- - '##'
  - 练习 19：执行无障碍测试
- - '##'
  - 总结
- - '#'
  - 第 8 章：Espresso 与 UI Automator：完美组合
- - '##'
  - UI Automator 的主要特性
- - '##'
  - 开始使用 UI Automator
- - '##'
  - 查找并操作 UI 元素
- - '##'
  - 等待 UI 元素
- - '##'
  - 监视条件
- - '##'
  - 在测试中结合使用 Espresso 与 UI Automator
- - '##'
  - 练习 20
- - '##'
  - 总结
- - '#'
  - 第 9 章：处理运行时系统操作与权限
- - '##'
  - 以编程方式更改模拟器系统语言
- - '###'
  - 保存和加载模拟器快照的示例脚本
- - '###'
  - 建立模拟器 Telnet 连接并加载模拟器快照的 Python 脚本
- - '###'
  - 建立模拟器 Telnet 连接并加载模拟器快照的 Expect 工具脚本
- - '##'
  - 练习 21
- - '##'
  - 处理运行时权限
- - '###'
  - 使用 GrantPermissionRule 启用权限
- - '####'
  - chapter9. RuntimePermissionsTest.kt
- - '###'
  - 使用 UI Automator 处理运行时权限
- - '##'
  - 练习 22：使用运行时权限
- - '####'
  - 1. 删除 `GrantPermissionRule`
- - '####'
  - 2. 运行 `RuntimePermissionsUiAutomatorTest.kt` 类中实现的所有测试
- - '####'
  - 3. 编写一个测试
- - '##'
  - 总结
- - '#'
  - 第 10 章：Android 测试自动化工具
- - '##'
  - 为测试自动化设置虚拟或物理设备
- - '###'
  - 系统动画
- - '###'
  - 触摸和长按延迟
- - '###'
  - 虚拟键盘显示
- - '##'
  - 练习 23
- - '##'
  - 使用 Espresso 测试录制器工具
- - '##'
  - 练习 24
- - '##'
  - 从 Android Studio 在 Firebase Test Lab 中运行 Espresso 测试
- - '##'
  - 练习 25
- - '#'
  - 第 11 章：Android UI 测试中的屏幕对象设计模式
- - '##'
  - 屏幕对象设计模式在 Android 测试项目中的优缺点
- - '###'
  - 优点
- - '####'
  - 逻辑测试步骤分离
- - '####'
  - 更易读的测试
- - '####'
  - 易于构建的用户流程
- - '####'
  - 易于维护的测试
- - '####'
  - 代码复用
- - '###'
  - 缺点
- - '####'
  - 处理跨屏幕的视图
- - '####'
  - 相同操作打开不同屏幕
- - '####'
  - 过于细化的屏幕方法会导致冗长的测试
- - '##'
  - 应用屏幕对象设计模式
- - '##'
  - 练习 26
- - '#'
  - 第 12 章：使用 Espresso 和 Kotlin 测试机器人模式
- - '##'
  - 分离“做什么”与“怎么做”
- - '#'
  - 第 13 章：使用 Espresso 和 UI Automator 进行监督式猴子测试
- - '##'
  - 检测和第三方应用的 Monkey 测试
- - '###'
  - 识别 Monkey 测试的操作区域
- - '###'
  - 定义 Monkey 测试动作
- - '###'
  - 实现依赖于包的功能
- - '###'
  - 运行 Monkey 测试
- - '##'
  - 练习 28
- - '##'
  - 小结
- - '#'
  - 第 14 章：AndroidX 测试库
- - '##'
  - AndroidX 测试与测试支持库的对比
- - '##'
  - 为 AndroidX 测试配置项目
- - '##'
  - 迁移至 AndroidX
- - '##'
  - UI 测试中的 ActivityScenario
- - '##'
  - 在 UI 测试中使用 Truth 断言库
- - '###'
  - 表 14-1 基本 JUnit 和 Truth 断言对比
- - '##'
  - 练习 29
- - '##'
  - 总结
- - '#'
  - 第 15 章：提升生产力与测试非常规组件
- - '##'
  - 创建参数化测试
- - '##'
  - 将测试聚合到测试套件中
- - '##'
  - 在 UI 测试中使用 AndroidStudio 的实时模板
- - '##'
  - Espresso 的 Drawable 匹配器
- - '##'
  - 在 Espresso UI 测试中设置 SeekBar 进度
- - '##'
  - 排版后的内容
- - '#'
  - 索引
- - '##'
  - A
- - '##'
  - B
- - '##'
  - C
- - '##'
  - D
- - '##'
  - E
- - '##'
  - F
- - '##'
  - G
- - '##'
  - H
- - '##'
  - I
- - '###'
  - 插桩
- - '###'
  - Intents
- - '####'
  - 类
- - '####'
  - 类型
- - '####'
  - 验证
- - '##'
  - J
- - '###'
  - JUnit 参数化测试
- - '###'
  - JUnit 套件运行器
- - '##'
  - K
- - '###'
  - Kotlin
- - '###'
  - Kotlin，Espresso 领域特定语言
- - '##'
  - L
- - '##'
  - M
- - '##'
  - N
- - '##'
  - O
- - '##'
  - P, Q
- - '##'
  - R
- - '###'
  - '`RecyclerViewActions`'
- - '###'
  - RecyclerView 匹配器
- - '###'
  - 运行插桩测试
- - '###'
  - 运行时权限
- - '###'
  - '`RuntimePermissionsTest.kt`'
- - '###'
  - '`RuntimePermissionsUiAutomatorTest.kt`'
- - '##'
  - S
- - '###'
  - '`ScreenDimensions` 类'
- - '###'
  - 屏幕对象设计模式，Android UI 测试
- - '###'
  - '`SearchCondition`'
- - '###'
  - SeekBar 进度
- - '###'
  - 对 Activity 的 Intent 进行桩操作
- - '###'
  - 监督式 Monkey 测试
- - '##'
  - T
- - '###'
  - 测试自动化
- - '###'
  - 测试机器人模式
- - '##'
  - U
- - '###'
  - UI Automator
- - '###'
  - UI 元素
- - '###'
  - UI 测试
- - '##'
  - V
- - '###'
  - '`ViewActions` 类'
- - '###'
  - 视图匹配器，Espresso
- - '##'
  - W, X, Y, Z
