name: Learn Android Studio 4
name_cn: Android Studio 4 学习指南
slug: learn-android-studio-4
toc:
- - '#'
  - 引言
- - '##'
  - 章节概览
- - '#'
  - 致谢
- - '#'
  - 关于作者
- - '#'
  - 关于技术评审者
- - '#'
  - Android 概述
- - '##'
  - 历史
- - '##'
  - 操作系统
- - '##'
  - 摘要
- - '#'
  - 2. Android Studio
- - '##'
  - 环境搭建
- - '##'
  - 配置 Android Studio
- - '###'
  - 硬件加速
- - '##'
  - 总结
- - '#'
  - 3. 项目基础
- - '##'
  - 创建项目
- - '###'
  - 创建 AVD
- - '##'
  - 总结
- - '#'
  - 4. Android Studio IDE
- - '##'
  - IDE（集成开发环境）
- - '###'
  - 主编辑器
- - '###'
  - 编辑布局文件
- - '###'
  - TODO 项
- - '##'
  - 如何为代码获取更多屏幕空间
- - '###'
  - 项目工具窗口
- - '##'
  - 总结
- - '#'
  - 5. Android 应用程序概述
- - '##'
  - Android 项目的构成
- - '##'
  - 应用入口点
- - '##'
  - 活动（Activities）
- - '##'
  - 意图（Intents）
- - '##'
  - 总结
- - '#'
  - 6. 活动（Activities）与布局（Layouts）
- - '##'
  - 活动（Activity）
- - '###'
  - 布局文件
- - '##'
  - 视图与视图组对象
- - '###'
  - 容器
- - '##'
  - Activity 类
- - '###'
  - Hello World
- - '###'
  - 修改 Hello World
- - '##'
  - 属性面板
- - '###'
  - 折叠状态
- - '###'
  - 展开状态
- - '##'
  - 本章小结
- - '#'
  - 7. 事件处理
- - '##'
  - 事件处理简介
- - '##'
  - 处理长按点击
- - '##'
  - 总结
- - '#'
  - 8. 意图
- - '##'
  - 什么是 Intent
- - '##'
  - 隐式 Intent
- - '###'
  - 摘要
- - '#'
  - 9. 片段
- - '##'
  - 片段简介
- - '##'
  - 总结
- - '#'
  - 10. 导航
- - '##'
  - 架构组件之前的导航方式
- - '##'
  - 导航组件
- - '###'
  - 使用 Jetpack Navigation
- - '##'
  - 总结
- - '#'
  - 11. 在后台运行
- - '##'
  - 基本概念
- - '##'
  - UI 线程
- - '##'
  - 线程与可运行对象
- - '##'
  - 本章小结
- - '#'
  - 12. 调试
- - '##'
  - 错误类型
- - '###'
  - 语法错误
- - '###'
  - 运行时错误
- - '###'
  - 逻辑错误
- - '##'
  - 调试器
- - '###'
  - 单步执行
- - '##'
  - 总结
- - '#'
  - 13. 测试
- - '##'
  - 测试类型
- - '##'
  - 单元测试
- - '###'
  - JVM 测试 vs. 插桩测试
- - '###'
  - 简单示例
- - '###'
  - 执行测试
- - '###'
  - 运行单元测试
- - '##'
  - 仪器化测试
- - '###'
  - 搭建一个简单的测试
- - '###'
  - 录制 Espresso 测试
- - '###'
  - 更多关于 Espresso 匹配器
- - '###'
  - Espresso 操作
- - '###'
  - 总结
- - '#'
  - 14. 文件操作
- - '##'
  - 内部与外部存储
- - '##'
  - 缓存目录
- - '##'
  - 如何使用内部存储
- - '###'
  - 总结
- - '#'
  - 15. BroadcastReceivers
- - '##'
  - '`BroadcastReceiver` 简介'
- - '###'
  - 系统广播与自定义广播
- - '###'
  - 注册广播的两种方式
- - '###'
  - 清单注册
- - '###'
  - Context 注册
- - '##'
  - 总结
- - '#'
  - 16. Jetpack、LiveData、ViewModel 和 Room
- - '##'
  - 生命周期感知组件
- - '##'
  - ViewModel
- - '###'
  - LiveData
- - '###'
  - Room
- - '##'
  - 总结
- - '#'
  - 17. 发布应用
- - '##'
  - 准备发布应用
- - '###'
  - 准备发布材料和素材
- - '###'
  - 配置应用以进行发布
- - '###'
  - 构建一个可供发布的应用程序
- - '##'
  - 发布应用
- - '###'
  - 摘要
- - '#'
  - 18. 补充说明
- - '##'
  - 生产力特性
- - '###'
  - 导入示例
- - '###'
  - 重构
- - '###'
  - 生成
- - '###'
  - 编码风格
- - '##'
  - 动态模板
- - '##'
  - 重要快捷键
- - '##'
  - 总结
- - '#'
  - 索引 A
- - '##'
  - 活动（Activity）
- - '##'
  - Android 开发者工具 (ADT)
- - '##'
  - 应用发布
- - '##'
  - 算术运算符
- - '##'
  - 赋值运算符
- - '#'
  - B
- - '##'
  - 广播（Broadcast）
- - '#'
  - C
- - '##'
  - 缓存目录
- - '##'
  - 类型转换（Casting）
- - '##'
  - 代码生成器
- - '##'
  - 兼容性测试
- - '##'
  - 合规性测试
- - '##'
  - 组件导航
- - '##'
  - 复合视图（Composite view）
- - '##'
  - 上下文注册
- - '##'
  - 控制结构
- - '#'
  - D
- - '##'
  - '`databaseBuilder()` 方法'
- - '##'
  - 数据类型
- - '##'
  - 调试器（Debugger）
- - '##'
  - 声明式事件处理
- - '##'
  - 开发者测试
- - '##'
  - 设备浏览器（Device Explorer）
- - '#'
  - E
- - '##'
  - 相等运算符
- - '##'
  - 事件处理
- - '##'
  - 外部存储，优缺点
- - '#'
  - F
- - '##'
  - 片段（Fragments）
- - '##'
  - 功能测试
- - '#'
  - G
- - '##'
  - '`getNumber()` 方法'
- - '#'
  - H
- - '##'
  - Hello World，活动注释
- - '#'
  - I
- - '##'
  - 集成开发环境 (IDE)
- - '##'
  - '`if/switch` 语句'
- - '##'
  - 隐式 Intent
- - '##'
  - '`indexOf()` 方法'
- - '##'
  - 插桩测试
- - '##'
  - '`Integer.parseInt()` 方法'
- - '##'
  - Intent
- - '##'
  - 内部存储
- - '#'
  - J
- - '##'
  - Java
- - '##'
  - Java 2 标准版 (J2SE)
- - '##'
  - Java 社区进程 (JCP)
- - '##'
  - Java 开发工具包 (JDK)
- - '##'
  - Java 企业版 (Java EE)
- - '##'
  - Java 密钥库 (JKS)
- - '##'
  - '`java.lang.String` 类'
- - '##'
  - Java 移动版 (Java ME)
- - '##'
  - Java 标准版 (Java SE)
- - '##'
  - Java 语法
- - '##'
  - Jetpack 导航
- - '#'
  - K
- - '##'
  - 键盘快捷键
- - '#'
  - L
- - '##'
  - 布局文件
- - '##'
  - 生命周期感知组件
- - '##'
  - 生命周期观察者
- - '##'
  - 生命周期所有者
- - '##'
  - Linux 内核
- - '##'
  - LiveData
- - '##'
  - 实时模板
- - '##'
  - 本地化测试
- - '##'
  - Logcat 工具窗口
- - '##'
  - 逻辑运算符
- - '##'
  - 逻辑错误
- - '##'
  - 长按事件
- - '#'
  - M
- - '##'
  - '`MainActivityObserver`'
- - '##'
  - '`makeText()` 函数'
- - '#'
  - N
- - '##'
  - 窄化转换
- - '##'
  - 导航（Navigation）
- - '#'
  - O
- - '##'
  - '`onCreate()` 方法'
- - '##'
  - '`onLongClick` 方法'
- - '##'
  - '`onPause()` 方法'
- - '##'
  - '`onReceive()` 方法'
- - '##'
  - '`onResume()` 方法'
- - '##'
  - '`openFileOutput()` 方法'
- - '##'
  - 运算符
- - '##'
  - '`@Override` 注解'
- - '#'
  - P, Q
- - '##'
  - 渗透/安全测试
- - '##'
  - 性能测试
- - '##'
  - 基本/原生数据类型
- - '##'
  - 生产力
- - '##'
  - 发布-订阅模式
- - '#'
  - R
- - '##'
  - '`RandomNumber` 类'
- - '##'
  - 恢复测试
- - '##'
  - 重构
- - '##'
  - '`registerReceiver()` 方法'
- - '##'
  - 关系运算符
- - '##'
  - Room
- - '##'
  - 运行时错误
- - '#'
  - S
- - '##'
  - '`setContentView` 方法'
- - '##'
  - '`setText()` 方法'
- - '##'
  - 浸泡测试/耐力测试
- - '##'
  - 声音测试
- - '##'
  - 尖峰测试/可扩展性测试
- - '##'
  - 字符串
- - '##'
  - Switch 语句
- - '##'
  - 语法错误
- - '##'
  - 系统广播
- - '#'
  - T
- - '##'
  - '`TextView`'
- - '##'
  - Try-catch 结构
- - '#'
  - U
- - '##'
  - UI 线程
- - '##'
  - 一元运算符
- - '##'
  - 单元测试
- - '##'
  - 用户定义类型 (UDT)
- - '#'
  - V
- - '##'
  - '`ViewGroup`'
- - '##'
  - '`ViewModel`'
- - '##'
  - 容量测试
- - '#'
  - W, X, Y, Z
- - '##'
  - While 循环语句
