name: Beginning iOS Social Games
name_cn: iOS 社交游戏入门指南
slug: beginning-ios-social-games
toc:
- - '#'
  - 序言：与友同乐
- - '#'
  - 关于作者
- - '##'
  - 关于技术审校者
- - '##'
  - 简介
- - '##'
  - 前置要求
- - '##'
  - 本书结构
- - '##'
  - 源代码
- - '##'
  - 所需软件、材料与设备
- - '##'
  - 致谢
- - '#'
  - 目录
- - '##'
  - 第 1 章：社交游戏入门
- - '##'
  - 第 2 章：Game Center：设置与入门
- - '##'
  - 第 3 章：排行榜
- - '##'
  - 第 4 章：成就
- - '##'
  - 第 5 章：匹配与邀请
- - '##'
  - 第 6 章：对等选择器
- - '##'
  - 第 7 章：网络设计概述
- - '##'
  - 第 8 章：数据交换
- - '##'
  - 第 9 章：使用 Game Center 的回合制游戏
- - '##'
  - 第 10 章：语音聊天
- - '##'
  - 第 11 章：使用 StoreKit 进行应用内购买
- - '##'
  - 第 12 章：Twitter
- - '##'
  - 第 13 章：Facebook
- - '##'
  - 第 14 章：AirPlay
- - '##'
  - 第 15 章：游戏控制器
- - '#'
  - 第 1 章：社交游戏入门
- - '##'
  - 摘要
- - '##'
  - Game Kit 概述
- - '###'
  - 网络功能
- - '###'
  - Game Center
- - '###'
  - 语音聊天
- - '##'
  - 示例游戏：UFO
- - '###'
  - UFO：理解游戏
- - '###'
  - UFO：检查源代码
- - '####'
  - 设置加速计委托
- - '####'
  - 将玩家绘制到视图上
- - '####'
  - 设置奶牛、牵引光束和得分
- - '####'
  - 处理旋转事件
- - '####'
  - 添加玩家移动
- - '####'
  - 监听触摸事件
- - '####'
  - 生成和移动奶牛
- - '####'
  - 使用 `UIImage` 执行命中测试
- - '####'
  - 绑架奶牛
- - '###'
  - 配置 iTunes Connect 以支持 Game Center
- - '####'
  - 开始使用 iTunes Connect
- - '####'
  - 在 iTunes Connect 中配置 Game Center
- - '##'
  - 总结
- - '#'
  - 第 2 章：Game Center：设置与入门
- - '##'
  - 测试 Game Center
- - '##'
  - 使用 Game Center 进行身份验证
- - '###'
  - 修改 GameCenterManager 类
- - '####'
  - 在 iOS 6 和 iOS 7 上进行身份验证
- - '####'
  - 在 iOS 6 之前进行身份验证
- - '###'
  - 从 UFOViewController 进行身份验证
- - '###'
  - 沙盒
- - '###'
  - 监控状态变化
- - '##'
  - 使用 GKLocalPlayer
- - '###'
  - 获取好友列表
- - '###'
  - 好友列表头像
- - '##'
  - 与玩家协作
- - '##'
  - 本章小结
- - '#'
  - 第 3 章：排行榜
- - '##'
  - 为何需要排行榜？
- - '##'
  - Game Center 排行榜概述
- - '###'
  - 使用苹果排行榜 GUI 相比自定义 GUI 的优势
- - '##'
  - 在 iTunes Connect 中配置排行榜
- - '###'
  - 创建单个排行榜并提交分数
- - '####'
  - 提交分数
- - '####'
  - 设置默认排行榜
- - '##'
  - 为 UFO 游戏添加分数提交功能
- - '###'
  - 处理成绩提交失败
- - '##'
  - 展示排行榜
- - '###'
  - 自定义排行榜
- - '###'
  - 修改 GameCenterManager
- - '###'
  - 在自定义排行榜上过滤结果
- - '###'
  - 显示自定义排行榜
- - '###'
  - 映射玩家 ID
- - '###'
  - 本地玩家分数
- - '###'
  - 更好的方法
- - '###'
  - 挑战
- - '###'
  - GKLeaderboard 集合
- - '##'
  - 摘要
- - '#'
  - 第 4 章：成就
- - '##'
  - 为什么使用成就？
- - '##'
  - Game Center 成就概览
- - '###'
  - 使用苹果成就 GUI 与自定义 GUI 的好处
- - '##'
  - 在 iTunes Connect 中配置成就
- - '###'
  - 创建新成就
- - '##'
  - 展示成就
- - '##'
  - 修改成就进度
- - '###'
  - 加载成就
- - '###'
  - 成就协议
- - '##'
  - 重置成就
- - '##'
  - 添加成就挂钩
- - '###'
  - 在 UFO 游戏中添加挂钩
- - '####'
  - 基于时间的成就钩子
- - '####'
  - 另一个便捷方法
- - '####'
  - 完成成就时的反馈
- - '###'
  - 添加成就完成横幅
- - '###'
  - 自定义成就图形界面
- - '###'
  - 获取成就数据
- - '##'
  - 从提交失败中恢复
- - '##'
  - 成就挑战
- - '##'
  - 总结
- - '#'
  - 第 5 章：匹配与邀请
- - '##'
  - 摘要
- - '##'
  - 为什么要为你的应用添加联网功能？
- - '##'
  - 通用匹配场景
- - '###'
  - 创建新的匹配请求
- - '###'
  - 呈现匹配界面
- - '###'
  - 处理收到的邀请
- - '##'
  - 自动匹配
- - '##'
  - 以编程方式进行匹配
- - '##'
  - 向匹配中添加玩家
- - '##'
  - 重新邀请玩家
- - '##'
  - 玩家分组
- - '##'
  - 玩家属性
- - '###'
  - 理解玩家属性限制
- - '###'
  - 使用玩家属性
- - '##'
  - 玩家活动
- - '###'
  - 使用自有服务器（托管比赛）
- - '##'
  - 总结
- - '#'
  - 第 6 章：对等选择器
- - '##'
  - 对等选择器的优势
- - '##'
  - 现实世界示例
- - '##'
  - 使用会话（Sessions）
- - '##'
  - 展示对等选择器
- - '##'
  - 高级 `GKSession` 交互
- - '##'
  - 点对点选择器委托
- - '##'
  - 总结
- - '#'
  - 第 7 章：网络设计概述
- - '##'
  - 提前规划
- - '###'
  - 三种网络类型
- - '####'
  - 点对点网络
- - '####'
  - 客户端-主机网络
- - '####'
  - 环形网络
- - '###'
  - 较少见的网络类型
- - '##'
  - 可靠数据 vs. 不可靠数据
- - '##'
  - 只发送必要的数据
- - '###'
  - 预测与外推
- - '###'
  - 消息格式化
- - '##'
  - 防止作弊与超时断线
- - '##'
  - 万策尽时如何应对
- - '##'
  - 总结
- - '##'
  - 脚注
- - '#'
  - 第 8 章：数据交换
- - '##'
  - 摘要
- - '##'
  - 修改单人游戏
- - '##'
  - 为多人游戏设置引擎
- - '###'
  - 选择主机
- - '###'
  - 发送数据
- - '###'
  - 接收数据
- - '##'
  - 整合所有功能
- - '###'
  - 选择主机
- - '###'
  - 显示敌方 UFO
- - '####'
  - 生成奶牛
- - '###'
  - 共享分数
- - '###'
  - 添加网络劫持代码
- - '##'
  - 断开连接
- - '##'
  - 总结
- - '#'
  - 第 9 章：使用 Game Center 进行回合制游戏
- - '##'
  - 新示例项目
- - '###'
  - '`GKTurnBasedMatchmakerViewController`'
- - '##'
  - 开始新游戏
- - '###'
  - 落子
- - '##'
  - 继续进行中的游戏
- - '##'
  - 结束比赛
- - '###'
  - 退出与弃权
- - '###'
  - 玩家超时
- - '###'
  - 玩家交涉
- - '###'
  - 玩家提醒
- - '##'
  - 编程式匹配
- - '##'
  - '`GKTurnBasedEventHandler`'
- - '##'
  - 总结
- - '#'
  - 第 10 章：语音聊天
- - '##'
  - 摘要
- - '##'
  - Game Center 的语音聊天
- - '###'
  - 创建音频会话
- - '###'
  - 创建新的语音频道
- - '###'
  - 启动和停止语音聊天
- - '###'
  - 聊天音量和静音
- - '###'
  - 监测玩家状态
- - '##'
  - 适用于 Game Kit 的语音聊天
- - '###'
  - 创建音频会话
- - '###'
  - 必需的额外设置
- - '###'
  - 启动运行
- - '##'
  - 整合
- - '##'
  - 总结
- - '#'
  - 第 11 章：使用 StoreKit 实现应用内购买
- - '##'
  - 摘要
- - '##'
  - 在 iTunes Connect 中设置你的应用
- - '##'
  - 向应用添加产品
- - '###'
  - 应用标识与内购
- - '###'
  - 设置
- - '###'
  - 获取产品列表
- - '###'
  - 向用户展示你的产品
- - '##'
  - 购买产品
- - '###'
  - 购买代码
- - '###'
  - 购买多个商品
- - '###'
  - 处理交易
- - '###'
  - 恢复之前完成的交易
- - '##'
  - 测试账户与测试购买
- - '###'
  - 使用测试账户登录
- - '####'
  - 提交购买界面截图
- - '####'
  - 开发者批准
- - '####'
  - 收据
- - '###'
  - iOS 7 本地收据验证
- - '##'
  - 在 UFO 游戏中整合所有内容
- - '##'
  - 总结
- - '#'
  - 第 12 章：Twitter
- - '##'
  - 摘要
- - '##'
  - UFO 游戏
- - '##'
  - iOS 上的 Twitter
- - '###'
  - Tweet Composer
- - '###'
  - 自定义推文
- - '###'
  - 深入探索 Twitter
- - '##'
  - 本章小结
- - '#'
  - 第 13 章：Facebook
- - '##'
  - 关于示例项目
- - '##'
  - iOS 上的 Facebook
- - '###'
  - Facebook 分享器
- - '###'
  - Facebook 应用
- - '###'
  - Facebook 权限
- - '###'
  - 自定义 Facebook 帖子
- - '##'
  - 进一步探索 Facebook
- - '##'
  - 摘要
- - '#'
  - 第 14 章：AirPlay
- - '##'
  - 简介
- - '##'
  - 内置播放器的 AirPlay
- - '###'
  - MPNowPlayingInfoCenter
- - '###'
  - 响应远程事件
- - '##'
  - 在应用中启用 AirPlay
- - '##'
  - AirPlay 屏幕镜像
- - '##'
  - 第二屏幕的 AirPlay
- - '##'
  - 响应屏幕通知
- - '##'
  - 总结
- - '#'
  - 第 15 章：游戏控制器
- - '##'
  - 摘要
- - '##'
  - 游戏控制器的类型
- - '##'
  - 连接到游戏控制器
- - '###'
  - 通过轮询读取数据
- - '###'
  - 数据回调
- - '###'
  - 暂停
- - '##'
  - 玩家指示灯
- - '##'
  - 快照
- - '##'
  - 总结
- - '#'
  - 附录
- - '##'
  - iOS 社交游戏入门
- - '##'
  - 索引
- - '###'
  - A, B
- - '###'
  - C
- - '###'
  - D
- - '###'
  - E
- - '###'
  - F
- - '###'
  - G
- - '###'
  - H
- - '###'
  - I, J, K
- - '###'
  - L
- - '###'
  - M
- - '###'
  - N, O
- - '###'
  - P, Q
- - '###'
  - R
- - '###'
  - S
- - '###'
  - T
- - '###'
  - U
- - '###'
  - V
- - '###'
  - W, X, Y, Z
