name: Windows 8 Apps Revealed Using XAML and C#
name_cn: Windows 8 应用开发揭秘：XAML 与 C# 使用指南
slug: windows-8-apps-revealed-using-xaml-and-c
toc:
- - '#'
  - Windows 8 应用揭秘
- - '##'
  - 内容概览
- - '##'
  - 目录
- - '##'
  - 关于作者
- - '##'
  - 关于技术审校
- - '##'
  - 致谢
- - '#'
  - 第 1 章：入门
- - '##'
  - 关于本书
- - '##'
  - 阅读本书前需要了解什么？
- - '##'
  - 阅读本书需要什么软件？
- - '###'
  - 安装 Visual Studio
- - '##'
  - 本书结构是怎样的？
- - '###'
  - 第 1 章：入门
- - '###'
  - 第 2 章：数据、绑定和页面
- - '###'
  - 第 3 章：应用栏、浮出控件和导航栏
- - '###'
  - 第 4 章：布局和磁贴
- - '###'
  - 第 5 章：应用生命周期和协定
- - '##'
  - 关于示例 Windows 应用的更多信息
- - '##'
  - 本书代码多吗？
- - '##'
  - 启动与运行
- - '###'
  - 创建项目
- - '##'
  - 探索 App.xaml 文件
- - '##'
  - 探索 MainPage.xaml 文件
- - '##'
  - 探索 `StandardStyles.xaml` 文件
- - '##'
  - 探索 `Package.appxmanifest` 文件
- - '##'
  - 极简 XAML 概述
- - '##'
  - 使用 Visual Studio 设计图面
- - '##'
  - 在 XAML 中配置控件
- - '##'
  - 应用样式
- - '##'
  - 指定事件处理程序
- - '##'
  - 在代码中配置控件
- - '##'
  - 运行和调试 Windows 应用程序
- - '###'
  - 在模拟器中运行 Windows 应用程序
- - '##'
  - 总结
- - '#'
  - 第 2 章：数据、绑定和页面
- - '###'
  - 添加 View Model
- - '###'
  - 添加主布局
- - '##'
  - 编写代码
- - '###'
  - 添加资源字典
- - '##'
  - 编写 XAML
- - '##'
  - 运行应用程序
- - '##'
  - 将其他页面插入布局
- - '##'
  - 动态地将页面插入布局
- - '##'
  - 在页面之间切换
- - '##'
  - 实现嵌入页面
- - '##'
  - 总结
- - '#'
  - 第 3 章：应用栏、浮出控件和导航
- - '##'
  - 添加上下文菜单 (AppBar)
- - '###'
  - 声明 AppBar
- - '##'
  - 调整预定义的 AppBar 按钮
- - '##'
  - 创建自定义 AppBar 按钮样式
- - '##'
  - 实现 AppBar 按钮操作
- - '##'
  - 创建 Flyout
- - '###'
  - 创建用户控件
- - '##'
  - 编写用户控件代码
- - '##'
  - 定位 Popup 控件
- - '##'
  - 显示和隐藏 Popup 控件
- - '##'
  - 向应用添加 Flyout
- - '##'
  - 在 Windows 应用内导航
- - '###'
  - 创建包装器
- - '###'
  - 创建另一个视图
- - '###'
  - 测试导航
- - '##'
  - 本章小结
- - '#'
  - 第 4 章：视图与磁贴
- - '##'
  - 支持视图
- - '###'
  - 在代码中响应视图变化
- - '##'
  - 在 XAML 中响应视图更改
- - '##'
  - 创建动态磁贴
- - '##'
  - 填充 XML 模板
- - '##'
  - 应用磁贴更新
- - '##'
  - 调用磁贴更新方法
- - '##'
  - 测试磁贴更新
- - '##'
  - 更新宽磁贴
- - '###'
  - '`ImportNode` 方法'
- - '##'
  - 应用徽章
- - '##'
  - 总结
- - '#'
  - 第 5 章：应用生命周期与合约
- - '##'
  - 处理应用生命周期
- - '##'
  - 修正 Visual Studio 事件代码
- - '##'
  - 模拟生命周期事件
- - '##'
  - 测试生命周期事件
- - '###'
  - 激活应用
- - '###'
  - 挂起应用
- - '###'
  - 恢复应用
- - '##'
  - 添加后台活动
- - '##'
  - 扩展视图模型
- - '##'
  - 显示位置数据
- - '##'
  - 声明应用功能
- - '##'
  - 控制后台任务
- - '##'
  - 分发 UI 更新
- - '##'
  - 测试后台任务
- - '##'
  - 实现协定
- - '###'
  - 声明对协定的支持
- - '###'
  - 实现搜索功能
- - '##'
  - 响应搜索生命周期事件
- - '###'
  - 测试搜索协定
- - '##'
  - 总结
- - '#'
  - 索引
