name: Beginning ARKit for iPhone and iPad
name_cn: ARKit for iPhone and iPad 入门指南
slug: beginning-arkit-for-iphone-and-ipad
toc:
- - '#'
  - 理解增强现实与 ARKit
- - '##'
  - 移动设备上的增强现实技术
- - '##'
  - ARKit 简介
- - '#'
  - 增强现实应用
- - '##'
  - 注意
- - '##'
  - ARKit 的系统要求
- - '##'
  - 概述
- - '#'
  - 认识 ARKit
- - '##'
  - 注意
- - '##'
  - 注意
- - '##'
  - 理解 Swift 源代码
- - '##'
  - 注意
- - '##'
  - 理解用户界面
- - '#'
  - 使用单视图 App 模板创建增强现实应用
- - '##'
  - 修改`ViewController.swift`文件
- - '##'
  - 添加 ARKit 场景视图
- - '#'
  - 在 Xcode 中导入并使用 COLLADA (.dae) 文件
- - '##'
  - 准备 Swift 代码与用户界面
- - '##'
  - 导入 3D 图像到 Xcode
- - '##'
  - 概述
- - '##'
  - 世界追踪
- - '###'
  - 显示世界原点
- - '###'
  - 重置世界原点
- - '#'
  - 在坐标处显示形状
- - '##'
  - 准备项目
- - '##'
  - 测试应用程序
- - '##'
  - 试验坐标
- - '##'
  - 添加与移除多个物体
- - '###'
  - 为滑块创建 IBOutlet
- - '##'
  - 总结
- - '#'
  - 4. 使用形状
- - '##'
  - 显示不同的几何形状
- - '##'
  - 显示文本
- - '##'
  - 为形状添加纹理
- - '##'
  - 更改形状的透明度
- - '##'
  - 绘制形状
- - '##'
  - 总结
- - '#'
  - 5. 处理光照
- - '##'
  - 使用颜色、强度与色温
- - '##'
  - 添加约束和修改用户界面对象
- - '##'
  - 将用户界面连接到 Swift 代码
- - '##'
  - 使用聚光灯
- - '##'
  - 设计用户界面
- - '##'
  - 连接用户界面与代码
- - '##'
  - 小结
- - '#'
  - 第六章 定位物体
- - '##'
  - 定义相对位置
- - '##'
  - 相对定位虚拟对象
- - '##'
  - 组合几何形状
- - '##'
  - 总结
- - '#'
  - 7. 旋转对象
- - '##'
  - 使用欧拉角旋转对象
- - '##'
  - 关联对象的旋转
- - '##'
  - 相对定位移动所有相关的虚拟对象
- - '##'
  - 总结
- - '#'
  - 8. 在屏幕上绘图
- - '##'
  - 添加约束与连接界面
- - '##'
  - 绘制增强现实视图
- - '###'
  - 获取摄像头旋转与位置
- - '##'
  - 应用功能与设置
- - '###'
  - 编写渲染器函数代码
- - '####'
  - 绘制绿线
- - '####'
  - 显示指针
- - '####'
  - 完整的 DispatchQueue 代码
- - '##'
  - 完整的 ViewController.swift 文件
- - '##'
  - 运行应用
- - '###'
  - 应用程序运行步骤
- - '###'
  - 功能完善
- - '###'
  - 运行应用程序
- - '##'
  - 总结
- - '#'
  - 9. 为增强现实添加触控手势
- - '##'
  - 识别触摸手势
- - '##'
  - 识别虚拟对象上的触摸手势
- - '##'
  - 测试应用
- - '##'
  - 识别虚拟物体上的滑动手势
- - '##'
  - 测试滑动检测应用
- - '##'
  - 识别虚拟物体的平移手势
- - '##'
  - 识别虚拟物体上的长按手势
- - '##'
  - 添加捏合与旋转手势
- - '##'
  - 总结
- - '#'
  - 10. 与增强现实交互
- - '##'
  - 使用捏合触摸手势进行缩放
- - '##'
  - 使用旋转触摸手势进行旋转
- - '##'
  - 旋转虚拟平面
- - '##'
  - 使用平移手势移动虚拟对象
- - '#'
  - 11. 平面检测
- - '##'
  - 连接视图并配置平面检测
- - '##'
  - 配置视图和平面检测
- - '##'
  - 实现渲染器委托方法
- - '##'
  - 完整的 ViewController.swift 文件
- - '##'
  - 测试项目
- - '##'
  - 在平面上显示图像
- - '###'
  - 创建平面
- - '###'
  - 使平面变为双面且水平
- - '###'
  - 将平面附加到检测到的表面
- - '##'
  - 在水平面上放置虚拟对象
- - '##'
  - 修改 `Info.plist` 文件
- - '##'
  - 修改 `ViewController.swift` 文件
- - '##'
  - 添加点击手势识别
- - '##'
  - 创建 `addObject` 函数
- - '##'
  - 检测垂直平面
- - '##'
  - 总结
- - '#'
  - 12. 虚拟对象的物理特性
- - '##'
  - 连接用户界面与代码
- - '##'
  - 检测并绘制虚拟平面
- - '##'
  - 更新虚拟平面
- - '##'
  - 测试项目
- - '##'
  - 对虚拟对象施加力
- - '##'
  - 处理点击手势
- - '##'
  - 测试代码
- - '##'
  - 与虚拟物体发生碰撞
- - '##'
  - 碰撞检测
- - '##'
  - 小结
- - '#'
  - 13. 与现实世界互动
- - '##'
  - 检测现实世界中的点
- - '##'
  - 在现实世界中定义点
- - '##'
  - 测量虚拟物体之间的距离
- - '##'
  - 总结
- - '#'
  - 14. 图像检测
- - '##'
  - 存储图像
- - '##'
  - 检测多张图像
- - '##'
  - 在增强现实中显示信息
- - '##'
  - 总结
- - '#'
  - 15. 显示视频和虚拟模型
- - '##'
  - 在半空中显示虚拟对象
- - '##'
  - 在平面上显示视频
- - '##'
  - 总结
- - '#'
  - 16. 图像跟踪与物体检测
- - '##'
  - 检测物体
- - '##'
  - 扫描对象
- - '###'
  - 在应用中检测物体
- - '##'
  - 小结
- - '#'
  - 17. 持久化
- - '##'
  - 保存世界地图
- - '##'
  - 加载世界地图
- - '##'
  - 清除增强现实视图
- - '##'
  - 总结
- - '#'
  - 索引
- - '##'
  - A
- - '##'
  - B
- - '##'
  - C
- - '##'
  - D
- - '##'
  - E
- - '##'
  - F
- - '##'
  - G
- - '##'
  - H
- - '##'
  - I, J
- - '##'
  - K
- - '##'
  - L
- - '##'
  - M, N
- - '##'
  - O
- - '##'
  - P, Q
- - '##'
  - R
- - '##'
  - S
- - '##'
  - T, U
- - '##'
  - V
- - '##'
  - W, X, Y, Z
