name: Objective-C programmer's reference
name_cn: Objective-C 程序员参考
slug: objective-c-programmers-reference
toc:
- - '#'
  - 关于作者
- - '#'
  - 关于技术审校
- - '#'
  - 引言
- - '#'
  - 讨论的主题
- - '##'
  - 你将学到什么
- - '###'
  - 第 1 章：Objective-C 中的 C 语言元素
- - '###'
  - 第 2 章：类
- - '###'
  - 第 3 章：字符串和容器类
- - '###'
  - 第 4 章：协议和类别
- - '###'
  - 第 5 章：继承
- - '###'
  - 第 6 章：块语法
- - '#'
  - Objective-C 进阶指南
- - '###'
  - 第 7 章：动态绑定
- - '###'
  - 第 8 章：内存管理
- - '###'
  - 第 9 章：键值编程
- - '###'
  - 第 10 章：文件系统
- - '###'
  - 第 11 章：Foundation 框架
- - '###'
  - 第 12 章：编译器
- - '###'
  - 第 13 章：预处理器
- - '###'
  - 第 14 章：单元测试
- - '###'
  - 第 15 章：调试
- - '###'
  - 第 16 章：在 Cocoa 中构建 OS X 应用程序
- - '###'
  - 第 17 章：在 Cocoa Touch 上构建 iOS 应用程序
- - '##'
  - 编译代码示例
- - '##'
  - 致谢
- - '##'
  - 目录
- - '#'
  - 第一部分
- - '#'
  - 1. Objective-C 中的 C 语言
- - '##'
  - 摘要
- - '##'
  - 简单语句
- - '##'
  - 变量
- - '###'
  - 变量初始化
- - '##'
  - 变量类型
- - '###'
  - 整数类型
- - '##'
  - 浮点数
- - '##'
  - 字符
- - '##'
  - 逻辑值
- - '##'
  - 指针
- - '##'
  - void 类型
- - '##'
  - 注释
- - '##'
  - 算术表达式
- - '##'
  - 函数基础
- - '###'
  - 定义新函数
- - '####'
  - 函数语法
- - '##'
  - 条件运算
- - '###'
  - '`if` 语句'
- - '##'
  - 循环
- - '###'
  - '`while` 循环'
- - '###'
  - '`do { } while( )` 循环'
- - '###'
  - '`for` 循环'
- - '###'
  - '`switch` 语句'
- - '###'
  - 赋值运算符
- - '###'
  - 自增与自减运算符
- - '###'
  - 复合赋值
- - '##'
  - 结构体
- - '##'
  - 指针
- - '###'
  - 参数传递
- - '##'
  - 数组
- - '###'
  - 数组与指针
- - '##'
  - 总结
- - '#'
  - 2. 类
- - '##'
  - 面向对象编程
- - '###'
  - 为什么对象如此重要？
- - '##'
  - 使用对象
- - '###'
  - 方法参数
- - '###'
  - '`id` 类型'
- - '##'
  - 创建新对象
- - '##'
  - 定义新类
- - '##'
  - 实例变量
- - '##'
  - 添加和定义实例方法
- - '###'
  - 消息与函数的区别
- - '###'
  - 多态消息
- - '###'
  - 特殊变量 `self`
- - '##'
  - 定义类方法
- - '##'
  - init 方法
- - '##'
  - 定义属性
- - '###'
  - 使用属性
- - '###'
  - 合成属性
- - '###'
  - 属性特性
- - '##'
  - 类与文件结构
- - '##'
  - 总结
- - '#'
  - 3. 字符串与容器类
- - '##'
  - 摘要
- - '##'
  - 字符串
- - '###'
  - 创建字符串
- - '###'
  - NSString 方法
- - '###'
  - 子字符串
- - '##'
  - NSNumber 类
- - '###'
  - 访问 `NSNumber`
- - '###'
  - 何时使用 `NSNumber`？
- - '##'
  - 容器
- - '##'
  - 数组
- - '###'
  - 向 `NSArray` 添加其他对象类型
- - '###'
  - 使用字面量表示法
- - '###'
  - 访问数组
- - '##'
  - 可变数组
- - '##'
  - 字典
- - '###'
  - 访问字典元素
- - '####'
  - 检索键
- - '####'
  - 使用字典枚举器
- - '###'
  - 可变字典
- - '##'
  - 总结
- - '#'
  - 4. 类别与协议
- - '##'
  - 摘要
- - '##'
  - 类别
- - '###'
  - 注意
- - '###'
  - 创建新分类
- - '###'
  - 使用分类头文件
- - '###'
  - 类别与私有方法
- - '###'
  - 向类别添加属性
- - '##'
  - 协议
- - '###'
  - 非正式协议
- - '####'
  - 检查协议合规性
- - '###'
  - 正式协议
- - '##'
  - 可选方法
- - '##'
  - 总结
- - '#'
  - 5. 继承
- - '##'
  - 摘要
- - '##'
  - 继承的概念
- - '###'
  - 继承与重写
- - '####'
  - 调用超类中的方法
- - '####'
  - 模板方法
- - '##'
  - 对象初始化
- - '##'
  - 替换原则
- - '##'
  - 类簇
- - '###'
  - 类簇的另一个示例
- - '##'
  - 防止子类化
- - '##'
  - 多重继承
- - '###'
  - 模拟多重继承
- - '##'
  - 继承与委托
- - '##'
  - 总结
- - '#'
  - 6. 块
- - '##'
  - 摘要
- - '##'
  - 介绍 Blocks
- - '##'
  - 声明 Blocks
- - '###'
  - 理解复杂块声明
- - '##'
  - 将块作为参数传递
- - '##'
  - 访问外部变量
- - '###'
  - 局部变量的读写访问
- - '##'
  - 块与内存管理
- - '##'
  - 在 Foundation 框架中使用块
- - '##'
  - 总结
- - '#'
  - 7. 动态绑定
- - '##'
  - 摘要
- - '##'
  - 方法选择器
- - '###'
  - 一个简单示例
- - '###'
  - 带参数的调用
- - '###'
  - 使用选择器
- - '##'
  - Cocoa 中的 Target-Action
- - '##'
  - 动态响应消息
- - '###'
  - 创建代理对象
- - '###'
  - 使用 forwardInvocation
- - '##'
  - 模拟多重继承
- - '###'
  - 实现 `respondsToSelector:`
- - '##'
  - 避免方法调用
- - '##'
  - 总结
- - '#'
  - 8. 内存管理
- - '##'
  - 处理内存问题
- - '###'
  - 内存问题的类型
- - '###'
  - 识别内存 Bug
- - '##'
  - 分配内存
- - '##'
  - 引用计数规则
- - '##'
  - autorelease 方法
- - '##'
  - 使用属性
- - '##'
  - 自动释放池
- - '##'
  - 使用 ARC
- - '##'
  - 总结
- - '#'
  - 9. 键值编码
- - '##'
  - 摘要
- - '##'
  - 键值编码的概念
- - '###'
  - 避免直接访问
- - '###'
  - 编写属性访问器
- - '####'
  - 修改值
- - '#####'
  - 注意
- - '###'
  - KVC 与属性
- - '##'
  - 使用结构体
- - '##'
  - 通过键路径访问对象
- - '##'
  - 访问集合
- - '##'
  - 响应未定义键
- - '##'
  - KVC 与 KVO
- - '##'
  - 总结
- - '#'
  - 10. 文件系统
- - '##'
  - 摘要
- - '##'
  - 使用 NSURL 指定位置
- - '##'
  - 读写文本文件
- - '##'
  - 读写二进制数据
- - '##'
  - 使用 NSStream
- - '###'
  - 读取文件
- - '###'
  - 使用 `NSOutputStream` 写入文件
- - '##'
  - 总结
- - '#'
  - 第二部分
- - '#'
  - 11. Foundation 框架
- - '##'
  - 摘要
- - '##'
  - 基础类
- - '###'
  - NSObject
- - '###'
  - NSString
- - '###'
  - NSMutableString
- - '###'
  - NSValue
- - '###'
  - NSNumber
- - '##'
  - '`NSData`'
- - '###'
  - NSMutableData
- - '##'
  - 集合类
- - '###'
  - NSArray
- - '###'
  - NSDictionary
- - '###'
  - NSHashTable
- - '###'
  - NSSet
- - '##'
  - 总结
- - '#'
  - 第三部分
- - '#'
  - 12. 编译器
- - '##'
  - 摘要
- - '##'
  - 使用 GCC 与 LLVM 编译器
- - '##'
  - 在 Xcode 中更改编译器选项
- - '##'
  - 从命令行运行编译器
- - '###'
  - 文件 Makefile
- - '##'
  - 代码优化
- - '###'
  - 速度优化
- - '###'
  - 空间优化
- - '##'
  - ARC 支持
- - '##'
  - 编译 Objective-C++
- - '##'
  - 总结
- - '#'
  - 13. 预处理器
- - '##'
  - 摘要
- - '##'
  - 定义宏
- - '###'
  - 带参数的宏
- - '###'
  - 宏运算符
- - '###'
  - 常见陷阱
- - '##'
  - 条件编译
- - '###'
  - '#if 指令'
- - '###'
  - '#ifdef 指令'
- - '##'
  - 导入机制
- - '##'
  - 头文件最佳实践
- - '##'
  - 总结
- - '#'
  - 14. 单元测试
- - '##'
  - 摘要
- - '##'
  - 单元测试框架
- - '##'
  - 注意
- - '##'
  - 添加单元测试目标
- - '##'
  - 创建新测试
- - '##'
  - 在 Xcode 中运行测试
- - '##'
  - OCUnit 断言宏
- - '##'
  - Test-Driven Development
- - '##'
  - 总结
- - '#'
  - 15. 调试
- - '##'
  - 通用调试策略
- - '###'
  - 数据收集：调试的第一步
- - '###'
  - 定义假设：调试的第二步
- - '###'
  - 应用修复：调试的第三步
- - '###'
  - 创建一个或多个单元测试：调试的第四步
- - '##'
  - 使用 Xcode 进行调试
- - '###'
  - 控制程序执行
- - '###'
  - 添加断点
- - '###'
  - 监视表达式
- - '###'
  - 检查局部对象
- - '###'
  - 使用日志控制台
- - '##'
  - 命令行调试器
- - '##'
  - 调试内存问题
- - '###'
  - 使用 NSZombie
- - '###'
  - 使用 guardmalloc 库
- - '##'
  - 附加工具
- - '###'
  - 版本控制系统
- - '###'
  - Bug 追踪系统
- - '##'
  - 总结
- - '#'
  - 第四部分
- - '#'
  - 16. 构建 OS X GUI 应用程序
- - '##'
  - 摘要
- - '##'
  - 使用 Cocoa 创建 UI 概述
- - '###'
  - 设置 Cocoa 项目
- - '###'
  - 使用 `nib` 文件
- - '###'
  - Cocoa UI 类
- - '###'
  - Objective-C 中的出口和动作
- - '##'
  - Cocoa UI 层级结构
- - '###'
  - NSWindow 类
- - '###'
  - 窗口控制器对象
- - '###'
  - 委托对象
- - '##'
  - 使用 Xcode 进行 UI 设计
- - '###'
  - nib 文件的组成元素
- - '###'
  - 对象库
- - '###'
  - 创建主窗口
- - '###'
  - 添加菜单
- - '###'
  - 加载 nib 后进行修改
- - '##'
  - 使用 Objective-C 编写 UI 应用
- - '###'
  - main 函数
- - '###'
  - AppDelegate
- - '###'
  - GraphView 接口
- - '###'
  - '`GraphView` 的实现'
- - '###'
  - 代码与解释
- - '##'
  - 总结
- - '#'
  - 17. 构建 iOS 应用
- - '##'
  - iOS 编程
- - '###'
  - 内存限制
- - '###'
  - 有限的多处理
- - '##'
  - iOS 中的 UI 类
- - '###'
  - 容器类
- - '###'
  - UI 控件
- - '##'
  - 设置 Cocoa Touch 项目
- - '##'
  - 使用 iOS 模拟器进行测试
- - '##'
  - 一个 iOS 应用示例
- - '###'
  - 主文件
- - '###'
  - '`MainViewController` 接口'
- - '###'
  - '`MainViewController` 实现'
- - '###'
  - FlipsideViewController 接口
- - '###'
  - FlipsideViewController 实现
- - '##'
  - 总结
- - '#'
  - Carlos Oliveira
- - '##'
  - Objective-C 程序员参考手册
- - '##'
  - 索引
- - '###'
  - A
- - '###'
  - B
- - '###'
  - C
- - '###'
  - D
- - '###'
  - E
- - '###'
  - F
- - '###'
  - G
- - '###'
  - H
- - '###'
  - I
- - '###'
  - J
- - '###'
  - K
- - '###'
  - L
- - '###'
  - M
- - '###'
  - N
- - '###'
  - O
- - '###'
  - P
- - '###'
  - Q
- - '###'
  - R
- - '###'
  - S
- - '###'
  - T
- - '###'
  - U
