name: Beginning Swift Games Development for IOS
name_cn: iOS 的 Swift 游戏开发入门指南
slug: beginning-swift-games-development-for-ios
toc:
- - '#'
  - iOS Swift 游戏开发入门
- - '##'
  - 引言
- - '###'
  - 本书涵盖哪个版本的 Swift？
- - '###'
  - 本书内容
- - '###'
  - 你需要了解的知识
- - '###'
  - 你需要具备的条件
- - '#'
  - 本书内容概览
- - '##'
  - 致谢
- - '##'
  - 目录
- - '###'
  - 第一部分：SpriteKit 入门
- - '####'
  - 第 1 章：设置游戏场景并添加首个精灵
- - '####'
  - 第 2 章：SpriteKit 场景和 SKNode 定位
- - '####'
  - 第 3 章：为游戏添加物理引擎和碰撞检测
- - '####'
  - 第 4 章：添加场景滚动和游戏控制
- - '####'
  - 第 5 章：添加动作和动画
- - '####'
  - 第 6 章：使用发射器节点为游戏添加粒子效果
- - '####'
  - 第 7 章：添加分数和声音
- - '####'
  - 第 8 章：场景之间的转换
- - '####'
  - 第 9 章：SpriteKit 最佳实践
- - '###'
  - 第二部分：SceneKit 入门
- - '####'
  - 第 10 章：创建你的第一个 SceneKit 项目
- - '####'
  - 第 11 章：场景和节点
- - '####'
  - 第 12 章：SceneKit 中的光照、摄像机和材质效果
- - '####'
  - 第 13 章：渲染循环、物理和移动
- - '####'
  - 第 14 章：碰撞检测
- - '####'
  - 第 15 章：SceneKit 与 SpriteKit 的交互
- - '####'
  - 第 16 章：SceneKit 编辑器
- - '####'
  - 索引
- - '###'
  - 内容速览
- - '###'
  - 关于作者和关于技术审阅人
- - '####'
  - 关于作者
- - '####'
  - 关于技术审阅人
- - '#'
  - 第一部分：Swift 与 SpriteKit
- - '##'
  - 第 1 章：设置游戏场景并添加第一个精灵
- - '###'
  - 你需要了解并拥有的东西
- - '###'
  - 介绍 SuperSpaceMan
- - '###'
  - 创建一个 Swift SpriteKit 项目
- - '###'
  - 从头开始
- - '####'
  - '`GameViewController` 类'
- - '####'
  - '`GameScene` 类'
- - '###'
  - 添加背景和玩家精灵
- - '###'
  - 本章小结
- - '##'
  - 第 2 章：SpriteKit 场景与 SKNode 定位
- - '###'
  - 什么是 SKScene？
- - '###'
  - SKScene 渲染循环
- - '###'
  - 构建场景的节点树
- - '####'
  - 渲染节点树
- - '####'
  - 搜索节点树
- - '###'
  - 了解 SKSpriteNode 坐标和锚点
- - '####'
  - 坐标
- - '####'
  - 锚点
- - '###'
  - 总结
- - '##'
  - 第 3 章：为游戏添加物理与碰撞检测
- - '###'
  - 什么是 SKPhysicsBody？
- - '###'
  - 为游戏世界添加物理
- - '###'
  - 理解 SpriteKit 中的物理体
- - '###'
  - 向 SKPhysicsBody 施加力
- - '###'
  - 向 `SKNode` 添加碰撞检测
- - '####'
  - 添加碰撞节点
- - '####'
  - 添加碰撞检测
- - '####'
  - 为 SKPhysicsBody 添加位掩码
- - '####'
  - 收到接触消息时移除能量球
- - '###'
  - 总结
- - '##'
  - 第 4 章：添加场景滚动与游戏控制
- - '###'
  - 重新组织 GameScene
- - '###'
  - 改进游戏场景代码
- - '###'
  - 向场景添加更多能量球
- - '###'
  - 滚动场景
- - '###'
  - 使用加速度计控制玩家移动
- - '###'
  - 添加加速计控制
- - '###'
  - 总结
- - '##'
  - 第 5 章：添加动作和动画
- - '###'
  - 最后一次重构轨道节点布局
- - '###'
  - Sprite Kit 动作
- - '####'
  - 使用动作在场景中移动节点
- - '####'
  - 使用 SKActions 为精灵添加动画
- - '###'
  - 为 GameScene 添加一些额外的闪光点
- - '####'
  - 向背景添加星星
- - '####'
  - 添加行星表面
- - '####'
  - 添加视觉死亡指示器
- - '###'
  - 小结
- - '##'
  - 第 6 章：使用发射器节点为游戏添加粒子效果
- - '###'
  - 使用粒子发射器模板
- - '###'
  - 创建粒子发射器
- - '###'
  - 粒子发射器属性
- - '####'
  - 粒子生命周期属性
- - '#####'
  - 发射器出生速率与最大粒子数属性
- - '####'
  - 生命周期起始值与范围属性
- - '####'
  - 粒子运动属性
- - '#####'
  - 位置范围属性
- - '#####'
  - Z 位置属性
- - '#####'
  - 角度属性
- - '#####'
  - 速度属性
- - '#####'
  - 加速度属性
- - '###'
  - 为玩家添加尾迹
- - '###'
  - 总结
- - '##'
  - 第 7 章：添加分数和音效
- - '###'
  - 介绍 SKLabelNodes
- - '###'
  - 更改标签节点的水平对齐方式
- - '###'
  - 更改标签节点的垂直对齐方式
- - '###'
  - 为游戏添加冲量计数器
- - '###'
  - 为游戏添加简单音效
- - '###'
  - 总结
- - '##'
  - 第 8 章：场景之间的切换
- - '###'
  - 在切换期间暂停场景
- - '###'
  - 检测新场景何时被呈现
- - '###'
  - 为 SuperSpaceMan 添加新场景
- - '###'
  - 结束游戏
- - '####'
  - 赢得游戏
- - '####'
  - 输掉游戏
- - '####'
  - 添加过渡动画
- - '###'
  - 总结
- - '##'
  - 第 9 章：SpriteKit 最佳实践
- - '###'
  - 通过子类化创建自己的节点
- - '###'
  - 重用纹理
- - '###'
  - 使用单一的 `SKTextureAtlas` 实例
- - '###'
  - 外部化你的游戏数据
- - '###'
  - 保持节点树的精简
- - '###'
  - 总结
- - '#'
  - 第二部分：SceneKit 入门
- - '##'
  - 第 10 章：创建你的第一个 SceneKit 项目
- - '###'
  - SceneKit 入门
- - '####'
  - SceneKit 动画
- - '####'
  - 需要了解的知识
- - '###'
  - 创建 SceneKit 项目
- - '###'
  - 连接并构建场景
- - '####'
  - Swiftystein3D
- - '####'
  - 项目资源
- - '####'
  - 构建场景
- - '###'
  - 开始使用 SceneKit
- - '###'
  - 总结
- - '##'
  - 第 11 章：场景与节点
- - '###'
  - 场景图 (Scene Graph)
- - '###'
  - SceneKit 内置模型类
- - '####'
  - SCNGeometry 对象
- - '###'
  - 添加可收集节点
- - '###'
  - 总结
- - '##'
  - 第 12 章：SceneKit 中的光照、摄像机和材质效果
- - '###'
  - SceneKit 摄像机用法
- - '###'
  - 点亮场景
- - '###'
  - 材质
- - '###'
  - 为障碍物应用材质
- - '###'
  - 总结
- - '##'
  - 第 13 章：渲染循环、物理与移动
- - '###'
  - 什么是渲染循环？
- - '###'
  - '`GameView`：移动英雄'
- - '###'
  - 编写回调委托函数
- - '###'
  - 移动摄像机
- - '###'
  - 介绍 CoreMotion 框架
- - '###'
  - 总结
- - '##'
  - 第 14 章：碰撞检测
- - '###'
  - 碰撞检测
- - '###'
  - 摘要
- - '##'
  - 第 15 章：SceneKit 与 SpriteKit 的交互
- - '###'
  - SpriteKit 集成
- - '###'
  - 将控制器连接到覆盖层
- - '###'
  - “游戏结束”画面
- - '###'
  - 总结
- - '##'
  - 第 16 章：SceneKit 编辑器
- - '###'
  - SceneKit 场景
- - '###'
  - 创建场景
- - '####'
  - 添加地板
- - '####'
  - 添加英雄角色
- - '####'
  - 添加摄像机
- - '####'
  - 添加节点
- - '###'
  - 总结
- - '##'
  - 第 1 章：SceneKit 编辑器简介
- - '#'
  - 索引
- - '###'
  - A
- - '###'
  - B
- - '###'
  - C
- - '###'
  - D
- - '###'
  - E
- - '###'
  - F
- - '###'
  - G
- - '###'
  - H
- - '###'
  - I, J, K
- - '###'
  - L
- - '###'
  - M
- - '###'
  - N
- - '###'
  - O
- - '###'
  - P, Q
- - '###'
  - R
- - '###'
  - S
- - '###'
  - T
- - '###'
  - U
- - '###'
  - V, W, X, Y
- - '###'
  - Z
