name: Xamarin mobile application development
name_cn: Xamarin 移动应用开发
slug: xamarin-mobile-application-development
toc:
- - '#'
  - 前言
- - '#'
  - 额外前言
- - '#'
  - Xamarin.Forms：全面指南
- - '##'
  - 简介
- - '##'
  - 本书面向的读者
- - '##'
  - 如何下载代码示例
- - '##'
  - XAML
- - '##'
  - 立即开始使用 Xamarin.Forms 吧！
- - '##'
  - 章节内容
- - '##'
  - 如何阅读本书
- - '##'
  - 完整代码
- - '##'
  - 我现在读的是哪个平台？
- - '#'
  - 前置要求
- - '##'
  - 本书未涵盖的内容
- - '##'
  - Windows Phone
- - '##'
  - 系统需求
- - '###'
  - Mac
- - '###'
  - Windows
- - '###'
  - Xamarin.Forms
- - '##'
  - 勘误
- - '##'
  - 客户支持
- - '##'
  - 联系作者
- - '##'
  - 摘要
- - '##'
  - 致谢
- - '#'
  - 目录
- - '#'
  - 使用 Xamarin 进行移动开发
- - '##'
  - 什么是 Xamarin？
- - '###'
  - 封装的原生 API
- - '###'
  - 开发环境
- - '###'
  - UI 设计器
- - '##'
  - 熟悉的部分：熟悉的 C# 和 .NET 技术
- - '#'
  - 新特性：移动开发技术
- - '##'
  - 移动 UI
- - '###'
  - Xamarin.Forms 与平台特定 UI
- - '###'
  - 移动 UI 设计
- - '####'
  - Xamarin.Forms 自定义渲染器
- - '###'
  - 数据访问层
- - '###'
  - 使用 SQLite 进行本地数据访问
- - '###'
  - 数据绑定
- - '###'
  - 跨平台开发
- - '#'
  - 摘要
- - '#'
  - 构建移动用户界面
- - '##'
  - 理解 Xamarin.Forms
- - '###'
  - Xamarin.Forms 解决方案架构
- - '#'
  - 理解平台特定 UI 方法
- - '##'
  - 平台特定 UI 解决方案架构
- - '##'
  - Xamarin.Android
- - '##'
  - Xamarin.iOS
- - '###'
  - Windows Phone SDK
- - '##'
  - 选择 Xamarin.Forms 或平台特定 UI
- - '###'
  - 通过自定义渲染器同时使用两种方法
- - '##'
  - 探索移动 UI 的构成元素
- - '##'
  - 使用 Xamarin.Forms UI
- - '###'
  - 页面
- - '###'
  - 布局
- - '###'
  - 视图
- - '##'
  - 创建 Xamarin.Forms 解决方案
- - '###'
  - Xamarin.Forms 共享代码
- - '####'
  - 应用程序生命周期方法：`OnStart`、`OnSleep` 和 `OnResume`
- - '####'
  - 使用 `ContentPage` 构建页面
- - '###'
  - Xamarin.Android
- - '###'
  - Xamarin.iOS
- - '###'
  - Windows Phone 应用程序
- - '###'
  - 核心库
- - '###'
  - 设置应用的主页面
- - '##'
  - 添加 Xamarin.Forms 视图
- - '###'
  - 标签视图
- - '###'
  - 使用 `StackLayout` 放置视图
- - '###'
  - 背景颜色和字体颜色
- - '###'
  - 使用字体
- - '###'
  - 使用特定平台的字体
- - '###'
  - 按钮视图
- - '###'
  - 设置视图对齐和大小：`HorizontalOptions` 和 `VerticalOptions`
- - '####'
  - 使用 `LayoutOptions` 进行对齐
- - '####'
  - '`AndExpand` 用空间填充'
- - '###'
  - 用于文本输入的 `Entry` 视图
- - '###'
  - '`BoxView`'
- - '###'
  - Image 视图
- - '####'
  - '`Source` 属性'
- - '####'
  - 本地图像
- - '####'
  - 图像大小设置：`Aspect` 属性
- - '####'
  - 使用 `GestureRecognizer` 使图像可点击
- - '###'
  - 最终确定 `StackLayout`
- - '###'
  - '`ScrollView`'
- - '###'
  - 分配 `ContentPage.Content` 属性
- - '###'
  - 整个页面周围的边距
- - '###'
  - 代码完成：添加 Xamarin.Forms 视图
- - '##'
  - 总结
- - '#'
  - 使用布局进行 UI 设计
- - '##'
  - Xamarin.Forms 布局
- - '##'
  - Android 布局
- - '##'
  - iOS 布局
- - '##'
  - 理解自定义控件
- - '##'
  - 使用 Xamarin.Forms 布局
