name: Pro iOS 5 Augmented reality
name_cn: iOS 5 增强现实高级指南
slug: pro-ios-5-augmented-reality
toc:
- - '#'
  - 目录
- - '##'
  - 关于作者
- - '##'
  - 关于技术审校者
- - '##'
  - 前言
- - '##'
  - 第 1 章 引言
- - '###'
  - 现实世界与网络世界中的增强现实
- - '####'
  - 流行文化
- - '####'
  - 游戏与基于位置的 AR
- - '###'
  - 准备工作就绪
- - '####'
  - 注册 GitHub 账号
- - '###'
  - 从你的电脑访问 GitHub
- - '###'
  - 设置 Xcode 4.2 和你的开发者账户
- - '###'
  - 将 Xcode 项目关联到 GitHub
- - '###'
  - 创建我们的 Xcode 项目
- - '###'
  - 将项目连接到远程仓库
- - '###'
  - 接下来是什么？
- - '####'
  - 定位服务
- - '####'
  - 传感器编程
- - '####'
  - 灯光，摄像机，开拍……
- - '####'
  - 游戏框架
- - '####'
  - 第三方框架
- - '###'
  - 总结
- - '##'
  - 第 2 章 硬件对比
- - '###'
  - 告别旧设备
- - '###'
  - 硬件组件
- - '####'
  - 摄像头支持
- - '#####'
  - 检测摄像头
- - '###'
  - 硬件功能检测
- - '####'
  - 检测定位能力
- - '####'
  - 数字指南针
- - '####'
  - 音频检测
- - '####'
  - 检测视频功能
- - '####'
  - 加速度计与陀螺仪
- - '###'
  - 强制执行硬件要求
- - '###'
  - 本章小结
- - '##'
  - 第 3 章 使用定位服务
- - '###'
  - 您现在的位置
- - '###'
  - 标准定位服务
- - '###'
  - 重大位置变化（Significant-Change Location）服务
- - '###'
  - 地理区域监控（Geographic Region Monitoring）服务
- - '###'
  - 海拔高度
- - '###'
  - 在地图上查看
- - '####'
  - 居中地图与设置显示区域
- - '####'
  - 更改地图类型
- - '###'
  - 为地图添加标注
- - '###'
  - 反向地理编码
- - '###'
  - 本章小结
- - '##'
  - 第 4 章 iOS 传感器
- - '###'
  - 朝向传感器
- - '###'
  - 使用加速计
- - '###'
  - UIAccelerometerDelegate 类
- - '###'
  - 摇动检测
- - '###'
  - 低通滤波
- - '###'
  - 使用陀螺仪
- - '####'
  - 姿态
- - '####'
  - 旋转速率
- - '###'
  - 磁力计
- - '####'
  - 磁力计可用性
- - '####'
  - 校准
- - '####'
  - 看看我们指向何方
- - '###'
  - 处理方向变化
- - '###'
  - 总结
- - '##'
  - 第 5 章 声音与用户反馈
- - '###'
  - 音频数据格式
- - '####'
  - 那么，哪种数据格式适合我？
- - '####'
  - 关于文件格式
- - '####'
  - 比特率与音质
- - '####'
  - 采样率
- - '####'
  - 转换音频以便在 iOS 中使用
- - '#####'
  - 获取媒体文件信息
- - '#####'
  - 转换文件类型
- - '#####'
  - 测试你的新声音
- - '###'
  - 在 iOS 应用中播放声音
- - '###'
  - 系统声音服务
- - '###'
  - AVAudioPlayer 类
- - '###'
  - 试验多个音频播放器
- - '###'
  - 播放位置音效
- - '###'
  - 通过振动提供用户反馈
- - '###'
  - 录制声音
- - '####'
  - 初始化音频录制器
- - '###'
  - 总结
- - '##'
  - 第 6 章 摄像头与视频捕获
- - '###'
  - 快速回顾
- - '###'
  - 照片拍摄
- - '####'
  - 使用故事板
- - '###'
  - 使用相机
- - '###'
  - 以不同格式保存图像
- - '###'
  - 通过电子邮件发送图片
- - '###'
  - 视频捕获
- - '####'
  - 在视频预览上构建基础
- - '####'
  - 构建帧捕获的基础
- - '###'
  - 总结
- - '##'
  - 第 7 章 使用 cocos2D 实现增强现实
- - '###'
  - 概述
- - '###'
  - 安装
- - '####'
  - 安装项目模板
- - '####'
  - 创建项目
- - '###'
  - 增强现实版 Hello World
- - '####'
  - 调整默认视图
- - '####'
  - 添加相机视图
- - '####'
  - 缩放相机视图
- - '###'
  - cocos2D 概念
- - '####'
  - 场景
- - '####'
  - 导演
- - '####'
  - 图层
- - '###'
  - 添加特效
- - '####'
  - 处理触摸事件
- - '####'
  - 视觉效果
- - '####'
  - 添加音效
- - '###'
  - 添加 HUD 层
- - '###'
  - 本章小结
- - '##'
  - 第 8 章 构建 cocos2D AR 游戏
- - '###'
  - 概述
- - '###'
  - 创建项目
- - '####'
  - 相机视图
- - '###'
  - 创建游戏菜单
- - '####'
  - 美术资源
- - '####'
  - 辅助代码目录
- - '###'
  - 完成菜单屏幕
- - '####'
  - 使用 Chipmunk
- - '###'
  - 在 Chipmunk 中创建对象
- - '###'
  - 在 Chipmunk 中创建弹簧关节
- - '###'
  - 添加菜单选项
- - '###'
  - 启用摄像头支持
- - '###'
  - 完成动作层
- - '###'
  - 南瓜登场
- - '###'
  - 结束游戏
- - '###'
  - 总结
- - '##'
  - 第 9 章 第三方增强现实工具包
- - '###'
  - 概览
- - '###'
  - 基于 String 开发
- - '###'
  - String 的基本工作流程
- - '###'
  - 额外功能
- - '###'
  - Unity 集成
- - '###'
  - 高级着色器与 OpenGL 特性
- - '###'
  - Qualcomm SDK
- - '###'
  - 构建我们自己的 QCAR 演示
- - '####'
  - 创建 Xcode 项目
- - '####'
  - EAGLView
- - '####'
  - 重定向 UIView
- - '###'
  - ARKit
- - '###'
  - 总结
- - '##'
  - 第 10 章 使用 OpenGL ES 构建基于标记的 AR 应用
- - '###'
  - 构建标记
- - '####'
  - 我们的标记
- - '####'
  - OpenGL ES
- - '###'
  - 创建项目
- - '###'
  - 添加 String SDK
- - '####'
  - 项目依赖项
- - '###'
  - EAGLView
- - '####'
  - 创建 AR 视图控制器
- - '###'
  - 最终代码更新
- - '###'
  - 总结
- - '##'
  - 第 11 章 构建社交 AR 应用
- - '###'
  - 开始设置
- - '####'
  - 创建 Facebook 应用
- - '####'
  - 克隆 Facebook iOS SDK
- - '###'
  - 词汇课
- - '####'
  - 方位角
- - '####'
  - 修正后的标题
- - '###'
  - 构建应用程序
- - '####'
  - 鸣谢
- - '####'
  - 必需的框架
- - '####'
  - 添加 Facebook iOS SDK
- - '####'
  - 好了，开始吧！
- - '####'
  - 监听传感器更新
- - '###'
  - 存储坐标
- - '###'
  - 添加社交上下文
- - '###'
  - 面向朋友的图形
- - '###'
  - 总结
- - '##'
  - 第 12 章 人脸识别技术
- - '###'
  - 人脸识别的选择
- - '####'
  - OpenCV
- - '####'
  - iOS 5 CIDetector 类
- - '####'
  - Face.com
- - '###'
  - 使用 OpenCV 方法
- - '####'
  - 捕获用于测试的图像
- - '####'
  - Haar 级联
- - '####'
  - OpenCV 与 iOS 图像处理
- - '####'
  - OpenCV 回顾
- - '###'
  - 使用 CIDetector 类方法
- - '####'
  - CIDetector 回顾
- - '###'
  - 使用 Face.com API 方法
- - '####'
  - Faces.detect API 调用
- - '####'
  - 为示例添加 Face.com 支持
- - '####'
  - Face.com API 密钥
- - '####'
  - 添加 Face.com 调用
- - '###'
  - 性能测量
- - '###'
  - 本章小结
- - '##'
  - 第 13 章 构建人脸识别增强现实应用
- - '###'
  - 应用目的
- - '###'
  - 使用的技术
- - '###'
  - 准备工作
- - '####'
  - Face.com
- - '####'
  - cocos2D
- - '####'
  - 设置我们的 Twilio 账户
- - '####'
  - 下载 ASI-HTTP-Request 库
- - '####'
  - JSON-Framework
- - '###'
  - 项目结构
- - '###'
  - 设置主场景
- - '####'
  - 启用摄像头
- - '###'
  - Face.com API
- - '####'
  - 使用 ASI-HTTP-Request 库
- - '####'
  - 创建 POST 请求方法
- - '####'
  - 创建 NSTimer
- - '####'
  - 解析输出
- - '###'
  - 构建 HUD 层
- - '###'
  - 添加 Twilio 调用
- - '###'
  - 总结
- - '##'
  - 索引
- - '###'
  - A, B
- - '###'
  - AR 应用
- - '####'
  - 传感器更新
- - '####'
  - 存储坐标
- - '###'
  - ARKit 工具包
- - '###'
  - 增强现实 (AR)
- - '####'
  - 标记
- - '####'
  - 由 String SDK 驱动
- - '####'
  - QCAR 演示
- - '####'
  - Qualcomm SDK
- - '###'
  - AVAudioPlayer 类
- - '###'
  - AVFoundation 框架
- - '###'
  - 方位角
- - '###'
  - C
- - '###'
  - D
- - '###'
  - E
- - '###'
  - F
- - '###'
  - G
- - '###'
  - H
- - '###'
  - I
- - '###'
  - J, K
- - '###'
  - L
- - '###'
  - M
- - '###'
  - N
- - '###'
  - O
- - '###'
  - P
- - '####'
  - 性能测量
- - '####'
  - 照片捕捉
- - '####'
  - 邮件发送图片
- - '####'
  - 以不同格式保存图像
- - '####'
  - 使用相机
- - '####'
  - 使用故事板
- - '###'
  - Q
- - '####'
  - QCAR 演示
- - '#####'
  - 创建新项目
- - '#####'
  - 创建新的可追踪链接
- - '#####'
  - 创建 Xcode 项目
- - '#####'
  - 下载可追踪链接
- - '#####'
  - EAGLView
- - '#####'
  - 重定向 UIView
- - '####'
  - Qualcomm SDK
- - '###'
  - R
- - '####'
  - MKReverseGeocoder 类
- - '###'
  - S
- - '####'
  - 重要变更位置服务
- - '####'
  - 声音与主动反馈
- - '####'
  - 标准位置服务
- - '####'
  - 故事板
- - '###'
  - T
- - '###'
  - U
- - '###'
  - V, W
- - '###'
  - X, Y, Z
