name: IOS Wow Factor
name_cn: iOS 惊艳效果指南
slug: ios-wow-factor
toc:
- - '#'
  - iOS 惊艳设计
- - '##'
  - 目录
- - '##'
  - 关于作者
- - '##'
  - 关于技术审稿人
- - '#'
  - 引言
- - '##'
  - 在语境中理解 iOS 人机界面指南
- - '###'
  - 回顾往昔
- - '###'
  - 局限性
- - '###'
  - 超越 HIG 指南
- - '###'
  - 解构 iOS 用户体验
- - '####'
  - 隐喻 vs. 实用性
- - '#'
  - iOS 文件系统与交互设计
- - '##'
  - 直接操作
- - '#'
  - 直接操控与比例
- - '##'
  - 手势
- - '##'
  - 隐形按钮
- - '#'
  - 主页按钮的演进
- - '##'
  - iOS 的奇特拓扑结构
- - '#'
  - 空间模型与导航
- - '##'
  - iOS 空间模型与用户体验分析
- - '##'
  - 简单与显而易见
- - '#'
  - 用户界面简洁性的设计原则
- - '##'
  - 核心原则
- - '##'
  - 张力与矛盾
- - '###'
  - 摘要
- - '##'
  - 用户体验差异化与策略
- - '###'
  - 感知与期望的转变
- - '###'
  - 可用性与采纳度
- - '####'
  - 渴望之辩
- - '###'
  - 用户体验策略
- - '###'
  - 定义你的策略
- - '###'
  - 思考差异化
- - '#'
  - 了解你的用户
- - '#'
  - 评估竞争对手
- - '#'
  - 引领市场
- - '###'
  - 摘要
- - '##'
  - 杀手级应用
- - '###'
  - 移动端的重要性
- - '###'
  - 移动体验 vs 便携体验
- - '#'
  - 移动设备的关键用例
- - '##'
  - 1 沟通
- - '###'
  - 一对一沟通
- - '###'
  - 一对多沟通
- - '##'
  - 2 娱乐
- - '##'
  - 3 基于位置的服务
- - '###'
  - 商务
- - '###'
  - 实用性
- - '###'
  - 综合分析与移动相关性
- - '###'
  - 迁移至移动端
- - '###'
  - 总结
- - '##'
  - 利用 iOS 能力实现最佳用户体验
- - '###'
  - 关键技术
- - '####'
  - UIKit
- - '####'
  - Core Graphics
- - '####'
  - Core Animation
- - '####'
  - OpenGL ES
- - '###'
  - 自定义外观设计
- - '###'
  - 通用性考量
- - '###'
  - 原生应用与移动网页考量
- - '###'
  - 摘要
- - '##'
  - 交互建模与新颖概念的创造
- - '###'
  - 什么才算“惊艳”？
- - '#'
  - 交互建模：流程概览
- - '##'
  - 需求定义
- - '##'
  - 用例与场景开发
- - '##'
  - 应用工作流
- - '##'
  - 交互建模
- - '#'
  - 流程细节
- - '##'
  - 构思工作流
- - '#'
  - 构建交互模型
- - '####'
  - 附加问题解决技巧
- - '####'
  - 打造标志性交互
- - '####'
  - 文档记录
- - '###'
  - 案例研究与示例
- - '####'
  - X 公司
- - '###'
  - 公司 X 的需求
- - '#'
  - 应用详情
- - '###'
  - 摘要
- - '####'
  - 惊艳因素
- - '####'
  - 交互建模
- - '###'
  - 控件映射与触摸屏人体工学
- - '####'
  - 对物理性的认知
- - '###'
  - iPhone
- - '###'
  - iPad
- - '###'
  - 基本布局考量
- - '###'
  - 反馈与响应
- - '###'
  - 隐藏控件的提示
- - '###'
  - 总结
- - '##'
  - 易用性与功能自动化
- - '###'
  - 为何需要自动化？
- - '#####'
  - GPS 卫星数据
- - '#####'
  - 三轴加速度计
- - '#####'
  - 陀螺仪传感器
- - '#####'
  - 数字指南针
- - '#####'
  - 距离传感器
- - '#####'
  - 摄像头
- - '#####'
  - 麦克风
- - '###'
  - 何时适用自动化
- - '##'
  - 如何处理功能自动化
- - '###'
  - 总结
- - '##'
  - 索引
- - '###'
  - A, B
- - '###'
  - C, D, E, F
- - '###'
  - G
- - '###'
  - H
- - '###'
  - I, J
- - '###'
  - K, L
- - '###'
  - M, N
- - '###'
  - O, P, Q, R, S
- - '###'
  - T
- - '###'
  - U, V
- - '###'
  - W, X, Y, Z
