name: Data Structures and Algorithms in Swift
name_cn: Swift 数据结构与算法
slug: data-structures-and-algorithms-in-swift
toc:
- - '#'
  - 第1章 数组
- - '##'
  - 引言
- - '##'
  - 数组的主要特性
- - '##'
  - 从数组中检索元素
- - '##'
  - 向数组添加元素
- - '##'
  - 从数组中移除元素
- - '##'
  - 内置函数和属性
- - '###'
  - isEmpty
- - '###'
  - First 和 Last
- - '###'
  - 反转与反向
- - '###'
  - 计数
- - '####'
  - 重要提示
- - '##'
  - 结论
- - '#'
  - 第2章 字典
- - '##'
  - 引言
- - '##'
  - 访问字典中的值
- - '##'
  - 向字典添加/修改值
- - '##'
  - 从字典中移除值
- - '##'
  - 内置函数和属性
- - '###'
  - isEmpty
- - '###'
  - First
- - '###'
  - Count
- - '###'
  - Keys
- - '##'
  - 结论
- - '#'
  - 第3章 集合
- - '##'
  - 访问、添加和删除集合中的元素
- - '###'
  - 访问元素
- - '###'
  - 添加元素
- - '###'
  - 删除元素
- - '##'
  - 集合运算
- - '###'
  - 比较运算
- - '####'
  - 并集
- - '####'
  - 交集
- - '####'
  - 差集
- - '####'
  - 对称差集
- - '##'
  - 成员关系和相等性运算
- - '###'
  - 集合相等
- - '###'
  - 集合成员关系
- - '##'
  - 总结
- - '#'
  - 第4章 栈
- - '##'
  - 在 Swift 中使用栈
- - '##'
  - 栈结构
- - '##'
  - 栈扩展
- - '##'
  - 总结
- - '#'
  - 第5章 队列
- - '##'
  - 实现
- - '##'
  - 结论
- - '#'
  - 第6章 链表
- - '##'
  - 实现
- - '###'
  - 节点
- - '##'
  - 单向链表
- - '##'
  - 向链表添加新值
- - '###'
  - 追加
- - '###'
  - 插入
- - '##'
  - 从链表中移除值
- - '###'
  - removeLast
- - '###'
  - remove(at:)
- - '##'
  - 双向链表
- - '###'
  - 追加元素
- - '###'
  - 移除节点方法
- - '###'
  - remove(at:)
- - '##'
  - 本章小结
- - '#'
  - 第7章 哈希表
- - '##'
  - 创建哈希表
- - '###'
  - 从哈希表中检索数据
- - '###'
  - 更新哈希表中的值
- - '###'
  - 从哈希表中删除值
- - '##'
  - 总结
- - '#'
  - 第8章 树
- - '##'
  - 创建
- - '###'
  - 插入
- - '###'
  - 搜索数据
- - '##'
  - 结论
- - '#'
  - 第9章 字典树数据结构
- - '##'
  - 为什么需要 Trie？
- - '##'
  - 工作原理
- - '##'
  - 实现
- - '###'
  - 插入
- - '###'
  - 查询
- - '####'
  - 移除
- - '##'
  - 结论
- - '#'
  - 第10章 二叉树
- - '##'
  - 二叉树入门
- - '###'
  - 二叉树的属性
- - '###'
  - 二叉树的类型
- - '##'
  - 实现
- - '##'
  - 树的遍历（又称树搜索）
- - '###'
  - 中序遍历
- - '###'
  - 前序遍历
- - '###'
  - 后序遍历
- - '##'
  - 总结
- - '#'
  - 第11章 二叉搜索树
- - '##'
  - 实现
- - '###'
  - 插入
- - '###'
  - 搜索
- - '##'
  - 示例
- - '###'
  - 删除
- - '####'
  - 删除叶子节点
- - '####'
  - 删除只有一个子节点的节点
- - '####'
  - 删除拥有两个子节点的节点
- - '##'
  - 本章小结
- - '#'
  - 第12章 红黑树
- - '###'
  - 红黑树的属性
- - '###'
  - 实现
- - '###'
  - 旋转
- - '###'
  - 插入
- - '###'
  - 红黑树插入
- - '###'
  - 删除
- - '##'
  - 结论
- - '#'
  - 第13章 大 O 表示法
- - '###'
  - 时间复杂度
- - '###'
  - 空间复杂度
- - '##'
  - 忽略常数项与非主导项
- - '##'
  - 如何计算复杂度？
- - '##'
  - 加法 vs. 乘法
- - '##'
  - 平摊时间
- - '###'
  - 对数时间运行时间
- - '###'
  - 递归运行时间
- - '##'
  - 结论
- - '#'
  - 第14章 排序算法
- - '##'
  - 冒泡排序
- - '###'
  - 实现
- - '##'
  - 选择排序
- - '###'
  - 实现
- - '##'
  - 插入排序
- - '###'
  - 实现
- - '##'
  - 归并排序
- - '###'
  - 优点
- - '###'
  - 缺点
- - '###'
  - 实现
- - '##'
  - 快速排序
- - '###'
  - 实现
- - '###'
  - 基准选择
- - '##'
  - 总结
- - '#'
  - 第15章 搜索算法
- - '##'
  - 线性搜索
- - '###'
  - 实现
- - '##'
  - 二分搜索
- - '###'
  - 实现
- - '##'
  - 结论
- - '#'
  - 第16章 图算法
- - '##'
  - 有向图
- - '##'
  - 无向图
- - '##'
  - 加权图
- - '##'
  - 广度优先搜索
- - '###'
  - 实现
- - '##'
  - 深度优先搜索 (DFS)
- - '###'
  - 实现
- - '##'
  - 迪杰斯特拉算法
- - '###'
  - 实现
- - '###'
  - 算法
- - '##'
  - 总结
- - '#'
  - 第17章 选择最佳算法
- - '##'
  - 排序算法
- - '###'
  - 冒泡排序
- - '###'
  - 选择排序
- - '###'
  - 插入排序
- - '###'
  - 归并排序
- - '###'
  - 快速排序
- - '##'
  - 搜索算法
- - '###'
  - 线性搜索与二分搜索
- - '##'
  - 图搜索算法 (GSA)
- - '###'
  - 广度优先搜索 (BFS) 与深度优先搜索 (DFS)
- - '##'
  - 迪杰斯特拉算法
- - '#'
  - 索引
- - '##'
  - 索引：A
- - '##'
  - 索引：B, C
- - '##'
  - 索引：D, E
- - '##'
  - 索引：F
- - '##'
  - 索引：G
- - '##'
  - 索引：H
- - '##'
  - 索引：I, J, K
- - '##'
  - 索引：L, M, N, O
- - '##'
  - 索引：P
- - '##'
  - 索引：Q
- - '##'
  - 索引：R
- - '##'
  - 索引：S
- - '##'
  - 索引：T
- - '##'
  - 索引：U, V
- - '##'
  - 索引：W, X, Y, Z
