name: Learn Lua for iOS Game Development
name_cn: iOS 游戏开发的 Lua 入门指南
slug: learn-lua-for-ios-game-development
toc:
- - '#'
  - 学习 Lua 语言进行 iOS 游戏开发
- - '##'
  - 内容概览
- - '#'
  - 第 1 章：Lua 入门
- - '##'
  - 什么是 Lua？
- - '##'
  - Lua 的历史
- - '##'
  - Lua 时间线
- - '##'
  - 开始使用 Lua
- - '###'
  - MVC 模式与架构
- - '###'
  - 安装 Lua
- - '####'
  - 在线 Lua Shell
- - '####'
  - Windows、Mac OS X 和 *nix
- - '####'
  - iOS
- - '##'
  - Lua 的特性
- - '###'
  - 变量
- - '###'
  - Hello World，变量方式
- - '###'
  - 字符串
- - '###'
  - 数值
- - '###'
  - 值和类型
- - '##'
  - Lua 基础
- - '###'
  - '`nil`'
- - '###'
  - '`boolean`'
- - '###'
  - '`number`'
- - '###'
  - '`string`'
- - '###'
  - '`function`'
- - '###'
  - '`userdata`'
- - '###'
  - '`thread`'
- - '###'
  - '`table`'
- - '##'
  - 代码块和作用域
- - '##'
  - Lua 运算符
- - '###'
  - 算术运算符
- - '###'
  - 关系运算符
- - '###'
  - 逻辑运算符
- - '###'
  - 其他运算符
- - '##'
  - 总结
- - '#'
  - Lua 库
- - '##'
  - 基础函数
- - '###'
  - '`assert ( v [, message] )`'
- - '###'
  - '`collectgarbage ( [opt [,arg]] )`'
- - '###'
  - '`dofile ( [filename] )`'
- - '###'
  - '`error ( message [,level] )`'
- - '###'
  - '`_G`'
- - '###'
  - '`getfenv ( [f] )`'
- - '###'
  - '`getmetatable ( object )`'
- - '###'
  - '`ipairs ( t )`'
- - '###'
  - '`load ( func [,chunkname] )`'
- - '###'
  - '`loadstring ( string [,chunkname] )`'
- - '###'
  - '`next ( table [,index] )`'
- - '###'
  - '`pairs ( t )`'
- - '###'
  - '`pcall ( f, arg1, … )`'
- - '###'
  - '`print( … )`'
- - '###'
  - '`rawequal ( v1, v2 )`'
- - '###'
  - '`rawget ( table, index )`'
- - '###'
  - '`rawset ( table, index, value )`'
- - '###'
  - '`select ( index, … )`'
- - '###'
  - '`setfenv ( f, table )`'
- - '###'
  - '`setmetatable ( table, metatable )`'
- - '###'
  - '`tonumber( e [,base] )`'
- - '###'
  - '`tostring ( e )`'
- - '###'
  - '`type ( v )`'
- - '##'
  - 系统库
- - '##'
  - 表函数
- - '##'
  - 操作系统函数
- - '##'
  - 表：快速概览
- - '###'
  - 作为数组的表
- - '###'
  - 作为关联数组的表
- - '##'
  - 函数：进阶探讨
- - '###'
  - 作为对象的表
- - '###'
  - '`.` 和 `:` 的区别'
- - '##'
  - 总结
- - '#'
  - 第 3 章：文件操作
- - '##'
  - 隐式函数
- - '###'
  - '`io.close ( [file] )`'
- - '###'
  - '`io.flush ( )`'
- - '###'
  - '`io.input ( [file] )`'
- - '###'
  - '`io.lines ( [filename] )`'
- - '###'
  - '`io.open ( filename [,mode] )`'
- - '###'
  - '`io.output ( [file] )`'
- - '##'
  - Lua 文件 I/O 函数
- - '###'
  - '`io.read ( … )`'
- - '###'
  - '`io.tmpfile ( )`'
- - '###'
  - '`io.type ( obj )`'
- - '###'
  - '`io.write ( … )`'
- - '##'
  - 显式函数
- - '###'
  - '`file:close ( )`'
- - '###'
  - '`file:flush ( )`'
- - '###'
  - '`file:lines ( )`'
- - '###'
  - '`file:read ( [format] )`'
- - '###'
  - '`file:seek ( [whence] [, offset] )`'
- - '###'
  - '`file:setvbuf (mode [, size] )`'
- - '###'
  - '`file:write( … )`'
- - '##'
  - 文件 I/O 在游戏开发中的应用
- - '###'
  - 保存变量
- - '###'
  - 获取数据
- - '###'
  - 代码工作原理
- - '###'
  - 潜在问题
- - '###'
  - 将数据保存到变量
- - '####'
  - 代码工作原理
- - '###'
  - 回到数据的保存与加载
- - '###'
  - 潜在问题
- - '###'
  - 将数据写入文件
- - '###'
  - 保存表
- - '###'
  - 动态变量
- - '###'
  - 本章小结
- - '#'
  - 第 4 章：使用 Lua 进行数学运算
- - '##'
  - Lua 数学运算简介
- - '###'
  - '`math.abs (x)`'
- - '###'
  - '`math.acos (x)`'
- - '###'
  - '`math.asin (x)`'
- - '###'
  - '`math.atan (x)`'
- - '###'
  - '`math.atan2 (y,x)`'
- - '###'
  - '`math.ceil (x)`'
- - '###'
  - '`math.cos (x)`'
- - '###'
  - '`math.cosh (x)`'
- - '###'
  - '`math.deg (x)`'
- - '###'
  - '`math.exp (x)`'
- - '###'
  - '`math.floor (x)`'
- - '###'
  - '`math.fmod (x)`'
- - '###'
  - '`math.frexp (x)`'
- - '###'
  - '`math.huge`'
- - '###'
  - '`math.ldexp (m, e)`'
- - '###'
  - '`math.log (x)`'
- - '###'
  - '`math.log10 (x)`'
- - '##'
  - 数学运算在游戏开发中的实际应用
- - '###'
  - 赋值
- - '###'
  - 递增与递减
- - '###'
  - 引入点
- - '###'
  - 条件分支
- - '###'
  - 抛硬币
- - '###'
  - 掷骰子
- - '##'
  - 哪里有蛇？哪里有梯子？
- - '##'
  - 关于棋盘的一些事实
- - '##'
  - 将其转换为代码
- - '##'
  - 移动角色
- - '##'
  - 脱离屏幕
- - '##'
  - 判定角色与对象的距离
- - '##'
  - 布尔运算
- - '##'
  - 函数基础与字符串处理
- - '##'
  - 总结
- - '#'
  - 第 5 章：字符串
- - '##'
  - 什么是字符串？
- - '###'
  - '`string.byte ( s [,i [,j ] ] )`'
- - '###'
  - '`string.char (. . .)`'
- - '###'
  - '`string.dump ( function )`'
- - '###'
  - '`string.find ( s, pattern [,init [,plain] ] )`'
- - '###'
  - '`string.format ( formatString, . . . )`'
- - '###'
  - '`string.gmatch ( s, pattern )`'
- - '###'
  - '`string.gsub ( s, pattern, repl [,n] )`'
- - '###'
  - '`string.len ( s )`'
- - '###'
  - '`string.lower ( s )`'
- - '###'
  - '`string.match ( s, patterns [,init] )`'
- - '###'
  - '`string.rep ( s, n )`'
- - '###'
  - 模式
- - '####'
  - 字符类
- - '####'
  - 模式项
- - '####'
  - 模式
- - '####'
  - 捕获
- - '###'
  - 使用字符串函数
- - '####'
  - 将字符串转换为大写
- - '####'
  - 将字符串转换为小写
- - '####'
  - 将字符串转换为首字母大写
- - '####'
  - 填充字符串
- - '####'
  - CSV 功能
- - '#####'
  - 将 CSV 字符串转换为表
- - '#####'
  - 从表转换为 CSV
- - '#####'
  - 转义 CSV
- - '##'
  - 使用千位分隔符格式化数字
- - '##'
  - 字母频率统计
- - '##'
  - 检测字符串是否为回文
- - '##'
  - 分割字符串
- - '##'
  - 关卡管理
- - '##'
  - 总结
- - '#'
  - 第 6 章：线程
- - '##'
  - 协程
- - '###'
  - 协程函数
- - '####'
  - coroutine.create ( f )
- - '####'
  - coroutine.resume ( co [, val1, …] )
- - '####'
  - coroutine.running()
- - '####'
  - coroutine.status(co)
- - '####'
  - coroutine.wrap(f)
- - '####'
  - coroutine.yield(...)
- - '###'
  - 创建新协程
- - '###'
  - 协程与恢复执行
- - '###'
  - 进度条
- - '###'
  - 游戏循环
- - '###'
  - 处理表
- - '##'
  - 自定义元表
- - '###'
  - '`__index`'
- - '###'
  - '`__newindex`'
- - '###'
  - '`__mode`'
- - '###'
  - '`__call`'
- - '###'
  - '`__metatable`'
- - '###'
  - '`__tostring`'
- - '###'
  - '`__gc`'
- - '###'
  - '`__unm`'
- - '###'
  - '`__add`'
- - '###'
  - 一个实用的例子
- - '##'
  - 面向对象的 Lua
- - '##'
  - 但对象是什么？
- - '##'
  - 总结
- - '#'
  - 第 7 章：技巧与窍门
- - '##'
  - 通用 Lua 函数
- - '###'
  - 使用 `printf` 函数
- - '###'
  - 计算表中的元素数量
- - '###'
  - 使用 `isEmpty`
- - '###'
  - 查找元素的索引
- - '###'
  - 判断表是否为数组
- - '###'
  - 设置默认值
- - '###'
  - 复制表
- - '###'
  - 执行深拷贝
- - '##'
  - 复制数组部分
- - '##'
  - 复制非数组部分
- - '##'
  - 合并两个表
- - '##'
  - 判断表中是否存在某个值
- - '##'
  - 查找两个表之间的差异
- - '##'
  - 将返回值作为表获取
- - '##'
  - 对表元素进行排序
- - '##'
  - 确定表中某个项目的出现频率
- - '##'
  - 将数字转换为罗马数字
- - '##'
  - 创建链表
- - '##'
  - 扩展标记化变量
- - '##'
  - 给字符串补零
- - '##'
  - 将月份获取为字符串
- - '##'
  - 像数组一样访问字符串
- - '##'
  - 在一维或二维空间中计算两点之间的距离
- - '##'
  - 计算两点之间的角度
- - '##'
  - 将数字保持在给定范围内
- - '##'
  - 执行线性插值
- - '##'
  - 获取值的符号
- - '##'
  - 碰撞检测
- - '###'
  - 使用`isPointInRect`
- - '###'
  - 使用`pointInCircle`
- - '###'
  - 确定一个矩形是否在另一个矩形内
- - '###'
  - 确定一个圆是否在另一个圆内
- - '###'
  - 检测矩形重叠
- - '###'
  - 检测圆形重叠
- - '###'
  - 判断圆形是否与矩形重叠
- - '###'
  - 使用 `pointInTriangle`
- - '###'
  - 使用 `pointInPolygon`
- - '##'
  - 其他通用函数
- - '###'
  - 比较布尔值
- - '###'
  - 将 C/Java 风格循环转换为 Lua 循环
- - '###'
  - 对物体应用摩擦力
- - '###'
  - 模拟弹簧玩偶盒
- - '###'
  - 使用正弦滚屏
- - '###'
  - 在棋盘上放置不与同行或同列其他棋子重叠的棋子
- - '###'
  - 使用数组通过模板输出大量文本
- - '###'
  - 参数处理
- - '####'
  - 固定参数
- - '####'
  - 可变参数
- - '####'
  - 可变命名参数
- - '###'
  - 使用可变参数
- - '###'
  - 解析传递的参数列表
- - '##'
  - 创建只读表
- - '##'
  - 实现栈
- - '##'
  - 在参数和表之间转换
- - '##'
  - 二维向量
- - '##'
  - 总结
- - '#'
  - 第 8 章：Corona SDK
- - '##'
  - 设置 Corona SDK
- - '##'
  - Corona SDK 的工作原理
- - '##'
  - Corona SDK 的 Hello World
- - '###'
  - 图形版本
- - '###'
  - 在屏幕上显示 Hello World
- - '###'
  - 在设备上显示 Hello World
- - '##'
  - 超越 Hello World：在屏幕上创建一个矩形
- - '##'
  - 组
- - '##'
  - 图像
- - '###'
  - 要加载图像，我们使用 `display` 命名空间中的 `newImage` 函数：
- - '##'
  - 基于事件的处理
- - '###'
  - 输入：触摸
- - '##'
  - 物理
- - '##'
  - 使用 `enterFrame` 实现动画
- - '##'
  - 回到生命值条
- - '##'
  - 使用过渡函数
- - '##'
  - 从屏幕上移除对象
- - '##'
  - 创建声音
- - '##'
  - 游戏音频与视频处理
- - '###'
  - 让我们制造一些噪音
- - '###'
  - 操控声音
- - '###'
  - 使用 OpenAL 音频
- - '####'
  - 设置音量
- - '###'
  - 使用视频
- - '##'
  - 创建电梯
- - '##'
  - 缩放以查看全景
- - '##'
  - 更多事件
- - '##'
  - 自定义事件
- - '##'
  - 事件的替代方案
- - '##'
  - 使用地图
- - '##'
  - 互联网浏览器
- - '##'
  - 没有什么能够永恒
- - '##'
  - 企业版
- - '##'
  - 总结
- - '#'
  - 第 9 章：Gideros Studio
- - '##'
  - 许可证
- - '##'
  - 安装 Gideros Studio
- - '##'
  - 包含内容
- - '##'
  - 设置许可证
- - '##'
  - 第一步
- - '##'
  - 运行代码
- - '##'
  - 配置项目
- - '##'
  - 架构
- - '##'
  - Gideros Studio 架构
- - '###'
  - Gideros 引擎
- - '###'
  - Hello Birdie
- - '###'
  - 对齐图像
- - '###'
  - 组
- - '###'
  - 显示文本
- - '###'
  - 绘制形状
- - '####'
  - 线条
- - '####'
  - 矩形
- - '####'
  - 填充形状
- - '###'
  - 绘制其他形状
- - '###'
  - Application 对象
- - '####'
  - 保持设备唤醒
- - '####'
  - 方向
- - '####'
  - 缩放
- - '###'
  - 添加音效
- - '##'
  - Gideros 声音、事件与定时器
- - '###'
  - 事件
- - '####'
  - 触摸事件
- - '####'
  - 进入帧事件
- - '####'
  - 系统事件
- - '###'
  - 定时器
- - '####'
  - 自定义事件
- - '####'
  - 移除事件
- - '###'
  - 查询事件
- - '###'
  - 动画
- - '###'
  - 网络与互联网
- - '###'
  - GPS 与罗盘
- - '###'
  - 加速度计
- - '###'
  - 陀螺仪
- - '###'
  - 物理引擎
- - '###'
  - 插件
- - '##'
  - 总结
- - '#'
  - 第 10 章：Moai
- - '##'
  - Moai 框架概述
- - '##'
  - 什么是 Moai？
- - '##'
  - 获取 Moai
- - '##'
  - Moai SDK
- - '##'
  - Hello Moai
- - '##'
  - 显示文本
- - '###'
  - TrueType 字体
- - '###'
  - 位图字体
- - '###'
  - 文本属性
- - '###'
  - 文本样式
- - '###'
  - 对齐文本
- - '###'
  - 文本动画
- - '##'
  - 绘制矢量图元
- - '###'
  - 绘制线条
- - '###'
  - 绘制矩形
- - '##'
  - 绘制填充矩形
- - '##'
  - 绘制圆形
- - '##'
  - 绘制填充圆形
- - '##'
  - 绘制椭圆
- - '##'
  - 绘制填充椭圆
- - '##'
  - 绘制多边形
- - '##'
  - 绘制点
- - '##'
  - 绘制属性
- - '###'
  - 颜色
- - '###'
  - 线宽
- - '###'
  - 点大小
- - '##'
  - 绘制图像
- - '##'
  - 绘制自定义图像
- - '##'
  - 加载图像
- - '##'
  - 复制图像
- - '##'
  - MOAITimer 事件
- - '##'
  - 线程（Threading）
- - '##'
  - 组（Groups）
- - '##'
  - 处理输入（Handling Input）
- - '###'
  - 键盘事件
- - '###'
  - 鼠标事件
- - '##'
  - 使用 JSON
- - '##'
  - 使用 Base64
- - '##'
  - 压缩数据
- - '##'
  - 物理
- - '###'
  - Box2D 物理
- - '###'
  - Chipmunk Physics
- - '##'
  - Moai Cloud
- - '###'
  - 创建 Web 服务
- - '###'
  - 使用 Web 服务
- - '##'
  - 总结
- - '#'
  - 第 11 章：LÖVE
- - '##'
  - 架构
- - '##'
  - 安装 LÖVE
- - '##'
  - 运行 LÖVE
- - '##'
  - 回调函数
- - '###'
  - '`love.load()`'
- - '###'
  - '`love.update(dt)`'
- - '###'
  - '`love.draw()`'
- - '###'
  - '`love.mousepressed(x, y, button)`'
- - '###'
  - '`love.mousereleased(x, y, button)`'
- - '###'
  - '`love.keypressed(key, unicode)`'
- - '###'
  - '`love.keyreleased(key)`'
- - '##'
  - LÖVE 函数与命名空间
- - '###'
  - LÖVE 命名空间
- - '####'
  - '`love.audio`'
- - '####'
  - '`love.event`'
- - '####'
  - '`love.filesystem`'
- - '####'
  - '`love.font`'
- - '####'
  - '`love.graphics`'
- - '####'
  - '`love.image`'
- - '####'
  - '`love.joystick`'
- - '####'
  - '`love.mouse`'
- - '####'
  - '`love.physics`'
- - '####'
  - '`love.sound`'
- - '####'
  - '`love.thread`'
- - '####'
  - '`love.timer`'
- - '##'
  - 图形模块
- - '###'
  - 图像
- - '##'
  - 移动对象
- - '###'
  - 使用键盘和鼠标控制图像
- - '###'
  - 基本移动逻辑
- - '###'
  - 活动窗口
- - '###'
  - 使用键盘移动
- - '###'
  - 旋转玩家
- - '##'
  - 绘制基本图形
- - '###'
  - 线条
- - '###'
  - 矩形
- - '###'
  - 圆形
- - '###'
  - 多边形
- - '###'
  - 四边形
- - '##'
  - 应用程序设置 – `conf.lua`
- - '##'
  - 创建效果
- - '##'
  - 物理引擎
- - '##'
  - 显示文本
- - '##'
  - 着色器
- - '##'
  - 制作声音
- - '##'
  - 示例游戏代码
- - '##'
  - 摘要
- - '#'
  - 第 12 章：Codea
- - '##'
  - 获取 Codea
- - '##'
  - Codea 架构
- - '##'
  - Hello World
- - '##'
  - 参数
- - '##'
  - 使用 Codea 绘图
- - '##'
  - Codea 绘制基础
- - '###'
  - 方向
- - '###'
  - 系统键盘
- - '###'
  - 绘制模式
- - '###'
  - 背景颜色
- - '###'
  - 笔颜色
- - '###'
  - 填充颜色
- - '###'
  - 线宽
- - '###'
  - 绘制线条
- - '###'
  - 抗锯齿
- - '###'
  - 绘制圆和椭圆
- - '###'
  - 绘制矩形
- - '####'
  - 矩形的绘制模式
- - '###'
  - 绘制文本
- - '####'
  - 绘制模式
- - '####'
  - 文本对齐
- - '####'
  - 文本换行
- - '####'
  - 更改字体
- - '####'
  - 更改字号
- - '###'
  - 显示图像
- - '####'
  - 离屏绘制
- - '####'
  - 将精灵加载到图像中
- - '####'
  - 保存图像
- - '####'
  - 保存数据
- - '##'
  - 无颜色绘制
- - '###'
  - '`noFill`'
- - '###'
  - '`noStroke`'
- - '###'
  - '`noTint`'
- - '##'
  - Codea 文档排版
- - '###'
  - 变换函数
- - '####'
  - '`rotate`'
- - '####'
  - '`scale`'
- - '####'
  - '`translate`'
- - '###'
  - 录制视频
- - '###'
  - 触摸
- - '####'
  - 使用触摸绘图
- - '###'
  - 多点触控
- - '###'
  - 制作声音
- - '###'
  - iOS 硬件
- - '###'
  - 下载数据
- - '###'
  - 显示网页
- - '###'
  - 物理引擎
- - '###'
  - 向量数学
- - '####'
  - '`angleBetween`'
- - '####'
  - '`cross`'
- - '####'
  - '`dist`'
- - '####'
  - '`distSqr`'
- - '####'
  - '`dot`'
- - '####'
  - '`len`'
- - '####'
  - '`lenSqr`'
- - '####'
  - '`normalize`'
- - '####'
  - '`rotate`'
- - '####'
  - '`rotate90`'
- - '##'
  - 总结
- - '#'
  - 第 13 章：第三方库与工具
- - '##'
  - Particle Candy
- - '###'
  - 示例代码
- - '##'
  - Text Candy
- - '###'
  - 示例代码
- - '##'
  - Widget Candy
- - '###'
  - 示例代码
- - '##'
  - Corona AutoLAN
- - '###'
  - 示例代码
- - '##'
  - Corona Profiler
- - '##'
  - Director
- - '##'
  - Lime
- - '##'
  - RapaNui
- - '##'
  - Gideros Illustrator (SVG 库)
- - '##'
  - TNT 粒子库
- - '##'
  - Busted
- - '##'
  - Moses
- - '##'
  - Allen
- - '##'
  - BhWax
- - '##'
  - 总结
- - '#'
  - 第 14 章：第三方应用程序
- - '##'
  - 集成开发环境（IDEs）
- - '###'
  - Glider
- - '##'
  - IDE 与文本编辑器概览
- - '###'
  - CoronaComplete
- - '###'
  - Lua Studio
- - '###'
  - ZeroBrane Studio
- - '##'
  - 文本编辑器
- - '###'
  - Notepad++
- - '###'
  - TextMate
- - '###'
  - TextWrangler
- - '###'
  - BBEdit
- - '###'
  - Sublime Text 2
- - '###'
  - Textastic 代码编辑器
- - '##'
  - 代码片段收集器
- - '###'
  - CodeBox
- - '###'
  - Code Collector Pro
- - '##'
  - 版本控制
- - '##'
  - 位图编辑器
- - '###'
  - Pixen
- - '###'
  - GraphicsGale
- - '###'
  - Pixelmator
- - '###'
  - Axialis IconWorkshop
- - '###'
  - Inkscape
- - '###'
  - Paint.NET
- - '###'
  - iConify
- - '##'
  - 精灵动画与关卡创建工具
- - '###'
  - SpriteHelper
- - '###'
  - LevelHelper
- - '###'
  - Tiled
- - '###'
  - TexturePacker
- - '###'
  - PhysicsEditor
- - '###'
  - Particle Designer
- - '###'
  - Glyph Designer
- - '###'
  - Spriteloq
- - '###'
  - Zoë
- - '###'
  - TNT Animator Studio
- - '##'
  - 声音工具
- - '###'
  - Audacity
- - '###'
  - Bfxr
- - '###'
  - NodeBeat
- - '##'
  - 总结
- - '#'
  - 第 15 章：示例源代码
- - '##'
  - 直升机救援
- - '###'
  - 图形设计
- - '###'
  - 环境设置
- - '###'
  - 让直升机飞行
- - '###'
  - 使用加速计
- - '###'
  - 移动直升机
- - '###'
  - 制作声音
- - '###'
  - 射击子弹
- - '###'
  - 移动子弹
- - '###'
  - 生成敌人
- - '###'
  - 移动场景对象
- - '###'
  - 失去一条命
- - '###'
  - 增添一些色彩
- - '###'
  - 显示信息
- - '###'
  - 游戏结束；再来一次？
- - '###'
  - 碰撞
- - '###'
  - 射击飞机和气球
- - '###'
  - 营救幸存者与加油
- - '###'
  - 整合所有代码
- - '##'
  - 总结
- - '#'
  - 附录
- - '##'
  - 关于作者
- - '##'
  - 关于技术审校
- - '##'
  - 致谢
- - '##'
  - 系统库，Lua
- - '##'
  - T、U、V
