name: Build Mobile Apps with SwiftUI and Firebase
name_cn: SwiftUI 和 Firebase 移动应用构建指南
slug: build-mobile-apps-with-swiftui-and-firebase
toc:
- - '#'
  - 1. SwiftUI 简介
- - '##'
  - Xcode 界面导览
- - '###'
  - 1 – 左侧标签页显示了项目包含的所有文件。默认情况下，会有三个主要文件夹：一个包含应用的入口点，名为 `DiscoverApp`，类似于 Web 开发中的
    `index.html`。`ContentView` 是默认提供的，它是一个用于呈现用户界面的起始模板。最后还有一个 `Assets` 文件夹，你可以用来存储图片和视频；这非常实用，因为它能减小你上传的任何素材文件的体积。此外，这个文件夹还会包含你的应用图标。
- - '###'
  - 2 – 第二个区域正是我们要工作的地方！从这里我们可以编写代码，并查看文件的内容。另外，在 SwiftUI 中，每个 SwiftUI 视图都附带一个名为 `Preview`
    的结构体（在绿色方框内）。它负责在右侧向你呈现屏幕预览。如果你删除这段代码，将无法使用 Canva 功能。
- - '###'
  - 3 – Canva 于 2019 年引入；它是一种便捷的方式，可以让你实时看到正在构建的用户界面。从这里，你可以观察到当你在代码中进行更改时，应用的外观会如何变化。
- - '###'
  - 4 – 右侧标签页将显示你当前正在查看的文件的信息。在这里，你可以重命名文件、更改编程语言，甚至可以编辑一些用户界面元素，例如字体和元素间距（如果你点击顶部的最后一个按钮进行导航）。请注意，在本书中，我们不会经常用到这个部分。
- - '##'
  - SwiftUI 的不同之处
- - '#'
  - 使用 SwiftUI 编写代码
- - '##'
  - 总结
- - '#'
  - Firebase 简介
- - '#'
  - 什么是 Firebase？
- - '#'
  - 设置 Firebase 账户和项目
- - '##'
  - Firebase 操作指南
- - '##'
  - 将你的 iOS 应用连接到 Firebase
- - '##'
  - 你可能想知道这个文件是做什么用的
- - '#'
  - 总结
- - '#'
  - 3. 体验 Firestore
- - '##'
  - 介绍 MVVM 设计模式
- - '##'
  - 创建 Firestore 数据
- - '##'
  - 从 Firestore 读取数据
- - '##'
  - 在视图之间传递数据
- - '##'
  - 从 Firestore 更新数据
- - '##'
  - 从 Firestore 删除数据
- - '##'
  - 总结
- - '#'
  - 4. 使用 Firebase Auth 进行用户认证
- - '##'
  - 设置 Firebase 身份验证
- - '##'
  - 管理用户会话
- - '##'
  - 使用邮箱和密码注册
- - '###'
  - 忘记密码怎么办？
- - '##'
  - 保护 Firestore 数据库
- - '#'
  - 安全规则
- - '#'
  - 总结
- - '#'
  - 5. 高级 Firestore 使用
- - '##'
  - 介绍我们的新项目
- - '###'
  - 我们为什么要创建一个新的 Firebase 项目？
- - '##'
  - 使用 Async/Await 调用后端
- - '##'
  - 总结
- - '#'
  - 6. 使用 Firebase Storage 管理图片
- - '##'
  - 访问 iPhone 相机与相册
- - '##'
  - 将图片上传至 Firebase Storage
- - '###'
  - 使用 Firestore 集成大型文档
- - '###'
  - 总结
- - '##'
  - 通过 Apple 认证
- - '#'
  - 配置项目并集成「通过 Apple 登录」
- - '##'
  - 如何在 Firebase 中实现？
- - '###'
  - 重要说明
- - '##'
  - 在 Xcode 中的配置
- - '##'
  - 在 Firebase 控制台中的配置
- - '#'
  - 集成「通过 Apple 登录」
- - '##'
  - 总结
- - '#'
  - 8. 无需编码即可添加功能
- - '#'
  - 探索 Firebase Extension
- - '##'
  - 使用 Analytics 跟踪应用使用情况
- - '##'
  - 保护我们的数据库
- - '##'
  - 总结
- - '##'
  - 索引
