name: iOS eCommerce App Development with Parse
name_cn: iOS Parse 电子商务应用开发
slug: ios-ecommerce-app-development-with-parse
toc:
- - '#'
  - 简介
- - '##'
  - 目标读者
- - '##'
  - 你将学到什么
- - '##'
  - iOS SDK 版本及示例源代码
- - '#'
  - 目录
- - '#'
  - 第 1 章：需求
- - '##'
  - 1. 需求
- - '###'
  - 常见的应用需求
- - '####'
  - Apple Store 应用
- - '#####'
  - 精选
- - '#####'
  - 商店
- - '#####'
  - 门店
- - '#####'
  - 账户
- - '######'
  - 收藏夹
- - '######'
  - 订单
- - '#####'
  - 账户设置
- - '######'
  - 更多
- - '#####'
  - 购物车
- - '###'
  - 必备功能列表
- - '###'
  - 预备知识
- - '####'
  - iOS 开发者计划
- - '####'
  - 开发环境
- - '###'
  - 示例 iPhone 应用：Beauty & Me
- - '###'
  - 总结
- - '#'
  - 第 2 章：规划与构建原型
- - '##'
  - 2. 规划与构建原型
- - '###'
  - 设计用户体验
- - '####'
  - 商店
- - '####'
  - 我的账户
- - '####'
  - 购物袋
- - '####'
  - 注册或登录
- - '###'
  - 整合实现
- - '###'
  - 总结
- - '#'
  - 第 3 章：Parse 基础
- - '##'
  - 3. 解析基础
- - '###'
  - 与对象交互：`PFObject`
- - '###'
  - 检索数据：`PFQuery`
- - '###'
  - 创建对象间的关系
- - '####'
  - 使用指针
- - '####'
  - 使用数组
- - '####'
  - 使用 Parse 关系
- - '####'
  - 连接表
- - '###'
  - 介绍特殊解析对象：PFUser
- - '###'
  - 加载和显示图像：PFImageView
- - '###'
  - 在单元格中显示图像：PFTableViewCell
- - '###'
  - 查询与展示数据：`PFQueryTableViewController`
- - '###'
  - 本章小结
- - '#'
  - 第 4 章：Parse 项目设置
- - '##'
  - 4. Parse 项目设置
- - '###'
  - 管理你的密钥：`EMABConstants` 类
- - '###'
  - 创建一个新的 Parse 应用
- - '###'
  - 设置支付：Stripe
- - '###'
  - 设置事务性邮件：Mailgun
- - '###'
  - 设置 Facebook 登录
- - '###'
  - 管理依赖：CocoaPods
- - '###'
  - 安装 Podfile
- - '###'
  - 实现进度指示器：SVProgressHud
- - '###'
  - 总结
- - '#'
  - 第 5 章：产品类别
- - '##'
  - 5. 产品类别
- - '###'
  - 产品类别模型
- - '###'
  - 产品类别视图
- - '###'
  - 产品类别控制器
- - '###'
  - 整合所有内容：UIStoryboard
- - '###'
  - 添加样本数据
- - '###'
  - 小结
- - '#'
  - 第 6 章：产品屏幕
- - '##'
  - 6. 产品界面
- - '###'
  - 产品模型
- - '####'
  - 产品视图
- - '####'
  - 产品控制器
- - '###'
  - 添加示例数据
- - '###'
  - 添加搜索功能
- - '###'
  - 添加筛选选项
- - '###'
  - 本章小结
- - '#'
  - 第 7 章：产品详情屏幕
- - '##'
  - 7. 产品详情界面
- - '###'
  - 构建产品详情界面
- - '###'
  - 添加分享选项
- - '###'
  - 添加收藏列表
- - '###'
  - 本章小结
- - '#'
  - 第 8 章：注册功能
- - '##'
  - 8. 注册功能
- - '###'
  - 构建调度屏幕
- - '###'
  - 注册模型
- - '###'
  - 注册视图
- - '###'
  - 注册控制器
- - '###'
  - 总结
- - '#'
  - 第 9 章：登录功能
- - '##'
  - 9. 登录功能
- - '###'
  - 使用直接登录
- - '###'
  - 使用 Facebook 登录
- - '###'
  - 本章小结
- - '#'
  - 第 10 章：购物袋
- - '##'
  - 10. 购物袋
- - '###'
  - 购物袋模型
- - '###'
  - 购物袋视图
- - '###'
  - 购物袋控制器
- - '###'
  - 总结
- - '#'
  - 第 11 章：收货地址
- - '##'
  - 11. 送货地址
- - '###'
  - 送货地址模型
- - '###'
  - 送货地址视图
- - '###'
  - 配送地址控制器
- - '###'
  - 总结
- - '#'
  - 第 12 章：信用卡支付
- - '##'
  - 12. 使用信用卡支付
- - '###'
  - 支付模型
- - '###'
  - 支付视图
- - '###'
  - 支付控制器
- - '###'
  - 总结
- - '#'
  - 第 13 章：Apple Pay 支付
- - '##'
  - 13. 使用 Apple Pay 付款
- - '###'
  - Apple Pay 概述
- - '###'
  - Apple Pay 与 Stripe
- - '###'
  - 摘要
- - '#'
  - 第 14 章：扣款与邮件
- - '##'
  - 14. 扣款与电子邮件
- - '###'
  - 创建并扣款客户
- - '###'
  - Parse 云代码
- - '###'
  - Parse 命令行工具 (CLT)
- - '###'
  - Parse 云模块
- - '###'
  - 创建 Stripe 客户
- - '###'
  - 向客户收费
- - '###'
  - 收费令牌
- - '###'
  - 总结
- - '#'
  - 第 15 章：我的账户
- - '##'
  - 15. 我的账户
- - '###'
  - 创建“我的账户”界面
- - '####'
  - 联系信息
- - '####'
  - 支付方式
- - '#####'
  - 视图
- - '#####'
  - 控制器
- - '###'
  - 我的订单历史
- - '####'
  - 视图
- - '####'
  - 控制器
- - '###'
  - 收藏的商品
- - '####'
  - 模型
- - '####'
  - 视图
- - '####'
  - 控制器
- - '###'
  - 总结
- - '#'
  - 第 16 章：添加产品
- - '##'
  - 16. 添加产品
- - '###'
  - 模型
- - '###'
  - 视图
- - '###'
  - 控制器
- - '###'
  - 上传产品照片
- - '###'
  - 输入产品名称、价格、单价和产品摘要
- - '####'
  - 选择品牌
- - '####'
  - 保存
- - '###'
  - 摘要
- - '#'
  - 第 17 章：促销
- - '##'
  - 17. 推广
- - '###'
  - 模型
- - '###'
  - 视图
- - '###'
  - 控制器
- - '###'
  - 总结
- - '#'
  - 第 18 章：安全
- - '##'
  - 18. 安全
- - '###'
  - 密钥
- - '###'
  - 权限
- - '####'
  - 访问控制列表（ACL）
- - '###'
  - 云代码
- - '###'
  - 会话
- - '###'
  - 小结
- - '#'
  - 第 19 章：更多 Parse 功能
- - '##'
  - 19. 深入了解 Parse
- - '###'
  - 电子邮件验证
- - '###'
  - 密码重置
- - '###'
  - 分析
- - '###'
  - 崩溃报告
- - '###'
  - 总结
- - '#'
  - 内容概览
- - '#'
  - 关于作者与技术审校者
- - '#'
  - 索引
- - '##'
  - A
- - '###'
  - 访问控制列表
- - '###'
  - 账户
- - '###'
  - 账户设置
- - '###'
  - 添加产品
- - '###'
  - Apple Pay 与 Stripe
- - '###'
  - iOS 开发者 Apple Store 应用
- - '###'
  - 数组
- - '##'
  - B
- - '##'
  - C
- - '###'
  - 购物车
- - '###'
  - 类级权限
- - '###'
  - Cocoapods
- - '###'
  - 命令行工具
- - '###'
  - 计算机编程分类
- - '###'
  - 信用卡支付控制器
- - '##'
  - D
- - '###'
  - DispatchViewController
- - '##'
  - E
- - '###'
  - EcommerceAppBook
- - '###'
  - EMABCategory
- - '###'
  - EMABConstants
- - '###'
  - EMABPaymentMethod 模型
- - '###'
  - EMABProduct 模型
- - '###'
  - EMABProductTableViewCell
- - '###'
  - 电子邮件
- - '###'
  - 电子邮件验证流程
- - '##'
  - F
- - '##'
  - G
- - '##'
  - H
- - '###'
  - Facebook 登录
- - '##'
  - I
- - '###'
  - iOS 开发者计划
- - '##'
  - J
- - '###'
  - 连接表方法
- - '##'
  - K
- - '###'
  - '`kOrder`'
- - '##'
  - L
- - '###'
  - 实时密钥
- - '###'
  - 登录
- - '##'
  - M
- - '##'
  - N
- - '##'
  - O
- - '###'
  - Mailgun API
- - '###'
  - 模型-视图-控制器
- - '###'
  - 我的账户
- - '##'
  - P
- - '##'
  - Q
- - '###'
  - Parse 应用邮箱地址
- - '###'
  - Parse 关系
- - '###'
  - 密码重置
- - '###'
  - 支付模型
- - '###'
  - '`PFQuery`'
- - '###'
  - Podfile
- - '###'
  - 指针
- - '###'
  - 编程书籍
- - '###'
  - 产品分类模型
- - '###'
  - 产品控制器
- - '###'
  - 产品详情屏幕
- - '###'
  - 产品模型自定义静态方法
- - '###'
  - 产品屏幕
- - '###'
  - 产品视图
- - '###'
  - 促销模型
- - '###'
  - 原型分发导航控制器
- - '##'
  - R
- - '###'
  - 必需功能列表（Apple Store 应用）
- - '##'
  - S
- - '##'
  - T
- - '###'
  - 安全性
- - '###'
  - 收货地址控制器
- - '###'
  - 收货地址模型
- - '###'
  - 购物袋控制器
- - '###'
  - 购物袋模型
- - '###'
  - 注册控制器
- - '###'
  - 注册模型
- - '###'
  - '`SVProgressHud`'
- - '##'
  - U
- - '##'
  - V
- - '##'
  - W
- - '###'
  - '`UIStoryboard`'
- - '##'
  - X
- - '##'
  - Y
- - '##'
  - Z
- - '###'
  - Xcode 项目 `.plist` 文件
