name: Pro Core Data for iOS
name_cn: iOS Core Data 高级指南
slug: pro-core-data-for-ios
toc:
- - '#'
  - iOS 平台 Core Data 高级编程：iPhone、iPad 和 iPod touch 的数据访问与持久化引擎 第二版
- - '##'
  - 目录一览
- - '##'
  - 关于作者
- - '##'
  - 关于技术审校
- - '##'
  - 引言
- - '###'
  - 为何推出第二版？
- - '###'
  - 你需要准备什么
- - '###'
  - 你将学到什么
- - '###'
  - 本书的组织结构
- - '###'
  - 源代码与勘误
- - '###'
  - 如何联系我们
- - '##'
  - 第 1 章：开始入门
- - '###'
  - 什么是 Core Data？
- - '###'
  - iOS 中的持久化历史
- - '###'
  - 创建一个基础的 Core Data 应用程序
- - '####'
  - 理解 Core Data 组件
- - '###'
  - 创建新项目
- - '###'
  - 运行新项目
- - '###'
  - 理解应用程序的组件
- - '###'
  - 获取结果
- - '####'
  - 插入新对象
- - '####'
  - 初始化托管上下文
- - '###'
  - 将 Core Data 添加到现有项目
- - '####'
  - 添加 Core Data 框架
- - '####'
  - 创建数据模型
- - '###'
  - 初始化托管对象上下文
- - '###'
  - 总结
- - '##'
  - 第 2 章：理解 Core Data
- - '###'
  - Core Data 框架类
- - '####'
  - 模型定义类
- - '###'
  - 数据访问类
- - '###'
  - 键值观察
- - '###'
  - 查询类
- - '###'
  - 类的交互方式
- - '####'
  - SQLite 入门
- - '###'
  - 使用 Core Data 读取数据
- - '###'
  - 小结
- - '##'
  - 第 3 章：存储数据：SQLite 与其他选项
- - '###'
  - 可视化用户界面
- - '###'
  - 使用 SQLite 作为持久化存储
- - '####'
  - 配置一对多关系
- - '###'
  - 构建用户界面
- - '###'
  - 配置表格
- - '###'
  - 创建团队
- - '####'
  - 球员用户界面
- - '####'
  - 添加、编辑和删除球员
- - '###'
  - 查看持久化存储中的数据
- - '###'
  - 使用内存持久化存储
- - '###'
  - 创建自定义持久化存储
- - '####'
  - 初始化自定义存储
- - '###'
  - NSManagedObject 与 NSAtomicStoreCacheNode 之间的映射
- - '####'
  - 序列化数据
- - '####'
  - 使用自定义存储
- - '####'
  - XML 持久化存储怎么样？
- - '###'
  - 总结
- - '##'
  - 第 4 章：创建数据模型
- - '###'
  - 设计数据库
- - '####'
  - 关系型数据库规范化
- - '###'
  - 使用 Xcode 数据模型器
- - '###'
  - 查看和编辑属性详细信息
- - '###'
  - 查看和编辑关系详情
- - '###'
  - 使用获取属性
- - '###'
  - 创建实体
- - '###'
  - 创建属性
- - '###'
  - 创建关系
- - '####'
  - 名称
- - '####'
  - 目标和反向
- - '####'
  - 瞬态（Transient）
- - '####'
  - 可选（Optional）
- - '####'
  - 对多关系（To-Many Relationship）
- - '####'
  - 数量（最小值和最大值）（Count (Minimum and Maximum)）
- - '####'
  - 删除规则（Delete Rule）
- - '###'
  - 总结
- - '##'
  - 第 5 章：处理数据对象
- - '###'
  - 理解 CRUD
- - '####'
  - 创建 Shape 应用数据模型
- - '###'
  - 排版后的文本
- - '###'
  - 构建形状应用用户界面
- - '####'
  - 启用与图形应用的用户交互
- - '###'
  - 生成类
- - '###'
  - 修改生成的类
- - '###'
  - 使用可转换类型
- - '###'
  - 排版后的内容
- - '###'
  - 验证数据
- - '####'
  - 自定义验证
- - '###'
  - 排版结果
- - '###'
  - 调用验证
- - '###'
  - 默认值
- - '###'
  - 撤销与重做
- - '####'
  - 撤销组
- - '####'
  - 限制撤销堆栈
- - '####'
  - 禁用撤销追踪
- - '####'
  - 为 Shapes 添加撤销功能
- - '###'
  - 总结
- - '##'
  - 第 6 章：优化结果集
- - '###'
  - 构建测试应用程序
- - '###'
  - 创建组织架构图数据
- - '###'
  - 读取并输出数据
- - '###'
  - 过滤
- - '####'
  - 单值表达式
- - '####'
  - 集合表达式
- - '####'
  - 比较谓词
- - '####'
  - 复合谓词
- - '####'
  - 子查询
- - '###'
  - 聚合（Aggregating）
- - '###'
  - 排序（Sorting）
- - '####'
  - 返回未排序的数据
- - '####'
  - 按单一条件排序数据
- - '####'
  - 按多个条件排序数据
- - '###'
  - 小结
- - '##'
  - 第 7 章：掌控局面：故意触发故障
- - '###'
  - 构建用于测试的应用程序
- - '###'
  - 创建 Core Data 项目
- - '###'
  - 创建数据模型与数据
- - '###'
  - 创建测试视图
- - '###'
  - 构建测试框架
- - '###'
  - 将测试框架添加到应用程序
- - '###'
  - 运行你的第一个测试
- - '###'
  - 错误/故障机制
- - '####'
  - 触发故障
- - '####'
  - 故障与缓存
- - '####'
  - 恢复故障
- - '###'
  - 构建故障测试
- - '###'
  - 掌控主动权：主动触发故障
- - '###'
  - 预取
- - '###'
  - 缓存
- - '###'
  - 过期
- - '####'
  - 内存消耗
- - '###'
  - 暴力缓存过期
- - '###'
  - 通过 Fault 机制使缓存过期
- - '###'
  - 唯一性保证
- - '###'
  - 实现文件中的唯一性测试
- - '###'
  - 使用更好的谓词提高性能
- - '####'
  - 使用更快的比较器
- - '###'
  - 使用子查询
- - '###'
  - 分析性能
- - '###'
  - 启动 Instruments
- - '###'
  - 理解结果
- - '###'
  - 总结
- - '##'
  - 第 8 章：版本控制与数据迁移
- - '###'
  - 版本控制
- - '###'
  - 轻量级迁移
- - '####'
  - 迁移简单变更
- - '####'
  - 迁移更复杂的变更
- - '###'
  - 重命名实体和属性
- - '###'
  - 创建映射模型
- - '####'
  - 理解实体映射
- - '####'
  - 理解属性映射
- - '###'
  - 创建需要映射模型的新模型版本
- - '####'
  - 创建映射模型
- - '###'
  - 迁移数据
- - '####'
  - 运行你的迁移
- - '###'
  - 自定义迁移
- - '####'
  - 确保需要迁移
- - '####'
  - 设置迁移管理器
- - '####'
  - 运行迁移
- - '###'
  - 总结
- - '##'
  - 第 9 章：使用获取结果控制器管理表视图
- - '###'
  - 理解 `NSFetchedResultsController`
- - '###'
  - 获取请求
- - '###'
  - 托管对象上下文
- - '###'
  - 分区名称键路径
- - '###'
  - 缓存名称
- - '###'
  - 理解 `NSFetchedResultsController` 委托
- - '###'
  - 使用 `NSFetchedResultsController`
- - '###'
  - 在 League Manager 中实现 NSFetchedResultsController
- - '###'
  - 实现 `NSFetchedResultsController`
- - '###'
  - 实现 `NSFetchedResultsControllerDelegate` 协议
- - '###'
  - 为表格添加索引
- - '###'
  - 响应数据变化
- - '###'
  - 总结
- - '##'
  - 第 10 章：在高级应用中使用 Core Data
- - '###'
  - 创建用于笔记与密码存储及加密的应用
- - '####'
  - 设置数据模型
- - '####'
  - 设置标签栏控制器
- - '####'
  - 添加标签页
- - '####'
  - 将 NSFetchedResultsController 集成到 MyStash 中
- - '####'
  - 创建获取结果控制器
- - '####'
  - 将获取结果控制器集成到表格中
- - '####'
  - 创建添加和编辑笔记与密码的界面
- - '###'
  - 跨多个持久化存储拆分数据
- - '####'
  - 使用模型配置
- - '###'
  - 添加加密
- - '####'
  - 使用数据保护功能的持久化存储加密
- - '####'
  - 数据加密
- - '#####'
  - 使用加密功能
- - '###'
  - 自动加密字段
- - '###'
  - 测试加密
- - '###'
  - 数据变更时发送通知
- - '####'
  - 注册观察者
- - '#####'
  - 接收通知
- - '###'
  - 预填充数据
- - '####'
  - 为密码添加分类
- - '###'
  - 创建种子数据的新版本
- - '###'
  - 错误处理
- - '####'
  - 处理 Core Data 操作错误
- - '####'
  - 处理验证错误
- - '####'
  - 在 MyStash 中处理验证错误
- - '###'
  - 实现验证错误处理例程
- - '###'
  - 总结
- - '##'
  - 索引
- - '###'
  - A
- - '###'
  - B
- - '###'
  - C
- - '###'
  - Core Data 模型配置
- - '###'
  - 自定义数据迁移
- - '###'
  - 数据加密
- - '###'
  - 数据迁移，253，276
- - '###'
  - 数据模型，9，10，111
- - '###'
  - 数据对象
- - '###'
  - 数据存储
- - '###'
  - 数据验证
- - '###'
  - 数据库
- - '###'
  - Deny 规则，41，131
- - '###'
  - 设计数据库
- - '###'
  - E
- - '###'
  - 加密
- - '###'
  - 错误处理，MyStash
- - '###'
  - 缓存过期
- - '###'
  - F, G
- - '###'
  - H
- - '###'
  - I, J
- - '###'
  - K
- - '###'
  - L
- - '###'
  - '`MakeRandomColor` 方法，151，170'
- - '###'
  - '`Memory usage`（内存使用）'
- - '###'
  - '`MyStash` 项目，307'
- - '###'
  - N
- - '###'
  - O
- - '###'
  - '`P, Q`'
- - '###'
  - R
- - '###'
  - S
- - '###'
  - T
- - '###'
  - U
- - '###'
  - V
- - '###'
  - W
- - '###'
  - X, Y
- - '###'
  - Z
