name: Android Essentials
name_cn: Android 入门指南
slug: android-essentials
toc:
- - '#'
  - Android 要点
- - '##'
  - 关于 firstPress
- - '#'
  - Android 基础
- - '##'
  - 第 3 章：用户界面
- - '##'
  - 第 4 章：定位，定位，定位
- - '##'
  - 第 5 章：带 Android 出去遛遛
- - '##'
  - 第 6 章：最后收尾
- - '#'
  - 第 1 章：引言
- - '##'
  - 你需要具备哪些知识才能开始
- - '##'
  - 如何最好地利用本书
- - '##'
  - 入门指南
- - '###'
  - 安装 Eclipse
- - '###'
  - 注意
- - '###'
  - 获取 Android SDK
- - '###'
  - 安装 Eclipse 插件
- - '###'
  - Android 项目
- - '###'
  - 多媒体及其他必需文件
- - '####'
  - '`res/`'
- - '#####'
  - '`res/drawable`'
- - '#####'
  - '`res/layout`'
- - '###'
  - 表 1-1. 续
- - '###'
  - 代码清单 1-1. `AndroidManifest.xml`
- - '#'
  - Android 核心要素
- - '##'
  - 运行、调试与制造混乱
- - '#'
  - 第 2 章：应用程序
- - '##'
  - 行动起来
- - '###'
  - Android 与 Java ME 和 BREW 的对比
- - '###'
  - 功能
- - '###'
  - 打造启动画面
- - '####'
  - 添加图像资源
- - '####'
  - 创建 XML 布局文件
- - '####'
  - 绘制启动画面
- - '####'
  - 时机几乎就是一切
- - '##'
  - 启动画面计时
- - '##'
  - 暂停、恢复、冲洗、重复
- - '##'
  - 基本按键处理
- - '###'
  - Android 核心要点
- - '####'
  - 补充练习
- - '####'
  - 明确 Intent
- - '####'
  - 运行应用
- - '####'
  - Activity 的生命周期
- - '####'
  - 迄今为止
- - '###'
  - 创建 Intent 接收器
- - '####'
  - 设置场景
- - '#####'
  - 这有什么实际用途吗？
- - '#####'
  - 使用 Intent 接收器
- - '###'
  - 构建意图接收器
- - '###'
  - 权限
- - '###'
  - 也把短信发给我！
- - '##'
  - 一窥意图接收器的实际运行
- - '###'
  - 短信里有什么？
- - '##'
  - 触发 Activity
- - '###'
  - 设置活动
- - '####'
  - 代码清单 2-4. 针对特定 Intent Action 启动
- - '##'
  - 今天你想羞辱谁？
- - '##'
  - 对服务的疑虑
- - '###'
  - 创建服务
- - '####'
  - 代码清单 2-5. 精简版服务
- - '###'
  - 启动服务
- - '###'
  - 启动音乐
- - '##'
  - 上下文类
- - '###'
  - 仁慈之举
- - '###'
  - 清单配置
- - '###'
  - 报复的禅意与艺术
- - '####'
  - 实施步骤
- - '##'
  - 更多恶作剧思路
- - '#'
  - 在 Android 中移动数据
- - '##'
  - 毫不掩饰的自我推销
- - '###'
  - 获取用户的书签
- - '###'
  - 搜索结果
- - '##'
  - 使用内容解析器添加“邪恶”的公司 URL
- - '##'
  - 均衡早餐的一部分
- - '#'
  - 第 3 章：用户界面
- - '##'
  - 在苏维埃谷歌中，界面渲染你
- - '##'
  - 简单快速的 XML 布局
- - '###'
  - 布局
- - '###'
  - '`LinearLayout`'
- - '###'
  - 滚动
- - '###'
  - 深入解析 TextView
- - '###'
  - XML 布局
- - '##'
  - 唤醒小部件
- - '###'
  - 获取句柄（Getting a Handle on Things）
- - '###'
  - 获取文本（Reeling in the Text）
- - '###'
  - Java 中的 Widget
- - '##'
  - 主菜单
- - '###'
  - 布局，Java 风格
- - '###'
  - 添加标题
- - '###'
  - 布局菜单条目
- - '###'
  - Android 基础：创建带焦点和选择功能的菜单
- - '###'
  - '`ItemOne.setOnClickListener(clickListener);`'
- - '###'
  - 回顾过往
- - '##'
  - 使用 Canvas 自定义 UI 渲染
- - '###'
  - 自定义视图
- - '####'
  - 代码清单 3-7. 在 CanvasExample Activity 中声明的简单自定义视图
- - '#'
  - Android UI 与游戏循环的进阶探索
- - '#'
  - 第 4 章：位置，位置，还是位置
- - '###'
  - 我在哪里？
- - '###'
  - 构建 LocationManager 对象
- - '###'
  - 一项必备标准
- - '###'
  - 仰望星空，卫星在注视着你…
- - '####'
  - 代码清单 4-1 注册位置更新
- - '####'
  - 代码清单 4-2 定义意图接收器
- - '###'
  - Google Maps
- - '####'
  - 海量的地图对象
- - '##'
  - 移动地图
- - '##'
  - 阶段性总结
- - '##'
  - 是鸟，是飞机……不，是糟糕的 Photoshop
- - '##'
  - 结束语
- - '#'
  - 第 5 章：带 Android 出门溜达
- - '###'
  - 从网络加载列表
- - '###'
  - 首要任务...先做什么？
- - '###'
  - 将数据放到合适的位置
- - '###'
  - 创建列表并验证功能
- - '####'
  - 准备工作：拥抱列表
- - '####'
  - 添加适配器
- - '###'
  - 向适配器中填充数据
- - '####'
  - 重新获取 UI 线程
- - '###'
  - 最后，添加数据
- - '###'
  - 选择...
- - '###'
  - 下一步
- - '###'
  - 装饰菜单
- - '###'
  - 回顾
- - '#'
  - 第 6 章：收尾工作
- - '##'
  - 应用的构建
- - '##'
  - 外表并非一切，但有时外表就是一切
- - '##'
  - 位置信息没那么重要，除非你凌晨 4 点想吃披萨
- - '##'
  - 解开 Android 的束缚，让它畅游互联网
- - '##'
  - 总结
- - '##'
  - 其他信息来源
- - '##'
  - 获取帮助
- - '##'
  - 是时候停止阅读，开始做出贡献了
