name: Android Arcade Game App
name_cn: Android 街机游戏应用
slug: android-arcade-game-app
toc:
- - '#'
  - Android 街机游戏应用
- - '##'
  - 目录速览
- - '#'
  - 关于作者
- - '#'
  - 关于技术审阅者
- - '#'
  - 关于游戏美术设计师
- - '#'
  - 致谢
- - '#'
  - 第 1 章：Android 游戏开发入门
- - '##'
  - 你需要了解的知识
- - '##'
  - 你将学到什么
- - '##'
  - 游戏发展简史
- - '##'
  - Android 的诞生
- - '##'
  - Android 游戏编程
- - '##'
  - 总结
- - '#'
  - 第 2 章：什么是街机游戏？
- - '##'
  - 街机风格游戏起源于何处？
- - '##'
  - 你的游戏：越狱
- - '##'
  - 本书内容……
- - '#'
  - 第 3 章：创建菜单
- - '##'
  - 准备工作
- - '##'
  - 创建启动画面和主菜单
- - '###'
  - '`PrisonbreakActivity`'
- - '##'
  - PBMainMenu
- - '##'
  - 总结
- - '#'
  - 第 4 章：绘制背景
- - '##'
  - 开始游戏
- - '##'
  - 创建 SurfaceView 和 Renderer
- - '##'
  - 创建背景类
- - '##'
  - 绘制背景
- - '##'
  - 总结
- - '#'
  - 第 5 章：创建玩家挡板和砖块
- - '##'
  - 开始之前
- - '##'
  - 创建玩家挡板类
- - '##'
  - 创建砖块类
- - '##'
  - 创建 `PBBall` 类
- - '##'
  - PBRow 和 PBWall
- - '##'
  - 在 PBGameRenderer 中调用砖块、挡板和球
- - '##'
  - 完整的 PBGameRenderer
- - '##'
  - 总结
- - '#'
  - 第 6 章：碰撞检测与游戏内物理
- - '##'
  - 总结
- - '#'
  - 第 7 章：计分
- - '##'
  - 创建计分方法
- - '##'
  - 按砖块计分
- - '##'
  - 按行计分
- - '##'
  - 总结
- - '#'
  - 第 8 章：添加更多关卡
- - '##'
  - 添加静态关卡
- - '##'
  - 添加动态关卡
- - '##'
  - 总结
- - '#'
  - 索引
