name: Windows 8 Apps Revealed Using HTML5 and JavaScript
name_cn: Windows 8 应用开发揭秘：HTML5 与 JavaScript 使用指南
slug: windows-8-apps-revealed-using-html5-and-javascript
toc:
- - '#'
  - Windows 8 应用揭秘：使用 HTML5 与 JavaScript
- - '##'
  - 版权信息
- - '##'
  - 鸣谢
- - '##'
  - 内容一览
- - '##'
  - 目录
- - '##'
  - 引言
- - '##'
  - 关于作者
- - '##'
  - 关于技术审校者
- - '##'
  - 简介
- - '##'
  - 关于本书
- - '###'
  - 阅读本书前需要了解什么？
- - '###'
  - 需要了解 HTML5 吗？
- - '###'
  - 阅读本书需要什么软件？
- - '###'
  - 本书结构如何？
- - '#'
  - 第 1 章 入门
- - '##'
  - 启动和运行
- - '###'
  - 创建项目
- - '###'
  - 探索 default.html 文件
- - '###'
  - 探索 default.css 文件
- - '###'
  - 探索 default.js 文件
- - '###'
  - 在 Windows 8 中使用你喜爱的 JavaScript 库
- - '###'
  - 启动和调试 JavaScript Windows 8 应用
- - '###'
  - 重新加载 Windows 8 应用
- - '###'
  - 调试 Windows 商店应用
- - '###'
  - 本章小结
- - '#'
  - 第 2 章 数据与绑定
- - '##'
  - 创建 JavaScript 文件
- - '##'
  - 使用代码补全
- - '##'
  - 减少全局命名空间污染
- - '###'
  - 创建命名空间
- - '###'
  - 使用自执行函数
- - '###'
  - 使用严格模式
- - '###'
  - 回到视图模型
- - '##'
  - 使用数据绑定
- - '###'
  - 使用基本声明性绑定
- - '###'
  - 创建动态绑定
- - '##'
  - 将命名空间与可观察项结合使用
- - '##'
  - 更新可观察数据项
- - '##'
  - 创建可观察数组
- - '##'
  - 使用模板
- - '###'
  - 为模板元素设置样式
- - '###'
  - 导入 JavaScript 和 CSS
- - '###'
  - 测试模板
- - '##'
  - 响应列表更改
- - '##'
  - 跟踪选中的项
- - '##'
  - 将模板应用于应用
- - '##'
  - 总结
- - '#'
  - 第 3 章 应用程序控件
- - '##'
  - 添加 AppBar
- - '###'
  - 清单 3-1. 在`appbar.html`文件中定义`AppBar`
- - '###'
  - 清单 3-2. 将 HTML 片段导入`default.html`
- - '###'
  - 实现应用栏按钮
- - '###'
  - 清单 3-3. 为`AppBar`按钮设置支持
- - '##'
  - 添加 Flyouts
- - '###'
  - 将浮出控件与应用栏命令关联
- - '###'
  - 导入浮出控件内容
- - '###'
  - 连接浮出控件中的控件
- - '##'
  - 使用页面
- - '###'
  - 定义 HTML
- - '###'
  - 创建 JavaScript 回调
- - '###'
  - 加载和显示 HTML
- - '###'
  - 加载完整的 HTML 文档
- - '###'
  - 在页面之间切换
- - '##'
  - 显示外部内容
- - '###'
  - 清单 3-20：`storeDetail.html` 文件
- - '###'
  - 添加回调（清单 3-21）
- - '###'
  - 显示页面（清单 3-22）
- - '###'
  - 检查清单权限：互联网（客户端）功能
- - '###'
  - 图 3-5：允许用户编辑购物清单项目的详细信息
- - '###'
  - 图 3-6：显示外部内容
- - '##'
  - 本章小结
- - '#'
  - 第 4 章 布局与磁贴
- - '##'
  - 处理 Windows 8 的屏幕方向与视图
- - '##'
  - 模拟屏幕方向与视图的更改
- - '###'
  - 模拟屏幕方向更改
- - '###'
  - 模拟视图更改
- - '##'
  - 适应方向与视图变化
- - '###'
  - 使用 CSS 适配
- - '###'
  - 使用 JavaScript 适配
- - '###'
  - 清单 4-4. 支持 JavaScript 方向变化而添加的样式
- - '###'
  - 图 4-5. 使用 JavaScript 适应纵向方向
- - '##'
  - CSS3 弹性盒布局快速入门
- - '##'
  - 以编程方式退出贴靠视图
- - '###'
  - 清单 4-5. 向 `default.html` 文件添加元素
- - '###'
  - 清单 4-6. 向 `default.css` 文件添加新样式
- - '##'
  - 使用磁贴和锁屏提醒
- - '##'
  - 改进静态磁贴
- - '###'
  - 应用图像
- - '###'
  - 更大或更小的按钮
- - '##'
  - 更新磁贴
- - '###'
  - 填充 XML 模板
- - '###'
  - 创建磁贴更新
- - '###'
  - 应用磁贴更新
- - '####'
  - 代码清单 4-10。在应用程序设置期间更新磁贴
- - '####'
  - 代码清单 4-11。将`tiles.js`文件添加到`default.html`
- - '###'
  - 测试磁贴更新
- - '###'
  - 更新宽磁贴
- - '###'
  - 应用徽章
- - '####'
  - 文档格式：两种徽章模板
- - '##'
  - 总结
- - '#'
  - 第 5 章 生命周期事件
- - '##'
  - 处理应用生命周期
- - '##'
  - 修正 Visual Studio 事件代码
- - '##'
  - 使用 Visual Studio 模拟生命周期事件
- - '##'
  - 触发生命周期事件
- - '###'
  - 激活应用
- - '###'
  - 挂起应用
- - '###'
  - 恢复应用
- - '##'
  - 添加异步活动
- - '##'
  - 使用位置追踪
- - '###'
  - 声明位置功能
- - '###'
  - 测试后台任务
- - '##'
  - 控制任务
- - '##'
  - 实现搜索合约
- - '###'
  - 声明对合约的支持
- - '###'
  - 处理搜索
- - '##'
  - 实现`Activated`事件处理程序
- - '##'
  - 确保应用设置
- - '##'
  - 测试搜索合约
- - '##'
  - 总结
