name: Develop Intelligent IOS Apps with Swift
name_cn: Swift 开发智能 iOS 应用
slug: develop-intelligent-ios-apps-with-swift
toc:
- - '#'
  - 1. 机器学习与自然语言处理入门简介
- - '##'
  - 什么是机器学习？
- - '##'
  - 监督学习
- - '##'
  - 无监督学习
- - '##'
  - 机器学习基本术语
- - '##'
  - 什么是深度学习？
- - '##'
  - 什么是自然语言处理
- - '##'
  - 总结
- - '#'
  - 2. Apple ML 工具简介
- - '##'
  - Vision
- - '###'
  - 人脸与身体检测
- - '###'
  - 图像分析
- - '###'
  - 文本检测与识别
- - '###'
  - Vision 的其他功能
- - '##'
  - VisionKit
- - '##'
  - 自然语言处理
- - '###'
  - 语言识别
- - '###'
  - 分词
- - '###'
  - 词性标注
- - '###'
  - 识别人物、地点和组织
- - '##'
  - NLEmbedding
- - '##'
  - 语音
- - '##'
  - Core ML
- - '##'
  - Create ML
- - '##'
  - Turi Create
- - '#'
  - 3. 文本分类
- - '##'
  - 使用 Create ML 框架进行垃圾短信分类
- - '###'
  - 在 macOS Playgrounds 中训练模型
- - '##'
  - 使用 Create ML 应用进行垃圾邮件分类
- - '##'
  - 使用 Turi Create 进行垃圾邮件分类
- - '###'
  - Turi Create 环境设置
- - '####'
  - 创建一个 Python 虚拟环境
- - '####'
  - 激活你的虚拟环境 `source ~/venv/bin/activate`
- - '###'
  - 使用 Turi Create 训练文本分类器
- - '####'
  - 读取 CSV 文件
- - '####'
  - 重命名列
- - '####'
  - 分割数据
- - '####'
  - 创建文本分类器模型
- - '####'
  - 评估模型
- - '####'
  - 导出至 Core ML 使用
- - '##'
  - 本章小结
- - '#'
  - 4. 文本生成
- - '##'
  - GPT-2
- - '##'
  - 让我们构建 OCR 和文本生成应用
- - '###'
  - 使用内置 OCR
- - '###'
  - 使用 AI 模型生成文本
- - '##'
  - 总结
- - '#'
  - 5. 在文本文档中寻找答案
- - '##'
  - BERT
- - '###'
  - 构建问答应用
- - '##'
  - BERT-SQuAD
- - '##'
  - 检查 Core ML 模型
- - '##'
  - 让我们构建应用
- - '###'
  - 在 iOS 中使用 BERT 模型
- - '###'
  - 构建应用的 UI
- - '###'
  - 使用 Speech 框架进行语音识别
- - '##'
  - 总结
- - '#'
  - 6. 文本摘要
- - '##'
  - 什么是文本摘要？
- - '##'
  - 构建文本摘要应用
- - '##'
  - 总结
- - '#'
  - 7. 集成 Keras 模型
- - '##'
  - 将 Keras 模型转换为 Core ML 格式
- - '###'
  - 在 Keras 中训练文本分类模型
- - '####'
  - 选取 IMDB 数据集中最常见的 10000 个词
- - '####'
  - 解决 IMDB.load_data 在该版本中无法直接加载的问题
- - '####'
  - '错误提示为：''ValueError: Object arrays cannot be...'''
- - '####'
  - 保存 `np.load`
- - '####'
  - 修改 `np.load` 的默认参数
- - '####'
  - 以隐式设置 `allow_pickle=True` 的方式调用 `load_data`
- - '####'
  - 恢复 `np.load` 以供后续正常使用
- - '####'
  - 基于 RNN 的 IMDB 评论情感分析
- - '#####'
  - 加载数据集
- - '#####'
  - 检查单词分布
- - '#####'
  - 填充单词计数的列表
- - '#####'
  - 序列填充
- - '#####'
  - 创建 Keras 模型
- - '#####'
  - 编译并训练模型
- - '#####'
  - 导出模型
- - '###'
  - 测试 Core ML 模型
- - '###'
  - 在 Jupyter Notebook 中测试 Core ML 模型
- - '####'
  - 加载模型
- - '####'
  - 从模型中获取规格说明
- - '####'
  - 打印模型的输入/输出描述
- - '###'
  - 在 Xcode 中测试 Core ML 模型
- - '##'
  - 在 Xcode 中使用 Core ML 模型
- - '##'
  - 总结
- - '##'
  - 结论
- - '##'
  - 索引
