name: More iOS 6 development
name_cn: iOS 6 开发高级指南
slug: more-ios-6-development
toc:
- - '#'
  - 目录概览
- - '#'
  - 第 1 章：我们又出发了
- - '##'
  - 本书的内容
- - '###'
  - 你需要了解的内容
- - '####'
  - 完全是 iOS 新手？
- - '###'
  - 开始前需要准备什么
- - '###'
  - 本书内容
- - '#'
  - 第 3 章
- - '##'
  - 极佳开端：添加、显示和删除数据
- - '###'
  - 设置 Xcode 项目
- - '###'
  - 添加场景
- - '###'
  - 场景和 Segues
- - '###'
  - Segue 定义转场
- - '###'
  - 故事板文档大纲
- - '###'
  - 应用架构
- - '###'
  - 设计视图控制器接口
- - '###'
  - 创建 HeroListController
- - '###'
  - 建立连接与插座变量
- - '###'
  - 导航栏按钮
- - '###'
  - 标签栏和用户默认设置
- - '###'
  - 设计数据模型
- - '####'
  - 添加实体
- - '####'
  - 编辑新实体
- - '####'
  - 为 Hero 实体添加属性
- - '#####'
  - 添加 Name 属性
- - '###'
  - 属性类型
- - '####'
  - 整数数据类型
- - '####'
  - Decimal、Double 和 Float 数据类型
- - '####'
  - 字符串数据类型
- - '####'
  - 布尔数据类型
- - '####'
  - 日期数据类型
- - '####'
  - 二进制数据类型
- - '####'
  - 可变换数据类型
- - '####'
  - 设置 name 属性类型
- - '###'
  - 添加其余属性
- - '###'
  - 声明获取结果控制器
- - '###'
  - 实现获取结果控制器
- - '###'
  - 获取结果控制器代理方法
- - '###'
  - 让一切运转起来
- - '###'
  - 错误处理
- - '###'
  - 实现编辑和添加功能
- - '###'
  - 编写表格视图数据源和委托方法
- - '###'
  - 对表格视图进行排序
- - '###'
  - 启动时加载获取请求
- - '###'
  - 开动吧
- - '###'
  - 完成，但尚未完成
- - '#'
  - 第 4 章：魔鬼藏在细节视图中
- - '##'
  - 细节视图中的魔鬼
- - '###'
  - 视图实现的选择
- - '###'
  - 创建细节视图控制器
- - '###'
  - 连接 Segue
- - '###'
  - HeroDetailController
- - '###'
  - 详细视图挑战
- - '###'
  - 使用属性列表控制表格结构
- - '####'
  - 属性列表详解
- - '####'
  - 使用属性列表建模表格结构
- - '####'
  - 通过属性列表定义表格视图
- - '###'
  - 解析属性列表
- - '###'
  - 推送详细信息
- - '###'
  - 排版后的文本
- - '###'
  - 显示详情
- - '###'
  - 编辑详情
- - '####'
  - 详情视图中的编辑模式
- - '###'
  - 创建自定义 `UITableViewCell` 子类
- - '###'
  - 保存你的更改
- - '###'
  - 专用输入视图
- - '####'
  - DatePicker SuperDBEditCell 子类
- - '###'
  - 使用 DatePicker SuperDBEditCell 子类
- - '###'
  - 实现选择拾取器
- - '###'
  - 魔鬼的终结
- - '#'
  - 第 5 章：为变更做准备：迁移与版本控制
- - '##'
  - 为变更做准备：迁移和版本控制
- - '###'
  - 关于数据模型
- - '###'
  - 数据模型是被编译的
- - '###'
  - 数据模型可以有多个版本
- - '###'
  - 创建新数据模型版本
- - '###'
  - 当前数据模型版本
- - '###'
  - 数据模型版本标识符
- - '###'
  - Core Data 版本管理与迁移
- - '####'
  - 迁移
- - '#####'
  - 轻量级迁移 vs 标准迁移
- - '###'
  - 标准迁移
- - '###'
  - 设置应用程序使用轻量级迁移
- - '###'
  - 继续迁移
- - '#'
  - 第 6 章：自定义托管对象
- - '##'
  - 自定义托管对象
- - '###'
  - 更新数据模型
- - '####'
  - 添加年龄属性
- - '####'
  - 添加最喜欢的颜色属性
- - '####'
  - 为名称属性添加最小长度
- - '###'
  - 创建 Hero 类
- - '###'
  - 调整 Hero 头文件
- - '###'
  - 设置默认值
- - '###'
  - 验证
- - '####'
  - 单属性验证
- - '####'
  - '`nil` 与 `NULL`'
- - '####'
  - 多属性验证
- - '###'
  - Core Data 数据验证与虚拟存取器
- - '####'
  - 多属性验证方法
- - '####'
  - 虚拟存取器
- - '###'
  - 添加验证反馈
- - '###'
  - 更新详情视图
- - '###'
  - 重构 SuperDBEditCell
- - '####'
  - Xcode 重构选项
- - '###'
  - 移动代码
- - '###'
  - 可编辑属性
- - '###'
  - 构建并运行应用
- - '###'
  - 创建颜色表格视图单元格
- - '####'
  - 自定义颜色编辑器
- - '####'
  - 自定义颜色表格视图单元格
- - '#####'
  - 清理 Picker
- - '###'
  - 还有一件事
- - '###'
  - 色彩告别
- - '#'
  - 第 7 章：关系、获取属性与表达式
- - '##'
  - 关系、获取属性和表达式
- - '###'
  - 扩展你的应用：超级能力和报告
- - '###'
  - 图 7-3：报告部分
- - '###'
  - 关系
- - '####'
  - 一对一关系
- - '####'
  - 一对多关系
- - '###'
  - 反向关系
- - '###'
  - 获取属性（Fetched Properties）
- - '###'
  - 在数据模型编辑器中创建关系和提取属性
- - '####'
  - 删除规则
- - '###'
  - 表达式与聚合
- - '###'
  - 添加 Power 实体
- - '###'
  - 创建`powers`关系
- - '###'
  - 创建反向关系
- - '###'
  - 创建`olderHeroes`获取属性
- - '###'
  - 什么是谓词？
- - '###'
  - 创建`youngerHeroes`获取属性
- - '####'
  - 创建 `sameSexHeroes` 获取属性
- - '####'
  - 创建 `oppositeSexHeroes` 获取属性
- - '####'
  - 向 Hero 类添加关系和获取属性
- - '####'
  - 更新详情视图
- - '####'
  - 重新思考配置
- - '###'
  - 封装与信息隐藏
- - '###'
  - 数据驱动配置
- - '####'
  - 添加能力（Powers）
- - '####'
  - 重构详情视图控制器
- - '#####'
  - 重命名配置类
- - '#####'
  - HeroDetailConfiguration 类名
- - '####'
  - 重构详情控制器
- - '####'
  - 重构 Hero 实例变量
- - '####'
  - 多一点抽象
- - '####'
  - 新的 `HeroDetailController`
- - '####'
  - 强大的视图控制器
- - '####'
  - 导航到 `PowerViewController`
- - '####'
  - 获取属性
- - '####'
  - 核心数据之美
- - '#'
  - 第 8 章：iCloud 存储
- - '##'
  - iCloud 的背后
- - '###'
  - 使用 iCloud 存储数据
- - '###'
  - iCloud 基础
- - '###'
  - iCloud 备份
- - '###'
  - 在应用程序中启用 iCloud
- - '###'
  - 键值数据存储
- - '###'
  - 文档存储
- - '####'
  - UIDocument
- - '###'
  - 文档排版
- - '###'
  - 基于 iCloud 的 UIDocument
- - '###'
  - '`NSMetadataQuery`'
- - '###'
  - 在 iCloud 中使用`Core Data`
- - '###'
  - 增强 SuperDB
- - '####'
  - 授权
- - '####'
  - 创建支持 iCloud 的配置文件
- - '###'
  - 更新持久化存储
- - '###'
  - 更新托管对象上下文
- - '###'
  - 在 DataChanged 时更新 UI
- - '###'
  - 测试数据存储
- - '###'
  - iCloud 开发要点
- - '###'
  - 脚踏实地
- - '#'
  - 第 9 章：使用 GameKit 进行蓝牙点对点通信
- - '##'
  - 使用 Game Kit 进行蓝牙点对点连接
- - '###'
  - Game Center
- - '###'
  - 点对点连接
- - '####'
  - 游戏内语音
- - '####'
  - 本章应用程序
- - '###'
  - 网络通信模型
- - '####'
  - 客户端-服务器模型
- - '####'
  - 点对点模型
- - '###'
  - 排版后的文本
- - '###'
  - 混合客户端-服务器 / 点对点网络
- - '###'
  - Game Kit 会话
- - '####'
  - 创建会话
- - '####'
  - 查找并连接其他会话
- - '####'
  - 监听其他会话
- - '###'
  - 向对等节点发送数据
- - '###'
  - 打包待发送的信息
- - '###'
  - 从对等节点接收数据
- - '###'
  - 关闭连接
- - '###'
  - 对等选择器
- - '####'
  - 创建对等选择器
- - '###'
  - 处理对等连接
- - '###'
  - 创建会话
- - '###'
  - 创建项目
- - '###'
  - 关闭闲置定时器
- - '###'
  - 导入 Game Kit 框架
- - '###'
  - 设计界面
- - '####'
  - 定义应用程序常量
- - '####'
  - 设计游戏棋盘
- - '####'
  - 创建 Packet 对象
- - '####'
  - 设置视图控制器头文件
- - '###'
  - 排版后的文档
- - '###'
  - 实现井字棋视图控制器
- - '####'
  - Game Kit 点对点委托方法
- - '####'
  - Game Kit 会话委托方法
- - '#####'
  - Game Kit 数据接收处理程序
- - '####'
  - 实现井字棋方法
- - '###'
  - 文档排版
- - '####'
  - 尝试运行
- - '####'
  - 游戏开始！
- - '#'
  - 第 10 章：CoreLocation 与 MapKit
- - '##'
  - CoreLocation 与 MapKit
- - '###'
  - Map Kit
- - '####'
  - 本章的应用
- - '###'
  - 概览与术语
- - '###'
  - 地图视图
- - '####'
  - 地图类型
- - '####'
  - 用户位置
- - '####'
  - 坐标区域
- - '###'
  - 将度数转换为距离
- - '###'
  - 复杂的数学运算
- - '###'
  - 适应宽高比
- - '###'
  - 设置要显示的区域
- - '###'
  - 地图视图代理
- - '####'
  - 地图加载代理方法
- - '####'
  - 区域更改代理方法
- - '###'
  - 判断坐标是否可见
- - '###'
  - 标注
- - '####'
  - 标注对象
- - '####'
  - 标注视图
- - '####'
  - 添加和移除标注
- - '####'
  - 选中标注
- - '####'
  - 为地图视图提供注释视图
- - '####'
  - 地理编码与反向地理编码
- - '###'
  - 构建 MapMe 应用程序
- - '####'
  - 链接地图套件和核心定位框架
- - '###'
  - 构建界面
- - '###'
  - 完成视图控制器接口
- - '###'
  - 编写标注对象类
- - '#'
  - 第 11 章：消息传递：邮件、社交网络与 iMessage
- - '##'
  - 消息传递：邮件、短信和社交媒体
- - '###'
  - 本章应用
- - '###'
  - '`MessageUI` 框架'
- - '####'
  - 创建邮件撰写视图控制器
- - '####'
  - 填充主题行
- - '####'
  - 填充收件人
- - '####'
  - 设置消息正文
- - '####'
  - 添加附件
- - '####'
  - 呈现邮件撰写视图
- - '####'
  - 邮件撰写视图控制器委托方法
- - '####'
  - 消息撰写视图控制器
- - '###'
  - Social 框架
- - '####'
  - SLComposeViewController
- - '#####'
  - 示例：创建发送推文的视图控制器
- - '####'
  - SLRequest
- - '####'
  - Activity 视图控制器
- - '###'
  - 构建 MessageImage 应用程序
- - '####'
  - 构建用户界面
- - '####'
  - 拍照
- - '####'
  - 调用相机
- - '####'
  - 选择消息发送方式
- - '####'
  - 以邮件方式发送……
- - '#'
  - 第 12 章：媒体库访问与播放
- - '##'
  - 媒体库访问与播放
- - '###'
  - Core Data：是什么，为什么及怎么用
- - '####'
  - Core Data 简史
- - '###'
  - 创建 Core Data 应用程序
- - '###'
  - Core Data 概念与术语
- - '####'
  - 数据模型
- - '###'
  - 实体
- - '###'
  - 属性
- - '###'
  - Core Data 实体与数据模型
- - '####'
  - 属性（Attributes）
- - '####'
  - 关系（Relationships）
- - '####'
  - 获取属性（Fetched Properties）
- - '####'
  - 获取请求（Fetch Requests）
- - '####'
  - 配置（Configurations）
- - '####'
  - 数据模型类：`NSManagedObjectModel`
- - '####'
  - 持久化存储区与持久化存储协调器
- - '####'
  - 回顾数据模型
- - '####'
  - 管理对象
- - '#####'
  - 键值编码
- - '#####'
  - 管理对象上下文
- - '###'
  - Core Data 基本概念
- - '###'
  - 在终止时保存
- - '###'
  - 从持久化存储加载数据
- - '###'
  - 获取结果控制器
- - '####'
  - 创建获取结果控制器
- - '###'
  - Fetched Results Controller 的委托方法
- - '####'
  - '`controllerWillChangeContent:` 委托方法'
- - '####'
  - '`controllerDidChangeContent:` 委托方法'
- - '####'
  - '`controller:didChangeObject:atIndexPath:forChangeType:newIndexPath:` 委托方法'
- - '####'
  - '`controller:didChangeSection:atIndex:forChangeType:` 委托方法'
- - '####'
  - 从 `NSFetchedResultsController` 中检索托管对象
- - '####'
  - 创建并插入新的托管对象
- - '###'
  - 删除托管对象
- - '###'
  - 将所有内容置于上下文中
- - '###'
  - MediaPlayer 框架
- - '###'
  - 媒体项目
- - '####'
  - 媒体项目持久化标识
- - '####'
  - 媒体类型
- - '####'
  - 位运算宏
- - '####'
  - 可过滤属性
- - '###'
  - 不可过滤的数值属性
- - '###'
  - 检索歌词
- - '###'
  - 检索专辑插图
- - '###'
  - 用户自定义属性
- - '###'
  - 资源 URL 属性
- - '###'
  - 媒体项集合
- - '####'
  - 创建新集合
- - '####'
  - 检索媒体项
- - '####'
  - 创建派生集合
- - '###'
  - 媒体查询与媒体属性谓词
- - '###'
  - 媒体选择器控制器
- - '####'
  - 处理媒体选择器的取消操作
- - '####'
  - 处理媒体选择器的选择操作
- - '###'
  - 音乐播放器控制器
- - '####'
  - 创建音乐播放器控制器
- - '####'
  - 判断音乐播放器控制器是否正在播放
- - '####'
  - 指定音乐播放器控制器的队列
- - '###'
  - 获取或设置当前播放的媒体项目
- - '###'
  - 跳过曲目
- - '###'
  - 快进/快退
- - '###'
  - 播放时间
- - '###'
  - 重复与随机播放模式
- - '###'
  - 调整音乐播放器控制器的音量
- - '###'
  - 音乐播放器控制器通知
- - '###'
  - 简易音乐播放器
- - '###'
  - 构建 SimplePlayer 应用
- - '###'
  - 构建用户界面
- - '###'
  - 格式化你的 SimplePlayer 应用
- - '###'
  - 声明 Outlets 和 Actions
- - '###'
  - MPMoviePlayerController
- - '###'
  - AVFoundation
- - '####'
  - AVMediaPlayer
- - '####'
  - 当心！前方有险滩！
- - '#'
  - 第 13 章：锁定安全：iOS 安全
- - '##'
  - 锁定安全：iOS 安全
- - '###'
  - 安全考量
- - '###'
  - 安全技术
- - '####'
  - 加密
- - '###'
  - 加密与安全
- - '###'
  - 哈希
- - '###'
  - 证书与签名
- - '###'
  - 身份标识
- - '###'
  - iOS 中的安全性
- - '###'
  - 随机化与钥匙串
- - '###'
  - 证书、密钥和信任服务
- - '###'
  - 钥匙串查看器应用程序
- - '####'
  - 创建证书颁发机构
- - '###'
  - 创建钥匙串应用
- - '###'
  - 安全永不停歇
- - '#'
  - 第 14 章：保持界面响应
- - '##'
  - 保持界面响应
- - '###'
  - 探索并发问题
- - '###'
  - 创建 Stalled 应用程序
- - '####'
  - 设计界面
- - '###'
  - 实现卡顿视图控制器
- - '###'
  - 定时器
- - '####'
  - 创建定时器
- - '###'
  - 停止定时器
- - '###'
  - 定时器的局限性
- - '###'
  - 使用定时器修复 Stalled
- - '####'
  - 创建批处理对象
- - '###'
  - 更新 Nib
- - '###'
  - 更新视图控制器头文件
- - '###'
  - 更新视图控制器实现
- - '###'
  - 操作队列与并发
- - '###'
  - 线程
- - '###'
  - 竞态条件
- - '###'
  - 互斥锁与 `@synchronized`
- - '###'
  - 原子性与线程安全
- - '###'
  - 死锁
- - '###'
  - 休眠时间
- - '###'
  - 操作
- - '####'
  - 操作依赖
- - '####'
  - 操作优先级
- - '###'
  - 其它操作状态
- - '###'
  - 取消操作
- - '###'
  - 操作队列
- - '####'
  - 向队列添加操作
- - '####'
  - 设置最大并发操作数
- - '####'
  - 暂停队列
- - '###'
  - 使用操作队列修复 Stalled 应用
- - '####'
  - 创建 SquareRootApplication
- - '###'
  - 排版后的文档
- - '###'
  - 自定义`ProgressCell`
- - '###'
  - 调整用户界面
- - '###'
  - '`ViewController.h`的更改'
- - '###'
  - 更新`ViewController.m`
- - '###'
  - 将它们排入队列
- - '#'
  - 第 15 章：单元测试、调试与 Instruments
- - '##'
  - 单元测试、调试和性能分析工具
- - '###'
  - 单元测试
- - '###'
  - 图 15-3：DebugTestTests 方案在哪里？
- - '###'
  - 图 15-4：Xcode 中失败的测试
- - '###'
  - 图 15-5：仅将 DebugMe 类保存到 DebugTest 目标
- - '###'
  - 调试
- - '###'
  - 断点
- - '###'
  - 使用断点进行调试
- - '###'
  - 断点简介
- - '###'
  - 行号断点
- - '###'
  - 尝试基本功能
- - '###'
  - 调试导航器
- - '###'
  - 调试区域
- - '###'
  - 调试栏控制
- - '###'
  - 嵌套调用
- - '###'
  - 试用调试控件
- - '###'
  - 断点导航器和符号断点
- - '###'
  - 条件断点
- - '###'
  - 断点动作
- - '###'
  - 静态分析
- - '###'
  - 关于调试的另外一点
- - '###'
  - 使用 Instruments 进行性能分析
- - '####'
  - 旅程的终点
- - '#'
  - 第 16 章：道路漫漫，永无止境……
- - '##'
  - 单元测试、调试和性能分析工具（续）
- - '###'
  - 第十六章
- - '####'
  - 路漫漫其修远兮……
- - '####'
  - 摆脱困境
- - '#####'
  - Apple 的文档
- - '#####'
  - 邮件列表
- - '#####'
  - 讨论论坛
- - '#####'
  - 网站
- - '#####'
  - 博客
- - '#####'
  - 如果所有方法都失败了……
- - '#####'
  - 再会
- - '#####'
  - 索引
- - '#'
  - 附录
- - '##'
  - 索引
- - '###'
  - D
- - '####'
  - 调试
- - '###'
  - E
- - '###'
  - F
- - '###'
  - O
- - '###'
  - P, Q
- - '#'
  - 元信息
- - '##'
  - 关于作者
- - '##'
  - 关于技术审校
- - '##'
  - 致谢
