name: Build Android-Based Smart Applications
name_cn: Android智能应用构建指南
slug: build-android-based-smart-applications
toc:
- - '#'
  - 目录
- - '##'
  - 引言
- - '##'
  - 致谢
- - '#'
  - 第一部分：规则引擎
- - '##'
  - 1. 哪种规则引擎最适合构建智能应用？
- - '###'
  - 什么是规则引擎？
- - '####'
  - CLIPS
- - '####'
  - JRuleEngine
- - '####'
  - DTrules
- - '####'
  - Zilonis
- - '####'
  - Termware
- - '####'
  - Roolie
- - '####'
  - OpenRules
- - '####'
  - JxBRE
- - '####'
  - JEOPS
- - '##'
  - 2. 移植规则引擎的步骤
- - '###'
  - CLIPS
- - '###'
  - JRuleEngine
- - '###'
  - DTrules
- - '###'
  - Zilonis
- - '###'
  - Termware
- - '###'
  - Roolie
- - '###'
  - OpenRules
- - '###'
  - JxBRE
- - '###'
  - JEOPS
- - '###'
  - 示例代码片段
- - '####'
  - CLIPS
- - '####'
  - JRuleEngine
- - '####'
  - DTrules
- - '####'
  - Zilonis
- - '####'
  - Termware
- - '####'
  - Roolie
- - '####'
  - OpenRules
- - '####'
  - JxBRE
- - '####'
  - JEOPS
- - '###'
  - 移植规则引擎时遇到的问题
- - '###'
  - 其他规则引擎的移植问题
- - '##'
  - 3. 移动平台规则引擎比较
- - '###'
  - 规则引擎总结
- - '###'
  - 规则引擎比较
- - '##'
  - 4. 知识应用开发中的需求与挑战
- - '###'
  - 介绍 SmartAppGen 和 AutoQuiz
- - '###'
  - 开发知识应用
- - '#'
  - 第二部分：SmartAppGen：从结构化知识自动生成知识应用
- - '##'
  - 5. SmartAppGen 的设计与实现
- - '##'
  - 6. SmartAppGen 的架构
- - '###'
  - 模型代码生成器
- - '###'
  - 视图代码生成器
- - '###'
  - 控制器代码生成器
- - '###'
  - 问题提取器
- - '###'
  - 上下文管理器生成器
- - '###'
  - 规则生成器
- - '###'
  - 语言翻译器
- - '###'
  - 持久化助手
- - '###'
  - 交互到 XML 转换器
- - '###'
  - 规则升级器
- - '###'
  - Cwac-updater
- - '###'
  - 语音转文本转换器
- - '###'
  - 文本转语音转换器
- - '###'
  - 照片捕获器
- - '###'
  - 音频捕获器
- - '###'
  - 聊天框架
- - '###'
  - 边缘智能框架
- - '###'
  - REST 客户端
- - '###'
  - 安装管理器
- - '##'
  - 7. 从知识生成知识应用的示例
- - '###'
  - 与知识对应的 Android 布局
- - '###'
  - 与知识对应的 CLIPS 规则文件
- - '###'
  - 知识应用的处理流程
- - '###'
  - 知识应用支持功能的生成
- - '###'
  - 生成数据库辅助类
- - '###'
  - 如何使用 SmartAppGen
- - '###'
  - SmartAppGen 的优势
- - '##'
  - 8. AutoQuiz：从非结构化知识自动生成测验
- - '###'
  - 题目生成器
- - '###'
  - 测验应用
- - '###'
  - AutoQuiz 的优点
- - '###'
  - 已知问题
- - '##'
  - 9. 未来工作
- - '##'
  - 10. iEmergency
- - '###'
  - 方法
- - '###'
  - 系统架构
- - '###'
  - 系统实现
- - '####'
  - 请求者应用程序 iRescue
- - '####'
  - 帮助者应用程序 iRescuer
- - '####'
  - 用户界面
- - '####'
  - iEmergency 服务器
- - '#'
  - 第三部分
- - '##'
  - 11. 作业
- - '###'
  - iEncrypt 和 iDecrypt
- - '###'
  - iFitness
- - '###'
  - iPocket
- - '###'
  - iFall
- - '###'
  - iPrescribe
- - '###'
  - iSafety
