name: Learn Design for iOS Development
name_cn: iOS 开发设计学习指南
slug: learn-design-for-ios-development
toc:
- - '#'
  - 学习 iOS 开发设计
- - '##'
  - 目录概览
- - '#'
  - 目录
- - '#'
  - 目录
- - '##'
  - 第 4 章：熟悉 iPhone 和 iPad 用户界面的设计考量
- - '##'
  - 第 5 章：移动设计模式
- - '##'
  - 第 6 章：使用线框图设计你的应用
- - '##'
  - 第 7 章：使用 Adobe Photoshop 设计视觉资源
- - '###'
  - 图层面板
- - '###'
  - 创建注册/登录页面
- - '###'
  - 创建选择和编辑行程页面
- - '###'
  - 使用图层复合进行屏幕布局
- - '###'
  - Adobe Fireworks 呢？
- - '###'
  - 总结
- - '##'
  - 第 8 章：创建应用图标及 App Store 所需的附加图形
- - '###'
  - 应用发现
- - '###'
  - App Store
- - '###'
  - 应用图标
- - '###'
  - 启动图像
- - '###'
  - 报刊亭封面图标
- - '###'
  - 推广截图
- - '###'
  - 推广插图
- - '###'
  - 应用的页面
- - '###'
  - 总结
- - '##'
  - 第 9 章：为应用开发最终确定素材资源
- - '###'
  - 为开发人员创建设计规范文档
- - '###'
  - 设计规范文档概述
- - '###'
  - 提供颜色信息
- - '###'
  - 指定字体与类型
- - '###'
  - 解释用户交互
- - '###'
  - 将设计切片为素材资源
- - '###'
  - 针对不同设备缩放并保存素材资源
- - '###'
  - 其他素材准备工具
- - '###'
  - 命名素材资源
- - '###'
  - 将素材资源打包用于开发
- - '###'
  - 沟通是关键
- - '###'
  - 总结
- - '##'
  - 第 10 章：设计最佳实践与应避免的错误
- - '###'
  - 创建应用设计声明
- - '###'
  - 《人机界面指南》是你的设计圣经，请善加利用
- - '###'
  - 线框图很重要
- - '###'
  - UI 与 UX：两者有区别
- - '###'
  - 简化！
- - '###'
  - 善用留白
- - '###'
  - 留意 iOS 7 的变化
- - '###'
  - 问“为什么？”
- - '###'
  - 考虑小屏幕
- - '###'
  - iPad 不仅仅是放大版的 iPhone
- - '###'
  - 字体很重要
- - '###'
  - 提供视觉反馈
- - '###'
  - 用户是王者（或女王）
- - '###'
  - 设计模式是你的朋友
- - '###'
  - 拇指规则
- - '###'
  - 从高分辨率到低分辨率
- - '###'
  - 快速上手
- - '###'
  - 测试、测试、再测试
- - '###'
  - 软件会有所帮助
- - '###'
  - 图标和截图也很重要
- - '###'
  - 交接与沟通
- - '###'
  - 总结
- - '###'
  - 索引
- - '##'
  - 关于作者
- - '##'
  - 关于技术审校
- - '##'
  - 致谢
- - '##'
  - 引言
- - '##'
  - 本书读者对象
- - '##'
  - 如何使用本书
- - '##'
  - 网站上有什么
- - '###'
  - '`apress.com` 网站'
- - '##'
  - 第 1 章：你有了一个 iPhone 应用的点子，然后呢？
- - '###'
  - 假设
- - '###'
  - 第一步：定义你的想法
- - '###'
  - 第二步：与同行分享你的想法
- - '###'
  - 第三步：将你的应用与其他应用进行比较
- - '###'
  - App Store 竞品分析指南
- - '####'
  - 第一步：浏览用户评论
- - '####'
  - 第二步：关注应用评测网站
- - '####'
  - 第三步：分析你的发现
- - '####'
  - 第四步：为将来参考保存竞品应用
- - '####'
  - 第五步：根据需要修正你的创意
- - '###'
  - 总结
- - '##'
  - 第 2 章：iOS：你需要了解什么
- - '###'
  - iOS 7 的新特性
- - '####'
  - iOS 7 的指导原则
- - '###'
  - 主屏幕
- - '####'
  - iOS 7 中的主屏幕
- - '###'
  - 字体排印
- - '###'
  - 图标
- - '###'
  - 栏
- - '####'
  - 状态栏
- - '####'
  - iOS 7 UI 元素指南
- - '###'
  - 状态栏
- - '###'
  - 导航栏
- - '###'
  - 工具栏
- - '###'
  - 标签栏
- - '###'
  - 表视图与表视图元素
- - '####'
  - 表格视图元素
- - '####'
  - 预装应用
- - '#####'
  - 邮件
- - '######'
  - 标准邮件图标
- - '#####'
  - 计算器
- - '#####'
  - 日历
- - '#####'
  - 天气
- - '###'
  - 色彩、透明度与图层
- - '####'
  - iOS 7 设计原则
- - '###'
  - 运用色彩
- - '###'
  - 运用透明度
- - '###'
  - 运用图层
- - '###'
  - 按钮
- - '###'
  - 总结
- - '##'
  - 第 3 章：iOS 7 与扁平化设计
- - '###'
  - 扁平化设计的原则
- - '###'
  - 扁平化设计的起源及其他应用
- - '###'
  - 扁平化设计的未来
- - '###'
  - 将扁平化设计融入你的应用
- - '####'
  - 选择配色方案
- - '###'
  - 设计图标
- - '###'
  - 利用空间和模板
- - '###'
  - 定义按钮
- - '###'
  - 在 iOS 7 中，按钮与表单设计的演变
- - '####'
  - 简化表单
- - '####'
  - 确定字体排印
- - '####'
  - 评估可用性
- - '###'
  - 总结
- - '##'
  - 第 4 章：了解 iPhone 和 iPad 用户界面设计考量
- - '###'
  - 为 iPhone 和 iPad 进行设计
- - '####'
  - UI 中手势的使用
- - '#####'
  - 手势的一致性
- - '#####'
  - 手势的直接操纵
- - '#####'
  - 抽象手势与反馈
- - '####'
  - 图 4-2. Mailbox 应用针对旧手势的操作
- - '####'
  - iOS 中的手势
- - '#####'
  - 轻点
- - '#####'
  - 双击
- - '#####'
  - 拖移或平移
- - '#####'
  - 轻拂
- - '#####'
  - 轻扫
- - '#####'
  - 捏合
- - '#####'
  - 触摸并按住
- - '#####'
  - 摇晃
- - '####'
  - 新的 iOS 手势
- - '#####'
  - 向上轻扫
- - '#####'
  - 向下轻扫
- - '#####'
  - 向右轻扫（在 Mail 应用中）
- - '###'
  - iPad；有何不同？
- - '###'
  - iPad 系列概览
- - '###'
  - iPad 与 iPhone 的设计差异
- - '###'
  - iPad 特有的 UI 元素
- - '####'
  - 弹出视图
- - '####'
  - 分屏视图
- - '###'
  - 视觉上下文
- - '###'
  - iPad 应用设计指南
- - '####'
  - 屏幕触控目标
- - '####'
  - 屏幕分辨率
- - '####'
  - 通用应用
- - '####'
  - 图标
- - '#####'
  - 应用图标
- - '####'
  - 启动图像
- - '####'
  - iPad 专属手势
- - '#####'
  - 滑动
- - '####'
  - 排版后的文本
- - '####'
  - 捏合
- - '###'
  - 总结
- - '##'
  - 第 5 章：移动设计模式
- - '###'
  - 注册与登录/注册表单
- - '###'
  - 应用导航
- - '####'
  - 主屏幕或主屏幕模式
- - '####'
  - Springboard 模式
- - '###'
  - 列表与表视图模式
- - '####'
  - 表格
- - '####'
  - 标签栏
- - '####'
  - 标签栏按钮
- - '###'
  - 侧滑导航
- - '###'
  - 图片库
- - '###'
  - 搜索与排序
- - '###'
  - 提示、导览与引导教程
- - '###'
  - 图 6-1
- - '####'
  - 线框图工具
- - '####'
  - 为什么线框图很重要？
- - '####'
  - 线框图绘制流程
- - '####'
  - 聚焦可用性
- - '####'
  - 尝试不同布局
- - '####'
  - 勾勒用户流程
- - '###'
  - 总结
- - '##'
  - 第 7 章：使用 Adobe Photoshop 设计视觉资源
- - '###'
  - 一些 Photoshop 基础知识
- - '####'
  - 为 Retina 做准备
- - '####'
  - 你的 Photoshop 设置
- - '####'
  - 网格线与参考线
- - '###'
  - 工具面板
- - '####'
  - 选择工具
- - '####'
  - 裁剪与切片工具
- - '####'
  - 测量工具
- - '####'
  - 修饰工具
- - '####'
  - 绘画工具
- - '####'
  - 绘图与文字工具
- - '####'
  - 视图与导航工具
- - '####'
  - 3D 工具
- - '###'
  - 图层面板
- - '###'
  - 创建注册/登录页面
- - '###'
  - 创建选择和编辑行程页面
- - '###'
  - 使用图层复合进行屏幕布局
- - '####'
  - Adobe Fireworks 怎么样？
- - '####'
  - 总结
- - '##'
  - 第 8 章：创建应用图标和 App Store 所需的其他图形
- - '###'
  - 应用发现
- - '###'
  - App Store
- - '###'
  - App 图标
- - '###'
  - 启动图像
- - '###'
  - 报刊亭封面图标
- - '####'
  - 封面图标
- - '###'
  - 宣传截图
- - '####'
  - 应做到：
- - '####'
  - 不应做：
- - '####'
  - 宣传素材
- - '###'
  - 你的应用页面
- - '####'
  - 按钮
- - '####'
  - 按钮标题
- - '####'
  - 字体、字号、文件名和颜色
- - '####'
  - 将设计切片为资源
- - '###'
  - 为不同设备缩放和保存素材
- - '###'
  - 其他素材准备工具
- - '###'
  - 为资源命名
- - '###'
  - 为开发打包资源
- - '###'
  - 沟通是关键
- - '###'
  - 总结
- - '##'
  - 第 10 章：设计最佳实践与应避免的错误
- - '###'
  - 创建应用设计陈述
- - '###'
  - 人机界面指南是你的设计圣经，请善用它
- - '####'
  - Apple 人机界面指南
- - '###'
  - 线框图很重要
- - '###'
  - UI 与 UX：二者有区别
- - '###'
  - 化繁为简！
- - '###'
  - 善用留白
- - '###'
  - 关注 iOS 7 的变化
- - '###'
  - 多问为什么？
- - '###'
  - 放眼小屏幕
- - '###'
  - iPad 不只是放大的 iPhone
- - '###'
  - 字体很重要
- - '###'
  - 提供视觉反馈
- - '###'
  - 用户就是上帝
- - '###'
  - 设计模式是你的好帮手
- - '###'
  - 拇指法则
- - '###'
  - 从高分辨率到低分辨率
- - '####'
  - iOS 应用设计贴士
- - '###'
  - 快速导入
- - '###'
  - 测试、测试、再测试
- - '###'
  - 软件会助你一臂之力
- - '###'
  - 图标和截图同样重要
- - '###'
  - 交接与沟通
- - '###'
  - 总结
- - '###'
  - 索引
