name: Learn Objective-C on the Mac For OS X and iOS
name_cn: Mac 和 iOS 的 Objective-C 学习指南
slug: learn-objective-c-on-the-mac-for-os-x-and-ios
toc:
- - '##'
  - 修复说明
- - '#'
  - 学习 Objective-C：适用于 iOS 和 OS X
- - '##'
  - 内容概览
- - '##'
  - 目录
- - '##'
  - 前言
- - '##'
  - 关于作者
- - '##'
  - 关于技术审校
- - '##'
  - 致谢
- - '##'
  - 如何使用本书
- - '#'
  - 第 1 章
- - '##'
  - 你好
- - '###'
  - 开始之前
- - '###'
  - 未来诞生于昨日
- - '###'
  - 后续内容
- - '##'
  - 准备工作
- - '##'
  - 总结
- - '#'
  - 第 2 章
- - '##'
  - C 语言的扩展
- - '##'
  - 最简单的 Objective-C 程序
- - '###'
  - 构建 Hello Objective-C
- - '##'
  - 解构 Hello Objective-C
- - '###'
  - 那个古怪的 `#import` 玩意儿
- - '###'
  - 框架简介
- - '##'
  - '`NSLog()` 与 `@"strings"`'
- - '##'
  - NS 前缀：防止名称冲突的良方
- - '##'
  - '`NSString`：其中的 `@`'
- - '##'
  - 你是布尔类型吗？
- - '##'
  - 强大的 `BOOL` 实战演示
- - '###'
  - 第一个函数
- - '###'
  - 不再上当
- - '##'
  - 第二个函数
- - '##'
  - '`main()`函数'
- - '###'
  - 比较本身
- - '##'
  - 总结
- - '#'
  - 第 3 章：面向对象编程入门
- - '###'
  - 一切都是间接性
- - '##'
  - 变量与间接
- - '##'
  - 通过文件名的间接
- - '##'
  - 在 Xcode 中提供文件路径
- - '##'
  - 在面向对象编程中使用间接性
- - '##'
  - 过程式编程
- - '##'
  - 待绘制图形的形状
- - '##'
  - 执行工作的部分
- - '##'
  - 一个方便的 C 语言快捷方式
- - '##'
  - 实现面向对象
- - '##'
  - 术语小憩
- - '##'
  - Objective-C 中的面向对象编程
- - '###'
  - '`@interface` 部分'
- - '###'
  - 了解中缀表示法
- - '###'
  - 冒号大集合
- - '##'
  - '`@implementation` 部分'
- - '##'
  - 方法定义详解
- - '##'
  - 实例化对象
- - '##'
  - 扩展 Shapes-Object
- - '##'
  - 总结
- - '#'
  - 第 4 章：继承
- - '##'
  - 继承
- - '##'
  - 为什么要使用继承？
- - '##'
  - 继承语法
- - '###'
  - 单一继承
- - '##'
  - 术语小憩
- - '##'
  - 继承如何工作
- - '##'
  - 方法分发
- - '##'
  - 实例变量
- - '##'
  - 方法重写
- - '##'
  - 我感觉超棒！
- - '##'
  - 总结
- - '#'
  - 第 5 章
- - '##'
  - 组合
- - '###'
  - 什么是组合？
- - '###'
  - 汽车讨论
- - '####'
  - 为`NSLog()`进行自定义
- - '####'
  - 关于那个`if`语句...
- - '##'
  - 访问器方法
- - '###'
  - 设置引擎
- - '###'
  - 设置轮胎
- - '####'
  - 轮胎访问器
- - '####'
  - 跟踪对`Car`的修改
- - '###'
  - 扩展`CarParts`
- - '###'
  - 组合还是继承？
- - '##'
  - 总结
- - '#'
  - 第 6 章
- - '##'
  - 源文件组织
- - '###'
  - 拆分接口与实现
- - '###'
  - 在 Xcode 中创建新文件
- - '##'
  - Xcode 项目文件组织与依赖管理
- - '###'
  - 拆分`Car`类
- - '###'
  - 导入中心
- - '##'
  - 使用跨文件依赖关系
- - '##'
  - 基于“需要知道”原则进行重新编译
- - '##'
  - 导入与继承
- - '##'
  - 总结
- - '#'
  - 第 7 章 更多关于 Xcode 的内容
- - '##'
  - 一统天下的窗口
- - '##'
  - 更改公司名称
- - '##'
  - Xcode 包含文件名和项目名称
- - '##'
  - 使用编辑器技巧和窍门
- - '##'
  - 在 Xcode 的帮助下编写代码
- - '###'
  - 缩进（漂亮打印）
- - '###'
  - 自动补全
- - '##'
  - 亲吻括号
- - '##'
  - 批量编辑
- - '##'
  - 在代码中导航
- - '###'
  - emacs 不是 Mac
- - '###'
  - 芝麻开门！
- - '###'
  - 集中精力
- - '##'
  - 代码折叠与聚焦功能
- - '##'
  - 导航栏已打开
- - '##'
  - 获取信息
- - '###'
  - 帮帮忙，谢谢
- - '###'
  - 文档员在家吗？
- - '##'
  - 调试
- - '##'
  - 调试：识别并修复程序错误
- - '###'
  - 粗暴式调试
- - '###'
  - Xcode 的调试器
- - '###'
  - 微妙的符号化
- - '###'
  - 开始调试！
- - '###'
  - 查看一下
- - '###'
  - 速查表
- - '##'
  - 总结
- - '#'
  - 第 8 章：Foundation Kit 快速巡礼
- - '##'
  - 坚实的基础
- - '##'
  - 使用项目模板代码
- - '##'
  - 一些有用的类型
- - '###'
  - 范围（Range）概述
- - '##'
  - 几何类型
- - '##'
  - 字符串引导
- - '###'
  - 构建字符串
- - '##'
  - 类方法
- - '###'
  - 大小问题
- - '###'
  - 比较策略
- - '###'
  - 大小写不敏感性
- - '###'
  - 是否包含在内？
- - '###'
  - 可变性
- - '###'
  - 集合代理
- - '###'
  - NSArray
- - '##'
  - 可变数组
- - '##'
  - 枚举天地
- - '##'
  - 快速枚举
- - '##'
  - NSDictionary
- - '##'
  - NSNull
- - '##'
  - 示例：查找文件
- - '##'
  - 在“小心猎豹”警示牌背后
- - '##'
  - 本章小结
- - '#'
  - 第 9 章
- - '##'
  - 内存管理
- - '##'
  - 对象的生命周期
- - '##'
  - 引用计数
- - '##'
  - Retain Count 1 项目详解
- - '##'
  - 对象所有权
- - '##'
  - 存取器中的保留与释放
- - '##'
  - 自动释放
- - '###'
  - 都到池子里来！
- - '###'
  - 毁灭前夕
- - '##'
  - 池的实际运作
- - '##'
  - Cocoa 内存管理规则
- - '##'
  - 临时对象
- - '##'
  - 持有对象
- - '##'
  - 自动释放池
- - '##'
  - 清理废纸与垃圾
- - '##'
  - 自动引用计数
- - '##'
  - 有时候弱引用是好事
- - '##'
  - 所有权即特权
- - '##'
  - 异常处理
- - '##'
  - 异常的关键字
- - '##'
  - 捕获不同类型的异常
- - '##'
  - 抛出异常
- - '###'
  - 异常也需要内存管理
- - '###'
  - 异常与自动释放池
- - '##'
  - 总结
- - '#'
  - 第 10 章：对象初始化
- - '##'
  - 分配对象
- - '##'
  - 初始化对象
- - '##'
  - 编写初始化方法
- - '##'
  - 代码排版与优化
- - '##'
  - 用初始化赢在起跑线
- - '##'
  - 初始化时该做什么
- - '##'
  - 这不是很方便吗？
- - '##'
  - 更多零件
- - '###'
  - 轮胎的初始化
- - '##'
  - 更新`main()`函数
- - '##'
  - 清理`Car`类
- - '##'
  - Car Cleaning, GC and ARC Style
- - '##'
  - Making a Convenience Initializer
- - '##'
  - 指定初始化方法
- - '##'
  - 子类化的问题
- - '###'
  - 修复 Tire 的初始化方法
- - '###'
  - 添加 AllWeatherRadial 的初始化方法
- - '###'
  - 初始化方法规则
- - '###'
  - 总结
- - '#'
  - 第 11 章 属性
- - '###'
  - 精简属性值
- - '###'
  - 精简接口
- - '###'
  - 精简实现
- - '##'
  - 点符号的惊人之处
- - '##'
  - 反对使用属性
- - '###'
  - 命名别名（Appellation）
- - '##'
  - 只读属性
- - '##'
  - 我偏要亲力亲为
- - '##'
  - 我不喜欢这些方法名
- - '##'
  - 可惜，属性并非万能
- - '##'
  - 总结
- - '#'
  - 第 12 章
- - '###'
  - 类别
- - '##'
  - 创建分类
- - '##'
  - 让我们来创建一个分类
- - '###'
  - '`@interface`'
- - '###'
  - '`@implementation`'
- - '###'
  - 糟糕的分类
- - '###'
  - 好的分类
- - '##'
  - 使用分类拆分实现
- - '###'
  - 在我们的项目中使用分类
- - '##'
  - CategoryThing 与 Categories
- - '##'
  - 使用 Categories 进行前向引用
- - '###'
  - 用 Categories 来救场！
- - '##'
  - 非正式协议与委托类别
- - '##'
  - '`ITunesFinder` 项目'
- - '##'
  - 委托与分类
- - '##'
  - 响应选择器
- - '##'
  - 代码示例与选择器
- - '##'
  - 选择器的其他用途
- - '##'
  - 本章小结
- - '#'
  - 第 13 章 协议
- - '##'
  - 正式协议
- - '##'
  - 声明协议
- - '##'
  - 采纳协议
- - '##'
  - 实现协议
- - '###'
  - Car-bon 副本
- - '##'
  - 制作副本
- - '##'
  - 复制引擎
- - '##'
  - 复制轮胎
- - '##'
  - 复制自定义对象
- - '###'
  - 复制 `AllWeatherRadial`
- - '###'
  - 复制 `Car`
- - '##'
  - 协议与数据类型
- - '##'
  - Objective-C 2.0 新特性
- - '##'
  - 委托机制即将登场
- - '##'
  - 总结
- - '#'
  - 第十四章
- - '###'
  - 块与并发
- - '###'
  - 活到老学到老，玩转块
- - '###'
  - 块与函数指针
- - '##'
  - 使用 Block
- - '##'
  - 直接使用 Block
- - '##'
  - 使用 typedef
- - '##'
  - Block 与变量
- - '##'
  - 局部变量
- - '##'
  - 全局变量
- - '##'
  - 参数变量
- - '##'
  - '`__block` 变量'
- - '##'
  - Block 局部变量
- - '##'
  - Objective-C 对象
- - '##'
  - 对象引用与内存管理
- - '##'
  - 并发，或保持同步
- - '##'
  - 同步
- - '##'
  - 选择性能
- - '##'
  - 每天我都排队
- - '##'
  - 一碗串行队列
- - '##'
  - 并发调度队列
- - '##'
  - 直下主街
- - '##'
  - 我是杰克的调度队列
- - '##'
  - 队列也需要内存管理
- - '##'
  - 队列的上下文
- - '###'
  - 清理函数
- - '##'
  - 添加任务
- - '##'
  - 使用 Dispatch 进行编程
- - '##'
  - 操作队列
- - '###'
  - 创建调用操作
- - '###'
  - 创建块操作
- - '###'
  - 将操作添加到队列
- - '##'
  - 总结
- - '#'
  - 第 15 章
- - '##'
  - UIKit 简介
- - '##'
  - 视图控制器
- - '##'
  - 向 Nib 文件中添加元素
- - '#'
  - 第 16 章
- - '###'
  - 介绍 Application Kit
- - '###'
  - 创建项目
- - '##'
  - 制作委托的 `@interface`
- - '##'
  - Interface Builder
- - '##'
  - 布局用户界面
- - '##'
  - 建立连接
- - '##'
  - 连接输出口
- - '##'
  - 连接操作 (Actions)
- - '##'
  - AppDelegate 实现
- - '##'
  - 本章小结
- - '#'
  - 第 17 章
- - '##'
  - 文件加载与保存
- - '###'
  - 属性列表
- - '###'
  - NSDate
- - '###'
  - NSData
- - '###'
  - 写入和读取属性列表
- - '##'
  - 修改对象
- - '##'
  - 编码对象
- - '##'
  - 总结
- - '#'
  - 键值编码
- - '#'
  - 第 18 章 键值编码
- - '##'
  - 一个入门项目
- - '##'
  - 引入 KVC
- - '###'
  - 路径！路径！
- - '###'
  - 聚合攻击
- - '###'
  - 中途补给
- - '##'
  - 关键路径与运算符
- - '##'
  - KVC 并非免费午餐
- - '##'
  - 批量处理人生
- - '##'
  - nil 值依然存在
- - '##'
  - 解决此问题
- - '##'
  - 处理未处理的键
- - '##'
  - 总结
- - '#'
  - 第 19 章 使用静态分析器
- - '##'
  - 开始静态分析
- - '##'
  - 进入分析
- - '##'
  - 死存储不是吸血鬼买牛奶的地方
- - '##'
  - 密封车库
- - '##'
  - 记住你的停车位
- - '##'
  - 生不带来，死不带去
- - '##'
  - 协助分析器
- - '##'
  - 返回一个保留对象
- - '##'
  - 返回非保留对象
- - '##'
  - 返回空值
- - '##'
  - 进一步分析
- - '###'
  - 比较错误
- - '###'
  - 内存泄漏
- - '###'
  - 过度释放
- - '###'
  - 对 nil 进行同步
- - '#'
  - NSPredicate
- - '##'
  - 创建谓词
- - '##'
  - 评估谓词
- - '##'
  - 总结
- - '##'
  - 燃油滤清器
- - '##'
  - 格式说明符
- - '##'
  - Hello Operator，给我数字 9
- - '###'
  - 比较运算符与逻辑运算符
- - '##'
  - 数组运算符
- - '##'
  - 自引用（SELF）
- - '##'
  - 字符串操作
- - '##'
  - 像 (LIKE) 一样匹配，确实如此
- - '##'
  - 就这些，各位
- - '##'
  - 附录 A：从其他语言过渡到 Objective-C
- - '###'
  - 从 C 语言过渡
- - '###'
  - 从 C++过渡
- - '####'
  - C++ vtable 与 Objective-C 动态派发
- - '###'
  - Objective-C++
- - '##'
  - 内嵌于 Objective-C 的 C++ 对象
- - '##'
  - 异常处理
- - '##'
  - 如果你来自 Java 背景
- - '##'
  - 如果你来自 BASIC 背景
- - '##'
  - BASIC 的生态与过渡
- - '##'
  - 从脚本语言转向 Objective-C
- - '##'
  - 总结
- - '##'
  - 索引
