name: Learn Objective-C on the Mac
name_cn: Mac 上 Objective-C 入门指南
slug: learn-objective-c-on-the-mac
toc:
- - '##'
  - 修复过程说明
- - '##'
  - 修复后的目录
- - '#'
  - 在 Mac 上学习 Cocoa
- - '#'
  - 内容概览
- - '#'
  - 目录
- - '#'
  - 输出口、动作与控制器
- - '#'
  - 第 4 章：首次响应动作
- - '#'
  - 第 5 章：GUI 组件
- - '#'
  - 第 6 章：使用表格视图
- - '#'
  - 第 7 章：Cocoa 绑定
- - '#'
  - 第 8 章：Core Data 基础
- - '##'
  - 通过绑定启用/禁用
- - '##'
  - 通过第一响应者启用/禁用
- - '##'
  - 工作表
- - '##'
  - 总结
- - '##'
  - 创建 ColorMix 应用程序
- - '##'
  - 检查默认的 Nib 文件
- - '##'
  - 定义模型
- - '##'
  - 设置两种颜色
- - '##'
  - 最简化的 GUI
- - '##'
  - 创建默认的 ColorSet
- - '##'
  - 确定文件格式
- - '##'
  - 添加颜色
- - '##'
  - CMColorBlendView 类
- - '##'
  - 在 GUI 中添加混合颜色
- - '##'
  - 关于撤销与重做
- - '##'
  - 撤销堆栈
- - '##'
  - 总结
- - '##'
  - 异常处理
- - '##'
  - 捕获异常
- - '##'
  - 异常在 Cocoa 中的有限作用
- - '##'
  - 创建测试平台
- - '##'
  - NSInvalidArgumentException
- - '##'
  - NSRangeException
- - '##'
  - 以及其他异常
- - '##'
  - 比异常更糟：信号致死
- - '##'
  - NSError
- - '##'
  - 域与错误码
- - '##'
  - 识别错误
- - '##'
  - 呈现错误
- - '##'
  - 总结
- - '##'
  - 基础概念
- - '##'
  - 视图坐标系
- - '##'
  - 框架矩形与边界矩形
- - '##'
  - 矩形、点与尺寸
- - '##'
  - 路径基础
- - '##'
  - 创建 NSView 子类
- - '##'
  - '基本绘图方法：drawRect:'
- - '##'
  - 图形状态
- - '##'
  - 路径辅助工具
- - '##'
  - 颜色与图形上下文
- - '##'
  - 超越颜色
- - '##'
  - 手动路径构建
- - '##'
  - 突破边界
- - '##'
  - LOLmaker
- - '##'
  - LOL 第一步
- - '##'
  - LOLView
- - '##'
  - 绘制位图
- - '##'
  - 让它滚动
- - '##'
  - 绘制文本
- - '##'
  - 总结
- - '##'
  - 编辑曲线
- - '##'
  - 准备工作
- - '##'
  - 贝塞尔曲线基础架构
- - '##'
  - 绘制曲线
- - '##'
  - 监听鼠标
- - '##'
  - 细节打磨
- - '##'
  - Core Animation 入门
- - '##'
  - Core Animation 基础
- - '##'
  - 隐式动画
- - '##'
  - 显式动画
- - '##'
  - 动画分组
- - '##'
  - 总结
- - '##'
  - 隐式文件访问
- - '##'
  - 高级文件操作
- - '##'
  - 关于那个文件：代码实现
- - '#'
  - 目录
- - '##'
  - 前言
- - '##'
  - 关于作者
- - '##'
  - 关于技术审校者
- - '##'
  - 致谢
- - '###'
  - 本书大部分内容是在明尼苏达州圣保罗的 Shish 咖啡馆和 Kopplin's Coffee 完成的。如果你想品尝美味的咖啡，Kopplin's 是你最好的选择。最后，也是最重要的，彼得想感谢他的妻子莫莉·麦克贝斯，以及孩子劳雷尔和贝娅；杰克想感谢他的妻子维罗妮卡·梅杰，以及孩子亨丽埃塔和多罗特娅。他们都非常支持编写这本书所投入的时间，没有他们的帮助，这本书不可能完成。彼得和杰克将本书献给我们的家人。
- - '#'
  - 第 1 章
- - '##'
  - 必须热爱 Cocoa
- - '##'
  - 何时 25 年不等于 25 年？
- - '##'
  - 获取 Mac 并下载工具
- - '##'
  - 下载源代码
- - '##'
  - 获取帮助
- - '##'
  - 开始前须知
- - '##'
  - 初次接触 Objective-C？
- - '##'
  - 准备好了吗？
- - '#'
  - 第 2 章：Hello, World
- - '###'
  - 构建“Hello, World”
- - '###'
  - 探索 Nib 文件
- - '###'
  - 库（Library）
- - '###'
  - 拖出一个标签
- - '###'
  - 使用蓝色参考线
- - '###'
  - 检查器
- - '###'
  - 属性检查器
- - '###'
  - 更改标签的颜色和字体
- - '##'
  - 创建应用程序图标
- - '##'
  - 将图标添加到项目
- - '##'
  - 属性列表
- - '##'
  - Foundation 框架
- - '##'
  - AppKit 框架
- - '##'
  - Cocoa 之道：模型-视图-控制器
- - '##'
  - 插座变量、动作和方法、控制器
- - '###'
  - 插座变量
- - '###'
  - 动作（Actions）
- - '###'
  - 出口与动作的实践
- - '##'
  - 文本字段的属性检查器
- - '##'
  - 总结
- - '#'
  - 第 4 章
- - '##'
  - 行动的号角
- - '##'
  - 输出口与操作
- - '###'
  - 声明输出口与操作
- - '####'
  - 声明输出口
- - '####'
  - 声明操作
- - '##'
  - 但它们到底是什么？
- - '##'
  - 输出口与操作实际运用，第二幕
- - '###'
  - 占位符对象
- - '##'
  - 设置窗口
- - '##'
  - 设计窗口的界面
- - '##'
  - 创建控制器类
- - '##'
  - 声明中包含 `IBOutlet` 关键字
- - '##'
  - 实现动作方法
- - '###'
  - 嵌套消息
- - '##'
  - 运行应用
- - '##'
  - 应用委托
- - '##'
  - 应用委托与 GUI 组件
- - '##'
  - 应用委托
- - '###'
  - 配置应用程序在窗口关闭时退出
- - '###'
  - 使用文档浏览器
- - '###'
  - 小结
- - '#'
  - 第 5 章：GUI 组件
- - '##'
  - 创建 VillainTracker 应用程序
- - '##'
  - 构建界面
- - '###'
  - 摆弄文本字段
- - '###'
  - 让用户选择日期
- - '###'
  - 创建组合框
- - '###'
  - 使用级别指示器显示评级
- - '##'
  - 配置 NSLevelIndicator 以显示星级评分
- - '##'
  - 在矩阵中添加单选按钮
- - '##'
  - 添加图像视图
- - '##'
  - 在矩阵中添加复选框
- - '##'
  - 配置弹出按钮
- - '##'
  - 插入文本视图
- - '##'
  - 进行逻辑分组
- - '##'
  - 调整大小
- - '##'
  - 连接 VillainTrackerAppDelegate 类
- - '##'
  - 反派属性映射到 GUI 类
- - '##'
  - 开始编码
- - '###'
  - 标准化键名
- - '###'
  - 创建默认 Villain
- - '###'
  - 关注细节
- - '###'
  - 设置简单值
- - '###'
  - 复杂控件中的值
- - '##'
  - 响应输入
- - '##'
  - 总结
- - '#'
  - 第 6 章：使用表格视图
- - '###'
  - 为处理多个反派准备 VillainTrackerAppDelegate
- - '##'
  - 为表格视图腾出空间
- - '##'
  - 糟糕的调整大小意外，或者说，约束来救场！
- - '##'
  - 创建和编辑约束
- - '##'
  - 为表格视图腾出空间：代码篇
- - '##'
  - 章节标题：为反派数组添加支持
- - '##'
  - 表格视图需要辅助
- - '##'
  - 添加更多反派
- - '##'
  - 选择一个反派
- - '##'
  - 阻止你的邪恶行径！
- - '##'
  - 在表格视图中编辑
- - '##'
  - 总结
- - '#'
  - 第 7 章 Cocoa 绑定
- - '##'
  - 绑定到简单控件
- - '###'
  - 创建 DungeonThing 项目与偏好设置窗口
- - '###'
  - 添加标签视图
- - '##'
  - Character Generation Preferences
- - '##'
  - Monster Generation Preferences
- - '##'
  - Dungeon Generation Preferences
- - '##'
  - 绑定到 NSUserDefaultsController
- - '###'
  - Character Generation 的绑定
- - '##'
  - 怪物生成器的绑定
- - '##'
  - 地下城生成器的绑定
- - '##'
  - 创建主窗口
- - '##'
  - 设置 DungeonThingAppDelegate
- - '##'
  - 定义常量
- - '##'
  - 指定默认偏好设置值
- - '##'
  - 创建操作方法
- - '##'
  - 绑定到表视图
- - '##'
  - 使代码支持绑定
- - '###'
  - 标准 INIT 方法
- - '##'
  - 配置表视图和文本视图
- - '###'
  - 创建并配置数组控制器
- - '###'
  - 通过数组控制器绑定表格显示
- - '###'
  - 通过数组控制器的选择绑定文本字段
- - '###'
  - 填充数组
- - '###'
  - 确保一切正常
- - '###'
  - 重复实践
- - '###'
  - 好吧，但这到底是如何工作的？
- - '###'
  - 键值编码
- - '##'
  - 键值观察
- - '##'
  - Cocoa 绑定：它是如何工作的
- - '##'
  - 总结
- - '#'
  - 第 8 章 Core Data 基础
- - '##'
  - 我们一直缺失的能力
- - '##'
  - 创建 MythBase
- - '##'
  - 定义模型
- - '###'
  - 建模：是什么？
- - '##'
  - 排版后的文本
- - '##'
  - 使用 Xcode 的模型编辑器
- - '##'
  - 创建实体
- - '##'
  - 创建属性
- - '##'
  - 排版后内容
- - '###'
  - 不支持类型的属性
- - '##'
  - 设计 GUI
- - '###'
  - 自动生成 GUI
- - '###'
  - 创建 MythBase 显示界面
- - '##'
  - 绑定数组控制器
- - '##'
  - 配置表格视图的绑定
- - '##'
  - '完成绑定：保存和搜索  '
- - '##'
  - 探究模板代码
- - '###'
  - 应用程序委托接口
- - '###'
  - 应用程序委托实现
- - '####'
  - '`applicationSupportDirectory` 方法'
- - '####'
  - '`managedObjectModel` 访问器方法'
- - '##'
  - 使用 NSError 进行错误处理
- - '##'
  - persistentStoreCoordinator 访问器方法
- - '##'
  - 核心数据存储类型及相关委托
- - '##'
  - managedObjectContext 访问器方法
- - '##'
  - NSWindow 委托方法
- - '##'
  - 'saveAction: 操作方法'
- - '##'
  - NSApplication 委托方法
- - '##'
  - 添加业务逻辑
- - '###'
  - 创建 MythicalPerson 类
- - '##'
  - 验证单个属性
- - '##'
  - 验证多个属性
- - '##'
  - 创建自定义属性
- - '##'
  - Core Data 关系与迁移
- - '##'
  - 理解 Core Data 中的依赖关系
- - '##'
  - 总结
- - '#'
  - 第 9 章：Core Data 关系
- - '##'
  - 建模新实体与关系
- - '##'
  - 模型版本控制与迁移
- - '###'
  - 准备多模型版本
- - '###'
  - 添加新实体
- - '##'
  - 添加关系
- - '##'
  - 创建简单迁移
- - '###'
  - 运行时机
- - '###'
  - 更新用户界面
- - '####'
  - 创建乐队窗口
- - '###'
  - 设置 Cocoa 绑定
- - '###'
  - 为数组控制器指定有用的名称
- - '###'
  - 将人员放入乐队
- - '###'
  - 创建一个“Venue”窗口
- - '###'
  - 向“Band”窗口添加“Gig”列表
- - '##'
  - 总结 (Wrap Up)
- - '#'
  - 第 10 章 使用条件进行搜索和检索 Core Data
- - '###'
  - 创建 QuoteMonger
- - '###'
  - 创建项目及其数据模型
- - '##'
  - 数据录入窗口
- - '###'
  - 两部分的窗口
- - '####'
  - 显示节目
- - '####'
  - 录入引文
- - '##'
  - 输入一些初始引用
- - '##'
  - 创建引用查找器窗口
- - '##'
  - 使用`NSPredicate`限制结果
- - '###'
  - 创建谓词
- - '##'
  - 向搜索窗口添加谓词编辑器
- - '##'
  - 配置谓词编辑器
- - '##'
  - 保存谓词
- - '##'
  - 总结
- - '#'
  - 第 11 章：窗口、菜单与面板
- - '##'
  - NSWindow 与 NSPanel
- - '##'
  - 处理输入
- - '##'
  - 使用面板还是不用面板？
- - '##'
  - 窗口属性
- - '##'
  - 标准系统面板
- - '##'
  - 字体面板
- - '##'
  - 拥有独立 Nib 文件的控制器
- - '###'
  - 使用 NSWindowController 加载 Nib 文件
- - '##'
  - Subclassing NSWindowController
- - '##'
  - 模态窗口
- - '###'
  - NSAlert 函数
- - '###'
  - 打开面板和保存面板
- - '##'
  - 系统菜单
- - '##'
  - 标准应用程序菜单项
- - '##'
  - 自定义菜单
- - '##'
  - 使用绑定启用/禁用
- - '###'
  - 使用 First Responder 启用/禁用
- - '##'
  - 工作表
- - '##'
  - 总结
- - '#'
  - 文档排版结果
- - '##'
  - 第 12 章 基于文档的应用程序
- - '##'
  - 创建 ColorMix 应用程序
- - '##'
  - 检查默认的 Nib 文件
- - '##'
  - 定义模型
- - '##'
  - 设置两种颜色
- - '##'
  - 最简单的图形用户界面
- - '##'
  - 创建默认的 ColorSet
- - '##'
  - 确定文件格式
- - '##'
  - 添加色彩
- - '##'
  - '`CMColorBlendView` 类'
- - '##'
  - 向 GUI 中添加混合色
- - '##'
  - 关于撤销与重做
- - '##'
  - 撤销栈
- - '##'
  - 总结
- - '##'
  - 第 13 章 异常、信号、错误与调试
- - '##'
  - 异常处理
- - '###'
  - 捕获异常
- - '###'
  - Cocoa 中有限的异常角色
- - '##'
  - 创建一个测试平台
- - '###'
  - 排版后内容
- - '###'
  - 调试器
- - '###'
  - NSRangeException
- - '##'
  - 其余异常
- - '##'
  - 比异常更糟：信号致死
- - '##'
  - '`NSError`'
- - '###'
  - 域和代码
- - '###'
  - 识别错误
- - '##'
  - 当我们查看一个根本没有 `userInfo` 字典的根本性错误时，它仍然会提供一个人类可读的 `localizedDescription`，而这仅通过查看域和代码是无法直接看出的。实际上，我们可以像这样创建自己的内部和外部错误：
- - '##'
  - 展示错误
- - '##'
  - 总结
- - '##'
  - 第 14 章：Cocoa 中的绘图
- - '##'
  - 基础概念
- - '##'
  - 视图坐标系
- - '##'
  - 框架矩形 vs. 边界矩形
- - '##'
  - 图形绘制基础
- - '##'
  - 视图边界与坐标点
- - '##'
  - 矩形、点和尺寸
- - '##'
  - 路径基础
- - '##'
  - 创建 `NSView` 子类
- - '##'
  - 基本绘制方法：`drawRect:`
- - '##'
  - 图形状态
- - '##'
  - 路径辅助工具
- - '##'
  - 颜色与图形上下文
- - '##'
  - 图形上下文中的颜色管理与路径绘制
- - '##'
  - 超越颜色
- - '##'
  - 手动路径构建
- - '##'
  - 边界问题
- - '##'
  - LOLmaker
- - '###'
  - 关于 LOLcats 的一点说明
- - '###'
  - LOL 第一步
- - '##'
  - LOLView
- - '###'
  - 绘制位图
- - '##'
  - 让它滚动起来
- - '##'
  - 绘制文字
- - '##'
  - 总结
- - '##'
  - 高级绘图主题
- - '##'
  - 编辑曲线
- - '##'
  - 准备工作
- - '##'
  - 一点优化
- - '##'
  - Core Animation 入门
- - '###'
  - Core Animation 基础
- - '##'
  - 隐式动画
- - '##'
  - 显式动画
- - '##'
  - 动画分组
- - '##'
  - 总结
- - '##'
  - 第 16 章
- - '#'
  - 文件操作
- - '###'
  - 隐式文件访问
- - '###'
  - 高级文件操作
- - '###'
  - “关于那个文件？”：代码实现
- - '##'
  - 文件部分呢：GUI
- - '##'
  - 总结
- - '#'
  - 第 17 章 并发
- - '##'
  - SlowWorker
- - '##'
  - 线程基础
- - '##'
  - 工作单元
- - '##'
  - 操作队列
- - '##'
  - 成为块专家
- - '##'
  - 激活 SlowWorker
- - '##'
  - 要求主线程
- - '##'
  - 排版后的文档
- - '##'
  - GCD：底层队列
- - '##'
  - 第二次改进 SlowWorker
- - '##'
  - 不要忘记那个主线程
- - '##'
  - GCD 中的并发块
- - '##'
  - 小并发，大不同
- - '#'
  - 第 18 章
- - '##'
  - 未来之路
- - '##'
  - 更多 Cocoa 特性
- - '###'
  - 通知
- - '###'
  - Blocks
- - '####'
  - 枚举
- - '##'
  - 使用块观察通知
- - '##'
  - 为块弱化指针
- - '##'
  - 过滤
- - '##'
  - 异域风味的 Cocoa
- - '##'
  - PyObjC
- - '##'
  - MacRuby
- - '##'
  - Nu
- - '##'
  - JavaScript
- - '##'
  - Cocotron
- - '##'
  - Cappuccino/Objective-J
- - '##'
  - 一切终章
- - '#'
  - 索引
- - '##'
  - 索引
- - '##'
  - 索引
- - '##'
  - G
- - '##'
  - H
- - '##'
  - I
- - '##'
  - J
- - '##'
  - K
- - '##'
  - L
- - '##'
  - M
- - '##'
  - N
- - '##'
  - 其他
- - '##'
  - F
- - '##'
  - I
- - '##'
  - M
- - '##'
  - N
- - '##'
  - N（续）
- - '##'
  - O
- - '##'
  - P
