name: Designing for iOS with Sketch
name_cn: Sketch iOS 设计指南
slug: designing-for-ios-with-sketch
toc:
- - '##'
  - 修复说明
- - '#'
  - 1. 为什么选择 Sketch？
- - '##'
  - 一段小历史
- - '#'
  - 进入 Sketch 2
- - '##'
  - Sketch Mirror
- - '##'
  - 再见，Fontcase……
- - '##'
  - 苹果设计奖
- - '#'
  - Sketch 3
- - '##'
  - Sketch 3 界面
- - '#'
  - 位图 vs. 矢量图
- - '#'
  - Sketch 的独特优势
- - '##'
  - 社区
- - '##'
  - iOS 9
- - '###'
  - 应用切换器
- - '###'
  - 照片的新导航方式
- - '###'
  - 新的返回按钮
- - '###'
  - 新系统字体：旧金山（San Francisco）
- - '##'
  - Apple Watch
- - '##'
  - 总结
- - '#'
  - Sketch 入门
- - '##'
  - 安装
- - '#'
  - 开场介绍
- - '##'
  - 画布
- - '##'
  - 工具栏
- - '###'
  - 自定义工具栏
- - '##'
  - 图层
- - '###'
  - 选择和移动图层
- - '###'
  - 复制图层
- - '###'
  - 隐藏和锁定图层
- - '###'
  - 组
- - '###'
  - 检查器
- - '###'
  - 样式
- - '###'
  - 智能参考线
- - '##'
  - 画板
- - '##'
  - 标尺和参考线
- - '###'
  - 显示像素
- - '###'
  - 显示标尺和参考线
- - '###'
  - 显示网格
- - '###'
  - 显示布局
- - '#'
  - 快捷键
- - '##'
  - Sketch 通用快捷键
- - '##'
  - 图层快捷键（插入）
- - '##'
  - 移动、隐藏和调整图层大小的快捷键
- - '##'
  - 文本与字体快捷键
- - '##'
  - 自定义快捷键
- - '#'
  - 总结
- - '#'
  - 3. 为图形设置样式
- - '#'
  - 特殊形状
- - '#'
  - 编辑形状上的点
- - '##'
  - 直线模式
- - '##'
  - 镜像模式
- - '##'
  - 分离模式
- - '##'
  - 不对称模式
- - '#'
  - 组合形状
- - '#'
  - 自定义形状
- - '#'
  - 布尔运算
- - '##'
  - 相加
- - '##'
  - 减去
- - '##'
  - 相交
- - '##'
  - 排除
- - '#'
  - 蒙版
- - '##'
  - 轮廓蒙版
- - '###'
  - Alpha 蒙版
- - '##'
  - 扁平化
- - '##'
  - 缩放
- - '##'
  - 样式
- - '###'
  - 填充
- - '####'
  - 图案填充
- - '###'
  - 噪点填充
- - '###'
  - 渐变
- - '####'
  - 线性渐变
- - '####'
  - 径向渐变
- - '####'
  - 环形渐变
- - '####'
  - 角度渐变
- - '##'
  - 混合
- - '###'
  - 不透明度
- - '###'
  - 阴影
- - '##'
  - 模糊
- - '###'
  - 高斯模糊
- - '###'
  - 运动模糊
- - '###'
  - 缩放模糊
- - '###'
  - 背景模糊
- - '##'
  - 共享样式
- - '##'
  - 图像
- - '##'
  - 颜色调整
- - '##'
  - 总结
- - '#'
  - 4. 符号与文本
- - '#'
  - iOS 模板符号
- - '#'
  - 文本与字体
- - '#'
  - 文本检查器
- - '##'
  - 文本对齐
- - '###'
  - 路径文本
- - '###'
  - 文本轮廓
- - '###'
  - 抗锯齿与文本
- - '###'
  - 文本样式
- - '###'
  - 总结
- - '#'
  - 5. 应用设计准备
- - '##'
  - 人机界面指南
- - '##'
  - 顺从
- - '#'
  - 清晰性
- - '#'
  - 纵深性
- - '#'
  - 设备与分辨率
- - '#'
  - 使用标准 iOS 尺寸
- - '##'
  - 总结
- - '#'
  - 6. 优化你的工作流程
- - '##'
  - 自定义你的工作空间
- - '###'
  - 整理文档
- - '####'
  - 扁平化图像
- - '###'
  - 命名图层和符号
- - '###'
  - 创建自定义网格
- - '###'
  - 演示模式
- - '###'
  - 设置默认样式
- - '###'
  - 定义你的色板
- - '##'
  - 旋转工具
- - '#'
  - Sketch Mirror
- - '#'
  - 其他工作流工具
- - '##'
  - Flinto
- - '##'
  - Flinto for Mac
- - '##'
  - Marvel
- - '###'
  - Dropbox
- - '###'
  - InVision
- - '##'
  - 本章小结
- - '#'
  - 7. 使用 Sketch 为应用绘制线框图
- - '##'
  - 应用
- - '###'
  - 启动屏
- - '###'
  - 新手引导
- - '###'
  - 身份验证
- - '###'
  - 电子邮件注册
- - '###'
  - 主页
- - '###'
  - 个人资料页面
- - '###'
  - 权限
- - '###'
  - 相机拍摄
- - '##'
  - 本章小结
- - '#'
  - 8. 设计你的应用
- - '##'
  - 色彩
- - '##'
  - 准备工作
- - '##'
  - 启动画面
- - '#'
  - 引导页
- - '#'
  - 身份验证
- - '#'
  - 电子邮件注册
- - '#'
  - 主页
- - '#'
  - 设置
- - '#'
  - 个人资料页面
- - '#'
  - 权限设置
- - '#'
  - 相机拍摄
- - '#'
  - 总结
- - '#'
  - 设计你的应用图标
- - '##'
  - 什么造就了一个出色的应用？
- - '###'
  - 避免使用文字
- - '###'
  - 明智地使用色彩
- - '###'
  - 保持简洁
- - '#'
  - 受他人启发
- - '##'
  - 使用 Sketch 设计你的图标
- - '###'
  - 设置背景颜色
- - '###'
  - 创建炸弹图标
- - '###'
  - 添加光泽
- - '###'
  - 创造火花
- - '###'
  - 添加相机！
- - '###'
  - 为保持一致性所做的其他更改
- - '#'
  - 10. 导出设计资源用于开发
- - '##'
  - 哪些需要导出，哪些无需导出
- - '##'
  - 小刀图标
- - '###'
  - 从"插入"菜单切片
- - '####'
  - 导出的文件格式
- - '#####'
  - PNG
- - '#####'
  - JPEG
- - '###'
  - TIFF
- - '###'
  - PDF
- - '###'
  - EPS
- - '###'
  - SVG
- - '##'
  - 导出的尺寸选项
- - '###'
  - 快速导出法
- - '##'
  - 导出画板
- - '##'
  - 导出单个资源
- - '##'
  - 为资源创建文件夹
- - '###'
  - 裁剪背景
- - '##'
  - 总结
- - '#'
  - 11. Sketch 资源
- - '##'
  - 插件
- - '###'
  - 安装插件
- - '###'
  - Sketch Toolbox
- - '###'
  - GitHub
- - '###'
  - 我最喜欢的插件
- - '###'
  - 画板专用插件
- - '###'
  - 其他资源
- - '####'
  - 网站
- - '####'
  - 群组
- - '####'
  - 与 Sketch 集成的应用
- - '####'
  - 设计原型工具
- - '##'
  - 总结
- - '###'
  - 索引
