name: Android Software Internals Quick Reference
name_cn: Android 软件内部参考快速指南
slug: android-software-internals-quick-reference
toc:
- - '#'
  - 1. 引言
- - '##'
  - 本书内容
- - '##'
  - 本书不涵盖的内容
- - '#'
  - 2. Android 版本
- - '#'
  - 3. 基础
- - '##'
  - Android 沙箱
- - '##'
  - 应用程序组件
- - '###'
  - 活动（Activities）
- - '####'
  - 服务（Services）
- - '###'
  - 广播接收器（Broadcast Receivers）
- - '###'
  - 内容提供器（Content Providers）
- - '###'
  - 清单文件（Manifest）
- - '#'
  - 4. 权限
- - '#'
  - 5. 上下文
- - '##'
  - 应用程序上下文
- - '##'
  - Activity 上下文
- - '#'
  - 6. Activity 生命周期
- - '###'
  - '`onCreate()`'
- - '###'
  - '`onStart()`'
- - '###'
  - '`onResume()`'
- - '###'
  - '`onPause()`'
- - '###'
  - '`onStop()`'
- - '###'
  - '`onRestart()`'
- - '#'
  - 7. Android 用户
- - '##'
  - Linux 用户
- - '##'
  - Android 用户
- - '#'
  - 8. 脚注
- - '#'
  - 9. Intent
- - '##'
  - 启动组件
- - '##'
  - Intent 属性
- - '###'
  - 核心属性
- - '###'
  - 附加属性
- - '###'
  - 操作（Actions）
- - '###'
  - 类别（Categories）
- - '###'
  - 附加信息（Extras）
- - '#'
  - 10. 获取输入名称并查看输入事件发生时间
- - '#'
  - 11. 返回输入是否正在使用。用于识别屏幕是否正在使用。
- - '#'
  - 12. 向输入设备发送事件。例如，在我的设备上，以下命令将音量设置为 0。
- - '#'
  - 13. 返回内核版本
- - '#'
  - 14. 也返回内核版本以及设备架构。
- - '#'
  - 15. 以 root 身份访问应用程序用作内部存储的位置。
- - '#'
  - 16. 例如，访问 Chrome 中保存的离线页面，并将其存储在 data/local/tmp 目录中，以便后续从设备中拉取。
- - '##'
  - 以编程方式运行命令
- - '#'
  - 17. 反编译和反汇编 Android 应用程序
- - '##'
  - 反编译的 Java
- - '##'
  - 反汇编的 Dalvik 字节码（Smali）
- - '##'
  - 从运行中的设备提取 APK
- - '##'
  - 脚注
- - '#'
  - 18. 结语
- - '##'
  - 脚注
- - '#'
  - 19. 索引
