name: UI Design for IOS App Development
name_cn: iOS 应用开发的 UI 设计
slug: ui-design-for-ios-app-development
toc:
- - '#'
  - 1. 介绍 SwiftUI
- - '##'
  - 练习
- - '##'
  - 概念
- - '##'
  - 唯一数据源
- - '##'
  - 老朋友
- - '##'
  - 新朋友
- - '##'
  - Combine
- - '##'
  - 一切都好
- - '##'
  - 平台
- - '##'
  - 开始编码吧！
- - '#'
  - 2. 放轻松
- - '##'
  - 代码 + 界面
- - '##'
  - 你的第一个 SwiftUI 应用
- - '##'
  - 你好，SwiftUI
- - '##'
  - 修饰符
- - '##'
  - SwiftUI 检查器
- - '###'
  - 属性检查器
- - '##'
  - 堆叠中的堆叠
- - '##'
  - 重点来了
- - '##'
  - 用户界面练习
- - '##'
  - 章节总结
- - '#'
  - 3. SwiftUI 构建块
- - '##'
  - 老友与新交
- - '##'
  - 按钮
- - '###'
  - 在用户界面中创建一个按钮
- - '###'
  - 本练习中我们做了什么？
- - '###'
  - 按钮参数
- - '##'
  - 图像
- - '###'
  - SF Symbols
- - '####'
  - 添加一个图像
- - '###'
  - 图像创建
- - '##'
  - 开关
- - '###'
  - 绑定
- - '###'
  - '`@State` 属性包装器'
- - '###'
  - Toggle 标签
- - '##'
  - Toggle 练习
- - '###'
  - 当前代码
- - '##'
  - TextField
- - '###'
  - 添加一个 `TextField`
- - '##'
  - 章节总结
- - '#'
  - 4. 绑定数据源
- - '##'
  - 数据驱动 UI
- - '##'
  - 流程步骤
- - '###'
  - UI 中的计数器更新
- - '##'
  - 可步进类型 (Strideable)
- - '##'
  - 属性包装器 (Property Wrapper)
- - '###'
  - '`@Binding`'
- - '###'
  - 章节总结
- - '#'
  - 5. 可观察对象
- - '##'
  - 典型模型
- - '###'
  - 构建笔记界面
- - '##'
  - 绑定？
- - '##'
  - 观察引用对象
- - '##'
  - ObservableObject 协议
- - '###'
  - 发布更新
- - '##'
  - '@Published'
- - '##'
  - 本章小结
- - '#'
  - 6. 环境值
- - '##'
  - 环境值
- - '###'
  - 每个视图的设置
- - '###'
  - 应用环境
- - '##'
  - '`EnvironmentObject` 属性包装器'
- - '###'
  - 预览环境
- - '###'
  - 用法
- - '##'
  - 自定义环境值
- - '##'
  - 章节总结
- - '#'
  - 7. 项目列表
- - '##'
  - List
- - '###'
  - NoteRow 视图
- - '##'
  - 创建笔记列表
- - '###'
  - 模型列表
- - '##'
  - 在列表中删除项目
- - '##'
  - 本章小结
- - '#'
  - 8. SwiftUI Canvas 预览
- - '##'
  - 编译
- - '##'
  - 预览提供器
- - '##'
  - 预览设备
- - '##'
  - 环境
- - '###'
  - 预览布局
- - '##'
  - NoteRow 中的文本大小
- - '##'
  - 固定预览
- - '##'
  - 章节总结
- - '##'
  - 为预览而设计
- - '###'
  - 预览内容
- - '###'
  - 预览 JSON
- - '###'
  - 模型
- - '###'
  - 视图模型
- - '###'
  - 视图
- - '###'
  - 预览
- - '##'
  - 预览测试数据
- - '###'
  - 预览资源
- - '##'
  - 在 ContentView 中使用 NoteRow
- - '##'
  - 实时模式
- - '##'
  - 章节总结
- - '#'
  - 10. SwiftUI 导航
- - '##'
  - 点击手势
- - '##'
  - 模态导航
- - '##'
  - 导航视图
- - '###'
  - 导航链接
- - '##'
  - 为 ListProject 添加导航
- - '##'
  - 章节总结
- - '#'
  - 11. SwiftUI 中的 UIKit
- - '##'
  - '`UIViewRepresentable`'
- - '###'
  - '`NoteView`'
- - '###'
  - 使用`NoteView`显示详情
- - '##'
  - 提取视图
- - '##'
  - SwiftUI 中的 `UIView`
- - '###'
  - SwiftUI 中的 `UITextView`
- - '###'
  - 章节摘要
- - '#'
  - 12. 通过协调器从 UIKit 获取数据
- - '##'
  - UIViewPresentable 协议
- - '##'
  - 协调器
- - '##'
  - 绑定属性包装器
- - '##'
  - 将协调器作为委托
- - '##'
  - 替代语法
- - '##'
  - '`TextView` 的协调器'
- - '##'
  - 更新列表
- - '##'
  - 本章小结
- - '#'
  - 13. SwiftUI 中的目标/动作模式
- - '###'
  - 目标/动作
- - '###'
  - ButtonView
- - '###'
  - SwiftUI 中的 UIView
- - '###'
  - 添加协调器
- - '##'
  - 章节总结
- - '#'
  - 14. SwiftUI in UIKit
- - '##'
  - '`UIHostingController`'
- - '##'
  - 向 UIKit 添加 SwiftUI 视图
- - '##'
  - 现有项目
- - '###'
  - 添加 SwiftUI
- - '##'
  - 将计时器视图添加到 UIKit
- - '###'
  - 传递 ObservableObject
- - '##'
  - 使 TimerItem 可观察
- - '##'
  - 本章小结
- - '#'
  - 15. Combine 框架入门
- - '##'
  - 常见概念
- - '###'
  - 发布者与订阅者
- - '##'
  - 转换至 Combine
- - '##'
  - 改进优化
- - '##'
  - Sink 订阅者
- - '###'
  - 分配订阅者
- - '##'
  - 操作符
- - '##'
  - '@Published 属性包装器'
- - '##'
  - 章节总结
- - '#'
  - 16. URLSession 发布者
- - '##'
  - URLSession 发布者
- - '###'
  - 状态跟踪器项目
- - '###'
  - 状态跟踪器 UI
- - '###'
  - 模型管理器
- - '##'
  - 使用发布者获取数据
- - '##'
  - 调试数据
- - '###'
  - 排版后的文本
- - '##'
  - 章节总结
- - '#'
  - 17. 过渡与动画
- - '###'
  - 过渡效果
- - '##'
  - 文本的过渡效果
- - '##'
  - 非对称过渡
- - '###'
  - 非对称过渡
- - '###'
  - 动画
- - '##'
  - 为更改添加动画
- - '##'
  - ViewModifier 协议
- - '###'
  - 创建视图修饰符
- - '###'
  - 渐变
- - '##'
  - 为圆形添加颜色
- - '##'
  - 旋转
- - '###'
  - 添加旋转效果
- - '##'
  - '`DrawingGroup`'
- - '###'
  - 在 Swift 中使用 Metal
- - '###'
  - 章节总结
- - '#'
  - 18. 包含 WatchKit 的应用
- - '###'
  - 属性
- - '###'
  - UI 设计
- - '##'
  - 小费计算器
- - '###'
  - WatchKit
- - '###'
  - 章节总结
- - '#'
  - 19. 用户输入表单
- - '##'
  - 表单
- - '##'
  - 分区
- - '##'
  - 应用需求
- - '###'
  - WatchKit
- - '###'
  - 章节总结
- - '#'
  - 20. 呈现弹出窗口
- - '##'
  - 警告修饰器
- - '###'
  - 带对象绑定的警告
- - '##'
  - 操作表修饰符
- - '##'
  - 操作表
- - '##'
  - Sheet 修饰符
- - '###'
  - 弹出视图修饰符
- - '###'
  - 章节总结
- - '##'
  - 索引
