name: Beginning iPhone development with Swift
name_cn: Swift iPhone 开发入门指南
slug: beginning-iphone-development-with-swift
toc:
- - '#'
  - 1. 理解 iOS 编程
- - '#'
  - 了解 Xcode
- - '##'
  - 操控 Xcode 面板
- - '##'
  - 总结
- - '#'
  - 2. 使用 SwiftUI 设计用户界面
- - '##'
  - 使用检查器面板修改用户界面
- - '##'
  - 摘要
- - '#'
  - 3. 在用户界面上放置视图
- - '##'
  - 使用填充修饰符
- - '##'
  - 在堆栈内定义间距
- - '##'
  - 在堆栈中对齐视图
- - '##'
  - 使用间距器
- - '##'
  - 使用偏移与位置修饰符
- - '##'
  - 总结
- - '#'
  - 4. 文本处理
- - '##'
  - 更改文本外观
- - '##'
  - 使用标签视图
- - '###'
  - 为文本或标签视图添加边框
- - '##'
  - 总结
- - '#'
  - 5. 使用图像
- - '##'
  - 显示形状
- - '###'
  - 为形状着色
- - '###'
  - 使用渐变给形状着色
- - '##'
  - 显示图像
- - '###'
  - 裁剪图像
- - '###'
  - 为图像添加阴影
- - '###'
  - 为图像添加边框
- - '###'
  - 定义图像的不透明度
- - '##'
  - 总结
- - '#'
  - 6. 使用按钮和分段控件响应用户操作
- - '##'
  - 在按钮中运行代码
- - '##'
  - 使用分段控件
- - '###'
  - 从分段控件运行代码
- - '##'
  - 总结
- - '#'
  - 7. 从文本字段和文本编辑器中检索文本
- - '##'
  - 使用文本字段
- - '###'
  - 更改文本字段样式
- - '###'
  - 创建安全文本字段
- - '###'
  - 使用自动更正和文本内容类型
- - '###'
  - 定义不同的键盘
- - '####'
  - 隐藏虚拟键盘
- - '###'
  - 使用文本编辑器
- - '##'
  - 概述
- - '#'
  - 8. 使用选择器限制选择
- - '##'
  - 使用选择器
- - '##'
  - 使用 `ColorPicker`
- - '##'
  - 使用 `DatePicker`
- - '###'
  - 选择日期选择器样式
- - '###'
  - 显示日期和/或时间
- - '###'
  - 限制日期范围
- - '###'
  - 格式化日期
- - '###'
  - 总结
- - '#'
  - 9. 使用开关、步进器和滑块限制选择
- - '##'
  - 使用开关
- - '##'
  - 使用步进器
- - '###'
  - 定义步进器的范围
- - '####'
  - 在步进器中定义增量/减量值
- - '##'
  - 使用滑块
- - '###'
  - 更改滑块的颜色
- - '###'
  - 为滑块定义范围
- - '###'
  - 为滑块定义步进增量
- - '###'
  - 在滑块上显示最小值和最大值标签
- - '##'
  - 总结
- - '#'
  - 10. 通过链接和菜单提供选项
- - '##'
  - 使用链接
- - '##'
  - 使用菜单
- - '###'
  - 格式化菜单和按钮上的标题
- - '###'
  - 添加子菜单
- - '##'
  - 总结
- - '#'
  - 11. 触摸手势
- - '##'
  - 检测轻点手势
- - '##'
  - 检测长按手势
- - '##'
  - 检测缩放手势
- - '##'
  - 检测旋转手势
- - '##'
  - 检测拖动手势
- - '##'
  - 定义优先级与同时手势
- - '###'
  - 定义高优先级手势
- - '###'
  - 定义同时手势
- - '##'
  - 总结
- - '#'
  - 12. 使用警告框、操作列表和上下文菜单
- - '##'
  - 显示警告框/操作列表
- - '###'
  - 显示和响应多个按钮
- - '###'
  - 使 Alert/ActionSheet 按钮可响应
- - '##'
  - 使用上下文菜单
- - '##'
  - 总结
- - '#'
  - 13. 显示列表
- - '##'
  - 在列表中显示数组数据
- - '##'
  - 在列表中显示结构体数组
- - '##'
  - 在列表中创建分组
- - '##'
  - 为列表添加行分隔线
- - '##'
  - 为列表添加滑动手势
- - '###'
  - 从列表中删除项目
- - '####'
  - 在列表中移动项目
- - '###'
  - 为列表创建自定义滑动操作
- - '##'
  - 总结
- - '#'
  - 14. 使用表单和分组框
- - '##'
  - 创建简单表单
- - '###'
  - 将表单划分为分区
- - '##'
  - 在表单中禁用视图
- - '##'
  - 使用分组框
- - '##'
  - 总结
- - '#'
  - 15. 使用 Disclosure Groups、Scroll Views 和 Outline Groups
- - '##'
  - 使用 Disclosure Group
- - '##'
  - 使用 Scroll View
- - '##'
  - 使用大纲组
- - '##'
  - 总结
- - '#'
  - 16. 使用导航视图
- - '##'
  - 使用导航视图
- - '###'
  - 向导航栏添加按钮
- - '##'
  - 为导航视图添加链接
- - '###'
  - 在导航视图中显示结构
- - '####'
  - 在导航视图中传递数据
- - '###'
  - 在导航视图中改变结构体间的数据
- - '###'
  - 在导航视图中实现结构体间数据共享
- - '###'
  - 在导航视图中使用列表
- - '##'
  - 总结
- - '#'
  - 17. 使用标签视图
- - '##'
  - 使用标签视图
- - '###'
  - 在标签栏中以编程方式选择按钮
- - '###'
  - 显示页面视图
- - '##'
  - 在标签视图中显示结构
- - '###'
  - 在标签视图中的结构之间传递数据
- - '###'
  - 在标签视图中更改结构体之间的数据
- - '###'
  - 在标签页视图中在结构体之间共享数据
- - '##'
  - 总结
- - '#'
  - 18. 使用网格
- - '##'
  - 定义多行/多列
- - '###'
  - 调整行/列间距
- - '##'
  - 总结
- - '#'
  - 19. 使用动画
- - '##'
  - 移动动画
- - '##'
  - 缩放动画
- - '##'
  - 旋转动画
- - '##'
  - 动画选项
- - '###'
  - 在动画中使用延迟和持续时间
- - '###'
  - 在动画中使用插值弹簧
- - '##'
  - 使用`withAnimation`
- - '##'
  - 总结
- - '#'
  - 20. 使用 `GeometryReader`
- - '##'
  - 理解 `GeometryReader`
- - '##'
  - 理解全局坐标与局部坐标的区别
- - '##'
  - 识别 GeometryReader 的最小值、中值和最大值
- - '##'
  - 总结
- - '#'
  - 索引
- - '##'
  - A
- - '###'
  - 警告/操作列表
- - '###'
  - 动画
- - '##'
  - B
- - '###'
  - 按钮
- - '##'
  - C
- - '###'
  - 上下文菜单
- - '##'
  - D, E
- - '###'
  - 可展开列表
- - '##'
  - F
- - '###'
  - 表单/分组框
- - '##'
  - G, H
- - '###'
  - 几何形状
- - '###'
  - GeometryReader
- - '###'
  - 网格
- - '###'
  - 分组框
- - '##'
  - I, J, K
- - '###'
  - 图像
- - '##'
  - L
- - '###'
  - 链接/菜单
- - '###'
  - 列表
- - '##'
  - M
- - '###'
  - 菜单
- - '##'
  - N
- - '###'
  - 导航视图
- - '##'
  - O
- - '###'
  - Objective-C
- - '###'
  - 面向对象编程 (OOP)
- - '###'
  - 大纲视图
- - '##'
  - P, Q
- - '###'
  - 填充修饰符
- - '###'
  - 选择器
- - '###'
  - 放置视图 (用户界面)
- - '##'
  - R
- - '###'
  - 检索文本
- - '##'
  - S
- - '###'
  - 滚动视图
- - '###'
  - 安全输入框
- - '###'
  - 分段控件
- - '###'
  - 滑块
- - '###'
  - 间距器
- - '###'
  - 步进器
- - '###'
  - 存储数据
- - '##'
  - T, U, V, W
- - '###'
  - 标签视图
- - '###'
  - 文本编辑器
- - '###'
  - 文本输入框
- - '###'
  - 文本信息
- - '###'
  - 切换开关
- - '###'
  - 触摸手势
- - '##'
  - X, Y, Z
- - '###'
  - Xcode 项目
