name: Beginning IOS 5 Development
name_cn: IOS 5开发入门指南
slug: beginning-ios-5-development
toc:
- - '#'
  - 开始 iOS 5 开发：探索 iOS SDK
- - '##'
  - 内容概览
- - '#'
  - 目录
- - '##'
  - 关于作者
- - '#'
  - 关于技术审校者
- - '#'
  - 序言
- - '#'
  - 第 1 章
- - '##'
  - 欢迎来到丛林
- - '###'
  - 本书内容
- - '###'
  - 你需要什么
- - '####'
  - 开发者选项
- - '####'
  - 你需要了解的知识
- - '###'
  - 为 iOS 编码有何不同？
- - '####'
  - 只有一个活动应用
- - '####'
  - 只有一个窗口
- - '###'
  - 受限的访问权限
- - '###'
  - 有限的响应时间
- - '###'
  - 有限的屏幕尺寸
- - '###'
  - 有限的系统资源
- - '###'
  - 没有垃圾回收，但是…
- - '###'
  - 一些新功能
- - '###'
  - 一种不同的交互方式
- - '###'
  - 本章更新内容
- - '###'
  - 你准备好了吗？
- - '#'
  - 第 2 章
- - '##'
  - 安抚提基之神
- - '###'
  - 在 Xcode 中设置你的项目
- - '####'
  - Xcode 工作区窗口
- - '#####'
  - 工具栏
- - '###'
  - 导航视图
- - '###'
  - 跳转栏
- - '###'
  - Xcode 键盘快捷键
- - '###'
  - 工具面板
- - '###'
  - 界面生成器
- - '###'
  - 新编译器和调试器
- - '####'
  - 深入了解我们的项目
- - '###'
  - Xcode 的界面生成器介绍
- - '####'
  - Nib 文件中有什么？
- - '####'
  - 库
- - '####'
  - 向视图中添加标签
- - '####'
  - 更改属性
- - '###'
  - 一点 iPhone 润色——收尾工作
- - '###'
  - 排版后的内容
- - '###'
  - 本章小结
- - '#'
  - 第 3 章
- - '##'
  - 处理基本交互
- - '###'
  - 模型-视图-控制器范式
- - '###'
  - 创建我们的项目
- - '###'
  - 查看视图控制器
- - '###'
  - 理解输出口与动作方法
- - '###'
  - 输出口
- - '###'
  - 动作方法
- - '###'
  - 清理视图控制器
- - '###'
  - 设计用户界面
- - '###'
  - 添加按钮和操作方法
- - '###'
  - 连接操作与输出口
- - '####'
  - 添加标签和输出口
- - '###'
  - 编写操作方法
- - '###'
  - 消息嵌套
- - '###'
  - 尝试运行
- - '###'
  - 查看应用委托
- - '###'
  - 回到正题
- - '#'
  - 第 4 章
- - '##'
  - 更多用户界面趣味
- - '###'
  - 满屏控件
- - '###'
  - 活动控件、静态控件与被动控件
- - '###'
  - 创建应用
- - '###'
  - 实现图像视图与文本字段
- - '####'
  - 添加图像视图
- - '####'
  - 调整图像视图尺寸
- - '####'
  - 设置视图属性
- - '#####'
  - 模式属性
- - '###'
  - 标签
- - '###'
  - 透明度值
- - '###'
  - 背景
- - '###'
  - 拉伸
- - '####'
  - 添加文本字段
- - '###'
  - 文本字段检查器设置
- - '###'
  - 设置第二个文本字段的属性
- - '###'
  - 创建并连接输出口
- - '###'
  - 关闭键盘
- - '####'
  - 点击“完成”时关闭键盘
- - '####'
  - 触摸背景关闭键盘
- - '###'
  - 添加滑块和标签
- - '####'
  - 创建并连接操作和插座
- - '####'
  - 实现操作方法
- - '###'
  - 实现开关、按钮和分段控件
- - '####'
  - 添加两个带标签的开关
- - '###'
  - 连接并创建输出口和操作
- - '###'
  - 实现开关操作
- - '###'
  - 添加按钮
- - '###'
  - 连接并创建按钮的输出口和操作
- - '###'
  - 实现分段控件的操作
- - '###'
  - 实现操作表和警告框
- - '###'
  - 遵循操作表单代理方法
- - '###'
  - 显示操作表单
- - '###'
  - 美化按钮
- - '###'
  - 使用 `viewDidLoad` 方法
- - '###'
  - 控制状态
- - '###'
  - 可拉伸图像
- - '###'
  - 冲过终点线
- - '#'
  - 第 5 章
- - '##'
  - 自动旋转与自动调整大小
- - '###'
  - 自动旋转的机制
- - '###'
  - 点、像素与视网膜显示屏
- - '###'
  - 自动旋转的实现方法
- - '###'
  - 使用自动调整大小属性处理旋转
- - '####'
  - 配置支持的方向
- - '####'
  - 指定旋转支持
- - '####'
  - 设计具有自动调整大小属性的界面
- - '####'
  - 使用尺寸检查器的自动调整大小属性
- - '####'
  - 设置按钮的自动调整大小属性
- - '###'
  - 旋转时重构视图
- - '###'
  - 创建并连接输出口
- - '###'
  - 在旋转时移动按钮
- - '###'
  - 交换视图
- - '####'
  - 设计两个视图
- - '####'
  - 实现切换
- - '####'
  - 更改插座集合
- - '###'
  - 旋转出此处
- - '#'
  - 第 6 章
- - '##'
  - 多视图应用程序
- - '###'
  - 常见的多视图应用程序类型
- - '###'
  - 多视图应用程序的架构
- - '####'
  - 根控制器
- - '####'
  - 内容视图的结构
- - '###'
  - 构建视图切换器
- - '####'
  - 创建我们的视图控制器和 Nib 文件
- - '####'
  - 修改应用委托
- - '####'
  - 修改`BIDSwitchViewController.h`
- - '####'
  - 添加视图控制器
- - '###'
  - 使用工具栏构建视图
- - '###'
  - 编写根视图控制器
- - '###'
  - 实现内容视图
- - '###'
  - 动画转场
- - '###'
  - 切换结束
- - '#'
  - 第 7 章
- - '##'
  - 标签栏与选择器
- - '###'
  - Pickers 应用
- - '###'
  - 委托和数据源
- - '###'
  - 设置标签栏框架
- - '####'
  - 创建文件
- - '####'
  - 添加根视图控制器
- - '###'
  - '`CreatingTabBarController.xib`'
- - '###'
  - 初始测试运行
- - '###'
  - 实现日期选择器
- - '###'
  - 实现单组件选择器
- - '####'
  - 声明输出口和操作
- - '####'
  - 将控制器实现为数据源和代理
- - '###'
  - 实现多组件选择器
- - '####'
  - 声明输出口与操作方法
- - '####'
  - 构建视图
- - '####'
  - 实现控制器
- - '####'
  - 实现依赖组件
- - '###'
  - 使用自定义选择器创建一个简单游戏
- - '####'
  - 编写控制器头文件
- - '####'
  - 构建视图
- - '####'
  - 添加图片资源
- - '####'
  - 实现控制器
- - '#####'
  - '`spin` 方法'
- - '###'
  - '`viewDidLoad` 方法'
- - '####'
  - 最终细节
- - '###'
  - 链接音频工具箱框架
- - '###'
  - 最终旋转
- - '#'
  - 第 8 章
- - '##'
  - 表视图入门
- - '###'
  - 表视图基础
- - '####'
  - 表视图与表视图单元格
- - '####'
  - 分组表与纯表
- - '###'
  - 实现一个简单表格
- - '####'
  - 设计视图
- - '####'
  - 编写控制器
- - '###'
  - 添加图片
- - '###'
  - 使用表格视图单元格样式
- - '####'
  - 设置缩进级别
- - '####'
  - 处理行选择
- - '####'
  - 更改字体大小与行高
- - '###'
  - 自定义表格视图单元格
- - '###'
  - 向表格视图单元格添加子视图
- - '###'
  - 创建 UITableViewCell 子类
- - '####'
  - 添加新单元格
- - '###'
  - 实现控制器的代码
- - '####'
  - 从 Nib 加载 `UITableViewCell`
- - '#####'
  - 在 Interface Builder 中设计表格视图单元格
- - '###'
  - 使用新的表视图单元格
- - '###'
  - 分组与索引分区
- - '####'
  - 构建视图
- - '####'
  - 导入数据
- - '####'
  - 实现控制器
- - '####'
  - 添加索引
- - '###'
  - 实现搜索栏
- - '####'
  - 重新思考设计方案
- - '####'
  - 深层可变复制
- - '###'
  - 更新控制器头文件
- - '###'
  - 修改视图
- - '###'
  - 修改控制器实现
- - '#####'
  - 从 allNames 复制数据
- - '#####'
  - 实现搜索
- - '###'
  - '`viewDidLoad` 的修改'
- - '###'
  - 数据源方法的修改
- - '###'
  - 添加表格视图委托方法
- - '###'
  - 添加搜索栏委托方法
- - '###'
  - 在索引中添加放大镜图标
- - '####'
  - 向键数组添加特殊值
- - '####'
  - 抑制节标题
- - '####'
  - 告诉表格视图如何响应
- - '###'
  - 全盘托出
- - '#'
  - 第 9 章
- - '##'
  - 导航控制器与表格视图
- - '###'
  - 导航控制器基础
- - '####'
  - 栈的妙用
- - '####'
  - 控制器栈
- - '###'
  - Nav，一个六部分的分层应用程序
- - '####'
  - 认识子控制器
- - '#####'
  - 展开按钮视图
- - '#####'
  - 复选框视图
- - '#####'
  - 行控制视图
- - '#####'
  - 可移动行视图
- - '#####'
  - 可删除行视图
- - '#####'
  - 可编辑详细信息视图
- - '####'
  - Nav 应用程序的骨架
- - '###'
  - 创建顶层视图控制器
- - '###'
  - 设置导航控制器
- - '####'
  - 将图像添加到项目
- - '####'
  - 第一个子控制器：披露按钮视图
- - '###'
  - 创建详情视图
- - '###'
  - 修改信息披露按钮控制器
- - '####'
  - 添加一个公开按钮控制器实例
- - '###'
  - 第二个子控制器：清单
- - '###'
  - 创建复选标记视图
- - '###'
  - 添加待办清单控制器实例
- - '###'
  - 第三个子控制器：表格行上的控件
- - '####'
  - 创建行控件视图
- - '###'
  - 添加行控件控制器实例
- - '###'
  - 第四个子控制器：可移动行
- - '###'
  - 创建可移动行视图
- - '####'
  - 添加“移动我”控制器实例
- - '###'
  - 第五个子控制器：可删除行
- - '###'
  - 创建可删除行视图
- - '####'
  - 添加“删除我”控制器实例
- - '###'
  - 第六个子控制器：可编辑的详情面板
- - '###'
  - 创建数据模型对象
- - '###'
  - 创建详细信息列表控制器
- - '####'
  - 创建详情视图控制器
- - '###'
  - 添加可编辑详情视图控制器实例
- - '###'
  - 但还有一件事……
- - '###'
  - 冲破终点线
- - '#'
  - 第 10 章
- - '##'
  - 故事板
- - '###'
  - 创建简单的故事板
- - '###'
  - 动态原型单元格
- - '####'
  - 动态表格内容，故事板风格
- - '####'
  - 编辑原型单元格
- - '###'
  - 好旧式表格视图数据源
- - '####'
  - 它会加载吗？
- - '###'
  - 静态单元格
- - '####'
  - 静态化
- - '####'
  - 再见，老朋友表格视图数据源
- - '###'
  - 你说 Segue，我说 Segue
- - '####'
  - 创建 Segue Navigator
- - '####'
  - 填充空白画布
- - '####'
  - 第一个转场
- - '####'
  - 一个稍微更有用的任务列表
- - '###'
  - 查看任务详情
- - '###'
  - 创建更多 Segue
- - '###'
  - 从列表中传递任务
- - '###'
  - 键值编码
- - '####'
  - 为什么要使用 KVC 而不是直接设置代理？KVC 的一个好处是它使我们无需了解其他类接口的具体细节，从而实现了更松散的代码耦合。如果我们想直接调用方法，就需要声明某种包含`setDelegate:`方法的接口，并将目标变量转换为实现了该方法的类型。使用
    KVC，我们的代码不需要了解`setDelegate:`方法的任何信息（除了接收方能够响应它），因此我们不需要声明任何接口。`BIDTaskListController`不会导入`BIDTaskDetailController`的头文件，实际上甚至不知道它的存在，这是一件好事！通常，类之间的依赖关系越少越好。正确应用
    KVC 可以帮助你朝着这个方向改进代码。
- - '###'
  - 处理任务详情
- - '###'
  - 传回详情
- - '####'
  - 让列表接收详细信息
- - '####'
  - 要是能用平滑过渡收尾就好了
- - '#'
  - 第 11 章
- - '##'
  - iPad 相关考量
- - '###'
  - 分割视图与弹出框
- - '###'
  - 创建一个 SplitView 项目
- - '###'
  - 故事板定义了结构
- - '###'
  - 代码定义了功能
- - '###'
  - 应用委托
- - '####'
  - 主视图控制器
- - '###'
  - 详情视图控制器
- - '###'
  - 总统登场
- - '####'
  - 本节最后一项调整纯粹是外观上的。当您在横屏模式下运行此应用时，左侧导航视图上方的标题仍然是*Master*。请切换到竖屏模式，点击*Presidents*工具栏按钮，您会看到相同的标题。
- - '###'
  - 创建自己的弹出框
- - '###'
  - 什么是**保留循环**？
- - '###'
  - iPad 应用开发：Popover 与 Split View
- - '###'
  - iPad 总结
- - '#'
  - 第 12 章
- - '##'
  - 应用设置与用户默认值
- - '###'
  - 了解设置 Bundle
- - '###'
  - AppSettings 应用
- - '####'
  - 创建项目
- - '####'
  - 使用设置包
- - '#####'
  - 向项目添加设置包
- - '###'
  - 设置属性列表
- - '####'
  - 添加文本字段设置
- - '####'
  - 添加应用程序图标
- - '####'
  - 添加安全文本字段设置
- - '###'
  - 添加多值字段
- - '###'
  - 添加切换开关设置
- - '###'
  - 添加滑块设置
- - '###'
  - 向设置捆绑包中添加图标
- - '###'
  - 添加子设置视图
- - '###'
  - 在应用中读取设置
- - '###'
  - 获取用户设置
- - '###'
  - 创建主视图
- - '###'
  - 更新主视图控制器
- - '###'
  - 注册默认值
- - '####'
  - 更改应用程序的默认设置
- - '###'
  - 保持同步
- - '###'
  - 基本数据持久化
- - '####'
  - 斯科蒂，带我走
- - '#'
  - 第 13 章
- - '##'
  - 基本数据持久化
- - '###'
  - 应用的沙盒
- - '####'
  - 获取 Documents 目录
- - '####'
  - 获取 tmp 目录
- - '###'
  - 文件存储策略
- - '####'
  - 单文件持久化
- - '####'
  - 多文件持久化
- - '###'
  - 使用属性列表
- - '####'
  - 属性列表序列化
- - '###'
  - 持久化应用程序的第一个版本
- - '####'
  - 创建持久化项目
- - '####'
  - 设计持久化应用程序视图
- - '####'
  - 编辑持久化类
- - '###'
  - 归档模型对象
- - '####'
  - 遵循 NSCoding
- - '####'
  - 实现 NSCopying
- - '###'
  - 数据对象的归档与解档
- - '###'
  - 归档应用
- - '####'
  - 实现 BIDFourLines 类
- - '####'
  - 实现 `BIDViewController` 类
- - '###'
  - 使用 iOS 的嵌入式 SQLite3
- - '####'
  - 创建或打开数据库
- - '####'
  - 使用绑定变量
- - '###'
  - SQLite3 应用
- - '####'
  - 链接到 SQLite3 库
- - '####'
  - 修改持久化视图控制器
- - '###'
  - 使用 Core Data
- - '####'
  - 实体与托管对象
- - '####'
  - 键值编码
- - '####'
  - 综合上下文
- - '####'
  - 创建新的托管对象
- - '####'
  - 检索托管对象
- - '###'
  - Core Data 应用实践
- - '####'
  - 设计数据模型
- - '###'
  - 创建持久化视图与控制器
- - '###'
  - 使持久化视图控制器成为应用程序的根控制器
- - '###'
  - 坚持终有回报
- - '#'
  - 第 14 章
- - '##'
  - 嘿！就是你！快上 iCloud！
- - '###'
  - 使用 UIDocument 管理文档存储
- - '####'
  - 构建 TinyPix
- - '###'
  - 创建 `BIDTinyPixDocument`
- - '####'
  - 我们的文档类只需要这些
- - '###'
  - 代码大师
- - '####'
  - 初始故事板
- - '####'
  - 创建 BIDTinyPixView
- - '###'
  - 故事板细节处理
- - '###'
  - 添加 iCloud 支持
- - '###'
  - 创建配置文件（Provisioning Profile）
- - '###'
  - 启用 iCloud 授权
- - '####'
  - 如何查询
- - '####'
  - 保存在哪里？
- - '###'
  - 未涉及的内容
- - '#'
  - 第 15 章
- - '##'
  - 中央调度、后台处理与你
- - '###'
  - 中央调度
- - '###'
  - 认识 SlowWorker
- - '###'
  - 线程基础
- - '###'
  - 工作单元
- - '###'
  - GCD：底层队列
- - '###'
  - 认识 Block
- - '###'
  - 改进 SlowWorker
- - '###'
  - 别忘了主线程
- - '###'
  - 提供一些反馈
- - '###'
  - 并发块
- - '###'
  - 后台处理
- - '####'
  - 应用生命周期
- - '####'
  - 状态变更通知
- - '####'
  - 创建状态实验室
- - '###'
  - 探索执行状态
- - '###'
  - 利用执行状态变化
- - '####'
  - 活动 ![images](img/U001.jpg) 不活动
- - '####'
  - 不活动 ![images](img/U001.jpg) 后台
- - '####'
  - 后台 ![images](img/U001.jpg) 不活动
- - '###'
  - 非活跃状态与活跃状态
- - '####'
  - 处理非活跃状态
- - '####'
  - 处理后台状态
- - '###'
  - 进入后台时释放资源
- - '###'
  - 进入后台时保存状态
- - '###'
  - 短暂回溯往昔
- - '###'
  - 回到后台
- - '###'
  - 请求更多后台时间
- - '###'
  - 中央调度，收尾
- - '#'
  - 第 16 章：使用 Quartz 和 OpenGL 绘图
- - '###'
  - 图形世界的两种视角
- - '###'
  - Quartz 2D 的绘图方法
- - '####'
  - Quartz 2D 的图形上下文
- - '####'
  - 坐标系
- - '####'
  - 指定颜色
- - '#####'
  - 关于 iOS 设备屏幕的一点色彩理论
- - '#####'
  - 其他颜色模型
- - '#####'
  - 颜色便捷方法
- - '####'
  - 在上下文中绘制图像
- - '####'
  - 绘制形状：多边形、线条和曲线
- - '####'
  - Quartz 2D 工具示例：图案、渐变和虚线样式
- - '###'
  - QuartzFun 应用程序
- - '####'
  - 设置 QuartzFun 应用程序
- - '#####'
  - 创建随机颜色
- - '###'
  - 定义应用程序常量
- - '###'
  - 实现 `QuartzFunView` 骨架
- - '####'
  - 创建并连接输出口与操作
- - '####'
  - 实现动作方法
- - '###'
  - 添加 Quartz 2D 绘图代码
- - '####'
  - 绘制线条
- - '####'
  - 绘制矩形和椭圆
- - '####'
  - 绘制图像
- - '###'
  - 优化 QuartzFun 应用
- - '###'
  - GLFun 应用程序
- - '####'
  - 设置 GLFun 应用程序
- - '####'
  - 创建 BIDGLFunView
- - '####'
  - 更新 BIDViewController
- - '####'
  - 更新 Nib
- - '###'
  - 完成 GLFun 项目
- - '###'
  - 绘图接近尾声
- - '#'
  - 第 17 章
- - '##'
  - 点击、触摸与手势
- - '###'
  - 多点触控术语
- - '###'
  - 响应者链
- - '####'
  - 响应事件
- - '###'
  - 转发事件：保持响应链的活力
- - '###'
  - 多点触控架构
- - '###'
  - 四种触摸通知方法
- - '###'
  - TouchExplorer 应用程序
- - '###'
  - Swipes 应用程序
- - '###'
  - 自动手势识别
- - '###'
  - 实现多指滑动
- - '###'
  - 检测多次点按
- - '###'
  - 检测捏合手势
- - '###'
  - 定义自定义手势
- - '###'
  - CheckPlease 应用
- - '###'
  - CheckPlease 触摸方法
- - '###'
  - 结账？请确认！
- - '#'
  - 第 18 章
- - '##'
  - 我在哪里？使用 Core Location 定位
- - '###'
  - 位置管理器
- - '###'
  - 设置期望精度
- - '###'
  - 设置距离过滤器
- - '###'
  - 启动位置管理器
- - '###'
  - 明智地使用位置管理器
- - '###'
  - 位置管理器委托
- - '###'
  - 获取位置更新
- - '####'
  - 使用 `CLLocation` 获取经纬度
- - '####'
  - 错误通知
- - '###'
  - 尝试使用 Core Location
- - '####'
  - 更新位置管理器
- - '####'
  - 确定行进距离
- - '###'
  - 无论你身在何处，你都在那里
- - '#'
  - 第 19 章
- - '##'
  - 哇哦！陀螺仪和加速度计！
- - '###'
  - 加速度计物理原理
- - '###'
  - 别忘了旋转
- - '###'
  - Core Motion 与运动管理器
- - '####'
  - 基于事件的运动
- - '###'
  - 主动运动访问
- - '####'
  - 加速计结果
- - '###'
  - 检测摇晃
- - '####'
  - 内置的摇晃检测
- - '####'
  - 摇晃与碎裂
- - '###'
  - 加速度计作为方向控制器
- - '####'
  - 滚动弹珠
- - '###'
  - 编写“球体视图”
- - '####'
  - 计算球的移动
- - '###'
  - 滚动前行
- - '#'
  - 第 20 章
- - '##'
  - 摄像头与照片库
- - '###'
  - 使用图像选择器和 `UIImagePickerController`
- - '###'
  - 实现图像选择器控制器代理
- - '###'
  - 实地测试相机和照片库
- - '###'
  - 设计界面
- - '###'
  - 实现相机视图控制器
- - '###'
  - 轻而易举！
- - '#'
  - 第 21 章
- - '##'
  - 应用本地化
- - '###'
  - 本地化架构
- - '###'
  - 字符串文件
- - '####'
  - 字符串文件中有什么？
- - '####'
  - 本地化字符串宏
- - '###'
  - 真实世界的 iOS：本地化你的应用程序
- - '####'
  - 设置 LocalizeMe
- - '###'
  - 试用 LocalizeMe
- - '####'
  - 本地化 Nib 文件
- - '####'
  - 本地化图片
- - '####'
  - 生成并本地化字符串文件
- - '####'
  - 本地化应用显示名称
- - '###'
  - 再见
- - '#'
  - 第 22 章
- - '##'
  - 下一步去哪里？
- - '###'
  - Apple 的文档
- - '###'
  - 邮件列表
- - '###'
  - 讨论论坛
- - '###'
  - 网站
- - '###'
  - 博客
- - '###'
  - 会议
- - '###'
  - 关注作者
- - '###'
  - 告别
- - '##'
  - 索引
- - '###'
  - 特殊字符和数字
- - '###'
  - A
- - '###'
  - B
- - '###'
  - C
- - '####'
  - Core Data 框架
- - '####'
  - Core Location
- - '###'
  - 其他
- - '###'
  - D
- - '###'
  - E
- - '###'
  - F
- - '###'
  - G
- - '###'
  - H
- - '###'
  - I
- - '####'
  - 图标
- - '####'
  - IDE（集成开发环境），3
- - '####'
  - 图像选取器
- - '####'
  - 图像
- - '####'
  - 非活跃状态，547–552
- - '####'
  - 缩进层级，针对表格，230
- - '####'
  - 索引分区，分组分区与，248–254
- - '####'
  - 索引
- - '####'
  - 检查器设置，针对文本字段，87–88
- - '####'
  - 集成开发环境（IDE），3
- - '####'
  - 交互，45–68
- - '####'
  - 界面生成器，27，30–39
- - '####'
  - 界面方向，118
- - '####'
  - 界面
- - '####'
  - iPad 平台，381–406
- - '###'
  - J
- - '###'
  - K
- - '###'
  - L
- - '###'
  - M
- - '###'
  - N
- - '####'
  - 导航应用
- - '####'
  - 导航栏
- - '####'
  - 导航控制器
- - '####'
  - 导航器视图（在 Xcode 中）
- - '####'
  - 导航器（用于 Segue）
- - '####'
  - nib 文件
- - '####'
  - NIB 名称字段
- - '####'
  - 更新 nib
- - '####'
  - 多触摸通知方法
- - '####'
  - 状态变更通知
- - '####'
  - '`NSArray` 对象'
- - '####'
  - '`NSArray` 属性'
- - '####'
  - '`NSBundle`'
- - '####'
  - '`NSCoding` 协议，遵循'
- - '####'
  - '`NSCopying` 协议，实现'
- - '####'
  - '`NSData` 对象'
- - '####'
  - '`NSDate` 对象'
- - '####'
  - '`NSDateFormatter` 类'
- - '####'
  - '`NSDictionary` 类'
- - '####'
  - '`NSError` 对象'
- - '####'
  - '`NSIndexPath` 属性'
- - '####'
  - '`NSInteger` 类'
- - '####'
  - '`NSKeyedUnarchiver` 方法'
- - '####'
  - '`NSLocale` 类'
- - '####'
  - '`NSLocalizedString` 函数'
- - '####'
  - '`NSLog()` 方法'
- - '####'
  - '`NSMutableData` 对象'
- - '####'
  - '`NSMutableDictionary` 对象'
- - '####'
  - '`NSMutableString`'
- - '####'
  - '`NSObject`'
- - '####'
  - '`NSOperationQueue`'
- - '####'
  - '`NSPredicate` 类'
- - '####'
  - '`NSSearchPathForDirectoriesInDomains()` 方法'
- - '####'
  - '`NSString` 方法'
- - '####'
  - '`NSTemporaryDirectory()` 方法'
- - '####'
  - '`NSUInteger` 列'
- - '####'
  - '`NSUInteger` 行列'
- - '####'
  - '`NSURL` 对象'
- - '####'
  - '`NSUserDefaults` 类'
- - '####'
  - '`NSValue` 对象'
- - '####'
  - '`NSZone` 参数'
- - '####'
  - 数字
- - '####'
  - '`numInRow`'
- - '###'
  - O
- - '###'
  - P
- - '###'
  - Q
- - '###'
  - R
- - '###'
  - S
- - '###'
  - T
- - '###'
  - U
- - '###'
  - V
- - '###'
  - W
- - '###'
  - X
- - '###'
  - Y, Z
