name: Smart Mobility
name_cn: 智能出行
slug: smart-mobility
toc:
- - '#'
  - 前言
- - '##'
  - 关于作者
- - '#'
  - 第1章 迈向以人为本的智慧城市
- - '##'
  - 1.1 世界城市化问题
- - '##'
  - 1.2 以人为本的智慧城市
- - '##'
  - 城市作为异质实体
- - '##'
  - 智慧城市的支柱
- - '##'
  - 全球智慧城市倡议
- - '###'
  - 线城：一座愿景中的智慧城市
- - '##'
  - 1.3 智慧出行：实现可持续发展的关键推动力
- - '##'
  - 1.4 总结
- - '#'
  - 第2章 智能出行三要素
- - '##'
  - 2.1 智能出行管理
- - '##'
  - 2.2 城市规划
- - '##'
  - 2.3 智能出行技术
- - '#'
  - 第3章 智慧出行：基础技术、使能技术与颠覆性技术
- - '##'
  - 3.1 智慧出行：基础技术
- - '##'
  - 3.2 PNT 与 GIS
- - '###'
  - 基于 WiFi 的定位与地理信息系统
- - '####'
  - 基于 WiFi 的定位
- - '####'
  - 地理信息系统（GIS）
- - '####'
  - 高精地图（HD Maps）
- - '####'
  - 将 5G 与 PNT、GIS、高精地图和交通数据相结合
- - '#####'
  - 处理差异
- - '##'
  - 3.3 无线通信
- - '##'
  - 3.4 移动计算
- - '##'
  - 3.5 区块链
- - '###'
  - 智能出行中的区块链
- - '###'
  - 警告
- - '###'
  - 表 3-1：区块链类型及其在智能出行中的应用实例
- - '##'
  - 3.6 物联网 (IoT)
- - '##'
  - 3.7 人工智能 (AI)
- - '###'
  - 3.7.1 人工智能的演进
- - '###'
  - 3.7.2 统计机器学习
- - '###'
  - 3.7.3 人工智能赋能智能出行
- - '###'
  - 3.7.4 人工智能解决智能出行中的结构不良问题
- - '####'
  - 多准则最优路径规划
- - '####'
  - 其他问题
- - '####'
  - 基础设施问题示例
- - '#####'
  - 交通传感器的优化布置
- - '#####'
  - 其他问题
- - '####'
  - AI 搜索算法与现代元启发式优化技术
- - '###'
  - 3.7.5 AI/ML 成功采用的关键因素
- - '##'
  - 3.8 机器人学
- - '###'
  - ADS 框架
- - '###'
  - 认知循环
- - '###'
  - 运动规划示例
- - '###'
  - 历史背景
- - '###'
  - 开源工具与数据集
- - '##'
  - 3.9 电动化
- - '###'
  - 表 3-3：电动汽车分类 | 数据来源：OneWedge
- - '##'
  - 3.10 本章小结
- - '#'
  - 第4章 智慧出行：技术推动因素
- - '##'
  - 4.1 智能基础设施
- - '##'
  - 4.2 网联出行
- - '##'
  - 4.3 自动化出行
- - '###'
  - 自动驾驶汽车 vs. 自动飞行飞机
- - '###'
  - 4.3.2 自动驾驶
- - '###'
  - 4.3.3 自动驾驶与安全
- - '###'
  - 4.3.4 数据驱动方法与自动驾驶车辆安全
- - '###'
  - 4.3.5 自动驾驶与社会互动
- - '###'
  - 4.3.6 自动驾驶与智慧出行
- - '##'
  - 4.4 电动出行
- - '###'
  - 可负担性与电动出行
- - '##'
  - 4.5 微出行
- - '##'
  - 4.6 主动、轻柔或零冲击出行
- - '##'
  - 4.7 包容性出行
- - '###'
  - 包容性出行：全面概述
- - '###'
  - 技术组件与用户驱动方法
- - '###'
  - 基准测试与行业倡议
- - '###'
  - 助行器具与技术
- - '###'
  - 医疗保健交通服务
- - '##'
  - 4.8 情境感知系统（CAS）
- - '##'
  - 4.9 本章小结
- - '#'
  - 第5章 智能出行：颠覆性创新
- - '##'
  - 5.1 卡诺模型
- - '##'
  - 5.2 颠覆性出行平台
- - '###'
  - 5.2.1 自主地面车辆
- - '###'
  - 5.2.2 三维机动性与城市空中交通（UAM）
- - '###'
  - 5.2.3 水上出租车
- - '###'
  - 5.2.4 自动旅客捷运系统
- - '###'
  - 5.2.5 超级高铁与城市环线高铁
- - '##'
  - 5.3 共享出行
- - '##'
  - 5.4 出行即服务（MaaS）
- - '###'
  - 重要信息
- - '##'
  - 5.5 按需出行（MOD）
- - '##'
  - 5.6 无缝集成出行系统（SIMS）
- - '##'
  - 5.7 最后一公里配送
- - '##'
  - 5.8 车辆即服务（VaaS）
- - '##'
  - 5.9 零工经济与乘客经济
- - '###'
  - 5.9.1 零工经济与众包
- - '###'
  - 5.9.2 乘客经济
- - '##'
  - 5.10 本章小结
- - '#'
  - 第6章 新冠疫情及后疫情时代的智能出行
- - '##'
  - 6.1 新冠疫情下的智慧出行
- - '###'
  - 6.1.1 新冠疫情对共享出行的影响
- - '###'
  - 6.1.2 新冠疫情对最后一公里配送服务的影响
- - '##'
  - 6.2 后疫情时代的智能出行
- - '###'
  - 通勤模式
- - '###'
  - 共享出行
- - '###'
  - 6.2.3 末端配送
- - '###'
  - 6.2.4 电动汽车
- - '###'
  - 6.2.5 自动驾驶汽车
- - '###'
  - 6.2.6 工作策略
- - '###'
  - 6.2.7 数字化转型
- - '###'
  - 6.2.8 开放式创新
- - '###'
  - 6.2.9 可持续发展
- - '###'
  - 6.2.10 以全球方案应对全球挑战
- - '##'
  - 6.3 征程远未结束
- - '###'
  - 6.3.1 就业
- - '###'
  - 6.3.2 隐私
- - '###'
  - 6.3.3 网络安全攻击与物理攻击
- - '##'
  - 6.4 总结
- - '#'
  - 索引
- - '##'
  - A
- - '##'
  - B
- - '##'
  - C
- - '##'
  - D
- - '##'
  - E
- - '##'
  - F
- - '##'
  - G
- - '##'
  - H
- - '##'
  - I, J
- - '##'
  - K
- - '##'
  - L
- - '##'
  - M
- - '##'
  - N
- - '##'
  - O
- - '##'
  - P
- - '##'
  - Q
- - '##'
  - R
- - '##'
  - S
- - '##'
  - T
- - '##'
  - U
- - '##'
  - V
- - '##'
  - W, X, Y
- - '##'
  - Z
