name: Practical Fashion Tech
name_cn: 时尚科技实战指南
slug: practical-fashion-tech
toc:
- - '#'
  - 目录
- - '##'
  - 引言
- - '##'
  - 致谢
- - '##'
  - 内容速览
- - '##'
  - 第一部分：宏观概述
- - '##'
  - 第二部分：基础入门
- - '##'
  - 第三部分：进阶提升
- - '##'
  - 第四部分：未来之路
- - '#'
  - 第一部分
- - '#'
  - 1. 时尚科技
- - '##'
  - 时尚科技简史
- - '##'
  - 戏服制作
- - '##'
  - 我们的设计理念
- - '##'
  - 规划你的项目
- - '###'
  - 穿戴者的环境
- - '###'
  - 原型制作与测试
- - '###'
  - 林的服装故事
- - '##'
  - 总结
- - '#'
  - 2. 实践性戏服设计
- - '##'
  - 何为戏服？
- - '###'
  - 戏服设计的力量
- - '###'
  - Lyn 的学生戏剧戏服制作贴士
- - '##'
  - 戏服设计原则
- - '###'
  - 让戏服为你服务
- - '###'
  - 戏服开发的时间与精力
- - '###'
  - 你将制作什么？
- - '##'
  - 初学者的错误
- - '###'
  - 材料
- - '###'
  - 估算时间
- - '###'
  - 不要独自硬撑
- - '##'
  - 本章总结
- - '#'
  - 第二部分
- - '#'
  - 3. 如何缝纫
- - '##'
  - 基础手缝工具与技巧
- - '###'
  - 穿针
- - '###'
  - 打结
- - '###'
  - 使用不同的针法
- - '####'
  - 平针缝
- - '####'
  - 疏缝针
- - '####'
  - 倒针缝
- - '####'
  - 暗缝针或藏针缝
- - '####'
  - 包边缝
- - '####'
  - 卷针缝
- - '##'
  - 穿引缝纫机线
- - '###'
  - 绕制梭芯
- - '###'
  - 安装机针
- - '###'
  - 为机器上半部分穿线
- - '###'
  - 安装梭芯
- - '##'
  - 试机缝纫
- - '###'
  - 改变缝纫方向
- - '###'
  - 尝试不同类型的针法
- - '####'
  - 双针缝纫或加固缝
- - '####'
  - 缩缝针迹
- - '####'
  - 边缘缝
- - '####'
  - 面缝
- - '####'
  - 倒针缝
- - '###'
  - 针法的实际应用
- - '##'
  - 本章小结
- - '#'
  - 4. 制作与使用缝纫纸样
- - '##'
  - 测量
- - '##'
  - 选择纸样
- - '###'
  - 购买纸样
- - '###'
  - 制作纸样
- - '###'
  - 基本纸样形状与部件
- - '###'
  - 选择布料
- - '###'
  - 计算所需布料用量
- - '##'
  - 使用纸样
- - '###'
  - 布局纸样
- - '###'
  - 固定与裁剪纸样
- - '###'
  - 标记布料
- - '##'
  - 制作一件简单的马甲
- - '###'
  - 选择布料
- - '###'
  - 排版与裁剪纸样
- - '###'
  - 缝制背心
- - '####'
  - 缝制肩部
- - '####'
  - 缝制侧缝
- - '####'
  - 组装前贴边
- - '####'
  - 组装袖窿贴边
- - '####'
  - 下摆
- - '###'
  - 其他收尾工作
- - '##'
  - 常见问题
- - '##'
  - 时尚科技设计注意事项
- - '##'
  - 总结
- - '#'
  - 5. 可穿戴科技电子学
- - '##'
  - 电路设计
- - '###'
  - 面包板
- - '###'
  - 欧姆定律
- - '###'
  - 电路元件
- - '####'
  - 电阻器
- - '####'
  - LED
- - '###'
  - 电阻选型
- - '###'
  - 杜邦线
- - '##'
  - 分压器
- - '###'
  - 模拟与数字的接口
- - '###'
  - 电位器
- - '###'
  - 示例
- - '##'
  - 制作电路
- - '###'
  - Fritzing
- - '####'
  - 使用检查器
- - '####'
  - 添加新元件
- - '####'
  - Fritzing 专家提示
- - '##'
  - 可缝纫组件
- - '###'
  - 可缝纫 Arduino 电路板
- - '###'
  - 使用可缝纫 Arduino 电路板进行原型开发
- - '###'
  - 电池
- - '###'
  - 导电丝带和缝线
- - '##'
  - 其他组件
- - '###'
  - 我需要学习焊接吗？
- - '###'
  - 洗涤
- - '##'
  - 总结
- - '#'
  - 6. 可穿戴设备编程
- - '##'
  - 编程基础
- - '##'
  - 开环控制 vs. 闭环控制
- - '###'
  - 规划程序：流程图
- - '##'
  - Arduino 代码规范
- - '###'
  - 格式惯例
- - '###'
  - 让人感到望而生畏的地方
- - '####'
  - 语法的严格性
- - '###'
  - 编程词汇与概念
- - '####'
  - 注释
- - '####'
  - 变量与循环
- - '####'
  - 保留字
- - '####'
  - 函数
- - '####'
  - 赋值、比较与基础数学
- - '####'
  - If、Else 与 While
- - '###'
  - 示例讲解
- - '##'
  - 为 Arduino 编程
- - '###'
  - Arduino 的运作方式
- - '###'
  - 编译、加载、运行
- - '###'
  - 添加库
- - '###'
  - 使用预处理指令
- - '###'
  - 为图 5-7 编写代码
- - '##'
  - Arduino 输入与输出
- - '###'
  - 数字读取与写入
- - '###'
  - 模拟读取与 PWM
- - '###'
  - 写入串口
- - '##'
  - 可缝纫开发板编程
- - '##'
  - 本章小结
- - '#'
  - 你的第一个项目
- - '#'
  - 7. 定时器围裙
- - '##'
  - 项目规划
- - '##'
  - 控制设计及软件
- - '##'
  - 电路布局
- - '##'
  - 调试
- - '##'
  - 缝制围裙
- - '###'
  - 制作纸样
- - '###'
  - 制作平底锅按钮
- - '###'
  - 制作口袋
- - '###'
  - 包边处理
- - '###'
  - 缝制系带和颈带
- - '###'
  - 组装平底锅按钮
- - '###'
  - 缝制电子元件和电路
- - '####'
  - 第一道导电线程走线
- - '####'
  - 第二根导电线行程
- - '####'
  - 第三根导电线行程
- - '####'
  - 第四根导电线行程
- - '####'
  - 第五根导电线行程
- - '###'
  - 收尾工作
- - '##'
  - 实际应用
- - '##'
  - 总结
- - '#'
  - 第三部分
- - '#'
  - 8. 传感器与其他硬件
- - '##'
  - 传感器
- - '###'
  - 创建带传感器的电路
- - '###'
  - 可缝制传感器替代方案
- - '###'
  - 其他常见传感器
- - '##'
  - 热敏电阻
- - '###'
  - 使用热敏电阻
- - '###'
  - 与热敏电阻交互的 Arduino 程序
- - '##'
  - 光电二极管：夜灯示例
- - '###'
  - 使用光电二极管
- - '###'
  - 在项目中使用多个传感器
- - '##'
  - 让物体动起来
- - '###'
  - 电源管理
- - '###'
  - 伺服电机
- - '##'
  - 本章小结
- - '#'
  - 9. 3D 打印
- - '##'
  - 3D 打印的工作原理
- - '##'
  - 在 3D 打印机上制作物品的步骤
- - '##'
  - 基于线材的 3D 打印机的限制
- - '##'
  - 3D 建模
- - '###'
  - TinkerCAD 及其他 123D 应用
- - '###'
  - OpenSCAD
- - '###'
  - 其他 CAD 程序
- - '##'
  - 切片与打印
- - '###'
  - MatterControl
- - '###'
  - 专有 3D 打印机
- - '##'
  - 3D 打印材料
- - '##'
  - 应用
- - '###'
  - 制作模具或铸造模型
- - '###'
  - 使用 3D 打印笔
- - '##'
  - 在织物上进行 3D 打印
- - '##'
  - 本章小结
- - '#'
  - 10. 规划的重要性
- - '##'
  - 过于宏大的首个项目
- - '###'
  - 鬼魅连衣裙——最初构想
- - '###'
  - 错误
- - '####'
  - 花朵与 NeoPixel 的布局
- - '####'
  - 神奇的袖子
- - '####'
  - 鼓起的裙摆
- - '####'
  - 软件
- - '####'
  - 最终结果如何
- - '###'
  - 我们学到的经验
- - '####'
  - 材料考量
- - '####'
  - 隐藏并支撑电池和机械装置
- - '####'
  - 导电缝纫线、导线和线缆
- - '####'
  - 避免短路
- - '####'
  - 路由物理控制线
- - '####'
  - 导线 vs. 导电缝线
- - '####'
  - 安装舵机
- - '####'
  - 放置开关和传感器
- - '####'
  - 可变电阻元件
- - '####'
  - 光纤
- - '##'
  - 穿戴科技
- - '##'
  - 设计可测试项目
- - '##'
  - 本章小结
- - '#'
  - 11. 两个进阶项目
- - '##'
  - 摇头帽
- - '###'
  - 传感器
- - '###'
  - 材料清单
- - '###'
  - 制作电路
- - '###'
  - 连接电池
- - '###'
  - 库文件
- - '####'
  - 加载代码与使用感应帽
- - '##'
  - 发光 60 年代摩登连衣裙
- - '###'
  - 设计
- - '###'
  - 材料与工具
- - '###'
  - 测量尺寸与制作纸样
- - '####'
  - 连衣裙前片尺寸
- - '####'
  - 裙身后片的尺寸测量
- - '###'
  - 制作纸样
- - '###'
  - 制作 EL 冷光线和导线的通道管
- - '###'
  - 整理裁片
- - '###'
  - 缝制前片
- - '###'
  - 添加后片
- - '###'
  - 低腰口袋
- - '###'
  - EL 电光带套管
- - '###'
  - EL 彩带与礼服布线
- - '###'
  - 收尾工作
- - '###'
  - 药盒帽的制作
- - '####'
  - 裁剪部件
- - '####'
  - 组装帽子
- - '###'
  - 其他方案
- - '##'
  - 总结
- - '#'
  - 第四部分
- - '#'
  - 12. 其他技术
- - '##'
  - 切割工具
- - '###'
  - 激光切割
- - '####'
  - 切割布料
- - '####'
  - 为激光切割机进行设计
- - '###'
  - CNC 铣削
- - '##'
  - 构建技术
- - '###'
  - 泡沫盔甲
- - '###'
  - 真空成型
- - '###'
  - Worbla
- - '##'
  - 其他想法
- - '##'
  - 涂装
- - '##'
  - 总结
- - '#'
  - 13. 展望未来
- - '##'
  - 3D 打印高级时装
- - '###'
  - 蒂塔·万提斯连衣裙
- - '###'
  - 神经系统
- - '##'
  - 电子时装
- - '###'
  - 阿努克·维普雷希特
- - '###'
  - 2016 年纽约大都会艺术博物馆慈善舞会
- - '##'
  - 纺织科技
- - '###'
  - 生物逻辑
- - '###'
  - 雅卡尔项目
- - '##'
  - 服装遇上物联网
- - '##'
  - 最后几点想法
- - '##'
  - 总结
- - '#'
  - 附录 A：教授时尚科技
- - '##'
  - 课程目标与评分
- - '###'
  - 课程描述
- - '###'
  - 学习目标
- - '###'
  - 评分标准
- - '##'
  - 后勤问题
- - '###'
  - 课程安排
- - '###'
  - 材料共享
- - '###'
  - 教室环境
- - '###'
  - 预算
- - '##'
  - 课程资源
- - '##'
  - 课程内容大纲
- - '###'
  - 项目
- - '###'
  - 课程安排
- - '#'
  - 附录 B：链接
- - '###'
  - 关于作者
- - '###'
  - 第 1 章 时尚科技
- - '###'
  - 第 2 章 实用戏服设计
- - '###'
  - 第 3 章 如何缝纫
- - '###'
  - 第 4 章 制作与使用缝纫样板
- - '###'
  - 第 5 章 可穿戴技术电子元件
- - '###'
  - 第 6 章 可穿戴设备编程
- - '###'
  - 第 7 章 你的第一个项目
- - '###'
  - 第 8 章 传感器与其他硬件
- - '###'
  - 第 9 章 3D 打印
- - '###'
  - 第 10 章 规划的重要性
- - '###'
  - 第 11 章 两个更大的项目
- - '###'
  - 第 12 章 其他技术
- - '###'
  - 第 13 章 展望未来
- - '###'
  - 索引
