name: Learn Sprite Kit for iOS Game Development
name_cn: iOS 游戏开发的 Sprite Kit 入门指南
slug: learn-sprite-kit-for-ios-game-development
toc:
- - '##'
  - 本书内容
- - '##'
  - 为何购买本书
- - '##'
  - 你需要了解什么
- - '##'
  - 你需要准备什么
- - '##'
  - 本书章节概览
- - '#'
  - 第 1 章：Hello World
- - '##'
  - 我们热爱游戏
- - '##'
  - 传统
- - '##'
  - 设置
- - '##'
  - 总结
- - '#'
  - 第 2 章：SKActions 和 SKTextures：你的第一个动画精灵
- - '##'
  - 初露锋芒
- - '##'
  - 移除不必要的琐碎内容
- - '##'
  - 设备方向
- - '##'
  - 轻微的视图控制器更改
- - '###'
  - 锚点
- - '###'
  - 回到启动画面
- - '###'
  - 场景切换
- - '###'
  - 创建新场景
- - '###'
  - 使用 SKActions 进行动画过渡
- - '###'
  - 组合多个动作
- - '###'
  - 使用`SKTexture`实现动画帧
- - '##'
  - 总结
- - '#'
  - 第 3 章：精灵移动：响应用户输入
- - '##'
  - 跑起来！
- - '###'
  - 代码重组
- - '###'
  - 玩家新类
- - '##'
  - 替换静态值
- - '##'
  - 为纹理创建新类
- - '##'
  - 添加纹理
- - '##'
  - 改变方向
- - '##'
  - 你所做的操作
- - '##'
  - 滑行停止
- - '##'
  - 总结
- - '#'
  - 第 4 章：边缘、边界和平台
- - '###'
  - 物理效果
- - '###'
  - 物理体的属性
- - '##'
  - 添加背景图
- - '##'
  - 接触与碰撞
- - '##'
  - 添加砖块地基
- - '###'
  - 确定与边缘的接触
- - '##'
  - 处理精灵环绕
- - '###'
  - 跳跃
- - '###'
  - 岩架与连接
- - '##'
  - 总结
- - '#'
  - 第 5 章：更多动画精灵：“敌人”与“奖励金币”
- - '###'
  - 对立面
- - '##'
  - 敌人“Ratz”类
- - '##'
  - 时机
- - '###'
  - 环绕
- - '###'
  - Update 方法
- - '##'
  - 奖励金币
- - '##'
  - 敌机与金币的碰撞
- - '##'
  - 总结
- - '#'
  - 第 6 章：创建角色阵容
- - '##'
  - 静态 vs 动态角色
- - '##'
  - 文件格式
- - '##'
  - 创建文件
- - '###'
  - XML 格式
- - '###'
  - 加载文件
- - '##'
  - 解析数据
- - '##'
  - 实现新的生成流程
- - '###'
  - 本章小结
- - '#'
  - 第 7 章：分数与计分
- - '##'
  - 分数有什么用？
- - '##'
  - 分数显示
- - '###'
  - SKLabelNode
- - '##'
  - 自定义字体纹理
- - '##'
  - // 计分
- - '##'
  - 状态栏 = 关闭
- - '##'
  - 另一种“分数”
- - '##'
  - 播放声音文件
- - '##'
  - CAF 音频格式
- - '##'
  - 玩家生成音效
- - '##'
  - 玩家奔跑音效
- - '##'
  - 玩家跳跃音效
- - '##'
  - 玩家滑行停止音效
- - '##'
  - 敌人出现音效
- - '##'
  - 金币出现音效
- - '##'
  - 总结
- - '#'
  - 第 8 章：接触与碰撞
- - '##'
  - 这部分内容之前不是讲过了吗？
- - '##'
  - 接触 vs. 碰撞
- - '##'
  - 格栅
- - '##'
  - 管道
- - '##'
  - 偶尔卡住的敌人
- - '###'
  - 设置玩家的起始位置
- - '###'
  - 收集金币
- - '###'
  - 收集金币的音效
- - '##'
  - 金币收集点数显示
- - '##'
  - 粒子效果
- - '##'
  - 壁架下方的金币接触
- - '##'
  - 玩家/金币
- - '##'
  - 从 ledge 下方击中 Ratz
- - '##'
  - 交集检测不够灵敏
- - '##'
  - 基座行径者
- - '##'
  - 玩家踢击敌人
- - '###'
  - 老鼠收集音效
- - '###'
  - Ratz 收集点数显示
- - '###'
  - 被踢飞
- - '##'
  - 落水
- - '##'
  - 玩家死亡音效
- - '##'
  - 玩家跌落平台
- - '###'
  - 本章小结
- - '#'
  - 第 9 章：添加更多场景和关卡
- - '###'
  - 多条玩家生命
- - '###'
  - 添加可视化生命计量器
- - '###'
  - 游戏结束
- - '##'
  - 接触/碰撞/触摸
- - '##'
  - 最高分
- - '##'
  - 关卡完成判定
- - '##'
  - 关卡完成效果
- - '##'
  - 无限关卡
- - '##'
  - 新型敌人
- - '##'
  - 移动
- - '##'
  - 金币/平台
- - '##'
  - 两次打击而非一次
- - '##'
  - 第三关和第四关
- - '##'
  - 玩家说明
- - '##'
  - 本章小结
- - '#'
  - 第 10 章：接下来该怎么做
- - '##'
  - 继续探索 Sprite Kit
- - '##'
  - 让游戏变得更好
- - '###'
  - 资源
- - '###'
  - 告别
- - '#'
  - 索引
- - '###'
  - A
- - '###'
  - B
- - '###'
  - 动画精灵。*参见* 敌人与奖励
- - '###'
  - C
- - '###'
  - D
- - '###'
  - 角色创建
- - '###'
  - 文件格式
- - '###'
  - 启动过程
- - '###'
  - 粒子效果
- - '###'
  - 接触与碰撞
- - '###'
  - 金币收集
- - '###'
  - 管道
