name: Meet the Kinect
name_cn: Kinect 入门指南
slug: meet-the-kinect
toc:
- - '#'
  - Cinder 能为您做什么
- - '#'
  - Cinder 入门指南
- - '#'
  - 现在，去创造吧！
- - '#'
  - 什么是 Beckon？
- - '#'
  - 安装 Beckon
- - '##'
  - 步骤 1：移除现有驱动程序
- - '##'
  - 步骤 2：安装新驱动程序
- - '##'
  - 步骤 3：下载并安装 Beckon SDK
- - '#'
  - 激活 Beckon
- - '#'
  - 入门指南
- - '#'
  - 将 Beckon 与 Flash 集成
- - '#'
  - 理解 Beckon Flash 示例
- - '##'
  - Beckon 如何与 Flash 协同工作
- - '##'
  - 示例代码
- - '###'
  - 骨架数据
- - '###'
  - 关节位置
- - '###'
  - 警报
- - '##'
  - 核心功能
- - '#'
  - 修改 Beckon Flash 示例
- - '#'
  - 设计自定义手势
- - '#'
  - 向 SDK 添加新手势
- - '##'
  - 录制手势
- - '##'
  - 标记手势
- - '##'
  - 训练手势
- - '##'
  - 测试手势
- - '##'
  - 添加供 Flash 使用的手势
- - '##'
  - 基于手势构建功能
- - '#'
  - 安装 Unity 及支持软件
- - '#'
  - 探索 Unity 界面
- - '##'
  - 项目
- - '##'
  - 工作区
- - '##'
  - 基本导航与变换工具
- - '##'
  - 播放控制
- - '#'
  - 理解 ZigFu 与 Unity 的关系
- - '##'
  - OpenNI 与 NITE
- - '##'
  - Unity 与 ZigFu
- - '#'
  - 运行 ZigFu 游戏示例
- - '##'
  - Avatar2Players
- - '##'
  - AvatarFrontFacing
- - '##'
  - TopDownUserMap
- - '##'
  - Blockman3rdPerson
- - '#'
  - 运行界面示例
- - '##'
  - Item Selector
- - '##'
  - CoverFlow
- - '##'
  - Slide Viewer
- - '#'
  - 从头创建骨架
- - '##'
  - 任务 1：添加 OpenNI 功能
- - '##'
  - 任务 2：制作基本骨架
- - '##'
  - 任务 3：连接各部件
- - '#'
  - 创建自定义手部追踪器
- - '#'
  - Coding4Fun
- - '#'
  - Kinect SDK 的优缺点
- - '#'
  - Kinect SDK 入门指南
- - '##'
  - 系统要求
- - '##'
  - 运行示例及故障排除
- - '##'
  - 设置新的 Kinect 项目
- - '#'
  - 构建一个简单应用
- - '#'
  - 需要更多信息？
- - '#'
  - 静态体显示
- - '##'
  - 静态体投影
- - '##'
  - 扫描体显示
- - '##'
  - 佩珀尔幻象显示
- - '##'
  - 多视角自动立体平板显示器
- - '##'
  - 激光等离子体发射显示
- - '##'
  - 自由空间气溶胶显示
- - '##'
  - IO2 Heliodisplay
- - '##'
  - FogScreen 显示
- - '##'
  - 投影光场阵列
- - '#'
  - 第 1 章
- - '##'
  - 开始上手
- - '###'
  - 购买正确的 Kinect
- - '###'
  - 将 Kinect 与 Xbox 分离
- - '###'
  - 确保拥有交流电源适配器
- - '###'
  - 逐件检视 Kinect 的各个部件
- - '###'
  - 下载与安装软件
- - '####'
  - 查找 `RGBDemo` 的正确版本
- - '####'
  - 为 Windows 下载并安装 `RGBDemo`
- - '###'
  - 下载二进制文件
- - '###'
  - 安装 OpenNI
- - '###'
  - 安装 SensorKinect
- - '###'
  - 安装 PrimeSense NITE
- - '###'
  - 连接 Kinect
- - '###'
  - 为 Mac OS X 下载并安装 RGBDemo
- - '###'
  - 测试你的 Kinect
- - '#'
  - 第 2 章
- - '##'
  - 技术背后
- - '###'
  - 理解技术栈
- - '##'
  - 硬件
- - '###'
  - 结构光摄像头系统
- - '####'
  - PrimeSense 参考设计
- - '####'
  - 华硕 WAVI Xtion PRO 与 PRO Live
- - '###'
  - 飞行时间相机系统
- - '####'
  - SoftKinetic DepthSense 摄像头
- - '####'
  - PMD [vision] 飞行时间摄像头
- - '####'
  - 松下 D-Imager
- - '##'
  - 驱动与数据
- - '####'
  - '`OpenKinect/Libfreenect`'
- - '####'
  - '`OpenNI`'
- - '####'
  - 商业驱动
- - '###'
  - 中间件和应用开发环境
- - '#'
  - 第 3 章
- - '##'
  - 现实世界中的应用
- - '###'
  - Kinect 应用的其他来源
- - '####'
  - SenseCast：少数派报告遇见网络
- - '#####'
  - 步骤 1：下载客户端
- - '#####'
  - 步骤 2：安装依赖项
- - '#####'
  - 步骤 3：启动 SenseCast
- - '#####'
  - 步骤 4：尽情享受吧！
- - '###'
  - 超人七号
- - '###'
  - 卡美哈梅哈
- - '###'
  - 身体畸形恐惧症
- - '###'
  - MatterPort
- - '#'
  - 第 4 章：对 Kinect 进行脚本编程
- - '##'
  - Processing
- - '###'
  - Processing 能为你做什么
- - '###'
  - 下载、安装与探索
- - '###'
  - Processing 库与草图
- - '####'
  - 内置示例
- - '####'
  - 添加库
- - '###'
  - 最终连接 Kinect
- - '##'
  - Windows 上的 Processing 版 Kinect
- - '###'
  - 添加 dLibs
- - '###'
  - 更新驱动
- - '###'
  - 运行点云示例
- - '#'
  - 点云草图的作用
- - '##'
  - 调整示例
- - '###'
  - 更高分辨率
- - '###'
  - 深度图
- - '###'
  - 阈值处理
- - '###'
  - 在 Mac OS X 上使用 Processing 控制 Kinect
- - '####'
  - 添加 OpenKinect
- - '####'
  - 更新驱动程序
- - '####'
  - 运行点云示例
- - '####'
  - 点云草图的工作原理
- - '####'
  - 调整示例
- - '#####'
  - 更高分辨率
- - '##'
  - 深度图与阈值处理
- - '###'
  - Processing 与 Kinect：本书之外
- - '#'
  - 第 5 章：面向创作者的 Kinect
- - '##'
  - MaxMSP
- - '###'
  - 拼图式编程语言
- - '###'
  - MaxMSP 能为你做什么
- - '###'
  - 入门：MaxMSP + Kinect
- - '##'
  - Flash Actionscript
- - '###'
  - Flash 能为你做什么
- - '#'
  - 入门指南：Flash + Kinect
- - '##'
  - openFrameworks
- - '###'
  - openFrameworks 能为你做什么
- - '###'
  - 入门指南：openFrameworks + Kinect
- - '##'
  - Cinder
- - '###'
  - Cinder 能为你做什么
- - '###'
  - Cinder 入门指南
- - '###'
  - 现在，开始创作吧！
- - '#'
  - 第六章
- - '##'
  - 使用 Beckon 框架进行应用程序开发
- - '###'
  - 什么是 Beckon？
- - '####'
  - 安装 Beckon
- - '#####'
  - 第 1 步：移除现有驱动程序
- - '#####'
  - 第 2 步：安装新驱动程序
- - '#####'
  - 第 3 步：下载并安装 Beckon SDK
- - '###'
  - 激活 Beckon
- - '###'
  - 快速入门
- - '###'
  - 将 Beckon 与 Flash 集成
- - '###'
  - 理解 Beckon Flash 示例
- - '####'
  - Beckon 如何与 Flash 协同工作
- - '####'
  - 示例代码
- - '####'
  - 骨骼数据
- - '####'
  - 关节位置
- - '####'
  - 警报
- - '####'
  - 核心功能
- - '###'
  - 修改 Beckon Flash 示例
- - '###'
  - 设计自定义手势
- - '###'
  - 向 SDK 添加新手势
- - '###'
  - 录制手势
- - '###'
  - 标记手势
- - '###'
  - 训练手势
- - '###'
  - 测试手势
- - '###'
  - 为 Flash 使用添加手势
- - '###'
  - 基于手势构建功能
- - '#'
  - 第 7 章
- - '##'
  - 使用 Unity 制作 3D 游戏与用户界面
- - '###'
  - 安装 Unity 及配套软件
- - '###'
  - 探索 Unity 界面
- - '####'
  - 项目
- - '####'
  - 工作区
- - '####'
  - 基本导航与变换工具
- - '####'
  - 播放控制
- - '###'
  - 理解 ZigFu 与 Unity 的关系
- - '####'
  - OpenNI 与 NITE
- - '####'
  - Unity 与 ZigFu
- - '###'
  - 运行 ZigFu 游戏示例
- - '####'
  - Avatar2Players
- - '####'
  - AvatarFrontFacing
- - '####'
  - TopDownUserMap
- - '####'
  - Blockman3rdPerson
- - '###'
  - 运行界面示例
- - '####'
  - Item Selector
- - '####'
  - CoverFlow
- - '####'
  - Slide Viewer
- - '###'
  - 从头创建骨骼
- - '####'
  - 任务 1. 添加 OpenNI 功能
- - '####'
  - 任务 2：制作基本骨架
- - '####'
  - 任务 3：将部件连接起来
- - '###'
  - 创建自定义手部追踪器
- - '#'
  - 第 8 章
- - '##'
  - 微软 Kinect SDK
- - '###'
  - Coding4Fun
- - '###'
  - Kinect SDK 的优缺点
- - '###'
  - 开始使用 Kinect SDK
- - '####'
  - 需求
- - '#####'
  - 系统
- - '#####'
  - Visual Studio 2010
- - '#####'
  - 附加框架和支持软件
- - '######'
  - .NET Framework
- - '######'
  - DirectX 运行时与 SDK
- - '######'
  - 微软的语音平台
- - '######'
  - Kinect SDK 和 Coding4Fun Kinect 工具包
- - '####'
  - 运行示例并排查问题
- - '####'
  - 设置新的 Kinect 项目
- - '#####'
  - 第 1 步：创建一个新项目
- - '#####'
  - 第 2 步：添加 Using 语句
- - '#####'
  - 第 3 步：创建加载和关闭事件
- - '###'
  - 构建一个简单的应用
- - '####'
  - 决定构建什么
- - '####'
  - 设计用户界面
- - '###'
  - 用代码连接用户界面
- - '###'
  - 需要更多？
- - '#'
  - 第 9 章
- - '##'
  - 体三维显示技术
- - '###'
  - 静态体显示
- - '###'
  - 静态体投影
- - '###'
  - 扫描体显示
- - '###'
  - 佩珀尔幻象显示
- - '###'
  - 多视角自动立体平板显示器
- - '###'
  - 激光等离子体发射显示器
- - '###'
  - 自由空间气态显示器
- - '####'
  - IO2 Heliodisplay
- - '####'
  - FogScreen 显示器
- - '###'
  - 投影光场阵列
- - '##'
  - 我们何去何从？
- - '#'
  - 索引
- - '##'
  - 数字与符号
- - '##'
  - A
- - '##'
  - B
- - '##'
  - C
- - '##'
  - D, E
- - '##'
  - F
- - '##'
  - G
- - '##'
  - H
- - '##'
  - I, J
- - '##'
  - K
- - '##'
  - L
- - '##'
  - M
- - '##'
  - N
- - '##'
  - O
- - '##'
  - P, Q
- - '##'
  - R
- - '##'
  - S
- - '##'
  - T
- - '##'
  - U
- - '##'
  - V
- - '##'
  - W
- - '##'
  - X, Y
- - '##'
  - Z
- - '#'
  - Sean Kean
- - '#'
  - Phoenix Perry
- - '#'
  - Johnathan C. Hall
- - '##'
  - 关于作者
- - '##'
  - 关于技术审校
