name: Swift 4 for Absolute Beginners
name_cn: Swift 4 入门指南（面向绝对初学者）
slug: swift-4-for-absolute-beginners
toc:
- - '#'
  - 引言
- - '##'
  - 致新手
- - '##'
  - 致更有经验的开发者
- - '##'
  - 本书组织方式
- - '##'
  - 成功公式
- - '##'
  - 开发技术栈
- - '#'
  - 所需软件、材料及设备
- - '##'
  - 操作系统与集成开发环境
- - '###'
  - 软件开发工具包
- - '###'
  - 双显示器（编辑注：不确定为何此“粗体”格式生效）
- - '##'
  - 免费在线研讨会、问答环节及 YouTube 视频
- - '###'
  - 免费书籍论坛
- - '#'
  - 读者论坛：获取习题答案并向作者提问
- - '##'
  - 目录
- - '###'
  - 第 1 章：成为优秀的 iOS 开发者 1
- - '###'
  - 第 2 章：编程基础 13
- - '###'
  - 第 3 章：一切都是关于数据 25
- - '###'
  - 第 4 章：决策、程序流程与应用设计 39
- - '###'
  - 第 5 章：Swift 面向对象编程 63
- - '###'
  - 第 6 章：学习 Swift 与 Xcode 83
- - '###'
  - 第 7 章：Swift 类、对象与方法 107
- - '###'
  - 第 8 章：Swift 编程基础 133
- - '###'
  - 第 9 章：比较数据 159
- - '###'
  - 第 10 章：创建用户界面 171
- - '###'
  - 第 11 章：存储信息 199
- - '###'
  - 第 12 章：协议与委托 229
- - '###'
  - 第 13 章：Xcode 调试器简介 247
- - '###'
  - 第 14 章：一个 Swift iPhone 应用 263
- - '###'
  - 第 15 章：Apple Watch 与 WatchKit 285
- - '##'
  - 索引 311
- - '##'
  - 关于作者与技术审阅者
- - '#'
  - 成为一名出色的 iOS 开发者
- - '##'
  - 成功的关键
- - '##'
  - 像开发者一样思考
- - '###'
  - 注意
- - '#'
  - 完成开发周期
- - '#'
  - 介绍面向对象编程
- - '#'
  - 使用 Playground 界面
- - '#'
  - 总结
- - '##'
  - 下一章节
- - '##'
  - 练习题
- - '#'
  - 2. 编程基础
- - '##'
  - Xcode 漫游
- - '###'
  - 探索工作区窗口
- - '###'
  - 导航工作区
- - '###'
  - 编辑项目文件
- - '##'
  - 创建你的第一个 Swift Playground 程序
- - '###'
  - 安装并启动 Xcode 9
- - '###'
  - 使用 Xcode 9
- - '##'
  - Xcode Playground IDE：编辑区和结果区
- - '##'
  - 总结
- - '#'
  - 3. 一切都与数据有关
- - '##'
  - 编程中使用的数制
- - '###'
  - 位
- - '####'
  - 摩尔定律
- - '###'
  - 字节
- - '###'
  - 十六进制
- - '###'
  - Unicode
- - '#'
  - 数据类型
- - '##'
  - 声明常量和变量
- - '##'
  - 可选类型
- - '#'
  - 在 Playground 中使用变量
- - '#'
  - 总结
- - '##'
  - 练习
- - '#'
  - 做出决策、程序流程与应用程序设计
- - '#'
  - 布尔逻辑
- - '##'
  - 真值表
- - '##'
  - 比较运算符
- - '#'
  - 设计应用
- - '###'
  - 伪代码
- - '###'
  - 可选值与强制解包
- - '####'
  - 可选绑定
- - '####'
  - 隐式解包可选值
- - '###'
  - 流程图
- - '###'
  - 设计与绘制示例应用的流程图
- - '###'
  - 应用设计
- - '###'
  - 使用循环重复执行程序语句
- - '####'
  - 计数控制循环
- - '####'
  - 条件控制循环
- - '####'
  - 无限循环
- - '#'
  - 使用 Swift 编写示例应用
- - '##'
  - 嵌套的 `if` 语句和 `else if` 语句
- - '##'
  - 移除多余字符
- - '##'
  - 通过重构改进代码
- - '##'
  - 运行应用
- - '###'
  - 设计需求
- - '##'
  - 总结
- - '###'
  - 练习
- - '#'
  - 5. 使用 Swift 进行面向对象编程
- - '#'
  - 对象
- - '##'
  - 什么是类？
- - '##'
  - 规划类
- - '#'
  - 规划属性
- - '##'
  - 规划方法
- - '###'
  - 实现类
- - '#'
  - 继承
- - '#'
  - 为什么要使用 OOP？
- - '##'
  - OOP 无处不在
- - '##'
  - 消除冗余代码
- - '##'
  - 易于调试
- - '##'
  - 易于替换
- - '#'
  - 高级主题
- - '##'
  - 接口
- - '##'
  - 多态性
- - '##'
  - 面向值编程
- - '##'
  - 小结
- - '###'
  - 练习
- - '#'
  - 6. 学习 Swift 与 Xcode
- - '##'
  - 新生语言
- - '##'
  - 理解语言符号
- - '#'
  - 在 Swift 中实现对象
- - '##'
  - 在 Xcode 中编写另一个程序
- - '###'
  - 创建项目
- - '##'
  - 总结
- - '##'
  - 练习
- - '#'
  - 7. Swift 类、对象与方法
- - '##'
  - 创建 Swift 类
- - '###'
  - 属性
- - '###'
  - 方法
- - '####'
  - 使用类型方法
- - '###'
  - 使用实例方法
- - '###'
  - 使用你的新类
- - '####'
  - 创建你的项目
- - '####'
  - 添加对象
- - '####'
  - 编写类
- - '###'
  - 创建用户界面
- - '###'
  - 连接代码
- - '###'
  - 运行程序
- - '###'
  - 将类型方法提升至新高度
- - '###'
  - 访问 Xcode 文档
- - '###'
  - 总结
- - '#'
  - 8. Swift 编程基础
- - '###'
  - 使用 `let` 与 `var`
- - '###'
  - 理解集合
- - '#'
  - 使用数组
- - '#'
  - 使用字典类
- - '#'
  - 创建书店应用
- - '##'
  - 创建你的类
- - '##'
  - 属性介绍
- - '##'
  - 访问属性
- - '##'
  - 完成 BookStore 程序
- - '###'
  - 创建视图
- - '###'
  - 添加属性
- - '###'
  - 添加描述
- - '###'
  - 创建简单的数据模型类
- - '###'
  - 修改 MasterViewController
- - '###'
  - 修改 DetailViewController
- - '##'
  - 总结
- - '##'
  - 练习
- - '#'
  - 9. 数据比较
- - '##'
  - 重温布尔逻辑
- - '##'
  - 使用关系运算符
- - '###'
  - 比较数字
- - '###'
  - 创建一个示例 Xcode 应用
- - '###'
  - 使用布尔表达式
- - '###'
  - 比较字符串
- - '##'
  - 使用 switch 语句
- - '###'
  - 比较日期
- - '###'
  - 组合比较
- - '##'
  - 本章小结
- - '#'
  - 10. 创建用户界面
- - '##'
  - 理解 Interface Builder
- - '#'
  - 模型-视图-控制器模式
- - '##'
  - 人机界面指南
- - '##'
  - 使用 Interface Builder 创建示例 iPhone 应用
- - '###'
  - 使用 Interface Builder
- - '###'
  - 文档大纲
- - '###'
  - 对象库
- - '###'
  - 检查器面板与选择器栏
- - '###'
  - 创建视图
- - '###'
  - 使用输出口
- - '###'
  - 使用操作
- - '###'
  - 类
- - '##'
  - 小结
- - '##'
  - 练习
- - '#'
  - 11. 存储信息
- - '##'
  - 存储考量
- - '##'
  - 数据库
- - '#'
  - 在数据库中存储信息
- - '#'
  - 开始使用 Core Data
- - '##'
  - 模型
- - '##'
  - 添加新属性
- - '###'
  - 托管对象上下文
- - '###'
  - 设置界面
- - '###'
  - '**图 11-18. 连接表格视图**'
- - '###'
  - '**图 11-19. 连接表格视图**'
- - '###'
  - '**图 11-20. 为按钮对象添加操作**'
- - '###'
  - '**图 11-21. 更改连接的类型和名称**'
- - '###'
  - '**图 11-22. 为表格视图创建输出口**'
- - '##'
  - 总结
- - '###'
  - 练习
- - '#'
  - 12. 协议和委托
- - '##'
  - 多重继承
- - '##'
  - 理解协议
- - '##'
  - 协议语法
- - '##'
  - 委托
- - '##'
  - 协议和委托示例
- - '#'
  - 开始使用
- - '##'
  - 工作原理
- - '##'
  - 总结
- - '##'
  - 练习
- - '#'
  - 13. 初识 Xcode 调试器
- - '##'
  - 调试入门
- - '#'
  - 设置断点
- - '#'
  - 使用断点导航器
- - '#'
  - 调试基础
- - '###'
  - 使用调试器控制
- - '##'
  - 使用单步控制
- - '###'
  - 查看线程窗口和调用栈
- - '###'
  - 调试变量
- - '##'
  - 处理代码错误和警告
- - '###'
  - 错误
- - '###'
  - 警告
- - '##'
  - 总结
- - '#'
  - 14. 一个 Swift iPhone 应用
- - '#'
  - 让我们开始吧
- - '###'
  - 开关（Switches）
- - '###'
  - 警告控制器（Alert Controllers）
- - '##'
  - 应用总结
- - '##'
  - 练习
- - '#'
  - 15. Apple Watch 与 WatchKit
- - '##'
  - 创建 watchOS 应用时的注意事项
- - '#'
  - 创建 Apple Watch 应用
- - '#'
  - 修改表格行标识符
- - '#'
  - 添加更多功能
- - '##'
  - 总结
- - '##'
  - 练习题
- - '#'
  - 索引 A
- - '##'
  - Apple 开发者计划
- - '##'
  - B
- - '##'
  - C
- - '##'
  - D
- - '##'
  - E
- - '##'
  - F
- - '##'
  - G
- - '##'
  - H
- - '##'
  - I, J
- - '##'
  - K
- - '##'
  - L
- - '##'
  - M, N
- - '##'
  - O
- - '##'
  - P
- - '##'
  - Q
- - '##'
  - R
- - '##'
  - S
- - '##'
  - T
- - '##'
  - U
- - '##'
  - V
- - '##'
  - W
- - '##'
  - X, Y, Z
