name: Learn Unity 2017 for IOS Game Development
name_cn: Unity 2017 iOS 游戏开发入门指南
slug: learn-unity-2017-for-ios-game-development
toc:
- - '#'
  - 学习使用 Unity 2017 进行 iOS 游戏开发
- - '##'
  - 致谢
- - '#'
  - 目录
- - '##'
  - 第 1 章：入门指南
- - '##'
  - 第 2 章：Unity 漫游
- - '##'
  - 第 3 章：创建场景
- - '##'
  - 第 4 章：动起来：为立方体编写脚本
- - '##'
  - 第 5 章：一起跳舞！动画与音效
- - '##'
  - 第 6 章：滚起来！物理与控制
- - '##'
  - 第 7 章：打保龄球！高级物理
- - '##'
  - 第 8 章：玩起来！游戏脚本编写
- - '##'
  - 第 9 章：游戏 GUI
- - '##'
  - 第 10 章：使用 Unity iOS
- - '##'
  - 第 11 章：真实设备构建：设备测试与应用提交
- - '##'
  - 第 12 章：呈现：屏幕与图标
- - '##'
  - 第 13 章：处理设备输入
- - '##'
  - 第 14 章：性能优化
- - '##'
  - 第 15 章：下一步该去哪里？
- - '#'
  - 开始使用
- - '##'
  - 前提条件
- - '###'
  - 准备你的 Mac
- - '###'
  - 注册成为 iOS 开发者
- - '###'
  - 下载 Xcode
- - '###'
  - 下载 Unity
- - '##'
  - 安装 Unity
- - '###'
  - 运行下载助手
- - '###'
  - 欢迎使用 Unity！
- - '##'
  - 管理 Unity
- - '###'
  - 更换皮肤（Pro 版）
- - '###'
  - 报告问题
- - '###'
  - 检查更新
- - '##'
  - 进一步探索
- - '###'
  - iOS 开发需求
- - '###'
  - Unity 网站
- - '###'
  - Unity 社区
- - '#'
  - 第 2 章：Unity 快速入门
- - '##'
  - 介绍《攀登者》游戏
- - '###'
  - 打开《攀登者》项目
- - '###'
  - 打开《攀登者》游戏场景
- - '###'
  - 运行《攀登者》
- - '###'
  - 构建游戏
- - '##'
  - 编辑器布局
- - '###'
  - 预设布局
- - '###'
  - 自定义布局
- - '####'
  - 调整区域大小
- - '####'
  - 移动视图
- - '####'
  - 分离视图
- - '###'
  - 添加和移除视图
- - '##'
  - 检视器视图
- - '##'
  - 项目视图
- - '###'
  - 单列与双列切换
- - '###'
  - 缩放图标
- - '###'
  - 检查资源
- - '###'
  - 搜索资源
- - '###'
  - 操作资源
- - '##'
  - 层级视图
- - '###'
  - 检查游戏对象
- - '###'
  - 父游戏对象与子游戏对象
- - '##'
  - 场景视图
- - '###'
  - 场景导航
- - '###'
  - 场景视图选项
- - '###'
  - 场景视图辅助图标
- - '##'
  - 游戏视图
- - '###'
  - 播放时最大化
- - '###'
  - 统计信息
- - '###'
  - 游戏视图辅助图标
- - '##'
  - 控制台视图
- - '##'
  - 进一步探索
- - '###'
  - Unity 手册
- - '###'
  - 教程
- - '###'
  - 版本控制
- - '##'
  - 第 3 章：创建场景
- - '##'
  - 创建新项目
- - '##'
  - 主摄像机
- - '###'
  - 多摄像机
- - '###'
  - 摄像机构造
- - '###'
  - 变换组件
- - '###'
  - 摄像机组件
- - '####'
  - 清除标记
- - '####'
  - 剔除遮罩
- - '####'
  - 投影
- - '####'
  - 视口
- - '####'
  - 深度
- - '####'
  - 渲染路径
- - '####'
  - 目标纹理
- - '####'
  - HDR
- - '###'
  - FlareLayer 组件
- - '###'
  - GUILayer 组件
- - '###'
  - AudioListener 组件
- - '##'
  - 向场景添加一个立方体
- - '###'
  - 制作立方体
- - '###'
  - 框选立方体
- - '###'
  - 移动立方体
- - '###'
  - 立方体的结构
- - '####'
  - Transform 组件
- - '####'
  - MeshFilter 组件
- - '####'
  - MeshRenderer 组件
- - '####'
  - BoxCollider 组件
- - '###'
  - 与视图对齐
- - '##'
  - 摄像机控制
- - '###'
  - 导入脚本
- - '###'
  - 附加脚本
- - '##'
  - 添加灯光
- - '###'
  - 灯光剖析
- - '####'
  - 类型
- - '####'
  - 范围
- - '####'
  - 颜色
- - '####'
  - 强度
- - '####'
  - 阴影类型
- - '####'
  - 轮廓遮罩
- - '###'
  - 剔除遮罩
- - '###'
  - 镜头光晕
- - '###'
  - 绘制光晕
- - '###'
  - 渲染模式
- - '###'
  - 光照贴图
- - '###'
  - 调整光照
- - '###'
  - 创建光晕
- - '##'
  - 纹理
- - '###'
  - 导入纹理
- - '###'
  - 浏览资源商店
- - '###'
  - 导入纹理
- - '###'
  - 应用纹理
- - '##'
  - 进一步探索
- - '###'
  - Unity 手册
- - '###'
  - 参考手册
- - '###'
  - 资源商店
- - '###'
  - 计算机图形学
- - '#'
  - 第 4 章：让它动起来：为立方体编写脚本
- - '##'
  - 组织资源
- - '##'
  - 创建脚本
- - '###'
  - 为脚本命名
- - '###'
  - 脚本剖析
- - '###'
  - 附加脚本
- - '###'
  - 编辑脚本
- - '##'
  - 理解脚本
- - '##'
  - 阅读脚本参考文档
- - '##'
  - 运行脚本
- - '##'
  - 调试脚本
- - '###'
  - 编译错误
- - '###'
  - 运行时错误
- - '####'
  - 使用 MonoDevelop 调试
- - '##'
  - 让它旋转
- - '###'
  - 旋转变换 (Transform)
- - '###'
  - 其他旋转方式
- - '###'
  - 在世界空间中旋转
- - '##'
  - 立方体的子物体 (Children of the Cube)
- - '###'
  - 制作预制体
- - '###'
  - 断开预制体连接
- - '##'
  - 进一步探索
- - '###'
  - Unity 手册
- - '###'
  - 脚本参考
- - '###'
  - 脚本编写
- - '#'
  - 第 5 章：一起跳舞吧！动画与音效
- - '##'
  - 导入骷髅包
- - '##'
  - 添加骷髅
- - '###'
  - 隐藏方块
- - '###'
  - 让骷髅旋转
- - '###'
  - 让骷髅跳舞
- - '###'
  - 让骷髅永远跳舞
- - '##'
  - 添加舞池
- - '##'
  - 添加阴影
- - '##'
  - 添加音乐
- - '##'
  - 进一步探索
- - '###'
  - Unity 手册
- - '###'
  - 参考手册
- - '###'
  - Asset Store
- - '###'
  - 计算机图形学
- - '#'
  - 第 6 章：开球吧！物理与操控
- - '##'
  - 创建新场景
- - '###'
  - 删除游戏对象
- - '###'
  - 调整灯光
- - '###'
  - 重新铺设地面
- - '###'
  - 重置摄像机
- - '##'
  - 制作一个球
- - '###'
  - 制作一个球体
- - '###'
  - 让它落下
- - '##'
  - 自定义碰撞
- - '###'
  - PhysicMaterials
- - '###'
  - 标准 PhysicMaterials
- - '###'
  - PhysicMaterial 的结构
- - '###'
  - 应用 PhysicMaterial
- - '###'
  - 创建新的 PhysicMaterial
- - '##'
  - 让球滚动起来
- - '###'
  - 创建脚本
- - '###'
  - 更新：收集输入
- - '###'
  - FixedUpdate：使用力
- - '###'
  - 真的在滚动吗？
- - '###'
  - 限制速度
- - '###'
  - 完整脚本
- - '##'
  - 成为保龄球
- - '##'
  - 进一步探索
- - '###'
  - Unity 手册
- - '###'
  - 参考手册
- - '###'
  - 脚本参考
- - '###'
  - 网络资源
- - '#'
  - 第 7 章：开打吧！高级物理
- - '##'
  - 加长球道
- - '###'
  - 创建保龄球瓶
- - '###'
  - 在场景中放置球瓶
- - '###'
  - 使用摄像机跟随
- - '###'
  - 持续游玩
- - '##'
  - 返回球的初始状态
- - '###'
  - 发送消息
- - '###'
  - 检测落沟球
- - '###'
  - 完整代码清单
- - '##'
  - 用木桶代替球瓶
- - '###'
  - 挑选一个木桶
- - '###'
  - 创建预制件
- - '###'
  - 使用预制件
- - '###'
  - 添加碰撞体
- - '###'
  - 添加复合碰撞体
- - '###'
  - 更新预制件
- - '###'
  - 复杂碰撞体（HyperBowl）
- - '##'
  - 添加声音
- - '###'
  - 获取声音
- - '###'
  - 添加滚动音效
- - '###'
  - 添加球瓶碰撞音效
- - '##'
  - 进一步探索
- - '###'
  - 脚本参考
- - '###'
  - 资源
- - '#'
  - 第 8 章：开始游戏！为游戏编写脚本
- - '##'
  - 游戏规则
- - '##'
  - 游戏计分
- - '###'
  - 单回合得分
- - '###'
  - 玩家得分
- - '###'
  - 设置分数
- - '###'
  - 获取得分
- - '###'
  - 完整代码清单
- - '###'
  - 创建 FuguBowlPlayer
- - '##'
  - 球瓶状态
- - '##'
  - 游戏逻辑
- - '###'
  - 设计 FSM
- - '###'
  - 跟踪游戏进程
- - '###'
  - 启动状态机
- - '###'
  - 各状态
- - '####'
  - StateNewGame
- - '####'
  - StateBall1
- - '####'
  - StateBall2
- - '####'
  - StateBall3
- - '####'
  - StateRolling
- - '####'
  - StateRolledPast
- - '####'
  - StateGutterBall
- - '####'
  - StateRollOver
- - '####'
  - StateSpare、StateStrike 和 StateKnockedSomeDown
- - '####'
  - StateNextBall
- - '####'
  - StateGameOver
- - '###'
  - 完整清单
- - '##'
  - 深入探索
- - '###'
  - Unity 手册
- - '###'
  - 脚本参考
- - '###'
  - 资源商店
- - '###'
  - 网络资源
- - '#'
  - 第 9 章：游戏图形用户界面
- - '##'
  - 记分牌
- - '###'
  - 创建脚本
- - '###'
  - 设计 GUI 样式
- - '##'
  - 暂停菜单
- - '###'
  - 创建脚本
- - '###'
  - 跟踪当前菜单页面
- - '###'
  - 暂停游戏
- - '###'
  - 检查 Time.deltaTime
- - '###'
  - 显示菜单
- - '###'
  - 自动布局
- - '##'
  - 主页面
- - '##'
  - Credits 页面
- - '##'
  - Options 页面
- - '##'
  - Audio 面板
- - '###'
  - 图形面板
- - '###'
  - 系统面板
- - '##'
  - 自定义 GUI 颜色
- - '##'
  - 自定义皮肤
- - '##'
  - 完整脚本
- - '##'
  - 更进一步
- - '###'
  - Unity 手册
- - '###'
  - 参考手册
- - '###'
  - 脚本参考
- - '###'
  - 资源商店
- - '#'
  - 第 10 章：使用 Unity iOS
- - '##'
  - 使用 Unity Remote 进行测试
- - '###'
  - 安装 Xcode
- - '###'
  - 自定义播放器设置
- - '####'
  - 分辨率和显示
- - '####'
  - 其他设置
- - '##'
  - 在 iOS 模拟器中进行测试
- - '##'
  - 进一步探索
- - '###'
  - Unity 手册
- - '###'
  - 参考手册
- - '###'
  - iOS 开发者库
- - '#'
  - 第 11 章：真机构建：设备测试与 App 提交
- - '##'
  - 注册为 iOS 开发者
- - '###'
  - 使用配置门户
- - '###'
  - 注册测试设备
- - '###'
  - 注册应用标识符
- - '###'
  - 使用开发配置配置文件
- - '###'
  - 使用发布配置配置文件
- - '##'
  - 使用 Xcode 设置器
- - '###'
  - 构建与运行
- - '###'
  - 准备 App Store 图形素材
- - '####'
  - 创建图标
- - '####'
  - 截图
- - '##'
  - 在 iTunes Connect 上添加应用
- - '###'
  - 选择应用类型
- - '###'
  - 输入应用信息
- - '###'
  - 设置上架时间和价格
- - '###'
  - 设置语言和类别
- - '###'
  - 准备提交
- - '###'
  - 上传图标和截图
- - '###'
  - 通用应用信息
- - '####'
  - 将构建包上传到 iTunes Connect
- - '####'
  - 提交以供审核
- - '####'
  - 为被拒绝做好准备
- - '####'
  - 更新应用
- - '####'
  - 跟踪销量
- - '####'
  - 发放促销代码
- - '##'
  - 进一步探索
- - '###'
  - Unity 手册
- - '###'
  - Apple 开发者网站
- - '#'
  - 第 12 章：呈现：屏幕与图标
- - '##'
  - 保龄球游戏 for iOS
- - '###'
  - 缩放 GUI
- - '###'
  - 缩放记分板
- - '###'
  - 缩放暂停菜单
- - '##'
  - 设置图标
- - '##'
  - 设置启动画面
- - '##'
  - 创建第二个启动画面
- - '###'
  - 创建启动场景
- - '###'
  - 创建启动画面
- - '####'
  - 加载下一个场景
- - '####'
  - 显示活动指示器
- - '####'
  - 为活动指示器编写脚本
- - '##'
  - 进一步探索
- - '###'
  - 参考手册
- - '###'
  - 脚本参考
- - '###'
  - iOS 开发者库
- - '###'
  - 资源商店
- - '###'
  - 书籍
- - '#'
  - 第 13 章：处理设备输入
- - '##'
  - 触摸屏
- - '###'
  - 滑动球
- - '###'
  - 轻触小球
- - '##'
  - 加速度计
- - '###'
  - 调试加速度计
- - '###'
  - 检测摇晃
- - '##'
  - 摄像机
- - '###'
  - 读取网络摄像头
- - '##'
  - 进一步探索
- - '###'
  - 脚本参考
- - '###'
  - iOS 开发者库
- - '###'
  - 资源商店
- - '#'
  - 第 14 章：优化
- - '##'
  - 选择目标
- - '###'
  - 帧率
- - '####'
  - 创建脚本
- - '####'
  - 挂载脚本
- - '###'
  - 空间目标
- - '##'
  - 剖析游戏
- - '###'
  - 游戏视图状态
- - '###'
  - 构建日志
- - '###'
  - 运行内置分析器
- - '###'
  - 运行编辑器性能分析器
- - '###'
  - 手动连接性能分析器
- - '###'
  - 添加帧率显示
- - '##'
  - 优化设置
- - '###'
  - 质量设置
- - '###'
  - 物理管理器
- - '###'
  - 时间管理器
- - '###'
  - 音频管理器
- - '###'
  - 其他设置
- - '####'
  - 静态批处理
- - '####'
  - 动态批处理
- - '####'
  - 加速度计频率
- - '####'
  - 剥离级别
- - '####'
  - 脚本调用优化
- - '####'
  - 优化网格数据
- - '##'
  - 优化游戏对象
- - '###'
  - 摄像机
- - '###'
  - 光源
- - '###'
  - 球瓶
- - '####'
  - 地面
- - '####'
  - 球
- - '##'
  - 优化资源
- - '###'
  - 纹理
- - '###'
  - 音频
- - '###'
  - 网格
- - '##'
  - 优化脚本
- - '###'
  - 缓存 GetComponent
- - '###'
  - UnityGUI
- - '###'
  - 运行时静态合批
- - '###'
  - 共享材质
- - '###'
  - 最小化垃圾回收
- - '##'
  - 离线优化
- - '###'
  - Beast
- - '###'
  - Umbra
- - '##'
  - 最终分析
- - '##'
  - 进一步探索
- - '###'
  - Unity 手册
- - '###'
  - 参考手册
- - '###'
  - 脚本参考
- - '###'
  - 资源商店
- - '###'
  - 网络资源
- - '###'
  - 书籍推荐
- - '#'
  - 第 15 章：接下来去哪里？
- - '##'
  - 更多脚本编程
- - '###'
  - 编辑器脚本
- - '###'
  - C#
- - '###'
  - 脚本执行顺序
- - '###'
  - 插件
- - '##'
  - 跟踪应用
- - '###'
  - 推广码
- - '##'
  - 更多盈利方式
- - '###'
  - 应用内购买
- - '###'
  - 资源商店
- - '###'
  - 为安卓开发
- - '###'
  - 外包工作
- - '##'
  - 结语
- - '#'
  - 索引 A
