name: Objective-C Quick Syntax Reference
name_cn: Objective-C 快速语法参考
slug: objective-c-quick-syntax-reference
toc:
- - '#'
  - 关于作者
- - '#'
  - 关于技术审校
- - '#'
  - 引言
- - '#'
  - 目录
- - '#'
  - 内容一览
- - '#'
  - 1. Hello World
- - '##'
  - Xcode
- - '##'
  - 创建新项目
- - '##'
  - Hello World
- - '##'
  - 代码注释
- - '##'
  - 构建并运行
- - '##'
  - 获取更多信息
- - '#'
  - 2. 构建并运行
- - '##'
  - 编译
- - '##'
  - 构建
- - '###'
  - 构建并运行
- - '#'
  - 3. 变量
- - '##'
  - 变量定义
- - '###'
  - 数据类型
- - '###'
  - 声明变量
- - '###'
  - 赋值
- - '###'
  - 整数类型
- - '###'
  - 布尔类型
- - '###'
  - 浮点类型
- - '###'
  - 作用域
- - '#'
  - 4. 运算符
- - '##'
  - 运算符定义
- - '###'
  - 算术运算符
- - '####'
  - 运算符优先级
- - '###'
  - 赋值运算符
- - '###'
  - 递增和递减运算符
- - '###'
  - 关系运算符
- - '###'
  - 逻辑运算符
- - '#'
  - 5. 对象
- - '##'
  - 对象定义
- - '###'
  - NSObject 类
- - '###'
  - 对象声明
- - '###'
  - 对象构造函数
- - '###'
  - 对象格式说明符
- - '###'
  - 消息
- - '#'
  - 6. 字符串
- - '##'
  - NSString
- - '##'
  - NSMutableString
- - '###'
  - 插入字符串
- - '###'
  - 删除字符串
- - '###'
  - 查找与替换
- - '#'
  - 7. 数字
- - '##'
  - NSNumber
- - '###'
  - 转换为原始数据类型
- - '###'
  - 格式化数字
- - '###'
  - 将字符串转换为数字
- - '#'
  - 8. 数组
- - '##'
  - NSArray
- - '###'
  - 引用对象
- - '###'
  - 枚举
- - '##'
  - NSMutableArray
- - '#'
  - 9. 字典
- - '##'
  - NSDictionary
- - '###'
  - 引用对象
- - '###'
  - 枚举
- - '##'
  - NSMutableDictionary
- - '#'
  - 10. For 循环
- - '##'
  - 摘要
- - '##'
  - For 循环详解
- - '###'
  - For 循环与数组
- - '#'
  - 11. While 循环
- - '##'
  - 摘要
- - '##'
  - While 循环详解
- - '###'
  - While 循环与数组
- - '#'
  - 12. Do While 循环
- - '##'
  - Do While 循环的定义
- - '###'
  - Do While 循环与数组
- - '#'
  - 13. For-Each 循环
- - '##'
  - For-Each 循环的定义
- - '###'
  - 使用 NSDictionary 的 For 循环
- - '#'
  - 14. If 语句
- - '##'
  - If 语句的定义
- - '###'
  - else 关键字
- - '###'
  - 嵌套 if-else
- - '##'
  - if 语句与变量
- - '#'
  - 15. Switch 语句
- - '##'
  - Switch 语句的定义
- - '###'
  - switch 关键字
- - '###'
  - case 关键字
- - '###'
  - break 关键字
- - '###'
  - 完整的 Switch 语句
- - '###'
  - 默认 case
- - '#'
  - 16. 定义类
- - '##'
  - 类
- - '###'
  - 类接口
- - '####'
  - 属性前置声明
- - '####'
  - 方法前置声明
- - '###'
  - 实现类
- - '####'
  - 实现方法
- - '#####'
  - 私有属性和方法
- - '######'
  - 类扩展
- - '######'
  - 局部实例变量
- - '#'
  - 17. 类方法
- - '##'
  - 类方法的定义
- - '###'
  - 编写类方法
- - '#'
  - 18. 继承
- - '##'
  - 创建子类
- - '##'
  - 扩展类
- - '###'
  - 重写方法
- - '####'
  - 实例变量的可见性
- - '#####'
  - 可见性级别
- - '######'
  - 私有实例变量
- - '######'
  - 受保护的实例方法
- - '######'
  - 公有实例变量
- - '#'
  - 19. 分类
- - '##'
  - 摘要
- - '##'
  - 分类定义
- - '###'
  - 类别示例
- - '#'
  - 20. 块（Blocks）
- - '##'
  - 摘要
- - '##'
  - 块的定义
- - '###'
  - 定义块
- - '###'
  - 赋值块
- - '###'
  - 使用块
- - '###'
  - 复制作用域内的变量
- - '###'
  - 作为属性的 Block
- - '####'
  - Block 的前向声明
- - '####'
  - 在类中使用 Block
- - '####'
  - 分配 Block
- - '#'
  - 21. 键值编码
- - '##'
  - 键值编码定义
- - '###'
  - 设置属性值
- - '###'
  - 检索属性值
- - '#'
  - 22. 键值观察
- - '##'
  - 键值观察定义
- - '##'
  - 项目与任务对象图
- - '###'
  - 实施键值观察
- - '####'
  - 添加观察者
- - '####'
  - 观察值的变化
- - '####'
  - 注销观察者
- - '####'
  - 测试观察者
- - '#'
  - 23. 协议
- - '##'
  - 摘要
- - '##'
  - 协议概述
- - '###'
  - 定义协议
- - '####'
  - 可选与必需的方法和属性
- - '####'
  - 采用协议
- - '####'
  - 实现协议方法
- - '#'
  - 24. 委托
- - '##'
  - 委托的定义
- - '###'
  - 定义委托协议
- - '###'
  - 向委托发送消息
- - '###'
  - 分配委托对象
- - '#'
  - 25. 单例模式
- - '##'
  - 单例模式定义
- - '###'
  - 单例接口
- - '###'
  - 单例实现
- - '###'
  - 引用单例
- - '#'
  - 26. 错误处理
- - '##'
  - 错误处理定义
- - '##'
  - NSError
- - '##'
  - Try/Catch 语句
- - '#'
  - 27. 背景处理
- - '##'
  - 背景处理定义
- - '#'
  - 28. 对象归档
- - '##'
  - 对象归档定义
- - '###'
  - NSCoding
- - '###'
  - 使用归档器（Archiver）
- - '#'
  - 29. Web 服务
- - '##'
  - Web 服务定义
- - '###'
  - Bitly 示例
- - '###'
  - 构造请求字符串
- - '###'
  - 创建会话和 URL
- - '###'
  - 发送和接收响应
- - '###'
  - 解析 JSON
