name: Pro Android with Kotlin
name_cn: Android 高级指南 (Kotlin 版)
slug: pro-android-with-kotlin
toc:
- - '#'
  - 前言
- - '#'
  - 引言
- - '##'
  - 简洁性与表现力
- - '#'
  - 从 Java 到 Kotlin 的过渡
- - '#'
  - 本书的目标读者
- - '#'
  - 源代码
- - '##'
  - 在线文本伴侣
- - '##'
  - 如何阅读本书
- - '#'
  - 关于代码的一些说明
- - '#'
  - 第 1 章 系统
- - '#'
  - Android 操作系统
- - '#'
  - 开发系统
- - '##'
  - Android Studio
- - '##'
  - 虚拟设备
- - '##'
  - SDK
- - '#'
  - 第 2 章 应用
- - '##'
  - 任务
- - '#'
  - 应用清单
- - '#'
  - 活动
- - '##'
  - 声明 Activity
- - '###'
  - 注意事项
- - '##'
  - 启动 Activity
- - '##'
  - Activity 与任务
- - '##'
  - Activity 返回数据
- - '###'
  - 注意事项
- - '#'
  - 意图过滤器
- - '##'
  - Intent 动作
- - '##'
  - Intent 类别
- - '##'
  - Intent 数据
- - '##'
  - Intent 额外数据
- - '##'
  - Intent 标志
- - '##'
  - 系统意图过滤器
- - '##'
  - Activity 生命周期
- - '##'
  - 在 Activity 中保存状态
- - '##'
  - 服务
- - '###'
  - 前台服务
- - '###'
  - 后台服务
- - '###'
  - 声明服务
- - '#'
  - Android 服务属性
- - '##'
  - '`android:enabled`'
- - '##'
  - '`android:exported`'
- - '##'
  - '`android:icon`'
- - '##'
  - '`android:isolatedProcess`'
- - '##'
  - '`android:foregroundServiceType`'
- - '##'
  - '`android:label`'
- - '##'
  - '`android:name`'
- - '##'
  - '`android:permission`'
- - '##'
  - '`android:process`'
- - '##'
  - '`<service>` 元素的子元素'
- - '##'
  - 进程理解
- - '##'
  - 设备保护存储
- - '##'
  - 服务类
- - '##'
  - 启动服务
- - '#'
  - Android 服务的启动与绑定
- - '##'
  - 启动服务
- - '###'
  - 内部服务（同一应用）
- - '###'
  - 外部服务（另一应用）
- - '##'
  - 绑定服务
- - '###'
  - 内部绑定（同一应用）
- - '###'
  - 外部绑定（另一应用）
- - '##'
  - 服务发送的数据
- - '##'
  - 服务的子类
- - '##'
  - 服务的生命周期
- - '##'
  - 更多服务特性
- - '#'
  - 第 3 章 广播
- - '#'
  - Android 广播
- - '##'
  - 显式广播
- - '###'
  - 显式本地广播
- - '###'
  - 显式远程广播
- - '###'
  - 发送到其他应用的显式广播
- - '##'
  - 隐式广播
- - '##'
  - 如何对广播消息类型进行分类？
- - '##'
  - 我们使用本地广播还是远程广播？
- - '##'
  - Intent 过滤器匹配
- - '###'
  - 活跃监听与待命监听
- - '###'
  - 发送隐式广播
- - '###'
  - 接收隐式广播
- - '###'
  - 监听系统广播
- - '###'
  - 为广播增加安全性
- - '####'
  - 保护显式广播
- - '##'
  - 保护隐式广播
- - '##'
  - 从命令行发送广播
- - '#'
  - 此命令
- - '##'
  - 关于广播的随机笔记
- - '#'
  - 第 4 章 内容提供者
- - '##'
  - 内容提供者框架
- - '##'
  - 提供内容
- - '##'
  - 初始化提供者
- - '##'
  - 查询数据
- - '#'
  - 内容提供者查询参数
- - '##'
  - 修改内容
- - '##'
  - 完成 ContentProvider 类
- - '##'
  - 注册内容提供者
- - '#'
  - 内容提供者属性
- - '##'
  - 设计内容 URI
- - '##'
  - 构建内容接口契约
- - '##'
  - 基于 `AbstractCursor` 等的游标类
- - '##'
  - 基于游标接口的游标类
- - '##'
  - 在提供者代码内分派 URI
- - '##'
  - 提供内容文件
- - '##'
  - 通知监听器数据已更改
- - '#'
  - 客户端通过 Content Provider 接收变更通知
- - '#'
  - 扩展 Content Provider
- - '##'
  - 注意
- - '#'
  - 通过 URI 规范化的客户端访问一致性
- - '#'
  - 消费内容
- - '##'
  - 使用 Content Resolver
- - '#'
  - 访问系统 Content Provider
- - '##'
  - '`BlockedNumberContract`'
- - '##'
  - '`CalendarContract`'
- - '##'
  - 通话记录
- - '##'
  - '`ContactsContract`'
- - '##'
  - '`DocumentsContract`'
- - '##'
  - '`FontsContract`'
- - '##'
  - '`MediaStore`'
- - '##'
  - '`Settings`'
- - '#'
  - 探究 Android 设置表
- - '##'
  - 注意事项
- - '#'
  - '`SyncStateContract`'
- - '#'
  - '`UserDictionary`'
- - '#'
  - '`VoicemailContract`'
- - '#'
  - 批量访问内容数据
- - '#'
  - 保护内容安全
- - '##'
  - 1. 通过单一标准保护所有内容
- - '##'
  - 2. 保护特定的 URI 路径
- - '##'
  - 3. 权限豁免
- - '#'
  - 为搜索框架提供内容
- - '#'
  - 文档提供者
- - '##'
  - '`override fun onCreate(): Boolean`'
- - '##'
  - '`override fun queryRoots(projection: Array<out String>?): Cursor`'
- - '##'
  - '`override fun queryChildDocuments(parentDocumentId: String?, projection: Array<out
    String>?, sortOrder: String?): Cursor`'
- - '##'
  - '`override fun queryChildDocuments(parentDocumentId: String?, projection: Array<out
    String>?, queryArgs: Bundle?): Cursor`'
- - '#'
  - 保护 Android 应用中的敏感数据
- - '##'
  - 权限类型
- - '##'
  - 定义权限
- - '##'
  - 使用权限
- - '###'
  - 图 7-1
- - '###'
  - 表 7-1：系统权限
- - '##'
  - 获取权限
- - '##'
  - 系统管理的权限请求
- - '##'
  - 获取特殊权限
- - '##'
  - 功能需求与权限
- - '##'
  - 使用终端处理权限
- - '#'
  - 第 5 章 APIs
- - '##'
  - 数据库
- - '###'
  - 配置 Room 环境
- - '###'
  - Room 架构
- - '###'
  - 数据库
- - '###'
  - 实体
- - '##'
  - 关系
- - '##'
  - 嵌套对象
- - '##'
  - 使用索引
- - '#'
  - Room 数据库访问与查询优化
- - '##'
  - 数据访问：DAO
- - '##'
  - 可观察查询
- - '##'
  - 数据库客户端
- - '##'
  - 事务
- - '##'
  - 迁移数据库
- - '##'
  - 调度
- - '###'
  - '`JobScheduler`'
- - '##'
  - '`AlarmManager`'
- - '###'
  - 表 8-3 发出闹钟
- - '#'
  - 时间参数
- - '#'
  - 通知
- - '##'
  - 创建和显示通知
- - '##'
  - 添加直接回复
- - '##'
  - 通知进度条
- - '##'
  - 可展开通知
- - '##'
  - 修正活动导航
- - '##'
  - 通知分组
- - '##'
  - 通知渠道
- - '##'
  - 通知徽章
- - '##'
  - 联系人
- - '###'
  - 联系人框架内部机制
- - '###'
  - 读取联系人
- - '##'
  - 编写联系人
- - '##'
  - 使用联系人系统 Activity
- - '##'
  - 使用快速联系人徽章
- - '#'
  - 快速联系人徽章
- - '#'
  - 搜索框架
- - '##'
  - 可搜索配置
- - '##'
  - 可搜索 Activity
- - '##'
  - 搜索对话框
- - '##'
  - 搜索小部件
- - '##'
  - 搜索建议
- - '###'
  - 近期查询建议
- - '###'
  - 自定义建议
- - '#'
  - Android 搜索建议与位置服务
- - '##'
  - 位置与地图
- - '###'
  - 最后已知位置
- - '###'
  - 注意事项
- - '###'
  - 追踪位置更新
- - '##'
  - 地理编码
- - '##'
  - 使用 ADB 获取位置信息
- - '##'
  - 地图
- - '##'
  - 偏好设置
- - '#'
  - 第 6 章 Kotlin Compose 界面组件
- - '##'
  - 用户界面
- - '##'
  - 后台任务
- - '###'
  - Java 并发
- - '##'
  - '`AsyncTask` 类'
- - '##'
  - '`Handlers`'
- - '#'
  - 并发与数据加载
- - '##'
  - '`HandlerThread`'
- - '##'
  - Loaders（加载器）
- - '##'
  - Coroutines（协程）
- - '###'
  - 在 ViewModel 中加载数据
- - '##'
  - 支持多种设备
- - '###'
  - 屏幕尺寸
- - '#'
  - 使用备选布局
- - '##'
  - 使用可拉伸图像
- - '#'
  - 像素密度
- - '#'
  - 声明受限屏幕支持
- - '#'
  - 检测设备能力
- - '#'
  - 程序化 UI 设计
- - '##'
  - 手动添加视图
- - '#'
  - 使用 Jetpack Compose 构建器
- - '##'
  - 适配器与列表控件
- - '##'
  - 样式与主题
- - '##'
  - XML 中的字体
- - '##'
  - 2D 动画
- - '###'
  - 自动动画布局
- - '###'
  - 动画位图
- - '###'
  - 属性动画
- - '#'
  - Android 动画与过渡指南
- - '##'
  - 注意事项
- - '##'
  - 视图属性动画
- - '##'
  - 弹簧物理
- - '##'
  - 过渡动画
- - '###'
  - 注意事项
- - '##'
  - 使用过渡启动 Activity
- - '###'
  - 注意
- - '#'
  - Jetpack Compose 中的动画
- - '#'
  - 快速图形 OpenGL ES
- - '#'
  - 在 Activity 中显示 OpenGL 表面
- - '#'
  - 创建自定义 OpenGL 视图元素
- - '#'
  - 带顶点缓冲区的三角形
- - '##'
  - 使用顶点缓冲区和索引缓冲区的四边形
- - '##'
  - 创建和使用渲染器
- - '##'
  - 投影
- - '##'
  - 运动
- - '##'
  - 光照
- - '##'
  - 纹理
- - '##'
  - 使用 Vulkan 实现快速图形
- - '##'
  - 使用可移动项目的 UI 设计
- - '##'
  - 菜单和操作栏
- - '###'
  - 选项菜单
- - '##'
  - 上下文菜单
- - '##'
  - 上下文操作模式
- - '##'
  - 弹出菜单
- - '##'
  - 进度条
- - '##'
  - 使用 Fragment
- - '###'
  - 创建 Fragment
- - '#'
  - 从 Kotlin 代码中添加 Fragment
- - '#'
  - 从 Activity 管理 Fragment
- - '#'
  - 与 Fragment 通信
- - '#'
  - 应用微件
- - '#'
  - 拖放
- - '#'
  - 拖放实现指南
- - '##'
  - 定义拖放数据
- - '##'
  - 定义拖拽阴影
- - '##'
  - 开始拖拽
- - '##'
  - 监听拖拽事件
- - '##'
  - 多点触控
- - '##'
  - 画中画模式
- - '##'
  - 文字转语音
- - '#'
  - 第 7 章 Firebase
- - '##'
  - Firebase 云存储
- - '##'
  - Firebase 云消息传递
- - '#'
  - 第 8 章 开发
- - '#'
  - 在 Kotlin 中编写可重用库
- - '##'
  - 启动一个库模块
- - '##'
  - 创建库
- - '##'
  - 测试库
- - '##'
  - 使用库
- - '#'
  - 发布库
- - '#'
  - 使用 Kotlin 的高级监听器
- - '#'
  - 多线程
- - '##'
  - 兼容库
- - '#'
  - Kotlin 最佳实践
- - '##'
  - 函数式编程
- - '##'
  - 顶级函数与数据
- - '##'
  - 类扩展
- - '##'
  - 命名参数
- - '##'
  - 作用域函数
- - '##'
  - 可空性
- - '##'
  - 数据类
- - '##'
  - 解构
- - '##'
  - 多行字符串字面量
- - '##'
  - 内部函数和类
- - '##'
  - 字符串插值
- - '##'
  - 限定“this”
- - '##'
  - 委托
- - '##'
  - 重命名导入
- - '##'
  - Kotlin on JavaScript
- - '###'
  - 创建一个 JavaScript 模块
- - '###'
  - 使用 JavaScript 模块
- - '#'
  - 第 9 章 构建
- - '##'
  - 构建相关文件
- - '##'
  - 模块配置
- - '##'
  - 模块通用配置
- - '##'
  - 模块构建变体
- - '##'
  - 构建类型
- - '#'
  - 产品风味
- - '#'
  - 源集
- - '#'
  - 从控制台运行构建
- - '#'
  - 签名
- - '#'
  - 第 10 章 通信
- - '#'
  - 通信
- - '##'
  - '`ResultReceiver` 类'
- - '##'
  - 与后端通信
- - '##'
  - 使用 `HttpsURLConnection` 通信
- - '##'
  - 使用 Volley 进行网络通信
- - '##'
  - 设置测试服务器
- - '##'
  - Android 与 NFC
- - '##'
  - 与 NFC 标签通信
- - '#'
  - NFC 开发指南
- - '##'
  - 点对点 NFC 数据交换
- - '##'
  - NFC 卡模拟
- - '##'
  - Android 与蓝牙
- - '###'
  - 一个蓝牙 RfComm 服务器
- - '##'
  - 一个 Android RfComm 客户端
- - '#'
  - 套接字连接与可穿戴设备开发
- - '##'
  - 蓝牙套接字通信
- - '##'
  - 硬件
- - '###'
  - 可穿戴设备编程
- - '###'
  - 可穿戴设备开发
- - '#'
  - 表盘复杂功能
- - '##'
  - 可穿戴应用用户界面
- - '##'
  - 可穿戴设备表盘
- - '##'
  - 添加表盘复杂功能
- - '##'
  - 提供复杂功能数据
- - '##'
  - 可穿戴设备上的通知
- - '##'
  - 控制应用在可穿戴设备上的可见性
- - '##'
  - Wear 中的身份验证
- - '##'
  - Wear 中的语音功能
- - '#'
  - “OK, Google”语音操作与数据提取
- - '#'
  - 可穿戴设备的扬声器
- - '#'
  - Wear 中的位置功能
- - '#'
  - Wear 中的数据通信
- - '#'
  - 使用 Android TV 进行编程
- - '##'
  - Android TV 使用场景
- - '##'
  - 启动 Android TV Studio 项目
- - '##'
  - Android TV 硬件特性
- - '##'
  - Android TV 的 UI 开发
- - '##'
  - 用于内容搜索的推荐频道
- - '##'
  - 内容搜索的建议行
- - '#'
  - Android TV 内容搜索
- - '#'
  - Android TV 游戏
- - '#'
  - Android TV 频道
- - '#'
  - 使用 Android Auto 和 Automotive OS 进行编程
- - '#'
  - 播放和录制声音
- - '##'
  - 短声音片段
- - '##'
  - 播放媒体
- - '##'
  - 录制音频
- - '##'
  - 使用摄像头
- - '#'
  - 拍摄照片
- - '#'
  - 录制视频
- - '#'
  - 编写你自己的相机应用
- - '##'
  - Android 与 NFC
- - '##'
  - Android 与蓝牙
- - '##'
  - Android 传感器
- - '#'
  - 近距传感器，例如：检测与用户耳朵之间的距离
- - '##'
  - 获取传感器能力
- - '##'
  - 监听传感器事件
- - '###'
  - 表 14-3：传感器事件数值
- - '##'
  - 与电话通话交互
- - '###'
  - 监控电话状态变化
- - '##'
  - 发起拨号流程
- - '##'
  - 创建自定义电话通话界面
- - '##'
  - 指纹认证
- - '#'
  - 第 11 章 测试
- - '#'
  - 单元测试
- - '##'
  - 标准单元测试
- - '##'
  - 使用桩版 Android 框架的单元测试
- - '##'
  - 使用模拟 Android 框架的单元测试
- - '##'
  - 使用 Mocking 的单元测试
- - '##'
  - 集成测试
- - '###'
  - 测试服务
- - '###'
  - 测试 Intent 服务
- - '##'
  - 测试内容提供者
- - '##'
  - 测试广播接收器
- - '##'
  - 用户界面测试
- - '#'
  - 第 12 章 故障排查
- - '##'
  - 日志记录
- - '#'
  - 日志开关
- - '#'
  - 调试
- - '#'
  - 性能监控
- - '#'
  - 内存使用监控
- - '#'
  - 第 13 章 分发应用
- - '##'
  - Android App Bundle
- - '##'
  - 你自己的应用商店
- - '##'
  - Google Play 商店
- - '#'
  - 第 14 章 即时应用
- - '##'
  - 开发即时应用
- - '#'
  - 第 15 章 CLI
- - '##'
  - SDK 工具
- - '#'
  - Android SDK 工具指南
- - '##'
  - 工具概述
- - '##'
  - 父目录中的工具
- - '##'
  - SDK 构建工具
- - '#'
  - '`x86_64-linux-android-ld`'
- - '#'
  - '`zipalign`'
- - '#'
  - SDK Platform Tools
- - '#'
  - Android Debug Bridge (ADB)
- - '#'
  - 索引
- - '#'
  - AbstractCursor 及其相关类
- - '##'
  - 获取特殊权限
- - '##'
  - Activity
- - '##'
  - 闹钟事件
- - '##'
  - Android
- - '##'
  - Android TV
- - '##'
  - 动画位图
- - '##'
  - API
- - '##'
  - 应用声明
- - '##'
  - 应用框架
- - '##'
  - 应用营销
- - '##'
  - 应用构建流程
- - '#'
  - 签名
- - '#'
  - 应用微件
- - '#'
  - Artifactory
- - '#'
  - 音频
- - '#'
  - 自动动画布局
- - '#'
  - 辅助 `AlarmManager` 方法
- - '#'
  - AVD 管理器
- - '#'
  - B
- - '#'
  - 后台服务
- - '#'
  - 后台任务，UI
- - '#'
  - 批量访问内容数据
- - '#'
  - Beam 技术
- - '#'
  - 蓝牙
- - '#'
  - BlueCove
- - '#'
  - 启动/关机
- - '#'
  - 广播
- - '#'
  - C
- - '#'
  - 内容解析器
- - '#'
  - C++
- - '#'
  - 相机
- - '#'
  - 基于云的内容提供器
- - '#'
  - COARSE 位置权限
- - '#'
  - 命令行工具
- - '#'
  - 通信
- - '#'
  - Volley
- - '#'
  - 伴生对象
- - '#'
  - 兼容性 API
- - '#'
  - 兼容性库
- - '#'
  - 可组合项
- - '#'
  - 消费内容
- - '#'
  - 联系人
- - '#'
  - 内容接口契约
- - '#'
  - 内容提供器
- - '#'
  - 上下文菜单
- - '#'
  - 上下文操作模式
- - '#'
  - 协程
- - '#'
  - 公司项目
- - '##'
  - '`createNotificationChannel()`'
- - '##'
  - '`Cursor` 对象'
- - '##'
  - '`CustomProvider` 类'
- - '##'
  - D
- - '##'
  - '`DocumentsContract`'
- - '##'
  - 拖放
- - '##'
  - E
- - '##'
  - F
- - '##'
  - G
- - '##'
  - H
- - '##'
  - I
- - '#'
  - LiveWallpapersPicker 活动
- - '#'
  - 地图活动
- - '#'
  - Music2 活动
- - '#'
  - NetSpeed 活动
- - '#'
  - OpenWnn 活动
- - '#'
  - 照片活动
- - '#'
  - PrebuiltBugle 活动
- - '#'
  - PrebuiltDeskClockGoogle 活动
- - '#'
  - PrebuiltGmail 活动
- - '#'
  - PrintSpooler 活动
- - '#'
  - 优先级属性
- - '#'
  - 视频活动
- - '#'
  - WallpaperPickerGooglePrebuilt 活动
- - '#'
  - WebViewStub 活动
- - '#'
  - YouTube 活动
- - '##'
  - 意图标志
- - '##'
  - 意图
- - '##'
  - IntentService 对象
- - '##'
  - J
- - '###'
  - Java 并发
- - '###'
  - Java/Kotlin 平台
- - '###'
  - Java/Kotlin 线程
- - '###'
  - JavaScript 模块
- - '##'
  - 添加文件夹
- - '##'
  - '`build.gradle` 文件'
- - '##'
  - '`dependsOn()` 声明'
- - '##'
  - 文件夹/文件，删除
- - '##'
  - Gradle 视图
- - '##'
  - HTML 页面
- - '##'
  - '`injectedObject`'
- - '##'
  - Kotlin 文件
- - '##'
  - '`Main.kt` 文件'
- - '##'
  - '`onCreate()` 回调'
- - '##'
  - '`WebView` 元素'
- - '##'
  - '`java.util.concurrency` 包'
- - '##'
  - Java 虚拟机
- - '##'
  - Jetpack Compose
- - '##'
  - Jetpack Compose 构建器
- - '##'
  - 构建文件
- - '##'
  - 可组合项
- - '##'
  - 碎片
- - '##'
  - '`HomeScreen`'
- - '##'
  - Kotlin
- - '##'
  - '`MyTopBar` 类'
- - '##'
  - '`navController`'
- - '##'
  - 屏幕过渡
- - '##'
  - '`topBar`'
- - '##'
  - '`ViewModel`'
- - '##'
  - Jetpack 库
- - '##'
  - '`jobFinished()`'
- - '##'
  - '`JobInfo` 对象'
- - '##'
  - '`JobIntentService`'
- - '##'
  - '`JobScheduler` 对象'
- - '##'
  - '`JobScheduler` 方法'
- - '##'
  - K
- - '###'
  - Kotlin
- - '##'
  - L
- - '###'
  - 最后已知位置
- - '###'
  - 布局
- - '###'
  - '`LifecycleOwner`'
- - '###'
  - '`LinearLayout`'
- - '###'
  - 监听器
- - '###'
  - '`LiveData` 对象'
- - '###'
  - 加载器
- - '###'
  - 本地广播接收器
- - '###'
  - 本地显式广播
- - '###'
  - '`Location` 对象'
- - '###'
  - 位置与地图
- - '###'
  - '`LocationRequest`'
- - '###'
  - 日志记录
- - '##'
  - M
- - '###'
  - 清单顶级条目
- - '###'
  - 媒体
- - '###'
  - '`MediaStore`'
- - '###'
  - 基于内存的数据库
- - '###'
  - 菜单和操作栏
- - '###'
  - '`Messenger`'
- - '###'
  - 元数据
- - '###'
  - '`migrate()` 方法'
- - '###'
  - 迁移数据库
- - '###'
  - '`mimeTypeFilter`'
- - '###'
  - 模拟
- - '###'
  - 监控
- - '###'
  - '`MotionEvent`'
- - '###'
  - 多行字符串字面量
- - '###'
  - 多线程
- - '###'
  - 多点触控事件
- - '###'
  - '`mutableStateOf()`'
- - '###'
  - '`MyContactsDataSource` 类'
- - '###'
  - '`MyContactsRepository`'
- - '###'
  - '`MyGLSurfaceView`'
- - '##'
  - N
- - '###'
  - 命名参数
- - '###'
  - 原生开发工具包 (NDK)
- - '###'
  - 嵌套对象
- - '###'
  - 网络
- - '###'
  - NFC
- - '###'
  - 九宫格位图
- - '###'
  - 非本地显式广播
- - '###'
  - 通知 API
- - '###'
  - '`NotificationChannel` 对象'
- - '###'
  - 可穿戴设备上的通知
- - '###'
  - 可空性
- - '##'
  - O
- - '###'
  - '`ObjectAnimator`'
- - '###'
  - '`observeForever()` 方法'
- - '###'
  - '`onActivityResult()` 方法'
- - '###'
  - '`onBackPressed()` 事件处理方法'
- - '###'
  - '`onBind()` 方法'
- - '###'
  - '`onBindViewHolder()` 函数'
- - '###'
  - '`onConfigurationChanged()` 方法'
- - '###'
  - '`onContextItemSelected`'
- - '###'
  - '`onCreate()` 方法'
- - '###'
  - '`onCreate(...)` 方法'
- - '###'
  - '`onCreateContextMenu(...)`'
- - '###'
  - '`onCreateViewHolder()` 函数'
- - '#'
  - 通信
- - '#'
  - 声音
- - '##'
  - 音乐播放
- - '##'
  - 录音
- - '##'
  - 弹簧物理学
- - '#'
  - 存储访问框架 (SAF)
- - '#'
  - 样式和主题
- - '#'
  - SyncAdapter
- - '#'
  - SyncStateContract
- - '#'
  - '`SYSTEM_ALERT_WINDOW` 权限'
- - '#'
  - 系统 Intent 过滤器
- - '#'
  - 系统管理的权限请求
- - '#'
  - T
- - '#'
  - 任务
- - '#'
  - 电话
- - '#'
  - 电视
- - '#'
  - 测试
- - '##'
  - 开发者
- - '##'
  - 开发
- - '###'
  - 功能视角
- - '###'
  - 非功能视角
- - '#'
  - TextToSpeech 类
- - '#'
  - 文本转语音框架
- - '#'
  - TextView 对象
- - '#'
  - '`throwIfCancelled()`'
- - '#'
  - Toast 消息
- - '#'
  - 事务
- - '#'
  - TransitionManager
- - '#'
  - 过渡动画
- - '#'
  - 三角形和四边形图形
- - '#'
  - Triangle 类
- - '#'
  - '`tts.synthesizeToFile()` 方法'
- - '#'
  - 2D 动画
- - '##'
  - 活动、过渡
- - '##'
  - 动画位图
- - '##'
  - 自动动画布局
- - '##'
  - Jetpack Compose
- - '##'
  - 属性动画
- - '##'
  - 弹簧物理学
- - '##'
  - 过渡
- - '##'
  - 视图属性动画器
- - '#'
  - U
- - '#'
  - '`uncanonicalize(url:Uri)`'
- - '#'
  - '`uniform sampler2D texture`'
- - '#'
  - 单元测试
- - '##'
  - 目标
- - '##'
  - Android 框架
- - '##'
  - 模拟
- - '##'
  - 存根
- - '##'
  - 模拟
- - '###'
  - '`参见 模拟`'
- - '###'
  - 设置
- - '###'
  - 标准单元测试
- - '###'
  - 测试类
- - '###'
  - 测试选项
- - '#'
  - URI 规范化
- - '#'
  - '`Uri.parse()` 方法'
- - '#'
  - '`Uri.withAppendedPath()` 方法'
- - '#'
  - USB
- - '#'
  - 用户账户
- - '#'
  - UserDictionary
- - '#'
  - 用户输入
- - '#'
  - 用户界面 (UI)
- - '##'
  - 适配器
- - '##'
  - 应用微件
- - '##'
  - 后台任务
- - '###'
  - '`参见 后台任务`, UI'
- - '##'
  - 2D 动画
- - '###'
  - '`参见 2D 动画`'
- - '##'
  - 拖放
- - '###'
  - '`参见 拖放`'
- - '##'
  - 最终用户应用
- - '##'
  - XML 中的字体
- - '##'
  - 碎片
- - '###'
  - 活动
- - '###'
  - 通信
- - '###'
  - 创建
- - '###'
  - 处理
- - '###'
  - 生命周期
- - '##'
  - 列表控件
- - '##'
  - 菜单和操作栏
- - '###'
  - '`参见 菜单和操作栏`'
- - '##'
  - OpenGL ES
- - '###'
  - '`参见 OpenGL ES`'
- - '##'
  - 画中画模式
- - '##'
  - 编程式 UI 设计
- - '###'
  - 添加视图
- - '###'
  - Jetpack Compose 构建器
- - '###'
  - 布局
- - '###'
  - UI 对象
- - '##'
  - 样式和主题
- - '##'
  - 支持多种设备
- - '###'
  - 声明受限屏幕支持
- - '###'
  - 检测设备能力
- - '###'
  - 设备兼容性
- - '###'
  - 像素密度
- - '###'
  - 屏幕尺寸
- - '###'
  - 测试
- - '##'
  - 文本转语音框架
- - '##'
  - 可移动项的 UI 设计
- - '##'
  - Vulkan API
- - '#'
  - V
- - '#'
  - 顶点缓冲区
- - '#'
  - ViewModels
- - '#'
  - '`viewModelScope`'
- - '#'
  - 视图属性动画器
- - '#'
  - 虚拟设备
- - '#'
  - VoicemailContract
- - '#'
  - VoicemailContract.Status
- - '#'
  - VoicemailContract.Voicemails
- - '#'
  - 网络电话 (VoIP)
- - '#'
  - VpnService
- - '#'
  - '`vTexture`'
- - '#'
  - Vulkan API
- - '#'
  - W, X, Y, Z
- - '#'
  - 可穿戴设备
- - '##'
  - 应用可见性
- - '##'
  - 身份验证
- - '##'
  - 复杂功能数据提供器
- - '###'
  - '`CustomComplicationProviderService` 类'
- - '###'
  - '`ProviderUpdateRequester` 类'
- - '###'
  - 服务声明
- - '##'
  - 数据通信
- - '###'
  - '`参见 可穿戴设备中的数据通信`'
- - '##'
  - 开发
- - '###'
  - 连接到模拟器
- - '###'
  - 调试
- - '###'
  - 表盘复杂功能
- - '###'
  - 模式
- - '###'
  - 智能手机
- - '###'
  - 虚拟 Wear 设备
- - '###'
  - 表盘
- - '##'
  - Wear 复选框
- - '##'
  - Wear OS by Google
- - '###'
  - 模拟器
- - '###'
  - 表盘复杂功能
- - '####'
  - '`参见 可穿戴设备表盘复杂功能`'
- - '###'
  - 表盘
- - '###'
  - 位置检测
- - '###'
  - 通知
- - '####'
  - '`参见 可穿戴设备上的通知`'
- - '###'
  - 扬声器
- - '###'
  - UI
- - '###'
  - 语音功能
- - '####'
  - 数据提取
- - '####'
  - Intent 过滤器
- - '####'
  - 标签属性
- - '####'
  - '`<action>` 元素'
- - '####'
  - '`onActivityResult(...)`'
- - '####'
  - 选项
- - '####'
  - 语音识别
- - '####'
  - 系统语音命令
- - '#'
  - 可穿戴设备表盘复杂功能
- - '##'
  - '`AndroidManifest.xml`'
- - '##'
  - '`ci.onCreate(...)`'
- - '##'
  - '`ComplicationConfigActivity` 类'
- - '##'
  - 复杂功能数据
- - '##'
  - 常量/工具方法
- - '##'
  - '`drawComplications()` 方法'
- - '##'
  - 表盘类
- - '##'
  - '`getTappedComplicationId()` 方法'
- - '##'
  - '`init()` 方法'
- - '##'
  - 布局
- - '##'
  - '`MyComplications` 类'
- - '##'
  - '`onComplicationDataUpdate()` 方法'
- - '##'
  - '`onComplicationTap()` 方法'
- - '##'
  - 复杂功能点按
- - '##'
  - '`onCreate()` 方法'
- - '##'
  - '`onDestroy()` 方法'
- - '##'
  - '`onDraw(...)`'
- - '##'
  - '`onTapCommand(...)`'
- - '##'
  - '`retrieveInitialComplicationsData` 方法'
- - '##'
  - '`updateComplicationBounds()` 方法'
- - '##'
  - 更新
- - '#'
  - 基于微件的搜索流程
- - '#'
  - Wi-Fi
- - '#'
  - 编写联系人
