name: OS X and iOS Kernel Programming
name_cn: OS X 与 iOS 内核编程
slug: os-x-and-ios-kernel-programming
toc:
- - '#'
  - OS X 与 iOS 内核编程
- - '##'
  - 目录速览
- - '#'
  - 目录
- - '##'
  - 关于作者
- - '##'
  - 关于技术审校
- - '##'
  - 引言
- - '###'
  - 本书面向的读者？
- - '###'
  - 书籍结构
- - '##'
  - 第 1 章
- - '#'
  - 操作系统基础
- - '###'
  - 操作系统的角色
- - '###'
  - 进程管理
- - '###'
  - 进程地址空间
- - '###'
  - 操作系统服务
- - '###'
  - 虚拟内存
- - '###'
  - 调度
- - '###'
  - 硬件与驱动程序
- - '###'
  - 总结
- - '##'
  - 第 2 章
- - '#'
  - Mac OS X 与 iOS
- - '##'
  - NeXTSTEP
- - '###'
  - 编程 API
- - '####'
  - Objective-C
- - '###'
  - 支持的平台
- - '###'
  - 64 位操作系统
- - '###'
  - iOS
- - '###'
  - XNU 内核
- - '###'
  - 内核扩展 (KEXT)
- - '###'
  - Mach
- - '####'
  - 任务与线程
- - '####'
  - 调度
- - '####'
  - Mach IPC：端口与消息
- - '###'
  - Mach 异常
- - '###'
  - 时间管理
- - '###'
  - 内存管理
- - '####'
  - 任务地址空间
- - '####'
  - 内核地址空间管理
- - '####'
  - VM 映射与条目
- - '####'
  - 物理映射
- - '####'
  - VM 对象
- - '###'
  - 页面
- - '###'
  - 检查任务的地址空间
- - '###'
  - 分页器
- - '###'
  - Mach 中的内存分配
- - '###'
  - BSD 层
- - '####'
  - 系统调用
- - '####'
  - 网络
- - '####'
  - 文件系统
- - '####'
  - 虚拟文件系统
- - '####'
  - 统一缓冲区缓存
- - '##'
  - I/O Kit
- - '##'
  - Libkern 库
- - '##'
  - 平台专家
- - '###'
  - 摘要
- - '##'
  - 第 3 章
- - '##'
  - Xcode 与内核开发环境
- - '###'
  - 首选语言：C++
- - '###'
  - Xcode
- - '####'
  - “Hello World” 内核扩展
- - '####'
  - 加载与卸载内核扩展
- - '###'
  - 排版后的内容
- - '###'
  - 使用控制台查看输出
- - '###'
  - 总结
- - '##'
  - 第 4 章
- - '#'
  - I/O Kit 框架
- - '###'
  - I/O Kit 模型
- - '###'
  - 对象关系
- - '###'
  - Info.plist 文件
- - '####'
  - 列表 4-1 假设外部磁盘的驱动程序特性，包含匹配 FireWire 和 USB 连接的字典
- - '###'
  - 驱动程序类
- - '####'
  - 列表 4-2 “IOKitTest.h”教程
- - '####'
  - 列表 4-3 “IOKitTest.cpp”教程
- - '###'
  - '`IORegistryExplorer`'
- - '###'
  - 内核库：`libkern`
- - '####'
  - OSObject
- - '####'
  - 容器类
- - '###'
  - 总结
- - '##'
  - 第 5 章
- - '##'
  - 从应用程序与驱动程序交互
- - '###'
  - I/O Kit 框架
- - '###'
  - 查找驱动程序
- - '###'
  - 监测设备移除
- - '###'
  - 修改驱动程序属性
- - '###'
  - 排版后的文档
- - '###'
  - 基于状态的交互
- - '###'
  - 来自驱动程序的通知
- - '###'
  - 排版后的文本
- - '###'
  - 总结
- - '##'
  - 第 6 章
- - '#'
  - 内存管理
- - '##'
  - 内存类型
- - '###'
  - CPU 物理地址
- - '###'
  - 总线物理地址
- - '###'
  - 用户和内核虚拟地址
- - '##'
  - 内存字节序：大端序 vs. 小端序
- - '##'
  - 32 位与 64 位内存寻址
- - '###'
  - 内存分配
- - '###'
  - 底层分配机制
- - '###'
  - Mach 区域分配器
- - '###'
  - kalloc 族
- - '####'
  - BSD 系统中的内存分配
- - '####'
  - I/O Kit 内存分配
- - '####'
  - 使用 C++ new 运算符分配内存
- - '###'
  - 内存描述符
- - '###'
  - '`IOBufferMemoryDescriptor`'
- - '###'
  - 其他内存描述符
- - '###'
  - 内存映射
- - '####'
  - 将用户空间任务的内存映射到内核空间
- - '####'
  - IOMemoryMap 类
- - '####'
  - 将内存从内核空间映射到用户空间任务
- - '####'
  - 将内存映射到特定用户空间任务
- - '####'
  - 物理地址映射
- - '###'
  - 总结
- - '##'
  - 第 7 章
- - '#'
  - 同步与线程化
- - '##'
  - 同步原语
- - '##'
  - 原子操作
- - '###'
  - 锁机制
- - '####'
  - 自旋锁
- - '####'
  - 互斥锁
- - '####'
  - 条件变量
- - '###'
  - 读/写互斥锁
- - '###'
  - 同步异步事件：工作循环
- - '###'
  - IOCommandGate
- - '###'
  - 定时器
- - '###'
  - 释放工作循环
- - '###'
  - 内核线程
- - '###'
  - 总结
- - '#'
  - 通用串行总线
- - '##'
  - USB 架构
- - '###'
  - USB 传输速度
- - '###'
  - 主机控制器
- - '###'
  - USB 协议
- - '###'
  - 端点
- - '###'
  - USB 描述符
- - '###'
  - USB 设备类别
- - '##'
  - I/O Kit USB 支持
- - '###'
  - USB 设备与驱动程序处理
- - '###'
  - 加载 USB 驱动程序
- - '###'
  - USB Prober
- - '###'
  - 驱动程序示例：USB 大容量存储设备驱动程序
- - '####'
  - 驱动程序属性列表与加载
- - '####'
  - 驱动程序启动
- - '####'
  - 处理设备移除
- - '####'
  - 枚举接口
- - '####'
  - 枚举端点
- - '####'
  - 执行设备请求
- - '####'
  - 控制请求
- - '####'
  - 对批量端点和中断端点执行 I/O
- - '####'
  - 处理错误和管道停滞
- - '###'
  - 等时传输 I/O
- - '###'
  - 异步请求
- - '###'
  - 总结
- - '##'
  - 第 9 章
- - '#'
  - PCI Express 与 Thunderbolt
- - '##'
  - PCI Express
- - '##'
  - Thunderbolt
- - '##'
  - ExpressCard
- - '###'
  - 配置空间寄存器
- - '##'
  - I/O Kit 中的 PCI
- - '###'
  - 驱动匹配与加载
- - '###'
  - 驱动程序示例：一个简单的 PCI 驱动程序
- - '###'
  - 访问配置空间寄存器
- - '###'
  - 访问扩展配置空间
- - '###'
  - 搜索能力寄存器
- - '###'
  - PCI I/O 内存区域
- - '###'
  - 枚举 I/O 区域
- - '###'
  - 映射与访问设备内存区域
- - '###'
  - 访问 I/O 空间
- - '###'
  - 处理设备移除
- - '###'
  - 中断
- - '####'
  - I/O Kit 中断机制
- - '####'
  - 注册以接收中断
- - '####'
  - 启用消息 Signaled 中断
- - '###'
  - 处理主中断
- - '###'
  - 处理次中断
- - '###'
  - 直接内存访问
- - '####'
  - 将物理地址转换为总线地址
- - '####'
  - 为 DMA 准备内存
- - '####'
  - 构建分散/聚集列表
- - '###'
  - IODMACommand 类
- - '###'
  - 总结
- - '##'
  - 第 10 章
- - '##'
  - 电源管理
- - '###'
  - I/O Registry 电源平面
- - '####'
  - I/O Kit 中的电源管理
- - '###'
  - 响应电源状态变更
- - '###'
  - 请求电源状态变更
- - '###'
  - 处理设备空闲状态
- - '###'
  - 观察设备电源状态变化
- - '###'
  - 综合运用
- - '###'
  - 总结
- - '##'
  - 第 11 章
- - '##'
  - 串口驱动程序
- - '###'
  - Mac OS X 串口架构概述
- - '###'
  - 串行端口驱动程序
- - '###'
  - 手动实例化驱动程序对象
- - '###'
  - 实现 `IOSerialDriverSync` 类
- - '###'
  - 实现 `IOSerialDriverSync` 接口的同步问题
- - '###'
  - 串口状态
- - '###'
  - 代码分析
- - '###'
  - 串口事件
- - '###'
  - 排版后内容
- - '###'
  - 串行数据传输
- - '###'
  - 从用户空间访问串口
- - '###'
  - 摘要
- - '##'
  - 第 12 章
- - '##'
  - 音频驱动程序
- - '###'
  - 数字音频与音频设备简介
- - '###'
  - 音频设备与驱动概念
- - '##'
  - Core Audio
- - '##'
  - I/O Kit 音频支持
- - '###'
  - 实现音频驱动程序
- - '###'
  - 驱动程序与硬件初始化
- - '####'
  - 你可能已经注意到，许多常见的 I/O Kit 生命周期方法，例如 `start()` 和 `stop()` ，都缺失了。这是因为父类 `IOAudioDevice`
    已经为我们实现了这些方法。`start()` 方法会负责注册电源管理，然后调用驱动程序应实现的 `initHardware()` 方法。
- - '###'
  - 注册音频控件
- - '###'
  - 排版后内容
- - '###'
  - 实现音频引擎
- - '###'
  - I/O 引擎初始化
- - '###'
  - 创建与初始化音频流
- - '###'
  - 处理格式变更
- - '###'
  - 采样裁剪与格式转换
- - '###'
  - 启动和停止音频引擎
- - '###'
  - 引擎操作：处理中断和时间戳
- - '###'
  - 其他音频引擎功能
- - '###'
  - 总结
- - '##'
  - 第 13 章
- - '#'
  - 网络
- - '##'
  - 网络内存缓冲区
- - '###'
  - 使用内存缓冲区（Memory Buffers）
- - '##'
  - 网络内核扩展（Network Kernel Extensions）
- - '###'
  - 内核控制 KPI
- - '###'
  - Socket 过滤器
- - '###'
  - 使用套接字过滤器构建应用层防火墙
- - '###'
  - AppWall 运行机制与数据结构
- - '###'
  - 附加与分离过滤器
- - '###'
  - 检索套接字的 IP 地址
- - '###'
  - 处理连接
- - '###'
  - Socket 数据输入与输出
- - '###'
  - 互联网协议过滤器
- - '###'
  - 接口过滤器
- - '##'
  - 调试和测试网络扩展
- - '###'
  - I/O Kit 中的网络功能
- - '###'
  - 构建一个简单的以太网控制器驱动程序
- - '####'
  - MyEthernetDriver 的设计
- - '###'
  - 驱动程序初始化与启动
- - '####'
  - 介质与状态选择
- - '####'
  - 配置设备硬件地址
- - '####'
  - 启用和禁用设备
- - '####'
  - 发送网络数据包
- - '###'
  - 排版后内容
- - '###'
  - 接收数据包
- - '###'
  - 试驾 MyEthernetDriver
- - '###'
  - 本章小结
- - '##'
  - 第 14 章
- - '##'
  - 存储系统
- - '###'
  - 传输层驱动程序
- - '###'
  - IOBlockStorageDevice 接口
- - '##'
  - 构建 RAM 磁盘设备
- - '###'
  - 分区方案
- - '####'
  - 实现分区方案示例
- - '###'
  - 排版后的内容
- - '###'
  - 媒体内容提示属性
- - '###'
  - 媒体过滤器驱动程序
- - '####'
  - 用于加密的示例过滤方案
- - '####'
  - 创建自定义 GUID 分区表
- - '###'
  - 排版后的文本
- - '###'
  - 总结
- - '##'
  - 第 15 章
- - '##'
  - 用户空间 USB 驱动程序
- - '###'
  - 幕后原理
- - '###'
  - IOUSBLib 框架
- - '###'
  - 处理异步操作
- - '###'
  - '`IOUSBDeviceInterface` 类'
- - '###'
  - IOUSBInterfaceInterface 类
- - '###'
  - 属性方法(Property Methods)
- - '###'
  - 端点数据传输方法(Endpoint Data Transfer Methods)
- - '###'
  - 低延迟等时传输
- - '###'
  - 摘要
- - '##'
  - 第 16 章
- - '##'
  - 调试
- - '###'
  - 常见问题类型
- - '###'
  - 内核恐慌
- - '###'
  - 调试机制
- - '####'
  - 从启动期间的崩溃中恢复
- - '####'
  - 使用 IOLog() 进行跟踪
- - '###'
  - 打印堆栈回溯
- - '###'
  - 通过 FireWire 进行远程跟踪
- - '####'
  - 远程内核核心转储
- - '###'
  - KDB
- - '###'
  - 通过以太网或 FireWire 使用 GDB 进行远程调试
- - '####'
  - 配置主机
- - '####'
  - 连接到远程目标
- - '####'
  - 使用 FireWire 进行调试
- - '###'
  - 对运行中的内核进行实时调试
- - '###'
  - 使用虚拟机进行调试
- - '###'
  - 使用 GDB 在内核中进行调试
- - '####'
  - 内核 GDB 宏
- - '####'
  - 为 KEXT 创建符号信息
- - '####'
  - 使用 GDB 调试 KEXT
- - '###'
  - 理解内核恐慌日志
- - '###'
  - x86-64 调用约定
- - '###'
  - 使用活动监视器诊断挂起的进程
- - '###'
  - 查找内存和资源泄漏
- - '###'
  - 摘要
- - '##'
  - 第 17 章
- - '#'
  - 高级内核编程
- - '###'
  - 内核中的 SSE 和浮点运算
- - '###'
  - 多函数驱动程序
- - '###'
  - 编写 I/O Kit 家族（Families）
- - '###'
  - 内核控制 KPI
- - '####'
  - 内核控制注册
- - '####'
  - 客户端连接
- - '####'
  - 获取与设置选项
- - '###'
  - 从用户空间访问内核控制接口
- - '###'
  - 在内核中处理进程
- - '###'
  - 加载资源
- - '####'
  - 超越 KEXT 资源
- - '###'
  - 来自内核驱动程序的通知
- - '###'
  - 总结
- - '##'
  - 第 18 章
- - '#'
  - 部署
- - '###'
  - 安装与加载内核扩展
- - '###'
  - Mac App Store 上的内核扩展
- - '###'
  - 内核扩展的版本管理
- - '###'
  - 测试与质量保证
- - '###'
  - 打包 KEXT 与软件
- - '####'
  - 为 Hello World 内核扩展构建软件包
- - '####'
  - 向软件包添加内容
- - '####'
  - 配置软件包
- - '####'
  - 构建软件包
- - '####'
  - 卸载软件包
- - '###'
  - 总结
- - '##'
  - 索引
- - '###'
  - 数字与符号
- - '###'
  - A
- - '###'
  - 数字音频与音频设备
- - '####'
  - 硬件初始化
- - '####'
  - I/O 引擎初始化
- - '####'
  - I/O Kit 音频支持
- - '####'
  - 注册音频控制
- - '####'
  - 音频 HAL
- - '###'
  - B
- - '###'
  - C
- - '####'
  - 条件变量
- - '####'
  - 配置空间寄存器
- - '###'
  - D
- - '###'
  - E
- - '###'
  - F
- - '###'
  - G
- - '###'
  - H
- - '###'
  - I, J
- - '###'
  - K
- - '###'
  - L
- - '###'
  - M
- - '###'
  - N
- - '###'
  - O
- - '###'
  - P, Q
- - '###'
  - R
- - '###'
  - S
- - '####'
  - Socket 过滤器
- - '####'
  - 挂接与分离
- - '####'
  - 自旋锁
- - '####'
  - 存储系统
- - '#####'
  - '`IOBlockStorageDevice` 接口'
- - '#####'
  - 分区方案
- - '#####'
  - RAM 磁盘设备
- - '###'
  - T
- - '###'
  - U
- - '####'
  - 用户客户端方法
- - '####'
  - 用户空间 USB 驱动程序
- - '####'
  - 用户空间 USB 驱动程序（续）
- - '#####'
  - '`IOUSBLib` 框架'
- - '###'
  - V
- - '###'
  - W
- - '####'
  - 工作循环
- - '###'
  - X, Y
- - '###'
  - Z
