name: Implementing IOS and MacOS Documents with the Files App
name_cn: Implementing IOS and MacOS Documents with the Files App 翻译为：使用文件应用的 iOS 与
  macOS 文档实现指南
slug: implementing-ios-and-macos-documents-with-the-files-app
toc:
- - '##'
  - 目录
- - '##'
  - 关于作者和技术审阅者
- - '###'
  - 关于作者
- - '###'
  - 关于技术审阅者
- - '#'
  - 第1章 使用文档
- - '##'
  - 描述文档
- - '##'
  - 追踪文档及其数据
- - '##'
  - 结构化文档
- - '###'
  - 注
- - '##'
  - 处理文档版本
- - '##'
  - 比较文档和文件
- - '###'
  - 注
- - '##'
  - 结构化文档和 App
- - '##'
  - 总结
- - '#'
  - 第2章 深入文档内部
- - '##'
  - 使用 JSON 编码
- - '##'
  - 介绍 JSON
- - '##'
  - JSON 与 Swift
- - '###'
  - 注意
- - '###'
  - 使用 Swift 结构体
- - '###'
  - 提示
- - '###'
  - 编码 JSON
- - '###'
  - 提示
- - '###'
  - 解码 JSON
- - '###'
  - 整合编码与解码
- - '###'
  - 注意
- - '##'
  - 总结
- - '#'
  - 第3章 将文档与文档格式匹配
- - '##'
  - 为 iCloud 做准备
- - '##'
  - 在你的应用中设置文档
- - '##'
  - 管理文档类型
- - '##'
  - 查看 `info.plist`
- - '##'
  - 总结
- - '#'
  - 第4章 保护数据安全
- - '##'
  - 安全与隐私概述
- - '##'
  - 案例研究：使用 Cocoa 定位服务
- - '##'
  - 总结
- - '#'
  - 第5章 在 macOS 上实现文档：NSDocument
- - '##'
  - iOS UIDocuments 与 macOS NSDocuments 的区别
- - '#'
  - 第6章 在 macOS 上创建基于文档的应用
- - '##'
  - 向 macOS 应用添加代码
- - '##'
  - AppDelegate
- - '##'
  - ViewController
- - '##'
  - Document
- - '##'
  - Storyboard
- - '##'
  - macOS 与 iOS 开发概述
- - '###'
  - 注
- - '##'
  - 总结
- - '#'
  - 第7章 在 iOS 上实现文档
- - '##'
  - 使用文件与 iOS 文件系统
- - '##'
  - 选择文档存储位置
- - '##'
  - 浏览文档
- - '##'
  - 查看最近文档
- - '###'
  - 提示
- - '##'
  - 查看某个 App 的文件和文件夹
- - '##'
  - 总结
- - '#'
  - 第8章 在 iOS 上实现文档：UIDocument 和 UIDocumentBrowserViewController
- - '##'
  - 创建一个基于文档的 App
- - '###'
  - 介绍 UIDocument
- - '##'
  - 使用 UIDocument
- - '##'
  - 使用 UIDocumentViewController
- - '###'
  - 打开文档
- - '###'
  - 关闭文档
- - '##'
  - 使用 UIDocumentBrowserViewController
- - '###'
  - 加载 UIDocumentBrowserViewController
- - '###'
  - 创建文档
- - '###'
  - 选取（打开）文档
- - '###'
  - 处理错误
- - '##'
  - 本章小结
- - '#'
  - 第9章 使用共享按钮共享文档
- - '##'
  - 使用共享按钮（作为用户）
- - '##'
  - 创建共享示例
- - '###'
  - 注意
- - '###'
  - 共享数据
- - '##'
  - 摘要
- - '###'
  - 注意
- - '##'
  - 审视数据结构
- - '###'
  - 提示
- - '##'
  - 理解用户默认值
- - '###'
  - 提示
- - '##'
  - 探索设置
- - '##'
  - 添加设置束
- - '###'
  - 提示
- - '###'
  - 从代码访问设置包
- - '###'
  - 添加设置界面
- - '##'
  - 总结
- - '#'
  - 第10章 使用文件封装和包
- - '##'
  - 使用包
- - '###'
  - 注意
- - '##'
  - 关于 Bundle
- - '##'
  - 使用文件封装器
- - '##'
  - 摘要
- - '#'
  - 第11章 使用文件归档
- - '###'
  - 注意
- - '##'
  - 使用 Swift 统一日志系统
- - '##'
  - 使用日志和断点归档数据
- - '###'
  - 选择要归档的项目
- - '###'
  - 创建要归档的对象
- - '###'
  - 执行归档
- - '####'
  - 使类符合 `NSCoding` 协议
- - '###'
  - 实现示例
- - '###'
  - 将归档迁移至文档
- - '##'
  - 总结
- - '###'
  - 索引
- - '####'
  - A
- - '####'
  - B
- - '####'
  - C
- - '####'
  - D
- - '####'
  - E
- - '####'
  - F
- - '####'
  - G, H
- - '####'
  - I
- - '####'
  - J, K
- - '####'
  - L
- - '####'
  - M
- - '####'
  - N, O
- - '####'
  - P, Q
- - '####'
  - R
- - '####'
  - S, T
- - '####'
  - U
- - '####'
  - V, W
- - '####'
  - X, Y, Z
