name: Pro iOS table views and collection views using Swift 2
name_cn: Swift 2 高级 iOS 表格视图与集合视图指南
slug: pro-ios-table-views-and-collection-views-using-swift-2
toc:
- - '##'
  - 目录
- - '#'
  - 引言
- - '##'
  - 本书涵盖内容
- - '##'
  - 本书风格
- - '##'
  - 关于第二版
- - '##'
  - 本书源代码
- - '##'
  - 更多资源
- - '###'
  - 联系作者
- - '##'
  - 致谢
- - '#'
  - 第 1 章：表视图快速入门
- - '##'
  - 什么是表格视图？
- - '##'
  - 表格视图的构成
- - '##'
  - 创建一个简单的表格视图应用
- - '##'
  - 创建应用骨架
- - '###'
  - 生成一些数据
- - '###'
  - 创建表格视图
- - '###'
  - 遵循表格视图协议
- - '####'
  - 连接数据源与委托
- - '####'
  - 显示数据
- - '#####'
  - '`numberOfSectionsInTableView( :)`'
- - '#####'
  - '`tableView:numberOfRowsInSection( :)`'
- - '#####'
  - 创建单元格
- - '######'
  - 创建原型单元格
- - '######'
  - 配置单元格
- - '######'
  - 运行应用
- - '###'
  - 添加交互性
- - '####'
  - '`tableView:didSelectRowAtIndexPath:`'
- - '##'
  - 理解应用对象的组合方式
- - '##'
  - 总结
- - '#'
  - 第 2 章：表格视图的组成
- - '##'
  - 理解表格视图
- - '##'
  - 使用 `UITableView` 系列
- - '###'
  - '`UITableView` 类层次结构'
- - '##'
  - 选择表格视图的类型
- - '###'
  - 普通表格
- - '###'
  - 索引表格
- - '###'
  - 分段表格
- - '###'
  - 分组表格
- - '##'
  - 设置 `TableView` 的尺寸
- - '##'
  - 控制 `UITableView` 的背景
- - '##'
  - '`UITableView` 继承自 `UIScrollView` 的要素'
- - '##'
  - 创建 `UITableView`
- - '###'
  - 在 Interface Builder 中创建 `UITableView`
- - '####'
  - 将 `UITableView` 放置到另一个视图中
- - '####'
  - 放置全屏 `UITableView`
- - '###'
  - 以编程方式创建 `UITableView`
- - '###'
  - 使用 `UITableViewController` 创建 `UITableView`
- - '####'
  - 连接 `UITableViewController` 的输出口
- - '##'
  - 本章小结
- - '#'
  - 第 3 章：集合视图快速入门
- - '##'
  - 什么是集合视图？
- - '##'
  - 集合视图的结构
- - '###'
  - 集合视图本身
- - '###'
  - 集合视图单元格
- - '###'
  - 支持对象
- - '####'
  - 集合视图的模型
- - '####'
  - 集合视图的数据源
- - '####'
  - 集合视图的委托
- - '####'
  - 集合视图的布局
- - '##'
  - 创建一个简单的集合视图应用
- - '##'
  - 创建应用骨架
- - '##'
  - 创建一些数据
- - '###'
  - 添加扑克牌图片
- - '###'
  - 构建模型
- - '###'
  - 在 Storyboard 中设置集合视图
- - '###'
  - 设置委托和数据源函数
- - '####'
  - '`numberOfSectionsInCollectionView:` 函数'
- - '####'
  - '`collectionView:numberOfItemsInSection:` 函数'
- - '####'
  - '`collectionView:cellForItemAtIndexPath:` 函数'
- - '###'
  - 配置集合视图的布局
- - '###'
  - 应用运行
- - '##'
  - 本章小结
- - '#'
  - 第 4 章：集合视图的构成
- - '##'
  - 什么是集合视图？
- - '##'
  - 集合视图的架构
- - '##'
  - 集合视图的剖析
- - '###'
  - 集合视图本身
- - '####'
  - 集合视图项
- - '###'
  - 集合视图布局
- - '###'
  - 详细解析支持对象
- - '####'
  - 集合视图的模型
- - '####'
  - 集合视图的数据源
- - '####'
  - 集合视图的委托
- - '##'
  - 集合视图的布局
- - '##'
  - 创建集合视图
- - '###'
  - 使用 Interface Builder 创建 `UICollectionView`
- - '####'
  - 将 `UICollectionView` 嵌入到现有视图中
- - '####'
  - 将 `UICollectionView` 添加为 Storyboard 场景
- - '###'
  - 向项目中添加 `UICollectionViewController` 子类
- - '###'
  - 在代码中创建 `UICollectionView`
- - '##'
  - 总结
- - '#'
  - 第 5 章：向视图提供数据
- - '##'
  - '`UITableView`、`UICollectionView` 与委托'
- - '###'
  - 理解委托
- - '###'
  - 委托示例：`collectionView(_:didSelectItemAtIndexPath:)`
- - '###'
  - 数据源示例：`tableView:cellForRowAtIndexPath`
- - '###'
  - 设置委托
- - '###'
  - 将对象与委托连接起来
- - '###'
  - 委托与内存管理
- - '##'
  - 定义协议
- - '###'
  - 在 Xcode 中访问协议定义
- - '##'
  - 使用 `UITableView` 的委托方法
- - '###'
  - 使用 `UITableViewDelegate` 方法
- - '###'
  - 使用 `UICollectionViewDelegate` 方法
- - '##'
  - 数据源
- - '###'
  - '`UITableView` 数据源'
- - '####'
  - 获取表格中的分区数量
- - '####'
  - 获取分区中的行数
- - '####'
  - 获取该分区该行所属的单元格
- - '####'
  - 表格如何获取关键信息
- - '###'
  - 与 Cell、Section 和 Row 相关的 `UITableViewDataSource` 方法
- - '###'
  - 与标题和索引相关的 `UITableViewDataSource` 方法
- - '###'
  - 与插入、删除和重排相关的 `UITableViewDataSource` 方法
- - '##'
  - '`UICollectionView` 的数据源'
- - '###'
  - 获取表格中的分区数
- - '###'
  - 获取分区中的项数
- - '###'
  - 获取属于该分区该行的 Cell
- - '###'
  - 获取属于该索引路径的补充视图
- - '###'
  - 集合视图如何获取关键信息
- - '###'
  - 我应该使用哪种配置方法？
- - '####'
  - 数据源的 `cellForItemAtIndexPath:` 函数
- - '####'
  - 委托的 `willDisplayCellAtIndexPath:` 函数
- - '###'
  - 与 Cell、Section 和 Item 相关的 `UICollectionViewDataSource` 方法
- - '##'
  - 关于 `dataSource` 方法需要记住的一点
- - '##'
  - 实现 `dataSource` 和 `delegate` 协议
- - '##'
  - 关于 `indexPath` 的一切
- - '##'
  - 模型-视图-控制器设计模式
- - '###'
  - 为何使用模型-视图-控制器模式？
- - '###'
  - MVC 与 iOS
- - '###'
  - MVC、TableView 和 CollectionView
- - '###'
  - 改进应用结构
- - '####'
  - 如何拆分数据源和委托
- - '#####'
  - 第 1 步：创建一个单独的类
- - '#####'
  - 第 2 步：将表格视图链接到新类
- - '##'
  - 总结
- - '#'
  - 第 6 章：表格单元格的构成
- - '##'
  - 理解`UITableViewCell`的结构
- - '###'
  - 单元格的基本结构
- - '###'
  - 单元格的背景视图
- - '###'
  - 内容和辅助视图
- - '##'
  - 设计原型单元格
- - '###'
  - 本章代码
- - '###'
  - 在 XIB 文件中创建原型单元格
- - '####'
  - 创建 XIB 文件
- - '####'
  - 将单元格对象添加到 XIB 文件中
- - '####'
  - 布局原型单元格
- - '####'
  - 告知表格视图有关 XIB 的信息
- - '####'
  - 创建并配置单元格
- - '###'
  - 在故事板中创建原型单元格
- - '###'
  - 创建原型单元格
- - '###'
  - 设置原型单元格
- - '###'
  - 告知表格视图关于原型单元格的信息
- - '###'
  - 创建和配置单元格
- - '##'
  - 在代码中创建原型单元格
- - '###'
  - 向表格视图注册单元格类
- - '###'
  - 创建和配置单元格
- - '##'
  - 使用标准单元格类型
- - '###'
  - 使用 `UITableViewCellStyleDefault`
- - '###'
  - 使用 `UITableViewCellStyleValue1`
- - '###'
  - 使用 `UITableViewCellStyleValue2`
- - '###'
  - 使用 `UITableViewCellStyleSubtitle`
- - '##'
  - 配置默认单元格的内容
- - '###'
  - '`textLabel`'
- - '###'
  - '`detailTextLabel`'
- - '###'
  - '`imageView`'
- - '###'
  - '`contentView`'
- - '###'
  - 默认单元格类型中的文本格式设置
- - '##'
  - 使用辅助视图
- - '###'
  - 使用 `UITableViewCellAccessoryDisclosureIndicator`
- - '###'
  - 使用 `UITableViewCellAccessoryDetailDisclosureIndicator`
- - '###'
  - 使用 `UITableViewCellAccessoryCheckmark`
- - '###'
  - 使用 `UITableViewCellAccessoryNone`
- - '###'
  - 设置辅助视图类型
- - '###'
  - 使用辅助视图显示单元格选中状态
- - '###'
  - 创建自定义辅助视图
- - '##'
  - 创建和复用单元格
- - '###'
  - 内存限制
- - '###'
  - 速度与流畅度
- - '###'
  - 即时创建与循环复用
- - '###'
  - 表格视图的“传送带”
- - '####'
  - “传送带”过程的代码实现方式
- - '###'
  - 使用 `cellIdentifier` 识别单元格
- - '###'
  - 单元格重用与缓存的副作用
- - '##'
  - 小结
- - '#'
  - 第 7 章：改善单元格的外观
- - '##'
  - 自定义单元格
- - '##'
  - 应使用哪个函数？
- - '##'
  - 向单元格的 `contentView` 添加子视图
- - '###'
  - 视图及其层次结构
- - '###'
  - 在单元格中创建元素
- - '####'
  - 更新自定义单元格中的内容
- - '####'
  - 为单元格中的控件添加标签
- - '####'
  - 转换控件类型
- - '##'
  - 在故事板中以原型方式可视化创建自定义单元格
- - '###'
  - 创建原型动态单元格
- - '####'
  - 自定义原型表格视图单元格
- - '####'
  - 原型单元格与自定义 `UITableViewCell` 子类
- - '####'
  - 设置原型单元格高度
- - '####'
  - 设置可变单元格高度
- - '####'
  - 自定义原型集合视图单元格
- - '###'
  - 设置原型集合视图单元格的大小
- - '###'
  - 使用 Interface Builder 可视化创建自定义单元格
- - '####'
  - 可视化创建单元格的阶段
- - '####'
  - 创建新的 XIB 文件
- - '#####'
  - 设置单元格的标识符
- - '###'
  - 创建单元格的内容
- - '####'
  - 为控件分配标签
- - '###'
  - 注册单元格
- - '##'
  - 控制单元格尺寸
- - '###'
  - 集合视图单元格尺寸
- - '###'
  - 表格视图单元格尺寸
- - '####'
  - 设置固定高度
- - '####'
  - 设置可变行高
- - '##'
  - 处理表格中单元格的尺寸调整
- - '##'
  - 本章小结
- - '#'
  - 第 8 章：使用子类创建自定义单元格
- - '##'
  - 为什么要创建自定义单元格子类？
- - '###'
  - 自定义单元格的创建流程
- - '####'
  - 需要注意的性能相关因素
- - '###'
  - 使用 XIB 的自定义单元格
- - '####'
  - 设计你的单元格
- - '####'
  - 创建自定义单元格的类
- - '#####'
  - 创建子类
- - '####'
  - 在 Interface Builder 中构建单元格
- - '####'
  - 创建 XIB 文件
- - '####'
  - 在 Interface Builder 中布局控件
- - '####'
  - 使单元格遵循自定义类
- - '####'
  - 连接自定义控件
- - '####'
  - 创建 `EvenCell`
- - '###'
  - 设置单元格高度
- - '###'
  - 创建自定义单元格实例
- - '###'
  - 处理自定义单元格的选中状态
- - '##'
  - 通过代码实现自定义单元格
- - '###'
  - 通过代码实现自定义单元格的流程
- - '###'
  - 创建自定义子类
- - '####'
  - 创建类
- - '####'
  - 向表格或集合视图注册自定义类
- - '####'
  - '`init` 函数'
- - '####'
  - 表格视图单元格的初始化函数
- - '####'
  - 集合视图的初始化函数
- - '###'
  - 重写 `layoutSubviews` 函数
- - '###'
  - 重写 `prepareForReuse` 函数
- - '##'
  - 使用 MVVM 改进应用架构
- - '###'
  - 模型-视图-视图模型方法
- - '###'
  - MVVM 的优缺点
- - '###'
  - 实现 MVVM 方法
- - '###'
  - 将项目转换为 MVVM 架构
- - '##'
  - 总结
- - '#'
  - 第 9 章：改善交互
- - '##'
  - 将自定义控件嵌入到单元格中
- - '###'
  - 简单方法 – 直接将按钮添加到单元格
- - '####'
  - 创建警告视图
- - '####'
  - 创建按钮
- - '####'
  - 将按钮添加到单元格
- - '####'
  - 响应单个控件
- - '###'
  - 更稳健的基于子类的方法
- - '####'
  - 声明协议
- - '####'
  - 实现自定义 `UITableViewCell`
- - '#####'
  - 向单元格的 ContentView 添加按钮
- - '#####'
  - 添加委托属性
- - '#####'
  - 添加处理按钮点击的代码
- - '#####'
  - 更新故事板
- - '###'
  - 更新视图控制器
- - '###'
  - 向单元格添加手势
- - '##'
  - 为表格视图添加下拉刷新
- - '###'
  - 使用`UITableViewController`实现下拉刷新
- - '####'
  - 添加刷新控件
- - '####'
  - 实现`pullToRefresh`功能
- - '###'
  - 向表格视图添加`UIRefreshControl`
- - '####'
  - 添加`UIRefreshControl`属性
- - '####'
  - 实例化刷新控件
- - '##'
  - 在表格和集合视图中搜索
- - '###'
  - 向表格添加搜索栏
- - '###'
  - 搜索的工作原理
- - '###'
  - 实现搜索功能
- - '###'
  - 实现 `UISearchBarDelegate` 函数
- - '###'
  - 更新 `UITableViewDataSource` 函数
- - '##'
  - 健康、流畅的表格
- - '###'
  - 后台、后台、再后台
- - '###'
  - 单元格是否被缓存？
- - '###'
  - 你的表格单元格高度是否不同？
- - '###'
  - 降低视图合成的成本
- - '####'
  - 在模拟器中检查透明度
- - '##'
  - 本章小结
- - '#'
  - 第 10 章：使用表格进行导航
- - '###'
  - 导航控制器界面模式
- - '##'
  - 介绍 `UINavigationController`
- - '##'
  - 导航控制器示例应用
- - '###'
  - 创建一个导航控制器应用
- - '####'
  - 创建 `Name` 类
- - '####'
  - 创建一些虚拟数据
- - '####'
  - 连接表格视图
- - '####'
  - 构建详情视图
- - '###'
  - 将数据传递到详细视图
- - '##'
  - 实现导航控制器
- - '##'
  - 导航控制器如何连接
- - '###'
  - 将导航控制器与详细视图连接起来
- - '##'
  - 使用 Segue 构建导航结构
- - '###'
  - 将表格视图嵌入导航控制器
- - '###'
  - 更新应用委托
- - '###'
  - 将详情视图与表格视图关联起来
- - '##'
  - 本章小结
- - '#'
  - 第 11 章：索引、分组与排序表格
- - '##'
  - 使用索引表格
- - '##'
  - 使用分区与分组表格
- - '##'
  - 创建简单索引表格
- - '###'
  - 设置基础表格
- - '###'
  - 创建源数据
- - '###'
  - 为表格填充数据
- - '###'
  - 返回表格中的分区数量
- - '###'
  - 创建分区标题
- - '###'
  - 构建索引
- - '###'
  - 将索引匹配到分区
- - '##'
  - 构建实用的分区表格
- - '##'
  - 创建带分区和索引的表格数据
- - '###'
  - 数组的数组
- - '###'
  - '`UILocalizedIndexedCollation`'
- - '####'
  - 本地化实践
- - '##'
  - 创建全能型表格
- - '###'
  - 从模板创建应用
- - '###'
  - 在 `plist` 文件中创建数据
- - '####'
  - 在代码中使用 `plist`
- - '###'
  - 整理用户界面
- - '###'
  - 扩展 `ViewController` 类
- - '####'
  - 配置分区
- - '##'
  - 创建表格和分区的表头与表尾视图
- - '##'
  - 表格表头和表尾
- - '###'
  - 整理表格底部
- - '###'
  - 通过代码滚动表格
- - '####'
  - '`scrollToRowAtIndexPath:atScrollPosition:animated:`'
- - '####'
  - '`scrollToNearestSelectedRowAtScrollPosition:animated:`'
- - '####'
  - '`selectRowAtIndexPath:animated:scrollPosition:`'
- - '###'
  - 查找表格中的当前滚动位置
- - '###'
  - 总结
- - '#'
  - 第 12 章：选择与编辑内容
- - '##'
  - 模型-视图-控制器模式回顾
- - '###'
  - 模型-视图-控制器模式为何重要
- - '##'
  - 表格视图中的单元格选择
- - '###'
  - 单元格选择的类型
- - '####'
  - 控制选择
- - '#####'
  - 全局选择
- - '###'
  - 理解表格选择功能的工作原理
- - '###'
  - 管理特定行的选择
- - '##'
  - 可视化选择
- - '###'
  - 自定义选择
- - '###'
  - 处理取消选中
- - '###'
  - 可视化持久选中
- - '###'
  - 使用选中标记表示多项选择
- - '###'
  - 处理选中操作
- - '###'
  - 可视化多项选择
- - '####'
  - 使用单元格的附件视图显示选中标记
- - '####'
  - 使用单元格的附件视图显示自定义视图
- - '###'
  - 以其他方式展示选择状态
- - '###'
  - 处理选择后的取消选择
- - '###'
  - 保持数据模型同步
- - '##'
  - 优化选择性能
- - '##'
  - 选择操作的注意事项
- - '##'
  - 对用户选择做出更详细的响应
- - '##'
  - 设计模式与 `UITableView`
- - '###'
  - 读取
- - '###'
  - 创建
- - '###'
  - 更新
- - '###'
  - 删除
- - '##'
  - 自定义行操作
- - '##'
  - 插入和删除行
- - '###'
  - 示例应用
- - '###'
  - 创建基于 `UINavigationController` 的表格
- - '###'
  - 创建示例表格的数据模型
- - '####'
  - 将表格置于编辑模式
- - '###'
  - 控制行是否可编辑
- - '###'
  - 控制每行的编辑样式
- - '###'
  - 处理行删除
- - '###'
  - 滑动式行删除
- - '##'
  - 处理行插入
- - '###'
  - 修改数据模型
- - '###'
  - 处理新行
- - '##'
  - 重新排列表格
- - '###'
  - 进入编辑模式
- - '###'
  - 检查行是否可移动
- - '###'
  - 移动行
- - '####'
  - 该行能否被移动到这里？
- - '####'
  - 更新数据模型
- - '###'
  - 启用批量插入和删除
- - '###'
  - 批量插入和删除分区
- - '##'
  - 在 `UICollectionView` 中选择
- - '###'
  - 集合视图中的剪切、复制与粘贴
- - '###'
  - 在集合视图中实现自定义菜单
- - '####'
  - 定义自定义协议
- - '####'
  - 实现自定义协议
- - '####'
  - 更新集合视图单元格子类
- - '####'
  - 创建自定义菜单项
- - '####'
  - 将单元格链接到其委托
- - '###'
  - 更新 `UICollectionViewDelegate` 函数
- - '###'
  - 响应菜单项移除单元格
- - '###'
  - 实现“添加单元格”选项
- - '####'
  - 扩展协议以添加插入单元格的函数
- - '####'
  - 在单元格子类中添加新函数
- - '####'
  - 在集合视图控制器中实现 `addItem` 函数
- - '####'
  - 添加新的菜单项
- - '##'
  - 重新排列 `UICollectionView`
- - '###'
  - 先决条件
- - '###'
  - 使用 `UICollectionViewController` 实现拖放
- - '###'
  - 添加 `UICollectionViewDelegate` 函数
- - '###'
  - 高亮移动过程
- - '###'
  - 使用拖放交互
- - '###'
  - 使用 `UIViewController` 实现拖放
- - '####'
  - 添加属性
- - '####'
  - 添加手势识别器
- - '####'
  - 添加 `UIGestureRecognizerDelegate` 函数
- - '####'
  - 收尾工作
- - '##'
  - 本章小结
- - '#'
  - 第 13 章：静态表格
- - '##'
  - 如何构建静态表格
- - '###'
  - 向表格视图添加静态单元格
- - '###'
  - 修复滚动问题
- - '###'
  - 向静态单元格添加控件
- - '####'
  - 调整单元格高度
- - '####'
  - 添加交互式控件
- - '###'
  - 在容器视图中使用静态表格
- - '####'
  - 先决条件
- - '###'
  - 添加 `UIViewController` 场景
- - '###'
  - 向 `UIViewController` 添加容器视图
- - '###'
  - 将静态表格视图嵌入到视图控制器中
- - '##'
  - 静态表格的其他用途
- - '##'
  - 总结
- - '#'
  - 第 14 章：WatchKit 中的表格
- - '##'
  - 关于 WatchKit
- - '##'
  - WatchKit 应用的结构
- - '##'
  - 什么是 WatchKit 表格？
- - '##'
  - 创建一个基本表格
- - '###'
  - 创建项目
- - '###'
  - 添加 WatchKit 目标
- - '###'
  - 构建表格界面
- - '###'
  - 创建表格
- - '####'
  - 创建行
- - '####'
  - 布局行
- - '###'
  - 创建行控制器类
- - '###'
  - 将类连接到行
- - '###'
  - 连接输出口
- - '###'
  - 在代码中创建行
- - '###'
  - 收尾工作
- - '###'
  - 添加交互性
- - '##'
  - 使用 WatchKit 表格进行导航
- - '###'
  - 添加新的界面控制器
- - '###'
  - 在 Storyboard 中添加新屏幕
- - '###'
  - 实现导航
- - '####'
  - 添加 Push Segue
- - '####'
  - 在代码中添加导航
- - '##'
  - 总结
- - '#'
  - 第 15 章：集合视图流布局
- - '##'
  - 关于流布局
- - '##'
  - 流布局的特性
- - '##'
  - '`UICollectionViewFlowLayout`'
- - '##'
  - 创建与配置流式布局
- - '###'
  - 实例化流式布局
- - '###'
  - 通过代码创建与配置流式布局
- - '####'
  - 创建流式布局
- - '####'
  - 设置集合视图的布局
- - '####'
  - 配置静态流式布局值
- - '####'
  - 动态配置流式布局值
- - '###'
  - 在 Interface Builder 中配置流式布局
- - '##'
  - 自定义流式布局
- - '###'
  - 通过属性自定义
- - '####'
  - 滚动方向
- - '####'
  - 项目尺寸
- - '#####'
  - '`EstimatedItemSize`'
- - '#####'
  - '`ItemSpacing`'
- - '#####'
  - '`LineSpacing`'
- - '#####'
  - '`SectionInsets`'
- - '#####'
  - '`SupplementaryViewSizes`'
- - '###'
  - 使用 `UICollectionViewDelegateFlowLayout` 自定义
- - '####'
  - 控制项目大小
- - '#####'
  - 参数
- - '#####'
  - 返回值
- - '#####'
  - 示例
- - '###'
  - 管理分区间距
- - '####'
  - '`collectionView(_:layout:insetForSectionAtIndex:)`'
- - '####'
  - '`collectionView(_:layout:minimumLineSpacingForSectionAtIndex:)`'
- - '####'
  - '`collectionView(_:layout:minimumInteritemSpacingForSectionAtIndex:)`'
- - '###'
  - 管理页眉和页脚大小
- - '##'
  - 子类化 `UICollectionViewFlowLayout`
- - '###'
  - 控制项目布局属性
- - '###'
  - 向项目添加额外的自定义布局属性
- - '###'
  - 添加新的补充视图
- - '###'
  - 控制插入和删除动画
- - '##'
  - 总结
- - '#'
  - 第 16 章：集合视图自定义布局
- - '##'
  - 关于自定义布局
- - '###'
  - 何时创建自定义集合视图布局
- - '###'
  - 创建自定义布局子类
- - '###'
  - 决定何时计算布局属性
- - '###'
  - 自定义布局的职责
- - '##'
  - 什么是布局属性？
- - '###'
  - 自定义布局属性
- - '###'
  - 需要实现的四个关键函数
- - '###'
  - '`prepareLayout`'
- - '###'
  - '`collectionViewContentSize`'
- - '###'
  - '`layoutAttributesForElementsInRect`'
- - '###'
  - '`layoutAttributesForItemAtIndexPath`'
- - '##'
  - 补充视图和装饰视图属性
- - '###'
  - 检查是否需要补充视图或装饰视图
- - '###'
  - 计算补充视图和装饰视图属性
- - '##'
  - 本章项目
- - '###'
  - SwiftClock：“静态”示例
- - '###'
  - 开始
- - '##'
  - 初始项目
- - '###'
  - 设置
- - '###'
  - 数据模型
- - '##'
  - 更新项目
- - '###'
  - 添加自定义布局类
- - '####'
  - 设置属性
- - '####'
  - 自定义布局的运行方式
- - '###'
  - 实现布局函数
- - '####'
  - '`prepareLayout` 函数'
- - '####'
  - '`collectionViewContentSize`'
- - '####'
  - '`layoutAttributesForElementsInRect:`'
- - '####'
  - '`layoutAttributesForElementAtIndexPath:`'
- - '####'
  - 其他 `UICollectionViewLayout` 函数
- - '###'
  - 实现自定义布局函数
- - '####'
  - '`calculateAllAttributes` 函数'
- - '####'
  - '`calculateAttributesForItemAtIndexPath:` 函数'
- - '###'
  - 计算小时标签的位置
- - '####'
  - 计算指针位置
- - '###'
  - 后续步骤
- - '###'
  - 显示数字和指针
- - '####'
  - 为小时标签创建 XIB 文件
- - '###'
  - 创建时钟指针的 `UICollectionView` 子类
- - '###'
  - 使用自定义布局
- - '###'
  - 让时钟“滴答”走动
- - '##'
  - 本章小结
- - '#'
  - 第 17 章：动画与交互式集合视图
- - '##'
  - 通过手势控制集合视图
- - '###'
  - 将手势与布局关联
- - '####'
  - 添加手势识别器
- - '####'
  - 处理手势
- - '##'
  - 集合视图与动画
- - '###'
  - 过程
- - '###'
  - 前提条件
- - '###'
  - 创建自定义布局
- - '####'
  - 内务函数
- - '####'
  - 计算属性
- - '###'
  - 计算中心点
- - '###'
  - 向集合视图提供属性
- - '###'
  - 批量提供属性
- - '####'
  - 提供单个项目属性
- - '####'
  - 提供初始布局属性
- - '###'
  - 提供最终布局属性
- - '###'
  - 连接集合视图
- - '####'
  - 添加新项目
- - '####'
  - 移除项目
- - '###'
  - 控制插入和移除动画
- - '##'
  - 总结
- - '#'
  - 索引
- - '##'
  - A
- - '##'
  - B
- - '##'
  - C
- - '##'
  - D
- - '##'
  - E
- - '##'
  - F
- - '##'
  - G
- - '##'
  - H
- - '##'
  - I
- - '##'
  - J
- - '##'
  - K
- - '##'
  - L
- - '##'
  - M
- - '##'
  - N
- - '##'
  - O
- - '##'
  - P, Q
- - '##'
  - R
- - '##'
  - S
- - '##'
  - T
- - '##'
  - U
- - '##'
  - V
- - '##'
  - W
- - '##'
  - X, Y, Z
- - '##'
  - 关于作者及技术审阅者
