name: Beginning IOS Game Center and GameKit
name_cn: iOS Game Center 和 GameKit 入门指南
slug: beginning-ios-game-center-and-gamekit
toc:
- - '#'
  - 前言：游戏英雄凯尔·里克特的传奇
- - '#'
  - 引言
- - '#'
  - 先决条件
- - '##'
  - 本书的组织结构
- - '##'
  - 所需的软件、材料和设备
- - '##'
  - 致谢
- - '##'
  - 关于作者
- - '#'
  - 1. GameKit 和 Game Center 入门
- - '##'
  - GameKit 概述
- - '###'
  - 网络
- - '###'
  - Game Center
- - '###'
  - 语音聊天
- - '##'
  - 示例游戏：UFOs
- - '###'
  - UFOs：理解游戏
- - '###'
  - UFOs：检查源代码
- - '####'
  - 设置加速计代理
- - '####'
  - 将玩家绘制到视图
- - '####'
  - 设置奶牛、光束和分数
- - '####'
  - 添加玩家移动
- - '####'
  - 监听触摸事件
- - '####'
  - 生成与移动奶牛
- - '####'
  - 对 `UIImage` 执行命中检测
- - '####'
  - 绑架奶牛
- - '###'
  - 在 App Store Connect 中配置 Game Center
- - '####'
  - App Store Connect 入门
- - '####'
  - 在 App Store Connect 中配置 Game Center
- - '####'
  - 本章小结
- - '#'
  - 2. Game Center：配置与入门
- - '##'
  - 创建 Game Center 管理器类
- - '##'
  - 通过 Game Center 进行身份验证
- - '###'
  - 修改 GameCenterManager 类
- - '###'
  - 从 UFOViewController 进行身份验证
- - '##'
  - 监听状态变化
- - '##'
  - 使用 `GKLocalPlayer`
- - '###'
  - Game Center 好友
- - '###'
  - 使用玩家
- - '##'
  - 总结
- - '#'
  - 3. 排行榜
- - '##'
  - 为什么要使用排行榜？
- - '##'
  - Game Center 排行榜概览
- - '###'
  - 使用 Apple 排行榜 GUI 与自定义 GUI 的优缺点
- - '##'
  - 在 App Store Connect 中配置排行榜
- - '##'
  - 周期性排行榜
- - '##'
  - 提交分数
- - '###'
  - 向 UFO 游戏添加分数提交功能
- - '##'
  - 处理提交分数时的失败情况
- - '##'
  - 展示排行榜
- - '###'
  - 自定义排行榜
- - '##'
  - 修改 GameCenterManager
- - '##'
  - 在自定义排行榜上过滤结果
- - '###'
  - 显示自定义排行榜
- - '##'
  - 本地玩家分数
- - '##'
  - 更佳方法
- - '##'
  - Game Center 组
- - '###'
  - 摘要
- - '#'
  - 4. 成就
- - '##'
  - 为什么要使用成就？
- - '##'
  - Game Center 中的成就概述
- - '###'
  - 使用 Apple 成就 GUI 与自定义 GUI 的对比优势
- - '##'
  - 在 App Store Connect 中配置成就
- - '###'
  - 呈现成就
- - '###'
  - 修改成就进度
- - '##'
  - 重置成就
- - '##'
  - 添加成就钩子
- - '###'
  - 成就完成反馈
- - '###'
  - 自定义成就界面
- - '###'
  - 从提交失败中恢复
- - '##'
  - 总结
- - '#'
  - 5. 匹配与邀请
- - '##'
  - 为何要在你的应用中添加匹配与邀请功能？
- - '###'
  - 常见的匹配场景
- - '##'
  - 创建新的比赛请求
- - '##'
  - 展示比赛图形界面
- - '##'
  - 处理收到的邀请
- - '##'
  - 自动匹配
- - '##'
  - 程序化匹配
- - '##'
  - 向比赛中添加玩家
- - '##'
  - 重新邀请
- - '##'
  - 玩家分组
- - '##'
  - 玩家属性
- - '###'
  - 了解玩家属性的限制
- - '###'
  - 使用玩家属性
- - '##'
  - 玩家活动
- - '##'
  - 使用自有服务器（托管比赛）
- - '###'
  - 总结
- - '#'
  - 6. 网络设计概述
- - '##'
  - 三种网络类型
- - '###'
  - 对等网络
- - '###'
  - 客户端-主机网络
- - '###'
  - 环形网络
- - '##'
  - 较少常见的网络
- - '##'
  - 可靠数据与不可靠数据
- - '##'
  - 仅发送必要数据
- - '##'
  - 预测与外推
- - '##'
  - 消息格式化
- - '##'
  - 预防作弊与超时断线
- - '###'
  - 当一切方法都失效时该怎么办
- - '##'
  - 本章小结
- - '#'
  - 7. 数据交换
- - '##'
  - 修改单人游戏
- - '##'
  - 为多人游戏设置引擎
- - '###'
  - 选择主机
- - '###'
  - 发送数据
- - '###'
  - 接收数据
- - '##'
  - 整合所有内容
- - '###'
  - 选择主机
- - '###'
  - 显示敌方 UFO
- - '###'
  - 生成奶牛
- - '###'
  - 共享分数
- - '###'
  - 添加网络劫持代码
- - '##'
  - 断线处理
- - '##'
  - 本章小结
- - '#'
  - 8. 使用 Game Center 实现回合制游戏
- - '##'
  - 新的示例项目
- - '##'
  - GKTurnBasedMatchmakerViewController
- - '###'
  - 建立游戏状态
- - '###'
  - 开始新游戏
- - '###'
  - 进行第一步操作
- - '###'
  - GKLocalPlayerListener 扩展
- - '###'
  - 继续进行中的游戏
- - '###'
  - 退出与投降
- - '###'
  - 编程式匹配
- - '##'
  - '`GKTurnBasedEventHandler`'
- - '###'
  - 总结
- - '#'
  - 9. 语音聊天
- - '##'
  - Game Center 的语音聊天
- - '###'
  - 创建音频会话
- - '###'
  - 创建新的语音频道
- - '###'
  - 启动和停止语音聊天
- - '###'
  - 聊天音量和静音
- - '###'
  - 监控玩家状态
- - '##'
  - 整合
- - '##'
  - 连接用户界面
- - '##'
  - 总结
- - '#'
  - 10. 使用 StoreKit 实现应用内购买
- - '##'
  - 在 App Store Connect 中设置你的应用
- - '###'
  - 图 10-5
- - '###'
  - 图 10-6
- - '###'
  - 图 10-7
- - '##'
  - 向应用添加产品
- - '##'
  - App ID 与应用内购买
- - '##'
  - 设置
- - '##'
  - 检索产品列表
- - '###'
  - 向用户展示你的产品
- - '##'
  - 购买产品
- - '###'
  - 购买代码
- - '###'
  - 购买多个商品
- - '###'
  - 处理交易
- - '###'
  - 恢复之前完成的交易
- - '##'
  - 测试帐户与测试购买
- - '###'
  - 使用测试帐户登录
- - '##'
  - 提交购买 GUI 截图
- - '##'
  - 开发者审批
- - '###'
  - 在 `UFOs` 中整合所有元素
- - '###'
  - 本章小结
- - '#'
  - 11. 游戏控制器
- - '##'
  - 实体游戏控制器的类型
- - '##'
  - 连接游戏控制器
- - '###'
  - 通过轮询读取数据
- - '###'
  - 数据回调
- - '###'
  - 暂停
- - '###'
  - 玩家指示灯
- - '##'
  - 快照
- - '##'
  - 虚拟控制器
- - '##'
  - 总结
