name: Android Continuous Integration
name_cn: Android 持续集成指南
slug: android-continuous-integration
toc:
- - '##'
  - 致谢
- - '#'
  - 目录
- - '#'
  - 内容概览
- - '##'
  - 关于作者与技术审校者
- - '#'
  - 1. 引言
- - '##'
  - 1.1 架构
- - '##'
  - 1.2 先决条件
- - '###'
  - 1.2.1 Windows 与 Mac 的选择
- - '###'
  - 1.2.2 Mac 环境
- - '###'
  - 1.2.3 移动设备
- - '###'
  - 1.2.4 网络
- - '###'
  - 1.2.5 平台
- - '##'
  - 1.3 编程语言
- - '##'
  - 1.4 安装流程
- - '###'
  - 1.4.1 安装 Jenkins
- - '###'
  - 1.4.2 安装 Nexus
- - '###'
  - 1.4.3 安装 SonarQube
- - '###'
  - 1.4.4 安装 CI 工具栈
- - '##'
  - 1.5 构建 Android 应用
- - '##'
  - 1.6 部署/安装 Android 应用
- - '##'
  - 1.7 测试（自动化测试）Android 应用
- - '##'
  - 1.8 移动技术
- - '###'
  - 1.8.1 消费者想要什么？
- - '###'
  - 1.8.2 生态系统
- - '###'
  - 1.8.3 硬件
- - '###'
  - 1.8.4 平台/操作系统
- - '##'
  - 1.9 移动应用的类型
- - '#'
  - 2. 移动测试自动化
- - '##'
  - 2.1 WebDriver 协议
- - '##'
  - 2.2 我们为何要讨论这些协议？
- - '##'
  - 2.3 它是如何工作的？
- - '##'
  - 2.4 它是如何扩展的？
- - '##'
  - 2.5 这与移动自动化有何关联？
- - '##'
  - 2.6 测试自动化库
- - '##'
  - 2.7 为什么要自动化？
- - '##'
  - 2.8 移动测试策略
- - '###'
  - 2.8.1 手动测试与自动化
- - '###'
  - 2.8.2 测试速度
- - '###'
  - 2.8.3 可扩展性
- - '###'
  - 2.8.4 成本
- - '####'
  - 测试金字塔
- - '##'
  - 2.9 移动测试环境
- - '###'
  - 2.9.1 真实设备 vs. 模拟器
- - '###'
  - 2.9.2 在本地 Android 真实设备上进行初始手动测试
- - '###'
  - 2.9.3 在本地 Android 模拟器上进行初始手动测试
- - '###'
  - 2.9.4 在云端进行进一步手动测试
- - '#'
  - 3. 使用 Jenkins 和 Android 的 CI 模式
- - '##'
  - 3.1 什么是持续集成？
- - '##'
  - 3.2 反馈回路
- - '###'
  - 3.2.1 反馈循环 1：构建
- - '####'
  - Jenkins Job1 配置
- - '#####'
  - 取消注释 set -xv 以进行调试
- - '####'
  - 反馈（执行结果）
- - '###'
  - 3.2.2 反馈循环 2：代码质量分析
- - '####'
  - Jenkins 任务 2：Sonar
- - '###'
  - 3.2.3 反馈循环 3：测试
- - '####'
  - Jenkins 任务 3：验收测试
- - '#####'
  - 取消注释 set -xv 以进行调试
- - '####'
  - 反馈（执行结果）
- - '#'
  - 4. Android 系统设置
- - '##'
  - 4.1 安装 Java
- - '###'
  - 4.1.1 JRE 与 JDK 与 SE
- - '###'
  - 4.1.2 在 Mac 上安装 JDK
- - '##'
  - 4.2 安装 Android SDK
- - '###'
  - 4.2.1 独立 SDK
- - '###'
  - 4.2.2 快速检查
- - '##'
  - 4.3 安装 Android Studio
- - '###'
  - 4.3.1 Android Studio 基础
- - '###'
  - 4.3.2 将系统 SDK 与 Android Studio 关联
- - '##'
  - 4.4 安装 Gradle
- - '###'
  - 4.4.1 下载与安装
- - '###'
  - 4.4.2 设置 Gradle Shell 变量
- - '###'
  - 4.4.3 在 Android Studio 中使用 Gradle
- - '###'
  - 4.4.4 Gradle 快速命令
- - '##'
  - 4.5 Gradle 任务
- - '##'
  - 4.6 构建应用
- - '##'
  - 4.7 需要了解的工具
- - '###'
  - 4.7.1 ADB
- - '###'
  - 4.7.2 录制视频
- - '###'
  - 4.7.3 uiautomatorviewer
- - '###'
  - 4.7.4 AVD 管理器
- - '###'
  - 4.7.5 SDK 管理器
- - '##'
  - 4.8 Android 设备监视器
- - '#'
  - 5. 构建 Android 应用
- - '##'
  - 5.1 Android 构建流程
- - '###'
  - 5.1.1 概览
- - '###'
  - 5.1.2 构建流程的另一个视角
- - '###'
  - 5.1.3 构建流程的输出
- - '##'
  - 5.2 从命令行构建
- - '###'
  - 5.2.1 Gradle 任务
- - '###'
  - 5.2.2 `Gradle Clean AssembleDebug` 任务
- - '###'
  - 5.2.3 调试模式下的 `.apk` 文件
- - '###'
  - 5.2.4 发布模式下的 `.apk` 文件
- - '##'
  - 5.3 从 Android Studio 构建
- - '###'
  - 5.3.1 导入项目
- - '###'
  - 5.3.2 Android Studio 视图
- - '###'
  - 5.3.3 项目视图
- - '##'
  - 5.4 构建示例应用
- - '###'
  - 5.4.1 源代码
- - '###'
  - 5.4.2 环境
- - '###'
  - 5.4.3 克隆与构建
- - '###'
  - 5.4.4 示例应用：`app-debug.apk`
- - '#'
  - 6. 连接 Android 目标设备
- - '##'
  - 6.1 使用模拟器与真实设备进行测试
- - '##'
  - 6.2 使用 Android 模拟器
- - '###'
  - 6.2.1 硬件加速
- - '###'
  - 6.2.2 创建新的 AVD
- - '###'
  - 6.2.3 示例 AVD
- - '###'
  - 6.2.4 学习曲线
- - '##'
  - 6.3 连接 Android 设备
- - '###'
  - 6.3.1 ADB 是你的朋友
- - '####'
  - 启用 USB 调试
- - '####'
  - 连接设备
- - '####'
  - 故障排除技巧
- - '####'
  - 通过 WiFi 进行调试
- - '##'
  - 6.4 ADB 命令
- - '##'
  - 6.5 通过 WiFi 连接
- - '##'
  - 6.6 远程调试 Chrome
- - '#'
  - 7. 部署或安装 Android 应用
- - '##'
  - 7.1 连接并识别目标
- - '###'
  - 7.1.1 向目标发送直接命令
- - '###'
  - 7.1.2 在模拟器上安装
- - '###'
  - 7.1.3 在真机上安装
- - '##'
  - 7.2 命令行演示
- - '##'
  - 7.3 Android Studio 演示
- - '#'
  - 8. 使用 Appium
- - '##'
  - 8.1 为什么选择 Appium？
- - '##'
  - 8.2 Appium 概念
- - '###'
  - 8.2.1 客户端/服务器架构
- - '###'
  - 8.2.2 会话
- - '###'
  - 8.2.3 所需功能
- - '###'
  - 8.2.4 Appium 服务器
- - '###'
  - 8.2.5 Appium 客户端
- - '###'
  - 8.2.6 Appium.app 和 Appium.exe
- - '###'
  - 8.2.7 Appium 设计原理
- - '###'
  - 8.2.8 Appium Android
- - '###'
  - 8.2.9 Appium
- - '##'
  - 8.3 安装 Appium 服务器
- - '###'
  - 8.3.1 下载并安装 Appium 服务器
- - '###'
  - 8.3.2 GUI 启动 Android 模式
- - '##'
  - 8.4 Appium 服务器配置
- - '###'
  - 8.4.1 Appium Doctor
- - '###'
  - 8.4.2 开发者模式
- - '###'
  - 8.4.3 服务器命令行
- - '###'
  - 8.4.4 Appium Android 设置
- - '###'
  - 8.4.5 Appium 服务器设置
- - '##'
  - 8.5 检查应用程序
- - '##'
  - 8.6 Appium Ruby 控制台
- - '###'
  - 8.6.1 方法 1
- - '####'
  - 返回包的名称、versionCode 等
- - '####'
  - 返回所有可启动的活动。通常应用的主入口点会被命名为 *.MainActivity（但这可能根据开发人员的决定而改变）
- - '###'
  - 8.6.2 方法 2
- - '##'
  - 8.7 使用 ARC 进行检查
- - '###'
  - 8.7.1 先决条件
- - '###'
  - 8.7.2 Appium.txt 文件
- - '####'
  - appium.txt
- - '###'
  - 8.7.3 使用 uiautomatorviewer
- - '##'
  - 8.8 测试策略与执行
- - '###'
  - 8.8.1 使用 Cucumber 进行持续测试自动化
- - '###'
  - 8.8.2 高层思维导图
- - '###'
  - 8.8.3 测试框架
- - '####'
  - Git 仓库与文件夹结构
- - '####'
  - 编写测试
- - '#####'
  - Cucumber 场景 (`ci_android.feature`)
- - '#####'
  - '`hooks.rb`'
- - '#####'
  - '`env.rb`'
- - '######'
  - 创建一个自定义 World 类，这样我们就不会用 Appium 的方法来污染 `Object`。
- - '#####'
  - 设备实验室
- - '######'
  - '`devices.yaml`'
- - '######'
  - '`emulators.yaml`'
- - '#####'
  - Capabilities.rb
- - '#####'
  - ScreenHelper.rb (未使用)
- - '#####'
  - Step Definitions
- - '######'
  - '`# valid = !version.match(/\d/).nil?`'
- - '######'
  - '`# expect(valid).to eq(true)`'
- - '####'
  - 关键概念解释
- - '###'
  - 8.8.4 在本地实验室执行测试
- - '####'
  - 启动 Appium 服务器
- - '####'
  - 执行测试
- - '###'
  - 8.8.5 在 Sauce Labs 上执行测试
- - '####'
  - 什么是 Sauce Labs？
- - '####'
  - 针对 Sauce Labs 运行测试
- - '#####'
  - 在真实设备上运行
- - '######'
  - 特性文件 (ci_android.feature)
- - '######'
  - Hooks.rb 文件
- - '######'
  - 执行文件
- - '######'
  - 反馈
- - '#####'
  - 在模拟器上运行
- - '###'
  - 8.8.6 多设备并行自动化
- - '####'
  - 在不同端口上启动 Appium 服务器
- - '####'
  - 客户端
- - '####'
  - 索引
