name: Beginning iPhone Development Exploring the iOS SDK
name_cn: iPhone 开发入门指南：探索 iOS SDK
slug: beginning-iphone-development-exploring-the-ios-sdk
toc:
- - '#'
  - 初探 iPhone 开发
- - '##'
  - 内容一览
- - '##'
  - 目录
- - '###'
  - 本书内容
- - '###'
  - 你需要什么
- - '###'
  - 开发者选项
- - '###'
  - 你需要了解什么
- - '###'
  - iOS 开发有何不同？
- - '####'
  - 只有一个活跃应用程序
- - '####'
  - 只有一个窗口
- - '####'
  - 访问受限
- - '####'
  - 响应时间有限
- - '####'
  - 屏幕尺寸有限
- - '####'
  - 系统资源有限
- - '####'
  - 没有垃圾回收，但是……
- - '####'
  - 一些新特性
- - '####'
  - 不同的方法
- - '###'
  - 本书内容
- - '###'
  - 本次更新有哪些新内容？
- - '#'
  - 第 1 章 欢迎来到丛林
- - '##'
  - 本书内容
- - '##'
  - 你需要准备什么
- - '##'
  - 开发者选项
- - '##'
  - 你需要掌握的知识
- - '###'
  - 学习 Objective-C 的资源
- - '###'
  - 为 iOS 编码有何不同？
- - '####'
  - 只有一个活动应用程序
- - '####'
  - 只有一个窗口
- - '####'
  - 有限的访问权限
- - '####'
  - 有限的响应时间
- - '####'
  - 有限的屏幕尺寸
- - '###'
  - iOS 开发笔记
- - '####'
  - 有限的系统资源
- - '####'
  - 没有垃圾回收，但是……
- - '####'
  - 一些新特性
- - '####'
  - 不同的交互方式
- - '###'
  - 本书内容
- - '###'
  - 本次更新有哪些新内容？
- - '###'
  - 你准备好了吗？
- - '#'
  - 第 2 章 安抚提基神
- - '##'
  - 在 Xcode 中设置你的项目
- - '##'
  - Xcode 项目窗口
- - '###'
  - 工具栏
- - '###'
  - 导航器
- - '##'
  - Xcode 界面与功能详解
- - '###'
  - Xcode 键盘快捷键
- - '###'
  - 实用工具区
- - '###'
  - 界面生成器
- - '###'
  - 新编译器和调试器
- - '###'
  - 深入了解我们的项目
- - '##'
  - 项目结构与界面构建器
- - '###'
  - 项目导航器文件夹
- - '###'
  - 介绍 Xcode 的界面构建器
- - '###'
  - 文件格式
- - '###'
  - Storyboard
- - '###'
  - The Library
- - '##'
  - 排版后的内容
- - '###'
  - 向视图中添加标签
- - '###'
  - 更改属性
- - '###'
  - 给 iPhone 应用抛光：最后的润色
- - '###'
  - 启动屏幕
- - '###'
  - 尾声
- - '##'
  - 我们的 Hello World 应用
- - '###'
  - 模型-视图-控制器范式
- - '###'
  - 创建我们的项目
- - '###'
  - 查看视图控制器
- - '###'
  - 理解输出口和动作
- - '####'
  - 出口
- - '#####'
  - 出口的变更
- - '####'
  - 动作
- - '###'
  - 清理视图控制器
- - '###'
  - 设计用户界面
- - '####'
  - 添加按钮和 Action 方法
- - '####'
  - 添加标签和插座变量
- - '####'
  - 编写操作方法
- - '####'
  - 试一试
- - '####'
  - 预览布局
- - '####'
  - 添加一些样式
- - '####'
  - 查看应用程序委托
- - '####'
  - 轻松入门
- - '#'
  - 第 4 章 更多用户界面乐趣
- - '##'
  - 布满控件的屏幕
- - '##'
  - 主动、静态和被动控件
- - '###'
  - 实现图像视图和文本字段
- - '####'
  - 添加图像视图
- - '####'
  - 调整图像视图大小
- - '####'
  - 设置视图属性
- - '#####'
  - Mode 属性
- - '#####'
  - Tag
- - '#####'
  - Interaction 复选框
- - '#####'
  - Alpha 值
- - '#####'
  - Background
- - '#####'
  - Tint
- - '###'
  - 下一个控件可让您为所选视图指定色调颜色
- - '###'
  - 绘制复选框
- - '###'
  - 拉伸
- - '###'
  - 添加文本字段
- - '###'
  - 文本字段检查器设置
- - '####'
  - 为第二个文本字段设置属性
- - '####'
  - 添加约束
- - '####'
  - 创建并连接输出口
- - '####'
  - 关闭键盘
- - '#####'
  - 点击 Done 时关闭键盘
- - '#####'
  - 触摸背景来关闭键盘
- - '###'
  - 添加滑块和标签
- - '###'
  - 添加更多约束
- - '###'
  - 创建并连接动作和输出口
- - '###'
  - 实现动作方法
- - '##'
  - 实现开关、按钮和分段控件
- - '###'
  - 添加两个带标签的开关
- - '###'
  - 连接与创建输出口和操作
- - '###'
  - 实现开关操作
- - '###'
  - 添加按钮
- - '###'
  - 美化按钮
- - '####'
  - 可拉伸图像
- - '####'
  - 控件状态
- - '####'
  - 连接并创建按钮 Outlet 和 Action
- - '###'
  - 实现分段控件动作
- - '##'
  - 实现操作表和警告框
- - '###'
  - 显示操作表
- - '###'
  - 显示警告
- - '##'
  - 跨越终点线
- - '#'
  - 第 5 章 旋转与自适应布局
- - '##'
  - 旋转的机制
- - '###'
  - 点、像素和 Retina 显示屏
- - '###'
  - 处理旋转
- - '####'
  - 选择你的视图方向
- - '#####'
  - 应用级别支持的方向
- - '####'
  - 逐控制器旋转支持
- - '###'
  - 代码补全实战
- - '###'
  - 使用约束设计界面
- - '###'
  - 全宽标签
- - '##'
  - 创建自适应布局
- - '###'
  - 重构应用程序
- - '###'
  - 尺寸类
- - '###'
  - 尺寸类与故事板
- - '###'
  - 创建 iPhone 横屏布局
- - '###'
  - 添加 iPad 布局
- - '###'
  - 旋转出局
- - '#'
  - 第 6 章 多视图应用程序
- - '##'
  - 多视图应用程序的常见类型
- - '##'
  - 多视图应用程序的架构
- - '###'
  - 根控制器
- - '###'
  - 内容视图的剖析
- - '##'
  - 构建 View Switcher
- - '###'
  - 重命名视图控制器
- - '###'
  - 添加内容视图控制器
- - '###'
  - 修改 SwitchingViewController.m
- - '###'
  - 使用工具栏构建视图
- - '####'
  - 将工具栏按钮连接到视图控制器
- - '###'
  - 编写根视图控制器
- - '###'
  - 实现内容视图
- - '###'
  - 动画过渡
- - '#'
  - 第 7 章 标签栏与选择器
- - '##'
  - 委托与数据源
- - '##'
  - 创建选择器应用程序
- - '###'
  - 创建视图控制器
- - '###'
  - 创建标签栏控制器
- - '###'
  - 初始测试运行
- - '###'
  - 实现日期选择器
- - '##'
  - 实现单组件选择器
- - '###'
  - 构建视图
- - '###'
  - 将控制器实现为数据源和代理
- - '####'
  - '`#pragma mark 选择器委托方法`'
- - '####'
  - '`#PRAGMA 是什么？`'
- - '##'
  - 实现多组件选择器
- - '###'
  - 声明 Outlets 和 Actions
- - '###'
  - 构建视图
- - '###'
  - 实现控制器
- - '##'
  - 实现依赖组件
- - '##'
  - 使用自定义选择器创建简单游戏
- - '###'
  - 编写控制器头文件
- - '###'
  - 构建视图
- - '###'
  - iOS 设备支持的字体
- - '###'
  - 实现控制器
- - '###'
  - spin 方法
- - '###'
  - viewDidLoad 方法
- - '###'
  - 最终细节
- - '#'
  - 第 8 章 表视图入门
- - '##'
  - 表视图基础
- - '###'
  - 表视图和表视图单元格
- - '###'
  - 分组表与平铺表
- - '##'
  - 实现一个简单的表
- - '###'
  - 设计视图
- - '###'
  - 编写控制器
- - '###'
  - 添加图片
- - '###'
  - 使用表格视图单元格样式
- - '####'
  - 设置缩进级别
- - '####'
  - 处理行选择
- - '####'
  - 更改字体大小和行高
- - '##'
  - 自定义表格视图单元格
- - '###'
  - 向表格视图单元格添加子视图
- - '###'
  - 创建 `UITableViewCell` 子类
- - '###'
  - 添加新单元
- - '###'
  - 实现控制器的代码
- - '##'
  - 从 Nib 加载 UITableViewCell
- - '###'
  - 在 Interface Builder 中设计表格视图单元格
- - '###'
  - 使用新的表格视图单元格
- - '##'
  - 分组和索引分区
- - '###'
  - 构建视图
- - '###'
  - 导入数据
- - '###'
  - 实现控制器
- - '##'
  - 添加索引
- - '##'
  - 实现搜索栏
- - '##'
  - 有多少个表格？：视图调试
- - '##'
  - 综合运用
- - '#'
  - 第 9 章 导航控制器与表格视图
- - '##'
  - 导航控制器基础
- - '###'
  - 堆栈之美
- - '##'
  - 控制器堆栈
- - '##'
  - Fonts：一个简单的字体浏览器
- - '##'
  - 认识子控制器
- - '###'
  - 字体列表控制器
- - '###'
  - 字体大小视图控制器
- - '##'
  - 字体信息视图控制器
- - '##'
  - 字体应用框架
- - '###'
  - 设置导航控制器
- - '###'
  - 跟踪收藏
- - '##'
  - 创建根视图控制器
- - '##'
  - 初始故事板设置
- - '##'
  - 第一个子控制器：字体列表视图
- - '###'
  - 为字体列表设计故事板
- - '####'
  - 让根视图控制器为转场做准备
- - '####'
  - 创建字体大小视图控制器
- - '####'
  - 为字体大小视图控制器绘制 Storyboard
- - '####'
  - 让字体列表视图控制器为转场做准备
- - '##'
  - 创建字体信息视图控制器
- - '###'
  - 为字体信息视图控制器构建 Storyboard
- - '####'
  - 设置约束
- - '###'
  - 为多个转场适配字体列表视图控制器
- - '##'
  - 我最喜爱的字体
- - '##'
  - 表格视图的便利功能
- - '###'
  - 实现滑动删除
- - '###'
  - 实现拖拽重排
- - '##'
  - 终章
- - '#'
  - 第 10 章 集合视图
- - '##'
  - 创建 DialogViewer 项目
- - '###'
  - 修正视图控制器类
- - '###'
  - 定义自定义单元格
- - '##'
  - 配置视图控制器
- - '###'
  - 提供内容单元格
- - '###'
  - 让布局流动起来
- - '###'
  - 提供头部视图
- - '#'
  - 第 11 章 使用分割视图和弹出框
- - '##'
  - 使用 UISplitViewController 构建主从应用
- - '###'
  - 故事板定义了结构
- - '###'
  - 代码定义了功能
- - '####'
  - 应用委托
- - '####'
  - 主视图控制器
- - '####'
  - 详情视图控制器
- - '####'
  - 主-从模板应用程序如何工作
- - '##'
  - 这里介绍的是总统
- - '##'
  - 创建你自己的弹出视图
- - '##'
  - iPhone 上的分割视图
- - '##'
  - iPhone 6 Plus 上的分割视图
- - '##'
  - 在所有 iPhone 上获得 iPhone 6 Plus 的行为
- - '##'
  - 自定义分割视图
- - '##'
  - 准备收尾与拆分
- - '#'
  - 第 12 章 应用程序设置与用户默认值
- - '##'
  - 了解你的设置捆绑包
- - '##'
  - 舰桥控制应用程序
- - '###'
  - 创建项目
- - '###'
  - 使用设置捆绑包
- - '###'
  - 向项目添加设置捆绑包
- - '####'
  - 设置属性列表
- - '####'
  - 添加文本字段设置
- - '####'
  - 添加应用图标
- - '####'
  - 添加安全文本字段设置
- - '####'
  - 添加多值字段
- - '####'
  - 添加开关设置
- - '####'
  - 添加滑块设置
- - '####'
  - 向设置束添加图标
- - '####'
  - 添加子设置视图
- - '###'
  - 在应用程序中读取设置
- - '####'
  - 获取用户设置
- - '####'
  - 创建主视图
- - '###'
  - 注册默认值
- - '###'
  - 保持真实
- - '##'
  - 传送我吧，斯科蒂
- - '#'
  - 第 13 章 基本数据持久化
- - '##'
  - 应用的沙盒
- - '###'
  - 应用数据存储
- - '####'
  - 文档、资料库和临时目录
- - '####'
  - 获取 Documents 和 Library 目录路径
- - '####'
  - 获取 tmp 目录
- - '##'
  - 文件保存策略
- - '###'
  - 单文件持久化
- - '###'
  - 多文件持久化
- - '##'
  - 使用属性列表
- - '###'
  - 属性列表序列化
- - '##'
  - 持久化应用程序的第一个版本
- - '###'
  - 创建持久化项目
- - '###'
  - 设计持久化应用程序的视图
- - '###'
  - 编辑持久化类
- - '##'
  - 归档模型对象
- - '###'
  - 遵循 NSCoding
- - '###'
  - 实现 NSCopying
- - '###'
  - 归档和解档数据对象
- - '##'
  - 归档应用程序
- - '###'
  - 实现`FourLines`类
- - '###'
  - 实现`ViewController`类
- - '##'
  - 使用 iOS 的内嵌 SQLite3
- - '###'
  - 创建或打开数据库
- - '###'
  - 使用绑定变量
- - '##'
  - SQLite3 应用程序
- - '###'
  - 链接到 SQLite3 库
- - '###'
  - 修改持久化视图控制器
- - '##'
  - 使用 Core Data
- - '###'
  - 实体与托管对象
- - '###'
  - 键值编码
- - '###'
  - 将所有内容置于上下文中
- - '###'
  - 创建新的托管对象
- - '###'
  - 检索托管对象
- - '###'
  - Core Data 应用程序
- - '####'
  - 设计数据模型
- - '####'
  - 创建持久化视图
- - '###'
  - 持久化的奖赏
- - '#'
  - 第 14 章 文档与 iCloud
- - '##'
  - 使用 UIDocument 管理文档存储
- - '##'
  - 构建 TinyPix
- - '###'
  - 创建 TinyPixDocument
- - '###'
  - 初始故事板设计
- - '###'
  - 创建 `TinyPixView`
- - '###'
  - 故事板详情
- - '##'
  - 添加 iCloud 支持
- - '###'
  - 创建配置文件
- - '###'
  - 如何进行查询
- - '###'
  - 保存在哪里？
- - '###'
  - 在 iCloud 上存储偏好设置
- - '##'
  - 我们未涉及的内容
- - '#'
  - 第 15 章 Grand Central Dispatch、后台处理与你的应用
- - '##'
  - Grand Central Dispatch
- - '###'
  - 引入 SlowWorker
- - '###'
  - 线程基础
- - '###'
  - 工作单元
- - '###'
  - GCD：底层队列
- - '####'
  - 成为 Block 高手
- - '###'
  - 改进 SlowWorker
- - '###'
  - 别忘了主线程
- - '###'
  - 给予一些反馈
- - '###'
  - 并发 Block
- - '###'
  - 后台处理
- - '##'
  - 应用生命周期
- - '###'
  - 应用状态
- - '###'
  - 状态变更通知
- - '###'
  - 创建状态实验室
- - '###'
  - 探索执行状态
- - '####'
  - 利用执行状态变化
- - '####'
  - 处理 Inactive 状态
- - '###'
  - 处理后台状态
- - '####'
  - 进入后台时移除资源
- - '####'
  - 进入后台时保存状态
- - '####'
  - 请求更多后台时间
- - '##'
  - Grand Central Dispatch，到此结束
- - '#'
  - 第 16 章 使用 Core Graphics 绘图
- - '##'
  - 绘制世界
- - '###'
  - Quartz 2D 的绘图方法
- - '###'
  - Quartz 2D 的图形上下文
- - '###'
  - 坐标系
- - '###'
  - 指定颜色
- - '####'
  - 针对你 iOS 设备屏幕的一点色彩理论
- - '###'
  - 颜色便捷方法
- - '###'
  - 在上下文中绘制图像
- - '###'
  - 绘制形状：多边形、线条和曲线
- - '##'
  - QuartzFun 应用程序
- - '###'
  - 设置 QuartzFun 应用程序
- - '###'
  - 创建随机颜色
- - '###'
  - 定义应用程序常量
- - '###'
  - 实现 QuartzFunView 骨架
- - '###'
  - 创建并连接 Outlets 和 Actions
- - '###'
  - 实现动作方法
- - '###'
  - 添加 Quartz 2D 绘图代码
- - '####'
  - 绘制线条
- - '####'
  - 绘制矩形和椭圆
- - '###'
  - 绘制图像
- - '###'
  - 优化 QuartzFun 应用程序
- - '##'
  - 绘图小结
- - '#'
  - 第 17 章 Sprite Kit 入门
- - '##'
  - 简单的开始
- - '##'
  - 初始场景定制
- - '###'
  - 玩家移动
- - '###'
  - 将玩家添加到场景中
- - '###'
  - 处理触摸：玩家移动
- - '##'
  - 几何计算
- - '##'
  - 摇摆部件
- - '##'
  - 创建敌人
- - '##'
  - 将敌人放入场景
- - '##'
  - 开始射击
- - '##'
  - 定义物理类别
- - '##'
  - 创建 BulletNode 类
- - '##'
  - 应用物理
- - '###'
  - 将子弹添加到场景中
- - '###'
  - 用物理攻击敌人
- - '###'
  - 完成关卡
- - '###'
  - 追踪敌人
- - '###'
  - 过渡到下一关
- - '###'
  - 自定义碰撞
- - '###'
  - 为 SKNode 添加类别
- - '###'
  - 为敌人添加自定义碰撞行为
- - '###'
  - 显示准确的玩家生命值
- - '##'
  - 用粒子系统增添趣味
- - '###'
  - 你的第一个粒子
- - '###'
  - 将粒子放入场景
- - '##'
  - 结束游戏
- - '##'
  - 最后，新开始：创建 StartScene
- - '##'
  - 一音胜过千张图
- - '##'
  - 增加游戏难度：力场
- - '##'
  - 游戏开始
- - '#'
  - 第 18 章 点击、触摸与手势
- - '###'
  - 多点触控术语
- - '###'
  - 响应者链
- - '##'
  - 响应事件
- - '##'
  - 转发事件：保持响应者链活跃
- - '##'
  - 多点触控架构
- - '###'
  - 四个触摸通知方法
- - '###'
  - TouchExplorer 应用程序
- - '##'
  - 轻扫应用程序
- - '###'
  - 使用触摸事件检测轻扫
- - '##'
  - 自动手势识别
- - '##'
  - 实现多种滑动手势
- - '##'
  - 检测多次轻点
- - '##'
  - 检测捏合和旋转
- - '##'
  - 定义自定义手势
- - '##'
  - CheckPlease 应用程序
- - '###'
  - 位置管理器
- - '####'
  - 设置所需精度
- - '####'
  - 设置距离过滤器
- - '####'
  - 获取使用定位服务的权限
- - '####'
  - 启动位置管理器
- - '####'
  - 明智地使用位置管理器
- - '####'
  - 位置管理器委托
- - '####'
  - 获取位置更新
- - '####'
  - 使用`CLLocation`获取纬度和经度
- - '###'
  - 错误通知
- - '###'
  - 尝试 Core Location
- - '###'
  - 使用定位管理器更新
- - '###'
  - 在地图上可视化你的运动轨迹
- - '###'
  - 启用地图套件与使用定位服务
- - '###'
  - 更改定位服务权限
- - '###'
  - 无论你去哪里，你就在这里
- - '#'
  - 第 20 章 哇塞！陀螺仪与加速计！
- - '##'
  - 加速计物理原理
- - '##'
  - 主动运动访问
- - '##'
  - 陀螺仪与姿态结果
- - '##'
  - 加速度计结果
- - '###'
  - 检测摇晃
- - '###'
  - 内置摇晃检测
- - '###'
  - 摇晃即破碎
- - '##'
  - 加速度计作为方向控制器
- - '###'
  - 滚动弹珠
- - '###'
  - 编写弹珠视图
- - '###'
  - 计算球的运动
- - '#'
  - 第 21 章 摄像头与照片库
- - '##'
  - 使用图像选择器和 UIImagePickerController
- - '###'
  - 使用图像选择器控制器
- - '###'
  - 实现图像选择器控制器委托
- - '##'
  - 实地测试摄像头和图库
- - '###'
  - 设计界面
- - '###'
  - 实现相机视图控制器
- - '#'
  - 第 22 章 应用程序本地化
- - '##'
  - 本地化架构
- - '##'
  - 字符串文件
- - '###'
  - 字符串文件中有什么？
- - '##'
  - 本地化字符串宏
- - '##'
  - 真实 iOS 示例：本地化你的应用程序
- - '###'
  - 设置 LocalizeMe
- - '###'
  - 尝试使用 LocalizeMe
- - '##'
  - 本地化项目
- - '##'
  - 本地化故事板
- - '##'
  - 生成并本地化字符串文件
- - '##'
  - 在 Xcode 中预览本地化效果
- - '##'
  - 本地化应用显示名称
- - '##'
  - 添加其他本地化
- - '#'
  - 索引
- - '#'
  - 关于作者
- - '#'
  - 关于技术审稿人
