name: The business of iOS app development
name_cn: iOS 应用开发商业指南
slug: the-business-of-ios-app-development
toc:
- - '###'
  - 修复后的目录
- - '#'
  - iOS 应用开发商业之道
- - '##'
  - 适用于 iPhone、iPad 和 iPod touch
- - '##'
  - 内容概览
- - '##'
  - 目录
- - '##'
  - 关于技术审校者
- - '##'
  - 特别贡献者
- - '##'
  - 引言
- - '##'
  - 第 1 章：在拥挤的应用商店市场中看清全局
- - '###'
  - 为什么为 iOS 开发者写一本商业书？
- - '###'
  - 应对移动营销的新世界
- - '###'
  - 放心——这可不是一本典型的商业书
- - '###'
  - 规划你自己的成功故事
- - '###'
  - 如何使用本书
- - '###'
  - 开始上手你的第一个 iOS 应用
- - '###'
  - 你的应用已经在 App Store 里了？提升销量永远不会太晚
- - '###'
  - 为客户端开发 iOS 应用
- - '###'
  - 准备好潜入了吗？
- - '##'
  - 第 2 章：做好功课：分析 iOS 应用创意并开展竞争性研究
- - '###'
  - 满足需求
- - '###'
  - 发现未被开发的市场
- - '####'
  - 寻找原创应用创意
- - '####'
  - 审视自身需求与兴趣
- - '####'
  - 探索你的业余爱好与兴趣
- - '####'
  - 向亲朋好友取经
- - '####'
  - 逛逛本地报刊亭
- - '####'
  - 将调查转向线上
- - '####'
  - 关于营销的最后一点说明
- - '###'
  - 推广你的应用
- - '####'
  - 提升移动端体验
- - '####'
  - 与同类应用竞争
- - '####'
  - 何时避免过度饱和的类别
- - '####'
  - 评估竞争
- - '#####'
  - 一款用于关注竞争对手的工具
- - '####'
  - 利用替代应用目录进行竞争研究
- - '####'
  - 分析应用排名统计信息
- - '####'
  - 从竞争对手的用户评论中寻找灵感
- - '####'
  - 从他人的错误中学习
- - '####'
  - 超越 App Store 的用户评价
- - '####'
  - 亲身体验你的竞争对手
- - '####'
  - 定义你的差异化
- - '###'
  - 面向多种 iOS 设备
- - '###'
  - 从商业角度看通用应用程序
- - '###'
  - 应用名称有何讲究？
- - '###'
  - 注册网站域名
- - '###'
  - 为 iOS 应用打造独特身份
- - '###'
  - 取得进展
- - '##'
  - 第 3 章：保护你的知识产权
- - '###'
  - 什么是知识产权？
- - '###'
  - 确定你的知识产权策略
- - '###'
  - iOS 应用有所不同
- - '###'
  - 制定 iOS 应用专属的行动计划
- - '###'
  - 为你的应用注册版权
- - '####'
  - 如何获得版权
- - '####'
  - 版权保护的局限性
- - '###'
  - 为应用图标和标志申请商标
- - '####'
  - 商业秘密法概述
- - '####'
  - 如何确立商业秘密？
- - '####'
  - 保密协议
- - '####'
  - 商业秘密保护的限制
- - '###'
  - 专利
- - '####'
  - 专利保护与 iOS 应用开发
- - '####'
  - 你的发明是否具备可专利性？
- - '####'
  - 避免“销售拦阻”
- - '####'
  - 如何提交专利申请
- - '####'
  - 自行提交临时专利申请
- - '###'
  - 知识产权与合同管理
- - '####'
  - 在承包商与员工协议中处理知识产权问题
- - '#####'
  - 雇佣承包商
- - '#####'
  - 雇佣员工
- - '####'
  - 知识产权的引入许可
- - '#####'
  - 记录您的引入许可
- - '###'
  - 应用程序开发中的许可与法律考量
- - '####'
  - 了解你所获取的内容
- - '####'
  - 避免病毒式许可
- - '####'
  - 不要使用苹果的商标
- - '####'
  - 创建自定义最终用户许可协议
- - '#####'
  - EULA 的目的
- - '#####'
  - 免责声明
- - '#####'
  - 责任限制
- - '#####'
  - Apple 的最终用户许可协议（EULA）
- - '#####'
  - 使用您自己 EULA 的理由
- - '#####'
  - 如何以及何时采取法律行动
- - '#####'
  - 争议解决的第一步
- - '#####'
  - 诉讼前步骤
- - '###'
  - 诉讼
- - '###'
  - 总结
- - '##'
  - 第 4 章：您的 iOS 应用是最强大的营销工具
- - '###'
  - 迈入门槛：第一印象决定一切
- - '####'
  - 第一视觉线索
- - '####'
  - 第二视觉线索
- - '####'
  - 第一印象的重要性
- - '####'
  - 打造良好第一印象的更多动力
- - '####'
  - 在苹果的沙盒中遵守规则
- - '###'
  - 为多种 iOS 设备设计
- - '####'
  - 准备 UI 美术资源
- - '####'
  - iPad 的方向考虑
- - '####'
  - 使用 Retina 显示屏屏幕，乐趣加倍
- - '####'
  - 为 iOS 8 设计
- - '#####'
  - SWIFT
- - '####'
  - iOS 8 中的差异
- - '###'
  - 为你的应用定义品牌
- - '####'
  - 你最强大的营销工具
- - '####'
  - 保持一致的品牌形象
- - '####'
  - 创建高效的应用图标与标识
- - '####'
  - 应用图标规则与工具
- - '####'
  - 设计自定义应用图标
- - '#####'
  - 开始绘制草图
- - '#####'
  - 使其独一无二
- - '#####'
  - 简约之美
- - '#####'
  - 示例应用图标
- - '###'
  - 界面设计：像用户一样思考，而非开发者
- - '####'
  - 了解你的用户
- - '####'
  - 在纸上绘制你的想法
- - '####'
  - 创建应用流程/故事板
- - '####'
  - Illustrator 和 Photoshop 中的精美模型
- - '####'
  - 用于设计模型的其他软件工具
- - '####'
  - 使用移动应用设计应用
- - '####'
  - 开始制作原型
- - '#####'
  - 制作一个原型
- - '#####'
  - 使用原型测试用户交互
- - '#####'
  - 跳出框架思考
- - '####'
  - 其他需要考虑的因素
- - '####'
  - UIKit 的舒适熟悉感
- - '####'
  - 可扩展性
- - '####'
  - 图标与图像
- - '####'
  - 为多个 iOS 设备目标设计时
- - '####'
  - 导航栏颜色
- - '####'
  - 使用文本
- - '####'
  - 无障碍设计
- - '####'
  - 给艺术创作困难者的建议
- - '#####'
  - 寻找图形和图标
- - '####'
  - 选择字体
- - '####'
  - 添加音频
- - '####'
  - 使用专业设计服务
- - '####'
  - 创意助推
- - '##'
  - 第 5 章：社交植入：在应用中推广您的应用
- - '###'
  - 在应用中鼓励用户评论
- - '####'
  - 在运行时征求反馈
- - '####'
  - 何时请求评分
- - '####'
  - 通过应用内邮件和社交网络“告诉朋友”
- - '####'
  - 使用第三方网络服务
- - '####'
  - 通过应用内分享连接用户
- - '###'
  - 添加邮件支持
- - '###'
  - 集成 Twitter 和 Facebook
- - '####'
  - 访问 Twitter 的 API
- - '####'
  - 使用适用于 iOS 的 Facebook SDK
- - '###'
  - 使用 ShareKit
- - '###'
  - 人多力量大：通过应用内交叉推广建立协同效应
- - '####'
  - 应用内交叉推广的成功之道
- - '####'
  - 开店设铺
- - '####'
  - 联合则兴
- - '###'
  - 让你的用户借助第三方社交游戏平台互动起来
- - '####'
  - 热情是会传染的
- - '####'
  - 选择社交游戏平台
- - '###'
  - 赢得你的荣誉
- - '##'
  - 第 6 章：免费午餐：免费的价值
- - '###'
  - 从免费应用中创收
- - '###'
  - 免费策略
- - '###'
  - 先试后买
- - '###'
  - 选择路径：精简版 vs. 应用内购买
- - '####'
  - App Store 精简版指南
- - '####'
  - 免费精简版真的能促进付费应用销售吗？
- - '####'
  - 如何制定有效的 Lite 版应用策略
- - '####'
  - 他们不会为免费牛奶而购买奶牛
- - '####'
  - 生产力工具和实用工具的 Lite 版本
- - '####'
  - 游戏的 Lite 版本
- - '####'
  - 何时发布 Lite 版本
- - '###'
  - 完善你的应用内销售话术
- - '####'
  - 放置购买按钮
- - '####'
  - 在精简版中添加升级信息
- - '####'
  - 关于 iPad 的更大显示屏
- - '####'
  - 应用被拒警告
- - '####'
  - 加入分析功能
- - '####'
  - 让精简版无懈可击
- - '####'
  - 将数据从精简版迁移到付费版
- - '####'
  - iOS 3.2 数据迁移方案
- - '####'
  - 云端同步
- - '####'
  - 通过 URL 传输数据
- - '###'
  - 保护市场份额：先免费赠送，再后续升级
- - '###'
  - 通过联盟计划挖掘额外收入
- - '####'
  - 联盟计划的工作原理
- - '####'
  - 免费应用的变现方式
- - '###'
  - 转变思路
- - '##'
  - 第 7 章：利用 iAd 及其他应用内广告机会实现免费应用变现
- - '###'
  - 何时使用应用内广告
- - '####'
  - 了解你的受众
- - '####'
  - 作为销售工具的应用内广告
- - '###'
  - 选择移动广告网络
- - '####'
  - 调查可用选项
- - '####'
  - 哪个广告网络适合你？
- - '###'
  - 支持的广告尺寸和格式
- - '###'
  - 报告和分析功能
- - '###'
  - 全球可用性和定向能力
- - '####'
  - 用户定向与广告收入
- - '####'
  - 收入与填充率
- - '###'
  - 通过广告支持的应用构建业务
- - '###'
  - 平衡 UI 设计美学与广告
- - '####'
  - 设计带可移除广告的免费应用
- - '####'
  - 设计两个版本：带广告版与无广告版
- - '###'
  - 在你的 iOS 应用中集成苹果的 iAd
- - '####'
  - 加入 iAd 网络
- - '####'
  - 设计你的应用以展示 iAd 横幅
- - '###'
  - 编写应用以支持广告
- - '####'
  - 创建新的 Xcode 项目
- - '####'
  - 向项目添加 iAd 框架
- - '####'
  - 向项目添加苹果的 Reachability 类
- - '####'
  - 构建应用基础
- - '####'
  - 检查 iOS 设备的网络连接
- - '####'
  - 构建应用的界面和 UIView 层次结构
- - '#####'
  - 将您的自有广告图片文件复制到项目
- - '#####'
  - 编写应用内广告代码
- - '###'
  - 在您的应用中启用实时广告
- - '####'
  - 关于 iAd
- - '###'
  - 知识就是力量：通过分析追踪应用使用情况
- - '###'
  - 思考赞助与植入式广告
- - '###'
  - 临界点
- - '###'
  - 探索使用应用内购买的免费增值模式
- - '##'
  - 第 8 章：探索使用应用内购买的免费增值模式
- - '###'
  - 忠诚度有回报：现有用户是最好的客户
- - '###'
  - 支持长尾：将持续开发货币化
- - '###'
  - 改变用户认知的挑战
- - '###'
  - 何时以及如何使用应用内购买
- - '####'
  - 理解基本原理
- - '####'
  - 应用内购买类型
- - '####'
  - 应用内购买指南
- - '####'
  - 简约的力量
- - '####'
  - 应用内购买的设置与使用
- - '###'
  - 销售更多内容
- - '###'
  - 提供服务与订阅
- - '###'
  - 展示是成功的关键
- - '###'
  - 找到最佳平衡点
- - '###'
  - 包含正确的元素组合
- - '###'
  - 允许用户随心所欲地花钱
- - '###'
  - 交付与管理应用内购买
- - '####'
  - 解锁内置内容
- - '####'
  - 从你的服务器下载内容
- - '####'
  - 在云端寻找帮助
- - '###'
  - 在 iTunes Connect 中配置应用内购买
- - '####'
  - 设置 iTunes 测试用户账户
- - '####'
  - 创建应用内购买项目
- - '####'
  - 管理你的应用内购买项目
- - '####'
  - 准备测试设备
- - '####'
  - 接入 Store Kit 框架
- - '####'
  - 为应用内购买配置项目
- - '#####'
  - 设置基础内容
- - '###'
  - 让应用内购买启动并运行
- - '####'
  - 步骤 1：消费者是否允许应用内购买？
- - '####'
  - 步骤 2：获取可用的应用内购买项目
- - '####'
  - 第 3 步：请求购买
- - '####'
  - 第 4 步：接收支付状态
- - '####'
  - 第 5 步：提供对已购内容的访问权限
- - '###'
  - 恢复已支付内容
- - '##'
  - 第 9 章：测试与可用性：展现最佳状态
- - '###'
  - 避免大多数一星差评
- - '###'
  - 避免常见陷阱
- - '###'
  - 征求直接反馈
- - '###'
  - 通过应用内帮助预防用户挫败感
- - '####'
  - 应用内帮助指南
- - '####'
  - 用屏幕提示播下知识的种子
- - '####'
  - 教学视频：双刃剑
- - '####'
  - 视觉演示：展示，而非告知
- - '####'
  - 通过基于文本的帮助提供移动手册
- - '####'
  - 一点 HTML 就能带来大不同
- - '####'
  - 仅需一次的操作指引
- - '####'
  - 使用移动 Web 框架构建应用内帮助
- - '###'
  - 配置：设置开发设备
- - '####'
  - 开发阶段的初步测试
- - '####'
  - 步骤 1：在 Xcode Organizer 中建立测试设备
- - '####'
  - 步骤 2：获取你的开发证书
- - '#####'
  - 验证苹果的 WWDR 证书是否已安装
- - '####'
  - 步骤 3：注册你的设备 ID
- - '###'
  - Beta 测试：掌握 Ad Hoc 分发的复杂性
- - '####'
  - 步骤 1：获取分发证书
- - '#####'
  - 导出你的分发私钥以妥善保管
- - '####'
  - 步骤 2：注册 Beta 测试者的设备 ID
- - '#####'
  - 召集队伍
- - '#####'
  - Beta 版测试者招募指南
- - '####'
  - 从 iTunes 收集设备 ID
- - '####'
  - 步骤 3：生成并安装 Ad Hoc 分发配置文件
- - '####'
  - 步骤 4：为 Ad Hoc 分发配置你的应用
- - '####'
  - 第 5 步：将你的应用分发给 Beta 测试人员
- - '####'
  - 向测试人员无线分发
- - '###'
  - 完美收官
- - '##'
  - 第 10 章：派对开始！制造发布前的热度
- - '###'
  - 最后倒计时：准备发射
- - '###'
  - 花时间寻找你的受众
- - '###'
  - 精心打造你的电梯游说
- - '###'
  - 公司标志
- - '###'
  - 应用图标与徽标
- - '###'
  - 截图
- - '###'
  - 视频预告片
- - '###'
  - 专属网站展示
- - '####'
  - 你的 iOS 应用值得拥有一个精心设计的网站
- - '####'
  - 网站托管
- - '####'
  - 格式之争：博客 vs. 定制网站
- - '####'
  - 域名优势
- - '####'
  - 搜索引擎优化策略
- - '#####'
  - '`<title>` 标签'
- - '#####'
  - '`description` 和 `keywords` Meta 标签'
- - '#####'
  - 关键词丰富的文本
- - '#####'
  - 关键词友好的 URL
- - '#####'
  - 保持有效链接
- - '#####'
  - XML 站点地图
- - '####'
  - 追踪网站流量
- - '###'
  - iOS 应用网站的构成
- - '####'
  - 应用品牌标识
- - '####'
  - 快速推介：这是什么？为什么我要关注？
- - '####'
  - App Store 身份标识
- - '####'
  - 购买按钮
- - '####'
  - 定价
- - '####'
  - 截图与视频
- - '#####'
  - 利用富媒体吸引用户
- - '####'
  - 附加详情
- - '####'
  - 社交媒体
- - '####'
  - 邮件新闻订阅列表
- - '####'
  - 客户支持与联系信息
- - '####'
  - 公司身份
- - '####'
  - 其他产品的交叉推广
- - '####'
  - 可下载的附加内容
- - '####'
  - 在销售之前，先开始收集
- - '####'
  - 为何网站与 Mobile Safari 的兼容性如此重要
- - '####'
  - “视口先生，我已准备好特写了。”
- - '####'
  - 使用浏览器检测来提供目标内容
- - '#####'
  - 用于浏览器检测的 JavaScript
- - '#####'
  - 用于浏览器检测的 PHP
- - '####'
  - 动态替换 Flash 为 iOS 兼容内容
- - '#####'
  - 用于 Flash 替换的 JavaScript
- - '#####'
  - 用于 Flash 替换的 PHP
- - '####'
  - 让主屏幕书签更美观
- - '###'
  - 制造声势：博客、Twitter 和社交网络的力量
- - '####'
  - 培养在线社区
- - '#####'
  - 社交媒体营销策略
- - '####'
  - 博客
- - '#####'
  - 同步你的博客内容
- - '#####'
  - 邀请评论
- - '#####'
  - 自己搭建博客还是使用第三方博客服务？
- - '####'
  - Twitter
- - '#####'
  - 管理 Twitter 账号
- - '#####'
  - 获取关注者
- - '#####'
  - 自定义个人资料
- - '#####'
  - 关键词和主题标签
- - '#####'
  - Twitter 列表
- - '#####'
  - 管理信息流
- - '####'
  - Facebook
- - '#####'
  - 创建 Facebook 主页
- - '#####'
  - 与粉丝建立联系
- - '#####'
  - 追踪您的 Facebook 营销效果
- - '#####'
  - 导入博客，输出到 Twitter
- - '#####'
  - 其他社交网络和书签网站
- - '#####'
  - 在论坛、群组和博客上发表评论
- - '#####'
  - 但不要噪音太多：维护专业声誉
- - '###'
  - 人人都爱赢家：收集发布前的评价和推荐
- - '####'
  - 传递接力棒
- - '##'
  - 第 11 章：王国的钥匙：App Store 提交流程
- - '###'
  - 定价策略
- - '####'
  - 分析类似应用
- - '####'
  - 回旋余地
- - '####'
  - 维持长期业务
- - '####'
  - 感知价值与消费者抵触
- - '#####'
  - 定价策略与应用商店优化
- - '###'
  - 提升应用发现率：关键词与命名的艺术
- - '####'
  - 指定关键词
- - '####'
  - 名称游戏
- - '####'
  - 完善应用描述中的销售话术
- - '#####'
  - App Store 描述最佳实践
- - '#####'
  - 这是什么？
- - '#####'
  - 奖项与推荐
- - '#####'
  - 应用功能与优势
- - '#####'
  - 整合所有要素
- - '###'
  - 一图胜千言：截图的重要性
- - '####'
  - 别指望用户会主动下载你的应用
- - '####'
  - 选择主截图
- - '####'
  - 当截图不仅仅是截图时
- - '###'
  - 准备向 App Store 提交的应用二进制文件
- - '####'
  - 第 1 步：确认你的分发证书仍然安装完好
- - '####'
  - 第 2 步：生成并安装一个 App Store 分发配置描述文件
- - '####'
  - 第 3 步：配置你的 Xcode 项目以进行 App Store 发布
- - '####'
  - 第 4 步：编译你的 iOS 应用
- - '####'
  - 确保 Apple 已处理你的合同和付款设置
- - '###'
  - 我们到了吗？在 iTunes Connect 中提交你的应用
- - '####'
  - 第 1 步：创建新的应用条目
- - '#####'
  - 公司名称和主要语言
- - '#####'
  - 应用信息
- - '####'
  - 步骤 2：设置可用日期和定价
- - '#####'
  - 可用日期
- - '#####'
  - 价格等级
- - '#####'
  - 教育折扣与区域可用性
- - '####'
  - 第 3 步：提交应用的元数据
- - '#####'
  - 版本号
- - '#####'
  - 描述
- - '#####'
  - 主要类别和次要类别
- - '#####'
  - 关键词
- - '#####'
  - 版权
- - '#####'
  - 联系邮箱地址
- - '#####'
  - 支持 URL
- - '######'
  - 第三方支持服务
- - '#####'
  - 关于支持的额外说明
- - '#####'
  - 应用 URL
- - '#####'
  - 审阅备注
- - '####'
  - 第 4 步：为你的应用指定分级
- - '####'
  - 第 5 步：上传你的应用图标和屏幕截图
- - '#####'
  - 版本信息页面
- - '#####'
  - 图像部分
- - '######'
  - App Store 图标
- - '######'
  - 应用截图
- - '#####'
  - iTunes Connect 中的新应用列表
- - '####'
  - 步骤 6：支持多种语言
- - '####'
  - 步骤 7：上传您的应用二进制文件以供 App Store 审核
- - '#####'
  - 出口合规
- - '#####'
  - 等待上传应用状态/等待上传状态
- - '#####'
  - 在 Xcode Organizer 中提交您的应用二进制文件
- - '#####'
  - 开发者拒绝状态
- - '#####'
  - 正在审核状态
- - '#####'
  - 准备销售状态
- - '#####'
  - 管理您自己的预期
- - '#####'
  - 获取应用状态通知
- - '#####'
  - 再试一次：应对 App Store 拒绝
- - '###'
  - 通过审核！进入应许之地
- - '###'
  - 分析你的 App Store 销售统计数据
- - '####'
  - 启动引擎
- - '##'
  - 第 12 章：提高你 iOS 应用的知名度
- - '###'
  - 投入与开发同样多的精力来营销你的应用
- - '###'
  - 以宣传大爆发的方式发布
- - '###'
  - 你应该投入多少时间用于营销你的应用？
- - '###'
  - 寻求专业人士的帮助
- - '###'
  - 撰写有效新闻稿的艺术
- - '####'
  - 新闻稿的核心要素
- - '#####'
  - 发布说明 (A)
- - '#####'
  - 主题行 (B)
- - '#####'
  - 摘要行 (C)
- - '#####'
  - 引言 (D)
- - '#####'
  - 描述 (E)
- - '####'
  - 定价与上市信息
- - '####'
  - 网站 URL 及其他信息
- - '####'
  - 关于公司
- - '####'
  - 新闻稿结束标志
- - '####'
  - 媒体联系方式
- - '####'
  - 翻译你的新闻稿
- - '####'
  - 虚拟 24 小时媒体室
- - '####'
  - 与媒体建立联系
- - '####'
  - 格式化你的邮件公告
- - '####'
  - 通知谁？
- - '####'
  - 触达大众
- - '####'
  - 以感谢信强化关系
- - '###'
  - 发放促销码：在有影响力的博客和评测网站上争取应用评测
- - '####'
  - 提供评测材料
- - '####'
  - 获取促销码
- - '####'
  - 宣传需要规划与耐心
- - '###'
  - 利用促销与赠品提升应用被发现率
- - '###'
  - 把握促销时机，重振应用下载量
- - '###'
  - 应用内广告能否促进销售？
- - '####'
  - 向移动受众投放广告
- - '####'
  - 平面杂志广告与 App 生命周期
- - '####'
  - 善用面向开发者的 iAd
- - '####'
  - 按安装付费激励实现交叉销售
- - '###'
  - 与客户保持联系
- - '####'
  - 频繁发布 App 更新
- - '####'
  - 提供高质量支持
- - '###'
  - 在 App Store 中保持势头的额外建议
- - '####'
  - 依靠奖项和认可的声望
- - '####'
  - 分享你的知识
- - '####'
  - Slashdot 效应与博客营销
- - '####'
  - 参与访谈与播客
- - '###'
  - 展望未来
- - '##'
  - 索引
- - '###'
  - A
