name: Program the Internet of Things with Swift for iOS
name_cn: iOS 的 Swift 物联网编程
slug: program-the-internet-of-things-with-swift-for-ios
toc:
- - '#'
  - 引言
- - '#'
  - 致谢
- - '##'
  - 关于作者与技术审稿人
- - '###'
  - 关于作者
- - '###'
  - 关于技术审稿人
- - '#'
  - 第一部分：为物联网构建健康应用
- - '#'
  - 第1章 为你的第一个物联网应用奠定基础
- - '##'
  - 学习目标
- - '###'
  - 注意
- - '##'
  - 设置项目
- - '###'
  - 线框图 vs. 高保真原型
- - '###'
  - 将你的 Apple 开发者账户关联到 Xcode
- - '###'
  - 注意事项
- - '##'
  - 构建自适应用户界面
- - '###'
  - 从基础模板重命名类
- - '###'
  - 注意
- - '###'
  - 布局用户界面
- - '###'
  - 提示
- - '###'
  - 应用自动布局约束
- - '###'
  - 提示
- - '###'
  - 自定义项目外观
- - '###'
  - 提示
- - '###'
  - 解决自动布局问题
- - '##'
  - 将故事板连接到代码
- - '###'
  - 定义与 Interface Builder 兼容的属性和方法（动作）
- - '###'
  - 使用连接检查器完成最终的故事板连接
- - '##'
  - 本章小结
- - '#'
  - 第2章 使用 Core Location 构建健身追踪应用
- - '##'
  - 学习目标
- - '##'
  - 为后台位置活动配置项目
- - '###'
  - 注意事项
- - '##'
  - 请求定位权限
- - '###'
  - 检查硬件可用性
- - '###'
  - 响应定位权限状态的变化
- - '####'
  - 请求用户更改应用设置
- - '##'
  - 请求位置更新
- - '###'
  - 响应位置更新
- - '####'
  - 以编程方式启用后台更新
- - '##'
  - 在地图上显示位置数据
- - '###'
  - 使用 Codable 协议进行基于文件的数据存储
- - '###'
  - 注意
- - '####'
  - 实现文件输入输出（File I/O）
- - '####'
  - 使用 `map()` 方法序列化数据
- - '##'
  - 在地图上显示已保存的位置
- - '##'
  - 本章小结
- - '#'
  - 第3章 使用 Core Motion 向你的 App 添加体能活动数据
- - '##'
  - 学习目标
- - '##'
  - 向用户请求运动权限
- - '##'
  - 从 iPhone 计步器接收实时步数更新
- - '##'
  - 更新用户界面
- - '###'
  - 停止与暂停计步器更新
- - '###'
  - 获取活动类型
- - '###'
  - 注意
- - '##'
  - 处理气压计更新
- - '##'
  - 本章小结
- - '#'
  - 第4章 使用 HealthKit 安全地检索和存储健康数据
- - '##'
  - 学习目标
- - '##'
  - 请求 HealthKit 权限
- - '###'
  - 注意
- - '##'
  - 将数据写入 HealthKit
- - '###'
  - 理解 HealthKit 如何表示数据
- - '###'
  - 创建和保存 HealthKit 样本
- - '##'
  - 从 HealthKit 读取锻炼数据
- - '##'
  - 使用表格视图控制器显示数据
- - '###'
  - 设置用户界面
- - '###'
  - 注意
- - '####'
  - 使用 `UITableViewDataSource` 协议填充表格视图
- - '####'
  - 使用 `UITableViewDelegate` 协议将数据映射到单元格
- - '##'
  - 本章小结
- - '#'
  - 第二部分：构建你自己的物联网设备
- - '#'
  - 第5章 构建基于 Arduino 的外围设备
- - '##'
  - 学习目标
- - '##'
  - 构建无线门磁硬件
- - '###'
  - 零件清单
- - '###'
  - 组装硬件
- - '###'
  - 注意
- - '##'
  - 编写 Arduino 解决方案（程序）
- - '###'
  - 设置 Arduino 编程环境
- - '###'
  - 注意
- - '##'
  - 使用 GPIO 监控输入引脚并控制输出引脚
- - '##'
  - 计算电池状态
- - '###'
  - 运行与监控 Arduino 解决方案
- - '###'
  - 编译故障排除
- - '##'
  - 本章小结
- - '#'
  - 第6章 构建低功耗蓝牙硬件配套应用
- - '##'
  - 学习目标
- - '##'
  - 低功耗蓝牙快速入门
- - '##'
  - 为 Arduino 解决方案添加蓝牙功能
- - '###'
  - 安装 `ESP32_BLE_Arduino` 库以实现蓝牙通信
- - '##'
  - 将 Arduino 设置为蓝牙外设
- - '###'
  - 注意
- - '###'
  - 通过蓝牙 LE 发送数据更新
- - '##'
  - 使用 Core Bluetooth 与蓝牙 LE 设备通信
- - '###'
  - 设置 IOTHome 项目
- - '###'
  - 启用蓝牙配件后台更新
- - '##'
  - 将 App 设置为中央管理器
- - '##'
  - 为 IOTHome 应用配置蓝牙中心管理器
- - '##'
  - 连接到蓝牙低功耗外设
- - '##'
  - 监控特征值更新
- - '###'
  - 在应用后台运行时监控更新
- - '##'
  - 本章小结
- - '#'
  - 第7章 搭建树莓派并将其用作 HomeKit 桥接器
- - '##'
  - 学习目标
- - '##'
  - 设置树莓派 HomeKit 桥接器
- - '###'
  - 组装硬件
- - '####'
  - 组装电路
- - '###'
  - 引导启动树莓派
- - '###'
  - 安装 HomeBridge
- - '####'
  - 注意
- - '####'
  - 警告
- - '###'
  - 配置 HomeBridge 以读取温度传感器数据
- - '####'
  - 注意
- - '###'
  - 配置 HomeBridge 以连接蓝牙低功耗配件
- - '###'
  - 配置 HomeBridge 开机自启动（实验性功能）
- - '###'
  - 连接到你的新 HomeKit 桥接器
- - '###'
  - 排查配置问题
- - '##'
  - 本章小结
- - '#'
  - 第8章 在树莓派上搭建网页服务器
- - '##'
  - 学习目标
- - '##'
  - 创建用于通过 HTTPS 共享数据的网页服务器
- - '###'
  - 使用 Express 公开网页服务
- - '###'
  - 从 DHT 温湿度传感器读取数值
- - '####'
  - 提示
- - '####'
  - 注意
- - '###'
  - 从蓝牙设备读取信息
- - '####'
  - 注意
- - '###'
  - 使用 HTTPS 提供安全的 HTTP 连接
- - '###'
  - 生成 OpenSSL 自签名 SSL 证书
- - '###'
  - 配置树莓派开机自启服务器
- - '##'
  - 从 iOS App 连接到你的服务器
- - '###'
  - 设置用户界面
- - '###'
  - 发起并响应 HTTPS 请求
- - '####'
  - 警告
- - '##'
  - 本章小结
- - '#'
  - 第三部分：使用 Apple 先进的物联网技术构建应用
- - '#'
  - 第9章 使用 tvOS 构建 Apple TV 仪表盘应用
- - '##'
  - 学习目标
- - '##'
  - 设置 tvOS 目标
- - '##'
  - 创建用户界面
- - '###'
  - 通过编程为元素添加样式以匹配 tvOS 设计语言
- - '####'
  - 注意
- - '###'
  - 使用 Font Awesome 实现基于字体的图形
- - '##'
  - 向 tvOS 应用添加数据源
- - '###'
  - 请求用户位置信息
- - '###'
  - 连接 OpenWeatherMap API
- - '##'
  - 处理 Siri Remote 的触控输入
- - '##'
  - 在 Apple TV 上调试应用
- - '##'
  - 本章小结
- - '#'
  - 第10章 使用 watchOS 构建 Apple Watch 应用
- - '##'
  - 学习目标
- - '###'
  - 设置项目
- - '##'
  - 构建 watchOS 用户界面
- - '###'
  - 实现 Stack Views 并配置 WatchKit 界面
- - '###'
  - 使用 `WKInterfaceTable` 类设置表格视图
- - '###'
  - 添加 Force Touch 支持
- - '###'
  - 将选择器连接到接口控制器中的方法
- - '##'
  - 使用 Core Location 和 Core Motion 创建新锻炼
- - '##'
  - 使用 HealthKit 填充锻炼历史表格
- - '##'
  - 本章小结
- - '#'
  - 第11章 使用 Face ID、Touch ID 和钥匙串服务保护您的应用
- - '##'
  - 学习目标
- - '##'
  - 项目设置
- - '##'
  - 创建锁屏用户界面
- - '##'
  - 查询传感器可用性
- - '##'
  - 使用 Face ID 或 Touch ID 限制功能访问
- - '##'
  - 完成身份验证流程的最后步骤
- - '##'
  - 使用钥匙串服务保护数据
- - '###'
  - 注意
- - '###'
  - 使用生物识别或应用密码锁定钥匙串项目
- - '###'
  - 注意事项
- - '##'
  - 检测应用何时回到前台
- - '##'
  - 本章小结
- - '#'
  - 索引
- - '##'
  - A
- - '##'
  - B
- - '##'
  - C
- - '##'
  - D
- - '##'
  - E
- - '##'
  - F
- - '##'
  - G
- - '##'
  - H
- - '##'
  - I, J
- - '##'
  - K
- - '##'
  - L
- - '##'
  - M
- - '##'
  - N
- - '##'
  - O
- - '##'
  - P, Q
- - '##'
  - R
- - '##'
  - S
- - '##'
  - T
- - '##'
  - U
- - '##'
  - V
- - '##'
  - W, X, Y, Z
