name: Modern Concurrency on Apple Platforms
name_cn: Apple 平台现代并发编程
slug: modern-concurrency-on-apple-platforms
toc:
- - '##'
  - 修复说明
- - '#'
  - 前言
- - '##'
  - 本书读者对象
- - '##'
  - 本书组织结构
- - '#'
  - 开始之前
- - '#'
  - 致谢
- - '#'
  - 关于作者与审校者
- - '#'
  - 1. 引言
- - '##'
  - 需要了解的重要概念
- - '###'
  - 线程
- - '###'
  - 并发与异步编程
- - '###'
  - 多线程陷阱
- - '####'
  - 死锁
- - '#####'
  - 解决死锁问题
- - '######'
  - 互斥锁
- - '######'
  - 信号量
- - '####'
  - 饥饿
- - '####'
  - 竞态条件
- - '####'
  - 活锁
- - '###'
  - 现有的多线程与并发工具
- - '####'
  - pthreads
- - '####'
  - NSThreads
- - '####'
  - Grand Central Dispatch (GCD)
- - '###'
  - '`NSOperation` APIs'
- - '###'
  - 介绍 `async/await`
- - '##'
  - 环境要求
- - '##'
  - 摘要
- - '##'
  - 练习题
- - '#'
  - 2. 初识 async/await
- - '##'
  - 闭包在并发与多线程中的定位
- - '##'
  - 开始使用 async/await
- - '###'
  - '`async` 关键字'
- - '###'
  - '`await` 关键字'
- - '###'
  - 使用 `async/await`
- - '###'
  - async get 属性
- - '###'
  - iOS 13 和 iOS 14 中的 async/await
- - '###'
  - 本章小结
- - '###'
  - 练习
- - '#'
  - 3. 续体
- - '##'
  - 理解续体
- - '###'
  - 将基于闭包的调用转换为 async/await
- - '###'
  - 将基于委托的代码转换为 async/await
- - '####'
  - '`ContactPicker` 项目'
- - '####'
  - 将基于委托的调用包装到 async/await 替代方案中
- - '###'
  - 在 iOS 13 和 14 中支持 async/await
- - '##'
  - 总结
- - '##'
  - 练习
- - '###'
  - 编程练习
- - '#'
  - 4. 结构化并发
- - '##'
  - 理解结构化并发
- - '###'
  - '`async let` 构造体'
- - '###'
  - 任务组
- - '####'
  - 任务组实战
- - '#####'
  - 图片下载器项目
- - '##'
  - 总结
- - '##'
  - 练习题
- - '#'
  - 5. 非结构化并发
- - '##'
  - 深入理解 Task
- - '###'
  - 创建任务
- - '###'
  - 无结构化并发实战
- - '####'
  - 修改 `ImageManager` 类
- - '####'
  - 修改 `ContentViewViewModel` 类
- - '####'
  - 修改 `ContentView` 对象
- - '###'
  - 任务树
- - '###'
  - 错误传播
- - '###'
  - 任务取消
- - '###'
  - 任务取消与任务组
- - '##'
  - 使用分离任务的无结构化并发
- - '##'
  - 总结
- - '##'
  - 练习
- - '###'
  - 改进项目
- - '#'
  - 6. 参与者（Actors）
- - '##'
  - 参与者介绍
- - '##'
  - 与 Actor 交互
- - '###'
  - 对 Actor 的非隔离访问
- - '###'
  - Actor 与协议遵循
- - '##'
  - Actor 重入问题
- - '##'
  - Actor 与分离任务
- - '##'
  - 使用 Actor 的一般性建议
- - '##'
  - 总结
- - '#'
  - 7. 可发送类型
- - '##'
  - 理解可发送类型
- - '###'
  - 可发送协议
- - '####'
  - 分析可发送类型
- - '###'
  - 结构体
- - '###'
  - 类
- - '###'
  - 闭包
- - '##'
  - 总结
- - '#'
  - 主执行者与最终执行者
- - '##'
  - 主线程
- - '###'
  - 主执行器
- - '####'
  - 使用 `@MainActor`
- - '##'
  - 理解全局 Actor
- - '###'
  - 创建全局 Actor
- - '##'
  - 总结
- - '#'
  - 9. AsyncSequence
- - '##'
  - AsyncSequence 简介
- - '##'
  - 深入浅出序列与异步序列
- - '##'
  - AsyncSequence 具体类型
- - '##'
  - AsyncSequence 示例
- - '###'
  - 支持`AsyncSequence`的原生 API
- - '##'
  - '`AsyncStream`对象'
- - '###'
  - '`CoreLocationAsyncStream`项目'
- - '####'
  - '`LocationUpdater`类'
- - '#####'
  - 请求位置使用权限
- - '#####'
  - 在循环中接收位置信息
- - '###'
  - 完成项目
- - '###'
  - '`AsyncThrowingStream` 对象'
- - '##'
  - 总结
- - '#'
  - 10. `@TaskLocal`
- - '##'
  - '`@TaskLocal` 属性包装器介绍'
- - '###'
  - 使用 `@TaskLocal`
- - '##'
  - 总结
- - '#'
  - 脚注
- - '##'
  - A
- - '##'
  - C
- - '##'
  - B
- - '##'
  - C (续)
- - '##'
  - D
- - '##'
  - E
- - '##'
  - F
- - '##'
  - G
- - '##'
  - H
- - '##'
  - I, J, K
- - '##'
  - L
- - '##'
  - M
- - '##'
  - N
- - '##'
  - O
- - '##'
  - P, Q
- - '##'
  - R
- - '##'
  - S
- - '##'
  - T
- - '##'
  - U
- - '##'
  - V
- - '##'
  - W, X, Y, Z
