name: Learn iOS 8 App Development
name_cn: iOS 8 应用开发入门指南
slug: learn-ios-8-app-development
toc:
- - '#'
  - 学习 iOS 8 应用开发
- - '##'
  - 内容速览
- - '##'
  - 目录
- - '#'
  - 配置详细视图
- - '#'
  - 编辑
- - '#'
  - 插入和移除项目
- - '#'
  - 启用表格编辑
- - '#'
  - 编辑详情
- - '#'
  - 观察 MyWhatsit 的变化
- - '#'
  - 模态编辑与非模态编辑
- - '#'
  - 细节优化
- - '#'
  - 高级表格视图专题
- - '#'
  - 总结
- - '#'
  - 两大家族，同样尊贵
- - '#'
  - 罗密欧遇见朱丽叶
- - '#'
  - 类与 Cookie
- - '#'
  - 类、对象与方法，天哪！
- - '#'
  - 继承
- - '#'
  - 抽象类与具体类
- - '#'
  - 重写方法
- - '#'
  - 设计模式与原则
- - '#'
  - 封装
- - '#'
  - 单一职责
- - '#'
  - 稳定性
- - '#'
  - 开闭原则
- - '#'
  - 委托
- - '#'
  - 其他模式
- - '#'
  - 总结
- - '#'
  - 设计
- - '#'
  - 扩展你的设计
- - '#'
  - 修订数据模型
- - '#'
  - 添加图像视图
- - '#'
  - 更新视图控制器
- - '#'
  - 连接“选择图像”操作
- - '#'
  - 拍照
- - '#'
  - 你不能总是得偿所愿
- - '#'
  - 呈现图像选择器
- - '#'
  - 导入图像
- - '#'
  - 裁剪与调整大小
- - '#'
  - 收尾工作
- - '#'
  - 测试相机
- - '#'
  - 处理常规界面
- - '#'
  - 粘性键盘
- - '#'
  - 高级相机技术
- - '#'
  - 总结
- - '#'
  - 模型-视图-控制器设计模式
- - '#'
  - 数据模型对象
- - '#'
  - 视图对象
- - '#'
  - 控制器对象
- - '#'
  - MVC 通信
- - '#'
  - 颜色模型
- - '#'
  - 创建你的数据模型
- - '#'
  - 创建视图对象
- - '#'
  - 编写你的控制器
- - '#'
  - 连接你的界面
- - '#'
  - 拥有多个视图
- - '#'
  - 整合更新
- - '#'
  - 复杂视图对象
- - '#'
  - 用 ColorView 替换 UIView
- - '#'
  - 将视图连接到数据模型
- - '#'
  - 绘制 ColorView
- - '#'
  - 做一名敏锐的观察者
- - '#'
  - 键值观察
- - '#'
  - 观察键值变化
- - '#'
  - 创建 KVO 依赖关系
- - '#'
  - 多向量数据模型变化
- - '#'
  - 处理触摸事件
- - '#'
  - 绑定滑块
- - '#'
  - 最终润色
- - '#'
  - 取巧
- - '#'
  - 总结
- - '#'
  - 目录
- - '##'
  - 关于作者
- - '##'
  - 关于技术评审
- - '##'
  - 致谢
- - '##'
  - 引言
- - '###'
  - 这本书适合谁？
- - '#'
  - 本书假定您是 iOS 开发新手
- - '##'
  - 不拘一格
- - '##'
  - 如何使用本书
- - '##'
  - 第 1 章：工欲善其事
- - '###'
  - 要求
- - '###'
  - 安装 Xcode
- - '###'
  - 什么是 Xcode？
- - '###'
  - 成为 iOS 开发者
- - '###'
  - 获取项目文件
- - '##'
  - 首次启动 Xcode
- - '##'
  - 欢迎使用 Xcode
- - '###'
  - 导航区域
- - '###'
  - 编辑器区域
- - '###'
  - 实用工具区域
- - '###'
  - 调试区域
- - '###'
  - 工具栏
- - '##'
  - 运行您的第一个应用程序
- - '#'
  - 总结
- - '##'
  - 第 2 章：砰！应用
- - '###'
  - 设计
- - '###'
  - 创建项目
- - '###'
  - 设置项目属性
- - '###'
  - 构建界面
- - '###'
  - 添加对象
- - '###'
  - 删除和连接对象
- - '###'
  - 向视图添加视图
- - '###'
  - 编辑对象属性
- - '###'
  - 添加资源
- - '###'
  - 图片资源的分辨率
- - '###'
  - 自定义按钮
- - '###'
  - 使用故事板
- - '####'
  - 无摩擦开发
- - '####'
  - 添加新场景
- - '####'
  - 创建 Segue
- - '####'
  - 设置导航标题
- - '###'
  - 测试你的界面
- - '###'
  - 调试你的应用
- - '###'
  - 添加基本约束
- - '###'
  - 添加缺失的约束
- - '###'
  - 编辑约束对象
- - '###'
  - 添加关系约束
- - '###'
  - 完成你的应用
- - '#'
  - 总结
- - '##'
  - 第 3 章：旋转网页
- - '###'
  - 设计
- - '###'
  - 创建项目
- - '###'
  - 构建网页浏览器
- - '###'
  - 编码一个网页浏览器
- - '###'
  - 向 `ViewController` 添加输出口
- - '###'
  - 连接自定义输出口
- - '###'
  - 向 `ViewController` 添加操作
- - '###'
  - 设置动作连接
- - '###'
  - 测试网页浏览器
- - '###'
  - 调试网页视图
- - '###'
  - 添加 URL 缩短功能
- - '###'
  - 设计 URL 缩短代码
- - '###'
  - 成为 Web 视图的委托
- - '###'
  - 缩短 URL
- - '####'
  - X.CO URL 缩短服务
- - '####'
  - 编写 `shortenURL(_:)`
- - '###'
  - URL 字符串编码
- - '###'
  - 成为 NSURLConnection 委托
- - '###'
  - 测试服务
- - '###'
  - 最终润色
- - '###'
  - 清理界面
- - '##'
  - 本章小结
- - '##'
  - 第 4 章：即将发生的事件
- - '###'
  - 运行循环
- - '###'
  - 事件队列
- - '###'
  - 事件传递
- - '####'
  - 直接传递
- - '####'
  - 命中测试
- - '####'
  - 第一响应者
- - '####'
  - 事件处理
- - '####'
  - 高级 vs. 低级事件
- - '##'
  - 八球应用
- - '###'
  - 设计
- - '###'
  - 创建项目
- - '###'
  - 创建界面
- - '###'
  - 编写代码
- - '###'
  - 处理摇动事件
- - '###'
  - 测试你的 EightBall 应用
- - '###'
  - 演示响应者链的实验
- - '#'
  - 收尾工作
- - '#'
  - 在物理 iOS 设备上测试
- - '#'
  - 响应者链的其他用途
- - '##'
  - Touchy 应用
- - '###'
  - 设计
- - '###'
  - 创建项目
- - '###'
  - 创建自定义视图
- - '###'
  - 处理触摸事件
- - '###'
  - 绘制你的视图
- - '###'
  - 在 Interface Builder 中添加自定义对象
- - '###'
  - 测试 Touchy
- - '#'
  - 高级事件处理
- - '#'
  - 总结
- - '##'
  - 练习题
- - '#'
  - 修改 EightBall
- - '##'
  - 第 5 章：餐桌礼仪
- - '###'
  - 表格视图
- - '####'
  - 纯表格
- - '####'
  - 分组表格
- - '###'
  - 单元格样式
- - '###'
  - 单元格辅助视图
- - '###'
  - 自定义单元格
- - '###'
  - 表格视图的工作原理
- - '####'
  - 表格单元格和橡皮图章
- - '##'
  - MyStuff
- - '###'
  - 设计
- - '###'
  - 创建项目
- - '###'
  - 创建数据模型
- - '###'
  - 创建数据源
- - '###'
  - 实现你的橡皮印章
- - '###'
  - 表格单元格缓存
- - '####'
  - 单元格对象标识符与重用
- - '###'
  - 测试 MyStuff
- - '##'
  - 添加详情视图
- - '###'
  - 创建详情视图
- - '###'
  - 配置详情视图
- - '###'
  - 编辑
- - '###'
  - 插入和移除项目
- - '###'
  - 启用表格编辑
- - '##'
  - 编辑详细信息
- - '##'
  - 观察 MyWhatsit 的变化
- - '##'
  - 细节打磨
- - '##'
  - 高级表格视图主题
- - '#'
  - 总结
- - '##'
  - 第 6 章：对象之课
- - '##'
  - 两大家族，同样尊贵
- - '##'
  - 继承
- - '##'
  - 抽象类与具体类
- - '##'
  - 重写方法
- - '##'
  - 设计模式与原则
- - '###'
  - 封装
- - '###'
  - 目的单一性
- - '###'
  - 稳定性
- - '###'
  - 开闭原则
- - '###'
  - 委托
- - '##'
  - 其他模式
- - '#'
  - 总结
- - '##'
  - 第 7 章：微笑！
- - '##'
  - 本章内容
- - '###'
  - 设计
- - '###'
  - 扩展设计
- - '####'
  - 修改数据模型
- - '####'
  - 添加图片视图
- - '###'
  - 更新视图控制器
- - '###'
  - 连接“选择图片”操作
- - '###'
  - 拍摄照片
- - '###'
  - 你无法总是得到想要的东西
- - '###'
  - 展示图像选取器
- - '###'
  - 导入图像
- - '###'
  - 裁剪和调整大小
- - '###'
  - 粘滞键盘
- - '###'
  - 高级相机技术
- - '#'
  - 总结
- - '##'
  - 练习
- - '##'
  - 第 8 章：模范成员
- - '###'
  - 模型-视图-控制器设计模式
- - '####'
  - 数据模型对象
- - '####'
  - 视图对象
- - '####'
  - 控制器对象
- - '####'
  - MVC 通信
- - '###'
  - 颜色模型
- - '###'
  - 创建你的数据模型
- - '###'
  - 创建视图对象
- - '###'
  - 编写你的控制器
- - '###'
  - 连接界面
- - '###'
  - 拥有多个视图
- - '####'
  - 整合更新
- - '####'
  - 复杂视图对象
- - '###'
  - 用 `ColorView` 替换 `UIView`
- - '###'
  - 将视图连接到数据模型
- - '###'
  - 绘制 `ColorView`
- - '###'
  - 成为一个敏锐的观察者
- - '###'
  - 键值观察
- - '###'
  - 观察键值变化
- - '###'
  - 创建 KVO 依赖关系
- - '###'
  - 多向量数据模型变更
- - '###'
  - 处理触摸事件
- - '###'
  - 绑定滑块
- - '###'
  - 最终润色
- - '#'
  - 总结
- - '##'
  - 练习
- - '##'
  - 第 9 章：甜美音乐
- - '###'
  - 制作你自己的 iPod
- - '####'
  - 设计
- - '####'
  - 添加音乐选择器
- - '####'
  - 查询 iPod 音乐资料库
- - '####'
  - 使用音乐播放器
- - '####'
  - 应用与 iPod 音乐播放器
- - '####'
  - 添加播放控制
- - '####'
  - 接收音乐播放器通知
- - '####'
  - 添加媒体元数据
- - '####'
  - 创建元数据视图
- - '####'
  - 添加图像视图
- - '####'
  - 添加通用约束
- - '####'
  - 添加紧凑/任意约束
- - '####'
  - 添加规则/任意约束
- - '####'
  - 添加歌曲标签
- - '####'
  - 预览你的布局
- - '####'
  - 完成专辑界面
- - '#####'
  - 观察正在播放的项目
- - '#####'
  - 制造一点声响
- - '#####'
  - 身处更广阔的世界
- - '###'
  - 配置你的音频会话
- - '###'
  - 播放音频文件
- - '###'
  - 创建 `AVAudioPlayer` 对象
- - '###'
  - 添加声音按钮
- - '####'
  - 紧凑型界面的按钮布局
- - '####'
  - 常规界面的按钮布局
- - '###'
  - 制造噪音
- - '###'
  - 激活音频会话
- - '###'
  - 其他音频主题
- - '#'
  - 总结
- - '##'
  - 练习
- - '##'
  - 第 10 章：有视图了吗？
- - '###'
  - 通过示例学习
- - '##'
  - 按钮
- - '##'
  - 响应者与视图类
- - '##'
  - 控件类
- - '##'
  - 按钮类型
- - '##'
  - 控件状态
- - '##'
  - 按钮代码
- - '##'
  - 开关与滑块
- - '##'
  - 页面控件
- - '##'
  - 步进器
- - '##'
  - 分段控件
- - '##'
  - 进度指示器
- - '##'
  - 文本视图
- - '###'
  - 标签
- - '###'
  - 文本字段
- - '###'
  - 文本编辑行为
- - '###'
  - 文本视图
- - '##'
  - 搜索栏
- - '##'
  - 选择器
- - '###'
  - 日期选择器
- - '##'
  - 分组表格
- - '##'
  - 你永远看不到的视图
- - '###'
  - 滚动视图与键盘
- - '##'
  - 警告控制器
- - '#'
  - 总结
- - '##'
  - 第 11 章：为我画一幅画
- - '###'
  - 创建自定义视图类
- - '####'
  - 视图坐标
- - '####'
  - 框架与边界
- - '####'
  - 移动视图
- - '####'
  - 坐标系转换
- - '####'
  - 视图的绘制时机
- - '####'
  - 绘制视图
- - '###'
  - 填充和描边函数
- - '###'
  - 贝塞尔路径
- - '###'
  - 图像
- - '##'
  - 形状优美的应用
- - '###'
  - 以编程方式创建视图
- - '###'
  - 初始化您的对象
- - '###'
  - '`drawRect(_:)` 函数'
- - '###'
  - 创建贝塞尔路径
- - '###'
  - 避免像素恐惧症：点与像素
- - '###'
  - 测试正方形
- - '###'
  - 更多形状，更多颜色
- - '###'
  - 应用平移变换
- - '###'
  - 应用缩放变换
- - '###'
  - 动效：不仅仅是漫画的专属
- - '###'
  - 使用核心动画
- - '###'
  - 为 Shapely 添加动效
- - '###'
  - OpenGL、Sprite Kit、Scene Kit 和 Metal
- - '###'
  - Sprite Kit
- - '###'
  - Scene Kit
- - '###'
  - Metal
- - '###'
  - OpenGL
- - '##'
  - 事物的顺序
- - '##'
  - 绘制图像
- - '##'
  - 高级图形
- - '###'
  - 文本
- - '###'
  - 阴影、渐变色和图案
- - '###'
  - 混合模式
- - '###'
  - 上下文栈
- - '#'
  - 总结
- - '###'
  - 练习
- - '##'
  - 第 12 章：到达那里并返回
- - '#'
  - 模态导航
- - '#'
  - 栈式导航
- - '#'
  - 标签栏导航
- - '#'
  - 页面视图导航
- - '#'
  - 分屏视图导航
- - '#'
  - 自定义导航
- - '#'
  - 仙境应用导航
- - '##'
  - 创建仙境应用
- - '###'
  - 添加仙境的资源
- - '###'
  - 配置标签栏项目
- - '###'
  - 第一个内容视图控制器
- - '###'
  - 创建可导航的表格视图
- - '###'
  - 为表格视图注入数据
- - '###'
  - 创建详情视图
- - '###'
  - 添加数据模型
- - '###'
  - 实现数据源
- - '###'
  - 定义表视图单元格对象
- - '###'
  - 推入详情视图控制器
- - '##'
  - 设计原型页面
- - '##'
  - 编写单页视图控制器代码
- - '##'
  - 编写页面视图数据源
- - '##'
  - 初始化页面视图控制器
- - '##'
  - 呈现视图控制器
- - '###'
  - 呈现控制器
- - '###'
  - 模态呈现视图控制器
- - '###'
  - 模态呈现样式
- - '###'
  - 制定展示建议
- - '###'
  - 在展示期间适配视图控制器
- - '##'
  - 弹出呈现控制器
- - '##'
  - 适配视图控制器内容
- - '###'
  - 1. 标签
- - '###'
  - 2. 图像视图
- - '###'
  - 3. 文本视图
- - '####'
  - 设置约束优先级
- - '####'
  - 固有尺寸
- - '###'
  - 使用特征集合
- - '###'
  - 添加自适应约束（及对象）
- - '###'
  - 以编程方式自适应视图
- - '####'
  - 在特征变化时自适应
- - '###'
  - 尺寸变化时的适配
- - '###'
  - 布局发生时的适配
- - '###'
  - 动画化布局变化
- - '##'
  - 视图控制器高级主题
- - '###'
  - 自定义呈现和转场
- - '###'
  - 外观代理
- - '#'
  - 总结
- - '##'
  - 第 13 章：共享即关爱
- - '##'
  - 为我的（社交）世界增添色彩
- - '##'
  - 有东西可分享
- - '###'
  - 呈现活动视图控制器
- - '###'
  - 分享越多，收获越多
- - '###'
  - 重构 `drawRect(_:)`
- - '##'
  - 提供更多可分享的项目
- - '##'
  - 排除活动
- - '##'
  - 最低共同标准之诅咒
- - '##'
  - 提供特定于活动的数据
- - '##'
  - 承诺与兑现
- - '##'
  - 大数据
- - '##'
  - 发明您自己的活动
- - '##'
  - 与特定服务分享
- - '##'
  - 其他社交网络交互
- - '#'
  - 总结
- - '##'
  - 第 14 章：游戏开始！
- - '###'
  - SpaceSalad
- - '###'
  - SpriteKit 简要介绍
- - '###'
  - 创建场景
- - '####'
  - 解档 SpriteKit 场景
- - '###'
  - 添加精灵
- - '###'
  - 调整场景大小
- - '###'
  - 让我们动起来
- - '###'
  - 设置边界
- - '###'
  - 枚举子节点
- - '###'
  - 添加障碍物
- - '###'
  - 与玩家交互
- - '###'
  - 响应触摸
- - '###'
  - 平面上的精灵
- - '###'
  - 发生碰撞的节点
- - '###'
  - 接触！
- - '##'
  - 将 SpaceSalad 游戏化
- - '##'
  - 行动中的动作
- - '#'
  - 传统动画
- - '#'
  - 呈现场景
- - '###'
  - 超越 SpaceSalad
- - '#'
  - 总结
- - '##'
  - 练习
- - '##'
  - 第 15 章：你若构建，它便成真……
- - '###'
  - Interface Builder 文件的工作原理
- - '###'
  - 编译 Interface Builder 文件
- - '###'
  - 加载场景
- - '##'
  - 加载 `.xib` 文件
- - '##'
  - 占位对象与文件所有者
- - '##'
  - 创建对象
- - '##'
  - 编辑属性
- - '##'
  - 创建自定义对象
- - '##'
  - 连接
- - '###'
  - 建立动作连接
- - '##'
  - 发送操作消息
- - '##'
  - 声明占位对象
- - '##'
  - 设计 ShapeView
- - '##'
  - 连接手势识别器
- - '##'
  - 创建视图
- - '##'
  - 获取运动数据
- - '###'
  - 创建`CMMotionManager`
- - '###'
  - 启动和停止更新
- - '##'
  - 推与拉
- - '##'
  - 时机就是一切
- - '##'
  - 抖动的烦恼
- - '##'
  - 使用动态动画
- - '##'
  - 创建动态动画师
- - '##'
  - 定义行为
- - '###'
  - 旋转拨盘动画
- - '###'
  - 获取其他类型的运动数据
- - '###'
  - 陀螺仪数据
- - '###'
  - 磁力计数据
- - '###'
  - 设备运动与姿态
- - '#'
  - 总结
- - '##'
  - 第 17 章：你在哪里？
- - '##'
  - 创建 Pigeon
- - '##'
  - 收集位置数据
- - '###'
  - 请求权限
- - '###'
  - 开始收集位置信息
- - '###'
  - 使用地图视图
- - '##'
  - 装饰您的地图
- - '###'
  - 添加标注
- - '###'
  - 地图坐标
- - '###'
  - 添加一点弹跳效果
- - '###'
  - 指引回家的路
- - '##'
  - 使用叠加层装饰地图
- - '###'
  - 添加叠加层
- - '###'
  - 提供渲染器
- - '###'
  - 创建自定义叠加层渲染器
- - '##'
  - 位置监控
- - '###'
  - 近似定位与非 GPS 设备
- - '###'
  - 监控区域
- - '###'
  - 减少位置变化消息
- - '###'
  - 移动与方向
- - '##'
  - 地理编码
- - '###'
  - 获取路线规划
- - '#'
  - 总结
- - '##'
  - 练习
- - '##'
  - 第 18 章：还记得我吗？
- - '#'
  - 属性列表
- - '##'
  - 属性列表
- - '##'
  - 序列化属性列表
- - '##'
  - 用户默认设置
- - '##'
  - 让鸽子记住
- - '##'
  - 最小化更新与代码
- - '###'
  - 定义键值
- - '###'
  - 向用户默认设置写入值
- - '###'
  - 从用户默认设置获取值
- - '###'
  - 测试用户默认设置
- - '###'
  - 注册默认值
- - '##'
  - 将对象转换为属性列表对象
- - '##'
  - 保存和恢复 savedLocation
- - '##'
  - 应用生命周期状态
- - '##'
  - 保存视图控制器
- - '###'
  - 保存与恢复的步骤
- - '##'
  - 分配恢复标识符
- - '##'
  - 自定义恢复
- - '##'
  - 更深层次的恢复
- - '##'
  - 云中的鸽子
- - '###'
  - 在云中存储值
- - '###'
  - 云端监控
- - '##'
  - 启用 iCloud
- - '##'
  - 测试云
- - '##'
  - 打包你的设置
- - '###'
  - 创建设置捆绑包
- - '###'
  - 使用你的设置束值
- - '###'
  - 测试你的设置束
- - '#'
  - 总结
- - '##'
  - 练习
- - '##'
  - 第 19 章：文档概述
- - '##'
  - 我的文档究竟该存到哪里？
- - '##'
  - MyStuff 的文档化
- - '##'
  - 提供文档的数据
- - '##'
  - 封装你的数据
- - '###'
  - 使用包装器
- - '###'
  - 增量文档更新
- - '###'
  - 构建你的包装器
- - '###'
  - 解读你的包装器
- - '##'
  - 其他存储方案
- - '##'
  - 归档对象
- - '###'
  - 采用 NSCoding
- - '####'
  - 子类化一个 <NSCoding> 类
- - '###'
  - 归档和取消归档对象
- - '##'
  - 归档序列化对决
- - '##'
  - 序列化，遇见归档
- - '##'
  - 文档，遇见你的数据模型
- - '##'
  - 跟踪更改
- - '##'
  - 测试你的文档
- - '###'
  - 设置断点
- - '###'
  - 单步执行代码并检查变量
- - '##'
  - 创建 `ThingsDocument` 委托
- - '##'
  - 存储图片文件
- - '###'
  - 检索图像
- - '###'
  - 删除图像
- - '##'
  - 连接文档与数据模型
- - '##'
  - 杂项
- - '#'
  - iCloud 存储
- - '#'
  - 归档版本控制
- - '#'
  - 总结
- - '##'
  - 第 20 章：看 Swift，看 Swift 奔跑
- - '#'
  - Swift 语言入门
- - '##'
  - Swift 的（简短）历史
- - '##'
  - 类
- - '#'
  - 访问控制
- - '##'
  - 游乐场
- - '##'
  - 属性
- - '##'
  - 计算属性
- - '##'
  - 属性观察者
- - '#'
  - 方法
- - '##'
  - 类方法
- - '##'
  - 参数名
- - '##'
  - 可选参数名
- - '##'
  - 参数名快捷方式
- - '##'
  - 默认参数值
- - '##'
  - 继承
- - '##'
  - 重写属性
- - '##'
  - 阻止继承
- - '##'
  - 对象创建
- - '##'
  - 子类初始化函数
- - '##'
  - 安全初始化
- - '##'
  - 便捷初始化函数
- - '##'
  - 初始化函数的继承
- - '##'
  - 使用闭包
- - '##'
  - 闭包快捷方式
- - '###'
  - 简写参数名称
- - '###'
  - 单表达式闭包
- - '##'
  - 尾随闭包
- - '##'
  - 闭包变量
- - '##'
  - 协议
- - '##'
  - 扩展
- - '#'
  - 扩展
- - '##'
  - 结构体
- - '##'
  - 元组
- - '##'
  - 枚举
- - '###'
  - 原始值
- - '##'
  - 关联值
- - '##'
  - 扩展枚举
- - '##'
  - 数值类型
- - '#'
  - 浮点数
- - '##'
  - 隐式类型转换
- - '##'
  - 数字字面量
- - '##'
  - 数字也是类型
- - '##'
  - 溢出和下溢
- - '##'
  - 字符串和字符
- - '###'
  - 字符串和字符字面量
- - '###'
  - Swift 字符串详解
- - '####'
  - 转义序列
- - '####'
  - Unicode
- - '####'
  - 字符串插值
- - '####'
  - 字符串即 NSString
- - '####'
  - 字符串拼接
- - '####'
  - 属性字符串
- - '##'
  - 集合
- - '##'
  - 控制语句
- - '#'
  - '`while` 循环'
- - '#'
  - '`for` 循环'
- - '###'
  - '`for` 循环简介'
- - '#'
  - '`switch` 语句'
- - '###'
  - 范围案例
- - '###'
  - 切换元组
- - '##'
  - 可选值
- - '##'
  - 使用可选值
- - '##'
  - 可选类型携带
- - '##'
  - 可选链
- - '##'
  - 可失败的初始化器
- - '##'
  - 隐式解包
- - '##'
  - 类型转换
- - '##'
  - 向下转型
- - '##'
  - 向下转型集合
- - '##'
  - 值 vs 引用 vs 常量 vs 变量
- - '##'
  - '`let`和`var`引用'
- - '##'
  - '`var`参数'
- - '##'
  - 值的引用（`inout`）
- - '##'
  - 使用 C 和 Objective-C
- - '###'
  - 无缝桥接
- - '###'
  - 方法签名
- - '#'
  - Swift 内存管理
- - '##'
  - 函数签名
- - '#'
  - 内存管理
- - '##'
  - 垃圾回收
- - '##'
  - 引用计数
- - '##'
  - 循环保留
- - '##'
  - 还有更多 Swift 特性
- - '#'
  - 总结
- - '##'
  - 第 21 章：框架搭建
- - '###'
  - 扩展
- - '###'
  - 创建扩展
- - '###'
  - 连接你的扩展
- - '###'
  - 运行你的 Action
- - '###'
  - 灯光，代码，Action
- - '###'
  - 每个扩展都是一座孤岛
- - '###'
  - 获取用户数据
- - '###'
  - 复用 Squeezer
- - '###'
  - 操作图标
- - '###'
  - 真正复用 Squeezer
- - '###'
  - 创建一个框架
- - '###'
  - 向框架添加代码
- - '###'
  - 与扩展共享框架
- - '#'
  - 摘要
- - '##'
  - 索引
- - '####'
  - B
- - '####'
  - C
