name: Learn SpriteBuilder for iOS game development
name_cn: iOS 游戏开发 SpriteBuilder 入门指南
slug: learn-spritebuilder-for-ios-game-development
toc:
- - '#'
  - 使用 SpriteBuilder 进行 iOS 游戏开发
- - '##'
  - 目录概览
- - '##'
  - 第一部分：介绍 SpriteBuilder 和 Cocos2D-iphone 第 3 版
- - '###'
  - 第 1 章：引言
- - '####'
  - 本书涵盖什么？
- - '####'
  - 本书适合谁？
- - '#####'
  - 绝对初学者
- - '#####'
  - 经验丰富的应用开发者
- - '#####'
  - 经验丰富的 Cocos2D 游戏开发者
- - '####'
  - 要求
- - '####'
  - 关于 SpriteBuilder
- - '####'
  - 为何使用 SpriteBuilder？
- - '####'
  - 关于 Cocos2D
- - '####'
  - 关于 Apportable
- - '####'
  - 关于程序版本
- - '####'
  - 关于 Xcode 版本
- - '####'
  - 关于示例项目
- - '####'
  - 示例项目与章节对照
- - '####'
  - 关于部署目标
- - '####'
  - 目录
- - '####'
  - 开始之前
- - '###'
  - 第 2 章：打下基础
- - '####'
  - 创建一个 SpriteBuilder 项目
- - '####'
  - SpriteBuilder 项目的 Xcode 项目
- - '####'
  - 第一个场景，第一段代码
- - '#####'
  - 创建 GameScene
- - '#####'
  - 查看节点库
- - '####'
  - 创建按钮
- - '####'
  - 分配按钮选择器
- - '####'
  - 更改启动场景
- - '####'
  - 为 GameScene 创建自定义类
- - '####'
  - 实现按钮选择器
- - '####'
  - 在按钮点击时切换场景
- - '####'
  - 创建关卡子文件节点
- - '#####'
  - 节点选择手柄
- - '#####'
  - 编辑节点属性
- - '#####'
  - 更改节点绘制顺序
- - '#####'
  - 排版后的文本
- - '#####'
  - 用渐变填充图层
- - '#####'
  - 创建子文件引用
- - '#####'
  - 添加玩家精灵
- - '#####'
  - 创建精灵表
- - '####'
  - 创建玩家预制体
- - '####'
  - 创建玩家预置体实例
- - '####'
  - 总结
- - '###'
  - 第 3 章：控制与滚动
- - '####'
  - 触摸即动：移动玩家
- - '#####'
  - 通过名称查找玩家节点
- - '#####'
  - 异常断点：关键的调试利器
- - '#####'
  - 分配关卡节点实例变量
- - '#####'
  - 使用 `CCActionMoveTo` 移动玩家
- - '####'
  - 滚动关卡
- - '#####'
  - 安排更新
- - '#####'
  - 向相反方向移动关卡节点
- - '####'
  - 视差滚动
- - '#####'
  - 添加背景 CCB
- - '#####'
  - 添加主背景精灵
- - '#####'
  - 处理图像
- - '#####'
  - 项目设置（Project Settings）
- - '######'
  - 音频质量
- - '######'
  - 屏幕模式
- - '######'
  - 方向
- - '#####'
  - 添加额外的背景层
- - '#####'
  - 为背景图形添加精灵表
- - '#####'
  - 设计背景层
- - '#####'
  - 总结
- - '###'
  - 第 4 章：物理与碰撞
- - '####'
  - 玩家物理
- - '#####'
  - 为玩家精灵启用物理
- - '#####'
  - 移动与旋转动作与物理引擎冲突
- - '#####'
  - 通过物理引擎移动玩家角色
- - '######'
  - 加速玩家角色
- - '######'
  - 列表 4-4 - 通过改变速度移动目标节点
- - '#####'
  - 对玩家施加速度限制
- - '#####'
  - 将设计值暴露为自定义属性
- - '#####'
  - 插曲：物理调试绘制
- - '####'
  - 碰撞回调方法
- - '#####'
  - 实现碰撞委托协议
- - '#####'
  - 碰撞类型与回调参数名称
- - '#####'
  - 使用类别和掩码忽略碰撞
- - '#####'
  - 让玩家离开
- - '######'
  - 创建出口节点
- - '######'
  - 实现出口碰撞回调
- - '####'
  - 小结
- - '###'
  - 第 5 章：时间线与触发器
- - '####'
  - 什么是时间线和关键帧？
- - '####'
  - 使用时间轴编辑器
- - '####'
  - 添加关键帧
- - '####'
  - 编辑动画设置
- - '#####'
  - 使用缓动函数让动画更平滑
- - '####'
  - 物理节点的关键帧动画
- - '####'
  - 添加齿轮和锯片
- - '#####'
  - 动画化齿轮和锯子
- - '#####'
  - 向关卡添加齿轮和锯子
- - '#####'
  - 如何不让动画自动播放
- - '######'
  - 编辑时间线以取消自动播放
- - '#####'
  - 以编程方式播放动画
- - '#####'
  - 动画播放完成回调
- - '#####'
  - 区分不同动画
- - '#####'
  - 在碰撞时触发动画
- - '######'
  - 向关卡添加触发目标
- - '######'
  - 创建触发 CCB
- - '####'
  - 排版后的文档
- - '#####'
  - 向关卡添加触发器
- - '#####'
  - 创建 Trigger 类
- - '#####'
  - 编程 Trigger 类
- - '######'
  - 初始化触发器和目标数组
- - '######'
  - 查找触发器与目标
- - '######'
  - 查找并存储触发器
- - '######'
  - NSPointerArray 与触发/目标管理
- - '######'
  - 使用 NSPointerArray 设置触发器
- - '######'
  - 查找并存储目标
- - '######'
  - 将触发事件转发给目标
- - '######'
  - 清理触发器和目标
- - '######'
  - 通知触发器处理碰撞
- - '######'
  - 触发目标节点
- - '######'
  - 避免“物理空间已锁定”错误
- - '####'
  - 总结
- - '###'
  - 第 6 章：菜单与弹出视图
- - '####'
  - 静态游戏内菜单
- - '#####'
  - 添加菜单图形
- - '#####'
  - 添加静态游戏菜单层
- - '#####'
  - 使用参考角点对齐按钮
- - '#####'
  - 编辑按钮属性
- - '######'
  - CCControl 属性
- - '######'
  - CCButton 属性
- - '#####'
  - 视觉高亮的另一种选择
- - '#####'
  - '`CCLabelTTF`属性'
- - '#####'
  - 分配按钮选择器
- - '#####'
  - 分配`GameMenuLayer`类和实例变量
- - '#####'
  - 编程实现`GameMenuLayer`
- - '######'
  - 实现并确认代码连接
- - '#####'
  - 为`GameMenuLayer`分配`GameScene`引用
- - '####'
  - 显示和移除弹出菜单
- - '#####'
  - 暂停游戏
- - '#####'
  - 创建暂停菜单弹出窗口
- - '#####'
  - 幕间：全屏弹出窗口
- - '#####'
  - 在恢复时为暂停菜单添加动画效果
- - '#####'
  - 插曲：当应用进入后台时暂停游戏
- - '#####'
  - 击杀玩家
- - '######'
  - 创建“游戏结束”弹出视图
- - '#####'
  - 显示“游戏结束”弹出层
- - '#####'
  - 插曲：修复初始滚动位置
- - '####'
  - 总结
- - '##'
  - 第二部分：在 SpriteBuilder 中正式开始工作
- - '###'
  - 第 7 章：主场景与游戏状态
- - '####'
  - 主场景背景
- - '#####'
  - 设计背景图片
- - '#####'
  - 设计背景 CCB
- - '#####'
  - 背景动画
- - '######'
  - 尝试强化此动画效果
- - '####'
  - 通过菜单启动
- - '####'
  - 主场景徽标和按钮
- - '#####'
  - 设计徽标和按钮
- - '#####'
  - 制作徽标和按钮的动画
- - '#####'
  - 编辑入场动画
- - '#####'
  - 用普通精灵创建按钮
- - '#####'
  - 连接按钮
- - '####'
  - 设置菜单
- - '#####'
  - 使用 Box Layout 设计设置菜单
- - '#####'
  - 介绍 Box Layout 节点
- - '#####'
  - 盒子布局的对齐与间距问题
- - '#####'
  - 使用盒子布局实现左对齐
- - '#####'
  - 使用盒子布局实现居中对齐
- - '#####'
  - 更改滑块视觉效果
- - '#####'
  - 默认滑块样式调整
- - '#####'
  - 连接滑块
- - '#####'
  - 关闭设置弹出窗口
- - '####'
  - 持久化游戏状态
- - '#####'
  - 引入 GameState 类
- - '#####'
  - 持久化滑块值
- - '####'
  - 总结
- - '###'
  - 第 8 章：选择和解锁关卡
- - '####'
  - 添加内容节点
- - '####'
  - 添加滚动视图节点
- - '####'
  - 显示滚动视图弹出框
- - '####'
  - 设计滚动视图内容节点
- - '####'
  - 解锁关卡
- - '####'
  - 高亮关卡按钮
- - '#####'
  - 关闭关卡选择弹出窗口
- - '#####'
  - 加载关卡
- - '#####'
  - 添加一个虚拟关卡
- - '#####'
  - 通关关卡
- - '####'
  - 添加更多关卡
- - '#####'
  - 统计关卡文件数量
- - '####'
  - 显示正确的关卡选择页面
- - '####'
  - 实现 Scroll View 委托方法
- - '####'
  - 总结
- - '###'
  - 第 9 章：物理关节
- - '####'
  - 什么是关节？
- - '####'
  - 关节的类型
- - '####'
  - 创建链条
- - '#####'
  - 设置链条精灵
- - '#####'
  - 为链条添加枢轴关节
- - '######'
  - 编辑通用关节属性
- - '######'
  - 编辑枢轴关节属性
- - '#####'
  - 连接链条元素
- - '####'
  - 创建绳索
- - '#####'
  - 将链条变成绳索
- - '####'
  - 向关卡中添加绳索与链条
- - '####'
  - 修复链条和绳索的碰撞问题
- - '####'
  - 最小化物理体“爆炸”的风险
- - '#####'
  - 定义碰撞类别
- - '#####'
  - 编辑碰撞类别和遮罩
- - '#####'
  - 碰撞行为的变化
- - '####'
  - 创建跳板
- - '#####'
  - 原理相同：弹簧、弹弓和弓
- - '####'
  - 设计跳板
- - '####'
  - 为跳板添加关节
- - '#####'
  - 弹簧板实现指南
- - '#####'
  - 设置静止长度
- - '#####'
  - 首次测试弹簧板
- - '#####'
  - 阻止弹簧的运动
- - '#####'
  - 添加弹簧锁
- - '#####'
  - 释放弹簧锁
- - '####'
  - 关节断裂与电机
- - '#####'
  - 断裂力示例
- - '#####'
  - 马达示例
- - '####'
  - 总结
- - '###'
  - 第 10 章：可变形物理
- - '####'
  - 刚体 vs. 可变形体
- - '####'
  - 配置软体玩家
- - '#####'
  - 创建新的玩家 CCB
- - '#####'
  - 添加中心和圆周主体
- - '#####'
  - 查找圆周上的点
- - '#####'
  - 定位圆周上的节点
- - '####'
  - 移动和绘制软体玩家角色
- - '#####'
  - 移动软体玩家角色
- - '####'
  - 设置顶点与纹理坐标
- - '#####'
  - 计算纹理坐标
- - '#####'
  - 不裁剪精灵表单精灵
- - '#####'
  - 使用 CCRenderer 绘制纹理
- - '#####'
  - for 循环用于遍历每一个子节点，以便为当前帧创建顶点位置。
- - '####'
  - 温柔地玩耍……
- - '####'
  - 连接圆周上的身体
- - '####'
  - 增加玩家的弹性
- - '####'
  - 改进软体角色
- - '#####'
  - 连接中心节点
- - '#####'
  - 改进软体角色
- - '#####'
  - 改进纹理渲染
- - '###'
  - 第 11 章：音频与字体（推断章节）
- - '####'
  - Cocos2D 音频框架
- - '####'
  - 在 SpriteBuilder 中使用音频文件
- - '#####'
  - 将音频导入 SpriteBuilder
- - '#####'
  - 通过时间线播放音效
- - '######'
  - 短时间不重复播放音效
- - '######'
  - 调整音频音量
- - '######'
  - 处理标签
- - '####'
  - SpriteBuilder 中的自定义 TrueType 字体
- - '#####'
  - 导入自定义 TrueType 字体
- - '#####'
  - 编辑标签属性
- - '#####'
  - 添加版权声明字符串
- - '#####'
  - 本地化积分标签
- - '#####'
  - 本地化注意事项
- - '#####'
  - TrueType 字体 vs. 位图字体
- - '#####'
  - 创建和导入位图字体
- - '#####'
  - 使用位图字体
- - '####'
  - 总结
- - '###'
  - 第 12 章：视觉效果与动画
- - '####'
  - 精灵帧动画
- - '#####'
  - 创建精灵帧动画
- - '#####'
  - 第一与第五关键帧
- - '#####'
  - 为 SoftBodyDrawNode 添加精灵帧动画
- - '#####'
  - 比较精灵帧
- - '####'
  - 粒子效果
- - '#####'
  - 粒子效果的局限性
- - '####'
  - 编辑粒子系统参数
- - '#####'
  - 粒子发射器属性详解
- - '####'
  - 着色器效果
- - '#####'
  - 添加效果节点
- - '#####'
  - 可用效果
- - '#####'
  - 着色器效果最佳实践
- - '####'
  - 总结
- - '###'
  - 第 13 章：移植到安卓
- - '####'
  - 安卓支持是如何工作的？
- - '####'
  - 安装 Android Xcode 插件
- - '####'
  - Android 开发先决条件
- - '#####'
  - 安装 Android SDK 是可选的
- - '#####'
  - Android 设备是必需的
- - '#####'
  - 通过 USB 连接 Android 设备
- - '#####'
  - 启用开发者选项
- - '#####'
  - 启用 USB 调试
- - '#####'
  - 启用保持唤醒
- - '#####'
  - 启用 OpenGL 堆栈跟踪
- - '####'
  - 确认部署到 Android
- - '#####'
  - 创建新的 SpriteBuilder 项目
- - '#####'
  - 选择 Scheme 和目标平台
- - '#####'
  - 构建、运行、传输、启动
- - '####'
  - 故障排除
- - '####'
  - 转换 Bouncy Beast
- - '#####'
  - 修复编译器错误
- - '#####'
  - 修复启动问题
- - '#####'
  - 修复布局问题
- - '#####'
  - 隔离问题
- - '####'
  - 何时移植到 Android
- - '#####'
  - 在 iOS 上发布后进行移植
- - '####'
  - 调试与最佳实践
- - '#####'
  - 从一开始就采用跨平台方案
- - '####'
  - 小结
- - '###'
  - 第 14 章：调试与最佳实践
- - '####'
  - 记录消息与变量
- - '####'
  - 添加异常断点（Xcode 5）
- - '####'
  - 断言假设
- - '####'
  - 添加断点
- - '####'
  - 分析代码
- - '####'
  - Cocos2D 帧率统计
- - '####'
  - 遍历场景图
- - '####'
  - 调试建议
- - '#####'
  - 常见问题
- - '#####'
  - nil 引用
- - '#####'
  - 节点名称检查
- - '#####'
  - 动画播放问题
- - '######'
  - 动画只播放一次但不循环
- - '######'
  - 动画未播放音效或未执行回调
- - '#####'
  - 音频播放问题
- - '#####'
  - 为精灵 CCB 类子类化 CCSprite
- - '#####'
  - 无法编辑自定义类字段
- - '#####'
  - 无法向节点添加自定义属性
- - '#####'
  - 物理碰撞未按预期工作
- - '#####'
  - 节点未释放
- - '####'
  - 总结
- - '##'
  - 索引
- - '###'
  - 导航区
- - '###'
  - 精灵帧动画
