name: Beginning Iphone and Ipad Web Apps
name_cn: iPhone 和 iPad Web 应用入门指南
slug: beginning-iphone-and-ipad-web-apps
toc:
- - '#'
  - 为 iOS 设备创建自定义网站和 Web 应用程序
- - '##'
  - iPhone 与 iPad Web 应用入门
- - '###'
  - 使用 HTML5、CSS3 和 JavaScript 进行脚本编写
- - '##'
  - 内容概览
- - '##'
  - 作者简介
- - '##'
  - 技术审校简介
- - '##'
  - 致谢
- - '##'
  - 引言
- - '###'
  - 本书读者对象
- - '###'
  - 你需要了解什么
- - '###'
  - 本书内容
- - '###'
  - 你准备好了吗？
- - '#'
  - 第一部分：Web 应用开发入门
- - '##'
  - 第 1 章：开发工具
- - '###'
  - 源代码编辑器
- - '####'
  - 科莫多巨蜥
- - '####'
  - 让自己舒适
- - '####'
  - Dashcode 怎么样？
- - '###'
  - 使用正确的浏览器
- - '####'
  - WebKit
- - '####'
  - Gecko 和 Firefox
- - '####'
  - Opera
- - '####'
  - 迷航的 Internet Explorer
- - '###'
  - 从 Web 角度进行开发
- - '####'
  - Acid...Acid...Acid
- - '####'
  - HTML5 一致性
- - '####'
  - 浏览器中的卫星
- - '###'
  - 针对 iOS 进行开发
- - '####'
  - 使用 iPhone 和 iPad 模拟器
- - '####'
  - 无论如何使用真实设备
- - '####'
  - ADC 是你的朋友
- - '##'
  - 摘要
- - '##'
  - 第 2 章：开发环境
- - '###'
  - 提供 Web 应用程序服务
- - '###'
  - Mac OS，化繁为简
- - '####'
  - 在你的 Mac 中嵌入 Apache
- - '####'
  - 脚本引擎
- - '###'
  - Windows，选择你的武器
- - '####'
  - 一体化安装流程
- - '###'
  - 主机数据库
- - '###'
  - localhost 用于配置回环接口
- - '###'
  - 系统启动时使用。请勿更改此条目。
- - '###'
  - 基于 Windows 的系统
- - '###'
  - 配置多个网站
- - '###'
  - Apache 2：深入探索
- - '####'
  - 检查配置
- - '####'
  - 确保 Apache 监听 80 端口
- - '####'
  - 在所有 IP 地址上监听虚拟主机请求
- - '####'
  - 配置你的第一个虚拟主机
- - '###'
  - Windows 的情况
- - '###'
  - 你成功了吗？
- - '###'
  - 全力提升可及性
- - '##'
  - 你一定做到了！
- - '##'
  - 第 3 章：开发者与调试工具简介
- - '###'
  - 与 WebKit 的开发者工具交朋友
- - '###'
  - 启用开发菜单
- - '###'
  - 探秘开发菜单
- - '###'
  - 在 Mobile Safari 上开发
- - '###'
  - Web Inspector 概览
- - '####'
  - 开发者工具窗口
- - '###'
  - 错误通知
- - '###'
  - 掌控你的代码
- - '###'
  - 开始使用元素检查器
- - '####'
  - 让文档属于你
- - '####'
  - 挖掘你的样式
- - '####'
  - 编辑样式
- - '####'
  - 度量（Metrics）
- - '####'
  - 属性（Properties）
- - '####'
  - 事件监听器
- - '####'
  - 高级搜索
- - '###'
  - 调试 JavaScript
- - '####'
  - 日志记录到控制台
- - '####'
  - '`inspector` 与 `console.log()` 对 HTML 元素的操作方式类似。'
- - '####'
  - '`console.trace()`'
- - '####'
  - '`inspect(object)`'
- - '####'
  - '`console.profile(name)`'
- - '####'
  - '`console.profileEnd(name)`'
- - '###'
  - 表 3-2：格式化选项
- - '###'
  - 使用交互式 Shell
- - '###'
  - 让调试器来完成工作
- - '####'
  - 断点
- - '####'
  - 单步执行
- - '###'
  - 监视表达式
- - '###'
  - 调用栈
- - '###'
  - 作用域变量
- - '###'
  - 异常
- - '###'
  - 页面的生命周期
- - '###'
  - 分析脚本
- - '###'
  - 本节仅在您首次打开时显示操作说明
- - '###'
  - 了解性能分析
- - '###'
  - 使用搜索字段进行过滤
- - '###'
  - 客户端数据存储
- - '####'
  - 数据库存储
- - '####'
  - Cookie
- - '####'
  - 其他存储功能
- - '###'
  - 审核你的页面
- - '###'
  - 仍然不确定？
- - '##'
  - 总结
- - '#'
  - 第二部分：使用 HTML5 和 CSS3 进行 Web 应用设计
- - '##'
  - 第 4 章：Web 应用程序的剖析
- - '###'
  - 移动互联网的早期发展
- - '###'
  - iPhone 革命
- - '###'
  - 对 Web 应用的信念
- - '###'
  - 什么是 Web 应用？
- - '###'
  - 下载自 Wow! eBook <www.wowebook.com>
- - '###'
  - 应用星球：谁主沉浮
- - '###'
  - 跨平台大师
- - '###'
  - 硬件访问不再是禁区的武器
- - '###'
  - 解放你的内容
- - '###'
  - 发布模式
- - '###'
  - 网络应用：不再是小朋友
- - '###'
  - 移动 Safari 上的网络应用
- - '###'
  - 掌握浏览器
- - '###'
  - 浏览器指标
- - '###'
  - 思考“网络应用”
- - '###'
  - 配置视口
- - '###'
  - 认真做应用：使用独立模式
- - '####'
  - 展示一个合适的图标
- - '###'
  - 全屏运行您的应用
- - '###'
  - 一个很棒的启动画面
- - '###'
  - 调整状态栏
- - '###'
  - 保持在独立模式
- - '###'
  - 构建您的第一个 Web 应用基础项目
- - '###'
  - 在 Komodo Edit 中创建文档模板
- - '###'
  - 隐藏 Mobile Safari 的地址栏
- - '###'
  - Mobile Safari
- - '###'
  - 处理屏幕方向变化
- - '###'
  - 此功能仅在 iPad 上可实现。对于其他设备，最佳实践是使用 JavaScript 在 `<body>` 标签上添加一个类或 ID，以便在屏幕方向改变时应用不同的样式。
- - '###'
  - 最终润色
- - '###'
  - 准备就绪
- - '##'
  - 第 5 章：用户体验与界面设计指南
- - '###'
  - 从桌面网页到移动网页
- - '###'
  - 忘掉桌面隐喻
- - '###'
  - 改变导航习惯
- - '###'
  - 精心展示广告
- - '###'
  - 让用户自行决定
- - '###'
  - 简洁性与易用性
- - '###'
  - 避免杂乱
- - '###'
  - 用户界面
- - '####'
  - 适应触控
- - '####'
  - 适应尺寸
- - '###'
  - 避免不必要的交互
- - '###'
  - 善用新型输入类型
- - '###'
  - 审慎对待用户输入信息
- - '###'
  - 避免增加操作步骤
- - '###'
  - 核心理念：专注
- - '###'
  - 实现响应式设计
- - '###'
  - 让你的 Web 应用响应迅速
- - '###'
  - 让你的 Web 应用具有交互反馈
- - '###'
  - iOS 界面设计最佳实践
- - '####'
  - 适应性
- - '####'
  - 列表与图标方法
- - '###'
  - 列表
- - '####'
  - 基本边到边列表
- - '####'
  - 圆角边框列表
- - '####'
  - 图标网格显示
- - '###'
  - 考虑 UI 替代方案
- - '###'
  - 模仿 iOS UI
- - '###'
  - 构建 iPad 体验
- - '####'
  - 不是笔记本电脑，也不是 iPhone
- - '###'
  - 勇于创新
- - '##'
  - 总结
- - '##'
  - 第 6 章：用于网页应用用户界面的有趣 CSS 特性
- - '###'
  - 用 CSS 提升用户体验
- - '####'
  - 用户反馈
- - '####'
  - 禁用复制/粘贴功能
- - '####'
  - 控制弹出菜单
- - '###'
  - 选择器
- - '####'
  - 可用 CSS 选择器概述
- - '####'
  - 位置相关选择器：结构伪类
- - '###'
  - 背景的高级处理
- - '###'
  - 背景的原点
- - '###'
  - 全局背景裁剪
- - '####'
  - 上一节中解释的设计优势同样适用于下一个属性 `background-clip`。虽然背景的“原点”仅影响背景图像，但 `background-clip` 属性允许你通过定义背景绘制区域，为所有背景元素（即图像和颜色）设定规则。
- - '###'
  - 基于文本的背景剪裁
- - '###'
  - 背景尺寸调整
- - '###'
  - 开发类似照片应用的照片墙
- - '####'
  - 解析指定文件夹并返回收集到的文件数组
- - '####'
  - 将 PHP 数组转换为 JavaScript 数组
- - '###'
  - 多层背景
- - '###'
  - 颜色
- - '####'
  - Alpha 通道
- - '####'
  - 新的颜色定义
- - '####'
  - 使用渐变
- - '####'
  - 基本语法
- - '####'
  - 改变渐变的尺寸
- - '####'
  - 完整的渐变语法
- - '####'
  - 高级颜色处理
- - '###'
  - 盒与边框
- - '####'
  - 盒尺寸
- - '####'
  - 圆角盒角
- - '####'
  - 用图片绘制边框
- - '####'
  - 阴影
- - '####'
  - 盒阴影
- - '####'
  - 文本阴影
- - '####'
  - 带有阴影和轮廓的文本效果
- - '####'
  - 为你的头部添加按钮
- - '##'
  - 第 12 章：Ajax 与动态内容
- - '###'
  - 使用 cURL API 处理请求。
- - '###'
  - 如果没有有效内容，则发送 HTTP 500 错误响应。
- - '###'
  - JSONP 方式
- - '####'
  - 我们有回调，处理 JSONP 行为
- - '####'
  - 没有回调，发送经典 JSON 内容
- - '####'
  - 从数据库或其他地方请求数据...
- - '###'
  - 跨域资源共享
- - '###'
  - 实际案例：显示 Twitter 趋势
- - '####'
  - Twitter 趋势订阅源
- - '####'
  - 获取并渲染数据
- - '###'
  - 善待等待中的用户
- - '####'
  - 添加视觉反馈
- - '###'
  - 处理过长的等待时间
- - '##'
  - 小结
- - '##'
  - 第 13 章：使用触摸和手势事件
- - '###'
  - 如何处理事件
- - '####'
  - 处理程序的调用优先级
- - '###'
  - 捕获阶段
- - '####'
  - 表 13-1. 不同事件阶段使用的常量
- - '###'
  - 控制事件传播
- - '###'
  - 阻止默认行为
- - '###'
  - 处理函数和对象方法
- - '###'
  - Mobile Safari 中的经典事件
- - '####'
  - 鼠标事件的行为
- - '###'
  - 触摸事件与多点触控
- - '####'
  - 滚动信息
- - '###'
  - 多点触控事件
- - '####'
  - 新的交互过程
- - '###'
  - 处理多点触控事件
- - '###'
  - 无限触点
- - '###'
  - 被取消的触摸事件
- - '###'
  - 基于触摸与变换构建的页面视图
- - '####'
  - 我们将要做什么
- - '####'
  - 容器
- - '####'
  - 引入元素与交互
- - '####'
  - 创建自定义事件
- - '####'
  - 处理自定义事件
- - '###'
  - 使用预计算手势
- - '###'
  - 创建你自己的手势
- - '####'
  - 一个代码，多种笔画
- - '###'
  - 边界框对象
- - '###'
  - 记录用户笔画
- - '###'
  - 使用`Recognizer`对象
- - '###'
  - 提高精确度
- - '##'
  - 总结
- - '##'
  - 第 14 章：位置感知的 Web 应用程序
- - '###'
  - 地理定位 API
- - '####'
  - 隐私注意事项
- - '####'
  - 设置注意事项
- - '####'
  - 获取当前位置
- - '####'
  - 经度、纬度等
- - '###'
  - 处理请求中的错误
- - '###'
  - 精度、超时和缓存位置
- - '###'
  - 使用 Google 地图将用户定位在地图上
- - '####'
  - 显示地图
- - '###'
  - 表 14-3. 可用的地图显示模式
- - '###'
  - 将地图居中于用户位置
- - '###'
  - 标记用户位置
- - '###'
  - 显示精确度
- - '####'
  - 遵循与标记器相同的原则
- - '###'
  - 追踪用户位置
- - '####'
  - 注册更新
- - '####'
  - 观察者的特定行为
- - '####'
  - 在 Google 地图上观察位置
- - '###'
  - 从数据到数学
- - '####'
  - 两点之间的距离
- - '####'
  - 更精确的两点间距离
- - '####'
  - 行进方向
- - '###'
  - 构建指南针 Web 应用
- - '####'
  - 创建移动元素
- - '###'
  - 刻度盘
- - '###'
  - 指针
- - '###'
  - 刻度盘光泽
- - '###'
  - 渲染罗盘
- - '###'
  - 向文档中添加元素
- - '###'
  - 准备文档以接收位置数据
- - '###'
  - 使用位置数据
- - '###'
  - 为罗盘添加动画效果
- - '###'
  - 防止指针晃动
- - '##'
  - 总结
- - '##'
  - 第 15 章：更优的客户端数据存储处理方案
- - '###'
  - 不同的存储区域
- - '###'
  - 如何使用新的存储能力
- - '###'
  - '`sessionStorage` 的特定行为'
- - '###'
  - 监听存储区域修改通知
- - '###'
  - 安全与隐私考量
- - '###'
  - 缓存 Ajax 请求
- - '####'
  - 基础文档
- - '####'
  - 添加缓存功能
- - '###'
  - 修改函数
- - '###'
  - 会话存储作为第一级缓存
- - '###'
  - 使用缓存
- - '###'
  - 将客户端数据发送到服务器
- - '###'
  - SQL 本地数据库
- - '###'
  - 打开数据库
- - '####'
  - 创建表
- - '###'
  - '`createSchema(transaction);`'
- - '###'
  - 向表中添加数据
- - '###'
  - 从表中查询数据
- - '####'
  - 表 15-2.*SQLResultSet* 对象的属性
- - '####'
  - 图 15–4：在桌面版 Safari 的 Web Inspector 中由 SQL 查询生成的新闻列表
- - '###'
  - 使用数据库代替存储
- - '###'
  - 处理事务和查询错误
- - '####'
  - 表 15–3：适用于事务和查询的错误码
- - '###'
  - 使用版本控制维护一致的数据访问
- - '###'
  - 删除数据库
- - '####'
  - 在桌面版 Safari 中
- - '####'
  - 在移动版 Safari 中
- - '###'
  - 安全再探讨
- - '###'
  - 离线网页应用缓存
- - '####'
  - 工作原理是什么？
- - '####'
  - 清单文件
- - '####'
  - 使用缓存清单实现离线 Web 应用
- - '###'
  - CACHE 部分
- - '####'
  - 我们的缓存资源
- - '###'
  - NETWORK 部分
- - '###'
  - FALLBACK 部分
- - '###'
  - 使用 JavaScript 控制缓存
- - '###'
  - 响应应用程序缓存发送的事件
- - '###'
  - 删除缓存
- - '###'
  - 用户是否在线？
- - '####'
  - 除了此属性外，移动版 Safari 还支持两个新事件：当网络状态发生变化时，会发送 `online` 事件（若 `onLine` 属性从 `false` 变为
    `true`）或 `offline` 事件（用户断开连接）。这能让您精细调节应用的加载和行为，以实现最佳用户体验。
- - '##'
  - 总结
- - '#'
  - 索引
- - '##'
  - A
- - '##'
  - C
- - '##'
  - D
- - '##'
  - G
- - '##'
  - F
- - '##'
  - M
- - '###'
  - MooTools 框架
- - '###'
  - 获取视频信息
- - '###'
  - “更多”按钮
- - '###'
  - 鼠标事件
- - '###'
  - moveNodes() 方法
- - '###'
  - moveSlides() 函数
- - '###'
  - moveTo() 方法
- - '##'
  - MP3
- - '##'
  - MPEG-4
- - '##'
  - 多层
- - '##'
  - 多媒体
- - '##'
  - 多点触控事件
- - '##'
  - MVC
- - '##'
  - myTimer() 函数
- - '##'
  - N
- - '###'
  - N（续）
- - '###'
  - 中野
- - '###'
  - 原生风格特性
- - '##'
  - 安全性
- - '##'
  - V
- - '##'
  - U
- - '##'
  - R
- - '##'
  - V
- - '##'
  - W
- - '##'
  - X, Y
- - '##'
  - Z
