name: Taking Your iPad 2 to the Max
name_cn: iPad 2 极致活用指南
slug: taking-your-ipad-2-to-the-max
toc:
- - '##'
  - 目录速览
- - '#'
  - 目录
- - '#'
  - 排版后内容
- - '##'
  - 关于作者
- - '##'
  - 关于技术审校
- - '#'
  - 引言
- - '##'
  - 第 1 章：将你的 iPad 带回家
- - '###'
  - 挑选你的 iPad
- - '####'
  - Wi-Fi 还是 Wi-Fi + 3G？
- - '####'
  - GSM vs. CDMA
- - '###'
  - 存储容量有多大？
- - '###'
  - 应该购买二手 iPad 吗？
- - '###'
  - 考虑系统需求
- - '###'
  - 购买你的 iPad
- - '###'
  - 在线购买你的 iPad
- - '###'
  - 维修、退货、保修、AppleCare 和保险
- - '###'
  - 拆箱你的 iPad
- - '###'
  - iPad 功能概览
- - '###'
  - 准备设置
- - '###'
  - 将 iPad 连接到电脑
- - '###'
  - 同步你的新 iPad
- - '###'
  - 为你的 iPad 配备配件
- - '###'
  - 总结
- - '##'
  - 第 2 章：将数据和媒体放入 iPad
- - '###'
  - 使用 iTunes
- - '###'
  - iPad 的 iTunes 设置面板
- - '####'
  - 关于同步数据的一点说明
- - '####'
  - 从哪里获取媒体内容？
- - '####'
  - 记得应用你的更改
- - '###'
  - 选项卡
- - '####'
  - 摘要选项卡
- - '#####'
  - iPad 信息框
- - '#####'
  - 版本框
- - '####'
  - 选项面板
- - '#####'
  - 信息标签
- - '######'
  - 同步通讯录
- - '######'
  - 同步 iCal 日历
- - '######'
  - 同步邮件账户
- - '######'
  - 其他
- - '######'
  - 高级
- - '#####'
  - 应用标签
- - '#####'
  - 同步应用
- - '#####'
  - 文件共享
- - '#####'
  - 音乐选项卡
- - '######'
  - 影片标签页
- - '######'
  - 电视节目标签页
- - '######'
  - 播客标签页
- - '######'
  - iTunes U 标签页
- - '######'
  - “图书”标签页
- - '######'
  - “照片”标签页
- - '#####'
  - iTunes 设备设置
- - '######'
  - 恢复
- - '###'
  - 总结
- - '##'
  - 第 3 章：探索 iPad 硬件
- - '###'
  - iPad 的各个部件
- - '####'
  - 开/关 睡眠/唤醒 按钮
- - '####'
  - 静音/屏幕旋转锁定
- - '####'
  - 音量开关
- - '####'
  - 扬声器
- - '####'
  - 基座接口端口
- - '####'
  - 主屏幕按钮
- - '####'
  - 耳机插孔
- - '####'
  - 麦克风
- - '####'
  - Micro-SIM 卡槽（仅限 Wi-Fi + 3G iPad）
- - '###'
  - iPad 的保养与维护
- - '####'
  - 保护壳
- - '####'
  - 保护套
- - '####'
  - 包袋
- - '####'
  - 机身贴膜
- - '####'
  - 书本式保护壳
- - '####'
  - 电池保养
- - '#####'
  - iPad 电池保养技巧
- - '####'
  - 屏幕保养
- - '#####'
  - 热量：iPad 的头号敌人
- - '###'
  - Apple iPad 配件
- - '####'
  - Smart Cover
- - '####'
  - iPad 2 底座
- - '####'
  - iPad 相机连接套件
- - '####'
  - iPad 10W USB 电源适配器
- - '####'
  - Apple VGA 适配器
- - '####'
  - Apple 数字影音适配器
- - '####'
  - Apple 复合及色差影音线缆
- - '####'
  - Apple 无线键盘
- - '####'
  - Apple 带遥控和麦克风的耳机
- - '####'
  - Apple 带遥控和麦克风的入耳式耳机
- - '###'
  - 摘要
- - '##'
  - 第 4 章：与 iPad 交互
- - '###'
  - 交互基础
- - '####'
  - iPad 语言
- - '####'
  - 方向
- - '###'
  - 锁定屏幕
- - '###'
  - 主屏幕
- - '####'
  - 操控主屏幕
- - '####'
  - 多任务与后台应用管理
- - '#####'
  - 彻底关闭应用
- - '#####'
  - 强制退出应用
- - '####'
  - 聚焦搜索
- - '#####'
  - 聚焦搜索设置
- - '###'
  - iPad 设置
- - '###'
  - 键盘
- - '####'
  - 更多键盘
- - '####'
  - 入门指南
- - '####'
  - iPad 打字技巧
- - '#####'
  - 缩略形式
- - '#####'
  - 标点符号
- - '#####'
  - 重音符号
- - '#####'
  - 大写锁定
- - '#####'
  - 单词删除
- - '#####'
  - 自动大写
- - '###'
  - 拷贝与粘贴
- - '###'
  - 撤销与重做
- - '###'
  - 辅助功能
- - '####'
  - 旁白
- - '####'
  - 缩放
- - '####'
  - 大文本
- - '####'
  - 白底黑字
- - '####'
  - 单声道音频
- - '####'
  - 自动朗读文本
- - '####'
  - 连按三次主屏幕按钮
- - '###'
  - 本章小结
- - '##'
  - 第 5 章：连接互联网
- - '###'
  - 连接 Wi-Fi
- - '####'
  - 认证与加密
- - '####'
  - 设置 Wi-Fi
- - '####'
  - 解决 Wi-Fi 连接问题
- - '#####'
  - 没有显示网络名称
- - '#####'
  - “输入密码”屏幕中的“加入”按钮呈灰色
- - '#####'
  - 你刚刚设置了 Wi-Fi 路由器，但不知道密码
- - '#####'
  - 信号强度只有一格，或者看不到你的 Wi-Fi 网络
- - '#####'
  - 你在公共场所，一个网页要求你登录网络
- - '#####'
  - 你的 Wi-Fi 连接显示满格信号，但无法连接到互联网
- - '#####'
  - 所有 Wi-Fi 网络都具有相同的名称
- - '#####'
  - 以上解决方案均无效
- - '####'
  - 特殊 Wi-Fi 设置
- - '###'
  - 通过 3G 连接
- - '####'
  - 设置 3G
- - '####'
  - 数据漫游
- - '####'
  - 更改账户信息或增加数据流量
- - '####'
  - 飞行模式
- - '###'
  - 内置 3G 的替代方案
- - '###'
  - 本章小结
- - '##'
  - 第 6 章：使用 Safari 浏览互联网
- - '###'
  - Safari 入门指南
- - '###'
  - Safari 浏览器窗口
- - '###'
  - 导航基础
- - '####'
  - 输入 URL
- - '####'
  - 输入文本
- - '####'
  - 搜索网页
- - '####'
  - 在网页中搜索文本
- - '####'
  - 跟随链接
- - '####'
  - 改变方向
- - '####'
  - 滚动、缩放及其他浏览技巧
- - '####'
  - 页面管理
- - '####'
  - 使用书签
- - '#####'
  - 选择书签
- - '#####'
  - 编辑书签
- - '#####'
  - 保存书签和共享网页
- - '###'
  - Safari 设置
- - '###'
  - iPad 与 Flash 视频
- - '###'
  - 总结
- - '##'
  - 第 7 章：掌控你的音乐与视频
- - '###'
  - 在 iPad 上观看视频
- - '###'
  - 视频播放
- - '###'
  - 视频 App
- - '####'
  - 播放视频
- - '####'
  - 删除视频
- - '###'
  - 视频设置
- - '###'
  - YouTube
- - '####'
  - 浏览和查找 YouTube 视频
- - '####'
  - 观看 YouTube 视频
- - '#####'
  - 管理视频：评分、分享等
- - '####'
  - YouTube 使用技巧
- - '###'
  - 在 Safari 浏览器中观看网页视频
- - '###'
  - 视频配件
- - '####'
  - 投影视频
- - '###'
  - 在 iPad 上听音乐
- - '####'
  - 浏览音乐资料库和播放列表
- - '####'
  - 其他歌曲控制选项
- - '####'
  - 从音乐资料库和播放列表播放音频
- - '####'
  - “正在播放”屏幕
- - '#####'
  - 标题栏
- - '#####'
  - 专辑封面
- - '#####'
  - 底部横条
- - '####'
  - 专辑视图
- - '####'
  - 创建播放列表
- - '#####'
  - 创建播放列表
- - '#####'
  - 编辑播放列表
- - '####'
  - 创建 Genius 播放列表
- - '####'
  - 编辑 Genius 播放列表
- - '####'
  - 播放 Genius 混合曲
- - '####'
  - 播放播客、有声读物和 iTunes U 课程
- - '####'
  - “正在播放”屏幕
- - '####'
  - 搜索
- - '####'
  - 在其他应用中显示音乐播放控制
- - '####'
  - iPod 应用设置
- - '####'
  - 设置家庭共享
- - '###'
  - 总结
- - '##'
  - 第 8 章：购买应用、书籍、音乐等更多内容
- - '###'
  - App Store
- - '####'
  - 精选应用
- - '####'
  - 新品
- - '####'
  - 热门推荐
- - '####'
  - 按发布日期
- - '####'
  - 排行榜
- - '####'
  - 类别
- - '####'
  - 搜索
- - '####'
  - 更新
- - '###'
  - iTunes Store
- - '####'
  - 精选内容
- - '####'
  - 流派与类别
- - '####'
  - 影片租赁
- - '####'
  - 季票
- - '####'
  - 高清 vs. 标清
- - '####'
  - 排行榜
- - '####'
  - Genius 功能
- - '###'
  - iBookstore
- - '####'
  - 精选
- - '####'
  - 纽约时报
- - '####'
  - 排行榜
- - '###'
  - 购买记录
- - '###'
  - 本章小结
- - '##'
  - 第 9 章：使用 iBooks
- - '###'
  - iBooks 应用
- - '###'
  - 同步书籍
- - '####'
  - iBookstore
- - '####'
  - ePub 电子书
- - '#####'
  - 什么是 ePub？
- - '###'
  - 浏览你的书库
- - '###'
  - 将书籍整理到收藏中
- - '####'
  - 创建新收藏
- - '#####'
  - 向收藏中添加书籍和 PDF
- - '####'
  - 在收藏间切换
- - '###'
  - 编辑精选集
- - '###'
  - 阅读图书
- - '####'
  - 翻页
- - '####'
  - 调整亮度
- - '####'
  - 调整字体、字号与页面颜色
- - '####'
  - 搜索文本
- - '####'
  - 添加书签
- - '####'
  - 与文本互动
- - '###'
  - 访问目录、书签与笔记
- - '####'
  - 分享笔记
- - '###'
  - 让书读给您听
- - '###'
  - 同步 PDF
- - '###'
  - 浏览 PDF 书架
- - '####'
  - 导航与阅读 PDF 文件
- - '####'
  - 使用缩略图
- - '###'
  - 设置
- - '###'
  - 摘要
- - '##'
  - 第 10 章：充分利用您的办公套件
- - '###'
  - 备忘录
- - '####'
  - 添加和删除备忘录
- - '####'
  - 同步备忘录
- - '###'
  - 日历
- - '####'
  - 添加日历事件
- - '####'
  - 同步日历
- - '###'
  - 通讯录
- - '####'
  - 添加联系人
- - '####'
  - 群组与搜索
- - '####'
  - 同步通讯录
- - '###'
  - MobileMe 同步
- - '###'
  - 本章小结
- - '##'
  - 第 11 章：设置和使用邮件
- - '###'
  - 设置邮件账户
- - '####'
  - 同步邮件账户
- - '####'
  - 直接在 iPad 上设置邮件账户
- - '####'
  - 其他邮件设置
- - '#####'
  - 获取新数据
- - '#####'
  - 显示
- - '#####'
  - 预览
- - '#####'
  - 最小字体大小
- - '#####'
  - 显示收件人/抄送标签
- - '#####'
  - 删除前询问
- - '#####'
  - 载入远程图像
- - '#####'
  - 始终密送给自己
- - '#####'
  - 签名
- - '#####'
  - 默认账户
- - '###'
  - 查看和管理你的收件箱
- - '####'
  - 启动和查看邮件应用
- - '####'
  - 浏览您的邮件
- - '####'
  - 查看和打开附件
- - '#####'
  - 编辑您的邮件
- - '####'
  - 恢复已删除的邮件
- - '####'
  - 导航邮件
- - '#####'
  - 移动和删除按钮
- - '#####'
  - 回复/全部回复/转发/打印
- - '###'
  - 撰写新邮件
- - '###'
  - 在其他应用中使用“邮件”
- - '####'
  - 通讯录
- - '####'
  - 备忘录
- - '####'
  - YouTube
- - '####'
  - iTunes
- - '####'
  - App Store
- - '####'
  - iBooks
- - '####'
  - iWork for iPad
- - '####'
  - 照片
- - '###'
  - 总结
- - '##'
  - 第 12 章：使用地图
- - '###'
  - 地图屏幕
- - '####'
  - 浏览地图
- - '####'
  - 手势
- - '####'
  - 更改地图视图
- - '####'
  - 查找位置
- - '####'
  - 搜索
- - '####'
  - 信息窗口
- - '####'
  - 街景视图
- - '####'
  - 当前位置
- - '####'
  - 数字指南针
- - '####'
  - 书签与查看已保存位置
- - '####'
  - 放置图钉
- - '####'
  - 添加书签
- - '####'
  - 路线与交通
- - '#####'
  - 路线
- - '#####'
  - 行车或步行路线
- - '#####'
  - 公共交通路线
- - '#####'
  - 交通
- - '###'
  - 其他应用中的地图
- - '####'
  - Flixster
- - '####'
  - The Weather Channel
- - '####'
  - Ndrive US HD
- - '####'
  - UpNext 3D Cities
- - '###'
  - 寻找遗失的 iPad
- - '###'
  - 总结
- - '##'
  - 第 13 章：触摸你的数码照片
- - '###'
  - 将照片导入 iPad
- - '####'
  - 从电脑同步照片
- - '####'
  - 从数码相机或 iPhone 导入照片
- - '####'
  - 使用 U 盘将照片传输到 iPad
- - '####'
  - 从邮件和 Safari 浏览器保存照片
- - '###'
  - 浏览你的照片
- - '####'
  - 触摸与查看相册和照片
- - '####'
  - 触摸与查看相簿
- - '####'
  - 触摸与查看照片
- - '####'
  - 通过 AirPlay 查看照片
- - '####'
  - 以幻灯片形式查看照片
- - '####'
  - 分享你的照片
- - '####'
  - 删除你的照片
- - '####'
  - 相框功能
- - '####'
  - 在不使用照片应用的情况下更改壁纸
- - '###'
  - 观看视频
- - '####'
  - 编辑你的视频
- - '####'
  - 分享你的视频
- - '###'
  - 本章小结
- - '##'
  - 第 14 章：使用 iWork 移动办公
- - '###'
  - 购买并安装适用于 iPad 的 iWork
- - '###'
  - Pages
- - '####'
  - 创建新文稿
- - '####'
  - Pages 样式标尺
- - '#####'
  - 撤销/重做
- - '#####'
  - 常用样式
- - '#####'
  - 剪切、拷贝、粘贴与拷贝样式
- - '#####'
  - 替换与定义
- - '#####'
  - 文本对齐
- - '#####'
  - 重命名 Pages 文档
- - '###'
  - Pages 工具栏
- - '####'
  - 信息
- - '####'
  - 插入
- - '####'
  - 工具
- - '####'
  - 全页显示
- - '###'
  - Numbers
- - '####'
  - 我的电子表格
- - '####'
  - 向电子表格添加元素
- - '####'
  - 信息按钮
- - '####'
  - 工具按钮
- - '###'
  - Keynote
- - '####'
  - 我的演示文稿
- - '####'
  - 编辑与添加幻灯片
- - '####'
  - 动画按钮
- - '####'
  - 播放按钮与演示者显示模式
- - '###'
  - 从电脑导入文档
- - '###'
  - 本章小结
- - '##'
  - 第 15 章：使用 iPad 摄像头：Camera、Photobooth 与 FaceTime
- - '###'
  - 摄像头硬件
- - '####'
  - 前置摄像头
- - '####'
  - 后置摄像头
- - '####'
  - 实际使用
- - '###'
  - 浏览相机应用
- - '###'
  - 拍摄静态照片
- - '####'
  - 调节曝光
- - '####'
  - 放大和缩小
- - '###'
  - 录制视频
- - '####'
  - 调整曝光
- - '###'
  - 查看“相机胶卷”
- - '####'
  - 查看单张照片
- - '###'
  - 观看视频
- - '###'
  - 玩转 Photo Booth
- - '####'
  - 拍摄照片
- - '#####'
  - 管理照片
- - '#####'
  - 将 Photo Booth 照片上传到电脑
- - '###'
  - 使用 FaceTime 聊天
- - '####'
  - 打开 FaceTime
- - '####'
  - 登录
- - '#####'
  - 创建账户
- - '####'
  - 浏览 FaceTime 联系人
- - '#####'
  - 个人收藏
- - '#####'
  - 最近通话
- - '#####'
  - 通讯录
- - '####'
  - 拨打和接听 FaceTime 通话
- - '####'
  - 其他 FaceTime 通话选项
- - '####'
  - FaceTime 设置
- - '###'
  - 总结
- - '##'
  - 第 16 章：使用 iPad 的其他绝佳方式
- - '###'
  - 将 iPad 用作游戏机
- - '####'
  - 弹球 HD
- - '####'
  - 空气曲棍球
- - '####'
  - i 鱼塘 HD
- - '####'
  - 饥饿鲨鱼三部曲
- - '####'
  - 镜之边缘
- - '###'
  - iPad 作为新闻和天气中心
- - '####'
  - 新闻应用
- - '#####'
  - 雅虎财经的 MarketDash
- - '#####'
  - iPad 版纽约时报
- - '#####'
  - BBC 新闻
- - '#####'
  - 《今日美国》iPad 版
- - '####'
  - 天气应用
- - '#####'
  - Weather HD
- - '#####'
  - The Weather Channel Max
- - '###'
  - 作为艺术家画板的 iPad
- - '####'
  - Brushes
- - '####'
  - Adobe Ideas
- - '###'
  - 作为电话的 iPad
- - '###'
  - 作为厨房帮手的 iPad
- - '####'
  - 美食频道·厨房助手
- - '####'
  - 大烤箱
- - '####'
  - 我的食谱书
- - '####'
  - 为 iPad 打造的份量调整器专业版
- - '####'
  - 为 iPad 打造的葡萄酒网
- - '###'
  - 将 iPad 用作演示工具
- - '####'
  - 讲演 Keynote
- - '####'
  - 萨顿的白板
- - '###'
  - App Store 中的教育类别
- - '####'
  - iTunes U 大学
- - '###'
  - iPad 作为旅行电脑
- - '####'
  - FlightTrack
- - '####'
  - iPad 版 Kayak HD
- - '####'
  - iPad 版 Urbanspoon HD
- - '####'
  - iPad 内置 VPN 支持
- - '####'
  - 摄影/摄像应用
- - '#####'
  - Photogene
- - '#####'
  - Masque
- - '#####'
  - 适用于 iOS 的 iMovie
- - '###'
  - 远程桌面计算
- - '####'
  - Splashtop Remote
- - '####'
  - LogMeIn Ignition
- - '####'
  - NetTools
- - '###'
  - 本章小结
- - '#'
  - 索引
- - '###'
  - A
- - '####'
  - “日历”应用
- - '####'
  - “Calibre”
- - '###'
  - B
- - '####'
  - “相机”应用
- - '####'
  - “相机连接套件”
- - '####'
  - “相机胶卷”
- - '####'
  - “摄像头”
- - '####'
  - “容量条”
- - '####'
  - “大写锁定”功能
- - '###'
  - 保养与维护（iPad 和 iPad 2）
- - '###'
  - C
- - '###'
  - D
- - '###'
  - E
- - '###'
  - F
- - '###'
  - G
- - '###'
  - H
- - '####'
  - 硬件（iPad 和 iPad 2）
- - '####'
  - HD 视频
- - '####'
  - HDMI 连接器
- - '####'
  - 页眉标签页
- - '####'
  - 耳机插孔
- - '####'
  - 隐藏键盘按钮
- - '####'
  - 持握
- - '####'
  - 主屏幕
- - '####'
  - 家庭共享
- - '####'
  - HTML5 视频
- - '####'
  - HTTP 代理
- - '####'
  - Hulu
- - '####'
  - 饥饿的鲨鱼三部曲
- - '####'
  - 混合视图
- - '####'
  - 超链接
- - '###'
  - I
- - '####'
  - iBooks app
- - '####'
  - iBookstore
- - '####'
  - Icon view
- - '####'
  - iFish Pond HD
- - '####'
  - 图像捕捉
- - '####'
  - iMovie for iOS
- - '####'
  - 全部导入按钮
- - '####'
  - 导入所选按钮
- - '####'
  - 收件箱按钮
- - '####'
  - 收件箱列表
- - '####'
  - 信息按钮
- - '####'
  - 信息标签页
- - '####'
  - 信息栏
- - '####'
  - 信息窗口
- - '####'
  - 插入按钮
- - '####'
  - 安装应用按钮
- - '####'
  - 与 iPad 交互
- - '####'
  - 互联网
- - '####'
  - 邀请收件箱
- - '####'
  - iOS 4
- - '####'
  - iOS 设备未在 iTunes 中显示
- - '####'
  - iPad 包装盒
- - '####'
  - iPad 支持网页
- - '####'
  - iPhone 4
- - '####'
  - iPhoto
- - '####'
  - iPod 应用
- - '####'
  - .ipsw 文件
- - '####'
  - iRig 麦克风
- - '####'
  - iTeleport
- - '####'
  - iTunes
- - '####'
  - iTunes DJ
- - '####'
  - iTunes Store
- - '####'
  - iTunes U
- - '####'
  - iWork for iPad
- - '###'
  - J
- - '###'
  - K
- - '###'
  - L
- - '####'
  - 邮件应用
- - '####'
  - 地图应用
- - '#####'
  - 卫星视图
- - '###'
  - M
- - '###'
  - N
- - '###'
  - O
- - '###'
  - P
- - '####'
  - Pages 应用
- - '####'
  - PDFs
- - '###'
  - Q
- - '###'
  - R
- - '####'
  - Sadun 的白板
- - '###'
  - S
- - '####'
  - Safari
- - '####'
  - 卫星视图
- - '####'
  - “已存储的照片”相簿
- - '####'
  - 屏幕（iPad 和 iPad 2）
- - '###'
  - T
- - '###'
  - U
- - '###'
  - V
- - '###'
  - W
- - '###'
  - X
- - '###'
  - Y
- - '####'
  - YouTube
- - '###'
  - Z
