name: Learn IOS Application Distribution
name_cn: iOS 应用分发入门指南
slug: learn-ios-application-distribution
toc:
- - '#'
  - 目录
- - '##'
  - 引言
- - '###'
  - 本书面向的读者
- - '###'
  - 前提假设
- - '###'
  - 什么是应用分发？
- - '###'
  - 本书内容
- - '###'
  - 本书并非什么
- - '###'
  - 本书内容概览
- - '###'
  - 如何使用本书
- - '###'
  - 致谢
- - '##'
  - 1. 智能手机格局
- - '###'
  - 从手机到智能手机
- - '####'
  - “砖头”与西蒙
- - '####'
  - 竞争
- - '###'
  - 当今的智能手机市场
- - '###'
  - 全球智能手机使用情况
- - '###'
  - 智能手机用户
- - '###'
  - 智能手机用户增长
- - '####'
  - 主要市场
- - '####'
  - 智能手机普及率
- - '####'
  - 苹果设备：iPhone
- - '####'
  - 苹果设备：iPad
- - '####'
  - 苹果部落
- - '###'
  - 本章小结
- - '##'
  - 2. 应用格局
- - '###'
  - 应用的演进
- - '###'
  - 打好基础
- - '###'
  - 应用的边界
- - '###'
  - 苹果的 App Store
- - '###'
  - 应用类型与分类
- - '####'
  - 最受欢迎的应用类别
- - '###'
  - 热门应用
- - '####'
  - Apple App Store 热门应用
- - '####'
  - Google Play 热门应用
- - '####'
  - 游戏：规模最大的应用类别
- - '###'
  - 开发者收入
- - '####'
  - 顶级应用开发者及收入
- - '###'
  - 总结
- - '##'
  - 3. 应用生态系统
- - '###'
  - 设备制造商
- - '###'
  - 操作系统开发商
- - '###'
  - 应用分发平台
- - '###'
  - 应用营销与分析平台
- - '###'
  - 监管机构
- - '###'
  - 投资者
- - '###'
  - 开发者
- - '###'
  - 资源制作者
- - '###'
  - 市场营销与广告公司
- - '###'
  - 教育者
- - '###'
  - 在线求职市场
- - '###'
  - 应用创业者
- - '####'
  - 技能组合
- - '####'
  - 时间管理
- - '####'
  - 反馈
- - '####'
  - 人脉
- - '#####'
  - 可信度
- - '####'
  - 创始团队
- - '#####'
  - 创始人
- - '#####'
  - 联合创始人
- - '#####'
  - 导师
- - '####'
  - 用户
- - '#####'
  - 收集信息
- - '#####'
  - 用户细分
- - '#####'
  - 关联与响应
- - '###'
  - 总结
- - '##'
  - 4. 应用经济学
- - '###'
  - 大问题 1：开发一款应用需要多少钱？
- - '####'
  - 应用类型
- - '####'
  - 应用平台
- - '####'
  - 编码
- - '####'
  - 功能
- - '####'
  - 用户界面设计
- - '####'
  - 图形
- - '####'
  - 营销
- - '####'
  - 内容
- - '####'
  - 更新
- - '####'
  - 运营成本
- - '###'
  - 大问题 2：应用如何赚钱？
- - '####'
  - 前期付费
- - '####'
  - 订阅制
- - '####'
  - 广告
- - '#####'
  - 横幅广告
- - '#####'
  - 插屏广告
- - '#####'
  - 原生广告
- - '#####'
  - 富媒体广告
- - '#####'
  - 视频广告
- - '#####'
  - 广告拦截器
- - '####'
  - 应用内购买
- - '####'
  - 构建稳健的变现策略
- - '###'
  - 大问题三：应用能赚多少钱？
- - '####'
  - 每位玩家的移动游戏支出
- - '####'
  - 开发者收入
- - '####'
  - 移动支付
- - '####'
  - 独角兽
- - '###'
  - 大问题四：如何衡量应用的性能？
- - '####'
  - 应用指标与关键绩效指标
- - '####'
  - 基本应用指标
- - '#####'
  - 性能分析
- - '######'
  - 性能指标与关键绩效指标类型
- - '#####'
  - 用户分析
- - '#####'
  - 用户参与度分析
- - '######'
  - 事件追踪
- - '######'
  - 触控热力图、群组分析与会话回放
- - '######'
  - 用户参与度指标与关键绩效指标类型
- - '#####'
  - 财务分析
- - '###'
  - 营销分析
- - '###'
  - 应用分析工具
- - '###'
  - 大问题 5：如何衡量应用的投资回报率？
- - '####'
  - 基本投资回报率
- - '####'
  - 净现值
- - '####'
  - 内部收益率
- - '####'
  - 如何保持应用盈利？
- - '#####'
  - 降低 CAC
- - '#####'
  - 提高 ARPU
- - '#####'
  - 应用业务中最重要的问题
- - '###'
  - 总结
- - '##'
  - 5. 想象你的应用
- - '###'
  - 正确的思维模式
- - '###'
  - 应用开发的四大迷思
- - '####'
  - 迷思一：你需要一个惊天创意
- - '####'
  - 迷思二：开发应用非常简单
- - '####'
  - 迷思三：你可以免费做到
- - '####'
  - 迷思四：不写代码也能开发应用
- - '####'
  - 认真对待
- - '###'
  - 应用发布最重要的原则
- - '####'
  - 内部与外部营销工具
- - '#####'
  - 反馈支持、内部推广与创收策略
- - '#####'
  - 尽早确定你的营销与收入策略
- - '###'
  - 如何产生应用创意
- - '####'
  - 那么，我该从哪里开始？
- - '####'
  - 方法一：头脑风暴
- - '####'
  - 方法二：从用户出发
- - '#####'
  - 用户画像与场景
- - '#####'
  - 创建用户画像
- - '######'
  - 分析人类行为
- - '#####'
  - 与你的未来用户对话
- - '#####'
  - 创建用户场景
- - '#####'
  - 通过本地化进行优化
- - '#####'
  - 改进一个职业
- - '#####'
  - 改进一个流程
- - '####'
  - 方法三：从 App Store 入手
- - '#####'
  - 识别一个有利可图的关键词利基
- - '######'
  - 如何找到一个好的长尾关键词？
- - '#####'
  - 比较、改进或复制应用
- - '####'
  - 其他灵感来源
- - '###'
  - 如何评估和验证应用创意
- - '####'
  - 验证
- - '#####'
  - 方法一：为你的应用创建一个基本的“即将上线”网站和/或社交媒体页面
- - '#####'
  - 方法二：了解有多少人在搜索类似你的应用
- - '#####'
  - 方法三：了解与你的应用类似的应用表现如何
- - '#####'
  - 方法四：检查与应用主题相关的关键词需求
- - '####'
  - 给认真的应用创业者：用于 Beta 测试的 MVP 发布
- - '###'
  - 总结
- - '##'
  - 6. 设计你的应用
- - '###'
  - 在启动设计流程之前：了解你在做什么
- - '####'
  - 选择平台
- - '#####'
  - iOS 原生应用：占智能手机市场的 13.9%（2015 年第二季度）
- - '#####'
  - Android 原生应用：占智能手机市场的 82.8%（2015 年第二季度）
- - '#####'
  - Windows 原生应用：占智能手机市场的 2.6%（2015 年第二季度）
- - '#####'
  - 混合应用
- - '#####'
  - 最优策略
- - '####'
  - 明确概念
- - '####'
  - 明确规模与成本
- - '###'
  - 应用的组成部分
- - '####'
  - 用户界面
- - '####'
  - 后端
- - '####'
  - 代码
- - '####'
  - 商业包
- - '###'
  - 应用设计的目标
- - '####'
  - 发现：让用户找到应用
- - '####'
  - 参与：让用户喜欢应用
- - '####'
  - 留存：让用户保留应用
- - '####'
  - 变现：让用户花钱
- - '####'
  - 转换点
- - '###'
  - 移动应用优化
- - '###'
  - 实现价值时间
- - '####'
  - 从出色的应用设计开始
- - '#####'
  - 信息设计
- - '######'
  - 准确性
- - '######'
  - 层次结构
- - '######'
  - 相关性
- - '#####'
  - 软件设计
- - '######'
  - 功能性
- - '######'
  - 效率
- - '######'
  - 灵活性
- - '#####'
  - 用户界面设计
- - '######'
  - 人体工程学
- - '######'
  - 一致性
- - '######'
  - 导航
- - '#####'
  - 用户体验设计
- - '######'
  - 参与感
- - '######'
  - 愉悦感
- - '######'
  - 成就感
- - '####'
  - 卓越设计的其他方面
- - '#####'
  - 清晰性（导向性设计）
- - '#####'
  - 直观设计的价值
- - '####'
  - 应用设计标准与指南
- - '#####'
  - 平台指南
- - '######'
  - 苹果
- - '####'
  - 工具与资源
- - '#####'
  - 设计模式
- - '#####'
  - 从草图到应用
- - '######'
  - 纸和笔
- - '######'
  - 用户流程图
- - '###'
  - 应用设计模板
- - '####'
  - 模板片
- - '####'
  - 线框图和 UI 工具包
- - '#####'
  - Adobe Photoshop、Illustrator、InDesign、Experience Design（`www.adobe.com`）
- - '#####'
  - Omnigraffle（`https://www.omnigroup.com/omnigraffle`）
- - '#####'
  - Sketch（`https://www.sketchapp.com`）
- - '#####'
  - 更多应用线框图和原型设计工具
- - '###'
  - 自行开发应用
- - '####'
  - 时间因素
- - '####'
  - 成本因素
- - '####'
  - 质量因素
- - '####'
  - 下一步
- - '#####'
  - 苹果之道
- - '###'
  - 总结
- - '##'
  - 7. 构建你的应用
- - '###'
  - 为苹果而用苹果开发：一个完整的系统
- - '####'
  - iOS (http://www.apple.com/ios/ios-10/)
- - '####'
  - Swift (https://developer.apple.com/swift/)
- - '####'
  - Xcode (https://developer.apple.com/xcode)
- - '###'
  - 应用开发与分发流程
- - '###'
  - 注册 Apple Developer Program
- - '####'
  - 将您的 Apple ID 添加到 Xcode
- - '####'
  - 组建 App 开发团队
- - '#####'
  - 标识符
- - '####'
  - 设计并开发 App
- - '#####'
  - Xcode 集成开发环境
- - '######'
  - 代码编辑器
- - '######'
  - 界面构建器
- - '######'
  - iOS 模拟器
- - '#####'
  - 框架
- - '#####'
  - 故事板
- - '#####'
  - 原型设计
- - '###'
  - 总结
- - '##'
  - 8. 配置您的应用
- - '###'
  - 配置项目
- - '####'
  - 创建捆绑包 ID
- - '####'
  - 标识您的团队
- - '####'
  - 输入产品信息
- - '####'
  - 输入部署信息
- - '####'
  - 提交视觉资源
- - '####'
  - 设置架构、基础 SDK 和调试信息
- - '###'
  - 应用记录
- - '####'
  - 应用信息
- - '###'
  - 应用框架
- - '####'
  - 3D Touch
- - '####'
  - 应用扩展
- - '####'
  - Bonjour
- - '####'
  - CarPlay
- - '####'
  - Handoff
- - '####'
  - 通知
- - '###'
  - 应用服务
- - '####'
  - Apple Pay
- - '####'
  - CallKit
- - '####'
  - CareKit, HealthKit, ResearchKit
- - '####'
  - HomeKit
- - '####'
  - iBeacon
- - '####'
  - iCloud 和 CloudKit
- - '####'
  - iMessage
- - '####'
  - MapKit
- - '####'
  - SiriKit
- - '####'
  - StoreKit
- - '####'
  - Wallet 和 PassKit
- - '###'
  - 功能
- - '####'
  - 附加配置
- - '####'
  - 应用瘦身、应用切片与按需资源
- - '###'
  - 总结
- - '##'
  - 9. 测试你的应用
- - '###'
  - 上传测试构建
- - '###'
  - 创建用于 Beta 测试的 iTunes 记录
- - '###'
  - 提交应用进行 Beta 应用审核
- - '###'
  - 创建测试团队
- - '###'
  - TestFlight Beta 测试
- - '###'
  - 使用 TestFlight 应用测试 Beta 应用
- - '###'
  - 利用反馈开发最终版本
- - '###'
  - 总结
- - '##'
  - 10. 提交你的应用
- - '###'
  - 避免应用被拒
- - '###'
  - 应用提交流程清单
- - '####'
  - 立即提交！
- - '###'
  - 总结
- - '##'
  - 11. 分发您的应用
- - '###'
  - 应用分发方法
- - '####'
  - App Store
- - '####'
  - 企业版
- - '####'
  - Ad Hoc
- - '###'
  - 归档与上传应用
- - '####'
  - 创建归档
- - '####'
  - 在 iTunes Connect 上验证应用
- - '####'
  - 将应用上传到 App Store
- - '###'
  - 你的应用产品页面
- - '###'
  - 管理你的应用和团队
- - '###'
  - 管理你的账户
- - '####'
  - 签名身份
- - '####'
  - 证书
- - '###'
  - 钥匙串
- - '###'
  - 标识符
- - '###'
  - 配置文件
- - '###'
  - 设备
- - '###'
  - 应用性能与分析
- - '####'
  - 崩溃报告
- - '####'
  - 分析与财务报告
- - '####'
  - 财务报告
- - '###'
  - 总结
- - '##'
  - 12. 营销你的应用
- - '###'
  - 营销速成
- - '####'
  - 营销即一切
- - '####'
  - 一切皆与营销有关
- - '###'
  - 应用营销：关键原则
- - '####'
  - 营销早在发布前就已开始
- - '####'
  - 每个应用都有自我营销机制
- - '####'
  - 自动化和个性化你的营销活动
- - '###'
  - 制定营销策略
- - '####'
  - 归因分析
- - '####'
  - 用户分层
- - '###'
  - 营销策略的组成部分
- - '####'
  - 营销策略组成部分 1：目标
- - '#####'
  - 采用率
- - '#####'
  - 信息收集
- - '#####'
  - 融资
- - '####'
  - 营销活动类型
- - '####'
  - 营销策略组成部分 2：预算
- - '####'
  - 营销策略组成部分 3：细分市场
- - '#####'
  - 个性化与时机
- - '####'
  - 市场营销策略第四部分：渠道
- - '####'
  - 数字营销：社交媒体
- - '#####'
  - 在 Facebook 上营销
- - '######'
  - 准则
- - '#####'
  - 在 Twitter 上营销
- - '#####'
  - 在 Instagram 上营销
- - '#####'
  - 尽早采取行动
- - '####'
  - 智能营销
- - '####'
  - 个人资料视觉元素速查表
- - '###'
  - 数字营销：在线品牌与身份
- - '####'
  - 应用商店优化
- - '####'
  - 评分与评论
- - '####'
  - 数字营销：联盟营销
- - '####'
  - 数字营销：电子邮件营销
- - '####'
  - 数字营销：推送通知与应用内消息
- - '#####'
  - 推送通知
- - '#####'
  - 应用内消息
- - '####'
  - 数字营销：启动屏
- - '####'
  - 付费广告
- - '####'
  - 数字营销：提交至评测网站
- - '####'
  - 非数字营销：印刷媒体与新闻界——广告、文章与采访
- - '#####'
  - 口碑传播
- - '###'
  - 营销策略要素 5：内容
- - '###'
  - 营销策略要素 6：产品/服务
- - '###'
  - 巧用策略扩大影响力
- - '####'
  - 深度链接
- - '####'
  - 桌面端到移动端营销
- - '####'
  - 内部营销渠道
- - '#####'
  - 请求评价
- - '###'
  - 衡量应用表现
- - '####'
  - 用户分析
- - '####'
  - 性能分析
- - '####'
  - 财务分析
- - '####'
  - 视觉分析
- - '####'
  - 指标
- - '####'
  - 关键分析 KPI
- - '####'
  - 用户参与度和财务指标示例
- - '####'
  - 如何在应用中使用分析？
- - '###'
  - 总结
- - '##'
  - 13. 应用营销概念
- - '###'
  - 预测性营销
- - '###'
  - A/B 测试
- - '###'
  - 再营销/重定向
- - '###'
  - 个性化
- - '###'
  - 营销漏斗
- - '###'
  - 激励
- - '###'
  - 思想领导力营销
- - '###'
  - 程序化营销
- - '###'
  - 身份解析
- - '###'
  - 单渠道、多渠道、全渠道营销
- - '###'
  - 移动应用归因
- - '###'
  - 内容营销
- - '###'
  - 忠诚度营销
- - '###'
  - 行为营销
- - '###'
  - 总结
- - '##'
  - 14. 为成功做好准备
- - '###'
  - 突如其来的成功
- - '####'
  - 初创企业的陷阱：为何高达 90% 会失败
- - '####'
  - 转变你的思维模式
- - '###'
  - 成功创业公司需要什么
- - '####'
  - 创意
- - '####'
  - 团队
- - '####'
  - 市场
- - '#####'
  - 资金
- - '###'
  - 管理快速增长
- - '####'
  - 高效扩展：硬件与软件
- - '####'
  - 高效扩展：人员与空间
- - '####'
  - 保护你的品牌
- - '####'
  - 知识产权保护
- - '####'
  - 公司注册：时间、地点与原因
- - '###'
  - 尽早注册公司：优势所在
- - '####'
  - 所有权
- - '####'
  - 股票价值与利润
- - '####'
  - 融资
- - '####'
  - 知识产权
- - '####'
  - 对创始人的保护
- - '###'
  - 规模化扩展：行动建议指南
- - '####'
  - 让用户满意
- - '####'
  - 有效营销
- - '####'
  - 构建知识管道
- - '####'
  - 确保持续的现金流
- - '####'
  - 升级技术基础设施
- - '####'
  - 组建更大的团队
- - '###'
  - 设计你的下一版应用
- - '####'
  - 接下来做什么？
- - '#####'
  - 利用你的专业技能
- - '#####'
  - 出售你的应用
- - '#####'
  - 创办一家初创公司
- - '###'
  - 退出策略
- - '####'
  - 合并
- - '####'
  - IPO
- - '####'
  - 收购
- - '####'
  - 现金牛
- - '###'
  - 应用行业趋势
- - '####'
  - 进一步打破人机界限
- - '####'
  - 更强的设备能力
- - '####'
  - 保持用户参与度的新方法
- - '####'
  - 改善用户体验
- - '####'
  - 更个性化的体验
- - '####'
  - 新技术的普及
- - '####'
  - 大数据
- - '####'
  - 用户赋权
- - '####'
  - 即刻购买
- - '####'
  - 新型应用
- - '###'
  - 应用的未来
- - '####'
  - 应用催生的进化飞跃：大数据
- - '####'
  - 更多赋能
- - '####'
  - 个性化
- - '####'
  - 应用的本质
- - '####'
  - 单一全平台应用
- - '####'
  - AI 的影响
- - '####'
  - 机器人
- - '####'
  - 深度链接
- - '####'
  - 泛在计算与物联网
- - '###'
  - 结语
- - '###'
  - 总结
- - '##'
  - 附录：在线资源
- - '###'
  - 应用开发
- - '###'
  - 游戏开发
- - '###'
  - 市场信息
- - '###'
  - 开发者网站
- - '###'
  - 应用市场
- - '###'
  - 云后端服务
- - '###'
  - 免费电子书
- - '###'
  - 应用开发公司
- - '###'
  - 跨平台应用开发
- - '###'
  - 应用设计
- - '###'
  - 应用广告、营销、盈利与分析
- - '###'
  - 应用评测网站
- - '###'
  - 无需编程的应用制作平台
- - '###'
  - 社交媒体平台及其他应用推广网站
- - '##'
  - 索引 A
- - '###'
  - A/B 测试
- - '###'
  - 应用发布平台
- - '###'
  - 应用营销平台
- - '###'
  - 应用性能与分析
- - '###'
  - 应用/应用程序
- - '###'
  - 应用服务
- - '###'
  - 应用切片
- - '###'
  - 应用商店优化（ASO）
- - '###'
  - 应用瘦身
- - '###'
  - 每用户平均收入（ARPU）
- - '##'
  - B
- - '###'
  - 行为营销
- - '##'
  - C
- - '###'
  - '`CallKit`'
- - '##'
  - D
- - '###'
  - 设计流程
- - '###'
  - 桌面到移动应用
- - '##'
  - E
- - '###'
  - 经济学
- - '###'
  - 电子邮件营销
- - '##'
  - F
- - '###'
  - 财务分析
- - '##'
  - G
- - '###'
  - Google Play 热门应用
- - '##'
  - H
- - '###'
  - '`HealthKit`'
- - '##'
  - I, J
- - '###'
  - '`iBeacon`'
- - '##'
  - K
- - '###'
  - 关键绩效指标（`KPIs`）
- - '##'
  - L
- - '###'
  - 忠诚度营销
- - '##'
  - M
- - '###'
  - '`MapKit`框架'
- - '##'
  - N
- - '###'
  - 净现值
- - '##'
  - O
- - '###'
  - 全渠道营销
- - '##'
  - P
- - '###'
  - 性能分析
- - '##'
  - Q
- - '###'
  - 质量因素
- - '##'
  - R
- - '###'
  - 再营销/重定向
- - '##'
  - S
- - '###'
  - 三星
- - '##'
  - T
- - '###'
  - '`Testflight`测试版测试'
- - '##'
  - U
- - '###'
  - 用户分析
- - '##'
  - V
- - '###'
  - 虚拟专用网络（`VPN`）
- - '##'
  - W
- - '###'
  - 钱包与 PassKit
- - '##'
  - X, Y, Z
- - '###'
  - '`Xcode` `IDE`（代码编辑器、框架、Interface Builder、`iOS`模拟器、故事板）'
