name: Beginning Reactive Programming with Swift
name_cn: Swift 响应式编程入门指南
slug: beginning-reactive-programming-with-swift
toc:
- - '##'
  - 修复说明
- - '#'
  - 引言
- - '##'
  - 关于作者与技术审校
- - '###'
  - 关于作者
- - '###'
  - 关于技术审校
- - '#'
  - 第一部分：用 Swift 构建复合型应用
- - '##'
  - 1. 构建模块：项目、工作区、扩展、委托与框架
- - '###'
  - 组件架构概述
- - '###'
  - 审视 iOS 与 macOS 的构建模块
- - '####'
  - 扩展
- - '####'
  - 委托与协议
- - '####'
  - 框架
- - '###'
  - 利用构建模块进行开发
- - '####'
  - 使用工作区
- - '####'
  - 组合使用构建模块进行开发
- - '###'
  - 命令行集成
- - '####'
  - 注意
- - '###'
  - 总结
- - '##'
  - 2. 使用 CocoaPods
- - '###'
  - 安装 CocoaPods
- - '###'
  - 创建简单应用（单视图应用）
- - '###'
  - 总结
- - '#'
  - 第二部分：在 Swift 和 iOS 中使用可编码数据
- - '##'
  - 3. 读写 JSON 数据
- - '###'
  - 识别需要共享的数据
- - '###'
  - 考虑共享数据的安全性
- - '###'
  - 共享数据面临的挑战
- - '####'
  - 识别数据元素
- - '####'
  - 管理不一致的数据类型
- - '####'
  - 探索文档和结构问题
- - '###'
  - 理解 JSON
- - '###'
  - JSON 基础使用
- - '###'
  - 总结
- - '##'
  - 4. 在 Swift 中使用 JSON 数据
- - '###'
  - 开始使用 JSON Swift Playground
- - '####'
  - 注意
- - '###'
  - 在 Swift 中使用 JSON 集成工具
- - '####'
  - 集成 Swift 数组
- - '####'
  - 集成 Swift 字典
- - '####'
  - 注意
- - '###'
  - 总结
- - '#'
  - 第三部分：集成 Facebook 登录
- - '##'
  - 5. 在 iOS 上设置 Facebook 账户
- - '####'
  - 注意
- - '###'
  - 开始探索 Facebook iOS SDK
- - '###'
  - 查看 Facebook iOS SDK 的组件
- - '###'
  - 总结
- - '##'
  - 6. 管理 Facebook 登录
- - '###'
  - 开始 Facebook SDK 登录过程
- - '###'
  - 提供基本的 iOS/Facebook 集成
- - '####'
  - 注意
- - '###'
  - 将 iOS 应用连接到你的 Facebook 应用
- - '####'
  - 注意
- - '###'
  - 总结
- - '##'
  - 7. 向 iOS 应用添加 Facebook 登录
- - '###'
  - 开始将 Facebook SDK 与 iOS 应用集成
- - '####'
  - 注意
- - '###'
  - 下载 Facebook Swift SDK
- - '###'
  - 为你的 Facebook 应用添加框架和功能
- - '###'
  - 增强你的应用
- - '####'
  - 注意
- - '####'
  - 注意
- - '###'
  - 总结
- - '#'
  - 第四部分：在 Amazon Web Services 中存储数据
- - '##'
  - 8. 使用 Amazon Web Services 和 Cocoa
- - '###'
  - 组件对比
- - '####'
  - 注意
- - '###'
  - 将 AWS 与 Cocoa 结合使用
- - '####'
  - 注意
- - '####'
  - 与他人共享数据
- - '####'
  - 跨平台使用数据
- - '####'
  - 备注
- - '####'
  - 发挥自身优势
- - '####'
  - 迎合用户期望
- - '###'
  - 探索 AWS
- - '####'
  - 注意
- - '####'
  - AWS 入门
- - '####'
  - 比较用于数据管理的 Cocoa 和 AWS 产品
- - '###'
  - 总结
- - '##'
  - 9. 管理 AWS 登录
- - '###'
  - 关于 AWS 账户与根用户
- - '###'
  - 创建组织
- - '###'
  - 使用 IAM
- - '###'
  - 将 AWS 与 Xcode 集成
- - '###'
  - 本章小结
- - '##'
  - 10. 开始一个 AWS 项目
- - '###'
  - 设置 iOS 应用
- - '###'
  - 设置 iOS 项目
- - '####'
  - 注意
- - '###'
  - 探索文档
- - '###'
  - 创建项目
- - '####'
  - 注意
- - '####'
  - 设置后端
- - '####'
  - 添加 Pods
- - '####'
  - 注意
- - '###'
  - 总结
- - '#'
  - 第五部分：使用 RxSwift
- - '##'
  - 11. 进入代码
- - '###'
  - 提示
- - '###'
  - 入门
- - '###'
  - 从 GitHub 安装 RxSwift
- - '####'
  - 提示
- - '###'
  - 使用 RxSwift Playground
- - '####'
  - 查看格式化的 Playground
- - '####'
  - 提示
- - '###'
  - 总结
- - '##'
  - 12. 响应式思考
- - '###'
  - 我们在开发什么？
- - '####'
  - 提示
- - '###'
  - 编程方法
- - '####'
  - 提示
- - '####'
  - 编程范式
- - '#####'
  - 结构范式
- - '#####'
  - 操作范式
- - '####'
  - 设计模式
- - '####'
  - 提示
- - '####'
  - 处理配置
- - '###'
  - 介绍响应式编程
- - '###'
  - 聚焦 ReactiveX
- - '####'
  - 注
- - '###'
  - 总结
- - '##'
  - 13. 探索 Rx 基础代码
- - '####'
  - 注
- - '###'
  - ReactiveX/RxSwift 与 Xcode 集成概览
- - '####'
  - 从 RxSwift 下载开始
- - '####'
  - 探索工作区和 Playground
- - '####'
  - 向 RxSwift 下载添加项目
- - '####'
  - 构建你的 RxSwift 增强版项目
- - '###'
  - 修改项目
- - '###'
  - 总结
- - '##'
  - 14. 构建 ReactiveX/RxSwift 应用
- - '###'
  - 注意
- - '###'
  - 项目设置
- - '####'
  - 注意
- - '####'
  - 提示
- - '###'
  - 添加 ReactiveX
- - '###'
  - 构建 RxCocoa 和 RxSwift
- - '###'
  - 将 RxSwift 和 RxCocoa 添加到项目中
- - '###'
  - 验证语法
- - '###'
  - 构建故事板
- - '####'
  - 添加 `UITableView` 代码与委托
- - '####'
  - 实现 ReactiveX 搜索栏
- - '#####'
  - 注意
- - '###'
  - 审查代码
- - '###'
  - 摘要
- - '#'
  - 索引
- - '##'
  - A, B
- - '##'
  - C
- - '##'
  - D
- - '##'
  - E
- - '##'
  - F
- - '##'
  - G
- - '##'
  - H
- - '##'
  - I
- - '##'
  - J, K, L, M, N
- - '##'
  - O
- - '##'
  - P, Q
- - '##'
  - R
- - '##'
  - S
- - '##'
  - T
- - '##'
  - U, V
- - '##'
  - W
- - '##'
  - X, Y, Z
