name: SWIFT RECIPES FOR IOS DEVELOPERS
name_cn: iOS开发者Swift秘籍
slug: swift-recipes-for-ios-developers
toc:
- - '#'
  - 如何使用本书
- - '##'
  - 好代码
- - '##'
  - NS 还是非 NS
- - '##'
  - 框架
- - '#'
  - HTTP 库
- - '#'
  - Firebase 库
- - '##'
  - Swift 版本与兼容性
- - '##'
  - 致谢
- - '##'
  - 关于作者 / 关于技术审校
- - '#'
  - 1. 处理数据
- - '##'
  - 数据类型之间的转换
- - '###'
  - 安全的数字转换
- - '###'
  - 秘诀 1-1：安全的数值转换
- - '###'
  - 数字与字符串的相互转换
- - '###'
  - 布尔值转换
- - '###'
  - 字符串与数据的相互转换
- - '###'
  - 日期、时间戳与 ISO 8601 格式
- - '##'
  - 从字典和数组中提取数据
- - '###'
  - 复杂数据类型
- - '###'
  - 从字典中提取数据
- - '###'
  - 从数组中提取数据
- - '##'
  - 本章小结
- - '#'
  - 2. 处理 JSON 和其他流行格式
- - '##'
  - 设备如何交换数据
- - '##'
  - 什么是序列化和反序列化
- - '##'
  - 使用 JSON
- - '###'
  - 将 JSON 解析为 Dictionary 或 Array
- - '###'
  - 从 Dictionary 或 Array 生成 JSON
- - '##'
  - 使用 XML
- - '###'
  - 解析 XML
- - '###'
  - 生成 XML
- - '##'
  - 处理 YAML
- - '##'
  - URL 编码字符串
- - '##'
  - 序列化和反序列化
- - '###'
  - 序列化对象
- - '###'
  - 反序列化对象
- - '##'
  - 编码键
- - '##'
  - 使用 `@propertyWrapper`
- - '##'
  - 单位转换
- - '###'
  - 距离和长度单位
- - '###'
  - 面积单位
- - '###'
  - 体积单位
- - '###'
  - 重量单位
- - '##'
  - 总结
- - '#'
  - 3. 使用字符串
- - '##'
  - 分析字符串内容
- - '##'
  - 名、姓和其他名称
- - '##'
  - 电子邮件地址
- - '###'
  - 密码
- - '###'
  - 电话号码
- - '###'
  - 性别
- - '###'
  - 出生日期
- - '###'
  - 信用卡信息
- - '##'
  - Base64 与十六进制编码
- - '###'
  - Base64 编码
- - '###'
  - 十六进制编码
- - '###'
  - MD5、SHA 与其他哈希
- - '###'
  - MD5 哈希
- - '###'
  - SHA 哈希
- - '###'
  - Hashable 协议与 Swift 哈希
- - '###'
  - 盐值
- - '##'
  - 整数索引
- - '##'
  - 本地化
- - '###'
  - NSLocalizedString 宏
- - '###'
  - 翻译文件
- - '###'
  - LocalizedStringKey 结构体
- - '###'
  - 语法糖
- - '##'
  - 总结
- - '#'
  - UIKit 与 Storyboards
- - '##'
  - 应用界面间的导航
- - '###'
  - 屏幕、窗口与视图
- - '###'
  - iOS 应用中的导航
- - '###'
  - 场景
- - '###'
  - 返回操作
- - '###'
  - 替换根视图
- - '###'
  - 修改 UINavigationController 栈
- - '####'
  - 从导航栈中移除元素
- - '###'
  - 将用户返回到特定的视图控制器
- - '###'
  - 弹窗与对话框
- - '####'
  - 显示提示、错误和警告
- - '####'
  - 询问一般性问题
- - '####'
  - 询问单行字符串答案的问题
- - '####'
  - 选择日期和时间
- - '###'
  - 什么是 SnapKit？
- - '###'
  - 日期与时间选择器弹出窗口
- - '###'
  - 底部面板中的日期与时间
- - '#'
  - 地图与导航
- - '##'
  - 在 iOS 应用中显示苹果地图
- - '##'
  - 在 iOS 应用中显示谷歌地图
- - '###'
  - 动态导航
- - '##'
  - 圆角、阴影和其他效果
- - '###'
  - 圆角、内容裁剪和边框
- - '###'
  - 阴影
- - '###'
  - UITextField 内边距
- - '###'
  - UITextView 占位符
- - '###'
  - 渐变
- - '###'
  - 模糊
- - '##'
  - 总结
- - '#'
  - 5. 图像处理
- - '###'
  - 读取和写入图像
- - '###'
  - 图像缓冲区
- - '###'
  - 文件格式
- - '###'
  - 从文件加载（读取）图像
- - '###'
  - 将图像保存（写入）到文件
- - '##'
  - 下载与缓存图像
- - '###'
  - 下载文件
- - '####'
  - 使用 Alamofire 下载文件
- - '####'
  - 使用 URLSession/URLRequest 下载文件
- - '###'
  - 将带有完成处理器的函数转换为异步函数
- - '###'
  - 在内存中缓存文件
- - '###'
  - 在文件系统中缓存文件
- - '####'
  - 获取目录路径
- - '####'
  - 将文件保存到缓存
- - '####'
  - 验证缓存大小
- - '###'
  - 秘诀 5-13：文件系统缓存系统
- - '##'
  - 调整大小与裁剪
- - '###'
  - 图像缩放
- - '###'
  - 图像裁剪
- - '##'
  - 准备与展示个人头像
- - '###'
  - 上传前处理个人头像
- - '###'
  - 展示个人头像
- - '##'
  - 图像遮罩
- - '###'
  - 合并图像
- - '###'
  - 应用蒙版
- - '##'
  - 效果与滤镜
- - '###'
  - CoreImage
- - '###'
  - GPUImage
- - '##'
  - GIF 动画
- - '###'
  - Kingfisher 中的 AnimatedImageView
- - '###'
  - SwiftyGif
- - '##'
  - 总结
- - '#'
  - 6. 文本编辑
- - '##'
  - 实时分析用户输入
- - '###'
  - 现在让我们在秘诀 6-2 中创建一个简单的验证器。所有验证器都各不相同，但基本结构是相似的。假设我们需要用户的电子邮件地址。我们的`EmailInputValidator`类应被指定为`UITextField`的委托。它会移除电子邮件地址中不允许的所有字符，并在地址有效时调用自身的委托函数。
- - '##'
  - 格式化用户输入
- - '###'
  - 格式化电话号码
- - '###'
  - 格式化银行卡号
- - '##'
  - 使用表情符号
- - '###'
  - 检测字符串中的表情符号
- - '###'
  - 阻止用户在输入中使用表情符号
- - '##'
  - 浮动前缀或后缀
- - '###'
  - 添加前缀
- - '###'
  - 添加后缀
- - '##'
  - 键盘处理
- - '###'
  - 用户点击文本框外部时隐藏键盘
- - '###'
  - 在可滚动区域中隐藏键盘
- - '###'
  - 用户离开屏幕时隐藏键盘
- - '###'
  - 键盘出现时调整布局
- - '###'
  - 滚动以显示当前文本字段
- - '##'
  - 密码键盘 UI 组件
- - '##'
  - 总结
- - '#'
  - 7. UI 动画与效果
- - '##'
  - 视图动画
- - '###'
  - 对 `UIView` 自身属性进行动画
- - '###'
  - 通过改变约束来对布局进行动画
- - '###'
  - 限制条件
- - '###'
  - 当键盘出现时对布局进行动画
- - '##'
  - 视差效果
- - '###'
  - 使用 UIScrollView 实现视差标题栏
- - '####'
  - 准备用户界面
- - '####'
  - 视差功能
- - '###'
  - 支持 UITableView 和 UICollectionView 的视差标题
- - '##'
  - 英雄动画
- - '###'
  - 在同一个 UIViewController 内的英雄动画
- - '####'
  - 创建并显示 UIView
- - '####'
  - 计算变换
- - '####'
  - 应用变换
- - '####'
  - 隐藏源 UIView 并显示目标 UIView
- - '####'
  - 动画
- - '####'
  - 最终代码
- - '###'
  - 英雄飞入新 UIViewController
- - '####'
  - 获取并使用 UIWindow
- - '####'
  - 细节
- - '##'
  - 屏幕间的转场
- - '###'
  - 标准转场
- - '###'
  - 创建自定义转场动画
- - '###'
  - 转场动画库
- - '##'
  - 总结
- - '#'
  - 8. SwiftUI
- - '##'
  - SwiftUI 基本概述
- - '###'
  - 基础应用
- - '###'
  - 构建块
- - '###'
  - 修改控件
- - '###'
  - 组合
- - '###'
  - 插入 UIKit 组件
- - '####'
  - 从 UIKit 组件创建 SwiftUI 组件
- - '###'
  - 自定义标签示例
- - '##'
  - 使用 ViewModifier 应用样式
- - '###'
  - 创建 ViewModifier
- - '###'
  - SwiftUI 中的链式修饰符
- - '###'
  - 不依赖 UIKit 的 HeaderText
- - '##'
  - 创建自定义视图
- - '###'
  - 在 Canvas 上绘制
- - '###'
  - 组件状态
- - '###'
  - 数据绑定
- - '##'
  - 总结
- - '#'
  - 索引
- - '##'
  - A
- - '##'
  - B
- - '##'
  - C
- - '##'
  - D
- - '##'
  - E
- - '##'
  - F
- - '##'
  - G
- - '##'
  - H
- - '##'
  - I
- - '##'
  - J
- - '##'
  - K
- - '##'
  - L
- - '##'
  - M
- - '##'
  - N
- - '##'
  - O
- - '##'
  - P, Q
- - '##'
  - R
- - '##'
  - S
- - '##'
  - T
- - '##'
  - U
- - '##'
  - V
- - '##'
  - W, X
- - '##'
  - Y, Z
