name: Learn IPhone 5 and IPad 2 Cocos2D Game Development
name_cn: Learn iPhone 5 和 iPad 2 Cocos2D 游戏开发入门指南
slug: learn-iphone-5-and-ipad-2-cocos2d-game-development
toc:
- - '#'
  - 目录
- - '##'
  - 关于作者
- - '##'
  - 关于技术审校者
- - '##'
  - 前言
- - '##'
  - 第 1 章 引言
- - '###'
  - 第二版的新增内容
- - '###'
  - 为什么在 iOS 上使用 cocos2d？
- - '####'
  - 它是免费的
- - '####'
  - 它是开源的
- - '####'
  - 它很客观，明白吗？
- - '####'
  - 它是 2D 的
- - '####'
  - 它自带物理引擎
- - '####'
  - 它不那么技术化
- - '####'
  - 它仍然是编程
- - '####'
  - 它拥有一个很棒的社区
- - '####'
  - '`cocos2d-iphone` 项目的未来'
- - '####'
  - 其他 `cocos2d` 游戏引擎
- - '####'
  - 本书适合你
- - '####'
  - 先决条件
- - '#####'
  - 编程经验
- - '#####'
  - Objective-C
- - '###'
  - 你将学到什么
- - '####'
  - 初学 iOS 游戏开发者将学到什么
- - '####'
  - iOS App 开发者将学到什么
- - '####'
  - Cocos2d 开发者将学到什么
- - '###'
  - 本书内容概览
- - '####'
  - 第 2 章 "起步"
- - '####'
  - 第 3 章 "核心要素"
- - '####'
  - 第 4 章 "你的第一个游戏"
- - '####'
  - 第 5 章 "游戏构建模块"
- - '####'
  - 第 6 章 "精灵深度解析"
- - '####'
  - 第 7 章 "快乐滚动"
- - '####'
  - 第 8 章 "射击游戏"
- - '####'
  - 第 9 章 "粒子特效"
- - '####'
  - 第 10 章 "使用瓦片地图"
- - '####'
  - 第 11 章 "等距瓦片地图"
- - '####'
  - 第 12 章 "物理引擎"
- - '####'
  - 第 13 章 "弹球游戏"
- - '####'
  - 第 14 章 "Game Center"
- - '####'
  - 第 15 章 "Cocos2d 与 UIKit 视图"
- - '####'
  - 第 16 章 "Kobold2D 介绍"
- - '####'
  - 第 17 章 "结论"
- - '###'
  - 如何获取本书的源代码？
- - '###'
  - 问题与反馈
- - '##'
  - 第 2 章 入门
- - '###'
  - 入门所需条件
- - '####'
  - 系统要求
- - '####'
  - 注册成为 iOS 开发者
- - '####'
  - 证书和配置文件
- - '###'
  - 下载并安装 iOS SDK
- - '###'
  - 下载并安装 cocos2d
- - '####'
  - 安装 cocos2d Xcode 项目模板
- - '####'
  - 创建一个 cocos2d 应用
- - '###'
  - HelloWorld 应用
- - '###'
  - 定位 HelloWorld 文件
- - '###'
  - 资源
- - '###'
  - 支持文件
- - '####'
  - Main.m
- - '####'
  - 预编译前缀头文件
- - '###'
  - HelloWorld 类
- - '###'
  - '`AppDelegate`'
- - '###'
  - 设备方向
- - '###'
  - 动画间隔
- - '###'
  - 显示 FPS
- - '###'
  - '`HelloWorldLayer`'
- - '###'
  - '`cocos2d` 的内存管理'
- - '###'
  - 改变世界
- - '###'
  - 你还应了解的其他内容
- - '###'
  - iOS 设备
- - '####'
  - 关于内存使用
- - '###'
  - iOS 模拟器
- - '####'
  - 无法评估性能
- - '####'
  - 无法评估内存使用情况
- - '####'
  - 无法使用所有 iOS 设备功能
- - '####'
  - 运行时行为可能不同
- - '###'
  - 关于日志记录
- - '###'
  - 总结
- - '##'
  - 第 3 章 基础
- - '###'
  - cocos2d 场景图
- - '###'
  - CCNode 类层次结构
- - '###'
  - CCNode
- - '###'
  - 节点操作
- - '###'
  - 动作操作
- - '###'
  - 定时消息
- - '###'
  - 导演、场景与层
- - '###'
  - Director
- - '###'
  - CCScene
- - '###'
  - 场景与内存
- - '###'
  - 场景的推送与弹出
- - '###'
  - '`CCTransitionScene`'
- - '###'
  - '`CCLayer`'
- - '###'
  - 接收触摸事件
- - '###'
  - 接收加速计事件
- - '###'
  - 接收键盘事件
- - '###'
  - 接收鼠标事件
- - '###'
  - CCSprite
- - '####'
  - 锚点揭秘
- - '####'
  - 纹理尺寸
- - '###'
  - CCLabelTTF
- - '###'
  - 菜单
- - '###'
  - 动作
- - '####'
  - 区间动作
- - '####'
  - 动作序列
- - '####'
  - 缓动动作
- - '####'
  - 网格动作
- - '####'
  - 即时动作
- - '###'
  - 关于 cocos2d 中单例模式的说明
- - '###'
  - Cocos2d 测试用例
- - '###'
  - 总结
- - '##'
  - 第 4 章 你的第一个游戏
- - '###'
  - 分步项目设置
- - '###'
  - 添加玩家精灵
- - '###'
  - 加速度计输入
- - '###'
  - 首次测试运行
- - '###'
  - 玩家速度
- - '###'
  - 添加障碍物
- - '###'
  - 碰撞检测
- - '###'
  - 标签与位图字体
- - '####'
  - 添加分数标签
- - '####'
  - 介绍 `CCLabelBMFont`
- - '####'
  - 使用 `Glyph Designer` 创建位图字体
- - '###'
  - 简单播放音频
- - '###'
  - 移植到 iPad
- - '####'
  - 一个通用应用还是两个独立的应用？
- - '####'
  - 使用 Xcode 3 移植到 iPad
- - '####'
  - 使用 Xcode 4 移植到 iPad
- - '###'
  - 摘要
- - '##'
  - 第 5 章 游戏构建块
- - '###'
  - 使用多个场景
- - '####'
  - 添加更多场景
- - '####'
  - 正在加载下一场景，请稍候
- - '###'
  - 使用多个层
- - '###'
  - 如何最佳实现关卡
- - '####'
  - 场景作为关卡
- - '####'
  - 图层即关卡
- - '###'
  - '`CCLayerColor`'
- - '###'
  - 从 `CCSprite` 派生游戏对象子类
- - '###'
  - 使用 CCSprite 组合游戏对象
- - '###'
  - 有趣的 `CCNode` 类
- - '###'
  - '`CCProgressTimer`'
- - '###'
  - '`CCParallaxNode`'
- - '###'
  - '`CCRibbon`'
- - '###'
  - '`CCMotionStreak`'
- - '###'
  - 本章小结
- - '##'
  - 第 6 章 深入理解精灵
- - '###'
  - '`Retina Display`'
- - '###'
  - '`CCSpriteBatchNode`'
- - '####'
  - 何时使用 `CCSpriteBatchNode`
- - '####'
  - 演示项目
- - '#####'
  - 一个常见且致命的错误
- - '#####'
  - 没有 SpriteBatch 的子弹
- - '###'
  - 引入 `CCSpriteBatchNode`
- - '###'
  - 优化
- - '####'
  - 棘手的精灵动画实现方式
- - '###'
  - 动画辅助类
- - '###'
  - 使用纹理图集
- - '####'
  - 什么是纹理图集？
- - '####'
  - 介绍 TexturePacker
- - '####'
  - 为 TexturePacker 准备项目
- - '####'
  - 使用 TexturePacker 创建纹理图集
- - '####'
  - 将纹理图集与 cocos2d 一起使用
- - '####'
  - 更新 CCAnimation 辅助类别
- - '####'
  - 合而为一，一应俱全
- - '###'
  - 总结
- - '##'
  - 第 7 章 滚动之乐
- - '###'
  - 高级视差滚动
- - '####'
  - 将背景创建为条带
- - '####'
  - 在代码中重构背景
- - '####'
  - 移动 ParallaxBackground
- - '#####'
  - 视差速度系数
- - '#####'
  - 滚动至无限远方
- - '#####'
  - 修复闪烁问题
- - '#####'
  - 重复，重复，再重复
- - '###'
  - 虚拟摇杆
- - '####'
  - 介绍 SneakyInput
- - '####'
  - 集成 SneakyInput
- - '#####'
  - 触摸按钮发射子弹
- - '#####'
  - 为按钮添加皮肤
- - '#####'
  - 控制操作
- - '#####'
  - 数字控制
- - '###'
  - 总结
- - '##'
  - 第 8 章 射击游戏
- - '###'
  - 添加 BulletCache 类
- - '###'
  - 敌人又该如何？
- - '###'
  - Entity 类层次结构
- - '###'
  - '`EnemyEntity` 类'
- - '###'
  - EnemyCache 类
- - '###'
  - 组件类
- - '###'
  - 射击目标
- - '###'
  - BOSS 的生命条
- - '###'
  - 总结
- - '##'
  - 第 9 章 粒子效果
- - '###'
  - 示例粒子效果
- - '###'
  - 手动创建粒子效果（传统方式）
- - '###'
  - 子类化 `CCParticleSystem`：`CCParticleSystemPoint` 还是 `CCParticleSystemQuad`？
- - '###'
  - '`CCParticleSystem` 属性'
- - '####'
  - 方差属性
- - '####'
  - 粒子数量
- - '####'
  - 发射器持续时间
- - '####'
  - 发射器模式
- - '#####'
  - 发射器模式：重力
- - '#####'
  - 发射器模式：半径
- - '####'
  - 粒子位置
- - '####'
  - 粒子大小
- - '####'
  - 粒子方向
- - '####'
  - 粒子生命周期
- - '####'
  - 粒子颜色
- - '####'
  - 粒子混合模式
- - '####'
  - 粒子纹理
- - '###'
  - 粒子设计器
- - '####'
  - 粒子设计器介绍
- - '####'
  - 使用粒子设计器效果
- - '####'
  - 分享粒子效果
- - '###'
  - 用粒子效果打造弹幕射击游戏
- - '###'
  - 小结
- - '##'
  - 第 10 章 使用瓦片地图
- - '###'
  - 什么是瓦片地图？
- - '###'
  - 使用 TexturePacker 准备图像
- - '###'
  - Tiled (Qt) 地图编辑器
- - '####'
  - 创建新地图
- - '####'
  - 设计地图
- - '###'
  - 将正交切片地图与 Cocos2d 结合使用
- - '####'
  - 图块全局标识符（GID）介绍
- - '####'
  - 定位触摸的图块
- - '#####'
  - 优化与可读性的练习
- - '####'
  - 使用对象层
- - '####'
  - 绘制对象层矩形
- - '####'
  - 滚动瓦片地图
- - '###'
  - 总结
- - '##'
  - 第 11 章 等距瓦片地图
- - '###'
  - 设计等距瓦片图形
- - '###'
  - 使用 Tiled 编辑等距瓦片地图
- - '####'
  - 创建新的等距瓦片地图
- - '####'
  - 创建新的等距瓦片集
- - '####'
  - 制定一些基本规则
- - '###'
  - 等距游戏编程
- - '####'
  - 在 Cocos2d 中加载等距瓦片地图
- - '###'
  - 为等距瓦片地图设置 Cocos2d
- - '###'
  - 定位等距瓦片
- - '####'
  - 滚动等距瓦片地图
- - '####'
  - 这个世界值得拥有更好的边界
- - '###'
  - 添加可移动玩家角色
- - '###'
  - 让玩家能移动到瓦片后方
- - '###'
  - 逐格移动玩家
- - '###'
  - 碰撞时阻止玩家移动
- - '###'
  - 为游戏增加更多内容
- - '###'
  - 本章小结
- - '##'
  - 第 12 章 物理引擎
- - '###'
  - 物理引擎的基本概念
- - '###'
  - 物理引擎的局限性
- - '###'
  - 正面交锋：Box2D vs. Chipmunk
- - '###'
  - Box2D
- - '####'
  - Box2D 眼中的世界
- - '####'
  - 限制移动至屏幕范围内
- - '####'
  - 转换点
- - '####'
  - 在 Box2D 世界中添加盒子
- - '####'
  - 将精灵与刚体连接
- - '###'
  - 碰撞检测
- - '###'
  - 关节连接
- - '###'
  - 花栗鼠
- - '####'
  - 面向对象的花栗鼠
- - '####'
  - 太空中的花栗鼠
- - '####'
  - 框定边界
- - '####'
  - 添加密密麻麻的小盒子
- - '####'
  - 更新盒子的精灵
- - '###'
  - Chipmunk 碰撞路线
- - '###'
  - Chipmunk 的关节
- - '###'
  - 总结
- - '##'
  - 第 13 章 弹球游戏
- - '###'
  - 形状：凸形与逆时针方向
- - '###'
  - 使用 PhysicsEditor
- - '####'
  - 定义柱塞形状
- - '####'
  - 定义台面形状
- - '####'
  - 定义挡板
- - '####'
  - 定义缓冲器和球
- - '####'
  - 保存与发布
- - '###'
  - 编写弹球游戏程序
- - '####'
  - '`BodyNode` 类'
- - '####'
  - 创建弹球台
- - '###'
  - Box2D 调试绘制
- - '###'
  - 添加弹球
- - '####'
  - 强制球体移动
- - '###'
  - 添加缓冲器
- - '####'
  - 弹射杆
- - '###'
  - 创建通用碰撞监听器
- - '###'
  - 响应接触事件
- - '###'
  - 挡板
- - '###'
  - 总结
- - '##'
  - 第 14 章 Game Center
- - '###'
  - 启用 Game Center
- - '####'
  - 在 iTunes Connect 中创建你的应用
- - '####'
  - 设置排行榜和成就
- - '####'
  - 创建 Cocos2d Xcode 项目
- - '####'
  - 配置 Xcode 项目
- - '####'
  - Game Center 设置总结
- - '###'
  - 游戏套件编程
- - '####'
  - '`GameKitHelper` 委托'
- - '####'
  - 检查 Game Center 可用性
- - '####'
  - 验证本地玩家
- - '###'
  - 块对象
- - '####'
  - 接收本地玩家的好友列表
- - '###'
  - 排行榜
- - '###'
  - 成就
- - '###'
  - 匹配机制
- - '####'
  - 发送与接收数据
- - '###'
  - 总结
- - '##'
  - 第 15 章 Cocos2d 与 UIKit 视图
- - '###'
  - 什么是 Cocoa Touch？
- - '###'
  - 同时使用 Cocoa Touch 和 cocos2d
- - '####'
  - 为什么要将 Cocoa Touch 与 cocos2d 混合使用？
- - '####'
  - 混合使用 Cocoa Touch 与 cocos2d 的局限性
- - '###'
  - Cocoa Touch 与 cocos2d 有何不同？
- - '####'
  - 模型-视图-控制器模式
- - '####'
  - Cocos2d 的视图使用 OpenGL ES
- - '###'
  - 提示：在 cocos2d 中使用你的第一个 UIKit 视图
- - '###'
  - 在 cocos2d 应用中嵌入 UIKit 视图
- - '####'
  - 在 cocos2d 视图前添加视图
- - '###'
  - 使用 UIImage 为 UITextField 设置皮肤
- - '###'
  - 在 cocos2d 视图后方添加视图
- - '####'
  - 改进视图层级
- - '#####'
  - 将 `UITextField` 移至背景
- - '#####'
  - 使 cocos2d 视图透明
- - '#####'
  - 通过命中测试正确传递触摸事件
- - '###'
  - 实现 Cocos2D 视图的“三明治”效果
- - '###'
  - 添加使用 Interface Builder 设计的视图
- - '####'
  - 自动旋转方向课程
- - '###'
  - 在 Cocoa Touch 应用中嵌入 cocos2d 视图
- - '####'
  - 使用 Cocos2D 创建基于视图的应用程序项目
- - '####'
  - 设计混合应用的用户界面
- - '####'
  - 启动你的 cocos2d 引擎
- - '####'
  - 停止 cocos2d 引擎并重新启动
- - '####'
  - 更改场景
- - '###'
  - 摘要
- - '##'
  - 第 16 章 Kobold2D 简介
- - '###'
  - 使用 Kobold2D 的优势
- - '####'
  - Kobold2D 开箱即用
- - '####'
  - Kobold2D 免费
- - '####'
  - Kobold2D 易于升级
- - '####'
  - Kobold2D 提供"库服务"
- - '####'
  - Kobold2D 高度重视跨平台
- - '###'
  - Kobold2D 工作区
- - '###'
  - Hello Kobold2D 模板项目
- - '####'
  - Hello World 项目文件
- - '####'
  - Kobold2D 如何启动应用
- - '####'
  - Main、AppDelegate 与 RootViewController
- - '###'
  - 启动配置文件
- - '###'
  - Hello Kobold2D 场景和层
- - '###'
  - 使用 iSimulate 运行 Hello World
- - '###'
  - 使用 KKInput 的 Mac 版 Doodle Drop
- - '###'
  - 使用 cocos3d 进入三维世界
- - '####'
  - 对 AppDelegate 类的更改
- - '###'
  - cocos3d 的世界观
- - '####'
  - 将 cocos3d 添加到现有 Kobold2D 项目
- - '###'
  - 总结
- - '##'
  - 第 17 章 非同凡响
- - '###'
  - 学习和工作的额外资源
- - '####'
  - 何处寻求帮助
- - '####'
  - Cocos2d 主页
- - '###'
  - Cocos2D 中心
- - '###'
  - Stack Exchange 网络
- - '###'
  - 教程与常见问题解答
- - '###'
  - 可供借鉴的源代码项目
- - '####'
  - iPhone RPG 游戏工具包
- - '####'
  - 划线游戏入门套件
- - '####'
  - 平台游戏套件
- - '####'
  - 太空游戏入门套件
- - '####'
  - iUridium 源代码
- - '####'
  - BATAK Duel 源代码
- - '####'
  - Cocos2D 播客
- - '####'
  - 工具、工具、工具
- - '####'
  - Cocos2d 参考应用
- - '#####'
  - 超级涡轮动作猪
- - '#####'
  - 开心农场
- - '#####'
  - 梅尔文说有怪物 (iPad)
- - '#####'
  - 火车站
- - '#####'
  - 抽象战争 2.0
- - '#####'
  - 富士叶
- - '###'
  - 制作游戏的商业之道
- - '####'
  - 与发行商合作
- - '#####'
  - 作为放弃部分自由的回报，他们会为你提供游戏营销方面的支持。他们了解各种渠道，并且能直接联系到评测网站和新闻媒体。这或许是你能够学到大量知识的另一专业领域。新闻媒体有其特定的接收和消化信息的方式，以便撰写关于你游戏的评测文章。你的发行商对此了如指掌，他们会向你索要一些你最初可能根本不会考虑的东西，比如高分辨率的美术素材，或是能真正勾起玩家对游戏兴趣的一句话宣传语。
- - '####'
  - 寻找自由职业者
- - '####'
  - 寻找免费美术和音频资源
- - '####'
  - 寻找开发工具
- - '####'
  - 市场营销
- - '#####'
  - 营销你的游戏与你自己
- - '#####'
  - 公共关系与新闻稿
- - '####'
  - 吸引玩家以增加收入
- - '#####'
  - 吸引你的玩家
- - '#####'
  - 社交网络
- - '#####'
  - 用于多人游戏的 Socket 服务器技术
- - '#####'
  - 推送通知提供商
- - '#####'
  - iCloud
- - '#####'
  - 赚取更多收入
- - '######'
  - 广告与分析
- - '######'
  - 应用内购买
- - '##'
  - 索引
- - '###'
  - A
- - '###'
  - B
- - '###'
  - '`CADisplayLink` 类'
- - '###'
  - '`CCParallaxNode` 类'
- - '###'
  - '`CCParticleSystem` 类'
- - '###'
  - '`ccpDistance` 方法'
- - '###'
  - '`CCProgressTimer` 类'
- - '###'
  - HelloWorld 应用程序
- - '###'
  - iOS 设备
- - '###'
  - 内存管理
- - '###'
  - Cocos3d
- - '###'
  - D
- - '###'
  - E
- - '###'
  - F
- - '###'
  - G
- - '####'
  - 注意事项
- - '###'
  - H
- - '###'
  - I, J
- - '###'
  - K
- - '###'
  - L
- - '###'
  - M
- - '###'
  - N
- - '###'
  - O
- - '###'
  - 方向控制与自动旋转
- - '###'
  - 正交瓦片地图, Cocos2d
- - '###'
  - P
- - '###'
  - Q
- - '###'
  - R
- - '###'
  - S
- - '###'
  - 动画（animations）
- - '###'
  - 批处理（batching）
- - '###'
  - 绘制调用（draw call）
- - '###'
  - Retina 显示屏（Retina display）
- - '###'
  - 纹理图集（texture atlas）
- - '###'
  - T
- - '###'
  - '`TexturePacker`（纹理打包器）'
- - '###'
  - '`Tiled (Qt) Map Editor`（基于 Qt 的瓦片地图编辑器）'
- - '###'
  - '`Tilemaps`（瓦片地图）'
- - '###'
  - U
- - '###'
  - V
- - '###'
  - W
- - '###'
  - X
- - '###'
  - Z
