name: Asynchronous programming with SwiftUI and Combine
name_cn: SwiftUI 和 Combine 异步编程
slug: asynchronous-programming-with-swiftui-and-combine
toc:
- - '#'
  - '![](img/978-1-4842-8572-5_CoverFigure.jpg)'
- - '##'
  - 序言
- - '##'
  - 前言
- - '#'
  - 本书目标
- - '##'
  - 致谢
- - '##'
  - 关于本书
- - '##'
  - 谁应该阅读本书
- - '##'
  - 本书的组织结构
- - '###'
  - 第 1 部分
- - '###'
  - 第 2 部分
- - '###'
  - 第 3 部分
- - '##'
  - 关于代码
- - '#'
  - 第一部分
- - '#'
  - 1. SwiftUI：新的开端
- - '##'
  - 为什么需要一个新的 UI 框架？
- - '##'
  - SwiftUI 原则
- - '###'
  - 声明式 vs. 命令式
- - '###'
  - 状态管理
- - '###'
  - 组合优于继承
- - '###'
  - 一切皆是视图——但并非如此
- - '###'
  - UI 是状态的一种函数
- - '##'
  - SwiftUI 快速入门
- - '###'
  - 先决条件
- - '###'
  - 创建一个新的 SwiftUI 应用
- - '###'
  - 为你的 App 添加交互
- - '###'
  - 使用 SwiftUI 的状态管理保持 UI 与模型同步
- - '###'
  - 练习
- - '###'
  - 总结
- - '#'
  - 2. 初识 SwiftUI
- - '##'
  - 我们将要构建的内容
- - '##'
  - 组合用于显示书籍的视图
- - '##'
  - 使用静态数据构建视图
- - '##'
  - 使用预览确保视图按预期工作
- - '##'
  - 显示书籍列表
- - '##'
  - 设置数据绑定
- - '##'
  - 调整预览画布
- - '##'
  - 使代码可复用
- - '###'
  - 使用提取子视图重构代码
- - '###'
  - 重命名 ContentView
- - '###'
  - 控制复杂性
- - '##'
  - 视图与视图修饰符
- - '##'
  - 练习
- - '##'
  - 技巧与窍门
- - '##'
  - 总结
- - '#'
  - 3. SwiftUI 构建块
- - '##'
  - 视图
- - '###'
  - 用户界面视图
- - '####'
  - 文本输入与输出
- - '####'
  - 图片
- - '####'
  - 控件与指示器
- - '####'
  - 形状
- - '###'
  - 容器视图
- - '###'
  - 布局行为
- - '####'
  - 紧缩
- - '####'
  - 扩展
- - '##'
  - 视图只是 UI 的描述
- - '##'
  - 视图修饰符
- - '###'
  - 配置视图
- - '###'
  - 将视图修饰符应用于子视图
- - '###'
  - 使用视图修饰符注册操作处理程序
- - '##'
  - 总结
- - '#'
  - 4. 状态管理
- - '##'
  - 在 SwiftUI 中管理状态
- - '##'
  - 绑定值类型
- - '##'
  - 绑定对象
- - '##'
  - ObservableObject
- - '##'
  - '`@StateObject`'
- - '###'
  - 何时使用
- - '##'
  - '`@ObservedObject`'
- - '###'
  - 何时使用
- - '##'
  - '`@EnvironmentObject`'
- - '###'
  - 何时使用
- - '##'
  - 总结
- - '#'
  - 5. 在列表中显示数据
- - '##'
  - SwiftUI 中的列表入门
- - '###'
  - 在列表行内使用其他 SwiftUI 视图
- - '###'
  - 构建自定义列表行
- - '###'
  - 更复杂的列表行
- - '##'
  - 动态列表
- - '###'
  - 显示元素列表
- - '###'
  - 使用列表绑定以允许修改列表项
- - '###'
  - 异步获取数据
- - '###'
  - 下拉刷新
- - '###'
  - 搜索
- - '##'
  - 样式设计
- - '###'
  - 列表样式
- - '###'
  - 页眉与页脚
- - '###'
  - 列表单元格
- - '###'
  - 分隔符
- - '##'
  - 操作
- - '###'
  - 滑动删除
- - '###'
  - 使用编辑模式移动和删除项目
- - '###'
  - 滑动操作
- - '####'
  - 基本滑动操作
- - '####'
  - 指定边缘
- - '####'
  - 滑动操作与 onDelete
- - '####'
  - 添加更多滑动操作
- - '####'
  - 全滑动
- - '####'
  - 美化滑动操作样式
- - '##'
  - 管理列表中的焦点
- - '###'
  - 如何在 SwiftUI 中管理焦点
- - '###'
  - 如何在列表中管理焦点
- - '###'
  - 处理回车键
- - '###'
  - MVVM 模式呢？
- - '###'
  - 消除空元素
- - '##'
  - 总结
- - '#'
  - 6. 构建输入表单
- - '##'
  - 构建简单表单
- - '###'
  - 排版后的内容
- - '##'
  - 在表单中显示数据
- - '###'
  - 使其可编辑
- - '##'
  - 钻取导航
- - '##'
  - 输入验证
- - '###'
  - 使用 `.onChange(of:)`
- - '###'
  - 使用 View Model 处理表单验证
- - '###'
  - 通过使用 `@Binding` 和 `@ObservableObject` 将本地数据源与全局数据源同步
- - '##'
  - 使用 Combine 执行表单验证
- - '##'
  - 总结
- - '#'
  - 第二部分
- - '#'
  - 7. 初识 Combine
- - '##'
  - 什么是函数式响应式编程？
- - '##'
  - 发布者
- - '##'
  - 订阅者
- - '##'
  - 运算符
- - '###'
  - 组合运算符
- - '##'
  - 组合发布者
- - '##'
  - 总结
- - '#'
  - 8. 使用 Combine 驱动 UI 状态
- - '##'
  - 使用 Combine 实现输入验证
- - '###'
  - 注册表单视图
- - '###'
  - 视图模型
- - '####'
  - 验证用户名
- - '####'
  - 显示验证消息
- - '####'
  - 将 Combine 管道封装在计算属性中
- - '####'
  - 密码验证
- - '####'
  - 综合应用
- - '###'
  - 练习
- - '##'
  - 总结
- - '#'
  - 9. 使用 Combine 进行网络请求
- - '##'
  - 使用 URLSession 获取数据
- - '###'
  - 使用 Combine 获取数据
- - '####'
  - 使用键路径解构元组
- - '####'
  - 映射数据
- - '####'
  - 使用 Combine 简化数据获取
- - '####'
  - 连接到 UI
- - '##'
  - 处理多线程
- - '##'
  - 优化网络访问
- - '###'
  - 查找根本原因
- - '###'
  - 使用 `share` 操作符共享发布者
- - '###'
  - 使用 `debounce` 进一步优化用户体验
- - '###'
  - 使用 `removeDuplicates` 避免重复发送相同请求
- - '##'
  - 整合所有内容
- - '##'
  - 练习
- - '##'
  - 总结
- - '#'
  - 10. Combine 中的错误处理
- - '##'
  - 错误处理策略
- - '###'
  - 忽略错误
- - '###'
  - 重试（带指数退避）
- - '###'
  - 显示错误消息
- - '###'
  - 使用错误视图替换整个界面
- - '###'
  - 显示内联错误消息
- - '##'
  - 典型错误条件及处理方法
- - '###'
  - 实现一个可能出错的网络 API
- - '###'
  - 调用 API 并处理错误
- - '###'
  - 处理设备/网络离线错误
- - '###'
  - 处理验证错误
- - '###'
  - 处理响应解析错误
- - '##'
  - 处理内部服务器错误
- - '##'
  - 改进错误处理与实现自定义 Combine 运算符
- - '###'
  - 重试策略中的暂停问题
- - '##'
  - 总结
- - '#'
  - 11. 实现自定义 Combine 运算符
- - '##'
  - 什么是 Combine 运算符？
- - '##'
  - 实现自定义操作符
- - '##'
  - 实现带延迟的重试操作符
- - '##'
  - 条件性重试
- - '##'
  - 实现指数退避的重试操作符
- - '##'
  - 总结
- - '#'
  - 12. 在 Combine 中封装现有 API
- - '##'
  - 案例研究
- - '##'
  - 使用 Combine 访问 Firestore
- - '###'
  - 使用视图模型与已发布属性
- - '###'
  - 使用 Combine 封装 API
- - '##'
  - 创建你自己的发布者
- - '###'
  - 使用 `PassthroughSubject` 封装快照监听器
- - '###'
  - 使用 `Future` 从 Firestore 实现一次性数据读取
- - '##'
  - 总结
- - '#'
  - 13. Combine 调度器与 SwiftUI
- - '##'
  - 什么是调度器
- - '###'
  - 调度器类型
- - '###'
  - 默认行为
- - '##'
  - 切换调度器
- - '###'
  - 使用`subscribe(on:)`控制上游发布者
- - '###'
  - 使用`receive(on:)`控制下游订阅者
- - '###'
  - 影响调度编排的其他操作符
- - '##'
  - 执行异步工作
- - '##'
  - 与其他 API 集成
- - '###'
  - URLSession
- - '###'
  - Firebase
- - '##'
  - 总结
- - '#'
  - 第三部分
- - '#'
  - 14. 开始使用 async/await
- - '##'
  - 在慢速资源上调用函数时，大多数情况下阻塞调用方是不可行的
- - '###'
  - 使用函数的同步编程
- - '###'
  - 使用闭包进行异步编程
- - '###'
  - 使用 async/await 进行异步编程
- - '####'
  - 定义与调用异步函数
- - '####'
  - 并行调用异步函数
- - '##'
  - 摘要
- - '#'
  - 15. 在 SwiftUI 中使用 `async/await`
- - '##'
  - 使用 `URLSession` 异步获取数据
- - '##'
  - 调用异步代码
- - '##'
  - 任务视图修饰符
- - '###'
  - 在用户点击按钮时调用异步代码
- - '###'
  - 使用下拉刷新异步更新视图
- - '###'
  - 可搜索视图与 async/await
- - '##'
  - 从主线程更新 UI
- - '##'
  - 总结
- - '#'
  - 16. 融会贯通：SwiftUI、async/await 和 Combine
- - '##'
  - 使用 Combine 获取数据
- - '##'
  - 使用 async/await 获取数据
- - '##'
  - 这是 Combine 的终结吗？
- - '###'
  - 连接 UI…
- - '###'
  - …到 Combine 管道
- - '###'
  - …到 async/await 方法
- - '###'
  - 从 Combine 调用异步代码
- - '##'
  - 总结
- - '##'
  - 索引
- - '###'
  - A
- - '###'
  - B
- - '###'
  - C
- - '###'
  - D
- - '###'
  - E
- - '###'
  - F
- - '###'
  - G
- - '###'
  - H
- - '###'
  - I, J, K
- - '###'
  - L
- - '###'
  - M
- - '###'
  - N
- - '###'
  - O
- - '###'
  - P, Q
- - '###'
  - R
- - '###'
  - S
- - '###'
  - T
- - '###'
  - U
- - '###'
  - V
- - '###'
  - W
- - '###'
  - X, Y, Z
