name: Pro Windows Embedded Compact 7
name_cn: Windows Embedded Compact 7 高级指南
slug: pro-windows-embedded-compact-7
toc:
- - '#'
  - Windows Embedded Compact 7 专业指南
- - '##'
  - 设备驱动开发
- - '##'
  - 目录速览
- - '##'
  - 第 4 章：掌握硬件环境
- - '###'
  - I/O 设备内存
- - '####'
  - 编程式 I/O（PIO）
- - '####'
  - 设备专用内存
- - '####'
  - 直接内存访问 – DMA
- - '#####'
  - 系统 DMA
- - '#####'
  - 总线主控 DMA
- - '###'
  - PCI 总线
- - '###'
  - 本章小结
- - '##'
  - 第 5 章：设备驱动程序注册表设置
- - '###'
  - 本章内容
- - '###'
  - 注册表概述
- - '####'
  - 注册表类型
- - '####'
  - 对象存储
- - '####'
  - 基于 RAM 的注册表
- - '####'
  - 基于配置单元的注册表
- - '####'
  - 小结
- - '###'
  - 设备驱动程序文件名
- - '####'
  - 设备文件命名空间 - 前缀和索引
- - '####'
  - 设备文件命名空间 – 挂载点
- - '###'
  - 加载序列
- - '####'
  - 流式设备驱动程序的加载序列
- - '###'
  - 设备管理器注册表键
- - '####'
  - 活动注册表键
- - '###'
  - 注册表条目
- - '####'
  - 必需项
- - '####'
  - 可选项
- - '####'
  - 用户模式驱动程序框架注册表设置
- - '###'
  - 创建设备驱动程序的注册表条目
- - '####'
  - 创建注册表设置文件
- - '###'
  - 本章小结
- - '##'
  - 第 6 章：理解设备驱动程序类型
- - '###'
  - 本章内容
- - '###'
  - 原生设备驱动程序
- - '###'
  - 流式设备驱动程序
- - '###'
  - 混合设备驱动程序
- - '###'
  - 单块式与分层式设备驱动程序
- - '###'
  - 设备接口类
- - '####'
  - 设备接口 GUID
- - '###'
  - 设备接口通知
- - '####'
  - 消息队列点对点通知
- - '####'
  - 通过 `WM_DEVICECHANGE` 进行的通知
- - '###'
  - 本章小结
- - '##'
  - 第 7 章：流式设备驱动的本质
- - '###'
  - 本章内容
- - '###'
  - 流式接口设备驱动程序
- - '####'
  - 流式接口设备驱动程序的结构
- - '###'
  - 内核模式设备驱动程序
- - '####'
  - 访问检查
- - '####'
  - 封送处理
- - '###'
  - 筛选器设备驱动程序
- - '###'
  - 用户模式设备驱动程序
- - '####'
  - 用户模式设备驱动程序的限制
- - '####'
  - 实现用户模式设备驱动程序
- - '####'
  - 加载和初始化用户模式设备驱动程序
- - '###'
  - 本章小结
- - '##'
  - 第 8 章：设备驱动程序的 I/O 与中断
- - '###'
  - 本章内容
- - '###'
  - 中断模型
- - '###'
  - 中断架构
- - '###'
  - 错误报告生成器
- - '###'
  - 错误报告传输驱动程序
- - '###'
  - 错误报告控制面板
- - '###'
  - 报告上传客户端
- - '###'
  - 小型转储与存储桶
- - '###'
  - 章节小结
- - '##'
  - 第 12 章：使用 CTK 开发测试代码
- - '###'
  - 本章要点
- - '###'
  - Windows Embedded Compact 测试工具包
- - '####'
  - 概述
- - '####'
  - 用户界面
- - '###'
  - 创建测试流程
- - '###'
  - 设计测试
- - '###'
  - 目录
- - '###'
  - TUX 测试框架
- - '####'
  - 实现 TUX 测试 DLL
- - '###'
  - 运行测试
- - '###'
  - 查看和分析测试结果
- - '###'
  - 性能测试
- - '###'
  - 添加第二个测试过程
- - '###'
  - 章节小结
- - '##'
  - 索引
- - '##'
  - 关于作者
- - '##'
  - 关于技术审校
- - '##'
  - 致谢
- - '##'
  - 引言
- - '#'
  - Windows Embedded Compact 设备驱动程序开发基础
- - '##'
  - 引言
- - '###'
  - 本书面向的读者
- - '##'
  - 第 1 章：Windows Embedded Compact 设备驱动程序开发基础
- - '###'
  - 嵌入式操作系统架构
- - '####'
  - 微内核架构
- - '#####'
  - 微内核架构与 Windows CE
- - '#####'
  - 微内核架构与时间关键型系统
- - '####'
  - 单体内核架构
- - '###'
  - 宏内核架构与 Windows CE
- - '####'
  - 宏内核架构中的用户模式与内核模式驱动
- - '###'
  - Windows CE 系统架构与 I/O 处理
- - '####'
  - 与设备驱动相关的系统组件
- - '###'
  - '`UDEVICE.EXE` – 用户模式进程'
- - '###'
  - Windows Embedded Compact 7 内存架构
- - '####'
  - 内核空间虚拟内存
- - '####'
  - 用户空间虚拟内存
- - '###'
  - 输入/输出处理
- - '####'
  - 中断处理
- - '####'
  - ISR 和 IST
- - '####'
  - 可安装 ISR 与中断共享
- - '###'
  - Windows Embedded Compact 设备驱动程序模型
- - '####'
  - 本机 Windows CE 设备驱动程序
- - '####'
  - Windows Embedded Compact 中的流接口设备驱动程序
- - '###'
  - 单体驱动与分层驱动
- - '###'
  - 内核模式或用户模式下的 Windows Embedded Compact 设备驱动程序
- - '####'
  - 内核模式设备驱动程序
- - '####'
  - 用户模式设备驱动程序
- - '###'
  - 加载和卸载设备驱动程序
- - '####'
  - 加载流接口设备驱动程序
- - '####'
  - Device Manager 架构
- - '####'
  - Device Manager 注册表项
- - '####'
  - 设备文件名称
- - '####'
  - 设备文件名称前缀
- - '####'
  - 设备文件名称索引
- - '####'
  - I/O 资源管理器
- - '###'
  - 章节摘要
- - '##'
  - 第 2 章：开发工具
- - '###'
  - 理解设备驱动程序的操作系统架构
- - '###'
  - 开发工具
- - '####'
  - Visual Studio 2008
- - '####'
  - Visual Studio 2008 与平台构建器 IDE
- - '####'
  - 远程工具
- - '####'
  - 远程工具框架
- - '###'
  - 框架及其安装到 Visual Studio 中
- - '###'
  - Platform Builder
- - '####'
  - Platform Builder 目录树
- - '####'
  - PLATFORM 目录
- - '####'
  - PUBLIC 目录
- - '###'
  - Platform Builder IDE
- - '###'
  - 平台构建器向导
- - '####'
  - Windows CE 操作系统设计向导
- - '####'
  - Windows CE 子项目向导
- - '###'
  - 平台构建器远程工具
- - '###'
  - 平台构建器注册表编辑器
- - '###'
  - 构建系统
- - '####'
  - 概述
- - '####'
  - 构建工具
- - '####'
  - 命令行构建
- - '####'
  - 理解 SYSGEN 过程
- - '####'
  - SYSGEN 过滤
- - '####'
  - 环境变量和 DEPTREES
- - '###'
  - 主构建工具
- - '####'
  - 如何准备开发环境
- - '####'
  - Build.exe
- - '####'
  - DIRS 文件
- - '####'
  - SOURCES 文件
- - '####'
  - SOURCES.CMN
- - '####'
  - 创建命令行构建批处理文件
- - '###'
  - 设备驱动程序开发包
- - '####'
  - CEDDK 动态链接库
- - '####'
  - 注册表辅助库
- - '###'
  - TRACE32-ICD
- - '####'
  - 概述
- - '####'
  - 如何准备您的 Trace 工具
- - '###'
  - 设备驱动程序向导
- - '####'
  - 概述
- - '####'
  - 最佳实践
- - '###'
  - 章节总结
- - '####'
  - 本章内容
- - '###'
  - 设备驱动程序位置
- - '####'
  - BSP
- - '####'
  - 特定操作系统设计
- - '####'
  - PUBLIC 树
- - '###'
  - 决定模式
- - '####'
  - 内核模式
- - '####'
  - 用户模式
- - '###'
  - 注册表
- - '###'
  - 设备驱动程序类型
- - '###'
  - 设备驱动程序特性
- - '###'
  - 直接内存访问
- - '###'
  - 中断支持
- - '###'
  - 电源管理支持
- - '###'
  - IO 控制代码
- - '###'
  - 设计物理设备驱动程序
- - '###'
  - 为测试而设计
- - '####'
  - 习惯上，这是开发中最容易被忽视的领域。
- - '###'
  - 章节总结
- - '##'
  - 第 4 章：掌握硬件环境
- - '###'
  - 引言
- - '###'
  - I/O 设备寄存器
- - '###'
  - 状态寄存器
- - '###'
  - 控制寄存器
- - '###'
  - 数据寄存器
- - '###'
  - I/O 端口寄存器
- - '###'
  - 内存映射寄存器
- - '###'
  - 访问寄存器
- - '###'
  - I/O 设备中断
- - '####'
  - 中断优先级
- - '####'
  - 中断向量
- - '####'
  - 信号机制
- - '###'
  - I/O 设备内存
- - '####'
  - 程序化 I/O（PIO）
- - '####'
  - 设备专用内存
- - '####'
  - 直接内存访问 – DMA
- - '#####'
  - 分散/聚集 DMA
- - '#####'
  - 系统 DMA
- - '#####'
  - 总线主控 DMA
- - '###'
  - PCI 总线
- - '###'
  - 章节总结
- - '##'
  - 第 5 章：设备驱动注册表设置
- - '###'
  - 注册表概述
- - '###'
  - 注册表类型
- - '###'
  - 对象存储
- - '####'
  - 存储机制
- - '####'
  - 基于 RAM 的注册表
- - '####'
  - 基于配置单元的注册表
- - '###'
  - 摘要
- - '###'
  - 设备驱动程序文件名
- - '####'
  - 设备文件命名空间——前缀与索引
- - '####'
  - 设备文件命名空间——挂载点
- - '###'
  - 加载顺序
- - '####'
  - 流设备驱动程序的加载顺序
- - '#####'
  - 操作系统启动时
- - '###'
  - 设备管理器注册表项
- - '####'
  - 活动注册表项
- - '###'
  - 注册表条目
- - '####'
  - 必需项
- - '####'
  - 可选项
- - '####'
  - 设备驱动程序注册表子项
- - '###'
  - 用户模式驱动程序框架注册表设置
- - '###'
  - 为设备驱动程序创建注册表项
- - '####'
  - 创建注册表设置文件
- - '####'
  - 使用注册表编辑器
- - '###'
  - 本章小结
- - '##'
  - 第 6 章：理解设备驱动程序类型
- - '###'
  - 本机设备驱动程序
- - '###'
  - 流设备驱动程序
- - '###'
  - 混合设备驱动程序
- - '###'
  - 单体式与分层式设备驱动程序
- - '###'
  - 设备接口类
- - '####'
  - 设备接口 GUID
- - '####'
  - IClass 注册表子项
- - '####'
  - 公布接口
- - '###'
  - 设备接口通知
- - '####'
  - 点到点消息队列通知
- - '####'
  - 通过 `WM_DEVICECHANGE` 通知
- - '###'
  - 章节总结
- - '##'
  - 第 7 章：流设备驱动程序的精髓
- - '###'
  - 本章内容
- - '###'
  - 流接口设备驱动程序
- - '####'
  - 流接口设备驱动程序的结构
- - '####'
  - 流接口入口点
- - '#####'
  - '`XXX_Cancel`'
- - '#####'
  - '`XXX_Close`'
- - '#####'
  - '`XXX_Deinit`'
- - '#####'
  - '`XXX_Init`'
- - '#####'
  - '`XXX_IOControl`'
- - '#####'
  - '`XXX_Open`'
- - '#####'
  - '`XXX_PowerDown`'
- - '#####'
  - '`XXX_PowerUp`'
- - '#####'
  - '`XXX_PreClose`'
- - '#####'
  - '`XXX_PreDeinit`'
- - '#####'
  - '`XXX_Read`'
- - '#####'
  - '`XXX_Write`'
- - '#####'
  - '`XXX_Seek`'
- - '###'
  - 设备上下文初始化
- - '###'
  - 关闭和反初始化设备驱动程序
- - '###'
  - 流接口设备驱动程序的加载
- - '###'
  - 异步 I/O 请求处理
- - '####'
  - 概述
- - '####'
  - 动机与实现说明
- - '####'
  - 实现异步 I/O 请求处理
- - '#####'
  - 清单 7-1\. 添加异步 I/O 处理支持
- - '###'
  - 内核模式设备驱动程序
- - '####'
  - 访问检查
- - '####'
  - 数据封送
- - '#####'
  - 同步与异步指针访问
- - '###'
  - 筛选设备驱动程序
- - '###'
  - 用户模式设备驱动程序
- - '####'
  - 用户模式设备驱动程序的限制
- - '####'
  - 实现用户模式设备驱动程序
- - '####'
  - 加载和初始化用户模式设备驱动程序
- - '###'
  - 章节总结
- - '##'
  - 第 8 章：设备驱动 I/O 与中断
- - '###'
  - 中断模型
- - '###'
  - 中断架构
- - '###'
  - 中断处理流程
- - '###'
  - 中断服务例程 - ISR
- - '###'
  - OAL 与中断处理
- - '####'
  - OEMIndicateIntSource 的实现
- - '###'
  - 可安装 ISR
- - '###'
  - 嵌套 ISR
- - '###'
  - 中断服务线程 (IST)
- - '###'
  - I/O 内存映射
- - '###'
  - 端口映射 I/O
- - '###'
  - 内存映射 I/O
- - '###'
  - 章节总结
- - '###'
  - 现代实时系统与中断处理
- - '##'
  - 第 9 章：设备 I/O 控制处理
- - '###'
  - 本章内容
- - '###'
  - 什么是 IOCTL
- - '####'
  - 设备类型 | 功能代码 | 请求 | 访问 | 方法
- - '#####'
  - 设备类型
- - '#####'
  - 内核 IOCTL
- - '###'
  - '`OEMIoControl`：必需函数'
- - '###'
  - '`g_oalIoCtlTable`：必需数组'
- - '###'
  - '`BSPIoCtlPostInit`：自定义函数'
- - '###'
  - 添加设备特定 IOCTL
- - '###'
  - 处理设备特定的 IOCTL
- - '###'
  - 电源管理支持
- - '###'
  - 章节总结
- - '##'
  - 第 10 章：网络驱动程序接口规范与网络设备驱动程序
- - '###'
  - 概述
- - '###'
  - NDIS
- - '###'
  - 网络设备驱动程序的层次
- - '####'
  - 物理层
- - '####'
  - 数据链路层
- - '####'
  - 网络层
- - '####'
  - 传输层
- - '###'
  - NDIS 微端口驱动程序
- - '####'
  - NDIS 微端口驱动程序函数
- - '#####'
  - '`DriverEntry`'
- - '#####'
  - '`MiniportSetOptions`'
- - '#####'
  - '`MiniportInitializeEx`'
- - '#####'
  - '`MiniportHaltEx`'
- - '#####'
  - '`MiniportDriverUnload`'
- - '#####'
  - '`MiniportPause`'
- - '#####'
  - '`MiniportRestart`'
- - '#####'
  - '`MiniportShutdownEx`'
- - '#####'
  - '`MiniportCheckForHangEx`'
- - '#####'
  - '`MiniportResetEx`'
- - '#####'
  - 物理数据传输
- - '####'
  - NDIS 内存管理辅助函数
- - '#####'
  - 共享内存
- - '#####'
  - 散聚 DMA
- - '###'
  - NDIS 协议驱动程序
- - '###'
  - NDIS 中间层驱动程序
- - '###'
  - 注册表设置
- - '###'
  - 章节总结
- - '##'
  - 第 11 章：调试设备驱动程序
- - '###'
  - 调试工具与技术概述
- - '###'
  - 调试技术
- - '####'
  - 调试工具
- - '###'
  - 简单高效的调试技术
- - '####'
  - 调试消息
- - '####'
  - 调试区域
- - '#####'
  - 调试区域宏
- - '#####'
  - 注册调试区域
- - '#####'
  - 更改调试区域
- - '###'
  - 内核调试器
- - '###'
  - CeDebugX
- - '###'
  - 硬件辅助调试
- - '###'
  - TRACE 32
- - '###'
  - 自动化调试过程
- - '###'
  - eXDI 概述
- - '###'
  - 目标控制
- - '###'
  - 创建调试扩展
- - '###'
  - 远程工具
- - '####'
  - 设备端实现
- - '####'
  - 桌面远程工具插件实现
- - '###'
  - 事后调试与 Dr. Watson
- - '####'
  - 错误报告生成器
- - '####'
  - 错误报告传输驱动程序
- - '####'
  - 错误报告控制面板
- - '####'
  - 报告上传客户端
- - '####'
  - 小型转储与存储桶
- - '###'
  - 章节总结
- - '##'
  - 第 12 章：使用 CTK 开发测试代码
- - '###'
  - 本章内容
- - '###'
  - Windows Embedded Compact 测试工具包
- - '####'
  - 概述
- - '####'
  - 用户界面
- - '#####'
  - CTK 使用的术语
- - '###'
  - 创建测试过程
- - '####'
  - 创建测试过程模板
- - '####'
  - 创建测试用例
- - '####'
  - 从模板创建测试过程
- - '####'
  - 为什么使用测试通行模板？
- - '###'
  - 设计测试
- - '###'
  - TUX 测试框架
- - '####'
  - 实现一个 TUX 测试 DLL
- - '###'
  - 运行测试
- - '###'
  - 查看和分析测试结果
- - '###'
  - 性能测试
- - '###'
  - 添加第二个测试过程
- - '###'
  - 章节总结
- - '##'
  - 索引
- - '###'
  - A
- - '###'
  - B
- - '####'
  - 构建系统
- - '###'
  - C
- - '####'
  - 命令行构建
- - '####'
  - 控制寄存器
- - '###'
  - D
- - '####'
  - DDK
- - '####'
  - 设备驱动程序向导
- - '####'
  - 设备管理器
- - '####'
  - 目录树
- - '###'
  - E
- - '###'
  - F
- - '###'
  - G
- - '###'
  - H
- - '###'
  - I
- - '####'
  - IDE
- - '####'
  - IClass 子项
- - '####'
  - 中断向量
- - '####'
  - I/O 设备寄存器
- - '###'
  - K
- - '###'
  - L
- - '####'
  - 加载与初始化，第 121–125 页
- - '###'
  - M
- - '###'
  - N
- - '###'
  - O
- - '###'
  - P
- - '####'
  - 平台构建器与开发工具
- - '#####'
  - 平台构建器工具
- - '####'
  - NDIS 协议函数
- - '###'
  - R
- - '####'
  - 注册表
- - '#####'
  - 设备驱动程序注册表
- - '#####'
  - 编辑器
- - '#####'
  - IClass 子项
- - '#####'
  - 注册表设置
- - '#####'
  - 注册表类型
- - '#####'
  - 注册表辅助库
- - '#####'
  - 注册表键
- - '####'
  - 远程工具
- - '#####'
  - 注册调试区域
- - '#####'
  - 报告与上传客户端
- - '####'
  - 寄存器
- - '#####'
  - I/O 设备寄存器
- - '####'
  - 基于 RAM 的注册表
- - '####'
  - 事务
- - '###'
  - S
- - '####'
  - 分散/聚集 DMA
- - '####'
  - 共享内存方案
- - '####'
  - 信号机制
- - '####'
  - SOURCES 文件
- - '####'
  - SYSGEN 过程
- - '###'
  - T
- - '####'
  - 目标控制服务
- - '####'
  - 测试通过模板
- - '####'
  - 测试用例
- - '####'
  - 测试
- - '####'
  - 测试项
- - '####'
  - TUX 测试工具
- - '####'
  - 流设备驱动程序
- - '####'
  - 流接口设备驱动程序
- - '####'
  - 子项
- - '####'
  - 系统 DMA
- - '####'
  - 线程化 Linux 测试工具
- - '####'
  - 时间关键系统
- - '####'
  - 流接口入口点
- - '####'
  - 状态寄存器
- - '###'
  - U
- - '####'
  - 上传客户端
- - '####'
  - 用户界面
- - '####'
  - 用户模式
- - '####'
  - 用户空间
- - '###'
  - V
- - '####'
  - 向量
- - '####'
  - Visual Studio 2008 工具
- - '#####'
  - Visual Studio 2008
- - '#####'
  - TRACE32 工具
- - '###'
  - W
- - '####'
  - WINCEROOT 变量
- - '####'
  - Windows CE
- - '####'
  - Windows Embedded Compact 7
- - '####'
  - 向导
- - '####'
  - '`WM_DEVICECHANGE` 消息'
- - '###'
  - X, Y, Z
- - '####'
  - XXX_Cancel 函数
- - '####'
  - XXX_Close 函数
- - '####'
  - XXX_Deinit 函数
- - '####'
  - XXX_Init 函数
- - '####'
  - XXX_IOControl 函数
- - '####'
  - XXX_Open 函数
- - '####'
  - XXX_PowerDown 函数
- - '####'
  - XXX_PowerUp 函数
- - '####'
  - XXX_PreClose 函数
- - '####'
  - XXX_PreDeinit 函数
- - '####'
  - XXX_Read 函数
- - '####'
  - XXX_Write 函数
- - '###'
  - 其他
- - '####'
  - PREfast 工具
- - '####'
  - 准备开发环境
- - '####'
  - 公共目录
- - '####'
  - 公共树
- - '####'
  - 异步 I/O 请求处理
- - '####'
  - 访问检查
