name: Apple MacOS and IOS System Administration
name_cn: 苹果 MacOS 和 IOS 系统管理
slug: apple-macos-and-ios-system-administration
toc:
- - '#'
  - 目录
- - '#'
  - 1. Apple 平台简介
- - '##'
  - 引言与概述
- - '###'
  - Apple 平台简史
- - '##'
  - macOS 简介
- - '###'
  - 硬件兼容性
- - '####'
  - Windows 管理员专业提示
- - '####'
  - 专业提示
- - '###'
  - macOS 用户界面
- - '##'
  - iOS 简介
- - '###'
  - iOS 用户界面
- - '##'
  - 总结
- - '#'
  - 2. macOS 客户端管理
- - '##'
  - Mac 硬件故障排除
- - '###'
  - 非易失性随机存取存储器
- - '###'
  - 系统管理控制器 (SMC)
- - '###'
  - 启动前键盘组合键
- - '##'
  - macOS 恢复
- - '###'
  - 磁盘工具
- - '###'
  - 时光机器备份
- - '##'
  - 文件系统与 macOS
- - '###'
  - 分层文件系统增强版（HFS+）
- - '###'
  - 苹果文件系统（APFS）
- - '###'
  - 分区方案与驱动器安全选项
- - '###'
  - APFS 快照
- - '##'
  - 安装与升级 macOS
- - '###'
  - 从互联网恢复安装
- - '###'
  - 创建可引导的 USB 安装盘
- - '###'
  - 创建可引导的技术员硬盘
- - '##'
  - 终端简介
- - '###'
  - 使用命令行界面导航
- - '###'
  - 命令手册
- - '###'
  - 提升权限
- - '###'
  - Shells
- - '###'
  - 常用命令
- - '###'
  - 启动磁盘
- - '###'
  - 共享
- - '###'
  - 用户与群组
- - '##'
  - 网络
- - '###'
  - 专业提示
- - '###'
  - Windows 管理员专业提示
- - '###'
  - 专业提示
- - '##'
  - 软件更新
- - '###'
  - 通过终端配置软件更新
- - '###'
  - 专业提示
- - '##'
  - 管理本地用户和群组
- - '###'
  - 创建新用户
- - '###'
  - 高级选项
- - '###'
  - 登录项
- - '###'
  - 用户模板
- - '##'
  - 高级访达技巧
- - '###'
  - Option 键修饰键
- - '##'
  - 目录结构
- - '###'
  - 应用程序捆绑包
- - '###'
  - 内核扩展
- - '###'
  - 额外系统实用工具
- - '####'
  - 钥匙串访问
- - '##'
  - 总结
- - '#'
  - 3. macOS 安全
- - '##'
  - Mac 硬件安全
- - '###'
  - 基本 EFI 启动安全
- - '###'
  - Apple T2 安全芯片
- - '##'
  - 文件权限
- - '###'
  - POSIX
- - '###'
  - 修改文件权限
- - '##'
  - 家长控制和屏幕使用时间
- - '##'
  - Gatekeeper
- - '##'
  - FileVault
- - '###'
  - FileVault 机构恢复密钥
- - '##'
  - 防火墙
- - '##'
  - 高级安全选项
- - '##'
  - 总结
- - '#'
  - 4. iOS 客户端管理
- - '##'
  - iOS 硬件支持
- - '###'
  - 强制重启
- - '###'
  - 电池健康
- - '##'
  - iOS 支持
- - '###'
  - iOS 重置
- - '###'
  - iOS 恢复模式
- - '##'
  - 设备固件更新模式
- - '##'
  - iOS 备份
- - '###'
  - 电脑备份
- - '###'
  - iCloud 备份
- - '###'
  - 从备份恢复
- - '##'
  - iOS 设备存储
- - '##'
  - iOS 辅助功能
- - '###'
  - 引导式访问
- - '##'
  - 网络设置
- - '###'
  - 无线局域网
- - '###'
  - 蜂窝网络
- - '####'
  - VPN
- - '##'
  - iOS 设备安全
- - '###'
  - 密码锁/Touch ID/Face ID
- - '###'
  - 隐私
- - '###'
  - 屏幕使用时间限制
- - '###'
  - 激活锁
- - '##'
  - 用户帐户
- - '##'
  - Apple ID
- - '##'
  - iCloud 账户
- - '##'
  - App Store 账户
- - '##'
  - iPadOS
- - '###'
  - 共享 iPad
- - '##'
  - 总结
- - '#'
  - 5. 使用 Apple Configurator 管理设备
- - '##'
  - 欢迎使用 Apple Configurator
- - '###'
  - Apple Configurator 用户界面
- - '##'
  - 组织与监督身份
- - '###'
  - 创建组织与监督身份
- - '####'
  - 专业提示
- - '##'
  - 在 Apple Configurator 中准备设备
- - '###'
  - 准备设备
- - '##'
  - 配置描述文件
- - '###'
  - 配置描述文件简介
- - '###'
  - 您的第一个配置描述文件
- - '##'
  - 创建用户可安装的配置描述文件
- - '###'
  - 开始创建
- - '###'
  - 配置通用负载
- - '###'
  - 添加并配置密码负载
- - '###'
  - 保存描述文件
- - '###'
  - 应用配置描述文件到设备
- - '###'
  - 场景对比：公司设备与 BYOD
- - '###'
  - 分发和安装描述文件
- - '##'
  - 探索 iOS 配置描述文件
- - '###'
  - 探索 iOS 配置描述文件
- - '##'
  - 使用 Apple Configurator 侧载应用和内容
- - '###'
  - 应用
- - '###'
  - 文档
- - '##'
  - 在 Apple Configurator 中修改 iOS 设备
- - '###'
  - 设备名称
- - '###'
  - 主屏幕布局
- - '###'
  - 墙纸
- - '##'
  - 使用蓝图配置 iOS 设备
- - '###'
  - 创建蓝图
- - '###'
  - 部署蓝图
- - '###'
  - 专家提示
- - '##'
  - 高级 Apple Configurator 工具
- - '###'
  - 单应用模式
- - '###'
  - iOS 设备控制台
- - '###'
  - 自动操作与终端命令
- - '###'
  - 设备信息导出
- - '###'
  - 清除密码
- - '###'
  - 恢复设备
- - '##'
  - 总结
- - '#'
  - 6. 使用 Apple 远程桌面管理 macOS 客户端
- - '##'
  - Apple Remote Desktop 简介
- - '###'
  - 安装 Apple Remote Desktop
- - '###'
  - 远程任务服务器
- - '###'
  - 服务器安装
- - '###'
  - 界面概览
- - '###'
  - 为 ARD 配置 macOS 客户端
- - '##'
  - 使用扫描器添加客户端
- - '##'
  - 在 ARD 控制台中组织客户端
- - '##'
  - Mac 远程支持
- - '###'
  - 观察模式
- - '###'
  - 控制模式
- - '###'
  - 幕帘模式
- - '###'
  - 聊天
- - '###'
  - 锁定屏幕
- - '##'
  - 客户端管理
- - '###'
  - 电源控制
- - '###'
  - 清倒废纸篓
- - '###'
  - 设置启动磁盘
- - '###'
  - 更改客户端设置
- - '##'
  - 资产管理及报告功能
- - '###'
  - 系统概览报告
- - '###'
  - 软件版本报告
- - '##'
  - 应用使用情况
- - '###'
  - 专业提示
- - '##'
  - 软件分发
- - '###'
  - 应用程序安装程序
- - '###'
  - 专业提示
- - '###'
  - 复制项目
- - '####'
  - 安装软件包
- - '####'
  - 运行 Unix 脚本
- - '####'
  - 专业提示
- - '##'
  - 总结
- - '#'
  - 7. macOS Server
- - '##'
  - macOS Server 简史
- - '###'
  - 服务
- - '##'
  - 硬件
- - '##'
  - macOS Server 简介
- - '###'
  - 我需要一台 Mac 服务器吗？
- - '##'
  - 部署 Mac 服务器
- - '###'
  - 硬件考量
- - '###'
  - 备份
- - '###'
  - 初始配置
- - '####'
  - 网络设置
- - '####'
  - 配置远程访问
- - '####'
  - 服务器安全考量
- - '##'
  - 配置基本服务器服务
- - '###'
  - 内容缓存
- - '###'
  - 文件共享
- - '##'
  - 打印机共享
- - '##'
  - Web 服务器
- - '##'
  - 配置 macOS Server 服务
- - '###'
  - 安装 macOS Server
- - '##'
  - 互联网可达性
- - '##'
  - macOS Server 中的目录域
- - '##'
  - 开放目录
- - '###'
  - 创建 Open Directory 主服务器
- - '###'
  - 完成 Open Directory 主服务器的初始配置
- - '###'
  - 创建网络用户和组
- - '###'
  - 绑定 macOS 客户端到 Open Directory
- - '##'
  - 证书
- - '###'
  - 回退 SSL 证书
- - '###'
  - 自签名证书
- - '###'
  - 管理证书
- - '###'
  - 受信任的证书
- - '####'
  - 专业提示
- - '##'
  - 描述文件管理器
- - '####'
  - 专业提示
- - '##'
  - 总结
- - '#'
  - 8. 移动设备管理
- - '##'
  - Apple MDM 入门
- - '##'
  - 设备注册计划 (DEP)
- - '##'
  - 批量购买计划 (VPP)
- - '##'
  - 监管与用户批准的 MDM
- - '###'
  - 设备监管
- - '###'
  - 用户批准的 MDM
- - '##'
  - Apple School Manager / Apple Business Manager
- - '###'
  - 配置 Apple 的管理门户
- - '##'
  - MDM 服务器集成
- - '###'
  - 配置描述文件管理器与 DEP
- - '##'
  - 管理 DEP 客户端
- - '##'
  - 托管式 Apple ID
- - '##'
  - 使用 VPP 兑换 App 和图书
- - '###'
  - 为描述文件管理器配置 VPP
- - '##'
  - 总结
- - '#'
  - 9. 描述文件管理器
- - '##'
  - 描述文件管理器简介
- - '###'
  - 描述文件管理器的用户界面
- - '###'
  - 注册设置
- - '##'
  - MDM 注册
- - '##'
  - 设备注册计划（DEP）与设置助手的集成
- - '###'
  - 使用 DEP 进行 MDM 注册
- - '####'
  - 专业提示
- - '###'
  - 我的设备门户
- - '##'
  - 为 BYOD 注册创建占位符设备
- - '##'
  - 移除设备
- - '##'
  - Apple Configurator
- - '###'
  - 在 Apple Configurator 中启用 MDM 注册
- - '###'
  - 手动安装或使用安装脚本
- - '##'
  - 使用注册配置文件添加设备
- - '###'
  - 专业提示
- - '##'
  - 使用 Profile Manager 管理 iOS
- - '###'
  - iOS 配置描述文件
- - '###'
  - iOS 远程管理
- - '##'
  - 使用配置文件管理器进行 macOS 管理
- - '###'
  - macOS 负载
- - '####'
  - 专业提示
- - '###'
  - macOS 远程管理
- - '##'
  - 使用 Profile Manager 进行软件分发
- - '###'
  - 托管式分发
- - '##'
  - 兑换应用程序
- - '##'
  - 应用分发
- - '##'
  - 摘要
- - '#'
  - 10. 使用 Munki 自动化部署 macOS 应用程序
- - '##'
  - 简介
- - '##'
  - 为 Munki 配置 Apache Web 服务器
- - '###'
  - 配置 Web 服务器
- - '###'
  - 修改 Unix 八进制文件权限
- - '###'
  - 为 Munki 创建网络文件共享
- - '##'
  - 配置 Munki 管理工作站
- - '###'
  - 安装 MunkiTools 和 MunkiAdmin
- - '###'
  - 在管理工作站上配置 Munki 客户端
- - '##'
  - Munki 组件
- - '##'
  - 导入 MunkiTools 软件包
- - '###'
  - 导入我们的第一个安装软件包
- - '##'
  - MunkiAdmin 简介
- - '##'
  - 将软件打包进 Munki
- - '##'
  - 将软件导入 Munki
- - '###'
  - 导入软件包
- - '###'
  - 应用程序包属性
- - '###'
  - 创建用于执行脚本的 Munki 包
- - '####'
  - 创建用于运行脚本的包
- - '##'
  - 使用 Munki 部署软件
- - '##'
  - 在客户端工作站上安装和配置 Munki
- - '###'
  - 使用 ARD 安装 Munkitools
- - '##'
  - 清单
- - '###'
  - 自定义清单
- - '####'
  - 专业提示
- - '###'
  - 管理软件中心
- - '###'
  - 目录
- - '###'
  - 卸载应用程序
- - '##'
  - 总结
- - '#'
  - 11. Microsoft 集成
- - '##'
  - Apple 与 Microsoft 集成简介
- - '###'
  - 我的 Microsoft 环境
- - '###'
  - Apple 用户所需的 Microsoft 服务
- - '##'
  - macOS 的 Active Directory 集成
- - '###'
  - 为 Mac 客户端准备域控制器
- - '###'
  - 将 Mac 添加到 Active Directory 域
- - '###'
  - 使用配置描述文件将 Mac 添加到 Active Directory
- - '###'
  - 使用脚本将 Mac 绑定到 Active Directory
- - '###'
  - 3. 管理员密码
- - '###'
  - 4. 域
- - '###'
  - 使用配置文件管理器模拟 Microsoft 组策略
- - '##'
  - Windows 打印机共享集成
- - '##'
  - Windows 文件共享集成
- - '###'
  - macOS 文件共享
- - '###'
  - iPadOS 文件共享
- - '##'
  - Microsoft Exchange 集成
- - '###'
  - 使用有效载荷变量配置 Microsoft Exchange 账户
- - '##'
  - Microsoft Office 365 应用程序与 OneDrive
- - '###'
  - 激活 Office 365 应用程序
- - '###'
  - 配置 OneDrive for Business
- - '##'
  - 将用户从 Windows 迁移到 macOS
- - '###'
  - 使用迁移助手
- - '###'
  - 将迁移后的数据归位
- - '##'
  - 总结
- - '#'
  - 12. iOS 设备的大规模部署
- - '##'
  - 引言
- - '##'
  - 规划您的部署
- - '###'
  - BYOD 场景
- - '##'
  - iPad 向远程销售团队的部署
- - '##'
  - 预期的支持需求
- - '##'
  - 为 BYOD 场景配置描述文件管理器
- - '##'
  - 为销售团队 iPad 场景配置 Profile Manager
- - '###'
  - 专业提示
- - '###'
  - 专业提示
- - '###'
  - 专业提示
- - '##'
  - 总结
- - '#'
  - 13. macOS 客户端的部署
- - '##'
  - 引言
- - '###'
  - 规划部署
- - '##'
  - 配置 Active Directory
- - '##'
  - 配置描述文件管理器
- - '###'
  - 使用 DEP 创建占位符
- - '###'
  - 设置设备名称
- - '###'
  - 创建设备组
- - '###'
  - 配置 MDM 注册
- - '###'
  - 配置描述文件设置
- - '##'
  - 配置应用程序
- - '###'
  - 分配 App Store 应用
- - '##'
  - 导入 Munki 软件包
- - '##'
  - 部署
- - '###'
  - 激活与 MDM 注册
- - '###'
  - 启用 Apple 远程桌面
- - '###'
  - 安装 MunkiTools
- - '####'
  - 最终用户登录
- - '##'
  - 后续步骤
- - '#'
  - 索引
- - '##'
  - A
- - '###'
  - 资产管理与报告
- - '##'
  - B
- - '##'
  - C
- - '##'
  - D
- - '##'
  - E
- - '##'
  - F
- - '##'
  - G
- - '##'
  - H
- - '##'
  - I, J
- - '###'
  - iOS 客户端管理
- - '##'
  - K
- - '##'
  - L
- - '##'
  - M
- - '###'
  - Mac 安全部署
- - '###'
  - Microsoft Group Policy
- - '###'
  - 移动设备管理
- - '###'
  - Munki
- - '###'
  - 我的设备门户
- - '##'
  - N
- - '##'
  - O
- - '##'
  - P, Q
- - '##'
  - R
- - '##'
  - S
- - '###'
  - 软件分发
- - '###'
  - 软件支持
- - '##'
  - T
- - '##'
  - U
- - '##'
  - V
- - '##'
  - W, X, Y, Z
