name: Migrating to iPhone and iPad for .NET Developers
name_cn: .NET 开发者的iPhone和iPad迁移指南
slug: migrating-to-iphone-and-ipad-for-net-developers
toc:
- - '#'
  - 面向 .NET 开发者的 iPhone 和 iPad 迁移指南
- - '#'
  - 目录
- - '#'
  - 关于作者
- - '#'
  - 关于技术审校
- - '#'
  - 引言
- - '#'
  - 第 1 章 准备工作：苹果平台与技术上的工具与开发
- - '##'
  - 注册成为 Apple 开发者
- - '##'
  - 应用开发注意事项
- - '###'
  - 通用开发原则
- - '###'
  - 第三方开发原则
- - '###'
  - 应用方法
- - '####'
  - Web 应用
- - '####'
  - 原生应用
- - '##'
  - Apple 平台与技术
- - '###'
  - Apple 术语与概念
- - '###'
  - 了解 iOS
- - '###'
  - 使用苹果组件进行应用程序开发
- - '####'
  - Xcode
- - '###'
  - iOS SDK
- - '###'
  - 第三方选项
- - '####'
  - Mono 家族
- - '#####'
  - Core Mono
- - '#####'
  - MonoTouch
- - '###'
  - MonoDevelop
- - '###'
  - DragonFire SDK
- - '###'
  - Appcelerator 的 Titanium Mobile
- - '##'
  - Marmalade SDK
- - '##'
  - Flash Professional Creative Studio 5
- - '##'
  - App Store 概述
- - '###'
  - 在 App Store 销售应用
- - '####'
  - 向 App Store 提交应用
- - '###'
  - 本章小结
- - '#'
  - 第 2 章 即刻上手：iOS SDK 开发速成课
- - '##'
  - 开始之前
- - '###'
  - 选择合适的机器
- - '###'
  - 选择 iOS SDK
- - '##'
  - Xcode 4 有哪些新功能？
- - '##'
  - Apple iOS 开发中心资源
- - '##'
  - 安装 Xcode 和 iOS SDK
- - '###'
  - 版本库管理器
- - '##'
  - Objective-C 入门
- - '###'
  - Objective-C 术语
- - '###'
  - 对象模型
- - '###'
  - 方括号和方法
- - '####'
  - 调用方法
- - '####'
  - 传递和检索
- - '###'
  - 命名约定
- - '####'
  - 导入
- - '####'
  - 类定义与实现
- - '####'
  - 空对象
- - '####'
  - 异常处理
- - '####'
  - 内存管理
- - '##'
  - 创建您的第一个 iPhone 应用程序
- - '###'
  - 创建项目
- - '###'
  - 探索项目与文件结构
- - '###'
  - 初始化你的应用程序
- - '###'
  - 创建你的用户界面
- - '####'
  - 使用 Interface Builder
- - '###'
  - 初始化视图
- - '###'
  - 使用自动引用计数
- - '####'
  - 为什么要使用它？
- - '####'
  - 启用 ARC
- - '####'
  - 迁移到 ARC
- - '####'
  - 使用 ARC 进行编程
- - '###'
  - 本章概要
- - '#'
  - 第 3 章 了解你的选项：使用第三方解决方案与 MonoTouch
- - '##'
  - 了解限制条件
- - '##'
  - 使用 Mono 与 MonoTouch 进行开发
- - '###'
  - 安装 Mono、MonoDevelop 与 MonoTouch
- - '##'
  - 安装 Mono
- - '##'
  - 安装 MonoDevelop
- - '##'
  - 安装 MonoTouch
- - '##'
  - 使用 MonoTouch 创建“Hello, World”应用
- - '##'
  - 使用 Appcelerator 的 Titanium Mobile
- - '###'
  - 安装 Titanium
- - '###'
  - 使用 Titanium 创建 Hello, World
- - '##'
  - 使用 Marmalade SDK
- - '###'
  - 安装 Marmalade
- - '###'
  - 使用 Marmalade 创建 Hello, World
- - '##'
  - 总结
- - '#'
  - 第 4 章 深入探讨：.NET、Objective-C 和 iOS SDK
- - '##'
  - 比较 iOS 设备的性能
- - '##'
  - iOS 应用设计
- - '###'
  - 设计考量
- - '###'
  - 设计模式
- - '##'
  - 深入探究应用程序的内部结构
- - '##'
  - 应用程序生命周期
- - '##'
  - 管理应用程序状态
- - '##'
  - 管理应用程序的行为
- - '###'
  - 处理方向变化
- - '####'
  - 应用程序内的文件与应用程序沙盒
- - '####'
  - 多任务处理
- - '##'
  - 比较 .NET Framework 与 iOS 及 iOS SDK
- - '###'
  - 用户界面服务
- - '###'
  - 应用服务
- - '####'
  - 媒体层
- - '###'
  - 核心服务
- - '##'
  - 运行时服务
- - '##'
  - Objective-C 入门，第二部分
- - '###'
  - 类声明
- - '##'
  - 方法声明
- - '##'
  - 属性
- - '##'
  - 字符串
- - '###'
  - 接口与协议
- - '###'
  - 委托
- - '##'
  - 注释
- - '##'
  - 比较 .NET 与 Xcode 工具
- - '##'
  - Xcode 4 入门
- - '###'
  - IDE 工作区及其编辑器
- - '####'
  - 代码补全和支持
- - '####'
  - 方案和方案编辑器
- - '####'
  - 项目编辑器
- - '###'
  - 检查器
- - '##'
  - 导航器
- - '##'
  - 视图
- - '##'
  - 使用其他 Xcode 工具
- - '###'
  - 静态分析
- - '###'
  - 代码片段
- - '##'
  - 总结
- - '#'
  - 第五章 开始行动：创建你的首个应用程序
- - '##'
  - 应用程序规划与设计过程
- - '###'
  - Apple iOS 设计资源
- - '####'
  - 其他设计资源
- - '###'
  - 规划与设计“月球着陆器”应用
- - '####'
  - 需求规格说明
- - '####'
  - “月球着陆器”应用设计
- - '#####'
  - 用户界面
- - '#####'
  - 游戏状态
- - '#####'
  - 其他游戏设计元素
- - '##'
  - 构建“月球着陆器”应用
- - '###'
  - 创建应用程序项目
- - '###'
  - 构建用户界面和流程逻辑
- - '###'
  - 在应用程序中实现导航
- - '##'
  - 构建核心游戏引擎并启用用户交互
- - '###'
  - 检查游戏视图头文件
- - '###'
  - 审视游戏视图的实现
- - '####'
  - 使用定时器触发核心事件
- - '###'
  - 自文档化代码
- - '####'
  - 使用常量
- - '###'
  - 使用枚举类型
- - '###'
  - 以编程方式初始化 XIB 资源
- - '####'
  - 手动绘制用户界面
- - '####'
  - 使用自定义方法
- - '###'
  - 使用模拟器测试你的应用
- - '###'
  - 总结
- - '#'
  - 第 6 章 提升技能：用动态用户界面增强你的应用
- - '##'
  - 理解平台与设备的限制条件
- - '###'
  - 屏幕尺寸与分辨率
- - '####'
  - 充分利用设备形态的示例应用
- - '####'
  - 点与像素的比较
- - '####'
  - 其他考虑因素
- - '###'
  - 支持设备方向
- - '###'
  - 处理设备方向
- - '##'
  - 应用类型及其关联的视图控制器
- - '###'
  - 基于实用工具的应用
- - '###'
  - 基于标签栏的应用
- - '###'
  - 基于导航的应用
- - '###'
  - 实现基于标签栏的应用
- - '###'
  - iPad 专用控制器概述
- - '####'
  - 弹出视图控制器
- - '####'
  - 分割视图控制器
- - '##'
  - 用户界面控件
- - '###'
  - 控件
- - '####'
  - 活动和进度指示器
- - '####'
  - 日期、时间和通用选择器
- - '####'
  - 详细信息展开按钮
- - '###'
  - 信息按钮
- - '###'
  - 页面指示器
- - '###'
  - 搜索栏
- - '###'
  - 开关
- - '###'
  - 分段控件
- - '###'
  - 常用控件
- - '##'
  - 导航栏和信息栏
- - '###'
  - 状态栏
- - '###'
  - 工具栏
- - '###'
  - 导航栏
- - '##'
  - 内容视图
- - '###'
  - 表格视图
- - '###'
  - 文本视图
- - '###'
  - 网页视图
- - '###'
  - 其他元素
- - '####'
  - 警告框
- - '####'
  - 操作表
- - '##'
  - Apple 的用户界面资源
- - '##'
  - 总结
- - '#'
  - 第 7 章：获取数据：存储和检索数据以及配置您的应用程序
- - '##'
  - 我们有哪些数据存储方案？
- - '###'
  - 使用沙盒提供基于文件系统的存储
- - '##'
  - 管理应用程序中的数据
- - '##'
  - 使用属性列表作为存储
- - '##'
  - 使用互联网存储数据
- - '###'
  - 使用 iOS 嵌入式数据库
- - '####'
  - iOS SDK 有哪些选项？
- - '####'
  - 创建或打开您的数据库
- - '####'
  - 在数据库中创建表
- - '##'
  - 向数据库写入数据
- - '##'
  - 从数据库读取数据
- - '###'
  - 连接到其他数据库
- - '##'
  - 创建高分示例
- - '###'
  - 创建持久化高分记录类
- - '###'
  - 测试高分榜类
- - '###'
  - 完成类
- - '###'
  - 将序列化示例与 .NET 进行比较
- - '##'
  - 总结
- - '#'
  - 第 8 章 扩展你的应用程序：使用库扩展你的 iOS 应用
- - '##'
  - 库概述
- - '###'
  - 什么是库？
- - '###'
  - 存在哪些类型的库？
- - '###'
  - 静态库
- - '###'
  - 动态库
- - '###'
  - iOS 库与 .NET 等效库的比较
- - '##'
  - 创建你自己的静态库
- - '###'
  - 使用 Xcode 4 创建静态库
- - '###'
  - 在 .NET 中创建程序集
- - '###'
  - Apple 开发者协议
- - '##'
  - 第三方库
- - '###'
  - 第三方库的分类
- - '###'
  - 有用的第三方库
- - '##'
  - 在其他地方寻找库
- - '##'
  - 总结
- - '#'
  - 第 9 章 发布：测试、部署和分发你的应用程序
- - '##'
  - 可用的测试功能
- - '###'
  - 单元测试
- - '####'
  - 定义你的测试方法
- - '###'
  - 单元测试
- - '###'
  - 集成测试
- - '###'
  - 测试驱动开发
- - '##'
  - 编写和运行你的单元测试
- - '##'
  - 使用 Xcode 4 调试器
- - '###'
  - 其他调试选项
- - '###'
  - 使用 `NSLog` 捕获诊断信息
- - '###'
  - 分析你的应用程序
- - '##'
  - 使用模拟器的调试功能
- - '###'
  - 更改设备
- - '###'
  - 更改 iOS 版本
- - '###'
  - 模拟动作
- - '###'
  - 触发低内存
- - '###'
  - 其他功能
- - '##'
  - 在真实设备上测试
- - '##'
  - 部署你的应用程序
- - '###'
  - 创建证书以签名你的应用程序
- - '###'
  - 注册你的设备
- - '###'
  - 使用配置门户入门
- - '###'
  - 构建并部署你的应用程序
- - '##'
  - 发布你的应用
- - '###'
  - 通过即席机制发布
- - '###'
  - 通过 App Store 发布
- - '####'
  - 准备提交应用到 App Store
- - '###'
  - 上传应用二进制文件
- - '###'
  - 其他资源
- - '##'
  - 总结
- - '#'
  - 第 10 章 拓展技能：高级特性
- - '##'
  - 使用全球定位系统
- - '###'
  - 定位服务概述
- - '###'
  - 实现基于位置的服务
- - '###'
  - 位置信息包含什么？
- - '##'
  - 使用相机
- - '###'
  - 相机基础
- - '##'
  - 编写一个相机示例应用
- - '###'
  - 使用相机胶卷
- - '##'
  - 使用加速计
- - '##'
  - 手势检测概述
- - '###'
  - 检测触摸事件
- - '###'
  - 检测滑动
- - '###'
  - 用你的代码支持多种设备
- - '##'
  - 最新动态与未来展望
- - '###'
  - iCloud
- - '###'
  - iOS 5
- - '####'
  - 通知中心
- - '####'
  - iMessage
- - '####'
  - 书报摊
- - '####'
  - 提醒事项
- - '####'
  - Twitter
- - '###'
  - 其他更新功能
- - '##'
  - 总结
- - '#'
  - 附录
- - '##'
  - 完成“月球着陆器”应用
- - '###'
  - 实现游戏物理引擎
- - '####'
  - 重力
- - '####'
  - 推力
- - '###'
  - 旋转
- - '###'
  - 启用用户交互
- - '###'
  - 捕捉游戏事件
- - '###'
  - 处理图形
- - '###'
  - 显示最高分
- - '###'
  - 资源
- - '###'
  - A
- - '###'
  - B
- - '###'
  - C
- - '###'
  - D
- - '###'
  - E
- - '###'
  - F
- - '###'
  - G
- - '###'
  - H
- - '###'
  - I
- - '###'
  - J
- - '###'
  - K
- - '###'
  - L
- - '###'
  - 库，207–221
- - '###'
  - Lunar Lander 应用，113–143，281–284
- - '###'
  - M
- - '###'
  - N
- - '###'
  - O
- - '###'
  - P
- - '###'
  - Q
- - '###'
  - R
- - '###'
  - S
- - '###'
  - Safari 浏览器，iOS 5 中更新的功能
- - '###'
  - 沙盒，使用基于文件系统的存储
- - '###'
  - '`scheduledTimerWithTimeInterval` 方法'
- - '###'
  - 模式驱动的对象
- - '###'
  - 方案，IDE 工作区
- - '###'
  - '`Score` 类'
- - '###'
  - 得分表
- - '###'
  - 屏幕，尺寸
- - '###'
  - SDK（软件开发工具包）
- - '###'
  - 搜索栏
- - '###'
  - '`SecondView`'
- - '###'
  - 安全性
- - '###'
  - 安全框架（`Security.framework`）
- - '###'
  - 分段控件
- - '###'
  - '`SELECT` 语句'
- - '###'
  - '`selector` 参数'
- - '###'
  - 自文档化代码
- - '###'
  - '`self.view` 属性'
- - '###'
  - 服务器数据库
- - '###'
  - '`setNeedsDisplay` 方法'
- - '###'
  - '`setter` 方法'
- - '###'
  - 短消息服务（SMS）
- - '###'
  - '`ShowDialog()` 方法'
- - '###'
  - 信号强度
- - '###'
  - 简单对象访问协议（SOAP）
- - '###'
  - 模拟器，模拟硬件键盘功能
- - '###'
  - 模拟器，使用调试
- - '###'
  - 尺寸检查器
- - '###'
  - 滑块（`UISlider`）
- - '###'
  - SMS（短消息服务）
- - '###'
  - SOAP（简单对象访问协议）
- - '###'
  - 软件开发工具包——*参见* SDK
- - '###'
  - '`Sort()` 方法'
- - '###'
  - '`sortArrayUsingSelector` 方法'
- - '###'
  - SourceForge 库
- - '###'
  - 分视图控制器
- - '###'
  - '`SplitContainer` 类'
- - '###'
  - '`sprintf()` 方法'
- - '###'
  - SQL 命令
- - '###'
  - SQL 语句
- - '###'
  - SQL（结构化查询语言）
- - '###'
  - SQLite 数据库
- - '###'
  - '`sqlite3_bind_text()` 方法'
- - '###'
  - '`sqlite3_prepare()` 方法'
- - '###'
  - '`sqlite3_step()` 方法'
- - '###'
  - '`sqlite_open()` 方法'
- - '###'
  - 方括号
- - '###'
  - 开始游戏按钮
- - '###'
  - 开始触摸事件
- - '###'
  - '`startAnimating` 方法'
- - '###'
  - '`startUpdatingLocation`'
- - '###'
  - 应用状态
- - '###'
  - 静态分析，在 XCode 中
- - '###'
  - 静态库
- - '###'
  - 静态链接库
- - '###'
  - 状态栏
- - '###'
  - '`StatusBar` 类'
- - '###'
  - '`STFail()` 方法'
- - '###'
  - '`stopUpdatingLocation`'
- - '###'
  - 存储
- - '###'
  - Store Kit（`StoreKit.framework`）
- - '###'
  - 字符串，在 Objective-C 中
- - '###'
  - 结构化查询语言（SQL）
- - '###'
  - '`Such` 类'
- - '###'
  - '`superinitWithCoder:aDecoder` 命令'
- - '###'
  - 轻扫，检测
- - '###'
  - 开关控件
- - '###'
  - 符号导航器
- - '###'
  - 合成
- - '###'
  - '`System.Collections.Generic.Dictionary` 类'
- - '###'
  - '`System.Date` 类'
- - '###'
  - '`System.Device.Location` 命名空间'
- - '###'
  - '`System.Diagnostics` 命名空间'
- - '###'
  - '`System.Runtime.Serialization.Formatters.Binary`'
- - '###'
  - 系统配置（`SystemsConfiguration.framework`）
- - '###'
  - '`System.String` 类'
- - '###'
  - '`System.Threading.Timer` 类'
- - '###'
  - T
- - '###'
  - 工具
- - '###'
  - U
- - '###'
  - V
- - '###'
  - W
- - '###'
  - X, Y, Z
