name: Foundation IPhone App Development
name_cn: iPhone 应用开发基础指南
slug: foundation-iphone-app-development
toc:
- - '#'
  - Foundation iPhone App Development
- - '##'
  - 内容速览
- - '#'
  - 第 1 天：Objective-C、Xcode 和 iOS SDK 基础工作
- - '##'
  - 第 1 章：设计和规划我们的应用
- - '###'
  - 应用创意
- - '###'
  - 添加与编辑生日
- - '###'
  - 从通讯录和 Facebook 导入生日
- - '###'
  - 笔记功能
- - '###'
  - 提醒通知
- - '###'
  - Facebook 社交集成与应用内营销
- - '###'
  - 竞争分析
- - '###'
  - App Store 标题
- - '###'
  - 图标设计
- - '###'
  - 用户界面设计
- - '####'
  - 视网膜显示屏、状态栏和 iPhone 5
- - '###'
  - 纸上原型：从设计开始
- - '###'
  - 应用设计逐一讲解
- - '####'
  - 主视图
- - '#####'
  - 生日详情视图
- - '#####'
  - 编辑生日与添加备忘：模态呈现
- - '#####'
  - 原生 Facebook 集成
- - '#####'
  - 设置视图
- - '####'
  - 导出设计图像资源
- - '###'
  - 一点额外帮助
- - '###'
  - 总结
- - '##'
  - 第 2 章：为开发配置我们的应用
- - '###'
  - 免费下载 Xcode
- - '###'
  - 注册成为苹果开发者
- - '###'
  - 加入 iOS 开发者计划
- - '###'
  - iOS 配置门户
- - '####'
  - 生成证书
- - '####'
  - 添加设备
- - '####'
  - 创建 App ID
- - '###'
  - 生成配置文件
- - '###'
  - Ad Hoc 分发
- - '###'
  - 总结
- - '##'
  - 第 3 章：设置我们的 Xcode 项目
- - '###'
  - 开始上手
- - '###'
  - 分解项目结构
- - '####'
  - 应用程序委托
- - '####'
  - Info.plist
- - '####'
  - 前缀头文件
- - '####'
  - Storyboard
- - '###'
  - Hello World
- - '###'
  - 设置应用方向与自动布局
- - '###'
  - 添加图标和启动屏幕
- - '###'
  - 在你的 iPhone 上运行应用
- - '###'
  - 总结
- - '##'
  - 第 4 章：Objective-C 和 Xcode：开发一个二十一点游戏
- - '###'
  - 游戏规则
- - '####'
  - 游戏玩法
- - '###'
  - 创建视图
- - '####'
  - 设置视图的背景颜色
- - '####'
  - 添加标签、图片和按钮
- - '####'
  - 输出口：连接视图
- - '####'
  - 操作：响应控件
- - '###'
  - Objective-C 基础
- - '###'
  - 理解头文件和源文件
- - '###'
  - 属性和实例变量 (iVars)
- - '###'
  - 创建私有类接口：类扩展
- - '###'
  - Arrays
- - '###'
  - Init、初始化器和指定初始化器（构造器）
- - '###'
  - 工厂方法/便捷方法
- - '###'
  - 开启/关闭多方向支持
- - '###'
  - 模型
- - '####'
  - 卡牌模型
- - '#####'
  - 子类化 NSObject
- - '#####'
  - 声明指针和基本类型
- - '#####'
  - 保留与释放，以及 ARC（自动引用计数）
- - '####'
  - 枚举器
- - '####'
  - 方法
- - '###'
  - 游戏模型
- - '###'
  - 我们的 MVC 黑杰克实现
- - '####'
  - 类方法
- - '####'
  - 洗牌：Objective-C 类别
- - '###'
  - 在我们的二十一点游戏中
- - '###'
  - 在类之间分发通知
- - '###'
  - 串联所有组件
- - '####'
  - 响应用户交互
- - '####'
  - 协议与委托模式
- - '###'
  - 本章小结
- - '#'
  - 第 2 天：Storyboard 绘制用户界面
- - '##'
  - 第 5 章：iPhone 应用导航、视图与视图控制器
- - '###'
  - 多视图应用
- - '###'
  - 掌握视图和视图控制器
- - '####'
  - 添加导航控制器
- - '####'
  - Storyboard 场景和根视图控制器
- - '####'
  - 通过 Segue 推入视图控制器
- - '###'
  - 创建视图控制器类
- - '###'
  - 视图与视图控制器的生命周期
- - '####'
  - viewDidLoad
- - '####'
  - 视图控制器初始化方法
- - '####'
  - dealloc
- - '###'
  - 导航视图控制器
- - '###'
  - 栏与栏按钮项
- - '####'
  - 导航栏
- - '####'
  - 工具栏
- - '###'
  - 展示模态视图控制器
- - '###'
  - 关闭模态视图控制器
- - '####'
  - 展开 Segue
- - '####'
  - 用代码关闭模态视图控制器
- - '###'
  - 子类化：创建核心视图控制器
- - '####'
  - 添加备注视图控制器
- - '####'
  - 翻转至设置视图
- - '###'
  - 总结
- - '####'
  - 一项挑战
- - '##'
  - 第 6 章：视图、控件、相机，开始行动！
- - '###'
  - 用户界面控件与组件
- - '###'
  - 编辑生日视图：日期选择器、开关和文本字段
- - '####'
  - 配置文本字段并响应文本变化
- - '#####'
  - 隐藏键盘
- - '#####'
  - 跟踪并响应文本变化
- - '#####'
  - 启用和禁用保存按钮
- - '####'
  - 捕获开关切换
- - '####'
  - 监控日期选择器更新
- - '###'
  - 多行文本视图（编辑笔记视图）
- - '####'
  - 显示文本控件和视图的键盘
- - '###'
  - 准备通知时间视图控制器
- - '####'
  - 多行居中标签
- - '###'
  - 使用日期选择器作为时间设置控件
- - '###'
  - 使用相机和相册增强用户界面交互
- - '###'
  - 手势识别器
- - '###'
  - 实现操作列表
- - '###'
  - UIImagePickerController：拍照与浏览照片库
- - '####'
  - 调整图像视图渲染
- - '###'
  - 总结
- - '#'
  - 第 3 天：处理数据
- - '##'
  - 第 7 章：表格视图、数组和字典——天哪！
- - '###'
  - 表格视图
- - '###'
  - 表格数据源与委托协议
- - '###'
  - 使用数组和 plist 文件填充表格视图
- - '###'
  - 使用 Segue 传递数据
- - '###'
  - 理解 Segue 标识符
- - '###'
  - 添加新生日
- - '####'
  - 编辑已有生日
- - '###'
  - 总结
- - '##'
  - 第 8 章：使用 Core Data 实现数据持久化
- - '###'
  - Core Data 简介
- - '###'
  - 创建 Core Data 应用程序
- - '###'
  - 持久化存储
- - '###'
  - 实体与托管对象
- - '###'
  - Core Data 模型文件
- - '####'
  - 初始化 Core Data 模型
- - '####'
  - 什么是托管对象上下文？
- - '####'
  - 添加、编辑、删除与保存实体
- - '#####'
  - 添加
- - '#####'
  - 编辑
- - '#####'
  - 删除
- - '#####'
  - 保存
- - '###'
  - 在生日提醒应用中实现 Core Data
- - '####'
  - 添加 Core Data 框架
- - '####'
  - 创建 Core Data 模型
- - '####'
  - 定义 Core Data 实体
- - '####'
  - 扩展实体
- - '####'
  - 初始化我们的 Core Data 模型
- - '####'
  - 使用 NSFetchedResultsController 将表格视图连接到结果集
- - '####'
  - 填充 Core Data 存储
- - '####'
  - 处理重复实体与同步（NSPredicate 与生日提醒优化）
- - '####'
  - 更新主视图控制器
- - '####'
  - 从字典过渡到实体
- - '#####'
  - 生日详情视图控制器
- - '#####'
  - 生日编辑视图控制器
- - '#####'
  - 创建图片缩略图
- - '#####'
  - 取消 Core Data 更改
- - '#####'
  - 返回主视图控制器
- - '####'
  - 保存笔记
- - '####'
  - 清理工作
- - '###'
  - 总结
- - '##'
  - 第 9 章：iOS 界面美化：让你的应用“秀色可餐”
- - '###'
  - 什么样的应用具有吸引力？
- - '###'
  - 开始制作皮肤！
- - '####'
  - 创建核心视图控制器
- - '####'
  - 自定义表格视图单元格
- - '####'
  - 表格视图单元格背景图像
- - '####'
  - 创建“样式表”
- - '####'
  - 自定义导航栏与工具栏外观
- - '####'
  - 外观 API：简洁而强大
- - '#####'
  - 容器的外观样式
- - '#####'
  - 将样式表应用到应用的其他部分
- - '######'
  - 样式化提醒时间视图
- - '######'
  - 样式化生日编辑视图
- - '######'
  - 样式化备注编辑视图
- - '######'
  - 创建并样式化生日详情视图
- - '####'
  - 滚动视图与可滚动内容
- - '####'
  - 计算文本大小
- - '####'
  - 制作按钮皮肤
- - '###'
  - 总结
- - '#'
  - 第 4 天：从通讯录和 Facebook 导入生日
- - '##'
  - 第 10 章：从通讯录导入生日
- - '###'
  - 增强空数据库状态下的主视图
- - '###'
  - 在 Storyboard 中标识视图控制器场景
- - '###'
  - 访问并过滤通讯录联系人
- - '####'
  - 通讯录数据隐私
- - '###'
  - 处理通讯录数据
- - '####'
  - 创建生日导入值对象
- - '###'
  - 将联系人照片和数据加载到表格视图中
- - '###'
  - 创建用于导入生日的多选表格视图
- - '###'
  - 将通讯录生日导入 Core Data 存储
- - '###'
  - 多任务应用中的 URL 方案与跨应用链接
- - '###'
  - 从数据存储中删除生日
- - '###'
  - 总结
- - '##'
  - 第 11 章：使用 Facebook 和 iOS 6 社交框架
- - '###'
  - 在 Facebook.com 上注册新应用
- - '###'
  - 创建 Facebook 导入视图控制器
- - '###'
  - 使用账户框架进行 Facebook 身份验证
- - '###'
  - 获取 Facebook 生日信息
- - '###'
  - 将 Facebook 好友加载到表格视图中
- - '###'
  - 将 Facebook 生日导入 Core Data 存储
- - '####'
  - 加载与显示远程图片
- - '###'
  - 在朋友的 Facebook 墙上发帖
- - '###'
  - 创建 Facebook 动态发布视图控制器
- - '###'
  - 总结
- - '##'
  - 第 12 章：设置与本地通知
- - '###'
  - 使用静态表格视图控制器
- - '###'
  - 修改静态表格视图分区的行
- - '###'
  - 从静态表格视图单元格创建 Segue 导航
- - '###'
  - 在 Storyboard 中将 BRSettingsViewController 分配给主设置视图控制器
- - '###'
  - 构建设置单例类
- - '####'
  - 用户默认设置：iOS 的 Cookies
- - '###'
  - 更新生日
- - '###'
  - 调度和触发提醒本地通知
- - '###'
  - 重置应用角标
- - '###'
  - 总结
- - '#'
  - 第 5 天：最终润色
- - '##'
  - 第 13 章：发布前：提高在 App Store 成功的机会
- - '###'
  - 获取更多 5 星 App Store 评分
- - '###'
  - 配置 Appirater
- - '###'
  - 在 Facebook、Twitter 和邮件上分享
- - '###'
  - 使用 UIActivityViewController 实现五分钟分享集成
- - '####'
  - 使用 SLComposeViewController 在 Facebook 上分享
- - '####'
  - 使用 SLComposeViewController 在 Twitter 上分享
- - '####'
  - 使用 MFMailComposeViewController 发送电子邮件
- - '####'
  - 使用 MFMessageComposeViewController 发送短信
- - '###'
  - 摘要
- - '##'
  - 第 14 章：提交我们的应用
- - '###'
  - 使用 iTunes Connect 创建新的应用提交
- - '####'
  - 设置默认语言
- - '####'
  - 输入应用名称
- - '####'
  - 输入 SKU 编号
- - '####'
  - 关联 Bundle Identifier
- - '###'
  - 安排应用的上架时间和定价
- - '####'
  - 延迟应用发布
- - '####'
  - 为你的应用定价
- - '####'
  - 将应用限制在特定国家/地区销售
- - '###'
  - 配置版本信息
- - '####'
  - 选择 App Store 类别
- - '###'
  - 设置应用评级
- - '###'
  - 添加描述和元数据
- - '####'
  - 添加关键词
- - '###'
  - 上传截图和 iTunes 作品图
- - '###'
  - 应用程序名称已锁定，并且我们获得了 iTunes 应用程序 ID
- - '###'
  - 准备应用程序以提交至 App Store
- - '###'
  - 创建项目的归档构建
- - '###'
  - 签名并上传构建版本
- - '###'
  - 但如果我在待审核的应用中发现了一个 Bug 怎么办？
- - '###'
  - 总结
- - '##'
  - 索引
- - '###'
  - A
- - '###'
  - B
- - '###'
  - C
- - '###'
  - D, E
- - '###'
  - F
- - '###'
  - G
- - '###'
  - H
- - '###'
  - I, J, K, L
- - '###'
  - M
- - '###'
  - N
- - '###'
  - O
- - '###'
  - P, Q
- - '###'
  - R
- - '###'
  - S
- - '###'
  - T
- - '###'
  - U
- - '###'
  - V, W
- - '###'
  - X, Y, Z
- - '##'
  - 关于作者
- - '##'
  - 关于技术审校
- - '##'
  - 关于封面图片作者
- - '##'
  - 引言
- - '####'
  - 谁应该购买这本书
- - '####'
  - 这本书将教你什么
- - '####'
  - 这本书不会教你什么
