name: Troubleshooting Xcode
name_cn: Xcode 故障排除指南
slug: troubleshooting-xcode
toc:
- - '#'
  - Xcode 故障排除指南
- - '##'
  - 前言
- - '##'
  - 内容概览
- - '##'
  - 关于作者与关于技术审阅者
- - '###'
  - 关于作者
- - '###'
  - 关于技术审阅者
- - '#'
  - Xcode 故障排除
- - '##'
  - 反击
- - '##'
  - 打开项目文件时 Xcode 崩溃？
- - '###'
  - 如果你没有使用 CocoaPods
- - '###'
  - 如果你正在使用 CocoaPods
- - '##'
  - 用于签署可执行文件的身份无效
- - '##'
  - Xcode 编译失败并报错“SBPartialInfo”
- - '###'
  - NSLayoutConstraint 问题
- - '###'
  - Info.plist 路径不正确
- - '###'
  - '`Info.plist` 不得分配给任何目标'
- - '##'
  - 未找到匹配的描述文件
- - '###'
  - 缺失描述文件
- - '##'
  - 比 Photoshop 更好的图片压缩
- - '##'
  - 为 App 内购买创建包
- - '###'
  - 提供内容
- - '###'
  - 什么是包？
- - '####'
  - '`ContentInfo.plist`'
- - '####'
  - '`Contents` 文件夹'
- - '###'
  - 创建包：更快的方法
- - '###'
  - 创建最终的包
- - '#'
  - 将编译时间减少高达 75%
- - '#'
  - Objective-C 中不可能的“常量”
- - '##'
  - Constants.h
- - '##'
  - Constants.m
- - '#'
  - Core Data 的并发处理
- - '##'
  - 代码实现
- - '###'
  - Swift
- - '###'
  - Objective-C
- - '#'
  - 从终端创建图标
- - '#'
  - 为 iOS 应用创建图标
- - '##'
  - 为 OS X 应用创建图标
- - '##'
  - 使用脚本
- - '##'
  - UINavigationBar 色调不生效
- - '###'
  - Swift
- - '###'
  - Objective-C
- - '##'
  - 调试极其棘手的 Quartz 错误
- - '###'
  - 还有希望...
- - '##'
  - 并发向数组添加对象
- - '###'
  - Objective-C
- - '###'
  - 老式 C 语言方法
- - '###'
  - 回到未来
- - '##'
  - 应用已损坏，无法打开
- - '###'
  - 情况
- - '###'
  - 众神想要惩罚你
- - '###'
  - 应用无法获取收据
- - '###'
  - 不同目标中存在同名类
- - '####'
  - 这是你所期望的...
- - '####'
  - 且慢！
- - '###'
  - 反对基础国际化的案例
- - '####'
  - 界面元素的本地化
- - '####'
  - UIBarButtonItem 及其他元素的本地化失败
- - '###'
  - 检查缺失的 Localizable.strings
- - '###'
  - 你错误地声明了你的 NSString
- - '##'
  - Objective-C
- - '##'
  - 'CocoaPods: /Manifest.lock: 没有那个文件或目录'
- - '##'
  - Asset Catalogs 错误
- - '###'
  - 错误表现
- - '###'
  - 解决方案
- - '##'
  - 应用崩溃且无任何线索？
- - '###'
  - Objective-C
- - '##'
  - 沙盒应用的 NSUserDefaults 失效？
- - '##'
  - 界面元素不更新？
- - '###'
  - Swift
- - '###'
  - Objective-C
- - '##'
  - 使用正则表达式查找和替换字符串
- - '###'
  - Swift
- - '###'
  - Objective-C
- - '###'
  - Swift
- - '###'
  - Objective-C
- - '###'
  - 使用正则表达式
- - '####'
  - “查找”字段
- - '#####'
  - 说明：
- - '####'
  - “替换”字段
- - '####'
  - 说明
- - '####'
  - 但有一个问题...
- - '##'
  - 从数组中提取字典
- - '###'
  - 'Swift: NSArray'
- - '###'
  - Swift 变体...
- - '###'
  - Objective-C
- - '##'
  - 计算数组中元素数量的神奇方法
- - '###'
  - Swift
- - '###'
  - Objective-C
- - '###'
  - 'Swift: NSArray'
- - '###'
  - Swift 变体...
- - '###'
  - Objective-C
- - '##'
  - OS X 应用未以正确尺寸启动
- - '##'
  - 检测正在运行的应用目标
- - '###'
  - Swift
- - '###'
  - Objective-C
- - '##'
  - 禁用类上的方法
- - '###'
  - Swift
- - '###'
  - Objective-C
- - '##'
  - 弃用类中的某个方法
- - '###'
  - Swift
- - '###'
  - Objective-C
- - '##'
  - Xcode 出现“沙滩球”现象
- - '##'
  - UIButton 未变灰
- - '###'
  - Swift
- - '###'
  - Objective-C
- - '###'
  - Swift
- - '###'
  - Objective-C
- - '##'
  - 捕获内存损坏
- - '###'
  - Sanitizer（地址清理器）
- - '##'
  - SpriteKit 在 didBeginContact 时崩溃
- - '###'
  - Swift
- - '###'
  - Objective-C
- - '##'
  - SpriteKit 对象不遵守边界？
- - '##'
  - 关于 Cocoa 应用使用 Storyboard 的反例
- - '###'
  - Swift
- - '###'
  - Objective-C
- - '##'
  - 支持独立圆角的 UIView 类
- - '###'
  - Swift
- - '###'
  - Objective-C
- - '##'
  - 让 NSViews 与 UIViews 兼容
- - '###'
  - Swift
- - '###'
  - Objective-C
- - '##'
  - 检测 UIPickerView 何时停止滚动
- - '###'
  - Swift
- - '###'
  - Objective-C
- - '##'
  - “疯狂”的 NSDates
- - '###'
  - Swift
- - '###'
  - Objective-C
- - '###'
  - Swift
- - '###'
  - Objective-C
- - '##'
  - 本地化应用名称
- - '##'
  - 使用 Auto Layout 水平居中视图
- - '###'
  - 示例
- - '###'
  - 哎呀……坏主意
- - '###'
  - 什么？！
- - '###'
  - 逻辑已退出房间
- - '###'
  - 这样就能击败这个“怪兽”
- - '##'
  - 复制后 Storyboard 中的元素变灰
- - '##'
  - 调试 Core Data
- - '###'
  - 在黑暗中独行
- - '##'
  - 包中不包含 Info.plist
- - '##'
  - 检查 App Store 中应用的版本
- - '###'
  - Swift
- - '###'
  - Objective-C
- - '##'
  - 断点和 NSLog 不工作
- - '###'
  - 项目损坏
- - '###'
  - 错误的 Product Scheme
- - '##'
  - ViewControllers 之间切换缓慢
- - '###'
  - Swift
- - '###'
  - Objective-C
- - '#'
  - 完成运行问题
- - '##'
  - 我们曾警告过你将受到的惩罚
- - '##'
  - iOS 与 Mac 之间的 Handoff 堵塞
- - '###'
  - 在你的 iOS 设备上
- - '###'
  - 在你的 Mac 上
- - '###'
  - 在 Mac OS X 上
- - '###'
  - 在你的项目中
- - '##'
  - 顽固的应用通用容器
- - '###'
  - 验证以下内容
- - '###'
  - 秘密“咒语”在此……
- - '###'
  - 在哪里可以查看文件……
- - '####'
  - Swift
- - '####'
  - Objective-C
- - '##'
  - 实用技巧
- - '###'
  - CocoaPods
- - '###'
  - GitHub
- - '###'
  - StackOverflow
- - '###'
  - fastlane 工具
- - '###'
  - HandBrake
- - '###'
  - Alcatraz
- - '#'
  - 附录
- - '##'
  - A
- - '##'
  - B
- - '##'
  - C
- - '##'
  - D
- - '##'
  - E
- - '##'
  - F
- - '##'
  - G
- - '##'
  - H
- - '##'
  - I, J, K, L
- - '##'
  - M
- - '##'
  - N
- - '##'
  - O
- - '##'
  - P, Q
- - '##'
  - R
- - '##'
  - S
- - '##'
  - T
- - '##'
  - U
- - '##'
  - V, W, X, Y, Z
